### ISSUE TITLE
[RFC] `shadow_update()` and `shadow_update_fixed()` functions for States

### ISSUE THREAD

**Issue by Telzhaak** [amethyst/amethyst#1005]
# Internal functionality of [`amethyst/src/state.rs`](https://github.com/amethyst/amethyst/blob/master/src/state.rs)
## Summary
Two update functions for `State`, which also run when a different State is pushed on top of it. See PR #1006 
## Background
For my game I decided to not create a monolithic `IngameState`, nor a monolithic `CustomGameData` struct.

Instead I created an `IngameBaseState`, holding a Dispatcher and dispatching its systems itself. This state stays on the stack until the player closes the game or returns to the MainMenu, and is responsible for the gaming-part where the player can move around, dig holes, etc. 
When the player opens his/her inventory, an `InventoryState` gets pushed onto the stack, with its own dispatcher that does not dispatch e.g. the `Gravity- ` or `MovementSystem`, which the `IngameBaseState` did. 
Since the `IngameBaseState`'s `update()` is not called anymore, this leads to the player not moving, which is the wanted outcome.

## Problem
The problem is, that the `IngameBaseState`'s own Dispatcher also dispatched a `TotalPlaytimeSystem`, which also isn't dispatched anymore, therefore not counting time spent in the inventory or shops as playtime.
It would be possible to make the `TotalPlaytime` a `Resource` instead of it being a member of the  `TotalPlaytimeSystem`. Then the `InventoryState`'s Dispatcher could dispatch the system again, therefore keeping track of time spent in the inventory (with some errors due to setting up the system and dispatcher and other stuff).

## Idea
Another possibility, however, would be to give states the ability, to keep certain routines running, independent of whether or not it is the current state. This could be done with seperate `shadow_update()`, or `background_update()` functions, that have no return value, or a Result return value. They may be called in the [`StateMachine.update()`](https://github.com/amethyst/amethyst/blob/master/src/state.rs#L330) function. FOr my example the `IngameBaseState` would then have 2 Dispatchers, one for the normal `update()`, and one for the `shadow_update()`.

## Pseudo-Code
Currently:
```rust
/// Updates the currently active state immediately.
pub fn update(&mut self, data: StateData<T>) {
    let StateData { world, data } = data;
    if self.running {
        let trans = match self.state_stack.last_mut() {
            Some(state) => state.update(StateData { world, data }),
            None => Trans::None,
        };

        self.transition(trans, StateData { world, data });
    }
}
```
could be turned into:
```rust
/// Updates the currently active state immediately,
/// and invokes the `shadow_update()` function of every state on the stack.
pub fn update(&mut self, data: StateData<T>) {
    let StateData { world, data } = data;
    if self.running {
        let trans = match self.state_stack.last_mut() {
            Some(state) => state.update(StateData { world, data }),
            None => Trans::None,
        };
        for state in self.state_stack.iter_mut() {
            state.shadow_update(StateData {world, data});
        }
        self.transition(trans, StateData { world, data });
    }
}
```
## Assuming this would be implemented
Should the `shadow_update()` be called for the active state, too?
### While we're at it
How about different `State` traits for States on which another State __can__ be `pushed`, like `TransitStates`.
And another trait for states that can only be `popped` or `switched` from, like `EndState`.

**Comment by jojolepro** [comment]
This is really interesting and I think it makes a lot of sense to have something like this.

>Should the shadow_update() be called for the active state, too?
yes

As for the last point with Trans limitations, I'm not really a fan of it.

**Comment by Telzhaak** [comment]
PR #1006 has been merged
