### ISSUE TITLE
Add Windows testing platform to Travis

### ISSUE THREAD

**Issue by ebkalderon** [amethyst/amethyst#1018]
Since we [dropped AppVeyor for Windows testing](amethyst/amethyst#839) a while back, we haven't had any test coverage for Windows builds of Amethyst. However, as of a day ago, Travis CI has officially rolled out native Windows support with the Rust toolchain available from the get-go ([relevant blog post](https://blog.travis-ci.com/2018-10-11-windows-early-release?utm_source=reddit&utm_medium=web&utm_campaign=windows_early_release)). I think that we should enable this to avoid regressions on all supported platforms.

The new `windows` environment in Travis uses Bash for scripting, meaning our existing CI scripts should run fine without modifications, in theory. It also exposes [Chocolatey](https://chocolatey.org/) for package management, should we need to install any native dependencies. Some packages like `curl` and `cmake` are pre-installed and don't need to be explicitly fetched ([complete list of pre-installed packages](https://docs.travis-ci.com/user/reference/windows#pre-installed-packages)).

**Comment by Moxinilian** [comment]
Considering Travis can still not support proper caches for projects with build artifacts as big as Amethyst, @magnonellie are still working on the alternative CI setup.
Depending on the state of that project, adding and testing Windows support to Travis might not be necessary.

**Comment by torkleyy** [comment]
Well, currently the caches lead to problems with the book testing.. which
is not Travis' fault. Caches are a bit dangerous because things can behave
differently without them (-> no really clean environment).
