### ISSUE TITLE
Managing graphics settings & applying changes

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1019]
We need some way to change filtering settings for multiple textures (or at least the anisatropic level). I think it would be best if textures wouldn't all contain different samplers, but instead refer to a bunch of samplers that are stored globally and can be configured accordingly (as pointed out by @Rhuagh, you'll want to set filtering independently for particles and standard objects).

This issue is the result of a discussion around #981.

**Comment by jojolepro** [comment]
You can use WindowMessages
https://www.amethyst.rs/doc/master/doc/amethyst_renderer/struct.WindowMessages.html

**Comment by Telzhaak** [comment]
The question is: Does that change the window size, or only the rendered resolution while the window size stays the same?

Normally games allow you to use fullscreen mode window e.g. 1920x1080 while rendering lower resolutions like 1240x720. I'd like to set these two seperately

**Comment by jojolepro** [comment]
That is a good question! (to which I don't have the answer but would be interested to know and document)

**Comment by fhaynes** [comment]
Closing due to age and lack of activity
