### ISSUE TITLE
New changelog strategy

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1029]
Our changelog is producing a lot of conflicts, leading to a lot of rebasing fun.

We can

* enforce specific commit formats to generate changelogs from (higher barrier for contributors, not what I recommend)
* continue doing what we are doing
* go through the PRs ourselves and write the changelog
* create a tool using the GitHub API that creates the changelog interactively

The tool would be my favourite. It'll be as simple as

* go through every PR from the selection
* ask if it's an addition (a), change (c) or fix (f)
* ask for a description, default to PR title
* automatically create the link and add it to the log

**Comment by Rhuagh** [comment]
1 or 4

**Comment by jojolepro** [comment]
2 or 4

**Comment by Xaeroxe** [comment]
4

**Comment by Moxinilian** [comment]
4 all the way

**Comment by magnonellie** [comment]
So who's gonna build 4 then?

**Comment by LucioFranco** [comment]
4th first, 3rd second.

**Comment by torkleyy** [comment]
Me ;) That's why I assigned myself.

**Comment by torkleyy** [comment]
Update: I'm currently working on a new ECS API, so please feel free to take this while I'm working on that.

**Comment by erlend-sh** [comment]
There's a [whole bunch](https://github.com/search?utf8=%E2%9C%93&q=generate+changelog&type=Repositories) of prior art on this. [Quite a few of these generators in Rust as well](https://github.com/search?l=rust&q=changelog&type=Repositories).

[git-journal](https://github.com/saschagrunert/git-journal) by @saschagrunert and [clog-lib](https://github.com/clog-tool/clog-lib/) by @cburgdorf and @kbknapp both look they're worth a good look.

**Comment by magnonellie** [comment]
I'm not okay with it personally. For one I hate the angular commit style, but disregarding that, enforcing a commit message format raises the barrier to entry considerably which I don't think we can afford.

**Comment by azriel91** [comment]
I'd prefer not to enforce a commit format for the change log, because the granularity of commits tends to be really fine (small), and I'd read the changelog as a user facing "things that I'd want to know about".

I like what we're currently doing

**Comment by jojolepro** [comment]
I'm also against commit formats

**Comment by torkleyy** [comment]
Yeah, I'm also not a big fan of it...

**Comment by torkleyy** [comment]
This seems like a better fit for use: https://github.com/github-changelog-generator/github-changelog-generator

It generates Changelogs in the Keep a Changelog format (which we are using), and it doesn't require commit messages to be formatted in any way.

**Comment by LucioFranco** [comment]
@torkleyy I really like that! I think that may be the right path or something very similar!

**Comment by torkleyy** [comment]
From Discord:

Another option (if you still want user edited entries) is to create one file per entry and make a command that just merges them together

so e.g. `/changelog/0.11.0/add/new-foo-method.md` and `/changelog/0.11.0/changed/rendy-rewrite.md`

**Comment by torkleyy** [comment]
Wrote a tool for this: https://github.com/torkleyy/clmerge

**Comment by fhaynes** [comment]
Closing this due to age and lack of activity, and that the tool now exists, I think?
