### ISSUE TITLE
UI entities get drawn multiple times

### ISSUE THREAD

**Issue by Murk1108** [amethyst/amethyst#1041]
I noticed that the FPS in the UI examples on master is constantly decreasing and tracked it down to the `cached_draw_order.cache` in the UI render pass constantly growing with new entities (or maybe the same added multiple times?), resulting in the UI elements being drawn multiple times in an ever increasing number.

**Comment by Xaeroxe** [comment]
Good catch, thanks!

**Comment by Xaeroxe** [comment]
Suspect this may be related to https://github.com/amethyst/amethyst/pull/1001

but I'm not sure.

**Comment by jojolepro** [comment]
set as critical because it needs to be fixed before friday for the release

**Comment by Telzhaak** [comment]
@Xaeroxe The issue is actually much simpler ....
The anti-storage `&` should be a `|`, because it is only visible if it is neither in hidden nor hidden_prop.
Currently it's only treated as visible if it is not in (hidden AND hidden_prop)
```rust
let visible_cached = (&self.cached_draw_order.cached
                ^ (!&hidden_set & !&hidden_prop_set))
```
```rust
let visible_cached = (&self.cached_draw_order.cached
                ^ (!&hidden_set | !&hidden_prop_set))
```
