### ISSUE TITLE
Better reference / architectural overview of Amethyst

### ISSUE THREAD

**Issue by SamuelMoriarty** [amethyst/amethyst#1044]
Created at the suggestion of @Moxinilian 

Right now, there are three ways to dive into Amethys, in order of ascending complexity:
* The Amethyst introduction book
* The Amethyst docs
* The Amethyst source code

The book is a nice resource to get your feet wet with Amethyst and get a general idea of what's going on - however, it doesn't go in-depth on the inner working of Amethyst itself.

Docs are the next step, however, they generally do not include implementation detail and are not very well suited for understanding what's going on *inside* the engine, just what you can do with it.

Game development isn't easy, and sometimes you just want/need to dive into the guts of whatever you're working with, to provide an integration, to extend the engine, or just to learn how it all fits together under the hood.

For this purpose, some kind of architectural overview or a reference would go a long way, especially around the time when the engine is becoming more or less stabilized. In particular:
* An overview of all the systems in amethyst and their respective crates and how they all interact.
* An overview of each system's implementation and structure. This doesn't have to be super-detailed, but it should provide a general idea of where to look for things you are interested in, and mention important details that users who are interested in studying the code would find helpful.
* Reasoning behind how/why certain decisions in the engine came to be, what are the advantages and the drawbacks of the chosen approach, and if there are any plans for further improvement down the road.
* Give a rough idea of how complete each component is, so people looking to contribute have an easier time finding tasks for themselves, or maybe can even come up with their own (unlogged) improvements.

These are just my personal thoughts on what would make a great reference document, something that I personally would appreciate a lot, being a newcomer to the engine.

**Comment by jojolepro** [comment]
>so people looking to contribute have an easier time finding tasks for themselves

Check the github "good first issue" tag for issues.

**Comment by Moxinilian** [comment]
I think the point was that a "good first issue" is pointless if the thing is not very clear to newcomers.
I've seen "good first issues" that even myself wasn't exactly sure what needed to be done and how to tackle it.

**Comment by torkleyy** [comment]
@Moxinilian Yeah, that's why I said that "good first issue" is only applicable if the description is very detailed. If somebody tags an issue with it, they need to describe

1) what changes need to be made where
2) what references to use for the implementation
3) special things that need to be taken care of

**Comment by torkleyy** [comment]
Related: #500

**Comment by torkleyy** [comment]
Another useful resource (thank you @distransient!): https://www.divio.com/blog/documentation/

**Comment by erlend-sh** [comment]
Whoever picks this up might also find [these ponderings]() by @kvark useful. A good way to kickstart this architectural overview could be an exhaustive reply to that topic.

**Comment by fhaynes** [comment]
Closing this due to age and lack of activity. This is a large task that will need to broken up properly.
