### ISSUE TITLE
Recommending bundle that needs to be used in Error Message

### ISSUE THREAD

**Issue by linonetwo** [amethyst/amethyst#1050]
I'm learning amethyst and loading .ron files really tortured me.

It gives error likes
```
[ERROR][amethyst_assets::progress] error loading handle 0, PREFAB, with name /Users/linonetwo/Desktop/xxx/resources/ui/example.ron, caused by: 
Error(Asset("/Users/linonetwo/Desktop/xxx/resources/ui/example.ron"), State { next_error: Some(Error(Format("Ui"), State { next_error: Some(Error(Msg("Failed parsing Ron file"), 
State { next_error: Some(Parser(ExpectedStruct, Position { col: 43, line: 88 })), backtrace: None })), backtrace: None })), backtrace: None })
```

And I don't really know why line 88 fails this .ron file:
```rust
text: (
                        text: "Editable",
                        font: File("font/square.ttf", Ttf, ()),
                        font_size: 75.,
                        color: (0.2, 0.2, 1.0, 1.0),
                        align: MiddleRight, <- Line 88 col 43
                        editable: (
                            max_length: 12,
                        ),
                    )
```

I've struggle loaded the mesh, after getting lots of error, and sometimes without any error, I know that the cause is that I didn't use 
```rust
.with_bundle(TransformBundle::new())?
```
And the Error message just says some line was wrong in the .ron file. After massive trying could I know I should use this bundle, so `.ron` file could load properly. This dramatically increases the cost to learn amethyst.

**Comment by linonetwo** [comment]
OK, this may not be an issue after 0.9 released since most of my confuse comes from /examples, which use features comes from 0.9.
And there is no other way to learn components of amethyst.

**Comment by jojolepro** [comment]
Hmmm you can read the api docs? :D

**Comment by linonetwo** [comment]
I think learn from example is more interesting for noobs like me.

I didn't knew that /examples use the latest feature that only exists in github version, so I was confused.
After use github version instead of 0.8, examples works, and I successfully made my first demo quickly.
