### ISSUE TITLE
Use the Transform component for all examples

### ISSUE THREAD

**Issue by magnonellie** [amethyst/amethyst#1053]
The ability to only use the `Transform` component without `GlobalTransform` was introduced recently and to reduce confusion for new users, I think it would be a good idea to make all examples and the book refer only to `Transform` instead of a mixture between the two.

**Comment by distransient** [comment]
It would be good to try to paint `GlobalTransform` as a special-case component in say, an "advanced" section.

**Comment by torkleyy** [comment]
## Task

`GlobalTransform` is not required, it'll be computed using the `Transform` component. Fixing this issue is as easy as removing all the explicit additions of `Transform` from the examples.

**Comment by Rhuagh** [comment]
Remove all explicit `GlobalTransform` you mean?

**Comment by torkleyy** [comment]
Yeah, right, fixed.
