### ISSUE TITLE
[Blocking] waiting for file lock on build directory

### ISSUE THREAD

**Issue by DuckerMan** [amethyst/amethyst#1065]
Amethyst version : `0.9`

Rust vesion: `rustc 1.29.2 (17a9dc751 2018-10-05)`

When I enter `cargo build` I get message:

`Blocking waiting for file lock on build directory`

I tryed to:

- `cargo clean`

- Wait

- Drink 2 cups coffee

- Reinstall Rust

**Comment by Moxinilian** [comment]
That's probably an issue with your environment.
What IDE do you use? I noticed VSCode sometimes locks files for no reason, but it's very rare.

**Comment by LucioFranco** [comment]
Yup, this usually happens when you have some sort of syntax checker that is checking as you type. It will usually run `cargo check` and during that process, it locks down the build directory. It just means you need to wait for the `check` command to finish before you can run `cargo build`.

**Comment by DuckerMan** [comment]
@Moxinilian, I use Terminal =)

**Comment by DuckerMan** [comment]
@LucioFranco I wait for 30 minutes, nothing.

**Comment by DuckerMan** [comment]
I remove all from .cargo, and now everything is OK.
Thank you, I love this community

**Comment by LucioFranco** [comment]
@DuckerMan glad you figured it out 😄 , let us know if you have any other issues. plus we have a discord you can join and ask questions, you'll usually get a quicker response there.

**Comment by DuckerMan** [comment]
@LucioFranco Yeah, I already joined to discord
