### ISSUE TITLE
[Doc][Book] Concept chapter for the renderer

### ISSUE THREAD

**Issue by Telzhaak** [amethyst/amethyst#1080]
Since a lot of questions regarding the renderer pop up in the Discord, it might be worthwhile to add a chapter for it in the book, once the new renderer is there (some of the following might even be outdated by then).

#### This chapter should cover the most important things:

General Intel:
- Coordinate system convention:  `x`-right, `y`-up, `z`-to the user, `origin` in the lower-left corner
- `Pass`es: what are they, how do you use them, how do you create a custom one

for 2D: 
- `RenderBundle.with_sprite_sheet_processor().with_sprite_visibility_sorting()`
- `DrawSprite.with_transparency`
- (`SpriteRender` vs `SpriteSheet` vs `Sprite`) vs `Texture`

for 3D:
- `haven't used this yet, so I got no idea`

for Ui:
- `UiBundle`
- `DrawUi`

Various:
- `Materials`
- `Textures`

#### Please tell me if something is missing that should DEFINITELY be in such a chapter

**Comment by jojolepro** [comment]
Also currently the renderer doesn't support opengl software renderer (no VM, no laptops with only integrated old graphics). Might be worthwhile to add if rendy doesn't support that either. (Please at least support virtual machines)

**Comment by fhaynes** [comment]
Closing this due to age. This will be handled in the documentation update for WASM funded by the Mozilla grant, with work scheduled to begin on May 1st
