### ISSUE TITLE
Windows: amethyst::ui::get_default_font isn't implemented for Path cases yet

### ISSUE THREAD

**Issue by DoumanAsh** [amethyst/amethyst#1084]
Currently when you try to use [get_default_font](https://www.amethyst.rs/doc/master/doc/amethyst_ui/fn.get_default_font.html) on Windows(presumably on Linux too?) you get [panic](https://github.com/amethyst/amethyst/blob/master/amethyst_ui/src/font/default.rs#L13-L15)

It could be nice maybe at least fallback to builtin font and print warning log?

If I understood `font-kit` sources correctly it will be always `Path` on windows https://github.com/pcwalton/font-kit/blob/master/src/sources/directwrite.rs#L79-L86
So essentially this API should not be available on windows as of now

**Comment by jojolepro** [comment]
# Task:
Implement the Path branch of the match here https://www.amethyst.rs/doc/master/doc/src/amethyst_ui/font/default.rs.html#13 by calling loader.load with the provided path buf. You should verify that you have read access to the destination of the pathbuf. Be aware that loader.load might not be able to load absolute paths, this should be verified

**Comment by DoumanAsh** [comment]
I imagine I could work on it during this weekend

**Comment by DoumanAsh** [comment]
Looking at `Loader::load` and `Loader::load_from` they all require that the asset would be present among directories in source list.
Which would either require the getter for default fonts modify loader(which changes requirements on argument), modify `Loader` to load asset from arbitary file paths or perform loading of bytes in getter
