### ISSUE TITLE
Rebase or merge on conflicting changes with upstream?

### ISSUE THREAD

**Issue by Emilgardis** [amethyst/amethyst#109]
There has been a few "sync with latest develop" commits lately. (b17b86e (in open pr #99), 266819c, 266819c, 3da54cd, cac16ba, and probably more)
The main problem here is if one should merge or rebase a pull request. Should we come to a agreement on how to handle "rebasable" upstream changes to a pr, or should we let the coder choose for themselves, i.e merge (aka sync with branch) or rebase (rewind, play changes, fastforward, fix possible conflicts)?

**Comment by ebkalderon** [comment]
@Emilgardis Yes, this is a good point. I think that many of these conflicts arise due to the nested nature of the crates.

**Comment by Emilgardis** [comment]
Yes, that sounds reasonable. Right now we have sync commits on #99 and #81 

I'll make a PR to reflect this in CONTRIBUTING.md

**Comment by Emilgardis** [comment]
21ee399 will in some ways prevent this. Closing issue
