### ISSUE TITLE
Look for a reliable way to measure test coverage

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1091]
Goals:

* make people aware of the coverage
* increase motivation for adding tests

**Comment by azriel91** [comment]
I've used kcov for a while, and while it's good for line coverage in the 95% case, it does give you false negatives, such as:

```rust
#[test]
fn my_test() {
    assert!( // this line is sometimes counted as "missed"
        something()
            .with_multiple_lines()
    ); // this line as well
}
```

I haven't tried [tarpaulin](https://github.com/xd009642/tarpaulin) (linux only), but it's rust based and looks somewhat cleaner.

**Comment by bgourlie** [comment]
I had a rust project that integrated with [coveralls.io](https://coveralls.io/), and it worked for a while, and then something changed (I forget what, exactly, but believe it had to with how rustc emitted debug symbols) and it all broke. A cursory search gives me the impression that the situation is resolved. See https://github.com/kennytm/cargo-kcov.

**Comment by TimonPost** [comment]
We did this with laminar checkout this PR: https://github.com/amethyst/laminar/pull/98

**Comment by torkleyy** [comment]
Any progress on this? If there's nobody else working on this I'd just utilize GitLab CI to measure the coverage.

**Comment by fhaynes** [comment]
@torkleyy are you still working on this?

**Comment by fhaynes** [comment]
We've converged on kcov, so I'm going to close this as it was to look for a reliable way. Jenkins is already compiling Amethyst, so having it run kcov is trivial.
