### ISSUE TITLE
PrefabData derive macro does not support enums

### ISSUE THREAD

**Issue by ISibboI** [amethyst/amethyst#1092]
For my game I have a component that lists the actions that are executed if an event is triggered in a vector. But the procedural macro does not support vectors yet. I propose to make the macro support vectors as well.

**Comment by OvermindDL1** [comment]
Just as a note, but be careful about storing potentially non-memcpy'able data in a component, it's makes serialization much more expensive.

**Comment by ISibboI** [comment]
I changed the title as I realized that my error message came from using the macro on an enum, not from a struct containing a vec.

**Comment by Rhuagh** [comment]
It does accept it if it's a Component. It doesn't accept it for aggregate prefabs. Check the part about #[prefab(Component)] in the book.
