### ISSUE TITLE
Document PrefabData required use statements

### ISSUE THREAD

**Issue by ISibboI** [amethyst/amethyst#1093]
When using the PrefabData derive macro, I still need to add use directives for the types used by the macro myself. Specifically there are
```rust
use amethyst::ecs::{Entity};
use amethyst::assets::{PrefabData, PrefabError, ProgressCounter};
```
I propose to make the macro add these on its own, if they are not present.

**Comment by jojolepro** [comment]
That isn't something we can fix. This is a limitation of how macro are built in rust currently. The required imports should be listed in the documentation.

I went over this quickly and I think there isn't any mention of the required `use` https://www.amethyst.rs/book/master/prefab.html

There isn't any docs here either, which is the doc-visible part of the macro https://www.amethyst.rs/doc/master/doc/amethyst_derive/fn.prefab_data_derive.html

**Comment by halfbro** [comment]
The documentation for this is merged, should this issue be closed?
