### ISSUE TITLE
Windows Framerate drops

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#1097]
### Scroll down to "How can you help" for the current contributing guide
# Original
Using multisampling on my game using the DrawPbmSeparate Pass would reduce the fps to 20-30 on windows with 50 cubes in the scene while the linux build could run just fine at 1200 fps.

Tested on windows 7 & 10, two different computers (1 desktop, 1 laptop), both nvidia graphics card (870m & 1070). Performance was better on my better pc (50 fps instead of 30), but it was still terrible. Turning off multisampling restored the framerate to a high value.

Multisampling was set to "4".

Replication:
* clone https://github.com/hoppinworld/hoppinworldclient
* change assets/base/config/window.ron -> multisampling: 4
* cargo run --release (:zzz:)
* profit ?

(note: I might not build currently as its based on a git branch that might have been removed. Should be fixed soon)

I did profile a while ago and what took the most time was swap_buffers.

I'm not sure if multisampling is managed by winit or the amethyst renderer.

# After 5+ hours of research

Note: All issues mentionned here were happening on windows only. I didn't get any issue on linux.

I think there is multiple issues at once which could be causing those performance problems.

I have added a lot of profiler calls at various places to get more info on where it gets stuck [here](https://github.com/jojolepro/amethyst/tree/renderprofile)

## Multisampling

First of all, there is the multisampling one. Changing the multisampling value makes the framerate change a lot, but it is hard to get a proper replication for it.

Multisampling (old results, couldn't replicate today)
* 0: 48 fps
* 1: 90 fps
* 4: 30 fps

## Text Rendering

This happened in my game and I wasn't able to replicate in the ui example. In the following screenshot, you can see that text rendering (glyph queue) can take an abnormal amount of time. Even weirder, the texts in question are changed on each frame, but the lag spikes happen on only 1/30 frame on average, and over 3-4 frames period.

![img1](https://i.imgur.com/c7Gq6Xe.png)

offending lines: <https://github.com/jojolepro/amethyst/blob/8032d2ad931c91a2447d5104a6bc2f34c435b3e0/amethyst_ui/src/pass.rs#L477-L488>

## Swap Buffer

I'm not sure what is the cause of this. Maybe an issue with drivers? Anyhow, I could replicate this by uncapping the frame rate limiter on the ui example. I also added a dynamic-sized ui text in my attempts to replicate the text rendering issues.

As you can see in the following screenshot, the framerate is consistent at 1400 frames per second before suddenly dropping to 450 for almost a whole second before coming back up.

![img2](https://i.imgur.com/hvSwtolh.jpg)

## How you can help

To have a better understanding of this issue, I need to know which of those issues can be ruled-out as driver issues. To do that, I need readers of this issue (you) to run the test and post your results here.

The good news is that you'll also learn how to profile Amethyst in the process ;)

1) Fork [this branch locally using git clone](https://github.com/jojolepro/amethyst/tree/renderprofile)
```
git clone https://github.com/jojolepro/amethyst -b renderprofile amethystrenderprofile
```
2) Go into the directory "amethystrenderprofile"
3) Run the ui example for 15 seconds using the profiler feature
```
cargo run --example ui --release --features profiler
```
4) After 15 seconds, close the ui window.
5) Open **Google Chrome or the Chromium browser** and type the following in the url bar:
```
chrome://tracing
```
6) Drag the thread_profile.json file into the window and you'll see a lot of lines appear.
7) Inside of the section where you see the lines, in the top right corner, you should see 4 tools icon. The second one is to move left and right, the third one is to zoom in/out and the first one is to select one box in particular. Use those tools to find anything that looks like the previous screenshot in this issue (where bars are way longer horizontally than the ones next to them)

Thanks a lot for your participation!

**Comment by lvitol** [comment]
I observed some large lag(about 100ms) between my frame when displaying fps number.

**Comment by lvitol** [comment]
When I manually set fps to a fixed number and display it, the frame rate is stable, no large lag between frame.

**Comment by jojolepro** [comment]
I did some benchmarking, and there are multiple things in the renderer that can cause lag spikes. The main one is when changing a UiText and drawing it, sometimes the library handling the text rasterization hangs for a little bit (10 to 150ms in my game). It only happens for 3-4 frames each ~100 frames.

**Comment by jojolepro** [comment]
I did more benchmarking, and considering how it can cause subtle breakages that won't be catched by devs not testing on windows, I'll bump the priority to critical.

**Comment by jojolepro** [comment]
Results of Sinono3, running the ui example.

Debug:
![image](https://cdn.discordapp.com/attachments/476032191567233025/537323856961208333/unknown.png)

Release:
![image](https://user-images.githubusercontent.com/4755185/51711855-26d11600-1ffb-11e9-9821-b9ee443ad3d6.png)

My results:
gfx-glyph performance example, release. Spikes are created when editing a 100k char text, so they are considered normal.
![image](https://user-images.githubusercontent.com/4755185/51711998-76afdd00-1ffb-11e9-9863-aed3e1969929.png)

amethyst_ui, release
![image](https://user-images.githubusercontent.com/4755185/51712064-ad85f300-1ffb-11e9-931a-3103e75dd656.png)

As you can see in my tests, some frames take almost no time, while others take up to 40 ms.
Sinono3's tests show the same kind of spikes, but with a the base frame time being higher.

**Comment by jojolepro** [comment]
The amount of vertices uploaded each frame by amethyst_ui varies between 2 and 14.

**Comment by jojolepro** [comment]
Fusha's times
![image](https://user-images.githubusercontent.com/4755185/51715378-6ea96a80-2006-11e9-9b94-5ea2adb8470c.png)
normal frame = 2ms

intel + nvidia

**Comment by jojolepro** [comment]
Frizi's times
![image](https://user-images.githubusercontent.com/4755185/51715732-fc398a00-2007-11e9-808c-107302b4da5a.png)

intel + nvidia

**Comment by moxian** [comment]
Runs at very stable ~120 FPS with occasional dips to 116, during which amethyst_renderer::renderer: render_system_draw_encoderflush runs
![chrome_2019-01-25_15-34-56](https://user-images.githubusercontent.com/7831163/51755732-4b8ac380-20b7-11e9-9f01-227c316d4a00.png)

CPU: Intel i5-6600
GPU: AMD RX 480
Driver version: 18.50.03.05-181217a-337289E-RadeonSoftwareAdrenalin2019 (AMD software version 18.12.3 - this is shown much more prominently and may be what people will report).
OS: Windows 7

**Comment by Friz64** [comment]
Runs very nicely at 60 FPS (+- ~0.6 fps)
![image](https://user-images.githubusercontent.com/20155479/51758507-26518180-20c6-11e9-8306-4d7785a59b29.png)
CPU: Ryzen 5 1600
GPU AMD RX 580 8GB
Radeon Software Version: 19.1.1
Driver version: 18.50.11.01-190109a-338124C-RadeonSoftwareAdrenalin2019
OS: Windows 10 Pro 1803

**Comment by jojolepro** [comment]
Fixed in latest gfx-glyph patch. Waiting for the release on crates.io.

**Comment by fhaynes** [comment]
Closing as it is fixed.
