### ISSUE TITLE
Increased memory usage when creating/destroying entities with Ui components

### ISSUE THREAD

**Issue by DoumanAsh** [amethyst/amethyst#1102]
I noticed that memory usage increased over time as I create and destroy UI elements on screen:

Extracted code example https://gist.github.com/DoumanAsh/21512a2fb3697459b7163dce651b6733

Note that it expects [fonts](https://gist.github.com/DoumanAsh/21512a2fb3697459b7163dce651b6733#file-example-rs-L104)

The logic here is simple:
1. I have two states: `Game` and `Paused`.
2. Running game currently does nothing but on ESC it changes state to Paused
3. On `Puased::on_start` I create UI elements: `UIText` and `UiImage` https://gist.github.com/DoumanAsh/21512a2fb3697459b7163dce651b6733#file-example-rs-L141-L177
4. After that when you press ESC, these entities are destroyed and I pop state
5. Repeat it over and over, and you notice that memory usage still increases

For example the game starts at 26mb (according to Task Manager)
After pressing 20 times ESC it increases to 31mb and remains like that(as Game state literally does nothing there is no memory increase)

P.s. I made sure that resources are created once when `Game` starts https://gist.github.com/DoumanAsh/21512a2fb3697459b7163dce651b6733#file-example-rs-L214-L215

**Comment by DoumanAsh** [comment]
No, sorry, I didn't try to debug further to determine where from memory leakage is coming

**Comment by Xaeroxe** [comment]
I suspect this is coming from the way we're managing glyph brushes.  That would be a good place to start looking.

**Comment by DoumanAsh** [comment]
Quick look indicates that glyph brushes cache is never cleaned

**Comment by jojolepro** [comment]
Yeah I saw there was an incrementing counter but no cleaning while checking the pass yesterday. The pass is going away, and I'll try to remember to not include the bug in the refactor :D
