### ISSUE TITLE
Does anyone build amethyst for android successfully?

### ISSUE THREAD

**Issue by harryfei** [amethyst/amethyst#1105]

**Comment by jojolepro** [comment]
Building yes.
Having graphics or input? Not yet ;)

**Comment by harryfei** [comment]
Do we have a plan to support it?

**Comment by torkleyy** [comment]
Yes, very much so! Our roadmap is very close to be published, so you'll see soon :wink:

**Comment by harryfei** [comment]
Nice to hear about that. Where can I check out the process/status? @torkleyy

**Comment by torkleyy** [comment]
It's not available yet, but we'll be sure to publish it on our website, Discord and subreddit.

**Comment by harryfei** [comment]
Look forward to it. Thanks.

**Comment by whaqzhzd** [comment]
Look forward to it. Thanks.
