### ISSUE TITLE
Documentation: What is a prefab actually for?

### ISSUE THREAD

**Issue by joepie91** [amethyst/amethyst#1114]
Reading the [book chapter about prefabs](https://www.amethyst.rs/book/master/prefab.html), it goes into a lot of technical detail about how they work, but the answer to one crucial question is completely missing: __what are they *for*?__

This is a problem that I've also noticed on a few other things (like eg. the `shrev` crate), where documentation assumes that the reader already knows the purpose of the tool, and goes on to describe the workings in that context.

But for somebody who *doesn't* already know what the tool is for, it becomes very difficult to understand any of it - they basically need to reverse-engineer the context out of the description, if at all possible, and then re-read the entire description again to finally understand how to use the tool.

This is really part question (right now, I genuinely *don't know* what prefabs are for in Amethyst), part documentation bug (I'm sure there are others running into this same problem), and part thing-to-keep-in-mind-in-the-future; I feel like "putting things into a reference frame" is generally something that tends to be missing from the documentation around the Amethyst ecosystem.

Even a very rudimentary frame of reference would help for a lot of these cases, it doesn't need to be perfectly written right out of the gate.

(I intend on eventually contributing documentation improvements... but to be able to do that, I first need to understand the tools myself.)

**Comment by Xaeroxe** [comment]
This is a great note, thank you for your insight!

**Comment by Xaeroxe** [comment]
To answer your prefab question:

Prefabs are around so you don't have to define your scenes and entities in code.  The objective is that someday someone without Rust experience can create scenes.  Hard coding scene data is not an objective of ours, so prefabs help us work against that.

**Comment by joepie91** [comment]
I see, thanks.

Looking at the examples directory, I see a lot of prefab-related code in them (eg. [here](https://github.com/amethyst/amethyst/blob/master/examples/gltf/main.rs)) - assuming that RON files are how prefab data is specified, is the prefab-related code just boilerplate for defining the expected structure of the data in the RON files, similar to how you might define structs for Serde?

**Comment by Xaeroxe** [comment]
Yeah it is. We'd really like to get away from doing even that in the code.  For now that's just a workaround for the fact that we don't have certain pieces built yet.

**Comment by Rhuagh** [comment]
I'd say the prefabs are more for abstracting entity creation, not loading data. Loading data is just a mapping "file format" -> "some data structure". Prefabs are used to faciliate fast entity hiearchy creation without having to do a lot of manual work. If you look at something like the prefab defined in the gltf example, that used to be a lot of boilerplate code that manually sets up all the entities, links them, adds a bunch of components etc.

**Comment by Rhuagh** [comment]
And dynamic prefabs are something we want (and can be built on top of the current system), it just requires a few features that don't exist yet in stable (specialisation).

**Comment by azriel91** [comment]
In #1251, a background about [Prefabs](https://www.amethyst.rs/book/master/prefabs.html) was added.
I'm currently learning how this works in detail (in Amethyst) and documenting it as I go.

**Comment by azriel91** [comment]
First cut for explanation in #1340, can't seem to tag @joepie91 in the PR for some reason.

**Comment by OvermindDL1** [comment]
Priority is important but the stale bot closed it?  ;-)

**Comment by jojolepro** [comment]
I think this page explains this well enough https://book.amethyst.rs/master/prefabs.html

Prefabs are used to instantiate/edit a bunch of entities without recompiling.

Feel free to re-open if you think the provided explanation is not good enough.

**Comment by rdelfin** [comment]
One of the pages on the book links to this issue: https://book.amethyst.rs/book/stable/prefabs/how_to_define_prefabs_asset

Is that message accurate, given that the issue is closed?

**Comment by jojolepro** [comment]
Sure! Feel free to contribute documentation whenever you want :hearts:
