### ISSUE TITLE
Quaternion rotation issue with nalgebra

### ISSUE THREAD

**Issue by JamesAngstrom** [amethyst/amethyst#1134]
I was already using it for some procedural geometry and with ncollide, so my code was a bit of a mess using both cgmath and nalgebra and converting between the two - so naturally I wanted to use the new nalgebra stuff!

However, once I translated my code to use nalgebra, I ended up with:
![bad1](https://user-images.githubusercontent.com/44684728/48392493-94132180-e703-11e8-9a27-cb9d55bd9a75.png)

Hmm, not so good. That was using the following code to rotate the camera's transform, where point is the location of the pink teapot it should be looking.
```rust
transform.look_at(point, Vector3::new(0.0, 1.0, 0.0));
```
So I'd already had some issues with rotations with cgmath, specifically it only providing a left-handed look at method. Before I switched to nalgebra I had do do either of the following:
```rust
// cgmath
let look = Quaternion::look_at(dir, Vector3::new(0.0, 1.0, 0.0));
transform.rotation = Quaternion::new(look.v.y, look.v.z, look.s, -look.v.x);
// converting cgmath to nalgebra_glm (right-handed)
let glm_rh = glm::quat_look_at_rh(&glm::vec3(dir.x, dir.y, dir.z), &glm::vec3(0.0, 1.0, 0.0));
let rh = Quaternion::new(glm_rh.coords.w, -glm_rh.coords.x, -glm_rh.coords.y, -glm_rh.coords.z);
// or using quat_look_at_lh cgmath to nalgebra_glm (left-handed)
let lh = Quaternion::new(-glm_lh.coords.y, -glm_lh.coords.z, -glm_lh.coords.w, glm_lh.coords.x);
```
Note how I have to flip the signs for x, y and z when converting between nalgebra and cgmath. As far as I can tell if nalgebra stores it's quaternion as (w, x, y, z) then the equivalent cgmath quaternion is (w, -x, -y, -z). I think these two representations are isomorphic, but suspecting this might be the issue I try changing my new camera rotation code to:
```rust
let q = UnitQuaternion::look_at_rh(&dir, &Vector3::new(0.0, 1.0, 0.0));
transform.set_rotation(Unit::new_unchecked(Quaternion::new(q.coords.w, -q.coords.x, -q.coords.y, -q.coords.z)));
```
That gives me:
![bad2](https://user-images.githubusercontent.com/44684728/48393142-477d1580-e706-11e8-8794-44a84780954f.png)
It's hard to see because the debug lines are very thin, but the teapot should be flat on the terrain, rotated in a specific direction (self.rotation in the below code):
```rust
let angle = glm::rotate_vec3(&(up.cross(&normal)), -(0.5 * PI), &normal);
let rotation = glm::quat_angle_axis(self.rotation, &normal);
let dir = glm::quat_cross_vec(&rotation, &angle);

debugline.add_direction(Point3::new(p.x, p.y + 2.0, p.z), angle * 2.0, Rgba::green());
debugline.add_direction(Point3::new(p.x, p.y + 2.0, p.z), angle * -2.0, Rgba::green());
debugline.add_direction(Point3::new(p.x, p.y + 2.0, p.z), dir * 2.0, Rgba::red());
debugline.add_direction(Point3::new(p.x, p.y + 2.0, p.z), dir * -2.0, Rgba::white());

transform.look_at(Vector3::new(p.x, p.y, p.z) + dir, up);
```
Essentially angle represents the steepest path down the terrain, and dir is a vector also tangent to the terrain offset by self.rotation. It's super hard to see in the image, but when I use quat_cross_vec with dir and then plot the red and white debug lines they are correct, but making the teapot look in that direction doesn't work.

However, I don't think the problem is look_at, the code for that looks fine to me. What I did is change:
```rust
    /// Returns the local object matrix for the transform.
    ///
    /// Combined with the parent's `GlobalTransform` component it gives
    /// the global (or world) matrix for the current entity.
    #[inline]
    pub fn matrix(&self) -> Matrix4<f32> {
        self.iso
            .to_homogeneous()
            .prepend_nonuniform_scaling(&self.scale)
    }
```
to
```rust
    /// Returns the local object matrix for the transform.
    ///
    /// Combined with the parent's `GlobalTransform` component it gives
    /// the global (or world) matrix for the current entity.
    #[inline]
    pub fn matrix(&self) -> Matrix4<f32> {
        Isometry3::from_parts(self.iso.translation, self.iso.rotation.conjugate())
            .to_homogeneous()
            .prepend_nonuniform_scaling(&self.scale)
    }
```
in local_transform.rs in amethyst_core, and this fixes all my issues (screenshot below) by doing the (w, x, y, z) <-> (w, -x, -y, -z) thing for every transform... but it _feels_ like a hack.

![good](https://user-images.githubusercontent.com/44684728/48393813-ee62b100-e708-11e8-9bab-37f8ce5e7e9f.png)

Apologies for not having a minimal example, I can try to build one tomorrow if that would be useful.

**Comment by magnonellie** [comment]
cc @sebcrozet

**Comment by harryfei** [comment]
Same to me. I used `look_at` in my demo but always got unexpected results.

**Comment by JamesAngstrom** [comment]
@sebcrozet Thanks that clarifies things a lot. Looking at the nalgebra code, the `look_a_{rh,lh}` do indeed call `new_observer_frame` and then invert the result, so using `new_observer_frame` directly should give me what I need. (I'm at work now but I will try and confirm later)

However, when using amethyst I do find it surprising that
```
camera_transform.look_at(point, up)
```
does not make the camera look at point, because it directly sets the camera's rotation to the result of look_at_rh, which like you say is inverted. I'm not sure this is the intended behavior for `transform.look_at` in amethyst, at least I would expect (and I think @harryfei is the same) it to behave as it does in e.g. unity:

https://docs.unity3d.com/ScriptReference/Transform.LookAt.html

**Comment by JamesAngstrom** [comment]
To maybe clarify things a bit: I think there are two things here. The first is that cgmath and nalgebra seem to return inverse rotations from their look_at functions. I agree that this isn't a bug in amethyst.

But I think amethyst may be making the same mistake I was - as here we are rotating the camera's transform component to look at something, not the view matrix. So in `amethyst_core/src/transform/components/local_transform.rs`, look_at should be changed from:
```rust
    pub fn look_at(&mut self, target: Vector3<f32>, up: Vector3<f32>) -> &mut Self {
        self.iso.rotation =
            UnitQuaternion::look_at_rh(&(target - self.iso.translation.vector), &up);
        self
    }
```
to something like (untested):
```rust
    pub fn look_at(&mut self, target: Vector3<f32>, up: Vector3<f32>) -> &mut Self {
        self.iso.rotation =
            UnitQuaternion::new_observer_frame(&(self.iso.translation.vector - target), &up);
        self
    }
```

**Comment by jojolepro** [comment]
Feel free to open a pull request :)

**Comment by magnonellie** [comment]
@JamesAngstrom This actually came up briefly while implementing nalgebra and my assumption is that this function has been broken since it was created since the behavior you're describing is obviously what people would expect. It would be great if you could send in a PR to fix it. I would also consider renaming the function in order to not have more breaking changes and to avoid confusion between nalgebras functions and this one. Maybe something like `face_towards` could work?

**Comment by JamesAngstrom** [comment]
I created a PR. I didn't rename the function yet but I could do so if people think it would be better.

**Comment by sebcrozet** [comment]
@magnonellie I find `face_towards` to be a very good name for this. The `new_observer_frame` from nalgebra should be renamed to that as well.

**Comment by JamesAngstrom** [comment]
Should be fixed now :)
