### ISSUE TITLE
Can't change texture color at runtime

### ISSUE THREAD

**Issue by JulienBe** [amethyst/amethyst#1135]
I would very much like to have a way to change easily the color of what I am drawing at runtime :)

As far as I know there is no way to do that for the moment (version 0.90)

**Comment by torkleyy** [comment]
@jojolepro Can you look into this?

**Comment by jojolepro** [comment]
1) Changing the sprite colors: This is planned as a new feature for the Ui refactor. It will take a bit of time..
2) Changing the color of a color texture (uniform). Simply change the Handle<Texture> component for another on the entity in question.

**Comment by torkleyy** [comment]
That's a pretty bad solution, the color should be implemented as a uniform in the shader.

**Comment by fhaynes** [comment]
Closing due to age and lack of activity, but this will go into the UI roadmap.
