### ISSUE TITLE
Packet Loss regression with laminar

### ISSUE THREAD

**Issue by TimonPost** [amethyst/amethyst#1138]
With amethyst network, we have some packet loss if we send to many packets. The packet loss starts happening around 20 000 packets.

Increase [this](https://github.com/amethyst/amethyst/blob/master/amethyst_network/src/test.rs#L66) value and the [assert](https://github.com/amethyst/amethyst/baob/master/amethyst_network/src/test.rs#L76) above 50 000 to see the assert failing because the received packets are not equal to the send once. 

If you follow those steps I described you should be able to see it your self by running `cargo test send_receive_100_packets` in `amethyst_network` crate.

**Comment by OvermindDL1** [comment]
That's fairly by design for UDP though without some reliability layer built on top of it.

**Comment by TimonPost** [comment]
Unfortunately, this is not the problem here. When running laminar with 10 000 000 packets I won't get packet loss. But when running from within amethyst network I'll get high packet lost. So I think there's more to it. Than just UDP not being reliable.

**Comment by OvermindDL1** [comment]
How does the integration test work?  Because if a lot of packets are sent but not read then the OS will definitely start dumping them when it's UDP buffer is full (significantly smaller than TCP, that's why it's important to read them *fast*, a dedicated thread should always be receiving UDP packets).

**Comment by TimonPost** [comment]
You can see the integration test of the amethyst network at the link I provided in issue header. I think that could be the case indeed. That the os dumps the packets. If you follow those steps I described you should be able to see it your self by running `cargo test send_receive_100_packets` in `amethyst_network` crate.

**Comment by TimonPost** [comment]
I think it is quite reasonable if you think about it. If you send a million packets the send loop will be working a lot. And the receiving can't happen until the send queue is empty. So some packets may not have time to be received. So I am thinking we should somehow separate the sending and receiving in on a thread. And redesign this process.

**Comment by qqwa** [comment]
The test passed for me with 1 000 000 packets but tried it only once. And failed 3 out of 3 times with 10 000 000 packets. left: `9998977`, left: `9999270`, left: `9999997`,

**Comment by TimonPost** [comment]
Oke, thanks for giving those stats. Actually, those results are very good and those packets dropped is probably a normal cause of UDP being unreliable. After 'some' debugging, I found that it was probably a problem of my Linux. I also got nice results on windows and it was working out very well. For now, this is not a problem anymore as far I can see. For now, this could be closed.
