### ISSUE TITLE
Add unit-tests for amethyst network

### ISSUE THREAD

**Issue by TimonPost** [amethyst/amethyst#1139]
Amethyst network should be well tested. Currently, it has two integrations tests and we want to have all code covered by unit tests also.  Feel free to add valuable unit tests to `amethyst network`.

**Comment by onbjerg** [comment]
Duplicates #819 somewhat?

**Comment by TimonPost** [comment]
I maked it more specific it isn't duplicated anymore.

**Comment by LucioFranco** [comment]
Yup this is fine, @TimonPost I think more detail would be nice and could you link to #819 as well?

I can think that we will at least want to test the ability to send packets using the different channels. Probably want to simulate a server and many clients as the current tests just have one server and one client.

**Comment by fhaynes** [comment]
Closing this. We'll include it when the network team moves on to amethyst_network from laminar.
