### ISSUE TITLE
Remove all expects() from amethyst_network

### ISSUE THREAD

**Issue by TimonPost** [amethyst/amethyst#1141]
Remove all `expects()` from amethyst network.

Here are a few: 
1. https://github.com/amethyst/amethyst/blob/master/amethyst_network/src/network_socket.rs#L69
2. https://github.com/amethyst/amethyst/blob/master/amethyst_network/src/network_socket.rs#L155
3. https://github.com/amethyst/amethyst/blob/master/amethyst_network/src/network_socket.rs#L151
4. https://github.com/amethyst/amethyst/blob/master/amethyst_network/src/bundle.rs#L36

This kind of relates to error handling from this [issue](#1140).

**Comment by Plasticcaz** [comment]
I think I'd like to have a go of this if that's okay.

**Comment by Plasticcaz** [comment]
I should note I've opened [pull request  #1176 ](https://github.com/amethyst/amethyst/pull/1176) for this issue.

**Comment by jojolepro** [comment]
Fixed?

**Comment by TimonPost** [comment]
Yes, it could be closed for now. The left expects could be looked at later.
