### ISSUE TITLE
GLTF example does not render after refactor

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#1145]
Puffy doesn't render (though it seems the animation logic is working). Just get a black screen.

![image](https://user-images.githubusercontent.com/2993230/48518398-5b737380-e8ce-11e8-8d8a-b16587c7c80c.png)

```
...
[DEBUG][amethyst_assets::storage] "animation::Sampler": Asset "<Data>" (handle id: Handle { id: 232 }) has been loaded successfully[DEBUG][amethyst_assets::storage] "PREFAB": Asset "mesh/puffy.gltf" (handle id: Handle { id: 0 }) has been loaded successfully
[DEBUG][amethyst_assets::storage] "PREFAB": Asset "prefab/puffy_scene.ron" (handle id: Handle { id: 0 }) has been loaded successfully
Running animation 0
Running animation 1
[INFO][amethyst::app] Engine is shutting down
```

The example works on ac851627 (after #1116), but not c50e2709 (after #1075). I've spent a while re-reviewing the code but can't find it. Someone else might have better eyes for this.

Reproducible on Ubuntu and Windows.

**Comment by jojolepro** [comment]
Fixed?

**Comment by azriel91** [comment]
Yeap! Thanks @udoprog!
