### ISSUE TITLE
Allow systems to be paused

### ISSUE THREAD

**Issue by udoprog** [amethyst/amethyst#1147]
Hey,

I'm working on a small experimental game to learn more about Amethyst, and when I got to states I was a but confounded how to implement the `PauseState`.

My goals were the following:
 1. Given that the state machine uses a certain state, only a certain set of system should be running for that state.
 2. Going to another state should cause the first set of systems to stop running, and a new set of system to run.

This way, entering the PauseState means that I could let my systems _not run_ that dealt with game logic and only run the system permitting me to unpause.

After some talking on Discord, two solutions were initially presented:

 * Run multiple dispatchers, one for the "base" set of systems, and another dedicated to the state we are currently in (e.g. empty for PauseState).
 * Build a shared resource that systems can read to figure out if their `run` method should be a no-op.

The example provided runs multiple dispatchers, this approach has a couple of pain points for users. **1)** You need to implement a custom GameData. At this stage, this is probably not something you have done before, and it's fairly involved to get an ergonomic interface (builder, game state, signatures, ...). **2)** The two dispatchers run serially - one after another. So rendering which would typically happen at the beginning of the next frame blocks any custom systems from running in parallel. We do however reduce the number of systems run.

The second approach is to build a shared resource. This is by far the most appealing, but suffers from having to add code to every system that could potentially be paused.
After discussing this with @torkleyy on Discord, they presented a variant on the second solution that sounded appealing to me. Use a shared resource like before, but build a trait and an associated implementation that wraps the existing system and is responsible for reading the state of the resource to determine if the system should run.

I've built a prototype for this here: #1146

Some pros:
* Deciding how a system should be enabled and disabled happens in one place: where the systems are installed.
* We don't touch shred and specs.

Cons:
* The systems are still installed, so we take the overhead of calling into them over dynamic dispatch. But compared to the amount of computation a system does normally this seems negligible. This could be overcome by a specs redesign which is in the makings.

**Comment by jojolepro** [comment]
Depending on what you need exactly, its possible to set the time scale to 0 here: https://www.amethyst.rs/doc/latest/doc/amethyst_core/timing/struct.Time.html#method.set_time_scale

You need your systems to be multiplying by the delta time for it to work (you should be doing that even if you don't pause).

**Comment by udoprog** [comment]
@jojolepro While it is an interesting approach, I'd like to elaborate why I think setting the time scale might difficult to apply as a more general solution.

We would only effectively pause systems that depend on time delta. As an example, I have two systems in my experimental project I'd like to suspend which do not: input handling and collision detection.

Time delta dependent systems might still join resources and perform a calculation (with a zero factor) that has no effect. But, we still perform the calculation, and any joined resources might be flagged through something like `FlaggedStorage`, causing additional work to be done.

It effects all systems globally, making it unsuitable for associating systems to states.

**Comment by torkleyy** [comment]
Thanks to @udoprog, this can be closed now.
