### ISSUE TITLE
Add InputEvent<T> to StateEvent

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#1148]
By default, users and amethyst examples are using the winit VirtualKeyCode to handle keyboard events. This should be changed to show goos pratices by using the events coming out of the EventChannel<InputEvent<AC>> in State::handle_event. To be able to do this, there will need to be a variant Input(InputEvent<T>) added to StateData. The generic type on StateData should default to String.

**Comment by udoprog** [comment]
I'll rephrase what I raised in another issue here.

If this is implemented we would have two places where we handle input events. For documentation purposes, and to reduce confusion, I'd like clarification on what is expected to be handled where. Or that we have a clear signal what the preferred way of handling input is.

I prefer handling _all_ input in systems. There is a clearly defined data dependency, and the handler is managed by the ECS like almost everything else. I'm curious what others think about this.

**Comment by jojolepro** [comment]
I only handle inputs in states **if** they are directly triggering a state `Trans`.
Otherwise, I put everything else into systems too. (There's no harm in handling input in multiple places)

**Comment by torkleyy** [comment]
Request by @jojolepro, let's implement this for now and discuss alternatives or improvements later given this is a big issue that would block progress on this.

**Comment by fhaynes** [comment]
Closing this due to age and lack of activity....and it was resolved, maybe?

**Comment by jojolepro** [comment]
I'll try implementing it tomorrow. Reopening so I don't forget.
