### ISSUE TITLE
Allow SpriteSheet .ron files to load grid like spritesheets

### ISSUE THREAD

**Issue by Skytrias** [amethyst/amethyst#1149]
Not sure if this was already discussed once but either way.

I'd like to propose a different way of how a spritesheet would be loaded from a .ron file. Most engines have this option of a grid like importing, so why not do this with .ron files too. Maybe this is already possible or not but I'm just going to give an example below. 

This would help me atleast in being able to define a spritesheet quicker and without having to define 50+ sprites that only have x and y coordinates changed. The example below has 8 sprites inside and this requires me to calculate the x everytime which takes a bit.

    spritesheet_width: 576.0,
    spritesheet_height: 40.0,
    sprites: [
        (
            x: 0.0,
            y: 0.0,
            width: 72.0,
            height: 40.0,
	    offsets: Some((-32.0, -16.0))
        ),
		(
            x: 72.0,
	    y: 0.0,
            width: 72.0,
            height: 40.0,
	    offsets: Some((-32.0, -16.0))
        ),
		(
            x: 144.0,
            y: 0.0,
            width: 72.0,
            height: 40.0,
	    offsets: Some((-32.0, -16.0))
        ),
		(
            x: 216.0,
	    y: 0.0,
            width: 72.0,
            height: 40.0,
	    offsets: Some((-32.0, -16.0))
        ),
	(
            x: 288.0,
	    y: 0.0,
            width: 72.0,
            height: 40.0,
	    offsets: Some((-32.0, -16.0))
        ),
	(
            x: 360.0,
	    y: 0.0,
            width: 72.0,
            height: 40.0,
	    offsets: Some((-32.0, -16.0))
        ),
	(
            x: 432.0,
	    y: 0.0,
            width: 72.0,
            height: 40.0,
	    offsets: Some((-32.0, -16.0))
        ),
	(
            x: 504.0,
	    y: 0.0,
            width: 72.0,
            height: 40.0,
	    offsets: Some((-32.0, -16.0))
        ),
    ],

An alternative to this would simply be this:

	spritesheet_width: 576.0,
        spritesheet_height: 40.0,
	columns: 8,
	rows: 1,
	cell_size: Some((72.0, 40.0))
        offsets: Some((-32.0, -16.0))

Sorry for the horrible indentation 😄 

So maybe this could be added as a seperate option for spritesheets with a specifier in the ron file?

**Comment by Rhuagh** [comment]
it'll probably be something like: 
```
(
    spritesheet_width: 576.0,
    spritesheet_height: 40.0,
    repeat: (
        columns: 8,
        rows: 1,
        offsets: Some((-32.0, -16.0)),
    ) 
)
```

**Comment by udoprog** [comment]
Does `offsets` refer to the distance between cells? If so, I'd refer to that `padding`. Offset sounds to me like if the entire grid was offset by some number of pixels. That could also be a top-level setting :P.

Design-wise, sometimes I'm silly and I lay things out into a flow which is not exactly a grid (fill one row, then continue on to the next). It would be nice if it was possible to also generate a mapping that is limited by `count`, like:

```
repeat: (
    columns: 8,
    rows: 1,
    count: 13,
)
```

**Comment by jojolepro** [comment]
@Rhuagh there already is a prefab for spritesheets. Make sure to modify that and not duplicate everything :)

**Comment by Rhuagh** [comment]
No, there's no prefab for spritesheets, there's a file format for spritesheets, big difference.

**Comment by azriel91** [comment]
@Rhuagh are you still working on this?

**Comment by Skytrias** [comment]
bump

**Comment by Rhuagh** [comment]
I am, yes. I will try to finish this in a few days.

**Comment by azriel91** [comment]
Completed in #1469.

**Comment by Machine-Hum** [comment]
Are there some docs on how to use this functionality?

`
[ERROR][amethyst_assets::storage] "renderer::SpriteSheet": Asset "sprites/basictiles.ron" (handle id: Handle { id: 0 }) could not be loaded: Failed to load asset with name "sprites/basictiles.ron"
`

Here is my ron
`
(
    spritesheet_width: 128.0,
    spritesheet_height: 240.0,
    repeat: (
        columns: 8,
        rows: 15,
        cell_size: (16.0, 16.0),
        offsets: (16.0, 16.0),
    )
)
`

**Comment by 0x6273** [comment]
There are some example ron files in examples/assets/texture

**Comment by azriel91** [comment]
Likely you have to write it in `Grid` or `List`, and change `spritesheet_*` to `texture_*`:

```rust
Grid((
    texture_width: 128.0,
    texture_height: 240.0,
    repeat: (
        columns: 8,
        rows: 15,
        cell_size: (16.0, 16.0),
        offsets: (16.0, 16.0),
    )
))
```

**Comment by Machine-Hum** [comment]
No dice :(

```
#![enable(implicit_some)]
    
Grid((
    texture_width: 128.0,
    texture_height: 240.0,
      repeat: (
          columns: 8,
          rows: 15,
          cell_size: (16.0, 16.0),
          offsets: (16.0, 16.0),
      )
))
```

```
machinehum@wlkr:~/realm.one$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `target/debug/amethyst-starter-2d`
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.13.0
[INFO][amethyst::app] Platform: x86_64-unknown-linux-gnu
[INFO][amethyst::app] Amethyst git commit: 
[INFO][amethyst::app] Rustc version: 1.39.0 Stable
[INFO][amethyst::app] Rustc git commit: 4560ea788cb760f0a34127156c78e2552949f734
[INFO][winit::platform::platform::x11::window] Guessed window DPI factor: 1
[WARN][gfx_backend_vulkan] Unable to find extension: VK_EXT_debug_utils
[WARN][gfx_backend_vulkan] Unable to find layer: VK_LAYER_LUNARG_standard_validation
[WARN][rendy_factory::factory] Slow safety checks are enabled! Disable them in production by enabling the 'no-slow-safety-checks' feature!
[INFO][rendy_util::wrap] Slow safety checks are enabled! You can disable them in production by enabling the 'no-slow-safety-checks' feature!
[ERROR][amethyst_assets::storage] "renderer::SpriteSheet": Asset "sprites/basictiles.ron" (handle id: Handle { id: 0 }) could not be loaded: Failed to load asset with name "sprites/basictiles.ron"
[ERROR][amethyst_assets::progress] Error loading handle 0, renderer::SpriteSheet, with name sprites/basictiles.ron: Failed to load asset with name "sprites/basictiles.ron"
caused by: Failed to load asset with name "sprites/basictiles.ron"
Error { inner: Inner { source: Some(Error { inner: Inner { source: Some(Error { inner: Inner { source: None, backtrace: None, error: LoadSpritesheetError } }), backtrace: None, error: Format("SPRITE_SHEET") } }), backtrace: None, error: Asset("sprites/basictiles.ron") } }
caused by: Format "SPRITE_SHEET" could not load asset
Error { inner: Inner { source: Some(Error { inner: Inner { source: None, backtrace: None, error: LoadSpritesheetError } }), backtrace: None, error: Format("SPRITE_SHEET") } }
caused by: Failed to parse SpriteSheet
Error { inner: Inner { source: None, backtrace: None, error: LoadSpritesheetError } }
[ERROR][amethyst_assets::progress] Note: to handle the error, use a `Progress` other than `()`
[WARN][amethyst_assets::storage] Loading unnecessary asset. Handle 6 is unique 
[ERROR][amethyst_assets::progress] Error loading handle 6, Mesh, with name sprites/basictiles.png: Asset was loaded but no handle to it was saved.
caused by: Asset was loaded but no handle to it was saved.
Error { inner: Inner { source: None, backtrace: None, error: UnusedHandle } }
[ERROR][amethyst_assets::progress] Note: to handle the error, use a `Progress` other than `()`
[INFO][amethyst::app] Engine is shutting down
```

**Comment by azriel91** [comment]
Take out the wrapping `Grid(..)`, think that's still on `master`. Also, pop by Discord (https://discord.gg/amethyst) -- it's faster to get feedback :slightly_smiling_face:
