### ISSUE TITLE
Pressing Esc does not exit the default start project 

### ISSUE THREAD

**Issue by clemarescx** [amethyst/amethyst#1158]
At the [beginning of the Pong tutorial](https://www.amethyst.rs/book/latest/pong-tutorial/pong-tutorial-01.html#opening-and-closing-a-window) is mentioned:
> Let's start a new project:
>
>`amethyst new pong`
>
>If you run this project with `cargo run`, you'll end up with a window titled "pong" that renders a really delightful shade of green. Press `Esc` to quit. [...] 

However, pressing `Esc` does not exit / close the window for me, whether on a newly created project or throughout the Pong tutorial. I don't know if it's a problem local to me, a bug in the engine, or the documentation needing an update.

I'm running it on Arch Linux, Rust stable 1.30.1, and Amethyst 0.9.0. 
Let me know if you need more info.

**Comment by jojolepro** [comment]
That default behavior was removed. The doc isn't up to date. Thanks for reporting!

**Comment by torkleyy** [comment]
This is fixed already.
