### ISSUE TITLE
Renderer tests sometimes fail

### ISSUE THREAD

**Issue by ebkalderon** [amethyst/amethyst#116]
Navigating directly into the `src/renderer/` directory and calling `cargo test` works fine, but for whatever reason, staying in the top-level directory of the repository and calling `cargo test -p amethyst_renderer` or `cargo local-pkgs test` fails from Cargo not finding the `genmesh` crate.

**Comment by yeliknewo** [comment]
It seems to be because dev dependencies aren't propagated even when testing. Should we add a feature for testing and use that instead of dev dependencies?

**Comment by Emilgardis** [comment]
This is a known issue, however it should have been fixed, see rust-lang/cargo#860

**Comment by sekhat** [comment]
I've added a pull request that should fix this issue. From my understanding of calling from a higher level cargo project, that project needs to be a workspace, and that at least needs to be pointed out explicitly, by having a [workspace] entry in the top level projects Cargo.toml.

The members of the workspace can be worked out implicitly. Mostly by path dependencies, and/or walking up the tree to a Cargo.toml with a [workspace].

I could be wrong on this, but adding the [workspace] to the Cargo.toml seems to have solved the issue.

**Comment by sekhat** [comment]
@ebkalderon Did the workspace stuff not fix this issue?

**Comment by Xaeroxe** [comment]
Issue no longer occurring on latest master, I'm closing this.
