### ISSUE TITLE
Amethyst CLI error when installing on Windows through cargo

### ISSUE THREAD

**Issue by irafunesta** [amethyst/amethyst#1166]
Hello, i'm new with cargo and Amethyst, i was just following the Getting Started guide, and installing the Amethyst CLI through cargo, but is giving me this error. Has anyone had this error ?

I'm using Window 10

cargo 1.28.0 (96a2c7d16 2018-07-13)

rustc 1.28.0 (9634041f0 2018-07-30)

[Amethyst_error.txt](https://github.com/amethyst/amethyst/files/2606998/Amethyst_error.txt)

Step to riproduce
$ cargo install amethyst_tools

**Comment by jojolepro** [comment]
Try using rustup update, then try installing amethyst_tools again. Let us know if it still doesn't work.

**Comment by irafunesta** [comment]
Upgrading to rustc 1.30.1 (1433507eb 2018-11-07) fixed the issue.
