### ISSUE TITLE
Pixel Perfect 2D Rendering

### ISSUE THREAD

**Issue by dotellie** [amethyst/amethyst#1174]
We should offer some sort of pixel perfect 2D render kind of like what Godot is doing. One of the primary reasons for this is that it'll avoid most floating point rounding issues. A potential problem I see is handling camera zoom but that could very well be considered an edge case as most 2D games don't actually want to scale their sprites.

**Comment by fhaynes** [comment]
Closing due to age and lack of activity. This one will go on the roadmap, but needs to be designed and broken up properly first.

**Comment by OvermindDL1** [comment]
It's pretty easy to do pixel perfect 2d rendering, just in the vertex shader adjust the points for the sprite to lay integral bounds with the camera's offset at the most basic, and you can get more fancy to handle zoom and rotation and all such as well too.
