### ISSUE TITLE
Introduce the API docs in the book

### ISSUE THREAD

**Issue by dotellie** [amethyst/amethyst#1175]
I think that we should introduce the API documentation to users while they are reading the book so that they get a feel for how it should be used without having to find out completely on their own. The best way to do this in my opinion would be to mention that we need a type (say a vector) but we don't know where we can find it. Then we introduce the API docs and point to how you find out about that.

**Comment by AregevDev** [comment]
Maybe I can handle it, I think concluding the types used by the end of each chapter and provided the API docs for each type will work well.:ok_hand:

**Comment by khionu** [comment]
I would suggest linking them when each type in introduced, instead of an index at the bottom.

**Comment by AregevDev** [comment]
I think I will be able to do that, any specific instructions you want to
include?

**Comment by fhaynes** [comment]
Closing this due to age and lack of activity
