### ISSUE TITLE
Avoid repeated warning about not (yet) loaded texture

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1177]
https://github.com/amethyst/amethyst/blob/46c18a7f1442c2af1590883b1b3bf481770e818f/amethyst_renderer/src/pass/flat2d/interleaved.rs#L318-L321

**Comment by azriel91** [comment]
Use `debug!` 🐞!

**Comment by fhaynes** [comment]
Closing this due to age and lack of activity. @azriel91 if it is still relevant, feel free to re-open it as a bug.
