### ISSUE TITLE
Consider using Dispatcher with static lifetime only

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1178]
There is close to no use case for having a lifetime in a system field, so we should consider exporting the dispatcher with only `'static` as lifetimes. That would also allow us to remove the lifetimes from the state implementations.

**Comment by torkleyy** [comment]
Related #1152

**Comment by Xaeroxe** [comment]
I'm so glad you investigated this.  I've been wondering if this was the case for a while now but I didn't dare dream to be honest.

**Comment by torkleyy** [comment]
We've got a few choices to do this, the ones that come to my mind are:

* remove lifetimes from `Simple*` and keep them for the other types + add a `SimpleDispatcher = Dispatcher<'static, 'static>`
* don't export the `Dispatcher` from Specs like that, but instead rename it and use `Dispatcher` to identify the static one. This seems like a confusing thing to do.
* Remove lifetimes from the traits, but make specifying `'static` just an obvious default.

**Comment by Xaeroxe** [comment]
I prefer the first option

**Comment by LucioFranco** [comment]
Yeah, 1 seems like the least path of friction. I think that might be a good option.
