### ISSUE TITLE
Hot-reloading config files

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1186]

**Comment by udoprog** [comment]
Could you elaborate what this is about? On the surface is looks like `diff: hard` :D.

To explain: when you load a configuration file its values tend to be copied into a resource. Hot reloading would then require some kind of system to detect changes which leads to mutating resources. We then need to make sure this data hasn't been copied anywhere else. That seems kinda hard to me.

**Comment by jojolepro** [comment]
You don't need to make sure the data has been copied, but I'm not exactly sure what torkleyy has in mind. I had this in my task list for months, but I'm still not sure how to go about it.

**Comment by torkleyy** [comment]
Oh, yeah, I guess it's not that easy. It depends on how we want to continue this; there are some things in place already that use callbacks (for screen dimension changes), but I can just as well imagine using events for it. I should change the diff label, agreed :)

**Comment by jojolepro** [comment]
Probably need an rfc imo.

**Comment by khionu** [comment]
This actually has been done for us: https://github.com/phaazon/warmy

**Comment by fhaynes** [comment]
Closing this due to age, lack of activity, and lack of specificity. If it is still relevant, please open a discussion on the forums for the feature.
