### ISSUE TITLE
3D Camera aspect ratio changes.

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#1193]
# Task
Add a `System` that automatically adjust the camera aspect ratio depending on the current window size.
Should only apply on camera with a `AutoFov` component.

```rs
pub struct AutoFov {
    base_horizontal_fov: f32,
    fov_grow_ratio: f32, // needed?
    base_aspect_ratio, // The ratio at which the base fov is applied without any transformation (ie 16/9 or 4/3)
}
```

**Comment by JameeKim** [comment]
Can you elaborate on what the system does with each field of the `AutoFov` component? This feature is exactly what I need, but I don't get how I should approach this problem.

**Comment by jojolepro** [comment]
base_aspect_ratio is the screen dimension ratio (16/9, 4/3, etc) for which the base_horizontal_fov is meant to apply. When the aspect ratio grows (horizontal stretch), you also grow the horizontal fov by a factor of 

delta_fov = fov_grow_ratio / (current_aspect_ratio - base_aspect_ratio)
new_camera_fov = base_horizontal_fov + delta_fov

Also you'll want min_fov and max_fov fields on the AutoFov struct, because otherwise it would be possible to see 360 degrees by making the window very large but not high.

Does that answer all your questions?

**Comment by JameeKim** [comment]
Thank you so much! I'll start working on this :)

**Comment by JameeKim** [comment]
Maybe this issue can be closed?

**Comment by torkleyy** [comment]
Yep, thanks!
