### ISSUE TITLE
Rewrite pong tutorial about `application_root_dir()`

### ISSUE THREAD

**Issue by celluloce** [amethyst/amethyst#1194]
I tried writing and running the pong tutorial https://www.amethyst.rs/book/latest/pong-tutorial.html , and error message appeared as follow.

```
error[E0425]: cannot find function `application_root_dir` in this scope                                               
  --> src/main.rs:28:3                                                                                                
   |                                                                                                                  
28 |         application_root_dir()                                                                                   
   |         ^^^^^^^^^^^^^^^^^^^^ not found in this scope                                                             
help: possible candidates are found in other modules, you can import them into scope                                  
   |                                                                                                                  
6  | use amethyst::utils::app_root_dir::application_root_dir;                                                         
   |                                                                                                                  
6  | use amethyst::utils::application_root_dir;  
```
And I found this commit https://github.com/amethyst/amethyst/commit/8288591fc3085a3b34bc3930f7165ba03f9ce113 .

So That, I think the pong tutorial must be rewritten about `application_root_dir()` an example this page https://www.amethyst.rs/book/latest/pong-tutorial/pong-tutorial-03.html#modifying-the-transform .

Thanks in advance.

**Comment by udoprog** [comment]
Hello, I see how that can be confusing. The snippet references a part of the existing pong example and isn't really meant to be run by itself. This could definitely be clarified.

Thank you!

**Comment by tommket** [comment]
Hi,
I was following the pong tutorial from the book "step by step" (copy pasting code from the tutorial) and I ended up with the same error and had to rewrite it to:
`let binding_path = "./resources/bindings_config.ron";`

**Comment by armyofevilrobots** [comment]
While hardcoding the dir is working, we now have a new issue induced in:
https://github.com/amethyst/amethyst/commit/25b46c223c1ee4f87230e3bc747c44ba960e70e5#diff-4f09cfd3722d8ae1ebd50e30fa9d8d1c
where a new project created via amethyst new will fail to build with something like:
```
  --> src/main.rs:23:59                                                              
   |                                                                                 
23 |     let path = format!("{}/resources/display_config.ron", application_root_dir());
   |                                                           ^^^^^^^^^^^^^^^^^^^^^^ `std::result::Result<std::path::PathBuf, std::io::Error>` cannot be formatted with the default formatter
   |                                                                                 
   = help: the trait `std::fmt::Display` is not implemented for `std::result::Result<std::path::PathBuf, std::io::Error>`
   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
   = note: required by `std::fmt::Display::fmt`
```
While it's easy enough to fix with ? and match or whatever, it breaks the walkthrough in:
https://www.amethyst.rs/book/latest/pong-tutorial/pong-tutorial-01.html
and it'll probably trip up noobs (like myself).

**Comment by jojolepro** [comment]
![image](https://user-images.githubusercontent.com/4755185/58349961-b31d0980-7e32-11e9-8068-64c2f73ca46b.png)
