### ISSUE TITLE
Config::load ignores the errors silently.

### ISSUE THREAD

**Issue by yjh0502** [amethyst/amethyst#1201]
Although the behavior is clearly documented [1], silently ignoring all errors including typo on the config file by default does not feel right. We have `Option::unwrap_or_default`, so how about changing `Config::load` to `Config::load_no_fallback` and let callers to use `unwrap_or_default` when needed?

[1] https://www.amethyst.rs/doc/master/doc/amethyst/prelude/trait.Config.html#tymethod.load

**Comment by torkleyy** [comment]
That's strange, why would `env_logger` ignore `error!`?

**Comment by torkleyy** [comment]
Okay, so I guess this issue should be "Make logging less verbose" instead?

**Comment by fhaynes** [comment]
Closing this due to age and lack of progress.
