### ISSUE TITLE
Consider removing features document

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1208]
I'm not exactly sure what to do with it right now as it tends to get rather outdated and doesn't provide such a good overview. So either we have to figure out a strategy to improve and maintain it or we remove it (at least the link to it from the README). Any ideas here?

**Comment by minecrawler** [comment]
[Link to list](https://github.com/amethyst/amethyst/blob/master/docs/FEATURES.md) so everyone knows what we are talking about 🙃

In the current state, it is hard to read and understand what is possible and what is not. It says "UI Layouting system", however it does not say to what extend. What UI elements are available? What effects are available? What degree of customization is possible?

Such a list is pretty bad, imho. If you start listing each and every little thing the engine can do, it'll become hard to read and cumbersome for everyone involved. The feature list is marketing most of the time, and should get people interested and make it easy to compare Amethyst to Godot, Unity, UE4, etc. So, I think that the feature list should be high-level, go on the landing page of the home page and be static and finished with a few points (don't use a bullet points list, that's lame 😉).

However, it is fairly important to also tell people what is implemented and works. So, I think, a list of everything implemented would be nice, indexed and searchable. If I could type "directx" and get a yes or no or a version number from the search engine, gee, that would be nice! That's not a list, though, and imho, that's a db which is best filled by each Amethyst team separately.

**Comment by LucioFranco** [comment]
I am for this as we are reworking the roadmap it will replace the features document.

**Comment by khionu** [comment]
Let's do this. It would be best for us to do this when we're approaching 1.0

**Comment by torkleyy** [comment]
I think that we should re-work the features document to be a high level overview. Our previous attempt at a roadmap unfortunately wasn't maintained very well, so having a high level overview in docs/FEATURES.md would be a good start IMO.

**Comment by khionu** [comment]
A roadmap serves a very different purpose from a list of features. What contributors would care about would come from browsing our issues, in lieu of a roadmap. What users would care about would be a much shorter list, then our documentation if that interests them.

**Comment by LucioFranco** [comment]
I opened an issue for that problem exactly as this one is just about removing it but they seem duplicates of each other #1380

**Comment by fhaynes** [comment]
Closing this as it is redundant at this point.
