### ISSUE TITLE
Improve documentation on EventReader

### ISSUE THREAD

**Issue by Hugal31** [amethyst/amethyst#1211]
As I searched for a way to receive custom events in a State, I looked at the documentation of [`StateEvent`](https://www.amethyst.rs/doc/master/doc/amethyst/enum.StateEvent.html), to try to replace it with a custom struct. I saw it derive from `EventReader`, and declare a [`StateEventReader`](https://www.amethyst.rs/doc/master/doc/src/amethyst/state_event.rs.html#14-19). But I had to read the source code of amethyst_derive to understand how the derive worked (i.e. aggregate multiple event types in a single enum).

I think the documentation of EventReader and its derive proc_macro should be improved by:

- A section in the book, either in [the State page](https://www.amethyst.rs/book/latest/concepts/state.html), either in its own page, to show how to use a custom StateEvent. A page on `CoreApplication` and how to change the default template parameters wouldn't hurt too.
- Maybe a better explanation on the [`EventReader`](https://www.amethyst.rs/doc/master/doc/amethyst_core/trait.EventReader.html) trait,
- An explanation on what the `EventReader` macro do, and how to use it, in the documentation of amethyst_derive for example.
- An practical code example on how to use a custom event reader (in the [examples directory](https://github.com/amethyst/amethyst/tree/master/examples), I mean).

**Comment by marot** [comment]
I'd like to claim this issue.

**Comment by marot** [comment]
I unassigned myself due to lack of time

**Comment by jojolepro** [comment]
Fixed by the explanation provided here: https://book.amethyst.rs/stable/concepts/state.html#event-handling
