### ISSUE TITLE
Support causes in amethyst::Error

### ISSUE THREAD

**Issue by udoprog** [amethyst/amethyst#1214]
Our existing error type is sparse and doesn't include any context of where an error happened.

We should include causes with contexts, and backtraces to our error type to improve our diagnostic capabilities both to users and developers.

#### Causes

The [`failure`](https://docs.rs/failure) allows doing this by adding "contexts":

```rust
use failure::{Error, ResultExt};

type Result<T> = Result<T, Error>;

fn ring_bell(sound: &str) -> Result<()> {
  bail!("I don't feel like ringing the bell")
}

fn something() -> Result<()> {
  ring_bell("ding").with_context(|_| format_err!("Failed to ding"))?;
  ring_bell("dong").with_context(|_| format_err!("Failed to dong"))?;
  Ok(())
}
```

Causal chains are useful because errors can be quite generic (i.e. `I don't feel like ringing the bell`). But in this case an important piece of information is: did it fail when dinging or donging?

#### Backtraces

I think most folks should be familiar with back traces, but I'll just provide some brief thoughts on why they should be included.

Backtraces provide additional context, but can be quite low level. Panics by default include a backtrace. This is something we will be losing out on unless we include it in our error types. 

Causes without backtraces could be rendered like this, and should be highly useful for many error cases:

```rust
Failed to ding
Caused by: I don't feel like ringing the bell.
```

Including backtraces provides much more detailed information:

```
Failed to ding
stack backtrace:
   0:     0x5616b3933aa6 - backtrace::backtrace::libunwind::trace::hebc3cbfc0bad42f5
                        at /home/udoprog/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h662d733ae29451d7
                        at /home/udoprog/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:     0x5616b392e053 - backtrace::capture::Backtrace::new_unresolved::hbefd36b5dad230fc
                        at /home/udoprog/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:     0x5616b392cb8f - failure::backtrace::internal::InternalBacktrace::new::h47fcb9ce8ccc42f5
                        at /home/udoprog/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.3/src/backtrace/internal.rs:44
   3:     0x5616b392b8ec - failure::backtrace::Backtrace::new::he764f9bfd4f865b9
                        at /home/udoprog/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.3/src/backtrace/mod.rs:111
   4:     0x5616b2dbc019 - <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::h765cf9c59ef2155c
                        at /home/udoprog/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.3/src/error/error_impl.rs:19
   5:     0x5616b2db51e8 - <failure::error::Error as core::convert::From<F>>::from::h22d775fc32792a12
                        at /home/udoprog/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.3/src/error/mod.rs:36
   6:     0x5616b2d94bb6 - failure::error_message::err_msg::h96fd6ab063debaa8
                        at /home/udoprog/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.3/src/error_message.rs:12
   7:     0x5616b2c1688d - quickcfg::ring_bell::hd60e60cb927b4bf8
                        at src/main.rs:20
   8:     0x5616b2c168da - quickcfg::something::h98ab5d22e04a3248
                        at src/main.rs:24
   9:     0x5616b2c17658 - quickcfg::try_main::h8e376b3c3dd53ebe
                        at src/main.rs:63
  10:     0x5616b2c17298 - quickcfg::main::he714b694ac2ecf8a
                        at src/main.rs:52
  11:     0x5616b2c9ff3f - std::rt::lang_start::{{closure}}::h82daacb8cc7771f5
                        at /rustc/b68fc18c45350e1cdcd83cecf0f12e294e55af56/src/libstd/rt.rs:74
  12:     0x5616b397a632 - std::rt::lang_start_internal::{{closure}}::h72c946a380ebec10
                        at src/libstd/rt.rs:59
                         - std::panicking::try::do_call::h221042e980f16854
                        at src/libstd/panicking.rs:310
  13:     0x5616b398f349 - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:102
  14:     0x5616b397b0c3 - std::panicking::try::h8b8c3a00343d5ed4
                        at src/libstd/panicking.rs:289
                         - std::panic::catch_unwind::h9533bb130dfaffce
                        at src/libstd/panic.rs:398
                         - std::rt::lang_start_internal::h4511552c790253e4
                        at src/libstd/rt.rs:58
  15:     0x5616b2c9ff18 - std::rt::lang_start::he32bc485e59e6dd3
                        at /rustc/b68fc18c45350e1cdcd83cecf0f12e294e55af56/src/libstd/rt.rs:74
  16:     0x5616b2c1db89 - main
  17:     0x7fdf42a6309a - __libc_start_main
  18:     0x5616b2bb41a9 - _start
  19:                0x0 - <unknown>
Caused by: I don't feel like ringing the bell
```

**Comment by torkleyy** [comment]
Related: #690 #516 #1140 #460

**Comment by udoprog** [comment]
Hm, yeah. The errors ecosystem is a bit of a clustertruck right now and I could have dug deeper into the existing discussions.

@torkleyy So if I've read things correctly, the status quo is that someone should write an RFC?

**Comment by torkleyy** [comment]
I'd personally just go with `failure`. I know there's an argument that it will eventually end up in `std`, but it's what seems to be the standard right now (and I don't think it's good to just leave it as-is until the std situation improves). If that's something we can't agree on, an RFC would make sense, yes.

**Comment by torkleyy** [comment]
@amethyst/engine-team please comment whether you'd like an RFC.

**Comment by azriel91** [comment]
I'm happy with going with `failure`

**Comment by LucioFranco** [comment]
I would like to stay away from failure because in its current state its deprecated. I say we punt on this issue till rust has settled on a proper backtrace type.

**Comment by torkleyy** [comment]
Can you provide any references for its deprecation?

**Comment by LucioFranco** [comment]
@torkleyy Yes [here](https://github.com/rust-lang-nursery/failure#evolution)


> # Evolution
> Failure is currently evolving as a library. First of all there is work going on  in Rust itself to fix the error trait secondarily the original plan for Failure towards 1.0 is unlikely to happen in the current form.
>
> As such the original master branch towards 1.0 of failure was removed and master now represents the future iteration steps of 0.1 until it's clear what happens in the stdlib.
>
> The original 1.0 branch can be found in evolution/1.0.

**Comment by termhn** [comment]
Is the error handling a large enough issue right now to warrant two rewrites to go to current-`failure` (or whatever custom error solution we make in an RFC) and then to `std` errors or new-`failure` when the time comes? I'd say *probably* not, but perhaps it could be argued; if not then I say we just punt the issue until `std`/Rust ecosystem in general figures it out as @LucioFranco suggested.

**Comment by LucioFranco** [comment]
Really, error handling is a `1.0` issue instead of a current milestone. It doesn't affect our ability to create things. So I say punt until rust has settled or else we will rewrite error handling for the 3rd and 4th time by the time we hit `1.0`, and its not a good use of our time.

_Takes off my @fhaynes hat_

**Comment by LucioFranco** [comment]
Right, but I say we hold off on touching any error handling for now. Wait, till rust has it stabilized. I don't even think we should invest our time into it until backtraces are in and stabilized.

**Comment by udoprog** [comment]
I think Amethyst both short and long term can maintain its own `amethyst::Error` type.

It would implement `std::error::Error` both before, and after the proposed changes. This would be compatible with people using `failure` today, and any `std::error::Error` trait that shows up tomorrow.

**Comment by LucioFranco** [comment]
So related to the RFC https://github.com/rust-lang/rfcs/blob/master/text/2504-fix-error.md#how-this-impacts-failure do you think its worth it to implement everything based on `Fail` then migrate it over. What benefit do we get now that we wouldn't get by just waiting?

**Comment by LucioFranco** [comment]
@udoprog related to your `reporoto` stuff why should we implement that now when we can just wait for it to exist within rust? As I see it you are implementing it similar to how backtrace will be done, but that part of the API is not resolved. So to me, it doesn't make sense to invest resources into having our own for the short future.

**Comment by torkleyy** [comment]
@udoprog I think this can be closed, right?

**Comment by udoprog** [comment]
@torkleyy yeah, you're right.
