### ISSUE TITLE
UI example broken

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1215]
The "Editable" field cannot be edited correctly and is very likely to be bugged. The issue seems to be exclusive to Linux.

**Comment by torkleyy** [comment]
Issue likely caused by one of https://github.com/amethyst/amethyst/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+label%3A%22project%3A+ui%22+created%3A%3E2018-10-14+

**Comment by udoprog** [comment]
I can verify that it doesn't work for me either.
I bisected the issue to: ef197a5a

**Comment by happenslol** [comment]
Interesting, it works for me on windows. I'll get my linux machine and look at it, thanks a lot for the bisect!

**Comment by udoprog** [comment]
After reverting ef197a5, the editable box is editable for one round, then after unfocus I can't edit it any longer.

**Comment by happenslol** [comment]
@udoprog are you getting mouse events for anything else? I'm not even able to click the buttons on linux

**Comment by udoprog** [comment]
Yeah, I get mouse events.

**Comment by torkleyy** [comment]
Okay, some more observations:

* I can edit the field when clicking on the empty space next to the text, never when clicking on the text
* However, it does not work always; I need to click multiple times for it to work

This is what it looks like:

![screenshot from 2018-12-04 18-18-24](https://user-images.githubusercontent.com/23152057/49460183-0d78ce00-f7f1-11e8-8b2e-e99773249760.png)

**Comment by torkleyy** [comment]
The buffer creation is not exclusive to UI...

**Comment by torkleyy** [comment]
This issue (editing the text) is definitely something introduced after the last release.

**Comment by jojolepro** [comment]
I can't reproduce :P

**Comment by happenslol** [comment]
Tried reproducing this for a while and even though I can't, this is probably related to screen dimensions being reported wrongly with wayland. It's weird that this was introduced in the latest release since this issue should have been around for a while... I'll unassign myself though, since it works perfectly on my machine. I might come back to this if I get around to installing wayland on one of my linux machines.

**Comment by Xaeroxe** [comment]
I'm proposing a motion to move wayland into officially unsupported.  The amount of issues we get from them that we can't do anything about is way too high.

**Comment by jojolepro** [comment]
Trying to install wayland on my laptop. Will report if I have any success within a couple of hours.

**Comment by jojolepro** [comment]
I got it to install. Currently updating everything and going to test amethyst to see if I can replicate. DPI set to 2.0

**Comment by jojolepro** [comment]
owo https://github.com/amethyst/amethyst/pull/1219
