### ISSUE TITLE
Add chapter about coordinate system

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1216]
It would be nice to have some explanations how the coordinate system is defined, what the origin is, what to look for, etc.

**Comment by jojolepro** [comment]
For those who don't know: x right, y up, z from the screen towards you.

How coordinates in a 2d scene map to the screen depends only on the Camera settings (and if you use CameraOrtho).

Coordinates of the ui start at the bottom left (0,0) and grows towards the top right of the screen (screen_width, screen_height).

The size of the screen is stored in ScreenDimensions.
