### ISSUE TITLE
Test compiling Amethyst for webasm

### ISSUE THREAD

**Issue by fhaynes** [amethyst/amethyst#1227]
We know it probably doesn't work, but we need to capture exactly what deps have issues.

**Comment by luckielordie** [comment]
A first two second attempt shows this

https://gist.github.com/luckielordie/9a820206a0dd4394d4c62be04652be9e

I'm not as knowledgeable in Rust as I'd like to be so maybe someone can make more sense than me.

**Comment by jojolepro** [comment]
You have to build for release when testing wasm

**Comment by luckielordie** [comment]
Updated the gist :)

**Comment by LucioFranco** [comment]
heh I guess this makes sense `error[E0433]: failed to resolve: could not find unix in os`

**Comment by fhaynes** [comment]
Closing this as the experiment was done. Captured the user story here: https://openproject.amethyst-engine.org/projects/portability/work_packages/64/

**Comment by jugglerchris** [comment]
> 
> 
> Closing this as the experiment was done. Captured the user story here: https://openproject.amethyst-engine.org/projects/portability/work_packages/64/

This link seems broken - has it moved or is it covered elsewhere?

**Comment by LucioFranco** [comment]
@fhaynes can you take a look into this?

**Comment by fhaynes** [comment]
No one was using OpenProject, so I took it down. It did not have any additional information than this thread does.

Regarding WASM, Chrome 70 got experimental threading support in WASM that supports the pthread API (you can enable it via chrome://flags and enable WebAssembly Threads support. Note these are not WebWorkers; these can share memory and support the pthreads api. 

A current attempt to compile it using the wasm32-unknown-unknown target results in an error in the slice-dequeue crate being unable to find an allocator. I'll try emscripten in a bit once I am on a machine with it installed.

Allocation error below:

```bash
error[E0425]: cannot find function `allocation_granularity` in this scope
 --> /Users/fletcher/.cargo/registry/src/github.com-1ecc6299db9ec823/slice-deque-0.1.16/src/mirrored/buffer.rs:7:14
  |
7 |     let ag = allocation_granularity();
  |              ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
error[E0425]: cannot find function `allocation_granularity` in this scope
   --> /Users/fletcher/.cargo/registry/src/github.com-1ecc6299db9ec823/slice-deque-0.1.16/src/mirrored/buffer.rs:107:15
    |
107 |             * allocation_granularity();
    |               ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
error[E0425]: cannot find function `allocation_granularity` in this scope
   --> /Users/fletcher/.cargo/registry/src/github.com-1ecc6299db9ec823/slice-deque-0.1.16/src/mirrored/buffer.rs:125:41
    |
125 |         assert!(mem::align_of::<T>() <= allocation_granularity());
    |                                         ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
error[E0425]: cannot find function `allocation_granularity` in this scope
   --> /Users/fletcher/.cargo/registry/src/github.com-1ecc6299db9ec823/slice-deque-0.1.16/src/mirrored/buffer.rs:138:36
    |
138 |         debug_assert!(alloc_size % allocation_granularity() == 0);
    |                                    ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
error[E0425]: cannot find function `allocate_mirrored` in this scope
   --> /Users/fletcher/.cargo/registry/src/github.com-1ecc6299db9ec823/slice-deque-0.1.16/src/mirrored/buffer.rs:141:19
    |
141 |         let ptr = allocate_mirrored(alloc_size)?;
    |                   ^^^^^^^^^^^^^^^^^ not found in this scope
error[E0425]: cannot find function `deallocate_mirrored` in this scope
   --> /Users/fletcher/.cargo/registry/src/github.com-1ecc6299db9ec823/slice-deque-0.1.16/src/mirrored/buffer.rs:158:18
    |
158 |         unsafe { deallocate_mirrored(first_half_ptr, buffer_size_in_bytes) };
    |                  ^^^^^^^^^^^^^^^^^^^ not found in this scope
```

**Comment by Niedzwiedzw** [comment]
how did it go?
