### ISSUE TITLE
example "debug_lines" does not respond to 'esc' key.

### ISSUE THREAD

**Issue by Plotnus** [amethyst/amethyst#1234]
First time user here. I ran the "debug_lines" example and was surprised when it didn't close when I pressed my 'esc' key. Just some feedback.

**Comment by udoprog** [comment]
Thanks for the report!

It seems we have a number of examples where pressing 'esc' doesn't exit the application, and that makes the examples hard to work with. At least on Linux, unfocusing the window is kinda hard :).

We'll try to make sure all examples handle this (where applicable).

**Comment by torkleyy** [comment]
To elaborate, to make examples close on `Esc`, we need to handle the event in `State::handle_event` as follows:

https://github.com/amethyst/amethyst/blob/a4f13ff1fd43b1bdd2cf0a82c477b20ca088f245/examples/window/main.rs#L19-L27
