### ISSUE TITLE
Build tool to collect system information

### ISSUE THREAD

**Issue by udoprog** [amethyst/amethyst#1235]
Sometimes we get reports about rendering or other runtime issues that might depend on the system that it's being run on. In order to resolve these it would be useful to have a tool that gives us anonymous information we'd need to troubleshoot these.

Related to #1231

**Comment by torkleyy** [comment]
We have some basic information in the logging, maybe it could just be added there?

**Comment by jojolepro** [comment]
https://doc.rust-lang.org/std/panic/fn.set_hook.html
Of interest, but only work for panics.

**Comment by Xaeroxe** [comment]
@torkleyy I take it that since this issue is being opened that our log is getting completely overflowed with assets and graphics information and people are missing the initialization text.

**Comment by torkleyy** [comment]
Our logging is generally too verbose...

**Comment by khionu** [comment]
I actually have a crate WIP for gathering system information on Panic and distributing it to a set of callbacks. It supports taking a UserContext, so any tooling or whatnot to submit that information into a popup or to a server can be made available to the callbacks. I reserved the crate already `evac`

**Comment by torkleyy** [comment]
I think Sentry will take care of this?
