### ISSUE TITLE
Regression in sprite handling

### ISSUE THREAD

**Issue by udoprog** [amethyst/amethyst#1238]
I tried bumping amethyst for my test game and encountered an issue.

Commit 847feecc065bada047a4d8a85391343fa93109ec introduces some changes to sprite handling which breaks [asteroids-amethyst](https://github.com/udoprog/asteroids-amethyst).

The window i blank, and the log starts with this for every sprite loaded:

```
[ERROR][amethyst_assets::storage] "renderer::SpriteSheet": Asset "texture/ship.ron" (handle id: Handle { id: 0 }) could not be loaded: Failed to load asset with name "texture/ship.ron"
[DEBUG][amethyst_assets::storage] "audio::Source": Asset "audio/pew1.wav" (handle id: Handle { id: 0 }) has been loaded successfully
[ERROR][amethyst_assets::progress] Error loading handle 0, renderer::SpriteSheet, with name texture/ship.ron, caused by: Error(Asset("texture/ship.ron"), State { next_error: Some(Error(Format("SPRITE_SHEET"), State { next_error: Some(Error(Format("Failed to parse Ron file for SpriteSheet"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })
caused by: Error(Format("SPRITE_SHEET"), State { next_error: Some(Error(Format("Failed to parse Ron file for SpriteSheet"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })
caused by: Error(Format("Failed to parse Ron file for SpriteSheet"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
```

And then spams:

```
[WARN][amethyst_renderer::pass::flat2d::interleaved] Sprite sheet not loaded for sprite_render: `SpriteRender { sprite_sheet: Handle { id: 2 }, sprite_number: 0 }`.
```

**Comment by jojolepro** [comment]
@udoprog post the ron file in here. There was breaking changes I think so you probably need to update the file for it to get loaded.

**Comment by udoprog** [comment]
Aha, thanks @jojolepro. So all fields were`f32 -> u32`. If possible it would help if we include diagnostics for what went wrong when decoding the spritesheet, but this issue can be closed.

For anyone who finds this when searching, these are the changes I did:
https://github.com/udoprog/asteroids-amethyst/commit/47d6b909536b8a1c2cd085110b08bf9bfea69883#diff-c1acc5c5ea3dbd798ad9ca98f6ff505b
