### ISSUE TITLE
Add logging system

### ISSUE THREAD

**Issue by nchashch** [amethyst/amethyst#124]
There is a need for a logging system, to uniformly handle errors/provide meaningful debug messages for the user. Currently errors are reported using `println!`s and `panic!`s.

Probably an instance of `Logger` should be inside of the `Context` struct (or it should be a resource in the `World` as suggested in #125), so it is available globally.

**Comment by Emilgardis** [comment]
Yes, I believe the wisest move is to use [slog](https://github.com/slog-rs/slog).

**Comment by Aceeri** [comment]
Would we even need to put the instance of the Logger inside of the Context/resources? `slog` seems to work as a global variable similar to `println!` and the `log` crate.

**Comment by Emilgardis** [comment]
It can work as that but it can also provide an interface "per-module", see https://github.com/slog-rs/slog/blob/master/crates/example-lib/lib.rs

**Comment by Aceeri** [comment]
@Emilgardis Yeah, but I feel having a logger as a global is a big plus rather than having to pass it to everything.

**Comment by Emilgardis** [comment]
That sounds good to me. :+1:

**Comment by Emilgardis** [comment]
I'm still working on this, it has just been slow, but now that the context rewrite is done I feel like it can be done correctly.

**Comment by Emilgardis** [comment]
I'm going to do this by not having the logger as a resource, but also make clones of the root logger that can then be fetched with ´slog_scope::logger()`.

**Comment by Binero** [comment]
I think having the logger be accessible globally encourages bad design. One of the features of slog is to create 'forks' of loggers, and most importantly, to filter on them. It's best if somehow every System can have access to their own, and only their own logger.

**Comment by torkleyy** [comment]
@Binero could you elaborate on how "having the logger be accessible globally" encourages bad design?

**Comment by Binero** [comment]
@torkleyy I briefly touched the topic in the original post, but I will elaborate.

`slog` has many interesting features like filtering what is logged. If different systems share a common `Logger`, we cannot filter log messages by system anymore. This one one of the main features of `slog`. Usually when debugging, we debug one system and not other systems that might be unrelated. 

Every system should only have access to a specific fork of the global `Logger`, as that considerably increases the power of the logging framework by unlocking this powerful filtering capability.

@Emilgardis recommended the use of `slog_scope`, but `slog` actually discourages scoped logging [in its FAQ](https://github.com/slog-rs/slog/wiki/FAQ#do-i-have-to-pass-logger-around). The `slog_scope` crate itself also [warns](https://github.com/slog-rs/scope) it shouldn't usually be used, especially in libraries.

**Comment by torkleyy** [comment]
Ah, I see, so it doesn't directly encourage bad design but rather makes debugging more complicated. I think `slog` would indeed be a good choice.

**Comment by Rhuagh** [comment]
Well, the issue as I see it is propagation of child loggers to all systems. Either we need to enforce this on a system creation level (need a trait for System::new that takes a logger as arg, or put it on the bundle), or we have a root logger in `Application`, spawn off a "Systems logger" child and put as resource, and any system that need logging spawn a child logger off of that.

**Comment by Rhuagh** [comment]
And if someone doesn't spawn a child logger and just straight up use the "systems logger" they get to eat their own bullet so to speak.

**Comment by Rhuagh** [comment]
I could go either way, there are pros and cons to each solution.

**Comment by Binero** [comment]
@Rhuagh I think relying on people putting in extra effort will almost certainly backfire. If we allow bad design, it will almost certainly happen.

That said, it does seem that that is the only option. Unless we require systems to be constructed by us of course, but that might be equally as much cognitive overhead as we already have.

Maybe we could create a special `Logger`resource that returns a different logger-fork depending on the system that called it. Sound complicated though, and I don't tend to be in favour of this kind of magic.

**Comment by Rhuagh** [comment]
Tbh, if people want to do bad design, let them. As long as there is no roadblock to doing it well, I don't see why we should police what people do.

**Comment by Binero** [comment]
@Rhuagh A lot of Amethyst's success will depend on having a good and healthy ecosystem. Can you imagine the horrors of having competing conventions for how loggers should be created, identified, and what kind of structured data should be in them? 

That said, it might not be possible to enforce an easy and well designed system here, and even if we do figure out a system in the future, for now having a global logger we manually fork from is a good way to get us started.

**Comment by Rhuagh** [comment]
All we can do is provide a recommended way of handling logging, if people choose to misuse it, then so be it. I just don't think we should put safeguards at every crossroad, just because some people might misuse it.

**Comment by Binero** [comment]
My language might have been a bit too strong for the idea I am trying to express. I don't think we shouldn't even allow the user to hack their way into a bad system, but I think good design should be the default, and bad design actually requires the user to go out of their way.

**Comment by Rhuagh** [comment]
In that we can agree. For this specific case, I can't see a good way around it however, not without black magic or potentially spawning lots of unused child loggers.

**Comment by Xaeroxe** [comment]
Fixed in #513
