### ISSUE TITLE
Build fails because of broken dependency

### ISSUE THREAD

**Issue by hardliner66** [amethyst/amethyst#1244]
Just a FYI to update the failure dependency as soon as the new version gets published.

Currently the failure crate doesn't compile because of an update in the backtrace crate which prevents creating new project with the amethyst tools. (See: https://github.com/rust-lang-nursery/failure/issues/281 and https://github.com/rust-lang-nursery/failure/pull/279)

For others having the same problem, the temporary workaround is creating the project by hand and downgrade the backtrace sub-dependency with:
`cargo update -p backtrace --precise 0.3.9`

**Comment by Xaeroxe** [comment]
The crate causing this problem has been yanked, so I'm going to close this.
