### ISSUE TITLE
Example is impossible to build

### ISSUE THREAD

**Issue by anarelion** [amethyst/amethyst#1245]
I was trying to get some example to work, and it seems like it is impossible.

https://www.amethyst.rs/book/latest/concepts/system.html#getting-a-component-of-a-specific-entity
```
struct WalkPlayerUp {
    player: Entity,
}

impl<'a> System<'a> for WalkPlayerUp {
    type SystemData = WriteStorage<'a, Transform>;

    fn run(&mut self, mut transforms: Self::SystemData) {
        transforms.get_mut(self.player).unwrap().translate_y(0.1);
    }
}
```

There is no way to initialize the system with an entity, as systems are created before any entity can be created

**Comment by azriel91** [comment]
> There is no way
I wanna be sneaky and say "custom dispatcher" 😛, but yes &ndash; in the usual case you aren't able to.

When the docs are updated, we should encourage systems to be relatively stateless, save for *contextual data* (subjective) such as event channel `ReaderId`s

**Comment by fhaynes** [comment]
Closing this as the question was answered.
