### ISSUE TITLE
Release Amethyst 0.10.1

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#1247]
We need to get this PR in https://github.com/amethyst/amethyst/pull/1246

**Comment by Xaeroxe** [comment]
Side note: you only need to patch renderer for this to get out there.

**Comment by jojolepro** [comment]
No because the main amethyst crate uses exact versions for the sub crates

**Comment by Xaeroxe** [comment]
False, you've only specified a minimum patch version.  An exact version specification looks like this `amethyst_animation = "= 0.5.0"`

That's two equal signs and yes that's on purpose.

**Comment by Xaeroxe** [comment]
Some reading material, this is the default behavior: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements

and this is how you specify an exact version: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inequality-requirements

**Comment by Xaeroxe** [comment]
I went ahead and took the liberty of releasing `amethyst_renderer` 0.10.1 after I verified it was semver compatible.  Then I generated an amethyst project and opened up the lock file after compiling it.  Indeed, it was using `amethyst_renderer` 0.10.1.

I'll go ahead and close this.

**Comment by jojolepro** [comment]
Ah thanks for teaching me!
