### ISSUE TITLE
RFC: Refactor context

### ISSUE THREAD

**Issue by msiglreith** [amethyst/amethyst#125]
### Motivation

The `context` struct is a large struct containing different subsystems (https://github.com/amethyst/amethyst/blob/ea43b895e5f1d598928945030729f5d9fefac890/src/context/src/lib.rs#L53-L65), which is passed as `Arc<..>` to the different processor requiring to lock the whole context.
### Proposal

Split the `context` into the separated subsystems + a new `context` (with `delta_time`, `timestep`, ...).
The subsystems are added as resources to the world, allowing a more fine-granual locking and removes the need of a global object passed around trough the whole engine.
### Open questions

How does this influence the entity-component system in terms of scheduling?
Will we only have a single world in the future, if not how should the resources be handled?

**Comment by Aceeri** [comment]
I'm pretty sure resources in `specs` behave exactly the same as components, splitting it up into subsystems just means less blocking between systems to get access to the context (when they might not use it).

I think it is safe to assume we will only have one world, I'm not sure what benefits you would get by having multiple.

**Comment by Aceeri** [comment]
To add to this, I'm thinking maybe we should move the context out of a sub-crate and into the core library of amethyst (similar to the ecs processors and such), since it is highly interconnected with the other sub-crates. Thoughts?

**Comment by Aceeri** [comment]
I think this is actually a necessity. Currently the context is under a `Mutex` which doesn't really allow multiple readers or one writer like a `RwLock`. I think it might also be blocking every other system as well.

**Comment by msiglreith** [comment]
Seems to be fixed by https://github.com/amethyst/amethyst/pull/133.
