### ISSUE TITLE
[BUG] Using `UiFinder` and `UiTransform` in a System results in invalid Borrow

### ISSUE THREAD

**Issue by KuSpa** [amethyst/amethyst#1254]
Since `UiFinder` has its own handle to the `UiTransform` storage, it is impossible to use both in a system, because the storage would be borrowed twice. For an example see [here](https://gist.github.com/KuSpa/2ac2dee270e6b17067f0b8f16b9e5c68).

**Comment by Xaeroxe** [comment]
Thanks for finding this!  @torkleyy might be interested in it for the purpose of #1179

**Comment by KuSpa** [comment]
The storage member of `UiFinder` is only a `ReadStorage`. It won't help if a user needs the `UiFinder` as well as write access to the `UiTransforms`

**Comment by torkleyy** [comment]
Yeah. The solution is that it needs to be split, and only `Named` should be
used for this.

**Comment by jojolepro** [comment]
not stale

**Comment by jojolepro** [comment]
So I tried to fix this again, and it doesn't seem possible with the current design of ui widgets. As such, I recommend that everyone actually uses the `Named` component when they want to identify entities without using tag components. This way you'll be able to both find entities and access their UiTransform components.
