### ISSUE TITLE
Network development outside GitHub - Tracking issue

### ISSUE THREAD

**Issue by TimonPost** [amethyst/amethyst#1257]
Currently, the networking team is trying several things out.

- **Metrics**
We are looking into possible ways of gathering metrics and ways to display them. We decided to give [InfluxDB](https://www.influxdata.com/) a look with nflux, chornograf telegraf and kapacitor.
- **Networking Editor**
Because the amethyst editor is probably going to take a while before it will include some network specific options we decided to start experimenting with our own UI. We are using Xamarin for this. Why Xamaring? Because you can create cross-platform applications for both desktop/web/mobile at once. 

    What will this editor do? This will do things like deploying your application to AWS, GWS etc. Also features like real-time metrics and stuff could be added in here.
-  **Headless Server and Client Application.**
   We have created a headless server and client application and moved it into a docker image so that we can test some scenario's easier. 
- **User Stories**
  Defining user-stories for future networking. 
- **Roadmap**
  Creating a Roadmap for amethyst_network and amethyst

This work is not publicly available yet because Github is constraining us in some ways to freely develop and experiment with networking applications. We first have to figure the DevOps platform we are going to use. We have two options: Azure DevOps (TFS) or Gitlap (GOLD).

**Comment by TimonPost** [comment]
Currently, our user stories are located here. They might change in the process of developing or the acceptance criteria might be changed. 

[Azure Devops](https://dev.azure.com/amethyst-foundation/amethyst_network/_workitems/recentlyupdated/)

**Comment by TimonPost** [comment]
We also created a wiki page with some documents about contribution, roadmap, and introduction. 

[Wiki Pages](https://dev.azure.com/amethyst-foundation/amethyst_network/_wiki/wikis/amethyst_network.wiki?wikiVersion=GBwikiMaster&pagePath=%2FAmethyst%20Network)

**Comment by TimonPost** [comment]
Headless server and client and a docker image can be located here.

[Server-Client docker](https://dev.azure.com/amethyst-foundation/e2e-tests)

**Comment by fhaynes** [comment]
Closing this as it is out of date. If needed, we should put the links in the forum.
