### ISSUE TITLE
Skybox improvements

### ISSUE THREAD

**Issue by derekdreery** [amethyst/amethyst#1260]
I'm just going to copy the shaders in for the skybox verbatim:

<details><summary>vertex shader:</summary>

```glsl
#version 150 core

layout (std140) uniform VertexArgs {
    uniform mat4 proj;
    uniform mat4 view;
    uniform mat4 model;
};

in vec3 position;
in vec2 tex_coord;

out VertexData {
    vec3 position;
    vec2 tex_coord;
} vertex;

void main() {
    mat4 view_without_translation = view;
    view_without_translation[3].xyz = vec3(0.0f, 0.0f, 0.0f);
    vec4 vertex_position = model * vec4(position, 1.0);

    vertex.position = vertex_position.xyz;
    vertex.tex_coord = tex_coord;

    gl_Position = (proj * view_without_translation * vertex_position).xyww;
}
```

</details>

<details><summary>fragment shader:</summary>

```glsl
#version 150 core

in VertexData {
    vec3 position;
    vec2 tex_coord;
} vertex;

out vec4 out_color;

uniform vec3 zenith_color;
uniform vec3 nadir_color;

void main() {
    vec3 normalized_position = normalize(vertex.position.xyz);
    vec3 horizon_color = mix(nadir_color, zenith_color, smoothstep(-1., 1., normalized_position.y));
    out_color = vec4(horizon_color, 1.0f);
}
```
</details>

I'm not sure I fully understand how these shaders work. Looking at [this gamedev stackexchange answer](https://gamedev.stackexchange.com/questions/60313/implementing-a-skybox-with-glsl-version-330), it is possible to just render a single quad covering the viewport, and essentially use the inverse of the projection matrix to calculate how the texture is mapped to this quad. I'm pretty sure this method could be modified to use arbitrarily complex gradients as well.

Do other people have any thoughts on this?

**Comment by fhaynes** [comment]
Closing this, including it in the user stories here: https://community.amethyst-engine.org/t/amethyst-user-story-collection/628/3
