### ISSUE TITLE
Discussion on restructuring of the Book

### ISSUE THREAD

**Issue by jchitel** [amethyst/amethyst#1261]
Hello there!

(I apologize in advance if it seems like I'm rambling. I'm a stickler for providing context and I want to provide some juicy material to start this discussion.)

I've been studying Amethyst for about a month or so. By "studying" I mean reading the existing documentation and source code. I find that I learn best by doing deep dives into the source code of projects and understanding how they work inside the black box. I am now in the process of doing this with Amethyst. I'm fairly new to Rust as well, but I've found that Rust lends itself extremely well to readability and traceability, and I'm happy to say that all of the Amethyst code I've been reading has been very easy to follow!

However, I understand that most developers (myself included) usually need some higher-level documentation when getting introduced to a new project. This is why API documentation and any "books" provided by library authors can go a long way toward reducing the learning curve for developers. 

As far as I've been able to see, Amethyst's API documentation is mostly sufficient. Many items seem to be well-documented. However, API documentation is only useful once you've actually started writing code. I don't know anyone that can just pop open API docs and use that to learn how to use a library from scratch. Everything's sorted alphabetically, so there's no clear starting point, and the relationships between all of the components are buried deep. But it isn't the purpose of those docs to provide these things. They are optimized so that you can easily find something *specific* that you're looking for.

This is where high-level documentation like the Book comes in. However, I've found that this is the most difficult kind of documentation to write. Developers that are well-versed in the inner workings of the library need to distill all of their knowledge into easily-digestible pieces, which takes time and mental effort. Additionally, while API documentation is meant to be read more like a technical specification, a Book needs to be written more like prose; it needs to be easy to read and it needs to flow well so that readers can stay on track and follow a smooth process of learning. This difficulty is quite evident in Amethyst's Book. The spirit is certainly there, but it's pretty clear at this point that it's really just a mishmash of topics that specific people decided needed to be documented. The first few sections are quite good: the intro, the "getting started" section, the concepts, and the tutorial (obviously it needs to be finished) are all sufficient. But the rest of the docs are pretty disorganized. It's difficult to see the purpose of some of the sections in the grand scheme of things, and there is very little flow after the tutorial.

Granted, I'm still learning how to properly write good (not just "sufficient") documentation myself, but I do have some experience in this area as a fairly tenured developer that has read and written a lot of documentation. And I'd love to facilitate discussion toward restructuring the Book, both for my own learning and to help set other developers up for the best chance of success with Amethyst!

I've already had some discussions on [this issue](https://github.com/amethyst/amethyst/issues/986), where I kind of got off track in the wee hours of the morning and started rambling. I specified some fairly clear structure there, but after having thought about it for a while, I think a different strategy would be better.

One of the best pieces of documentation I've ever read is the [Rust Book](https://doc.rust-lang.org/book/). The key feature of this book is the flow. It starts by setting expectations. It sets up expectations for the writers of the book: readers should have some experience in at least one programming language, so the book doesn't have to muddy itself with details about how to program or basic programming concepts. It also sets up expectations for the readers of the book: there is a short walkthrough of each chapter of the book, where you can jump based on what you're looking for, and descriptions of formatting used in the book.

The structure of the book is roughly:
* The introduction introduces Rust, sets expectations, and explains how to use the book
* Chapter 1 is a "getting started" section, i.e. what you need to do to start writing and running Rust code, and a basic Hello World program.
* Chapter 2 is a short tutorial describing the basics of Rust
* Chapters 3-11 walk through Rust's basic features and how to use them, starting with the 101 stuff and working up through all of the essentials of Rust from simple to intermediate.
* Chapter 12 is a more intermediate tutorial taking into account everything from the previous chapters.
* Chapters 13-19 cover more advanced features like closures, smart pointers, concurrency, and unsafe Rust.
* Chapter 20 is an advanced tutorial taking into account the full breadth of Rust features.
* Appendices provide more "reference-like" materials and things that developers don't *need* to be able to use Rust, but might be more "nice-to-know".

Amethyst's Book should provide a similar structure. Aside from the fact that the Rust book is an excellent piece of documentation in general, it would also be a good idea to follow the precedent set by the Rust team and use a structure that Rust developers will likely recognize. This will help to establish trust that Amethyst's documentation is "on par" with the documentation for Rust.

There may not be quite as much material as Rust's book, so there may not be a need for tutorials sprinkled throughout, but perhaps there might be another tutorial for the end of the Book that goes a little deeper than the Pong tutorial. Something for a small 3D game would be an excellent idea.

Here's a rough outline I'm thinking of for the Amethyst Book:

* Introduction (left as-is, obviously taking into account the changes made to the rest of the book)
* Chapter 1: Getting started (left as-is)
* Chapter 2: Pong tutorial: next go straight into the Pong tutorial. Things may need to be refactored to establish context that was previously set up in the Concepts chapter, but it definitely makes sense to go straight into a walkthrough that shows concrete examples of the concepts.
* Chapter 3: Concepts (left basically as-is, maybe with more details or other core concepts that don't have a page)
* Chapters 4-(n-1): More in-depth walkthroughs of how to use the Amethyst API. What are my options for building a State? a GameData? a Pipeline? an Application? How do I create renderable entities? What are the standard workflows for populating a scene? A chapter on each of the sub-crates of Amethyst (where it makes sense) will probably be a good place to start. The goal is to walk through the entire API, barring anything internal or not commonly used. Developers should be able to read through these chapters and come out knowing exactly what tools they need to get the job done.
* Chapter n: A final tutorial that covers nearly all of the concepts covered in the rest of the book. A 3D game that makes use of everything from animation, to audio, to advanced UI, to network features would be great. This is probably going to be the hardest part due to the sheer amount of pieces that likely need to go into such a game. Maybe a rudimentary online FPS? A multiplayer Minecraft clone?
* Appendices: As described above, these should be more "reference-like" chapters that provide things like lists and indices.
  * Appendix A: Built-in Components: the ECS Components provided by Amethyst out of the box
  * Appendix B: Built-in Systems: the ECS Systems provided by Amethyst out of the box
  * Appendix C: Built-in Bundles: the System bundles provided by Amethyst out of the box
  * Appendix D: Built-in Resources: the Resources provided by Amethyst out of the box

Let me know what you think of this outline. Feel free to suggest any changes or improvements, or documentation-related subjects I didn't mention that should be taken into account. Also feel free to provide any links to existing issues that talk about this kind of stuff. This issue can be a sort of "directory" for that kind of stuff.

Thanks in advance!

**Comment by khionu** [comment]
Hi, thanks for your input! We're glad to have all the feedback we can get, however we are trying to hold our discussions more on the Community Forums. I actually started a thread [here](https://community.amethyst-engine.org/t/mdbook-going-forwards/234/6). I'd encourage you to continue that thread, or start a new one if you would like to approach the topic from another scope.

**Comment by fhaynes** [comment]
Closed as this was moved to the forums.
