### ISSUE TITLE
Amethyst crashes when change resolution

### ISSUE THREAD

**Issue by tuananh** [amethyst/amethyst#1262]
macOS 10.14
Amethyst 0.12.2

It happens pretty often when changing resolution.

**Comment by LucioFranco** [comment]
huh strange, could you also verify that you have run `cargo update`? if not can you list steps to reproduce and I will see if I can fix it. thanks.

**Comment by tuananh** [comment]
> Sorry can you double check your amethyst version? We don't have a 0.12

I just check again, it's 0.12.2

**Comment by khionu** [comment]
Can you make a Gist of the contents of your `Cargo.toml`?

Our confusion comes from that there is definitely no version of Amethyst, or any of its modules, that have a version higher than `0.10`. You can see that for yourself in our [releases](https://github.com/amethyst/amethyst/releases) and through our [root crate](https://crates.io/crates/amethyst).

**Comment by tuananh** [comment]
@khionu 	I'm so sorry guys. Wrong repo. it's supposed to be this https://github.com/ianyh/Amethyst
