### ISSUE TITLE
High dpi issues on osx

### ISSUE THREAD

**Issue by cs2dsb** [amethyst/amethyst#1264]
I've just bumped my Amethyst version to master (from 0.9) and I'm seeing a few window size and rendering size issues on OSX (10.13.6 High Sierra if that matters.)

The first issue is the window is half the size of what is specified in display config. I think this commit 19538454a60549d05ee6a0ffd54cef6d7bdc8ad0 is the cause. On my 1dpi screen I'd expect 1920*1080 to be full screen but it's half of that. One problem is with_config is using the dpi of the primary monitor, which might not be where the window is launched. The other is I'm not sure treating the value in display config as a physical size is necessarily correct - if you do, the window will be a different size depending on what screen you put it on. I can also see that you might want to specify a lower physical resolution on a big screen for performance reasons - I don't know if there is a single size answer that works for all cases. I tried a few games I've got installed as test cases and they don't handle this well:
 - Darkest Dungeon seems to use the resolution as logical. The window is fullscreen on the 1dpi screen and mostly fullscreen on the 2dpi screen but the text looks pixelated on the 2dpi screen so I don't think they are scaling up the physical size. It lists the full phyisical resolution of the 2dpi screen as an option but when you pick it the window is 4x the size of the 2dpi screen - I can't get to the resize handle to see if scaling it down results in crisp text.
 - Hollow Knight seems to use the resolution as physical. The window is fullscreen on the 1dpi screen and 1/4 of the screen on the 2dpi screen. You can't set a resolution higher than the logical size of the display (or maybe it's just hardcoded to support up to 1080, who knows.) The result of this is on the high dpi screen the window is either 1/4 of the display or, if you manually resize it, the output is scaled up and lower quality.

I was just going to submit a PR but when I found the issue that caused it had changed this deliberately I thought it might need some more discussion.

I guess can think of a few options:
  1. config specifies physical size and the window size is different depending on which display it's on - this will look pretty janky when dragging between screens
  2. config specifies logical size and the physical size is dpi * this depending on which display it's on - this could have perf issues if you want a fullscreen window on a very high res/dpi screen
  3. some confusing hybrid where the config specifies logical size when windowed and physical when fullscreen
  4. add both logical and physical to config, resizing would be confusing
  5. add a scaling option {always 1, match display dpi, other...}
  6. kick the issue to the game dev by exposing some extra stuff in the renderer so it's easy to modify this behaviour

Whatever ends up being implemented I think it needs some extra documentation pointing out what it does and the edge cases where it falls down.

The second issue is on the 1dpi screen, the output is rendered in the bottom left quarter of the window. Resizing doesn't fix it. It's scaled down so the full screen of output is visible.

![image](https://user-images.githubusercontent.com/1633999/50233843-35992d00-03ac-11e9-898a-830713e7cb4c.png)

Cheers!

**Comment by jojolepro** [comment]
If you have screens with different DPI, I kind of expect things to break. However, the second issue isn't expected.

From what I understand, you have your primary monitor with a dpi of 2.0 and a secondary one (that you are using as your primary) with a dpi of 1.0?

The way I made it is that it uses the physical pixel size for everything. On a 4k monitor with a dpi of 2.0, if you set the screen size to 1080p, it will take half of the screen, and not all of it. This is intended, because that is already what the renderer was doing for the opengl canvas. I'll open a feature request issue about the resolution downscale, because its true that you can gain a lot of performance from that.

**Comment by cs2dsb** [comment]
Yea, I've got a 1080p 1dpi screen plugged into my laptop which has a 2dpi screen.

The thing that makes me think the window should have a fixed logical size is because dragging between screens shouldn't change the size of a window - I don't think I've ever seen an app do that.

Regarding 1080 being a small window on a 4k monitor, doesn't that depend on how the user has their dpi scaling set up? I haven't used a high dpi screen on modern windows but doesn't the user have the option to change the dpi expressly for the purpose of scaling stuff on their high res screen? Otherwise what does DPI do, if your window is always 100x100 physical pixels, the DPI makes no difference?

I'm basing my understanding off reading the [winit dpi documentation](https://www.amethyst.rs/doc/latest/doc/glutin/dpi/index.html) and the way OSX presents it's DPI scaling so I'm happy to be proved wrong.

**Comment by cs2dsb** [comment]
Something else I just noticed is that the UI text is tiny now too - previously the font in 25pt was a good readable size on both screens, now it's half the size. I assume this is related to the DPI changes but if not I'll investigate/raise another issue for it.

**Comment by jojolepro** [comment]
The text size change is intended. We plan on enforcing the scaling via a better layouting system, instead of relying on the dpi with often resulted in totally broken interfaces.

**Comment by jojolepro** [comment]
I'm not sure how we should support different dpi on different screens. Maybe there's a winit method to get the "current screen" the window is on? (which would be weird if you are on two screens)

**Comment by cs2dsb** [comment]
In RenderBuilder::build:
```
let cached_hidpi_factor = window.get_hidpi_factor();
```
That gets the dpi for the screen the window is really on. I added some printfs to with_config and build to print the dpis:
```
[INFO][amethyst_renderer::renderer] hidpi: 2
[INFO][amethyst_renderer::renderer] cached_hidpi_factor: 1
```
So, when launched on a 1dpi screen, the hidpi in with_config from the primary monitor is 2 and when the window gets created it's dpi is reported as 1.

So what you could do is resize the window at this point if the DPI isn't what you expected.

Personally I think the config should specify the logical size like it used to and the DPI causes the physical size to change rather than the logical size - this seems to line up with the behaviour described in winit.

Window size = logical size
Opengl size = physical size

The logic around resizing doesn't need to change, the renderer is always window size * dpi, this same logic would work when resizing on either screen and also moving the window between screens.

The only change in behaviour is going back to the previous behaviour in with_config that sets the size without taking the dpi into account - i.e. just setting the logical size to what is specified in config.

The primary reason I think this is correct is because it results in consistent behaviour: currently, if you launch it at 1dpi and drag it to 2dpi the window will be half the size that it would be if you started it at 2dpi and dragged it to 1dpi. This is how all other apps work on my system. I can't really demonstrate it but launching a new finder window on one then dragging it to the other results in the same size window.

Since it's currently not possible to specify resolution independent of window size, what is the benefit of specifying physical size in the config file? It seems more logical and in line with what winit describes to specify the logical size rather than physical size.

**Comment by jojolepro** [comment]
I changed it because before we needed to multiply by the hidpi factor at a lot of places in the engine, which was causing inconsistent behavior between systems (wayland, X11, windows, etc). I won't be able to look into this for around a week, because I'll be using a single screen setup. I think it would be possible to resize the window when it detects a dpi change, like you said.

**Comment by icefoxen** [comment]
Now this looks familiar: https://github.com/ggez/ggez/issues/409

**Comment by torkleyy** [comment]
Still relevant

**Comment by Frizi** [comment]
@torkleyy i'm not sure, this is likely to be fixed already, need some testing. We've changed rendering backend and upgraded winit, so it's likely that the issue is fixed

**Comment by jojolepro** [comment]
probably not stale

**Comment by distransient** [comment]
@cs2dsb has this issue been fixed for you?

**Comment by cs2dsb** [comment]
My mac broke and I'm currently using a linux box with no high dpi screen so I'm not able to test unfortunately. Happy if it's closed and someone (maybe me if I pick my game up again) reopens when they need to deploy to OSX.

**Comment by distransient** [comment]
👍 If anyone experiences this issue, comment and will reopen.
