### ISSUE TITLE
Resolution Downscale

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#1265]
Feature request: Have a way to downscale the resolution of the renderer.

## Why
If you have a 4k monitor and performance issue, you could make the renderer draw a stretched 1080p canvas instead, gaining a lot of performance.

## How
@omni-viral knows this better than me. :D

**Comment by Xaeroxe** [comment]
I thought we already supported this.  What needs to change?

**Comment by jojolepro** [comment]
Resizing the opengl render target from user-space code. Probably via a resource (ScreenDimensions with a render_scaling field?)

IIRC the opengl resize code is in amethyst_renderer/src/renderer.rs (or system.rs)

**Comment by omni-viral** [comment]
`rendy-graph` has present pass that copies data to presentable image. It should be configured to resize if resolution not match.

**Comment by khionu** [comment]
Does that make this solved, then?

**Comment by omni-viral** [comment]
Not yet. Present pass should do this. It doesn't. So let issue be open :)

**Comment by jojolepro** [comment]
Soon :tm: hopefully? :)

**Comment by hyperum** [comment]
Does this issue still exist? Amethyst examples run with ~200ms lags between input and display on an HiDPI laptop, perhaps this is the reason.

**Comment by omni-viral** [comment]
Is ~150ms lag accompanied by 6-7 fps?

**Comment by Frizi** [comment]
This is now technically supported through rendergraph setup. Do we want to provide something extra to make it easier?

**Comment by jojolepro** [comment]
1) Should be usable as a method that looks a bit like .set_render_resolution(x_pixels, y_pixels)
2) Should be configurable at runtime (people will want to change it in option menus while the game runs)
Recreating the whole graph is acceptable if required I think.

**Comment by omni-viral** [comment]
@jojolepro `set_render_resolution` method will affect which render output? Window? Offscreen? Intermediate.
I think it should be something more flexible because you want to configure all of this via config
