### ISSUE TITLE
Macro to make tag components

### ISSUE THREAD

**Issue by NateDogg1232** [amethyst/amethyst#1268]
I wrote a macro for making tag components, and I was wondering if this could be integrated somehow. I think it's a great macro to have which reduces some of the boilerplate which goes along with making a tag component.

```Rust
macro_rules! make_tag_component {
     ($tag_name: ident) => {
         pub struct $tag_name;

         impl Component for $tag_name {
             type Storage = NullStorage<Self>;
         }

         impl Default for $tag_name {
             fn default() -> Self {
                 $tag_name
             }
         }
     }
 }
```

It can be easily used as so:
```Rust
/// Tag to be on the player so the input system knows which entity to modify
make_tag_component!(PlayerTag);
```

**Comment by onbjerg** [comment]
I think you could just use `specs_derive`:

```rust
#[derive(Component)]
#[storage(NullStorage)]
struct PlayerTag;
```

**Comment by jojolepro** [comment]
Also you are missing derives in your macro: Debug, Copy, Clone, Serialize, Deserialize

I do like the idea however.

**Comment by khionu** [comment]
I mean, if we have `specs_derive`, I see little use in this. 2 extra lines for derives vs a single line total for a macro seems less than worth it. Maybe if there were other cases for quick-create components....

**Comment by jojolepro** [comment]
I would suggest asking people in the specs repo if they want it in specs or specs-derive. If not, you can always put it in a public crate, with other macros you come up with.

**Comment by khionu** [comment]
Since this is not actually in the scope of Amethyst specifically, I'm going to close this issue. I don't want to discourage you from making things that make your development easier, however. As Jojo mentioned, you can always propose this to Specs or put it in your own crate to publish.
