### ISSUE TITLE
failed to run custom build command for 'proc-macro2 v0.4.24'

### ISSUE THREAD

**Issue by Wolfman13** [amethyst/amethyst#1272]
I tried running pong_tutorial_01 and pong_tutorial_02. Both gave the same error message:

PONG_TUTORIAL_01:
   Updating crates.io index
   Compiling proc-macro2 v0.4.24                                                
   Compiling unicode-xid v0.1.0                                                 
   Compiling semver-parser v0.7.0                                               
   Compiling cc v1.0.27                                                         
   Compiling libc v0.2.45                                                       
   Compiling serde v1.0.82                                                      
   Compiling arrayvec v0.4.9                                                    
   Compiling nodrop v0.1.13                                                     
   Compiling rand_core v0.3.0                                                   
   Compiling void v1.0.2                                                        
   Compiling cfg-if v0.1.6                                                      
   Compiling stable_deref_trait v1.1.1                                          
   Compiling memoffset v0.2.1                                                   
   Compiling nix v0.11.0                                                        
   Compiling scopeguard v0.3.3                                                  
   Compiling lazy_static v1.2.0                                                 
   Compiling xml-rs v0.8.0                                                      
   Compiling num-traits v0.2.6                                                  
   Compiling rayon-core v1.4.1                                                  
   Compiling bitflags v1.0.4                                                    
   Compiling khronos_api v2.2.0                                                 
   Compiling crossbeam-utils v0.5.0                                             
   Compiling rayon v1.0.3                                                       
   Compiling khronos_api v3.0.0                                                 
   Compiling byteorder v1.2.7                                                   
   Compiling autocfg v0.1.1                                                     
   Compiling downcast-rs v1.0.3                                                 
   Compiling linked-hash-map v0.5.1                                             
   Compiling either v1.5.0                                                      
   Compiling num-complex v0.2.1                                                 
   Compiling typenum v1.10.0                                                    
   Compiling nix v0.12.0                                                        
   Compiling pkg-config v0.3.14                                                 
   Compiling same-file v1.0.4                                                   
   Compiling atom v0.3.5                                                        
   Compiling num-integer v0.1.39                                                
   Compiling mopa v0.2.2                                                        
   Compiling xdg v2.2.0                                                         
   Compiling matrixmultiply v0.1.15                                             
   Compiling tuple_utils v0.2.0                                                 
   Compiling num-bigint v0.2.2                                                  
   Compiling libm v0.1.2                                                        
   Compiling num-derive v0.2.3                                                  
   Compiling num-iter v0.1.37                                                   
   Compiling rustc-demangle v0.1.11                                             
   Compiling fnv v1.0.6                                                         
   Compiling nonzero_signed v1.0.2                                              
   Compiling rawpointer v0.1.0                                                  
   Compiling futures v0.1.25                                                    
   Compiling percent-encoding v1.0.1                                            
   Compiling mint v0.5.1                                                        
   Compiling adler32 v1.0.3                                                     
   Compiling unicode-xid v0.0.4                                                 
   Compiling cgmath v0.16.1                                                     
   Compiling safemem v0.3.0                                                     
   Compiling num-rational v0.2.1                                                
   Compiling quote v0.3.15                                                      
   Compiling approx v0.1.1                                                      
   Compiling color_quant v1.0.1                                                 
   Compiling lzw v0.10.0                                                        
   Compiling failure_derive v0.1.3                                              
   Compiling siphasher v0.2.3                                                   
   Compiling build_const v0.2.1                                                 
   Compiling scoped_threadpool v0.1.9                                           
   Compiling wavefront_obj v5.1.0                                               
   Compiling hetseq v0.2.0                                                      
   Compiling xi-unicode v0.1.0                                                  
   Compiling ansi_term v0.11.0                                                  
   Compiling unicode-width v0.1.5                                               
   Compiling hound v3.4.0                                                       
   Compiling seahash v3.0.5                                                     
   Compiling vec_map v0.8.1                                                     
   Compiling matches v0.1.8                                                     
   Compiling claxon v0.3.2                                                      
   Compiling strsim v0.7.0                                                      
   Compiling fluent-locale v0.4.1                                               
   Compiling float-ord v0.2.0                                                   
   Compiling unicode-segmentation v1.2.1                                        
   Compiling unicode-normalization v0.1.7                                       
   Compiling proc-macro2 v0.3.8                                                 
error: failed to run custom build command for `proc-macro2 v0.4.24`             
could not execute process `/media/wolfman13/Jean-Jacque/Game_Dev/Rust/Tutorials/GameEngine/Amethyst/pong_tutorial_01/target/debug/build/proc-macro2-94661c64c69d56ee/build-script-build` (never executed)
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `libc v0.2.45`                    
could not execute process `/media/wolfman13/Jean-Jacque/Game_Dev/Rust/Tutorials/GameEngine/Amethyst/pong_tutorial_01/target/debug/build/libc-63518811a0716c2c/build-script-build` (never executed)
warning: build failed, waiting for other jobs to finish...
error: build failed

PONG_TUTORIAL_02:
    Updating crates.io index
   Compiling proc-macro2 v0.4.24                                                
   Compiling unicode-xid v0.1.0                                                 
   Compiling cc v1.0.27                                                         
   Compiling semver-parser v0.7.0                                               
   Compiling libc v0.2.45                                                       
   Compiling serde v1.0.82                                                      
   Compiling arrayvec v0.4.9                                                    
   Compiling nodrop v0.1.13                                                     
   Compiling rand_core v0.3.0                                                   
   Compiling void v1.0.2                                                        
   Compiling cfg-if v0.1.6                                                      
   Compiling memoffset v0.2.1                                                   
   Compiling lazy_static v1.2.0                                                 
   Compiling nix v0.11.0                                                        
   Compiling stable_deref_trait v1.1.1                                          
   Compiling xml-rs v0.8.0                                                      
   Compiling scopeguard v0.3.3                                                  
   Compiling num-traits v0.2.6                                                  
   Compiling bitflags v1.0.4                                                    
   Compiling khronos_api v2.2.0                                                 
   Compiling rayon-core v1.4.1                                                  
   Compiling byteorder v1.2.7                                                   
   Compiling khronos_api v3.0.0                                                 
   Compiling crossbeam-utils v0.5.0                                             
   Compiling rayon v1.0.3                                                       
   Compiling autocfg v0.1.1                                                     
   Compiling same-file v1.0.4                                                   
   Compiling nix v0.12.0                                                        
   Compiling num-complex v0.2.1                                                 
   Compiling either v1.5.0                                                      
   Compiling downcast-rs v1.0.3                                                 
   Compiling pkg-config v0.3.14                                                 
   Compiling linked-hash-map v0.5.1                                             
   Compiling typenum v1.10.0                                                    
   Compiling xdg v2.2.0                                                         
   Compiling num-integer v0.1.39                                                
   Compiling matrixmultiply v0.1.15                                             
   Compiling mopa v0.2.2                                                        
   Compiling atom v0.3.5                                                        
   Compiling rustc-demangle v0.1.11                                             
   Compiling fnv v1.0.6                                                         
   Compiling futures v0.1.25                                                    
   Compiling libm v0.1.2                                                        
   Compiling tuple_utils v0.2.0                                                 
   Compiling num-derive v0.2.3                                                  
   Compiling nonzero_signed v1.0.2                                              
   Compiling num-bigint v0.2.2                                                  
   Compiling num-iter v0.1.37                                                   
   Compiling rawpointer v0.1.0                                                  
   Compiling safemem v0.3.0                                                     
   Compiling num-rational v0.2.1                                                
   Compiling cgmath v0.16.1                                                     
   Compiling mint v0.5.1                                                        
   Compiling adler32 v1.0.3                                                     
   Compiling unicode-xid v0.0.4                                                 
   Compiling percent-encoding v1.0.1                                            
   Compiling color_quant v1.0.1                                                 
   Compiling approx v0.1.1                                                      
   Compiling quote v0.3.15                                                      
   Compiling lzw v0.10.0                                                        
   Compiling scoped_threadpool v0.1.9                                           
   Compiling build_const v0.2.1                                                 
   Compiling siphasher v0.2.3                                                   
   Compiling failure_derive v0.1.3                                              
   Compiling xi-unicode v0.1.0                                                  
   Compiling unicode-width v0.1.5                                               
   Compiling ansi_term v0.11.0                                                  
   Compiling hetseq v0.2.0                                                      
   Compiling wavefront_obj v5.1.0                                               
   Compiling vec_map v0.8.1                                                     
   Compiling hound v3.4.0                                                       
   Compiling seahash v3.0.5                                                     
   Compiling matches v0.1.8                                                     
   Compiling claxon v0.3.2                                                      
   Compiling strsim v0.7.0                                                      
   Compiling float-ord v0.2.0                                                   
   Compiling fluent-locale v0.4.1                                               
   Compiling unicode-normalization v0.1.7                                       
   Compiling unicode-segmentation v1.2.1                                        
   Compiling proc-macro2 v0.3.8                                                 
error: failed to run custom build command for `proc-macro2 v0.4.24`             
could not execute process `/media/wolfman13/Jean-Jacque/Game_Dev/Rust/Tutorials/GameEngine/Amethyst/pong_tutorial_02/target/debug/build/proc-macro2-94661c64c69d56ee/build-script-build` (never executed)
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by khionu** [comment]
Just to get some initial troubleshooting out of the way, can you run `cargo update && cargo clean` and try again? Also, can you get us the output of `rustc --version`, and double check your Amethyst version?

**Comment by Wolfman13** [comment]
ran cargo update && cargo clean and then ran the tutorial again:

PONG_TUTORIAL_02
   Compiling proc-macro2 v0.4.24                                                
   Compiling unicode-xid v0.1.0                                                 
   Compiling cc v1.0.27                                                         
   Compiling semver-parser v0.7.0                                               
   Compiling arrayvec v0.4.9                                                    
   Compiling libc v0.2.45                                                       
   Compiling serde v1.0.82                                                      
   Compiling rand_core v0.3.0                                                   
   Compiling void v1.0.2                                                        
   Compiling cfg-if v0.1.6                                                      
   Compiling nodrop v0.1.13                                                     
   Compiling memoffset v0.2.1                                                   
   Compiling stable_deref_trait v1.1.1                                          
   Compiling xml-rs v0.8.0                                                      
   Compiling num-traits v0.2.6                                                  
   Compiling nix v0.11.0                                                        
   Compiling lazy_static v1.2.0                                                 
   Compiling scopeguard v0.3.3                                                  
   Compiling bitflags v1.0.4                                                    
   Compiling khronos_api v2.2.0                                                 
   Compiling rayon-core v1.4.1                                                  
   Compiling crossbeam-utils v0.5.0                                             
   Compiling byteorder v1.2.7                                                   
   Compiling rayon v1.0.3                                                       
   Compiling khronos_api v3.0.0                                                 
   Compiling num-complex v0.2.1                                                 
   Compiling pkg-config v0.3.14                                                 
   Compiling autocfg v0.1.1                                                     
   Compiling nix v0.12.0                                                        
   Compiling same-file v1.0.4                                                   
   Compiling downcast-rs v1.0.3                                                 
   Compiling typenum v1.10.0                                                    
   Compiling either v1.5.0                                                      
   Compiling linked-hash-map v0.5.1                                             
   Compiling mopa v0.2.2                                                        
   Compiling matrixmultiply v0.1.15                                             
   Compiling xdg v2.2.0                                                         
   Compiling num-integer v0.1.39                                                
   Compiling atom v0.3.5                                                        
   Compiling futures v0.1.25                                                    
   Compiling nonzero_signed v1.0.2                                              
   Compiling fnv v1.0.6                                                         
   Compiling num-bigint v0.2.2                                                  
   Compiling libm v0.1.2                                                        
   Compiling tuple_utils v0.2.0                                                 
   Compiling rustc-demangle v0.1.11                                             
   Compiling rawpointer v0.1.0                                                  
   Compiling num-derive v0.2.3                                                  
   Compiling num-iter v0.1.37                                                   
   Compiling adler32 v1.0.3                                                     
   Compiling safemem v0.3.0                                                     
   Compiling percent-encoding v1.0.1                                            
   Compiling unicode-xid v0.0.4                                                 
   Compiling num-rational v0.2.1                                                
   Compiling mint v0.5.1                                                        
   Compiling cgmath v0.16.1                                                     
   Compiling color_quant v1.0.1                                                 
   Compiling approx v0.1.1                                                      
   Compiling lzw v0.10.0                                                        
   Compiling quote v0.3.15                                                      
   Compiling failure_derive v0.1.3                                              
   Compiling siphasher v0.2.3                                                   
   Compiling build_const v0.2.1                                                 
   Compiling scoped_threadpool v0.1.9                                           
   Compiling hetseq v0.2.0                                                      
   Compiling ansi_term v0.11.0                                                  
   Compiling unicode-width v0.1.5                                               
   Compiling wavefront_obj v5.1.0                                               
   Compiling xi-unicode v0.1.0                                                  
   Compiling hound v3.4.0                                                       
   Compiling vec_map v0.8.1                                                     
   Compiling claxon v0.3.2                                                      
   Compiling seahash v3.0.5                                                     
   Compiling strsim v0.7.0                                                      
   Compiling matches v0.1.8                                                     
   Compiling fluent-locale v0.4.1                                               
   Compiling float-ord v0.2.0                                                   
   Compiling unicode-segmentation v1.2.1                                        
   Compiling unicode-normalization v0.1.7                                       
   Compiling proc-macro2 v0.3.8                                                 
error: failed to run custom build command for `proc-macro2 v0.4.24`             
could not execute process `/media/wolfman13/Jean-Jacque/Game_Dev/Rust/Tutorials/GameEngine/Amethyst/pong_tutorial_02/target/debug/build/proc-macro2-94661c64c69d56ee/build-script-build` (never executed)
warning: build failed, waiting for other jobs to finish...
error: build failed  

rustc --version: rustc 1.31.0 (abe02cefd 2018-12-04)
Amethyst: Amethyst CLI 0.7.6

**Comment by khionu** [comment]
I can't reproduce, but I was just having bizarre issues similar to this the other day, so I think the situation may have a similar solution. Since this isn't likely an Amethyst-specific issue, can you join [our Discord](https://discord.gg/GnP5Whs) so we can help you there?

**Comment by LucioFranco** [comment]
Wow, this is really strange. My initial thought is that something weird is happening with your toolchain, so I would recommend maybe uninstalling it and reinstall the whole toolchain. This is likely something with the upgrade path from rustup/cargo. The other option is to try a fresh clone?

**Comment by khionu** [comment]
Fresh clone was going to be my next recommendation, but I figured the Discord was a better venue for continuing this troubleshooting process, but I guess we can continue here.

**Comment by Wolfman13** [comment]
I uninstalled multirust and reinstalled normal rust. 
rustc: 1.30.0
cargo: 1.30.0
amethyst: Amethyst CLI 0.7.6
(When I ran "cargo install amethyst_tools" it told me: "warning: be sure to add `/home/wolfman13/.cargo/bin` to your PATH to be able to run the installed binaries" which it didn't do before I started getting the error.

I still get the same error message...

**Comment by Wolfman13** [comment]
And I have all the required dependencies installed and updated to the newest version

**Comment by udoprog** [comment]
> I'm also having issues with amethyst_tools. When I use the command "amethyst new hello-world" it says:
> 
> amethyst: command not found
> 
> And then when I say "cargo install amethyst_tools" it says:
> 
> ```
> Updating crates.io index
> ```
> Installing amethyst_tools v0.7.6
> error: binary `amethyst` already exists in destination as part of `amethyst_tools v0.7.6`
> Add --force to overwrite

This looks like you don't have $HOME/.cargo/bin in your $PATH.

I really suggest we move this to Discord so that you can get more active help!

**Comment by Wolfman13** [comment]
I ended up removing multirust. Reinstalling Rustc. Reinstalling amethyst_tools. And now it works for some reason.. No clue how or why... But it works

**Comment by torkleyy** [comment]
multirust? I think that's pretty old. I'd recommend using https://rustup.rs/ instead.

**Comment by khionu** [comment]
All's well that ends well! Glad it was resolved! If the issue resurfaces, please feel free to reopen the issue.

**Comment by counter-reverse** [comment]
@Wolfman13 I met the same error as in your log.

Can you tell how you solve this error here or in discord please?
