### ISSUE TITLE
Semantics behind popping a State

### ISSUE THREAD

**Issue by KuSpa** [amethyst/amethyst#1275]
When popping a State, nothing happens except for the removing of the State from the Stack. Every resource and entity stays part of the `World`, if not especially removed. This conflicts with my (humble) opinion of removing a State: Popping a State should (or at least provide the possibility to) remove all resources/entities created during this state. At the moment, there may be different behavior depending on if the State was already created once or not. Which seems odd.

My Proposal would be to have a `DeleteOnExitState`(with a better name ^.^) or a `type DeleteOnExit=bool` in the State trait.

**Comment by jojolepro** [comment]
Add a `Removal` component and in the state on_exit use exec_removal.

**Comment by khionu** [comment]
To elaborate further, in `on_open` you would create some Key related to that State Instance to store in a [Removal](https://www.amethyst.rs/doc/latest/doc/amethyst_utils/removal/struct.Removal.html) component. Then in `on_close` you would call [exec_removal](https://www.amethyst.rs/doc/latest/doc/amethyst_utils/removal/fn.exec_removal.html) with that Key.

**Comment by tripokey** [comment]
@KuSpa I also feet that a simple API to tie some entities to the lifetime of the current state would be nice to have. I have a small experiment for it using extension traits on https://github.com/tripokey/destructor

**Comment by fhaynes** [comment]
Closing as this seems to have been answered. Please re-open if needed.
