### ISSUE TITLE
Compiling amethyst from amethyst new fails

### ISSUE THREAD

**Issue by andreasterrius** [amethyst/amethyst#1283]
I did a plain amethyst install and when I tried to compile the project, it gave me this compilation error

```
  Compiling gfx_glyph v0.13.1
   Compiling amethyst_assets v0.6.0
   Compiling amethyst_network v0.3.0
error[E0599]: no method named `keep_cached_custom_layout` found for type `glyph_brush::glyph_brush::GlyphBrush<'font, H>` in the current scope
   --> /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_glyph-0.13.1/src/lib.rs:238:26
    |
238 |         self.glyph_brush.keep_cached_custom_layout(section, custom_layout)
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `keep_cached` found for type `glyph_brush::glyph_brush::GlyphBrush<'font, H>` in the current scope
   --> /home/x/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_glyph-0.13.1/src/lib.rs:250:26
    |
250 |         self.glyph_brush.keep_cached(section)
    |                          ^^^^^^^^^^^
```

My rust version is rustc 1.33.0-nightly (ddab10a69 2018-12-23)

**Comment by Xaeroxe** [comment]
Thanks for the report, someone might have broken semver.  I'll check it out.

**Comment by Xaeroxe** [comment]
I can't reproduce this no matter what compiler version I'm using, I even grabbed the nightly from 2018-12-23 and I still can't reproduce it.  I don't see any recently yanked versions for `glyph_brush` either so I'm doubtful it's that. Honestly I'm kind of stumped and probably need more info about your environment to stand a chance.

However, that all being said we're only going to fix this in our repository if we can reproduce it with a `stable` release branch compiler. If we can't, then an issue needs to be filed with rust-lang instead.

**Comment by andreasterrius** [comment]
it still gives me the same error.
But since this isolated to me, this is probably because of my environment.

anyway I think I'll use ggez for now since my aim just to play around with rust with a simple gamejam.

**Comment by andreasterrius** [comment]
Sorry to reopen the issue, but I followed the referenced issue ^, 
seems like cargo update fixes the problem
I can compile amethyst just fine now.
