### ISSUE TITLE
unable to compile gfx_glyph

### ISSUE THREAD

**Issue by tglanz** [amethyst/amethyst#1285]
Hi!

Possibly related to https://github.com/amethyst/amethyst/issues/1283

Im trying to compile from source - clone, then cargo build, but with no luck. The build process fails when trying to compile `gfx_glyph` - looks like a dependency for amethyst_ui. Have also tried to change the version to 0.13.1 with the same outcome.

The highest release tag on which i managed to compile and run the pong example successfully is v0.8.0. Compiling both v0.9.0 and v0.10.0 yields the same failure like in the head.

Interestingly, i saw that all of the build suites are passing successfully so it might be a machine issue? or my lack of knowledge on the build process?

Im running on windows, and have tried to compile using both of the stable / nightly toolchains
- stable-x86_64-pc-windows-msvc
- nightly-x86_64-pc-windows-msvc

The error message i receive below

> error: cannot find macro `__log_module_path!` in this scope
>    --> {some local and irrelevant path}\gfx_glyph-0.13.1\src\lib.rs:356:24
>     |
> 356 |                     if log_enabled!(log::Level::Warn) {
>     |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     |
>     = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
> 
> error: aborting due to previous error

Thank you for your work!!

**Comment by Xaeroxe** [comment]
This seems like a different error, though it's interesting that it's with the same library.  What you've described is basically exactly my environment, and I was able to build and run the latest version of amethyst.  I'm curious though, if you clone the repository for gfx_glyph and try to build it do you get the same error?

Here's the repo: https://github.com/alexheretic/glyph-brush

Let me know what you find, and thanks for filling an issue!

**Comment by Xaeroxe** [comment]
It's also just occurred to me that your graphics processing hardware might be relevant, somehow, so can you post that info too?

**Comment by tglanz** [comment]
thanks for the reply.

glyph-brush repo compiles successfully (with gfx-glyph in it). So, i tried changing the dependency in amethyst_ui to the file system - Still won't compile.

My graphics hardware is geforce gtx 960m

btw, is this related perhaps? https://github.com/rust-lang-nursery/log/commit/2f52d6ce91998cc6e85a17385613aa7243109dc3
As i understand, this change should make it so we won't need macro_use, which is how amethyst_ui does extern log (without macro use). So, because this change affected log 0.4.6, i tried switching the dependencies of log 0.4 to 0.4.6 across all amethyst crates, and now it compiles successfully, and the examples are running. Perhaps something with out caches/registries made me get 0.4 and you 0.4.6?

**Comment by Xaeroxe** [comment]
That is very helpful.  I think it's time to upgrade our minimum log patch version.  Thank you!

**Comment by jojolepro** [comment]
rustup update
cargo update
cargo clean
cargo build

Make sure you are building ametjyst 0.10 and let us know if you still get the issue. Thanks!

**Comment by tglanz** [comment]
Awesome! will start playiing pong :)
Thanks again for your work, the project looks great

**Comment by jojolepro** [comment]
I assume that means the issue is fixed? :D

**Comment by tglanz** [comment]
sure, thank you
