### ISSUE TITLE
Switch amethyst_renderer to using rendy

### ISSUE THREAD

**Issue by khionu** [amethyst/amethyst#1290]
The dominoes are starting to fall as `gfx-hal` now has a 0.1 release. `rendy` is getting ready for their release, so it is time for Amethyst to start the work to move to `rendy`.

**Comment by Xaeroxe** [comment]
I agree

**Comment by fhaynes** [comment]
Closing this due to age and that the integration has not yet been completed. When it is, we can revisit this.
