### ISSUE TITLE
Add releasing.md and outline how to create a patch

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/amethyst#1291]
Will fill in more later but this is a tracking issue to create and discuss a proper releasing.md doc to describe how amethyst should release major, minor and patch versions.

cc @Xaeroxe @fhaynes

**Comment by torkleyy** [comment]
When I released the renderer patch I wondered if we could have some log where we document Git revisions used for publishing.

When you cherry pick commits onto others and release versions from diverged branches having the last released rev can be of use.

Maybe we can agree to use tags?

**Comment by fhaynes** [comment]
Closing this due to age and lack of activity.
