### ISSUE TITLE
Move GH templates into .github

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1293]
Apparently, issue / PR templates need to be in a directory called `.github` (or top-level) to be recognized.

We should

* review the current template(s)
* eventually add more
* move them into `.github`

**Comment by onbjerg** [comment]
Done in a5ccfda20a95e2c5e4bb9f537d16d0c5c1491f73?

**Comment by torkleyy** [comment]
Yes, thank you @onbjerg.
