### ISSUE TITLE
Prefabs for sprite animation

### ISSUE THREAD

**Issue by adrien-ben** [amethyst/amethyst#1294]
Hi,

I am trying to animate some sprites. I tried to do it as in the animation example but failed to do so because `SpriteRenderPrimitive` does not implement De/Serialize. 

Is it an actual issue or just me failing to understand how it works ?

Here is how I tried to set up the animation loader :

```rust
/// My prefab data containing the animation set prefab
type HeroPrefabData = (
    Option<AnimationSetPrefab<u32, SpriteRender>>,
);

fn main() -> amethyst::Result<()> {
    // ...
    let game_data = GameDataBuilder::default()
        .with(PrefabLoaderSystem::<HeroPrefabData>::default(), "", &[])
        .with_bundle(AnimationBundle::<u32, SpriteRender>::new(
            "control", "sampler",
        ))?
        .with_bundle(
            RenderBundle::new(pipe, Some(display_config.clone())).with_sprite_sheet_processor(),
        )?;
    
    // ...
}
```

**Comment by azriel91** [comment]
Hiya, sorry for the late reply. That's right, the `AnimationSetPrefab` has a trait bound for the primitive to be `De/Serialize`. The `SpriteRenderPrimitive` looks like this:

```rust
pub enum SpriteRenderPrimitive {
    /// A spritesheet id
    SpriteSheet(Handle<SpriteSheet>),
    /// An index into a spritesheet
    SpriteIndex(usize),
}
```

The `SpriteSheet(Handle<SpriteSheet>),` variant has a `Handle`, which is [not serializable](https://github.com/amethyst/amethyst/blob/v0.10.0/amethyst_assets/src/storage.rs#L460-L472) -- a handle has a transient ID generated at runtime during loading, so even if we *could* implement `Serialize` / `Deserialize`, I'm not sure we *should*.

So, how are we meant to store sprite animation prefabs then? Good question, I *think* it would mean implementing something that can read a persistent ID, and at runtime, load the animation, then map the persistent ID to the transient one and link up like that.

**Comment by fhaynes** [comment]
Closing this as it doesn’t see to be actionable.

**Comment by adrien-ben** [comment]
Hi, thanks for the reply @azriel91. As a workaround a created a new asset type which is basically a map of sprite indices indexed by time. 

I'll dive into the assets management code as soon as I have some more time to see if I can make it work. 

Why closing the issue though ? Don't you think being able to load sprite animations would be a nice feature ?

**Comment by fhaynes** [comment]
hey @adrien-ben,
We're doing issue cleanup and trying to get them more organized. We now have issue templates for new feature requests, bugs, and feature modifications, so I'd rather it be recreated via that.

**Comment by adrien-ben** [comment]
Ok @fhaynes, I'll recreate the issue using the template then. Thank you !
