### ISSUE TITLE
[BUG] UiImage is rendered twice

### ISSUE THREAD

**Issue by KuSpa** [amethyst/amethyst#1305]
## Description

When I [create](https://github.com/KuSpa/RockRaiders/pull/52/commits/b55c0624e17662b7d86fc17f5bf985b10331243a#diff-ffb9f38893aa9593ab0d7c1f84bbb9f6R63) an Entity with a parent, an UiImage and an UiTransform, the image is rendered once as expected (irt the parent, which is a UiElement as well with UiTransform) But a second time on the bottom of the screen as well... 

## Reproduction Steps

1.Clone https://github.com/KuSpa/RockRaiders/tree/ui_map
2. Run
2.5 hit tab to enter level state. hit space to reveal the area.
3. click on the house to create a man
4. click on the man and navigate him to the top line of the terrain (see the red quad on the map)(by clicking on the destination tile)
5. see a second red quad appearing on the bottom, which is not expected

## What You Expected to Happen

A red quad on my map

## What Actually Happened

A red Quad on the map, but another red Quad on the bottom of the screen as well.

## Screenshots and Logs

![image](https://user-images.githubusercontent.com/18664378/50573415-c7089600-0dd3-11e9-804c-7eda43bb8568.png)

## Your Environment

1. OS Ubuntu 18.04.1 LTS
3. Amethyst version 0.10.0

**Comment by jojolepro** [comment]
Can you create a minimal example with showing the issue. The issue could be caused by amethyst's ui system, or by your game, so it would be nice to make sure the bug isn't from the game's logic before investigating it.

Also, can you do a `cargo update` and see if this still happens?

**Comment by Xaeroxe** [comment]
Hm I'm trying to replicate this and all I'm getting is a black screen when I launch the game on Windows 10. I'll try again when I get home.

**Comment by KuSpa** [comment]
@Xaeroxe you need to hit tab and then space.
@jojolepro the bug remains after `cargo update`.

sorry for not responding, I was ill and did not work :(. I'll do a minimal working (or buggy^^)  asap.

**Comment by KuSpa** [comment]
[This](https://gist.github.com/KuSpa/c12cc9abd7565c029ff132cc66bce777 ) is basically an empty amethyst project with a single static `UiImage` (grey), an invisible `RockRaider` entity in the world and an `UiMap` resource(which is only used to delete older UiElements). The bug still occurs.

**Comment by jojolepro** [comment]
You probably don't want to create and delete entities each frame like that. Modify existing ones if you can. The bug you arr having is due (i think) to the layout system not layouting AFTER you are creating thr entity, and BEFORE the rendering. Also entities.delete runs at the end of the dispatcher loop, after rendering. This means all your entities live for 2 frames, and only one has layout applied to it.

**Comment by KuSpa** [comment]
Thank you very much for the detailed explanation. I guess I don't want to create and delete entities each frame like that then ^^.  I'll rewrite that :)

**Comment by jojolepro** [comment]
You could change the order in the dispatcher if you put your System before the UiBundle. You would still draw two entities at once, but at least they would be at the correct position.
