### ISSUE TITLE
[BUG] Crashes Creating Window

### ISSUE THREAD

**Issue by sammerry** [amethyst/amethyst#1308]
## Description

I'm not sure if this is due to my setup or if the the project i've created is missing something.
after running `aethyst new <project>` and copying in resources from the pong example 01 (blank window) i get the following error

```
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.10.0
[INFO][amethyst::app] Platform: x86_64-unknown-linux-gnu
[INFO][amethyst::app] Amethyst git commit: 
[INFO][amethyst::app] Rustc version: 1.33.0-nightly Nightly
[INFO][amethyst::app] Rustc git commit: 9eac386342c601b14311b435f2b6d314fc817bb5
thread 'main' panicked at 'assertion failed: desc.min <= desc.max && desc.max < info.levels', /home/lappy/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.5/src/tex.rs:989:5
```

## Reproduction Steps

1. generate a new project
2. copy in resources from `examples/assets` and `examples/pong/pong_tutorial_01/resources/`
3. `cargo run`

## What You Expected to Happen

a blank window should show up

## What Actually Happened

a window briefly flashes and closes after exception

## Screenshots and Logs

```
[DEBUG][amethyst_renderer::pipe::effect] Creating raw constant buffers
[INFO][gfx_device_gl::factory] 	Created buffer 1
[INFO][gfx_device_gl::factory] 	Created buffer 2
[DEBUG][amethyst_renderer::pipe::effect] Set global uniforms
[DEBUG][amethyst_renderer::pipe::effect] Process Color/Depth/Blend outputs
[DEBUG][amethyst_renderer::pipe::effect] Finished building effect
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.10.0
[INFO][amethyst::app] Platform: x86_64-unknown-linux-gnu
[INFO][amethyst::app] Amethyst git commit: 
[INFO][amethyst::app] Rustc version: 1.33.0-nightly Nightly
[INFO][amethyst::app] Rustc git commit: 9eac386342c601b14311b435f2b6d314fc817bb5
thread 'main' panicked at 'assertion failed: desc.min <= desc.max && desc.max < info.levels', /home/lappy/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.5/src/tex.rs:989:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

## Your Environment

1. Linux version 4.19.8_1 (void-buildslave@vm1-a-lej-de) (gcc version 8.2.0 (GCC)) #1 SMP PREEMPT Sat Dec 8 19:05:10 UTC 2018
2. 0.10.0

## Additional Context

Pulling the master branch and running the pong_tutorial_01 works and a window is displayed. The same code copied into a new project does not run.

**Comment by jojolepro** [comment]
you'll want to release

**Comment by Xaeroxe** [comment]
(Technically a 0.10.3 because even though 0.10.2 is yanked we still can't use that version number)

**Comment by ndarilek** [comment]
Is there a workaround for this until 0.10.3 is released? Can I downgrade an indirect dependency, and if so, how would I go about that?

**Comment by LucioFranco** [comment]
@ndarilek it has been released on crates.io as of about 30 min ago.

**Comment by torkleyy** [comment]
This is resolved now. Please re-open if you're still experiencing this bug.
