### ISSUE TITLE
[BUG] clear_target colour is off, gamma problem?

### ISSUE THREAD

**Issue by Temeez** [amethyst/amethyst#1309]
## Description
The `clear_target` colour is too light? Some sort of gamma problem?

## Reproduction Steps
Create a new amethyst project and edit the clear_target to: `.clear_target([0.415, 0.721, 0.341, 1.0], 1.0)`.

## What You Expected to Happen

See the image.

## What Actually Happened

See the image.

## Screenshots and Logs

![image](https://user-images.githubusercontent.com/3135774/50588450-c7b03380-0e8a-11e9-9136-3f6f2fc421e5.png)

## Your Environment

1. Operating System: Windows
2. Operating System Version: 7
3. Version of Amethyst: df1bea8a274ad26e8abe5a738dac40eafcea5db8

**Comment by Temeez** [comment]
Never mind, discord helped. I got what I wanted with `.clear_target([0.415f32.powf(2.4), 0.721f32.powf(2.4), 0.341f32.powf(2.4), 1.0], 1.0)` (SRGB to linear) but damn it's way too hard.

**Comment by imjasonmiller** [comment]
I ended up using the following, which might be a bit easier to read if you're picking 8-bit colors:

```rust
RenderToWindow::from_config_path(display_path)?.with_clear([
    // Linear colorspace
    f32::powf((30.0 / 255.0 + 0.055) / 1.055, 2.4), // R
    f32::powf((30.0 / 255.0 + 0.055) / 1.055, 2.4), // G
    f32::powf((30.0 / 255.0 + 0.055) / 1.055, 2.4), // B
    1.0,                                            // A
]),

```
