### ISSUE TITLE
Amethyst logger ignores wrong env var values

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1316]
## Reproduction Steps

1. Launch any Amethyst game using the provided logger
2. Set `AMETHYST_LOG_STDOUT` to `this_is_not_allowed`
3. Notice no error is reported

## What You Expected to Happen

The application prints an error message.

## What Actually Happened

The variable's value was just silently ignored.

**Comment by khionu** [comment]
It's standard that env vars set to not accepted values is treated as not set at all. What behaviour does it exhibit in comparison to the "intended" values?

**Comment by torkleyy** [comment]
> It's standard that env vars set to not accepted values is treated as not set at all.

Oh, that I didn't know.

> What behaviour does it exhibit in comparison to the "intended" values?

Let's say you do `AMETHYST_LOG_STDOUT=no`, it will still pipe the log messages.

**Comment by torkleyy** [comment]
I just thought it's pretty clear this variable is meant for Amethyst, so signalling that it's ignored sounds reasonable to me.

**Comment by khionu** [comment]
We could extend accepted values to include the standard True/False dualities ie "yes/no".
