### ISSUE TITLE
[BUG] Ortho camera utils do not adjust the camera aspect ratio if screen is not resized

### ISSUE THREAD

**Issue by JameeKim** [amethyst/amethyst#1319]
## Description
Using `OrthoCamera` component and `CameraOrthoSystem` system successfully adjusts the rendered view to the screen size when the window is resized, but not so if the window is not resized at all. This is critical when the game is run in fullscreen mode.

## Your Environment

- Version of Amethyst = 0.10.0 (but also applies to the current master branch)

## Additional Context
The cause of this problem seems to be [this part](../blob/master/amethyst_utils/src/ortho_camera.rs#L222) in the [`CameraOrthoSystem`](../blob/master/amethyst_utils/src/ortho_camera.rs#L207).
```rust
pub struct CameraOrthoSystem {
    aspect_ratio_cache: f32,
}

impl<'a> System<'a> for CameraOrthoSystem {
    ...
    fn run(&mut self, (dimensions, mut cameras, ortho_cameras): Self::SystemData) {
        let aspect = dimensions.aspect_ratio();

        if aspect != self.aspect_ratio_cache {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            self.aspect_ratio_cache = aspect;

            for (mut camera, ortho_camera) in (&mut cameras, &ortho_cameras).join() { ... }
        }
}
```

**Comment by Xaeroxe** [comment]
Sorry can you clarify something for me

if we go from

1920x1080 fullscreen: false

to

1920x1080 fullscreen: true

you're encountering a rendering bug because we didn't adjust the camera, to render at the same resolution it was rendering at before?

I'm very confused, can you post a screenshot of the incorrect rendering output?

**Comment by JameeKim** [comment]
![streched](https://user-images.githubusercontent.com/26984355/50702867-8f307580-1095-11e9-9817-72a32d5e39ed.png)

**Comment by Xaeroxe** [comment]
Ok, and maybe now one of the correct output to compare?

**Comment by JameeKim** [comment]
Sorry, did that by accident.

It happens regardless of whether the game is fullscreen or not, but I specified the fullscreen mode because in fullscreen mode you can't adjust the screen size.

The picture below is when the game is started. (Sorry for the bad scene, I'm still working on it)
![streched](https://user-images.githubusercontent.com/26984355/50702867-8f307580-1095-11e9-9817-72a32d5e39ed.png)

When I resize the screen just by little, the rendered view suddenly snaps into the correct one.
![adjusted](https://user-images.githubusercontent.com/26984355/50702996-02d28280-1096-11e9-9c94-6bbef3130836.png)

**Comment by Xaeroxe** [comment]
Got it! Thanks. Seems like we need to force a re-eval on startup.

**Comment by JameeKim** [comment]
The part of the code I pointed out, it is saving the screen aspect ratio even when the camera is not present in the game world. The camera is loaded using gltf after a loading state, so maybe we should either
a) check the moment when the camera is being loaded
or
b) use a "brute-force" update in the `run` method of the system, by removing the `if`

**Comment by Xaeroxe** [comment]
Or just store the cache in the `ortho_camera` component. That seems the most viable solution to me.
