### ISSUE TITLE
[MAINTENANCE] Deprioritize DjSystem

### ISSUE THREAD

**Issue by ndarilek** [amethyst/amethyst#1322]
## Note

This type of request is for things like `unwrap()`s that snuck into production. They aren't likely to cause problems and aren't really a bug, but should be updated. Other examples include formatting updates, dependency updates, or code simplification. 

## Description

Right now the `DjSystem` is front and center when I create an `AudioBundle`. I can apparently pass a no-op closure if I don't want to use it, but if I create an `AudioBundle`, I get it whether I want it or not. I think it should be optional. Just as display initialization doesn't make any huge assumptions about my configuration or what components I need, the audio system shouldn't saddle me with a music system I may not need.

## Reason

First, what is music?

 * Game music is almost certainly music.
 * Is the cockpit ambience of my spaceship also music? It shares many of the characteristics--loops infinitely, not spatialized--but the DjSystem apparently only handles a single track at once, so I'd essentially need to create a new system that duplicates many of `DjSystem`'s characteristics.
 * Is my non-spatialized weapon shot also music? It doesn't loop, but will probably also be non-spatialized so will need its own system. Maybe `DjSystem` could be expanded to handle non-localized non-looping sounds, but then it quickly becomes unwieldy and general.

Further, while this system seems to support the simplest of cases--playing a single music track on infinite loop and occasionally changing it--I feel like I'd quickly hit its limitations and have to write my own system for handling music, non-spatialized level ambience, etc. And, while such a system should probably exist and may even be a refinement of the current `DjSystem`, it probably shouldn't be so integral that it must be initialized with `AudioBundle::new()`.

I think that `DjSystem` should either be initialized independently, or should be initialized via another method on `AudioBundle`. It shouldn't be required. It may also need improvements, but I think such improvements are a separate discussion from whether or not I should be able to completely opt out of it and build my audio system up from emitters and listeners.

I plan on being a heavy user of the audio subsystem, and am happy to take this change on. I just want a temperature check before going ahead with it.

## Impact

My understanding is that the audio system isn't heavily used, and it definitely isn't documented, so the only impact would likely be updating examples and crate documentation.

**Comment by jojolepro** [comment]
The current audio system is heavily under-developed and not very used. I don't even have sound at all because of a rodio bug (the main dependency).

We currently have no audio team, or anyone in charge of maintaining the crate. You are welcome to make the changes you want and open pull requests to improve it. :)

Thanks!

**Comment by ndarilek** [comment]
Awesome. My main interest in Amethyst is building [audio 
games](https://en.wikipedia.org/wiki/Audio_game), so if I do manage to 
wrap my head around the audio subsystem (which doesn't look too 
complicated now that I study it) I'd be interested in forming an audio 
team. AFAIK rodio doesn't currently support wasm, so it may be worth 
swapping that out once wasm support starts to look a bit more possible, 
or even before then so it isn't a blocker. Anyhow, happy to do the work, 
as Amethyst isn't useful for me without it. :)


What is your blocker issue, out of curiosity?

**Comment by jojolepro** [comment]
https://github.com/tomaka/rodio/issues/173

I didn't take the time to investigate too much.

**Comment by Rhuagh** [comment]
I would argue the audio subsystem needs a thorough redesign, it has received very little love.

**Comment by Xaeroxe** [comment]
aww I wasn't aware there was this much animosity towards the current audio implementation. Well I do want to say that as the original author of the audio system I take no issue with redesigns and improvements.

I just want to make you aware of the following:

- When I made this playing audio with Rust was not easy, and I made several enhancements to rodio to get us to where we are today. Maybe that's changed, maybe it hasn't.
- I wrote the 3D audio system used by rodio and implemented it for Amethyst, you may need to re-author it again if you want to switch dependencies.
- The music system was designed for "ambient background music" if a track has any degree of 3D space awareness then it's not ambient background music. For 3D space aware sound emitters I made this: https://www.amethyst.rs/doc/latest/doc/amethyst_audio/struct.AudioEmitter.html#method.set_picker

**Comment by Xaeroxe** [comment]
I've had a lot of problems with Linux audio even outside of Amethyst personally, though I'm not sure what to attribute those to. Maybe someone more familiar with audio on Linux can comment on the matter. Switching away from pulse audio might fix it, but I'm not really qualified to say.

**Comment by ndarilek** [comment]
PR submitted, hope I got everything right.

**Comment by Xaeroxe** [comment]
A lot of those can be achieved via a picker and `System`s, however you're
correct the 3D API surface area is somewhat lacking. Maybe improving that
will be my next project. My intent with most of the audio system is to make
no assumptions as to what the user needs and instead just make sure I give
them the tools to implement what they need.
