### ISSUE TITLE
Discord Invite Link is Broken

### ISSUE THREAD

**Issue by sunjay** [amethyst/amethyst#1323]
![image](https://user-images.githubusercontent.com/530939/50729912-3d790100-1110-11e9-82f9-661d52f66f6e.png)

This happens with the link in the README: https://discord.gg/amethyst

**Comment by LucioFranco** [comment]
Hi @sunjay! This is quite strange in both regular and incognito it seems to redirect to a proper invite url. I wonder if there is a weird caching issue going on.

cc @amethyst/community-team

**Comment by khionu** [comment]
What's your Discord Username and Discriminator? Ie mine is `Khionu#0047`

**Comment by sunjay** [comment]
You're right! It works incognito. I was able to join via the desktop client. I guess it was just my browser. Thanks for your help. :smile:
