### ISSUE TITLE
[BUG] Result<PathBuf, Error> cannot be formatted with the default formatter

### ISSUE THREAD

**Issue by sunjay** [amethyst/amethyst#1325]
## Description

If you create a project with amethyst new, you get some code with the following lines:

```rust
let path = format!(
    "{}/resources/display_config.ron",
    application_root_dir()
);
```

Edit: This is a breaking change that has not yet been released. This happens with the latest master of amethyst, not v0.10.0.

## Reproduction Steps

1. Create a project with amethyst new
2. cargo run

## What You Expected to Happen

It should compile.

## What Actually Happened

```rust
error[E0277]: `std::result::Result<std::path::PathBuf, std::io::Error>` doesn't implement `std::fmt::Display`
  --> src/main.rs:18:9
   |
18 |         application_root_dir()
   |         ^^^^^^^^^^^^^^^^^^^^^^ `std::result::Result<std::path::PathBuf, std::io::Error>` cannot be formatted with the default formatter
   |
   = help: the trait `std::fmt::Display` is not implemented for `std::result::Result<std::path::PathBuf, std::io::Error>`
   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
   = note: required by `std::fmt::Display::fmt`
```

## Screenshots and Logs

N/A

## Your Environment

* Operating System - Linux Mint
* Operating System Version - 19.1
* Version of Amethyst - latest master (after 0.10.0)

## Additional Context

Even if you use the `?` operator to get rid of the `Result`, you still can't format a `PathBuf` with `{}`. You need to use `to_str` which will check if the path is valid UTF-8. Then you need to unwrap (or even better, use except) in case it isn't.

This fixes the problem:

```rust
let path = format!(
    "{}/resources/display_config.ron",
    application_root_dir()?.to_str().unwrap(),
);
```

Should probably use except or otherwise change the API of application_root_dir() (breaking change) if this line is too ugly.

**Comment by khionu** [comment]
This might be better for us to encapsulate in a set of tools for OS- and system-context-specific actions, such as config/data directories.

**Comment by azriel91** [comment]
Hiya @sunjay, do you remember how you hit the error?
I'm reaching a bit, but I know 0.10.0 was released when `application_root_dir()` returned a `String`, but 0.10.1 swapped it to a `PathBuf` (0.10.1 wasn't branched off 0.10.0's release, but `master`, so it picked the change up by accident).

**Comment by Xaeroxe** [comment]
... In what world is that a sane thing to do? What was it trying to accomplish??

**Comment by sunjay** [comment]
Heh. Bad bot! Glad there was some way to undo it. Let me know if you have anymore questions :)

**Comment by azriel91** [comment]
Okay, I can't seem to reproduce the issue:

* 0.10 release branch [commits](https://github.com/amethyst/amethyst/commits/v0.10?after=a75928e6907ec266e22976f463b2ee2edf3e6da0+104) contains [the `PathBuf` change](https://github.com/amethyst/amethyst/commit/25b46c223c1ee4f87230e3bc747c44ba960e70e5)
* Running `amethyst new abcd; cd abcd; cargo run` works (I'm using Windows, but that should be beside the point).

---

oh.. now I see:

> Edit: This is a breaking change that has not yet been released. This happens with the latest master of amethyst, not v0.10.0.

---

Okay so I don't think the issue happens with things that are currently released -- I'm finding it hard to make it happen anyway.
I've opened https://github.com/amethyst/tools/pull/70 in preparation for the next release.

**Comment by torkleyy** [comment]
I don't think there's anything to fix here. 

When you want to `format!` a `PathBuf`, you should use `Path::display` fyi. We now have an updated template, and there's no reason to use `format!`, so I think this is resolved.

Feel free to re-open if there still is an issue.
