### ISSUE TITLE
[MAINTENANCE] Wiki page on "Configuration Design" out of date

### ISSUE THREAD

**Issue by distransient** [amethyst/amethyst#1333]
## Description

Configuration is, broadly speaking, no longer done with YAML, but with RON. This page must either be deleted or changed to reflect that.

[https://github.com/amethyst/amethyst/wiki/Configuration-Design]()

**Comment by jojolepro** [comment]
Still relevent. Maybe the wiki should be removed.

**Comment by jojolepro** [comment]
Same

**Comment by distransient** [comment]
I'm just deleting the page (which is fine because the wiki uses its own git tracking) so this can stay closed :P
