### ISSUE TITLE
Link redirects to 404 on book

### ISSUE THREAD

**Issue by Sinono3** [amethyst/amethyst#1347]
Close to the end of the page there's this paragraph:

> We've discovered Amethyst's root object: [Application](https://www.amethyst.rs/doc/master/doc/amethyst/struct.Application.html). It binds the OS event loop, state machines, timers...

That one redirects to a 404 page, shouldn't it be this one instead? https://www.amethyst.rs/doc/latest/doc/amethyst/type.Application.html (I am not sure since I have just started with Amethyst 😃)

**Comment by Xaeroxe** [comment]
Not anymore, so I'm going to close this
