### ISSUE TITLE
[NEW FEATURE] Let us define a SpriteRender in a Prefab

### ISSUE THREAD

**Issue by ISibboI** [amethyst/amethyst#1350]
## What problem does this solve? What need does it fill?
It fills the coders need of defining all entities as prefabs without hardcoding anything.
When a game designer wants to define an entity that can be rendered using a sprite, then the game designer needs to define the sprite somehow.

## Describe the solution you'd like
Make SpriteRender usable in Prefabs like
```ron
SpriteRender(sprite_sheet: Asset(File("texture/santa_spritesheet.ron")), sprite_number: 0)
```
Or similar.

## Describe alternatives you've considered
 * Hardcoding.
 * Writing your own sprite manager and giving the sprite sheets names or ids.

## Additional context
I'm trying to create an entity with a PrefabData like this:
```rust
#[derive(Serialize, Deserialize, PrefabData)]
pub struct PlayerPrefab {
    #[prefab(Component)]
    player: Player,
    #[prefab(Component)]
    transform: Transform,
    #[prefab(Component)]
    sprite_render: SpriteRender,
    #[prefab(Component)]
    gravity_affected: GravityAffected,
    #[prefab(Component)]
    world_collision_affected: WorldCollisionAffected,
    #[prefab(Component)]
    #[serde(default)]
    velocity: Velocity,
    #[prefab(Component)]
    #[serde(default)]
    animated: Animated,
    #[prefab(Component)]
    #[serde(default)]
    transparent: Transparent,
}
```

**Comment by Rhuagh** [comment]
This is being worked on in #1149.

**Comment by ISibboI** [comment]
Ah I didn't find this one. I'm looking forward to your results!
