### ISSUE TITLE
[BUG] Sprite Scaling Confusion with `DrawFlat2D`

### ISSUE THREAD

**Issue by DenialAdams** [amethyst/amethyst#1351]
## Description

I'm trying to render a 1x1 texture as a 100x16 sprite (platform.) To accomplish this, I tried setting the scale of entity to be (100.0, 16.0, 1.0). The entity is then drawn offset from its `Transform` translation, though I would expect it to be in the same place, just larger.

It's quite possible I am misunderstanding something here, and this is not in fact a bug.

## Reproduction Steps

1. Create an entity with Transform, etc, and TextureHandle to a 1x1 pixel
2. Observe position of entity on screen
3. Set scale to to (100.0, 16.0, 1.0)
4. Observe offset

I haven't yet gone to the effort of creating a minimal example to reproduce this, but I am happy to do so if that would help.

## What You Expected to Happen

The platform sprite to be scaled, maintaining its center (`Transform` translation).

## What Actually Happened

The platform sprite is drawn offset from its unscaled center (`Transform` translation).

## Screenshots and Logs

Platform with scale (1.0, 1.0, 1.0):
<img width="1919" alt="bug-centered-but-tiny" src="https://user-images.githubusercontent.com/2072405/51092825-f4f1c100-1769-11e9-8d8d-2fbc8bccef49.PNG">
Note it is centered in the game screen (very small!)

Platform with scale (100.0, 16.0, 1.0):
<img width="1920" alt="bug-offset" src="https://user-images.githubusercontent.com/2072405/51092826-f91dde80-1769-11e9-96c1-fc7328e16888.PNG">
Note it is offset to the right.

## Your Environment

1. Windows 10 Pro x64
2. 1803
3. HEAD (f73bb61fb518566791ca555bca667a05153a92c2)

## Additional Context
@Moxinilian dug into this on discord with me. You can find that conversation in the Amethyst #help channel. Huge thanks to him!

**Comment by jojolepro** [comment]
@jaynus did your pr for the sprites offsets fix this?

**Comment by jaynus** [comment]
I've re-tested this with rendy and the transform refactor. Somewhere along the way, this got fixed.

Test code here which confirms it is centered now.
https://gist.github.com/jaynus/4002ea609029a7255502475493f618b0#file-1x1-rs-L116-L131
