### ISSUE TITLE
[MAINTENANCE] how to use mut borrow transforms twice in system run.

### ISSUE THREAD

**Issue by a348019017** [amethyst/amethyst#1355]
![default](https://user-images.githubusercontent.com/12935754/51169289-779f8b00-18e6-11e9-9a61-f8119a4f9c77.png)

`

`

**Comment by Xaeroxe** [comment]
This is a classic case of mutating a collection while you're iterating it. 

If you look at our pong example, we resolve this by splitting the system into two, and introducing a velocity component.

https://github.com/amethyst/amethyst/blob/v0.10/examples/pong/systems/bounce.rs

and

https://github.com/amethyst/amethyst/blob/v0.10/examples/pong/systems/move_balls.rs

**Comment by Xaeroxe** [comment]
Also: https://github.com/amethyst/amethyst/blob/v0.10/examples/pong/systems/winner.rs

**Comment by Xaeroxe** [comment]
你可能無法閱讀我的英文，所以我正在使用谷歌翻譯。 對不起，如果這很難讀。

這是在迭代時改變集合的經典案例。

如果你看一下我們的乒乓球例子，我們通過將系統分成兩部分並引入一個速度分量來解決這個問題。

**Comment by Rhuagh** [comment]
As @Xaeroxe says, you need to break the loops apart and use intermediate storage for the results. Having two mutable references to the same data at the same time is illegal in rust.

**Comment by Xaeroxe** [comment]
Correct, and we can't really fix that. This is a constraint imposed by Rust itself.

**Comment by azriel91** [comment]
这样也可以：

```rust
type SystemData<'s> = (
    Entities<'s>,
    WriteStorage<'s, Ball>,
    ReadStorage<'s, Paddle>,
    WriteStorage<'s, Transform>,
);

fn run(&mut self, (entities, mut balls, paddles, mut transforms): Self::SystemData) {
    let mut updated_transforms = Vec::<(Entity, Transform)>::new();
    for (ball_entity, ball, transform) in (&*entities, &mut balls, &transforms).join() {

        // ..

        // 计算新的 Transform
        if ball_x <= ball.radius || ball_x >= ARENA_WIDTH - ball.radius {
            let mut new_transform = transform.clone();
            new_transform.set_x(0.0);
            new_transform.set_y(0.0);
            updated_transforms.push(*ball_entity, new_transform);
        }

        // Bounce at the paddles.
        for (paddle_entity, paddle, paddle_transform) in (&*entities, &paddles, &transforms).join() {
            // ..

            // 计算新的 Transform
            if ball_x <= ball.radius || ball_x >= ARENA_WIDTH - ball.radius {
                let mut new_transform = transform.clone();
                // ..
                updated_transforms.push(*paddle_entity, new_transform);
            }
        }
    }

    // 最后更新球和拍的 Transform
    updated_transforms
        .into_iter()
        .for_each(|(entity, transform)| transforms.insert(entity, transform).expect("Failed to update transform."));
}
```

Hope that helps ✌️!

**Comment by a348019017** [comment]
@azriel91 Thanks,l have entangled in the mut and borrow ..so forgot to do like this.
