### ISSUE TITLE
[FEATURE MODIFICATION] Simplify anonymous access of TeamCity build logs.

### ISSUE THREAD

**Issue by udoprog** [amethyst/amethyst#1366]
## Feature

Simplify anonymous access of TeamCity build logs.

## Change

A contributor should not have to click "Login as Guest" to see build logs.

## Reason

It's unintuitive compared to how build statuses usually work when posted to Github. This otherwise risks becoming a common support request on Discord or Github for new contributors.

## Impact

Make new contributors more independent to fix any issues after they have set up a pull request.

**Comment by fhaynes** [comment]
Can you post that link to the example @LucioFranco

**Comment by fhaynes** [comment]
Our fork of the plugin that does this is here: https://github.com/amethyst/commit-status-publisher

We'll need to tweak it, build it, and install it. It isn't terribly difficult, and the code looks nice.

**Comment by LucioFranco** [comment]
@fhaynes here you go https://github.com/rust-lang/rust/pull/57578#issuecomment-453845930

**Comment by fhaynes** [comment]
This is no longer relevant.
