### ISSUE TITLE
First-time build problems (with solutions)

### ISSUE THREAD

**Issue by U007D** [amethyst/amethyst#1374]
Amethyst gave me build problems (Ubuntu 18.04) the first time I tried to `cargo run --release --example hello_world`.  Here were the missing dependencies for each of the build errors I encountered:

**alsa-sys error**:
`sudo apt install libasound2-dev`

**CXX compiler error**:
`sudo apt install g++` # note: `sudo apt install clang` provided a `c++` executable but the build still failed; `g++` is required

**servo-fontconfig-sys error**:
`sudo apt install libfreetype6-dev libfontconfig1-dev`

It would be nice to have commonly-encountered dependency build errors as a FAQ in the crate `README.md`.  Hope that is helpful to other game engine newbs like me! :)
-U007D

**Comment by jojolepro** [comment]
Those are in the readme

**Comment by jojolepro** [comment]
Under the dependencies section to be exact.

**Comment by Xaeroxe** [comment]
Perhaps we should take this issue as an indicator that they aren't prominent enough.

**Comment by U007D** [comment]
Wow.  I looked there twice and missed it.  I guess I wasn't looking for "Dependencies", but something related to Installation instructions.  But I was already in troubleshooting mode by then.  Dependencies does make sense though.  Sorry for the noise!
