### ISSUE TITLE
[BUG] DebugLines differ in thickness depending on point distance from center.

### ISSUE THREAD

**Issue by Toqozz** [amethyst/amethyst#1376]
## Description

When using the `DebugLines` system, line thickness seems to change depending on where the line originates from / travels to.  This doesn't seem to happen when at least one point originates from the center of the camera / screen (0.0, 0.0), but does otherwise.

## Reproduction Steps
* Create a new Amethyst project with the following main.rs: https://gist.github.com/Toqozz/fdba2c5101033dceb25fcddbf05edba8

* `cargo run` and observe line thickness changing with movement.

Here's the core code snippet, without all the boilerplate:

```rs
let t = (time.absolute_time_seconds() as f32).cos();
debug_lines_resource.draw_line(
    [t * 50.0, 50.0, 0.0].into(),
    [t * 50.0, 0.0, 0.0].into(),
    [0.0, 1.0, 0.0].into(),
);
```

## What You Expected to Happen

Line thickness should stay the same regardless of origin or position.

## What Actually Happened

Line thickness changes depending on how far its points are from `(0.0, 0.0)`.

## Screenshots and Logs
Here's what you'll get from running the above program:
![gif](https://i.imgur.com/b13wejP.gif)

This doesn't happen if you position one of the points at `(0.0, 0.0)`:
![gif](https://i.imgur.com/zKOTfKJ.gif)

Here's another example in a real project:
![gif](https://i.imgur.com/rprPZnT.gif)

## Your Environment

1. Linux 
2. `4.20.3-arch1-1-ARCH`
3. `0.10.0`

## Additional Context
I think this issue may be related to camera perspective.  Even though in the example I've used an orthographic camera, the effect can be lessened by moving the line points back on the Z axis.  In the gifs above I've used a Z value of `-10.0` (`0.0` was too difficult to see in the gif).

**Comment by Frizi** [comment]
This was fixed with new debug lines pass in amethyst_rendy.
