### ISSUE TITLE
[FEATURE MODIFICATION] `AssetPrefab` improvement (if it can be called so)

### ISSUE THREAD

**Issue by JameeKim** [amethyst/amethyst#1399]
## Feature

Currently, `AssetPrefab` only has `File` and `Handle` variants, and requires both the format instance and the options (for the format) instance be specified in their serialized forms. There are a couple of limitations that
* the asset data should be separated into another file, even if the user wants it inlined
* the prefab writer should always write "File(filename, **(), ()**)" part even if not needed

## Suggestions

* Create a new enum (something called like `AssetDataPrefab`) which is a copy of `AssetPrefab`, but with an additional `Data` variant with `A::Data` type in it.
* Use `Option` enum to prevent the need for the asset data to be cloned (e.g. `Data(Option<A::Data>)`), and nofity the users to only use `Some` variant.
* Implement `Default` to all pre-defined formats and their options (wherever possible).
* For both `AssetPrefab` and `AssetDataPrefab`, use `#[serde(default)]` for the format and options fields of `File` variant.
* Also use `Option` enum to prevent cloning the options of the format?

The reason `Data` variant cannot be added to the originial `AssetPrefab` is because implementing `Deserialize` for all of `Asset::Data` types does not seem plausible. So, `AssetDataPrefab` is for assets which data can be deserialized.

## Example Code

Below is what I'm using for myself, called `AssetDataPrefab`. `FormatDefault` trait is just an alternative way to implementing `Default` for pre-defined formats, which clearly I cannot do in my crate.

#### Usage

With my `AssetDataPrefab`, I can, for example, have all of the game map data in one file (or separate ones just for the parts I want). The code below assumes that `AssetPrefab` is also written in the way `AsestDataPrefab` is, only without `Data` variant. Note that the fields in `File` variants are named.

```rust
#[derive(Deserialize, Serialize)]
type Maps = HashMap<String, MapData>;

#[derive(Deserialize, Serialize)]
struct MapData {
    name: String,
    prefab: AssetDataPrefab<Prefab<MapPrefab>, RonFormat>,
}

#[derive(Default, Deserialize, PrefabData, Serialize)]
#[serde(default)]
struct MapPrefab {
    gltf: Option<AssetPrefab<GltfSceneAsset, GltfSceneFormat>>,
    transform: Option<Transform>,
}
```
```rust
#![enable(implicit_some)]
{
    "map_1": (
        name: "First Map",
        prefab: Data(Prefab(
            entities: [
                (
                    data: (
                        gltf: File(
                            file: "maps/map_1_ground.gltf",
                            options: (flip_v_coord: true),
                        ),
                    ),
                ),
                (
                    data: (
                        transform: (
                            translation: (1.5, 0.5, -2.0),
                        ),
                    ),
                ),
                (
                    parent: 1,
                    data: (
                        gltf: File(
                            file: "objects/grass1.gltf",
                            options: (flip_v_coord: true, load_animations: true),
                        ),
                    ),
                ),
            ],
        )),
    ),
    "map_2": (
        name: "Second Map",
        prefab: File(file: "maps/map_2.ron"),
    ),
}
```

#### `FormatDefault`

```rust
/// `Default` trait for `Format`s
pub trait FormatDefault<A>
where
    Self: Format<A>,
    A: Asset,
{
    /// The default value for the format
    fn default() -> Self;
}
```

#### `AssetDataPrefab`

```rust
/// Prefab data that takes either an inline prefab data or an asset file
#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub enum AssetDataPrefab<A, F>
where
    A: Asset,
    F: FormatDefault<A>,
{
    /// Inline prefab data
    ///
    /// The `Option` type is used to prevent cloning the inner data. Do not use `None` variant.
    #[serde(bound(deserialize = "A::Data: for<'d> Deserialize<'d>"))]
    #[serde(bound(serialize = "A::Data: Serialize"))]
    Data(Option<A::Data>),

    /// Separate asset file for the data
    File {
        /// File path relative to the assets folder
        file: String,

        /// Format used to parse the file
        ///
        /// The `Option` type is used to prevent cloning the inner data. Do not use `None` variant.
        #[serde(default = "AssetDataPrefab::default_format")]
        format: Option<F>,

        /// Options used when parsing with the format
        ///
        /// The `Option` type is used to prevent cloning the inner data. Do not use `None` variant.
        #[serde(bound(deserialize = "F::Options: Default + for<'d> Deserialize<'d>"))]
        #[serde(bound(serialize = "F::Options: Serialize"))]
        #[serde(default = "AssetDataPrefab::<A, F>::default_format_options")]
        options: Option<F::Options>,
    },

    /// Handle to the loaded (or started-to-load) prefab data
    #[serde(skip)]
    Handle(Handle<A>),
}

impl<A, F> AssetDataPrefab<A, F>
where
    A: Asset,
    F: FormatDefault<A>,
{
    /// Get the handle, or `None` if it is not morphed yet
    #[inline]
    pub fn get_handle(&self) -> Option<Handle<A>> {
        if let AssetDataPrefab::Handle(handle) = self {
            Some(handle.clone())
        } else {
            None
        }
    }

    #[inline]
    fn default_format() -> Option<F> {
        Some(FormatDefault::default())
    }

    #[inline]
    fn default_format_options() -> Option<F::Options>
    where
        F::Options: Default,
    {
        Some(Default::default())
    }
}

impl<'a, A, F> PrefabData<'a> for AssetDataPrefab<A, F>
where
    A: Asset,
    F: FormatDefault<A>,
{
    #[allow(clippy::type_complexity)]
    type SystemData = (
        WriteStorage<'a, Handle<A>>,
        ReadExpect<'a, Loader>,
        Read<'a, AssetStorage<A>>,
    );
    type Result = Handle<A>;

    fn add_to_entity(
        &self,
        entity: Entity,
        (handles, _, _): &mut Self::SystemData,
        _: &[Entity],
    ) -> Result<Self::Result, Error> {
        let handle = self
            .get_handle()
            .expect("Call to `add_to_entity` before `load_sub_assets`");
        handles.insert(entity, handle.clone())?;
        Ok(handle)
    }

    fn load_sub_assets(
        &mut self,
        progress: &mut ProgressCounter,
        (_, loader, assets): &mut Self::SystemData,
    ) -> Result<bool, Error> {
        let handle = match self {
            // if it already contains the handle
            AssetDataPrefab::Handle(_) => {
                return Ok(false);
            }

            // inline data
            AssetDataPrefab::Data(data) => loader.load_from_data(
                data.take()
                    .expect("Data in `Data` variant should not be `None`"),
                progress,
                &assets,
            ),

            // separate asset file
            AssetDataPrefab::File {
                file,
                format,
                options,
            } => loader.load(
                file.as_ref(),
                format
                    .take()
                    .expect("Format in `File` variant should not be `None`"),
                options
                    .take()
                    .expect("Options in `File` variant should not be `None`"),
                progress,
                &assets,
            ),
        };

        *self = AssetDataPrefab::Handle(handle);
        Ok(true)
    }
}
```

## Reason

I wanted to avoid explicitly writing trivial information in the prefab files. Also, separating all asset files gave me a headache because my assets folder was flowing with files.

## Impact

The required prefab format will be changed, so all of the prefab files that use `AssetPrefab` should be taken care of to match the format.

## Additional Notes

I want to hear your thoughts on the suggestions above, which I'll write here again to save you from scrolling all the way up.

* Create a new enum (something called like `AssetDataPrefab`) which is a copy of `AssetPrefab`, but with an additional `Data` variant with `A::Data` type in it.
* Use `Option` enum to prevent the need for the asset data to be cloned (e.g. `Data(Option<A::Data>)`), and nofity the users to only use `Some` variant.
* Implement `Default` to all pre-defined formats and their options.
* For both `AssetPrefab` and `AssetDataPrefab`, use `#[serde(default)]` for the format and options fields of `File` variant.
* Also use `Option` enum to prevent cloning the options of the format?

**Comment by JameeKim** [comment]
I made the changes I proposed in [my fork](https://github.com/JameeKim/amethyst/tree/asset-prefab). I also changed `TexturePrefab` to match the new form of `AssetPrefab`.

**Comment by azriel91** [comment]
Hi @JameeKim, sorry for the radio silence. I haven't yet looked at the fork, but the proposal looks mostly good -- am wondering if the `Data` variant could live in `AssetPrefab` itself without needing to make the `AssetDataPrefab` type.

Using `Option` to prevent cloning sounds alright; would have to look at the code to see if the `FormatDefault` trait is necessary, or whether it's possible to just use the serde annotations when the format doesn't `impl Default`.

**Comment by JameeKim** [comment]
@azriel91 It's okay, I know you are all busy. :)
The Data variant would be absolutely fine to go in the original AssetPrefab as long as all asset data implement Deserialize (and probably Serialize, too). I tried that for FontAsset, but the compiler complained that FontData (if I remember the name correctly) didn't implement Deserialize. I wonder if implementing Deserialize for all asset data types is an ideal thing to do.
FormatDefault trait was just a workaround for implementing Default for Formats defined in amethyst crate. So if amethyst decides to accept this suggestion, it is most likely to use Default trait.

**Comment by azriel91** [comment]
unstale, I might look at this next week while doing open sourcey things

**Comment by jojolepro** [comment]
A new asset and prefab system is in the works. We'll keep this issue open to keep this use case in mind.
