### ISSUE TITLE
[FEATURE MODIFICATION] Extend Prefab loading to support asynchronously loaded assets

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#1401]
## Feature

Which feature would you like to modify?

The prefab loading system.

## Change

What change would you like to make to it?

Extend the current implementation of `PrefabData` to support waiting for `Asset`s to be loaded, as part of its `load_sub_assets` implementation, so that it can perform further loading based on data of the assets.

## Reason

Why do you want to make this change?

In my project, there is further information in the dependent assets that inform the loading of the current `PrefabData`. I don't know if I will be making this change.

## Impact

What impact would this change have? Do you think it would impact more features than just the one being modified?

It would allow the prefab loading feature to be less restrictive. No.

## Additional Notes

Anything else relevant to add can go here

**Comment by jojolepro** [comment]
When loading the prefab, you can use ProgressCounter to track the loading and wait for it. The is no way to have a blocking load call. Also note that the progress counter seems to not always be working properly for the gltf prefab.

**Comment by azriel91** [comment]
Yo, thanks for the reply; the scenario described is somewhat more complicated. Currently if you have a hierarchy of `PrefabData`, the hierarchy needs to be written out in the prefab file.

*Within a `PrefabData`'s loading*, it is possible to begin to load an `Asset` and obtain its handle (see `MaterialPrefab` and `TexturePrefab`), but it isn't possible to begin to load an `Asset`, wait for it to load, then do further loading based on that.

**Comment by jojolepro** [comment]
You can't wait for an asset loader at all. The processors are systems, so you cannot have a blocking call to wait on the asset. The best you can have is check each frame if it was loaded in state::update or a system, then do you next things you want to do.

**Comment by azriel91** [comment]
Hence this ticket to extend the prefab loading feature
