### ISSUE TITLE
CI does not check json feature

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1416]
We're currently not testing the `json` feature, and it turns out it doesn't compile:

https://github.com/amethyst/amethyst/blob/38877ed47c5bb9a7869276fdea545085ade0d81e/amethyst_assets/src/formats.rs#L48-L49

`chain_err` is not defined. Is there any convention for how to migrate to the new error handling @udoprog? I can't find it in the doc.

**Comment by udoprog** [comment]
Yeah, `ResultExt::with_context` is what should be used now:
https://github.com/amethyst/amethyst/blob/master/amethyst_error/src/lib.rs#L208

This should be imported through `amethyst_error`.

**Comment by torkleyy** [comment]
Fixed.
