### ISSUE TITLE
Question - State transitions

### ISSUE THREAD

**Issue by tglanz** [amethyst/amethyst#1418]
Just a question; Is it possible to transition into some state trait (EmptyState for example) from another (SimpleState for example)?

Specificaly, can't get this to compile
```
use amethyst::{
    prelude::*
};

pub struct CutsceneState;
pub struct LoadState;

impl SimpleState for LoadState {
    fn handle_event(&mut self, _data: StateData<'_, GameData<'_, '_>>, event: StateEvent) -> SimpleTrans {
        Trans::Push(Box::new(CutsceneState))
    }
}

impl EmptyState for CutsceneState {
    // Nothing to see here
}
```

Because of
```
the trait `amethyst::SimpleState` is not implemented for `states::check::CutsceneState`amethyst::SimpleState` is not implemented for `states::check::CutsceneState` 
```

I understand the error, is it just something i am not meant to do (design wise)?

Thanks!

**Comment by JameeKim** [comment]
`EmtpyState` has `()` as its game data type, whereas `SimpleState` has the `GameData` struct (defined in the amethyst crate) as its game data type. I think that is why your code is not compiling.

You can find the definition of `SimpleState` [here](/amethyst/amethyst/blob/master/src/state.rs#L77), and check that `EmptyState` has the game data type of `()` [here](/amethyst/amethyst/blob/master/src/state.rs#L173).

**Comment by tglanz** [comment]
Great thank you
