### ISSUE TITLE
Link example games in readme and website

### ISSUE THREAD

**Issue by msiglreith** [amethyst/amethyst#142]
As the engine is growing and a bunch of core features have been implemented so far (rendering, input, transform, assets, ...) it might be interesting to build up a 3D game based on on amethyst, which would help to verify the current API and check for possible extensions/changes. The focus would rather lay on the technical aspects than the actual gameplay.

Additionally, it would provide possible users an entry point to experiment with the engine code and create new games.

**Comment by Emilgardis** [comment]
This sounds good, a multiple "demo" projects would be good.

**Comment by torkleyy** [comment]
I have to do a scientific work for school which includes some sort of application for Android. I first planned and designed a minimal game engine for the project, however `amethyst` matches my ideas in many ways, which is why I would take care of this job. This engine does support Android, right? If not, what would be required to get it working?

As this is a work for school (-> I should be doing the main part), I'll start the project by myself and open source it once I submitted it.

**Comment by nchashch** [comment]
@torkleyy AFAIK nobody tried building amethyst for android yet, although it uses glutin for window management currently. So it should be possible to make it work on android (for example [ZoC](https://github.com/ozkriff/zoc) works on android and it uses glutin).

You might want to take a look at [android-rs-glue](https://github.com/tomaka/android-rs-glue) project. Probably the best way to start would be to try building amethyst for android and see if anything breaks.

**Comment by diegor8** [comment]
It thought sdl was being used

**Comment by torkleyy** [comment]
@nchashch I've tried the "sphere" example and it built successfully! I can also run it, however, as expected, I got a panic because the resources folder is not there. Can I put the config file into my source file? Because it seems difficult to bundle any files with the `.apk` with `android-rs-glue`.

**Comment by mabruckner** [comment]
I am writing a simple solitaire/klondike game. You can find it [here](https://github.com/mabruckner/solitaire).

**Comment by erlend-sh** [comment]
> @mabruckner: I am writing a simple solitaire/klondike game

Did you ever write a tutorial for it?

If anyone wants to have a go at it, a couple years back I made a Creative Commons game design for a simple game called Skulls. It's essentially just a reskinning of an old classic known as ["Rats!"](https://www.youtube.com/watch?v=YnO406cOVmM).

- [Design doc](https://jmonkeyengine.gitbooks.io/examplegame-skulls/content/index.html)
- [Game source code](https://github.com/jMonkeyEngine/examplegame-skulls)
- [Development log](https://hub.jmonkeyengine.org/t/jmonkeyengine-example-game/31439)
- [Development Tutorial](https://docs.google.com/document/d/e/2PACX-1vQnmCAK8Jpvgus9bmonHARCv0tX1MlWfju057khtjLHErQUujPEhRZDGd7cyEJWaXeMMuC4OS5dbV-r/pub)

I have a bunch of [Bitgem](https://shop.bitgem3d.com/) assets that I'd be happy to share with anyone who'd like to play with this game concept or something similar. Unfortunately these assets are proprietary so they may not be redistributed freely as part of an open source project, but they can be part of a game distribution.

**Comment by minecrawler** [comment]
We have yet to see suggestions for 3D games. I think, if Amethyst focuses too heavily on 2D, it will neglect 3D needs!

I want to suggest adding the following 3D games:

- Ball in a maze, you can tilt the maze to roll the ball through it (needs physics)
- 3D Space Invaders Arena (needs camera and physics, can add animations to space ships)
- Jump Puzzle: You control a ball from 3rd person. It can jump. You have to get from A to B and in between there are only floating blocks on which you can jump. Don't fall down or start at the beginning. (needs camera and physics; use a human-mesh later on with animations)

As you can see, physics are quite important in 3D, but not necessarily in 2D. If you only go the 2D samples, you might miss out on many (maybe even low-hanging fruit) concepts, which turns away 3D developers.

**Comment by erlend-sh** [comment]
I really like the "Ball in a maze". The game is simple and familiar, the use of physics is essential to the gameplay, and the controls for the game can be expanded upon as Rust/Amethyst expands its platform targets: (1) Keyboard, (2) Joystick, (3) Gyroscope.

Not a big fan of adding physics to Space Invaders though. It's in no way *essential* for the gameplay, so in my view it is bloat and teaches bad practice. Space Invaders is so simple and familiar that it's a perfect fit for one of the very first games you learn with Amethyst. It doesn't even need a GUI!

**Comment by minecrawler** [comment]
> Not a big fan of adding physics to Space Invaders though

Collision detection for arena borders and bombs. I think, it's essential.

**Comment by erlend-sh** [comment]
Aha, we probably just have different interpretations of what *game physics* are. I was thinking in terms of something that will require a robust physics library such as nphysics or Bullet.

Rudimentary collision detection doesn't require more than a few lines of code, no external library required.

**Comment by minecrawler** [comment]
Sure, there are easy workarounds, however, I think it should be part of a proper physics library. iirc, we want to have physics in Amethyst, so that should be a full library, not just a few lines for simple collision detection...

**Comment by Xaeroxe** [comment]
Pong meets this pretty well by now, so I'm going to close this.

**Comment by torkleyy** [comment]
I don't think we should close this already. There a lot of good suggestions in here and having a more impressive game than pong for demonstration would be helpful to get people attracted to the project.

**Comment by Xaeroxe** [comment]
Sounds good to me.

**Comment by jojolepro** [comment]
Will be resolved by amethyst/ludumdare42 
This project will need to be cleaned up before being advertised "proper tutorial" though. I suggest we version lock it to amethyst 0.8, as maintenance of it would slow us down in the long term.

**Comment by jojolepro** [comment]
I already talked about that on discord, but I'll repeat it here.
We should make a "projects" page on the amethyst website linking to games made using amethyst. That page would be divided in two categories: Playable and Prototypes. The prototype category would be for incomplete games that act more as examples with a bigger scope than the ones found in the engine or feature showcases.

**Comment by jojolepro** [comment]
Postponed until we get a prettier renderer

**Comment by azriel91** [comment]
Here's a list from the forum: https://community.amethyst-engine.org/t/games-made-with-amethyst/134
Will we get this into the website this release?

**Comment by jojolepro** [comment]
From what I know, I don't think its planned for this release.

**Comment by fhaynes** [comment]
Closing this, as there is now a Showcase Project team.
