### ISSUE TITLE
[BUG] ERROR: 0:45: 'Error' : Cannot offset into the vector (compiling on Windows)

### ISSUE THREAD

**Issue by ArnoldDeRuiter** [amethyst/amethyst#1426]
## Description

I am trying to use cargo run on a Pong example project. It compiles fine on Debian Stretch, but apparently not so much on my Windows 10 laptop.

## Reproduction Steps

1. Be on Windows 10 Enterprise N 2015 LTSB (up to date according to Windows Update)
2. Download/Clone the Amethyst repository.
3. Run 'cargo run --example pong'
4. Let is download/compile crates and the pong game.
5. See error under Screenshots/Logs

## What You Expected to Happen

On my Debian Stretch desktop it compiles and runs fine, so I was expecting it to work fine.
It's just an example after all.

## What Actually Happened

Well, see the error message under Screenshots/Logs below.
And again, as in reproduction step 1, this happened on a Windows 10 Enterprise N 2015 LTSB machine.

It's hardware specs are:
CPU: Intel i7-2630QM (@2GHz) (which has a HD 3000)
RAM: 6GB (DDR3 laptop)
GPU: Nvidia GT540M

## Screenshots and Logs

> Compiling amethyst_utils v0.5.0 (C:\Users\Arnold\Desktop\amethyst-master\amethyst-master\amethyst_utils)
>     Finished dev [unoptimized + debuginfo] target(s) in 5m 02s
>      Running `target\debug\examples\pong.exe`
>  [37m[INFO][winit::platform::platform::window] Guessed window DPI factor: 1 [0m
>  [33m[WARN][gfx_device_gl::shade]       Log: No errors.
>  [0m
>  [33m[WARN][gfx_device_gl::shade]       Log: No errors.
>  [0m
>  [33m[WARN][gfx_device_gl::shade]       Log: No errors.
>  [0m
>  [31m[ERROR][amethyst_renderer::system] Failed creating pipeline: Program compilation failed [0m
> Error: Error { inner: Inner { source: Some(Error { inner: Inner { source: Some(Error { inner: Inner { source: None, backtrace: None, error: Vertex(CompilationFailed("ERROR: 0:44: \'Error\' : Cannot offset into the vector \nERROR: 0:45: \'Error\' : Cannot offset into the vector \n\n")) } }), backtrace: None, error: ProgramCreation } }), backtrace: None, error: StringError("Renderer error!") } }
error: process didn't exit successfully: `target\debug\examples\pong.exe` (exit code: 1)

## Your Environment

1. Windows 10 
2. Enterprise N 2015
3. Amethyst 0.10.0
4. Rust 1.32.0
5. Nvidia graphics driver: 388.57

## Additional Context
Works fine on Debian Stretch/9.
The Windows environment has the C++ stuff installed, for VS 2017.

**Comment by jojolepro** [comment]
Did you make sure the nvidia drivers are installed and up to date?

@amethyst/render-devs is this gpu supported?

**Comment by ArnoldDeRuiter** [comment]
There was no Nvidia driver update available. The current version is: 388.57 for me.

**Comment by termhn** [comment]
Should easily be supported. Very weird... It doesn't like these lines https://github.com/amethyst/amethyst/blob/master/amethyst_renderer/src/pass/shaders/vertex/sprite.glsl#L44-L45 ("Cannot offset into the vector")... Could you clone from the `vector-index-patch` branch (https://github.com/amethyst/amethyst/tree/vector-index-patch) and see if that fixes it for you?

**Comment by termhn** [comment]
Hey @ArnoldDeRuiter just wanted to see if you'd gotten a chance to follow up on this yet? :D

**Comment by jojolepro** [comment]
The renderer was changed to rendy, making this issue obsolete. Reopen if this still occurs.
