### ISSUE TITLE
[BUG] Specular Highlights broken in DrawPbmSeparate / GLTF

### ISSUE THREAD

**Issue by robert-wallis** [amethyst/amethyst#1430]
## Description

# Specular Lighting Artifacts

When loading the gltf files, it appears that the specular lighting is not being calculated correctly along some faces.

For example the file [cube.gltf](https://github.com/robert-wallis/cube_spec_error/raw/master/resources/cube.gltf) created from a default cube mapped in blender.  With metallic of 0.0, and roughness of 0.5.

In Amethyst there are triangles that have what appears to be no specular lighting.  And the roughness appears too low.

However the specular lighting is displayed correctly in Don McCurdy's GLTF viewer https://gltf-viewer.donmccurdy.com

I made a repo for this issue at: https://github.com/robert-wallis/cube_spec_error  The code is mostly a copy of [examples/gltf/main.rs](../tree/master/examples/gltf/main.rs) except the animation and vertex weights have been removed.

## Reproduction Steps

1) `git clone https://github.com/robert-wallis/cube_spec_error.git`
2) `cd cube_spec_error`
3) `cargo run`
4) Turn the cube with the mouse so the light shines on face B1 or B2 

## What You Expected to Happen

* The lighting should be consistent across the faces.
* The lighting should be more subtle for a 0.5 roughness material.

## What Actually Happened

* It appears some normals are not being calculated correctly in the fragment shader.

### Amethyst: [cube.gltf](https://github.com/robert-wallis/cube_spec_error/raw/master/resources/cube.gltf)

![docs/amethys-b1.png](https://github.com/robert-wallis/cube_spec_error/raw/master/docs/amethyst-b1.png)
![docs/amethyst-b2.png](https://github.com/robert-wallis/cube_spec_error/raw/master/docs/amethyst-b2.png)

### https://gltf-viewer.donmccurdy.com
The specular lighting is more subtle, but you can see there are no artifacts if you drop the file in the viewer yourself.

![mccurdy-b1.jpg](https://github.com/robert-wallis/cube_spec_error/raw/master/docs/mccurdy-b1.jpg)
![mccurdy-b2.jpg](https://github.com/robert-wallis/cube_spec_error/raw/master/docs/mccurdy-b2.jpg)

Similar good results are visible in babylon.js's WebGL renderer and Blender 2.8 Eevee.

## Your Environment

* macOS 10.14.3 Mojave / MacBook Pro Retina 13-inch Early 2015 / Intel Iris 6100 (1.5gb vram)
* Windows 10 Pro 1809 / AMD Radeon R9-290x

## Additional Context
Possibly related to #1095 and #855

**Comment by jojolepro** [comment]
I have had this bug in my own game too.

**Comment by torkleyy** [comment]
Investigating.

**Comment by torkleyy** [comment]
Nice vertex tangents:

![Screenshot from 2019-04-23 14-11-08](https://user-images.githubusercontent.com/23152057/56579999-dbb2a900-65d1-11e9-8354-b8a233ccb8d6.png)

**Comment by Frizi** [comment]
Seems like the generated tangents are wrong. We use mikktspace in gltf loader, but probably incorrectly. I actually have a test model for that from gltf examples repository and it is indeed rendered incorrectly.

**Comment by Frizi** [comment]
There is new tangent generation code in place, also indexed meshes no longer duplicate vertices. This is likely fixed and should be tested for reproduction

**Comment by robert-wallis** [comment]
877e541 looks like it fixed the normals/tangents:

![B1](https://user-images.githubusercontent.com/145938/59411434-1930e880-8d70-11e9-8980-17f9abc4d123.png)
![B2](https://user-images.githubusercontent.com/145938/59411435-1930e880-8d70-11e9-9b15-83490bcc7a2b.png)
(side note, these screenshots are on a totally different OS, machine, and GPU, but the same sample repo)
