### ISSUE TITLE
[ASSET DEPLOY] Correctly deploy assets during the build, do not rely on manifest directory

### ISSUE THREAD

**Issue by Xaeroxe** [amethyst/amethyst#1437]
## Description

Currently Amethyst encourages use of the `CARGO_MANIFEST_DIR` for loading configurations and assets. This is not desirable, as it makes the final build dependent on the source directory. We should scrub all uses of this environment variable, and instead make sure that if an application is dependent on files at runtime, that those files are deployed alongside the final binary.

## What problem does this solve? What need does it fill?
Currently any application that uses `CARGO_MANIFEST_DIR` is not fit for deployment to end users
who will not have this variable set. Deployment to end users is the ultimate goal of Amethyst.

## Describe the solution you'd like
Identify dependent files in the source directory and use `build.rs` to copy them to the output directory on build. In the future we may even be able to pack and bundle assets together in the same file to improve loading times.

## Describe alternatives you've considered
We could use compile time macros to in-line config and resources into the exe, but then they all have to
be loaded when the game is started and that is highly undesirable. Additionally this would prevent configs from being, well, configurable.

## Additional context
None.

**Comment by jojolepro** [comment]
Some ideas: https://github.com/hoppinworld/hoppinworldclient

Check out the build_linux.sh, build_windows.bat and src/main.rs files (look for "AssetLoader").

AssetLoader implementation: https://github.com/jojolepro/amethyst-extra/blob/4580df4de159af684d8677a7068b3a2111060b79/src/lib.rs#L113

This is far from ideal, but it allows for runtime asset modding. You probably want to discuss with kae about how to go about the asset loading story.

**Comment by azriel91** [comment]
I actually think having the following isn't so bad:

```rust
// uses exe_dir() if `CARGO_MANIFEST_DIR` is not set
let assets_dir = application_root_dir().join("assets");
let application = Application::build(assets_dir, /* .. */)
```

It does mean users could override `CARGO_MANIFEST_DIR` for the final executable, but that and the additional line(s -- the import as well) of code are a small price to pay.

**Comment by jojolepro** [comment]
In most cases application_root_dir is good enough.

**Comment by Xaeroxe** [comment]
@jojolepro can you elaborate on what the weaknesses of that are?

**Comment by jojolepro** [comment]
Its not really weaknesses, it just doesn't cover enough use cases as-is.

You need an abstraction layer to get a proper asset system (caching, hot-reloading, overrides, etc). That's what my AssetLoader is (to a very limited and buggy extent) and what kae wanted to work on (with extra features like pipelines).

The biggest issue I see with application_root_dir is that all paths in prefabs need to start from the root of the project. There's also the fact that all assets need to be manually moved into the exported folder (by hand or with some script).

For the latter, you could have a build.rs script doing the exporting, but you can't force a specific workflow to the user (like "all assets go in the Assets/ folder"). If you do that, you'll have all kind of issues down the line, like not being able to separate your game into multiple repositories.

As to what I recommend doing, I would simply do a global replace of CARGO_MANIFEST_DIR->application_root_dir() and call it good enough.

Then we can work on abstraction layers and all that fun stuff.

**Comment by golergka** [comment]
There's no references to `CARGO_MANIFEST_DIR` aside from a few tests and examples and the body of `application_root_dir()` — so any project that would set up copying resources from manifest directory to location of executable would work already. However, as @jojolepro said, Amethyst user could place his assets under any folder, so we can't "correctly" deploy his assets because we don't know where they are: introducing a standard like "Assets" would be a breaking change (although a good idea in general, in my opinion).

Anyway, unless I'm missing something, it seems that "good first issue" is not a great label for something that would require a breaking change to fix.

**Comment by vultix** [comment]
> We could use compile time macros to in-line config and resources into the exe, but then they all have to be loaded when the game is started and that is highly undesirable. Additionally this would prevent configs from being, well, configurable.

An ideal macro system would allow the user to decide how they deploy their assets.  The ability to update entities using prefabs without needing to recompile is amazing, but for a release build we may or may not want these entities to be easily configurable.  

My vote would be to create a macro system that gives a few options depending on what the developer needs:

- If doing a development build, behaves as-is.  Loads assets and prefabs without any need for recompile.  This allows for quick development.
- For release builds, we can choose exactly which assets we want to bundle in the executable, and which assets we want to ship alongside with the executable.

I would imagine this would also help future-proof the asset management system.  I'd imagine sometime along the way these macros could preprocess the assets if needed, convert prefabs to rust code, or do any other asset management behind the scenes.

**Comment by jojolepro** [comment]
![image](https://user-images.githubusercontent.com/4755185/60431175-1e45c280-9bcd-11e9-8c56-8e0954d133ea.png)

It seems that `CARGO_MANIFEST_DIR` is only used internally now, where we cannot import amethyst_utils. This is thus resolved.

**Comment by vultix** [comment]
@jojolepro I still feel that amethyst could greatly benefit from a set of asset deploy macros, as discussed in [this comment](https://github.com/amethyst/amethyst/issues/1437#issuecomment-487645413).

Should we reopen this issue, or perhaps start another issue to discuss the problem there?  Let me know what you'd prefer, thanks!

**Comment by jojolepro** [comment]
@kabergstrom is working on an asset system that will be integrated into amethyst. For more details you can contact him or check his work here: https://github.com/amethyst/atelier-assets
