### ISSUE TITLE
Not possible to load two assets with the same name

### ISSUE THREAD

**Issue by jFransham** [amethyst/amethyst#146]
The map between asset names and asset ids is currently a `HashMap<String, AssetId>`. If you have, for example, `some_thing.obj` and a corresponding `some_thing.mtl` and you try to load both, the one that is loaded second will override the first. This should probably be keyed by a combination of `String` and `TypeId`.

Also, question - wouldn't it be easier to use a `HashMap<String, TypeMap>` where `TypeMap` is from [this repo](http://ironframework.io/doc/typemap/index.html) than an entire ECS `World`, since Assets don't need processors, and when they are made up of multiple parts those parts are normally shared between many assets rather than owned.

**Comment by msiglreith** [comment]
Thanks for the issue! My thoughts about the mentioned points:

> If you have, for example, some_thing.obj and a corresponding some_thing.mtl and you try to load both, the one that is loaded second will override the first.

This behaviour is actually not intended and should be fixed.

> This should probably be keyed by a combination of String and TypeId.

The motivation for using a `String` only was for accessing the asset later on, so the user doesn't need to care about the format the asset is stored (currently needs to the format extension on loading).
I personally prefer to store different assets in separated folders so this issue didn't occur for me, even though maybe storing the asset type (Mesh, Texture, etc.) might be better.

> wouldn't it be easier to use a HashMap<String, TypeMap> where TypeMap is from this repo than an entire ECS World

In same earlier iterations the AssetManager stored the loaders in the World as resources and I just sticked to the World approach as it was pretty easy to use. Feel free to change it if there are advantages!

**Comment by jFransham** [comment]
The advantages are better space efficiency, less allocation (I think, I would have to check that to be sure) and better developer ergonomics (both internally in Amethyst and for consumers, since they don't have to unwrap the `Asset` newtype). You have to downcast the reference anyway and therefore the consumer has to supply a type, so there's no reason _not_ to also key on TypeId. This might be a micro-optimisation (benchmarking would be the way forward here), but it might be better to have

```rust
enum Types {
    One(Box<Any>),
    Many(TypeMap),
}
```

So you don't have to waste cycles in the majority-case of there only being a single asset for a given name.

I also wonder whether we can do this in a way that allocates less, or at least allocates in a preallocated arena, so we can get better cache locality.

**Comment by bytebuddha** [comment]
A somewhat related issue. I noticed you couldn't have an "AssetLoader" that loads multiple file types. For example i have two that load images. A "JpgLoader" and "PngLoader", they are exactly the same but because the asset manager use's the file extension as the asset loader id they must be separate. It would be nice if they could be condensed into one.

**Comment by diegor8** [comment]
You mean that both asset loaders implement both PNG and jpg?

**Comment by jFransham** [comment]
@bytebuddha Does it fail at runtime if you try to do, for example,

```rust
context.asset_manager.register_loader::<Material, JpgLoader>("jpg");
context.asset_manager.register_loader::<Material, PngLoader>("png");
```

That won't fail at compile time, for sure.

**Comment by bytebuddha** [comment]
@jFransham No that works as expected. 

But the source of each Loader object is the same, so i think their should be away to specify the file extension (or override the default extension) of each asset. Then you could use the same AssetLoader for jpg and png images.

**Comment by jFransham** [comment]
@bytebuddha I can't offer anything better than using newtypes.

```rust
struct SharedLoader;

struct JpgLoader(SharedLoader);
struct PngLoader(SharedLoader);
```

Maybe the extensions should be a list?

**Comment by msiglreith** [comment]
I assume he refers to something like this:
```Rust
context.asset_manager.register_loader::<Material, ImgLoader>("jpg");
context.asset_manager.register_loader::<Material, ImgLoader>("png");
```
Which currently doesn't work as the closures don't safe the asset extension type
https://github.com/amethyst/amethyst/blob/develop/src/asset_manager/asset_manager.rs#L196-L199

**Comment by bytebuddha** [comment]
@msiglreith That's correct though a better way i think would be to override the file extension when loading the asset. Something like...
```
context.asset_manager.register_loader::<Material, ImgLoader>("jpg");
// Normal
context.asset_manager.load_asset("some/file", "jpg");
// Override file extension
context.asset_manager.load_asset("some/file.png", "jpg");
```

**Comment by jFransham** [comment]
I don't think that is better, since assets shouldn't be tied necessarily to a file system. That's kinda the point of an asset loader, it shouldn't care about extensions. It should work the same if you load it from the file system as if you load it from a `.pak` file.

**Comment by omni-viral** [comment]
This issue is outdated as there is new asset management system
