### ISSUE TITLE
[MAINTENANCE] Missing libraries when compiling examples

### ISSUE THREAD

**Issue by sunreef** [amethyst/amethyst#1471]
## Note

I followed the instructions on the [Getting started page](https://www.amethyst.rs/book/latest/getting-started.html) for using Amethyst on Linux. I installed the listed libraries: `libasound2-dev`, `libx11-xcb-dev` and `libssl-dev`. 

## Description

I was trying to compile an example in the amethyst repository and I encountered the errors listed below. I'm on Ubuntu 16.04 and I ran `cargo run --example sphere`.

>   /usr/bin/ld: cannot find -lxcb-render
>   /usr/bin/ld: cannot find -lxcb-shape
>   /usr/bin/ld: cannot find -lxcb-xfixes
>   collect2: error: ld returned 1 exit status
>
> error: aborting due to previous error
> error: Could not compile `amethyst`.

## Solution 

I fixed these errors by installing the following packages: `libxcb-render-util0-dev`, `libxcb-shape0-dev` and `libxcb-xfixes0-dev`. After that, the example ran just fine.

## Suggestion

Is this a known issue for Ubuntu 16.04 ?
If it is reproducible, maybe it would be worth mentioning this problem in the installation docs.

**Comment by LucioFranco** [comment]
I'm not totally sure but could you verify that these apt-get packages include those? https://github.com/amethyst/amethyst#debianubuntu

We could probably do a better job of making those dependencies clearer.

**Comment by sunreef** [comment]
These packages are indeed included in the `libxcb-composite0-dev`.

I only looked at the Amethyst documentation and failed to see the "See the readme on github for distribution specific details." line.
