### ISSUE TITLE
[BUG] Attempted to divide by zero with vertex length at 0

### ISSUE THREAD

**Issue by OptimisticPeach** [amethyst/amethyst#1476]
## Description

I want to run an algorithm to change a `Mesh` every few frames. Therefore, in my `SimpleState::on_start` I make a dummy entity (That is really only a dummy for a few frames). This is considered a dummy entity because there are 0 vertices attached to its mesh. Unfortunately creating a `Mesh` with 0 vertices causes an error of dividing by zero at [`amethyst_renderer\src\mesh.rs:68`](https://github.com/amethyst/amethyst/blob/18a2855bb4c6f660f6ae4cf62731242910909cf3/amethyst_renderer/src/mesh.rs#L68) because it attempts to calculate the stride of the buffer by dividing. 

## Reproduction Steps

I think that the easiest way to reproduce it is by cloning the [`asset_loading`](https://github.com/amethyst/amethyst/tree/master/examples/asset_loading) example and changing [line 79](https://github.com/amethyst/amethyst/blob/master/examples/asset_loading/main.rs#L79) to this:
```
let mesh: Handle<Mesh> = loader.load_from_data(Vec::<PosNormTex>::new().into(), (), meshes);
```

## What was Expected to Happen

It should've run just fine, ie. it would create an empty mesh.

## What Actually Happened

It attempted to divide by zero.

## The Environment
```
Version: 0.10.0
Platform: x86_64-pc-windows-msvc
Amethyst git commit: bc105a7fc18aea8497eeda8850124404529682d0
Rustc version: 1.34.0-nightly Nightly
Rustc git commit: 097c04cf433048585dd9e3f63b30e03cc3509e4b
```

**Comment by distransient** [comment]
Nice catch! I opened #1481 which should fix this.
