### ISSUE TITLE
[NEW FEATURE] Implement Flat Pass in rendy

### ISSUE THREAD

**Issue by fhaynes** [amethyst/amethyst#1487]
# Summary

This pass needs to be implemented for Rendy: https://github.com/amethyst/amethyst/tree/master/amethyst_renderer/src/pass/flat

This requires #1485 to be complete before starting work.

## How to Work on This

Please create a branch off of the rendy branch and submit PRs back to it. The work should be done in the amethyst_rendy crate.

**Comment by Frizi** [comment]
Implemented, but depends on https://github.com/amethyst/rendy/pull/121
