### ISSUE TITLE
[NEW FEATURE] Implement UI Pass in rendy

### ISSUE THREAD

**Issue by fhaynes** [amethyst/amethyst#1491]
# Summary

This pass needs to be implemented for Rendy: https://github.com/amethyst/amethyst/blob/master/amethyst_ui/src/pass.rs

## How to Work on This

Please create a branch off of the `rendy` branch and submit PRs back to it. The work should be done in the `amethyst_rendy` crate.

**Comment by Frizi** [comment]
Implemented on rendy branch, finally \o/
