### ISSUE TITLE
[BUG] Amethyst fails to compile on nightly due to Tuple Suffix

### ISSUE THREAD

**Issue by piedoom** [amethyst/amethyst#1492]
## Description

Amethyst errors as of 1.35.0-nightly with the issue `suffixes on a tuple index are invalid`.

## Reproduction Steps

1. Compile a project using `amethyst_renderer`

Quick version:

```
error: suffixes on a tuple index are invalid
   --> C:\Users\doomy\.cargo\git\checkouts\amethyst-fedb0a1032a075ce\1a77ac4\amethyst_renderer\src\light.rs:188:50
    |
188 | #[derive(Default, Clone, Serialize, Deserialize, PrefabData)]
    |                                                  ^^^^^^^^^^ invalid suffix `usize`

error: proc-macro derive produced unparseable tokens
   --> C:\Users\doomy\.cargo\git\checkouts\amethyst-fedb0a1032a075ce\1a77ac4\amethyst_renderer\src\light.rs:188:50
    |
188 | #[derive(Default, Clone, Serialize, Deserialize, PrefabData)]
    |                                                  ^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `amethyst_renderer`.
```

Verbose:

[See gist](https://gist.github.com/piedoom/8dbd7cc253c8498dcde54b57490e5a0e)

## Your Environment

1. OS: Windows 10
2. Operating System Version: 10.0.17134 Build 17134
3. Version of Amethyst: Master

**Comment by Patryk27** [comment]
@johan-bjareholt: the Rust compiler has been fixed and that's precisely the reason Amethyst fails to compile now - the error about tuple suffix was _not_ thrown before only because there was a bug in the compiler.

**Comment by azriel91** [comment]
Could someone with a recent `nightly` run this:
```bash
cargo install cargo-expand
cd path/to/amethyst/amethyst_renderer
cargo expand light > /tmp/expanded.rs
```

I'd like to see the output of `expanded.rs`. I've done it on an older nightly and there's no tuple suffix with usize, so maybe proc macro code has changed.
