### ISSUE TITLE
Untangle UI selection and improve keyboard/accessibility use case

### ISSUE THREAD

**Issue by ndarilek** [amethyst/amethyst#1497]
I'm looking to add accessibility to the UI subsystem. Keyboard support is critical for this.

It looks like there's a concept of Selection, but there are aspects of that design that will make keyboard use/accessibility difficult:

 * The concept is a bit overloaded and should probably be split for easier implementation.
 * Events aren't dispatched when items gain or lose selection. They do appear to be dispatched when a control is hovered or loses hover, but that seems mouse-specific.

I propose the following:

 * Split the concept of selection into "focused" and "selected." Widgets gain or lose focus. Items within widgets, or maybe multiple distinct widgets, might be selected. A button gains or loses focus, and may be selected or unselected if it is a radio button/checkbox. Lists gain or lose focus, and may or may not have one or multiple items selected.
 * Unify focus and selection handling to work as identically as possible using the keyboard or mouse.
 * Dispatch a unified set of events for focus gain/loss and selection change regardless of the input method used.

I'm happy to help with this--I just wanted to both check my assumptions about how things currently work, and ensure that these sound like good ideas to pursue. Also, given that I'm not familiar with the UI subsystem, and given I'm blind so can't test mouse interactivity, I'll probably need some direction with the implementation, and help getting the mouse support working.

**Comment by jojolepro** [comment]
Ah I see where the confusion comes from. The Selectable component is what you call "focus". For example, when you alt tab, it will focus or select each ui element by cycling through all entities with a Selectable component. When an entity gets selected, it will add a Selected component on it. Once it gets unselected, the component is removed.

I think adding either a SelectionEvent type or changing the Selected component storage type to FlaggedStorage would make a lot of sense. In both cases, you would get events for when an entity gains or loses focus.

**Comment by ndarilek** [comment]
Cool, thanks for the clarification. I'm going to submit a PR renaming 
that and everything around it to use `Focus` and not `Select` in its 
name. My concern is that, when listboxes and such are added, you're 
going to need the concept of items in the list being selected even if 
the list doesn't have focus, and overloading the word `select` would be 
problematic when describing those situations. It would also be difficult 
to use "focus" to describe items in a list being selected. I think it 
may be a good idea to remove the control-click behavior as well. I think 
what you're trying to do there is supporting the use case where multiple 
items in a list or multiselect group might be *selected* entirely 
independent of the *focus*. It makes sense to keep that behavior, but I 
think it muddies the concepts a bit, and it made telling what this was 
supposed to do a bit more difficult.


While I'm in here working on this, does it make more sense to have a 
separate system for managing focus/selection, or a single system for 
handling *all* keyboard/mouse interaction with the UI? I ask because I 
want to add support for clicking/interacting with components via the 
keyboard, and I wonder if I need a separate system for each interaction 
type, or just one for everything? Or maybe separate systems for 
keyboard/mouse interaction make sense, since those could be swapped out 
or augmented for touchscreen support. But should we have a single 
UiKeyboardSystem/UiMouseSystem for *all* keyboard interactivity, or do 
we need KeyboardFocusSystem, KeyboardClickSystem, etc.?

**Comment by jojolepro** [comment]
Separate the systems into smaller pieces whenever you can. As for the multiple selection stuff, keep the feature, but feel free to isolate it into its own system if possible.
