### ISSUE TITLE
[NEW FEATURE] 2d Text (not UI)

### ISSUE THREAD

**Issue by CosineP** [amethyst/amethyst#1500]
## Description
Render text as part of the scene, using camera coordinates.

## What problem does this solve? What need does it fill?
I have my viewport set up to pixelize my assets and I want the same to happen to my text.  
I'm trying to make visual novel style graphics, but this also applies to Uis in pixel art games.

## Describe the solution you'd like
I'd like to be able to add text just the same as I can add a Sprite.

## Describe alternatives you've considered
I could use a big bitmap text font and fake it.

## Additional context
I'm basically waiting on this until I can feasibly make my pixelly game idea in Amethyst

**Comment by jojolepro** [comment]
Soon :tm: 

<3

**Comment by CosineP** [comment]
i would uh, still like to see this happen?

**Comment by jojolepro** [comment]
I tried my best, but with the renderer changes it seems that my (partially) implemented solution was removed. If someone wants to work on this feature, let us know!
