### ISSUE TITLE
[BUG] vertex shader issue

### ISSUE THREAD

**Issue by MannyCyber** [amethyst/amethyst#1505]
## Description

It looks like the vertex shader is picking up the wrong version of GLSL. This causes the application to build correctly then fail at runtime.

## Reproduction Steps
1. Install Amethyst and dependencies
2. Copy the [windows example](https://github.com/amethyst/amethyst/tree/master/examples/window)
3. Run cargo build (application complied with no issues)
4. Run cargo run

## What You Expected to Happen

Expected a window to open as per [windows example](https://github.com/amethyst/amethyst/tree/master/examples/window)

## What Actually Happened

The error shown below. The window opened momentarily then closed.

## Screenshots and Logs
[INFO][winit::platform::platform::x11::window] Guessed window DPI factor: 1.25
[DEBUG][winit::platform::platform::x11::window] Calculated physical dimensions: 500x500
[INFO][gfx_device_gl::info] parsing version '2.1 Mesa 17.3.9'
[INFO][gfx_device_gl::info] parsing version '1.20'
[INFO][gfx_device_gl] Info { platform_name: PlatformName { vendor: "Intel Open Source Technology Center", renderer: "Mesa DRI Intel(R) Ironlake Mobile " }, version: 2.1, Mesa 17.3.9, shading_language: 1.20, extensions: {"GL_EXT_draw_instanced", "GL_ARB_map_buffer_alignment", "GL_ARB_framebuffer_sRGB", "GL_ARB_fragment_coord_conventions", "GL_ARB_ES2_compatibility", "GL_ARB_shader_group_vote", "GL_NV_light_max_exponent", "GL_EXT_texture_rectangle", "GL_EXT_framebuffer_blit", "GL_MESA_pack_invert", "GL_ARB_provoking_vertex", "GL_ARB_program_interface_query", "GL_ARB_seamless_cube_map", "GL_EXT_secondary_color", "GL_NV_conditional_render", "GL_3DFX_texture_compression_FXT1", "GL_EXT_pixel_buffer_object", "GL_IBM_multimode_draw_arrays", "GL_EXT_texture_compression_s3tc", "GL_ARB_texture_env_dot3", "GL_KHR_robustness", "GL_KHR_no_error", "GL_ARB_explicit_uniform_location", "GL_EXT_texture3D", "GL_ARB_get_texture_sub_image", "GL_EXT_compiled_vertex_array", "GL_EXT_packed_depth_stencil", "GL_ATI_draw_buffers", "GL_EXT_texture_compression_rgtc", "GL_ARB_half_float_vertex", "GL_ARB_framebuffer_object", "GL_ARB_shader_objects", "GL_ARB_color_buffer_float", "GL_ARB_multisample", "GL_ARB_sampler_objects", "GL_AMD_shader_trinary_minmax", "GL_ARB_window_pos", "GL_ARB_texture_float", "GL_ARB_separate_shader_objects", "GL_EXT_provoking_vertex", "GL_EXT_vertex_array", "GL_ARB_fragment_program", "GL_EXT_stencil_wrap", "GL_EXT_texture_sRGB", "GL_ARB_get_program_binary", "GL_ATI_blend_equation_separate", "GL_ARB_texture_env_crossbar", "GL_KHR_debug", "GL_EXT_texture", "GL_ARB_explicit_attrib_location", "GL_ARB_texture_border_clamp", "GL_ANGLE_texture_compression_dxt3", "GL_ARB_half_float_pixel", "GL_EXT_texture_lod_bias", "GL_NV_texture_env_combine4", "GL_ARB_copy_buffer", "GL_EXT_vertex_array_bgra", "GL_NV_primitive_restart", "GL_ATI_texture_float", "GL_ARB_vertex_type_10f_11f_11f_rev", "GL_ARB_fragment_shader", "GL_EXT_packed_pixels", "GL_AMD_seamless_cubemap_per_texture", "GL_EXT_texture_integer", "GL_NV_texgen_reflection", "GL_ARB_shadow", "GL_OES_EGL_image", "GL_ARB_sync", "GL_ARB_texture_env_add", "GL_NV_blend_square", "GL_ARB_buffer_storage", "GL_EXT_polygon_offset", "GL_EXT_subtexture", "GL_EXT_blend_func_separate", "GL_EXT_texture_array", "GL_S3_s3tc", "GL_EXT_texture_snorm", "GL_ARB_compressed_texture_pixel_storage", "GL_ARB_texture_rectangle", "GL_EXT_gpu_program_parameters", "GL_EXT_polygon_offset_clamp", "GL_ARB_texture_swizzle", "GL_ARB_draw_elements_base_vertex", "GL_NV_texture_rectangle", "GL_ARB_instanced_arrays", "GL_EXT_blend_equation_separate", "GL_MESA_texture_signed_rgba", "GL_SUN_multi_draw_arrays", "GL_EXT_texture_edge_clamp", "GL_ARB_texture_storage", "GL_ARB_texture_barrier", "GL_EXT_texture_sRGB_decode", "GL_EXT_stencil_two_side", "GL_ARB_point_parameters", "GL_SGIS_texture_lod", "GL_ARB_multitexture", "GL_ARB_texture_cube_map", "GL_EXT_blend_minmax", "GL_ARB_occlusion_query2", "GL_SGIS_texture_border_clamp", "GL_EXT_point_parameters", "GL_ARB_draw_buffers", "GL_EXT_texture_shared_exponent", "GL_ARB_texture_filter_anisotropic", "GL_IBM_texture_mirrored_repeat", "GL_ATI_texture_env_combine3", "GL_APPLE_object_purgeable", "GL_EXT_copy_texture", "GL_ARB_vertex_program", "GL_EXT_fog_coord", "GL_NV_depth_clamp", "GL_ARB_texture_non_power_of_two", "GL_ARB_clear_buffer_object", "GL_ARB_occlusion_query", "GL_ARB_depth_buffer_float", "GL_ARB_multi_bind", "GL_ARB_pixel_buffer_object", "GL_EXT_rescale_normal", "GL_ARB_internalformat_query2", "GL_ARB_clip_control", "GL_KHR_blend_equation_advanced", "GL_EXT_texture_filter_anisotropic", "GL_ARB_texture_mirror_clamp_to_edge", "GL_MESA_window_pos", "GL_ARB_shader_texture_lod", "", "GL_EXT_timer_query", "GL_ARB_seamless_cubemap_per_texture", "GL_ARB_depth_texture", "GL_SGIS_texture_edge_clamp", "GL_EXT_draw_buffers2", "GL_ARB_texture_rgb10_a2ui", "GL_ARB_vertex_type_2_10_10_10_rev", "GL_NV_packed_depth_stencil", "GL_OES_read_format", "GL_ARB_shader_bit_encoding", "GL_ARB_polygon_offset_clamp", "GL_EXT_texture_env_add", "GL_EXT_packed_float", "GL_ARB_map_buffer_range", "GL_EXT_framebuffer_sRGB", "GL_EXT_texture_cube_map", "GL_ARB_debug_output", "GL_ARB_shader_draw_parameters", "GL_ANGLE_texture_compression_dxt5", "GL_ARB_invalidate_subdata", "GL_EXT_abgr", "GL_EXT_texture_env_combine", "GL_INGR_blend_func_separate", "GL_EXT_separate_specular_color", "GL_SGIS_generate_mipmap", "GL_ARB_vertex_array_object", "GL_ARB_vertex_attrib_binding", "GL_ARB_texture_mirrored_repeat", "GL_IBM_rasterpos_clip", "GL_APPLE_packed_pixels", "GL_ARB_robustness", "GL_ARB_texture_env_combine", "GL_ARB_shading_language_100", "GL_EXT_draw_range_elements", "GL_EXT_bgra", "GL_EXT_shadow_funcs", "GL_ARB_copy_image", "GL_EXT_blend_color", "GL_ARB_fragment_program_shadow", "GL_ARB_texture_compression_rgtc", "GL_ARB_internalformat_query", "GL_ARB_arrays_of_arrays", "GL_ARB_shading_language_packing", "GL_ARB_point_sprite", "GL_ARB_draw_instanced", "GL_ARB_vertex_shader", "GL_ARB_vertex_array_bgra", "GL_EXT_texture_object", "GL_NV_texture_barrier", "GL_ARB_transpose_matrix", "GL_ATI_separate_stencil", "GL_EXT_texture_env_dot3", "GL_KHR_context_flush_control", "GL_ARB_texture_query_lod", "GL_EXT_texture_swizzle", "GL_EXT_texture_compression_dxt1", "GL_EXT_framebuffer_object", "GL_EXT_multi_draw_arrays", "GL_ARB_vertex_buffer_object", "GL_ARB_texture_compression", "GL_ARB_clear_texture", "GL_ARB_texture_rg", "GL_EXT_blend_subtract", "GL_ARB_depth_clamp"} }
[INFO][gfx_device_gl] Capabilities { max_vertex_count: 3000, max_index_count: 3000, max_texture_size: 8192, max_patch_size: 0, instance_base_supported: false, instance_call_supported: true, instance_rate_supported: true, vertex_base_supported: true, srgb_color_supported: true, constant_buffer_supported: false, unordered_access_view_supported: false, separate_blending_slots_supported: false, copy_buffer_supported: true }
[INFO][gfx_device_gl] PrivateCaps { array_buffer_supported: true, frame_buffer_supported: true, immutable_storage_supported: true, sampler_objects_supported: true, program_interface_supported: true, buffer_storage_supported: true, clear_buffer_supported: false, frag_data_location_supported: true, sampler_lod_bias_supported: true, texture_border_clamp_supported: true, texture_view_supported: false }
[INFO][gfx_device_gl::factory] 	Created frame buffer 1
[DEBUG][amethyst_renderer::pipe::effect] Building effect
[DEBUG][amethyst_renderer::pipe::effect] Compiling shaders
[INFO][gfx_device_gl::shade] 	Compiled shader 1
[ERROR][amethyst_renderer::system] Failed creating pipeline: Program compilation failed: Unable to compile the vertex shader: The shader failed to compile: 0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

Error: Core(Error(Msg("Renderer error!"), State { next_error: Some(ProgramCreation(Vertex(CompilationFailed("0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES\n")))), backtrace: InternalBacktrace { backtrace: None } }))

## Your Environment

1. Operating System: Fedora
2. Operating System Version: 27.0
3. Version of Amethyst: 0.10.0

`glxinfo | grep OpenGL`
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ironlake Mobile 
OpenGL version string: 2.1 Mesa 17.3.9
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 17.3.9
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:

**Comment by Frizi** [comment]
This issue no longer applies, we don't use GLSL directly now.
