### ISSUE TITLE
[BUG] Compile fails in nightly

### ISSUE THREAD

**Issue by martinellison** [amethyst/amethyst#1508]
## Description

Compile error in the renderer in nightly.

## Reproduction Steps

Build amethyst in nightly.

## What You Expected to Happen

Clean compile.

## What Actually Happened

Build failed; see messages below.

## Screenshots and Logs

This is what I am getting:

> /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_renderer-0.10.4/src/light.rs:185:50
>     |
> 185 | #[derive(Default, Clone, Serialize, Deserialize, PrefabData)]
>     |                                                  ^^^^^^^^^^ invalid suffix `usize`
> 
> error: proc-macro derive produced unparseable tokens

## Your Environment

> System:    Host: xiaomading Kernel: 4.4.154-59-rockchip-g5e70f14 aarch64 bits: 32
>            Desktop: Xfce 4.12.3 Distro: Ubuntu 18.04.2 LTS
> CPU:       6 core  (-MCP-)  (ARM)
>            clock speeds: max: 1416 MHz 1: 1008 MHz 2: 1008 MHz 3: 1008 MHz 4: 1008 MHz
>            5: 1008 MHz 6: 1008 MHz
> Graphics:  Card: Failed to Detect Video Card!
>            Display Server: x11 (X.Org 1.19.6 ) driver: modesetting
>            Resolution: 1920x1080@60.00hz
>            OpenGL: renderer: llvmpipe (LLVM 7.0, 128 bits) version: 3.3 Mesa 18.2.8

 "amethyst_core 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "amethyst_renderer 0.10.4 (registry+https://github.com/rust-lang/crates.io-index)",

**Comment by Patryk27** [comment]
Same as [here](https://github.com/amethyst/amethyst/issues/1492)?

**Comment by 0x6273** [comment]
If you want to use the 0.10 release on nightly, you will need to clone the repo, `git reset --hard v0.10.0`, and `git cherry-pick` [this](https://github.com/amethyst/amethyst/commit/7590fdb8ecaf608d286e28fd7a2b68ac3c93578c) and [this](https://github.com/amethyst/amethyst/commit/8ecf8d0749440033a149fb83557de38e85de836e) commit.

**Comment by torkleyy** [comment]
Ah, we should release new versions with the fix!

**Comment by Mec-iS** [comment]
On Ubuntu 18.04, this is still affecting building with official crate (0.10.0) and rust 1.34.0. Building is successful when using the code in `master` with rustc 1.34.1.

**Comment by Frizi** [comment]
This is resolved since 0.11
