### ISSUE TITLE
Release new 0.10 patch

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1510]
Crates:

* `amethyst_derive`: 0.3.0 -> 0.3.1

cc #1508

**Comment by torkleyy** [comment]
Note: this needs a backport of 8ecf8d0749440033a149fb83557de38e85de836e and 7590fdb8ecaf608d286e28fd7a2b68ac3c93578c to cb06b22a4419f8d11d4e4eef44db44d3f12e4221 since breaking changes occurred since.

**Comment by azriel91** [comment]
one more fix for amethyst_derive should probably go in -- if the enum used for the `EventReader` derive only has one variant, the generated code is invalid.

**Comment by torkleyy** [comment]
@azriel91 Is that fixed on master already?

**Comment by torkleyy** [comment]
Given that 0.11 will be released soon, and we're perfectly supporting stable Rust, I won't be investing any more time into this.
