### ISSUE TITLE
[MAINTENANCE] Update shred and specs to enable system disposal

### ISSUE THREAD

**Issue by Frizi** [amethyst/amethyst#1511]
Shred/specs recently got a new feature that enables implementing a `dispose` method on the system, to clean it up properly with access to all resources. This feature is needed to properly implement rendy graph cleanup on engine teardown (or on dispatcher drop/rebuild).

This feature depends on new shred and specs being released first (possibly with just this change cherry-picked on top of existing release).

The specific changeset that needed: [shred:6c6bfac..34859c88](https://github.com/slide-rs/shred/compare/6c6bfac85e274cdd49f2e2dc96781d1f5ee2fadc..34859c884217dce37c892059004f6fd164c5c8c2
)

**Comment by LucioFranco** [comment]
@Frizi this should be done, can we close this?

**Comment by Frizi** [comment]
Yes, this is done. Thank you!
