### ISSUE TITLE
[FEATURE MODIFICATION] Set up fixed update according to industry standard

### ISSUE THREAD

**Issue by JayPavlina** [amethyst/amethyst#1516]
## Feature

Fixed update

## Change

Make it work as a fixed update is expected to work, as explained in the classic article, [Fix Your Timestep](https://gafferongames.com/post/fix_your_timestep/).

## Reason

The way it works now is not how it is typically done in game engines and is not useful due to being tied to framerate.

## Impact

It will impact any states that use fixed update

## Additional Notes

The interpolation step as explained in the article is important, so the Time struct needs to be updated immediately after the fixed updates run, and before update. Currently Time is updated after update is called, which makes interpolation impossible.

**Comment by Laaas** [comment]
I think having framerate-independent updates in systems is really nice, but there are also systems where this is useful, for example visual effects. Is there a way to preserve both, like `State::fixed_update` and `State::update`?

**Comment by JayPavlina** [comment]
I am not sure what you mean. State.update and State.fixed_update already exist and systems can be dispatched from both.

**Comment by Laaas** [comment]
Perhaps I have misunderstood this @JayPavlina, but I understood it as that systems currently are run once per frame when using the standard `GameData` and `SimpleState`, and this changes it to be a constant rate, like with `State::fixed_update`. Did I misunderstand?

**Comment by jaynus** [comment]
This is a change to the behavior of fixed_update

**Comment by JayPavlina** [comment]
I am fairly certain systems run in update by default. I created my own GameData that has dispatchers for both.
