### ISSUE TITLE
[BUG] No longer able to implement UI button actions

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#1531]
## Description

since #1390, it isn't possible to implement a custom event handler and tie it to a `UiButton`.

## Reproduction Steps

1. Use `UiButtonBuilder` to create a `UiButton`.
2. Implement a system that listens for a `UiEvent` and reconcile the event to the button.
3. can't 😢

## What You Expected to Happen

One of:

* There is access to the `Entity`(s) created by the button (#1532).
* The `UiButton`'s widget ID is transmitted within the `UiEvent`.
* The `UiButton`'s has a component that stores its widget ID, so it can be looked up.
* ~~The `Widgets` resource also stores the entity for a given widget ID.~~ same as the first bullet point
* The `UiButtonBuilder` allows you to specify an event handler (not sure if this one is feasible).

## What Actually Happened

The API has changed and no longer allows this.

**Comment by fhaynes** [comment]
@jojolepro and @happenslol can you guys please take a look at this. This is a bad regression.

**Comment by happenslol** [comment]
Hiya! Jojo had remarked on this, but I was not immediately aware of the implications. Totally an oversight on my part, but thankfully a very quick fix.

**Comment by azriel91** [comment]
Got it going in my project, all good 👍!
