### ISSUE TITLE
[BUG] Links to documentation and API reference are broken

### ISSUE THREAD

**Issue by juchiast** [amethyst/amethyst#1541]
These links show 404 error:
- https://www.amethyst.rs/book/latest
- https://www.amethyst.rs/doc/latest/doc/amethyst

Referenced in https://www.amethyst.rs/doc/ and README.

**Comment by bamling** [comment]
I think this one can be closed; the book used to be down due to some migration...

**Comment by azriel91** [comment]
Thanks!
