### ISSUE TITLE
[MAINTENANCE] Investigate how to stop a sound and play another sound

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#1542]
# Tasks
- Find alternatives to rodio
- If no good alternative exist, create PR in rodio to rename the function to something like kill()

## Description

By design, after using `rodio::Sink#stop()` to stop a sound, you cannot play any more sounds using the same `Sink` (https://github.com/tomaka/rodio/issues/171).

Investigate how to achieve this, and come up with a solution:

* Can we abstract the functionality?
* Can we expose a simple API in `amethyst_audio`?
* Documentation for game developers on how to do this

## Reason

Because it's a common use case, but we cannot do it yet. Also it's not easily discoverable that you cannot play another sound from a stopped `Sink`, resulting in headaches.

## Impact

Good. Haha.

**Comment by SweGecko** [comment]
Here's my solution for amethyst 0.10.0. It simply replaces the old Sink with a new one, stopping all current sound playback. Can probably be rewritten more elegant.

```rust
fn stop_music(world: &mut World) {
    let sink = if let Some(ref output) = world.res.try_fetch::<Output>() {
        Some(AudioSink::new(output))
    } else {
        None
    };
    if let Some(sink) = sink {
        world.res.insert(sink);
    }
}
```

**Comment by mbillingr** [comment]
FWIW, in `ggez` I used the approach of recreating the sink. Unfortunately, this is kinda ugly because it requires that the low level output device is accessible when stopping a sound.

An alternative I chose for `ambisonic` is not to expose the sink at all. Instead, the sink just sits in the backend, forever consuming audio samples from a mixer. Sounds sources can be played and stopped by adding and removing them to the mixer.

Maybe something like that could be a viable option for `amethyst` too... maybe I'm just adding to the confusion :)

**Comment by azriel91** [comment]
@mbillingr Thanks for that :bowing_man:.
Best check out [`ambisonic`](https://crates.io/crates/ambisonic) when we improve the audio crate.

**Comment by Zizico2** [comment]
> FWIW, in `ggez` I used the approach of recreating the sink. Unfortunately, this is kinda ugly because it requires that the low level output device is accessible when stopping a sound.
> 
For a personal project of mine I made this [confort type](https://gitlab.com/snippets/1935325).
It's really simple, I just save a reference to the original device so I can use it when it I need to create a new Sink.

Btw...
Hi! I'm new to Rust and just started getting my hands dirty (after completing the books and making some simple projects of my own).

**Comment by jojolepro** [comment]
Welcome @Zizico2 !

**Comment by CleanCut** [comment]
Stale bot is configured [_not_ to close issues](https://github.com/amethyst/amethyst/blob/master/.github/stale.yml#L13).  I'm trying to figure out why it is closing them anyway.
