### ISSUE TITLE
Missing dependency in documentation

### ISSUE THREAD

**Issue by hendrikboom3** [amethyst/amethyst#1546]
On page https://amethyst.rs/book/latest/pong-tutorial/pong-tutorial-01.html
it says
If you run this project with cargo run, you'll end up with a window titled "pong" that renders a really delightful shade of green. 

But what actually happened to me was that it complained that the 'cmake' command was not available.  Of course I can install it and rerun.

But:

On page https://amethyst.rs/book/latest/getting-started.html
cmake should be mentioned in the section on Required dependencies.

**Comment by bamling** [comment]
The Getting Started page mentions the [README.md|https://github.com/amethyst/amethyst/blob/master/README.md] for Linux distribution specific dependencies. Under `Ubuntu/Debian` and `Fedora` `cmake` is mentioned. It's not directly clear from the book though so I'll see if I can change it up a bit.

**Comment by hendrikboom3** [comment]
It turns out two other Devuan/Debian packages needed to be added:

freetype2 not found: needed libfreetype6-dev
expat not found: needed libexpat1-dev

The Devuan/Debian package names were not immediately obvious from the names 'cargo run' told me were missing.  (Why a 6?  Why a 1?)

**Comment by bamling** [comment]
Okay thanks for adding that. I'll see about cleaning up the whole dependency section during the week.

**Comment by hendrikboom3** [comment]
I'm not sure this is the place to post this, but the previous discussion provides context.
I'm becoming increasingly frustrated with the tutorial.
I suspect I have done something subtly wrong.  Here's the informal log I kept as I progressed:

I tried the pong tutorial yesterday,

It all worked smoothly until I added ".with_bundle(TransformBundle::new())?" according to section "Initialise some entities" in https://amethyst.rs/book/latest/pong-tutorial/pong-tutorial-02.html#get-around-the-world

Instead, I got this error *after* I added that text:

hendrik@midwinter:~/ld/pong$ cargo run
   Compiling pong v0.1.0 (/home/hendrik/ld/pong)
error[E0433]: failed to resolve: use of undeclared type or module `TransformBundle`
  --> src/main.rs:34:22
   |
34 |         .with_bundle(TransformBundle::new())?;
   |                      ^^^^^^^^^^^^^^^ use of undeclared type or module `TransformBundle`



What could be wrong (or right?)?  Perhaps version skew between the documentation and the version I'm running?

However, when I get to the end of the "Creating a window" section, withuot the TransformBundle I get no paddles on the opened window.'


I can get .with_bundle(TransformBundle::new())?" to work if I add
use amethyst::core::transform::bundle::TransformBundle;
to the imports in main.rs.


But still no paddles.

Evidently I have done sonething wrong.  I presume the code I made from the turorial does't match what the tutorial actually intended.  I *know* there are deviations -- such as the use command I added above to get TransformBundle accepted.
 
Desperate, I tried just cloning the amethyst repository from github and compiling its examples/pong.  It seems to be significantly different from the code in the tutorial.

Compiling it doesn't work.  apparently the current examples/pong uses unstable features and the compiler I have (which says it's version rustc 1.32.0) doesn't accept unstable features.  I'm guessing these are features to be present in a future stable release, but I'm not there yet.

I think I'm hitting significant version skew problems among the various pieces of software I'm trying to use and between the tutorial and those versions.

How do I go about amassing a consistent set of stable versions?  Or do I really need to venture into unstable ground?

**Comment by bamling** [comment]
Ahh, which Amethyst version are you using? I started off using the `latest` version (`0.10`) and ended up switching the the `master` branch instead. I ran into a bunch of issues with the wrong documentation afterwards...

https://amethyst.rs/book/latest/
https://amethyst.rs/book/master/

So yeah... if you're using `0.10` make sure you're using `latest`, if you're using the `master` branch, `master`. I found it a bit confusing at first.

Alternatively hop on Discord and check out the #help channel. Probably best way to get quick feedback!

**Comment by hendrikboom3** [comment]
I seem to have acquired a serious case of version skew by following instructions online,  While asking on the discord server will may get me faster response, I will post here because the documentation evidently misled me and could be improved.

May I suggest that these links be mentioned in all versions of the documentation (at least from now on)?

https://amethyst.rs/book/latest/
https://amethyst.rs/book/master/

And that each version of the manual say which version of amethyst (and perhaps of rustc) it goes with?
If the user gets the manual directly from github she will likely know this, but if from elsewhere, she can be lost.

In the getting started section, it should invite the user to try running "amethyst --version" just to check she has the version she wants?

Also how to install a specific version.  "cargo install amethyst-tools" seems not to have found me the latest version.  Amethyst tells me

$ amethyst --version
Amethyst CLI 0.7.6

so it's probably old.  And, just to be complete,

$ rustc --version
rustc 1.32.0

That;s the version of rust my OS installed for me.  Is that one OK?

**Comment by jojolepro** [comment]
this has been fixed
