### ISSUE TITLE
[BUG] Removing Parent component causes child to be deleted

### ISSUE THREAD

**Issue by Awpteamoose** [amethyst/amethyst#1549]
## Description

Removing the Parent component from an entity causes the entity to be deleted.

## Reproduction Steps

1. Create an entity
2. Create another entity
3. Assign the first entity as a Parent
4. Remove the Parent with LazyUpdate

## What You Expected to Happen

Removing Parent shouldn't cause any entities to be deleted.

## What Actually Happened

The child entity is deleted.

**Comment by Awpteamoose** [comment]
Probably related: if I remove parent of an entity with children - the children get deleted
![](https://i.imgur.com/zl7ur0Y.gif)

**Comment by Awpteamoose** [comment]
Maybe related, deleting a Parent from an entity with children removes those children from ParentHierarchy and they aren't returned by calling `.children()`

i.e.
```rust
println!("--------------------------------------------------");
for entity in (&entities).join() {
    println!("ENTITY: {:?}", entity);
    for child in hierarchy.children(entity) {
        println!("CHILD: {:?}", child);
    }
}
for (entity, _) in (&entities, !&parents).join() {
    println!("NO PARENT: {:?}", entity);
}
for (entity, parent) in (&entities, &parents).join() {
    println!("YES PARENT: {:?}, {:?}", entity, parent);
}
println!("--------------------------------------------------");
```
```
--------------------------------------------------
ENTITY: Entity(0, Generation(1))
ENTITY: Entity(1, Generation(1))
CHILD: Entity(2, Generation(1))
ENTITY: Entity(2, Generation(1))
CHILD: Entity(3, Generation(1))
ENTITY: Entity(3, Generation(1))
NO PARENT: Entity(0, Generation(1))
NO PARENT: Entity(1, Generation(1))
YES PARENT: Entity(2, Generation(1)), Parent { entity: Entity(1, Generation(1)) }
YES PARENT: Entity(3, Generation(1)), Parent { entity: Entity(2, Generation(1)) }
--------------------------------------------------
REMOVING PARENT OF Entity(2, Generation(1))
--------------------------------------------------
ENTITY: Entity(0, Generation(1))
ENTITY: Entity(1, Generation(1))
ENTITY: Entity(2, Generation(1))
ENTITY: Entity(3, Generation(1))
NO PARENT: Entity(0, Generation(1))
NO PARENT: Entity(1, Generation(1))
NO PARENT: Entity(2, Generation(1))
YES PARENT: Entity(3, Generation(1)), Parent { entity: Entity(2, Generation(1)) }
--------------------------------------------------
```

This is very much unexpected, even though this is [documented](https://github.com/rustgd/specs-hierarchy) behaviour by `specs-hierarchy`.
```
When an Entity that is a parent gets removed from the hierarchy, the full tree of children below it will also be removed from the hierarchy.
```

**Comment by jaynus** [comment]
Looking into this, this is a combined issue on our usage of specs-hierarchy in transform as well as a standing bug in the upstream crate itself. I'm going to push an upstream fix to the crate, and then probably integrate the rest of the fix into the transform refactor

**Comment by jojolepro** [comment]
Is this still an issue?

**Comment by Awpteamoose** [comment]
Indeed it is.

**Comment by OvermindDL1** [comment]
I'm curious:  I'd expect children to be deleted when the parents are deleted unless the children are unparented first, is that not what is happening here?

**Comment by Awpteamoose** [comment]
No, I'm just deleting the Parent component, not the actual entity. Basically if you want to unparent an entity that has children - you can't do that.

**Comment by OvermindDL1** [comment]
That's still what I would expect, the parent component conceptually takes 'ownership' of its children, and would need to remove the children first otherwise.  Reasoning is that the children should not have an orphan parent.  My old C++ ECS engine worked the same way, when the parent 'component' was removed the children 'entities' were removed as well, this is the case that I would always want as the children entities would be things like attached weapon points as one example.

**Comment by Awpteamoose** [comment]
Yeah but why would you not just remove the whole entity at that point. You have no option to just remove the component.

My use case is with [amethyst-inspector](github.com/awpteamoose/amethyst-inspector) when I drag a child entity to top scope, like if I'm trying to rearrange the scene for example, it gets deleted along with its children. Once an entity gets a Parent there's no way to get rid of it, which is basically my issue.

**Comment by OvermindDL1** [comment]
> Yeah but why would you not just remove the whole entity at that point. You have no option to just remove the component.

The times when I remove the parent component to delete the children is actually in a heavily used section of my sandbox tests, specifically chunk handling, when the chunk is removed due to distance it removes children and it's positional mapping while serializing out its state, it is then reused loading new state for another chunk that came into view distance, the new location makes it able to be looked up by that new location and it will get new children instanced in.

> Once an entity gets a Parent there's no way to get rid of it, which is basically my issue.

If this is the case then this is wrong, there must always be a way to disconnect the children from the parent or vice-versa.

**Comment by tuzz** [comment]
I bumped into this same issue on a personal project. If the `Parent` component is removed from an entity, then arguably that entity is a root node of the hierarchy and its descendants shouldn't be removed from it.

I worked-around this issue by listening in on specs-hierarchy's channel and remembering which entities were removed from the hierarchy:

```rust
let mut removed = BitSet::new();

for event in hierarchy.changed().read(reader_id) {
    if let HierarchyEvent::Removed(entity) = event {
        removed.add(entity.id());
    }
}
```

I then join over all entities with the `Parent` component and add them back to the hierarchy by re-adding their `Parent` component:

```rust
(&parents, &entities).join()
    .filter(|(parent, _)| removed.contains(parent.id()))
    .map(|(_, child)| child).collect::<Vec<_>>().iter()
    .for_each(|child| {
        let p = parents.remove(*child).unwrap();
        parents.insert(*child, p).unwrap();
});
```

Finally, I have to run the hierarchy system for those changes to be reflected:

```rust
hierarchy_system.run_now(&mut world);
```

It's hacky and adds overhead but it keeps things consistent - at least, the way I'd expect them to be.

**Comment by OvermindDL1** [comment]
> then arguably that entity is a root node of the hierarchy and its descendants shouldn't be removed from the hierarchy.

Wait, why not in this case?  If you remove the root node then shouldn't everything bound to it also be removed, otherwise where would it make sense to put it in the hierarchy at that point?  Would you put it at the transformed location based on the now-removed parent into the upper global space, or into the parent's parent space, or not transform them and just move them to either global or the parent's parent?

**Comment by tuzz** [comment]
Maybe I could have phrased:
>then arguably that entity is a root node

Better as:
>then arguably that entity _becomes_ a root node

What I mean is that by removing the `Parent` component of an entity, that entity no longer has a parent. By definition, a node in a tree that has no parent is a root node.

As for how the transforms should now be interpreted, I think an example will help. Let's say we have three entities A, B and C with these components:

```
A: Translation(1, 2, 3)
B: Translation(1, 0, 0), Parent(A)
C: Translation(0, 1, 0), Parent(B)
```

That means A is a root entity, B is a child and C is a grandchild. Entities B and C have parents so we should interpret their `Translation` to be relative to their parent. For example, C's overall `Translation` would be `(1, 2, 3) + (1, 0, 0) + (0, 1, 0) = (2, 3, 3)`.

Now let's say we remove the `Parent(A)` component from B. That would mean the world now looks like this:

```
A: Translation(1, 2, 3)
B: Translation(1, 0, 0)
C: Translation(0, 1, 0), Parent(B)
```

Now we have two root nodes! Or rather, we've split our tree into two with A being the root of one tree and B being the root of the other. B's overall translation should now be interpreted as `(1, 0, 0)` and C's should be `(1, 0, 0) + (0, 1, 0) = (1, 1, 0)`.

Is this the right interpretation? Well, if we do what `specs-hierarchy` currently does and remove C from the hierarchy all together, then we're in an inconsistent state. C has a `Parent` component of `B` but it's being completely ignored. That seems wrong to me.

What do you think?

**Comment by Awpteamoose** [comment]
Not stale, maybe resolved by legion.

**Comment by distransient** [comment]
Whether legion fixes this or not this should be fixed for Specs. Is there an issue in the specs-hierarchy repository?

**Comment by AlveLarsson** [comment]
Hello, this issue has been marked stale or inactive.
We are currently going to go through major rewrites, please re-evaluate if this issue when 0.16 has been released. Closing this, for now, Thanks for your interest!
