### ISSUE TITLE
[SPIKE] Investigate current state of glow

### ISSUE THREAD

**Issue by fhaynes** [amethyst/amethyst#1555]
Investigate what needs to be moved into the glow crate from gfx-rs. https://github.com/grovesNL/glow. Priority should be given to the minimum things we need for our use-case. Prepare a prioritized list of work items.

Estimated time: 4 hours

**Comment by erlend-sh** [comment]
glow has been added as a OpenGL/WebGL backend in gfx-rs: https://github.com/gfx-rs/gfx/pull/2554

**Comment by omni-viral** [comment]
Yeap. And it works.
@fhaynes What did you mean by "needs to be moved into the glow crate from gfx-rs"?

**Comment by jojolepro** [comment]
Was this completed yet?

**Comment by omni-viral** [comment]
Yes. Glow is great! gfx-backend-gl uses it to abstract webgl/opengl and I had no issues with it.
