### ISSUE TITLE
[NEW FEATURE] Video Playback API

### ISSUE THREAD

**Issue by khionu** [amethyst/amethyst#1560]
# Tasks
- Ensure that we can load videos from files
- Add ability to play videos in renderer

## Description

Amethyst should provide for importing video media formats and playing them inside the game.

## What problem does this solve? What need does it fill?
There are plenty of times when you want to include a video that is a premade asset, including Cut Scenes or NPC video messages.

## Describe the solution you'd like
The solution should allow for playing, pausing, and stopping of the video, as well as controlling the speed of playback. The video should be rendered to a texture, to support render targets in the future.

We should aim to support splicing of videos, so they can be rendered across textures, to support a single video recording rendered across multiple surfaces.

**Comment by ishitatsuyuki** [comment]
Ideally with hardware acceleration. Software decoding is retarded but it seems game engines tend to lag behind (as a reference, Unreal Engine only just implemented it recently).

**Comment by jojolepro** [comment]
Gif support would be great too.

Also please refrain from using language like "retarded", thanks.

**Comment by jojolepro** [comment]
delet stale

**Comment by distransient** [comment]
This is an important feature the engine needs to support. Not stale.
