### ISSUE TITLE
[MAINTENANCE] Migration documentation for 0.11

### ISSUE THREAD

**Issue by distransient** [amethyst/amethyst#1561]
This should be a blocker for 0.11. While Renderer API (afaik) shouldn't change much, the generic parameter on Transform and removal of GlobalTransform will ***need*** a section in the book's *Appendix B: Migration Notes*.

**Comment by azriel91** [comment]
Need to write the page for this: https://github.com/amethyst/amethyst/pull/1451#issuecomment-469924537

**Comment by jojolepro** [comment]
+ add explanation of the missing resource issue if you don't specify the generic parameter of transform.

**Comment by torkleyy** [comment]
> add explanation of the missing resource issue if you don't specify the generic parameter of transform.

Is this still relevant? I think you changed it to a typedef, right?

**Comment by distransient** [comment]
I believe this has been resolved by #1594 #1626
