### ISSUE TITLE
[BUG] ComponentEvent reader for Transform constantly receives Modified events on master

### ISSUE THREAD

**Issue by bamling** [amethyst/amethyst#1563]
## Description

Since the recent `Transform` refactoring, it seems like the `ComponentEvent` reader for `Transform` keeps receiving `ComponentEvent::Modified` events, despite none of my `System` accessing `Transform`s in a mutable fashion. After having a quick chat with @azriel91 we narrowed it down to the `TransformSystem` triggering these events. This takes away from the `FlaggedStorage` features and makes it impossible to react to `Transform`s that were modified in the context of my game.

## Reproduction Steps

Create a `ReaderId<ComponentEvent>` for `Transform`s:
```
let transforms_reader = {
    let mut transforms = world.write_storage::<Transform<f32>>();
    transforms.register_reader()
};
```

Access the `ReadStorage<'s, Transform<f32>>` and read from its channel:
```
// `self.component_event_reader` is the `transforms_reader`.
for component_event in transforms.channel().read(&mut self.component_event_reader) {
    match component_event {
        ComponentEvent::Modified(id) => { println!("Got Modified for: {}", id); }
        _ => {}
    }
}
```

You'll end up seeing constant `Got Modified for:` messages for each `Entity`.

## What Actually Happened

`ComponentEvent::Modified` events are only triggered when my own, defined `System`s access `Transform` mutably.

## Your Environment

Amethyst version: 
`master` with Commit ID `331e83c46250464c38936f56a97fa1416bbbbe92`

**Comment by torkleyy** [comment]
This seems to be a problem with `global_matrix` stored inside `Transform`.

This way, writing to `Transform` will inevitably create a `Modified` event for this and the next frame (and right now it just creates that event every frame without any condition).

I think we need to write the global transform to a second component (I think this was the case before the transform refactor).

@jojolepro What was the reason for the change?

**Comment by bamling** [comment]
The referenced issue has been merged 2 days ago but that didn't seem to fix this. I used the current `master` earlier today and it still floods me with `ComponentEvent`s for `Transform`. Not sure if the issue was **supposed** to fix it but I figured I'd let you guys know anyways.

**Comment by bamling** [comment]
As of now (`git+https://github.com/amethyst/amethyst#85365d5543b9be0daa891706c5d46c80ee38f9ca`) this is still an issue. Any update on this?

**Comment by torkleyy** [comment]
This is still an issue. The PR only fixed serialization, so this bug remaons.

There are essentially three problems:

1) The global matrix is stored inside the `Transform`
2) A change of the `Transform` will trigger a matrix recalculation
3) A matrix recalculation triggers a change of the `Transform`

**Comment by Moxinilian** [comment]
Can we change FlaggedStorage to have silent gets maybe?

**Comment by torkleyy** [comment]
Well, theoretically, we could add a method to it and use unsafe code in the `TransformSystem`, but I really don't think it's a good idea.

What's the problem with separating? It's much more idiomatic, involves no special casing and allows you to load less data when iterating over transforms.

**Comment by Moxinilian** [comment]
Alright, besides, offering ways to bypass the flagging goes a bit against the idea of it.
Why use unsafe however?

**Comment by torkleyy** [comment]
> Why use unsafe however?

To access the `FlaggedStorage` with a custom method, we need to gain access to it (we cannot use `Storage::get`). Getting the unprotected storage (and accessing it) is unsafe.

**Comment by jojolepro** [comment]
This is a problem only if you have another system that is both listening and emitting transform changed events. The loop inside of the TransformSystem was resolved already.

**Comment by Moxinilian** [comment]
So in practice how would one get around it?

**Comment by torkleyy** [comment]
> The issue with using two write systems both reading for changed events is that you can't avoid loops at all, but that's like that for all flagged storage components.

No, that's not the issue. The issue is that you cannot write to a component whenever the component change, because then you will create an infinite loop (since every change event will trigger another change event).

This is the problematic line:

https://github.com/amethyst/amethyst/blob/16479480c052daa8661a6affdaad57f702e53b65/amethyst_core/src/transform/systems.rs#L112

**Comment by jojolepro** [comment]
That's why I empty the event buffer in that system after the write.

**Comment by torkleyy** [comment]
Ah, oops, sorry. So this issue seems solved then?

**Comment by jojolepro** [comment]
Yes https://github.com/amethyst/amethyst/pull/1564/files#diff-c5fa314622c177e7521dc59145ab1ca6R483

**Comment by jojolepro** [comment]
So now, it groups the global matrix change event with the local change event. This means that if you move a parent entity, you'll get a modified event in the child entity too. What is your use case for needing to get only local change events @bamling ?
