### ISSUE TITLE
[FEATURE MODIFICATION] PrefabData and shared SystemData access

### ISSUE THREAD

**Issue by Awpteamoose** [amethyst/amethyst#1565]
## Feature

`PrefabData::add_to_entity`

## Change

Rework it to allow multiple Prefabs to `Write` the same resources.

## Reason

I'm serializing rigid body descriptions and I'm not including the transform data because it's meant to be taken from the `Transform` component. So my rigidbody's `add_to_entity` wants `Read<'a, Transform>` and I crash because `Write<'a, Transform>` is used by `Transform`'s `PrefabData` implementation.

## Impact

For the time being I solved it with `LazyUpdate` but it's just punting the problem since potentially there could be components that depend on my rigid body and so on.

## Additional Notes

One potential solution would be to just run all `add_to_entity`s in a `LazyUpdate::exec_mut` and pass `&mut World` instead of `SystemData` to `add_to_entity`. If there's some setup that should be paralellized, maybe provide a separate `setup` method for PrefabData, kind of like what systems have.

As a side effect of the current implementation, prefab components are added to the entity with the prefab handle right away, but all child entities and their components are only added next frame. It might be desired sometimes, but it's still weird and unexpected that not the whole prefab is merged into the entity at the same time.

**Comment by Rhuagh** [comment]
Just a short note: you should never add the prefab handle to an entity before the loading is complete.  Track the load status with a ProgressCounter, and only add the handle once that reports completed.

**Comment by Rhuagh** [comment]
This is likely to be the issue with partial adds, the only other issue would be if the loaders are running in reverse order (higher level prefab loaders should run before lower level).

**Comment by jojolepro** [comment]
Not stale, we should look more in details if using a LazyUpdate approach is beneficial.
