### ISSUE TITLE
[FEATURE MODIFICATION] Missing PrefabData implementations

### ISSUE THREAD

**Issue by Awpteamoose** [amethyst/amethyst#1566]
## Feature

Some trivially prefabbable components are missing implementation. Namely:
* UiTransform
* Rgba
* Transparent
* Flipped

Might be others, but these are the ones I ran into.

## Change

Just a trivial impl like:
```rust
impl<'a> assets::PrefabData<'a> for $cmp {
	type SystemData = WriteStorage<'a, Self>;
	type Result = ();

	fn add_to_entity(&self, entity: Entity, storage: &mut Self::SystemData, _: &[Entity], _: &[Entity]) -> Result<Self::Result, amethyst::error::Error> {
		storage.insert(entity, self.clone())?;
		Ok(())
	}
}
```

**Comment by Frizi** [comment]
Be aware of some changes that are coming soom from `rendy` branch:
- Rgba is going to be replaced with types from `palette` crate
- Transparent has PrefabData implemented
- I would like to get Flipped component removed. You can either use sprites with reversed texcoords in your spritesheet, or transform with negative scale.
