### ISSUE TITLE
Port existing amethyst examples to new renderer

### ISSUE THREAD

**Issue by Frizi** [amethyst/amethyst#1575]
Many examples are still using old renderer crate, which is going away. Those need to be ported to rendy. 

- 🙏 - to do
- 🚧 - taken
- ✔️ - in `rendy` branch
- :recycle: - replaced by doc example
- :x:  - removed

| 🏴󠁧󠁢󠁮󠁩󠁲󠁿 | Example | Assignee |
| - | - | - |
| ✔️ | animation | @Frizi |
| :x: | appendix_a  | @Frizi |
| ✔️ | arc_ball_camera | @valkum |
| ✔️ | asset_custom | @torkleyy |
| ✔️ | asset_loading | @Frizi  |
| ✔️ | auto_fov | @jojolepro |
| ✔️ | custom_game_data | @valkum |
| :recycle: | custom_icon | @torkleyy |
| ✔️ | custom_ui | @Frizi |
| ✔️ | debug_lines | @Frizi |
| ✔️ | events | @torkleyy |
| ✔️ | fly_camera | @jaynus |
| ✔️ | gltf  | @frizi |
| ✔️ | headless_server | @jojolepro |
| ✔️ | hello_world | @Frizi |
| ✔️ | locale | @jojolepro  |
| ✔️ | material | @jaynus |
| ✔️ | net_client | @jojolepro |
| ✔️ | net_server | @jojolepro |
| ✔️ | pong | @Moxinilian |
| ✔️ | pong_tutorial_01 | @jaynus |
| ✔️ | pong_tutorial_02 | @jaynus |
| ✔️ | pong_tutorial_03 | @jaynus |
| ✔️ | pong_tutorial_04 | @Moxinilian |
| ✔️ | pong_tutorial_05 | @Moxinilian |
| ✔️ | prefab | @Frizi |
| ✔️ | prefab_adapter | @Frizi |
| ✔️ | prefab_basic | @Frizi |
| ✔️ | prefab_custom | @Frizi |
| ✔️ | prefab_multi | @Frizi |
| ✔️| renderable | @termhn |
| ✔️ | rendy | @Frizi |
| :x: | seperate_sphere | @Frizi |
| :x: | simple_image | @termhn |
| ✔️ | sphere | @Frizi |
| :x: | sphere_multisample | @Frizi  |
| ✔️ | spotlights | @Frizi |
| ✔️ | sprite_animation | @jaynus |
| ✔️ | sprite_camera_follow | @jaynus |
| ✔️ | sprites_ordered | @jaynus |
| ✔️ | state_dispatcher | @jojolepro |
| ✔️ | ui |  @Frizi |
| ✔️ | window | @jaynus |

**Comment by valkum** [comment]
Arc_ball_camera done by me. Currently working on custom_game_data

**Comment by torkleyy** [comment]
I believe we can close this :tada:
