### ISSUE TITLE
[MAINTENANCE] Add to docs that libexpat-dev may be required

### ISSUE THREAD

**Issue by storyfeet** [amethyst/amethyst#1576]
## Note

Trying to run an amethyst project I continuosly got the error expat required, because of the font system,
```
configure: error: 
*** expat is required. or try to use --enable-libxml2
make: *** [makefile.cargo:83: /home/matthew/bdata/scripts/rust/games/pong/target/debug/build/servo-fontconfig-sys-2dacb3418eb24097/out/Makefile] Error 1
thread 'main' panicked at 'assertion failed: Command::new("make").env("MAKEFLAGS",
                         env::var("CARGO_MAKEFLAGS").unwrap_or_default()).args(&["-R",
                                                                                 "-f",
                                                                                 "makefile.cargo"]).status().unwrap().success()', /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/servo-fontconfig-sys-4.0.7/build.rs:20:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

```

The solution was to make sure libexpat-dev was installed.

## Description

Please add to the docs that libexpat-dev may be needed.

## Reason

To save people the headache I had getting things working

Why should this change be made?

## Impact

I don't think the impact will be bad, maybe a few extra checks for people 

thanks
Matt

**Comment by bamling** [comment]
I'm doing a rework of the system dependencies for multiple Linux distributions in the near future... I'll keep that in mind. :)

**Comment by torkleyy** [comment]
This is fixed now thanks to @bamling!
