### ISSUE TITLE
[BUG] Sprites not rendering in a Cargo workspace environment

### ISSUE THREAD

**Issue by bamling** [amethyst/amethyst#1579]
## Description

I ended up converting my test project from a normal Cargo binary crate project into a workspace containing the initial, unchanged project as the workspace member `game` and a secondary WIP member called `game_physics`. After converting the project the sprites stopped rendering, but the rest of the project still worked as intended. I made sure that the `application_root_dir` is set correctly; the game crashes as expected when either of my assets or resources cannot be found. As soon as I remove `game` from the Cargo workspace via `exclude` and have it run as a standalone project again things work without an issue.

@azriel91 and Dispersia had a look at this and think it might be an issue with the current renderer.

This is is the example project:
https://github.com/bamling/amethyst-nphysics-example

## Reproduction Steps

1. Checkout the example project.
2. Execute `cargo run` inside the `game` crate directory; sprites render as expected.
3. Modify the root level `Cargo.toml` to include `game` as a `workspace`.
4. Execute `cargo run` inside the `game` crate directory; sprites disappear.

## What You Expected to Happen

I'd expect things to be rendered properly in a Cargo workspace environment.

## What Actually Happened

_see above_
The logs are clean, the application starts properly and seems to load the resources but the sprites won't show.

## Your Environment

1. ArchLinux 
2. `5.0.9-arch1-1-ARCH`
3. `master` with CommitID `331e83c46250464c38936f56a97fa1416bbbbe92`
@azriel91 and Dispersia could reproduce the issue so it does not seem to be OS related.

**Comment by bamling** [comment]
Chances are this won't be an issue with `rendy` anymore. I'll verify that as soon as `rendy` is merged to `master`.

**Comment by azriel91** [comment]
The assets (sprite sheet, prefabs) were verified to have loaded successfully -- `asset_storage.get(handle)` returned `Some`.

**Comment by bamling** [comment]
No longer an issue with the Rendy release.
