### ISSUE TITLE
[FEATURE MODIFICATION] Provide a way to create a SpriteRenderPrefab instance

### ISSUE THREAD

**Issue by mvlabat** [amethyst/amethyst#1585]
## Feature

Currently `SpriteRenderPrefab` can't be manually instantiated as it has a private field called `handle`.

## Change

Can't suggest anything smarter than just making it public or providing a constructor that can leave this field as `None`.

## Reason

I'm developing a tool for my project that can allow creating `SpriteRenderPrefab` and `AnimationSetPrefab` programmatically, along with generating a texture atlas. I would like to create these structs, then serialize them and save to a `ron` file. Currently I'm not able to do so as `SpriteRenderPrefab` can't be instantiated.

## Additional Notes

The problem can be worked around with deserializing the struct from a string, but I can hardly call that as a desirable way to solve it..

**Comment by mvlabat** [comment]
The issue is still relevant

**Comment by jojolepro** [comment]
I would suggest using the new-derive crate and macro with a `#[new(default)]` attribute on the handle field instead.
