### ISSUE TITLE
[MAINTENANCE] CONTRIBUTING.md

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#1589]
## Note

https://github.com/amethyst/amethyst/blob/master/docs/CONTRIBUTING.md#writing-documentation should indicate how to test book changes with the mdbook -L ... command.

## Reason

I have bad memory and keep forgetting the exact command :P

**Comment by distransient** [comment]
Related: #1587

The command is as follows:
```
# mdbook test $DIR -L $LIB_PATH
mdbook test book -L target/debug/deps
```

**Comment by marot** [comment]
The `CONTRIBUTING.md` file should also include that 
```
cargo clean
cargo build
```
will be necessary if mdbook has problems resolving the dependencies.
