### ISSUE TITLE
Use GFX for rendering

### ISSUE THREAD

**Issue by kvark** [amethyst/amethyst#16]
Creating a game engine is a huge effort. Your goals for rendering seem to perfectly match GFX domain:
> Renderer optimized for modern graphics APIs, e.g. Vulkan, Direct3D 12+, Metal.

I suppose, if you go this way and succeed, you will end up with your own cross-API rendering library. But then - why not put a fraction of this effort into GFX itself, so that we can benefit greatly from cooperation?

If you continue doing your own thing, this issue may at least contain the reasoning (or a discussion) for such a decision, and this kind of feedback is much appreciated.

**Comment by ebkalderon** [comment]
Copied from issue #7:

I have indeed. However, I drafted the design of my renderer well before gfx-rs officially rolled out pipeline state object support. Incorporating gfx-rs into the renderer is back on the table, now that PSO support is fully baked. Hopefully, gfx-rs will develop a working Vulkan backend and then the renderer can be greatly simplified.

**Comment by ebkalderon** [comment]
If this feature is implemented, this will invalidate issue #7.

**Comment by ebkalderon** [comment]
With the 0.2.0 release, the renderer now depends on gfx-rs. This means that issue #7 is now invalid. The functionality has not been implemented yet, however, so this issue will remain open.

**Comment by ebkalderon** [comment]
This issue is now a dependency of #19.

**Comment by kvark** [comment]
Fixed by #49
