### ISSUE TITLE
[MAINTENANCE] Add tests for Camera

### ISSUE THREAD

**Issue by valkum** [amethyst/amethyst#1603]
## Description

We should add tests to `Camera`. I'am not quite sure what the best way to test would be.

We can pop in a couple of points, multiply them by the projection matrix and check the result but my mind thinks there is a better way. But I have no idea what this would be.
Other libs don't have tests or just dummy tests (looking at you glm) so no inspiration about test cases from others.

## Reason

Currently there are no tests for our Camera implementation. As it has some todos and needs improvement (exposing (un)project methods etc.) we really should add tests to avoid bugs.

## Impact

No negativ impact. Only hardening.

## Additional Information

Any extra info you want to add can go here

**Comment by ecumene** [comment]
Hi there, I'm interested in contributing.

Looking at `cam.rs` in `amethyst_renderer`, if it's just a mat4 one should test that the projection constructors produce the correct matrix? For testing matrices, you can just compare their determinants. Perhaps I'm not well versed in this

**Comment by valkum** [comment]
Tests were added to the new camera in amethyst_rendy
