### ISSUE TITLE
[BUG] Compile error in amethyst_assets

### ISSUE THREAD

**Issue by martinellison** [amethyst/amethyst#1607]
_Edit: Fixed in master,_

## Description

Compile error in amethyst_assets in nightly or stable.

## Reproduction Steps

Try to build an app that uses amethyst:

```
cd ~/extgit/amethyst/    # contains git@github.com:amethyst/amethyst.git
git pull
cargo run --example sphere
```

## What You Expected to Happen

Builds ok.

## What Actually Happened
Build failed, see error below.

## Screenshots and Logs
This is the error message:
```
error[E0283]: type annotations required: cannot resolve `std::string::String: std::convert::AsRef<_>`
   --> amethyst_assets/src/prefab/mod.rs:385:22
    |
385 |                 name.as_ref(),
    |                      ^^^^^^
```

## Your Environment

Linux xiaosan 5.0.16-200.fc29.x86_64 #1 SMP Tue May 14 18:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Amethyst -- current git commit df2b163eea2c8a154ed77d2f3d0fc374fa41cc59

**Comment by hbina** [comment]
what rust toolchain are you using?

**Comment by skyne98** [comment]
@hbina latest nightly, in my case. The same issue.

**Comment by covercash2** [comment]
same issue

```
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.36.0-nightly (73a3a90d2 2019-05-17)
```

**Comment by covercash2** [comment]
PR: #1619

**Comment by martinellison** [comment]
cargo 1.36.0-nightly (c4fcfb725 2019-05-15)
rustc 1.36.0-nightly (7d5aa4332 2019-05-16)
rustup 1.18.2 (a0bf3c9cb 2019-05-02)

> rustup show
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.36.0-nightly (7d5aa4332 2019-05-16)

I have tried both nightly and stable with the same result.

**Comment by martinellison** [comment]
Fixed in master.
