### ISSUE TITLE
[BUG] Logo is missing from documentation page

### ISSUE THREAD

**Issue by KSXGitHub** [amethyst/amethyst#1621]
## Description

Cannot load logo when visit documentation page.

## Reproduction Steps

1. Open a browser
1. Go to https://docs-src.amethyst.rs/master/amethyst/ or https://docs.rs/amethyst/0.10.1/amethyst/

## What You Expected to Happen

Logo appears.

## What Actually Happened

Error 404

> NOT FOUND
> You just hit a route that doesn't exist... the sadness.

## Screenshots

![amethyst doc with missing logo](https://user-images.githubusercontent.com/11488886/58017259-efe2bb00-7b29-11e9-83e7-5185971c2216.png)

**Comment by mralve** [comment]
This issue is probably better suited in the https://github.com/amethyst/website repo in amethyst.

**Comment by KSXGitHub** [comment]
@mralve That repo is deprecated

**Comment by torkleyy** [comment]
Hmm, cannot reproduce.

**Comment by KSXGitHub** [comment]
It's been fixed.
