### ISSUE TITLE
[BUG] Compile error "method `dispose` is not a member of trait `RunNow`" at amethyst_rendy/src/system.rs:245

### ISSUE THREAD

**Issue by martinellison** [amethyst/amethyst#1631]
## Description

Build fails

## Reproduction Steps

> cd ~/extgit/amethyst/ # amethyst from github
> git pull
> cargo +nightly run --example sphere

Also fails similarly with `+stable`.

## What You Expected to Happen

Build succeeded

## What Actually Happened

Build error:

> error[E0407]: method `dispose` is not a member of trait `RunNow`
>    --> amethyst_rendy/src/system.rs:245:5

## Your Environment

> Linux xiaosan 5.0.16-200.fc29.x86_64 #1 SMP Tue May 14 18:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Amethyst latest git:

> commit 4800ac5a79ea15b9cfe731d9aab18f0f2a7c3a10 (HEAD -> master, origin/staging, origin/master, origin/HEAD)
> Merge: 6bdc329e 7ed8432d
> Author: bors[bot] <bors[bot]@users.noreply.github.com>
> Date:   Wed May 22 21:23:34 2019 +0000

**Comment by jojolepro** [comment]
Did you try running `cargo update`?

**Comment by martinellison** [comment]
OK thanks, I ran `cargo update` and  it compiled. I now have a (presumably unrelated) run-time error, but I am closing this ticket as the compile error is gone.
