### ISSUE TITLE
Update book to use new API after rendy rewrite

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1647]
The current book on master needs to be updated to actually work with the code on master.

This issue will track progress & assignees for all the chapter as this will require some effort.

## Steps

How to work on a book chapter:

1. Temporarily remove the other chapters from `book/src/SUMMARY.md`
2. `cargo clean && cargo build --all --features "gltf vulkan"`
3. Use `mdbook test book -L target/debug/deps` to check for compilation issues
4. Read the main file (`book/src/chapter_name.md`) and the sub-chapters (`book/src/chapter_name/*.md`) and check them for accuracy
5. Open a PR with your fixes, discarding changes in `book/src/SUMMARY.md`

## Progress

- 🙏 - to do
- 🚧 - chapter is being worked on
- ✔️ - chapter is correct

| 🏴󠁧󠁢󠁮󠁩󠁲󠁿 | Chapter | Assignee |
| - | - | - |
| ✔️ | animation | n/a |
| ✔️ | appendices | @azriel91 |
| ✔️ | assets | @torkleyy |
| ✔️ | concepts | @torkleyy |
| ✔️ | controlling_system_execution | @hbina |
| ✔️ | getting_started | @torkleyy |
| ✔️ | pong-tutorial | (see sub chapters below) |
| ✔️ | pong-tutorial - Creating a window | @belovachap |
| ✔️ | pong-tutorial - Drawing the paddles | @Frizi |
| ✔️ | pong-tutorial - Making a ball move and bounce | @Frizi |
| ✔️ | pong-tutorial - Winning rounds | @Frizi |
| ✔️ | prefabs | @torkleyy |
| 🚧 | sprites | @torkleyy |
| 🚧 | testing | @torkleyy |

**Comment by hbina** [comment]
> Temporarily remove the other chapters from book/src/SUMMARY.md

You meant to delete/move the folders mentioned in SUMMARY.md?

Also, whenever I run step 3 I get the following error:

`error: Found argument '-L' which wasn't expected, or isn't valid in this context`

**Comment by torkleyy** [comment]
> You meant to delete/move the folders mentioned in SUMMARY.md?

No, just remove the lines mentioning the chapters.

> Also, whenever I run step 3 I get the following error:

Ah, yes, sorry. It should be `mdbook test` instead.

**Comment by hbina** [comment]
Soooo I was confused why there are absolutely no errors at all for Pong tutorials and noticed that one of the "tags" or whatever for the code section is marked as `no_run`....is this intended?

**Comment by azriel91** [comment]
Most (if not all) of the `no_run` sections are intended -- it means the code snippet is still compiled, but isn't run because that would be running an interactive application.

**Comment by azriel91** [comment]
Pong book updates depend on https://github.com/amethyst/amethyst/pull/1673. I'm in favour of that being merged (maintains previous coordinate system).
