### ISSUE TITLE
[FEATURE MODIFICATION] Simpler RenderingSystem initialisation with default GraphCreator

### ISSUE THREAD

**Issue by bamling** [amethyst/amethyst#1649]
## Feature

The new `RenderingSystem` (the initialisation in particular) based on `Rendy`.

## Change

Right now it's required to explicitly create a `GraphCreator` and pass it to the `RenderingSystem`s initialiser:

```rust
let game_data = GameDataBuilder::default()
    // ...
    .with_thread_local(RenderingSystem::<DefaultBackend, _>::new(
        ExampleGraph::default(),
    ));

// ...

#[derive(Default)]
struct ExampleGraph {
    dimensions: Option<ScreenDimensions>,
    surface_format: Option<Format>,
    dirty: bool,
}

impl GraphCreator<DefaultBackend> for ExampleGraph {

// ...
```

Most Amethyst examples use the exact same `ExampleGraph` which (from what I can tell) handles the rendering of sprites and the UI elements. In most cases this should be more than enough and creating your own `GraphCreator` should be handled as an "advanced" feature with its own chapter in the book.

In my opinion the `RenderingSystem` should offer a _default_ initialiser that uses the `GraphCreator` from the example. Another option would be an easily configurable `GraphCreator` which lets you select the elements that should be handled:

```rust
GraphCreator::default()
    .with_sprite_pass()
    .with_draw_flat2d_pass();
```

## Reason

The current implementation feels a bit intimidating for someone new to Amethyst and brings a lot of boiler plate code with it, which for many projects will probably just be copied and pasted anyways.

**Comment by termhn** [comment]
While I know that @Frizi has been pretty vocal about not wanting to do this, and I do to an extent agree with his opinion which is basically that we should strive to make there be less or zero separation between what you need to do for a simple system to then build upon it up to an advanced one, designing a system like that is going to take time and probably several iterations.... And I think this is a serious enough UX issue currently that a stopgap solution is warranted, and honestly, I think having a few default graph implementation is not really much of a sin anyway.

**Comment by jojolepro** [comment]
Fixed by the new plugin system made by frizi
