### ISSUE TITLE
This Week in Amethyst is badly outdated.

### ISSUE THREAD

**Issue by binary132** [amethyst/amethyst#165]
Do you plan to update this section of the site or should the link perhaps be removed from the README since it is currently a bit misleading?

**Comment by Emilgardis** [comment]
See #158

**Comment by ebkalderon** [comment]
@binary132 Agreed, it is really outdated. We will update the blog once 0.4.0 is released, as mentioned previously in #158. Long term, we will need to find a way to partially automate the creation of *TWIA* articles so they come out on a more regular schedule. I'll close this issue for now, but if you would like to extend the discussion further, feel free to reopen it!
