### ISSUE TITLE
[BUG] DisplayConfig RON in docs is outdated

### ISSUE THREAD

**Issue by humb1t** [amethyst/amethyst#1657]
## Description

If you would copy an [example ](https://docs-src.amethyst.rs/master/amethyst_renderer/struct.DisplayConfig.html) of display_config.ron and try to run a game it ends up with ```[ERROR][amethyst_config] Failed to load config file '...resources/display_config.ron': 6:17: Expected option```

## Reproduction Steps

1. Use the [tutorial](https://github.com/amethyst/amethyst/blob/4800ac5a79ea15b9cfe731d9aab18f0f2a7c3a10/amethyst_window/src/config.rs)
2. cargo run
3. See error

## What You Expected to Happen

Documentation is built on time and use automation to prevent such cases.

## What Actually Happened

Implementation was changed without documentation (and tutorials) update.

## Screenshots and Logs

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 1.65s
     Running `target\debug\pong.exe`
[ERROR][amethyst_config] Failed to load config file '...\resources/display_config.ron': 6:17: Expected option
[INFO][winit::platform::platform::window] Guessed window DPI factor: 1
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.10.0
[INFO][amethyst::app] Platform: x86_64-pc-windows-msvc
[INFO][amethyst::app] Amethyst git commit: 85365d5543b9be0daa891706c5d46c80ee38f9ca
[INFO][amethyst::app] Rustc version: 1.36.0-nightly Nightly
[INFO][amethyst::app] Rustc git commit: f492693982d1e252f5411ae3e4d560ab0dfea48a
thread 'main' panicked at 'Unable to load Vulkan entry points: LibraryLoadError("The specified module could not be found. (os error 126)")', src\libcore\result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: process didn't exit successfully: `target\debug\pong.exe` (exit code: 101)
```

## Your Environment

1. Windows
2. 10
3. 85365d5543b9be0daa891706c5d46c80ee38f9ca

**Comment by Frizi** [comment]
I believe you have visited the online docs before those were rebuilt after merge. Currently display config is [here in amethyst_window crate](https://docs-src.amethyst.rs/master/amethyst_window/struct.DisplayConfig.html).

Additionaly, you are right that not all documentation is updated yet for recent renderer changes, but it will be before official release.

**Comment by torkleyy** [comment]
Should be up to date now.
