### ISSUE TITLE
[BUG] Incomplete docs in Pong guide docs

### ISSUE THREAD

**Issue by icefoxen** [amethyst/amethyst#1665]
## Description

Now I feel bad for not making a PR for this, but I don't have much time.  XD

In https://book.amethyst.rs/stable/pong-tutorial/pong-tutorial-01.html , it says:

```
We'll be implementing the SimpleState trait on this struct, which is used by Amethyst's 
state machine to start, stop, and update the game. But for now we'll just implement 
two methods:

impl SimpleState for Pong {
}
```

So, it doesn't actually implement the methods it talks about.  ...actually I'm not even sure from context what it intends to do.

**Comment by torkleyy** [comment]
That sentence was out of date, it's fixed on master now.

**Comment by Frizi** [comment]
Closing as fixed
