### ISSUE TITLE
[FEATURE MODIFICATION] Improve function names meaning

### ISSUE THREAD

**Issue by AndreaCatania** [amethyst/amethyst#1667]
I think that the game engine code would be more organized if we add more meaning to the function naming.

For example the TransformComponent struct has a lot of of functions like the following one: `translation()` as you can see is not exactly clear what this function is for and you have to open the implementation file to know what it does.

Even worst when you don't know the _TransformComponent_ and you need to read the translation, and so you don't know the correct function to use.
How can you find the correct function in the 901 rows of code?

One solution is the "_Find in file_" functionality but the problem is that when the code don't follow a naming pattern this solution is not so effective.

A solution to this problem is to add the **get_**, **set_**, **push_**, **append_**, **prepend_**, (etc..) prefix to all functions that are supposed to do that actions.

Returning to the first example we would have: 

> get_translation()

and now it is really clear what it does, and also is easy to find by searching through all **get_** functions.

**Comment by Patryk27** [comment]
Rust's convention is that getters are named without the `get` word (https://doc.rust-lang.org/1.0.0/style/style/naming/README.html - RFC 344), so `translation()` as it is seems good IMO.

**Comment by AndreaCatania** [comment]
This is good when you have a simple structure like:

> struct test{
>     a: f32
>     b: f32
> }

because you know that the parameters are there, and is easy to understand what and how to read.


Instead the transform struct is:

> pub struct Transform {
>     /// Translation + rotation value
>     #[get = "pub"]
>     #[set = "pub"]
>     #[get_mut = "pub"]
>     isometry: Isometry3<Float>,
>     /// Scale vector
>     #[get = "pub"]
>     #[get_mut = "pub"]
>     scale: Vector3<Float>,
>     /// The global transformation matrix.
>     #[get = "pub"]
>     pub(crate) global_matrix: Matrix4<Float>,
> }

And understand how to read the position is not immeditealy clear to me

**Comment by jojolepro** [comment]
The position getter is non generated from those macros. It is manually implemented using the rust naming standard. You can use the documentation to find the methods you want faster than by reading the source.
https://docs.amethyst.rs/master/amethyst_core/transform/components/struct.Transform.html#method.translation

**Comment by bamling** [comment]
I think sticking to the Rust standard is the right approach as Amethyst is a **Rust** game engine. As far as I know most crates/libraries try to stick to the standard, especially the ones used by Amethyst, so just for consistency we should stick to the standard. So just for consistency across the engine as a *whole* it should stay this way. I feel like it's mostly a *getting used to* kinda thing... it certainly was for me. :sweat_smile:

**Comment by Frizi** [comment]
We use rust convention and this isn't really up for discussion at this point. Feel free to report inconsistencies that doesn't conform to that convention. As provided example is not that, I'm going to close this.
