### ISSUE TITLE
[BUG] Need to explicitly set clang++ flag to compile metal backend

### ISSUE THREAD

**Issue by chrisburnor** [amethyst/amethyst#1669]
## Description

On MacOS 10.14.5 (Mojave), the `c++` command is symlinked to `clang++` but the `cc` package doesn't follow the symlink to use the correct compiler. Since it falls back to gnu, it isn't able to compile the `metal` backend for gfx.

The issue can be mitigated by prepending `CXX=which $(clang++)` to the `cargo run` command.

See https://github.com/gfx-rs/gfx/issues/2520 for full details.

## Reproduction Steps

1. Using MacOS 10.14.5+
2. Make sure `c++` command symlinked to `clang++`:
```
% ls -la $(which c++)
lrwxr-xr-x  1 root  wheel  7 Jan 12 12:56 /usr/bin/c++ -> clang++
```
3. Make sure on rendy branch
4. Run `cargo clean`
5. Run `% cargo run --features metal --example sphere`
6. See error:
```
error: failed to run custom build command for `spirv_cross v0.12.0`
```

## What You Expected to Happen

Expected symlink to be followed and correct version of compiler used.

Expect 
## What Actually Happened

Fallback to gnu compiler.

## Your Environment

1. Operating System: OSX Mojave
2. Operating System Version: 10.14.5
3. Version of Amethyst: master, sha da510c1db23c7c2b40d645c9fbb5c9b12d824bd5 (2019-05-30)

## Additional Context
See https://github.com/gfx-rs/gfx/issues/2520 and https://github.com/alexcrichton/cc-rs/issues/408

**Comment by jojolepro** [comment]
Is this still an issue?
