### ISSUE TITLE
[FEATURE MODIFICATION] Use type float

### ISSUE THREAD

**Issue by AndreaCatania** [amethyst/amethyst#1671]
Actually I noticed that internally the TransformComponent is using the struct Float that wrap the FloatBase type alias.

Even if use a wrapper is free, the code get more fragmented because you have to unwrap it to use it.

Also if you do let `f = f.as_f32();` but internally the FloatBase is using **f64** you are loosing precision and you don't know it.

Also in all other parts except for the Transform we have the type **f32** directly hard coded in the engine so compile it with float f64 doesn't improve the precision to everything in the engine.

Instead if we have an alias that is used across the engine that mask the float precision, you never lose the precision, and you don't need to perform wrap / unwrapping of the value (that make each operation a pain) and change the type at compile time is more effective.

For example: 
```
 let mut position = Vector2::new(position.x.as_f32(), position.y.as_f32());

 [Bla Bla]

 transf.set_translation(
    Vector3::new(
        Float::from(position.x),
        Float::from(position.y),
        Float::from(0.0)
    ));
```

Rather something more simple like: 

```
 let mut position = Vector2::new(position.x, position.y);

 [Bla Bla]

 transf.set_translation(
    Vector3::new(
        position.x,
        position.y,
        0.0
    ));
```

In the second case is possible to directly copy the data without writing the unwrap code, and the type is not lost.

So I think that we should have a type alias Float that must be used across all engines parts, so for example compile the engine with double precision improve the precision of everything, and the dev don't need to put extra effort when he encounter a Float.

**Comment by jojolepro** [comment]
This was already proposed and does not work for multiple reasons. Sorry ^^

**Comment by AndreaCatania** [comment]
I suspected it, do you have the issue or the post link where you discussed
it?

I would like to understand why it doesn't work.

**Comment by jojolepro** [comment]
Most of the discussion had happened on discord in private messages. It was over an hour long.
The short version is that feature gates had to be tested separately and have no compile time check that can check both at once. The solution using generics worked but required propagating a generic everywhere, which was very inconvenient. We ended up using the Float type because it did what the generic version was doing without the need to propagate it. Implicit conversions between type are unavoidable and happened in all proposed solutions.  As for any code using the Float type, we suggest avoiding to convert the Float into a concrete type and then back into Float. The type as all the methods you need to manipulate it.

**Comment by AndreaCatania** [comment]
I was talking about using type aliasing.

The same that we have for FloatBase: https://github.com/amethyst/amethyst/blob/master/amethyst_core/src/float.rs#L21

In order to have something like:
   ```
    #[cfg(feature = "float64")]
    type Float = f64;
    #[cfg(not(feature = "float64"))]
    type Float = f32;

    #[test]
    fn check_float() {
        let a: Float = 2.0;
        let b: Float = 5.0;
        let c: Float = 10.0;
        assert_eq!(a * b, c);
    }
```

By using this ^ you can easily use the Float in all part of the engine, without any problem.

If this is what you mean that you had problems with, still not exactly clear to me why it make problems. But this is unfortunate.

**Comment by jojolepro** [comment]
Yes this is what I meant. You cannot check that both variants are correct at compile time without compiling two times. There was also a bunch of conversion issues, making it error prone and impractical.
