### ISSUE TITLE
[BUG] A couple of extra dependencies needed for Pong tutorial on Ubuntu

### ISSUE THREAD

**Issue by biot023** [amethyst/amethyst#1680]
## Reproduction Steps

1. Create new project with amethyst CLI
2. Type `cargo run`
3. See error about linker missing dependencies

## What You Expected to Happen

It to build and run

## What Actually Happened

A massive linker error that boiled down to my system needed to install `libxcb-shape0-dev` and `libxcb-xfixes0-dev`

## Screenshots and Logs

If applicable, add screenshots to help explain your problem. Any relevant logs would be helpful as well.

## Your Environment

1. Ubuntu
2. 18.04.2 LTS (Bionic)
3. Version of Amethyst: 0.10.0 (CLI version 0.7.6)

## Additional Context
Running `sudo apt install libxcb-shape0-dev libxcb-xfixes0-dev` fixed it.

**Comment by torkleyy** [comment]
This should already be installed by following the instructions on our README; it's included in `libxcb-composite0-dev`: 

https://packages.debian.org/sid/libxcb-composite0-dev
