### ISSUE TITLE
[BUG] Pong example fails to run with "metal" feature

### ISSUE THREAD

**Issue by jstnlef** [amethyst/amethyst#1682]
## Description
Running `cargo run --features metal --example pong` panics.

## Reproduction Steps
1. Run `cargo run --features metal --example pong` on a Mac

## What You Expected to Happen
I expected to see a playable pong game.

## What Actually Happened
The example panicked with the following error.
```
thread '<unnamed>' panicked at 'Failed to create glyph texture: ErrorMessage { msg: "Format R8Srgb is not supported and no suitable conversion found." }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

## Your Environment
1. MacOS Mojave 10.14.5
2. Amethyst master branch

**Comment by torkleyy** [comment]
Probably a duplicate of https://github.com/amethyst/amethyst/issues/1663

**Comment by jstnlef** [comment]
Closed as duplicate
