### ISSUE TITLE
UI text in pong_tutorial_05 doesn't get rendererd properly

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#1686]
## Description

When starting the game, both scores are simply white rectangles.

![Screenshot from 2019-06-10 17-40-49](https://user-images.githubusercontent.com/23152057/59207433-57c77700-8ba7-11e9-82f1-0f7eaee9b4f2.png)

Once the score changes to `1`, it works as usual:

![Screenshot from 2019-06-10 17-41-24](https://user-images.githubusercontent.com/23152057/59207452-644bcf80-8ba7-11e9-8005-5137dc5ea7bf.png)

However, once it would change to `2` it becomes a white rectangle again.

## Reproduction Steps

1. Clone this repo
2. `cargo run --example pong_tutorial_05 --features "vulkan"`

## What You Expected to Happen

A few more working glyphs.

## What Actually Happened

Only `1` could be rendered.

## Screenshots and Logs

Logs: [logs.txt](https://github.com/amethyst/amethyst/files/3272778/logs.txt)

## Your Environment

1. Operating System: Fedora, 5.0.19-200.fc29.x86_64
2. Version of Amethyst: `master`

## Additional Context

* the `pong` example shows the same behavior

**Comment by azriel91** [comment]
Renders okay on Windows.

**Comment by jojolepro** [comment]
You might need to run it twice to see the bug happening. The first time I run it, it will render properly, but not the second.

**Comment by Frizi** [comment]
For me the text is usually either OK or totally missing, but i think those are connected.

**Comment by torkleyy** [comment]
@jojolepro @Frizi which driver are you using?

**Comment by Frizi** [comment]
GPU: NVIDIA GeForce GTX 1070 Ti
Driver: 11.12.2018

I already know that when it's not rendering, renderdoc see no draws at all, so it must be purely a glyph rendering bug.
