### ISSUE TITLE
Could not find `gfx_device` in `amethyst`

### ISSUE THREAD

**Issue by agmcleod** [amethyst/amethyst#170]
Hi there,

I'm trying out the window example, but I get a compile error when trying to pull in gfx_device. Given the examples run under the project cargo, I'm wondering if I need to include gfx_device separately? Or is there something else that I am missing?

```
extern crate amethyst;

use amethyst::engine::{Application, Duration, State, Trans};
use amethyst::gfx_device::DisplayConfig;

struct HelloWorld;

impl State for HelloWorld {
    fn on_start(&mut self) {
        println!("Game started!");
    }

    fn update(&mut self, _delta: Duration) -> Trans {
        println!("Hello from Amethyst!");
        Trans::Quit
    }

    fn on_stop(&mut self) {
        println!("Game stopped!");
    }
}

fn main() {
    let path = String::from("resources/config.yml");
    let display_config = DisplayConfig::from_file(path).unwrap();
    let mut game = Application::build(HelloWorld, display_config).done();
    game.run();
}

```

**Comment by nchashch** [comment]
It looks like you are not running the `develop` branch version of `amethyst`. crates.io version (0.3.1) is outdated. So currently the best way to run the examples would be to either clone this repo and checkout the develop branch or to pull in amethyst in `Cargo.toml` like this:
```toml
[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", branch = "develop" }
```
Currently there are plans to publish a new 0.4.0 release (see #158) which would allow using crates.io version.

**Comment by agmcleod** [comment]
@nchashch awesome, thanks for your help!
