### ISSUE TITLE
[MAINTENANCE] Add rendy basic custom shader example

### ISSUE THREAD

**Issue by jaynus** [amethyst/amethyst#1702]
## Description

We currently have no example for creating a custom RenderPass using your own shader. I think with the flexability we gained from rendy, this would be a good basic example for getting into the internals of the renderer and writing custom passes.

This should consist of something akin to https://vulkan-tutorial.com/Drawing_a_triangle where we simply supply a shader which takes a vertex buffer and index buffer, and draws a triangle. 

## Additional Information
Example pass:
https://github.com/jaynus/amethyst-imgui/blob/master/src/pass.rs

**Comment by Frizi** [comment]
I would prefer to leave that for 0.12, when we will have economics figured out a bit better. This is likely to change very dramatically.
