### ISSUE TITLE
[BUG] Code coverage reports are unreliable

### ISSUE THREAD

**Issue by Frizi** [amethyst/amethyst#1711]
I've noticed that code coverage is very inaccurate in many cases. As we are planning to rely on that coverage always going up, we have to make sure that it's reliable. https://github.com/amethyst/amethyst/pull/1704 is a good example where it's obviously incorrect.

I did some digging, suspecting that maybe codecov is doing something stupid (like selecting wrong base commits), but this seems all right. Instead, the coverage reports generated by our builds seems to be wrong. Codecov allows downloading raw coverages used for comparison, so i did that for https://github.com/amethyst/amethyst/pull/1704

The reports are quite different. Both versions and their somewhat unreadable diff is here: http://www.mergely.com/FUf75Qz8/

Interesting to notice is that those reports actually have different data, for example for "types.rs" file, and this is exactly what reports says. Obviously the PR itself doesn't contain any changes that could influence this file's coverage.
```
master:
    {"file": "/home/jenkins/workspace/amethyst_PR-1704@2/amethyst_rendy/src/types.rs", "percent_covered": "50.00", "covered_lines": "3", "total_lines": "6"},
that PR tip:
    {"file": "/home/jenkins/workspace/amethyst_master@2/amethyst_rendy/src/types.rs", "percent_covered": "40.00", "covered_lines": "2", "total_lines": "5"},
```
There's also per-line reports further down, and it's also different.

The cause of those discrepancies is unknown to me right now, needs further investigation.

**Comment by torkleyy** [comment]
Yeah, this is definitely very annoying. Maybe we can find an alternative to `kcov`? Last time I checked though, it seemed to be the best option for Rust.

**Comment by azriel91** [comment]
This script (needs adjustments) made coverage stable in my project:

https://gist.github.com/azriel91/a274d3023c9fba41552fdc1905ee838c

It:

1. Calls cargo to find out which test binaries belong to which crate.
2. Executes those bianries, saving coverage to each crate's own separate dir.
3. Merges all the coverage at the end.

**Comment by Frizi** [comment]
@azriel91 would you be able to try integrating that to amethyst?

**Comment by azriel91** [comment]
🔖 yeaps!
