### ISSUE TITLE
[BUG] Panics if the clear color used in the rendergraph is not also used in subpasses

### ISSUE THREAD

**Issue by AndreaCatania** [amethyst/amethyst#1715]
## Description
[BUG] Panics if the clear color used in the rendergraph is not also used in subpasses

## Reproduction Steps

1. Clone this https://github.com/AndreaCatania/amt_tests
2. Go here https://github.com/AndreaCatania/amt_tests/blob/master/cubes/src/render_graph.rs#L97 and change the color_image with a new one that is not used by any other subpasses
2. Execute "cargo run" inside the cube directory

## What You Expected to Happen

The new color should be used to clear the screen

## What Actually Happened

Panics

## Your Environment

1. Ubuntu 18.04
3. Master #2af04654d0b9929b31bcd860e53f133708fb3dc0

**Comment by jojolepro** [comment]
delet stale

**Comment by AndreaCatania** [comment]
not stale

**Comment by AlveLarsson** [comment]
Hello, this issue has been marked stale or inactive.
We are currently going to go through major rewrites, please re-evaluate if this issue when 0.16 has been released. Closing this, for now, Thanks for your interest!
