### ISSUE TITLE
[BUG] Book 4.2 Drawing the Paddles has a missing import

### ISSUE THREAD

**Issue by itmuckel** [amethyst/amethyst#1716]
## Description

(Using amethyst 0.10 and the "stable" book)
In the chapter "Drawing the Paddles" the imports in the section "A quick refactor" are incomplete.

## Reproduction Steps

1. Follow the tutorial.

## What You Expected to Happen

The last section compiles.

## What Actually Happened

I get the compiler error:

```
error[E0433]: failed to resolve: use of undeclared type or module `Flipped`
  --> src\pong.rs:95:15
   |
95 |         .with(Flipped::Horizontal)
   |               ^^^^^^^ use of undeclared type or module `Flipped`

error: aborting due to previous error
```

Looking at the code in the examples directory, I see it was a missing import (`amethyst::renderer::Flipped`). So chapter 4.2 should have this at the top:

```
use amethyst::assets::{AssetStorage, Loader};
use amethyst::core::transform::Transform;
use amethyst::ecs::prelude::{Component, DenseVecStorage};
use amethyst::prelude::*;
use amethyst::renderer::{
    Camera, Flipped, PngFormat, Projection, SpriteRender, SpriteSheet,
    SpriteSheetFormat, SpriteSheetHandle, Texture, TextureMetadata,
};
```

Also it could use the Rust 2018 nested imports:

```
use amethyst::{
    assets::{AssetStorage, Loader},
    core::transform::Transform,
    ecs::prelude::{Component, DenseVecStorage},
    prelude::*,
    renderer::{
        Camera, Flipped, PngFormat, Projection, SpriteRender, SpriteSheet,
        SpriteSheetFormat, SpriteSheetHandle, Texture, TextureMetadata,
    },
};
```

**Comment by itmuckel** [comment]
Okay, that's weird. I checked out `origin/v0.10` and there the import was fine. Maybe the book needs to be regenerated?

**Comment by distransient** [comment]
This should be fixed.
