### ISSUE TITLE
[MAINTENANCE] Use rust-toolchain to specify a rustc version

### ISSUE THREAD

**Issue by ts25504** [amethyst/amethyst#1726]
## Reason

The README said: "Amethyst supports only the latest stable release of Rust. Use the nightly and beta channels with this project at your own risk." 

## Description

Maybe we can add a rust-toolchain file to avoid these risks. https://github.com/rust-lang/rustup.rs#the-toolchain-file

**Comment by LucioFranco** [comment]
@ts25504 I don't think we really need this mostly because the default should always be `stable` and `nightly` and `beta` are backwards compat. This file is mostly useful for projects that have to live on nightly because they are using a feature that isnt available on stable.

**Comment by distransient** [comment]
I know quite a number of people who use Amethyst with nightly, usually with success. It also helps us quickly find errors in advance when they do so. It's not necessarily an error to use Amethyst with nightly, it just might break sometimes.
