### ISSUE TITLE
[BUG] Segmentation fault when running the Pong example.

### ISSUE THREAD

**Issue by patrick-o-harrison** [amethyst/amethyst#1734]
## Description

When running the code provided in section 4.1 of the book (the pong game), the application produces a segmentation fault.

## Reproduction Steps

1. Copy the code from section 4.1 of the book into main.rs
2. Build the code (using cargo build)
3. Run the program (using cargo run, or directly by running target/debug/appname)

## What You Expected to Happen

A blank window would open.

## What Actually Happened

The application produces a segmentation fault.

## Screenshots and Logs

[Output and gdb backtrace](https://gist.github.com/patrick-o-harrison/e37f6410032c2c517e48e29ba6f4c7a0)

## Your Environment

Arch Linux (5.1.11)
Amethyst 0.11.0

**Comment by distransient** [comment]
Could very well be a clone of #1634

**Comment by termhn** [comment]
This is actually an issue with the Vulkan validation layers, as the panic originates in them. Myself and @jaynus also had this issue. Downgrading one version to .106 solves the issue. I submitted a bug on the Vulkan validation layers repo for this just here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1011
