### ISSUE TITLE
[BUG] window freezes on some computer screens

### ISSUE THREAD

**Issue by lcnr** [amethyst/amethyst#1736]
## Description

On my desktop screens the window only gets updated during a window resize(everything works as expected when opened directly on my laptop screen). The cause for the freeze seems to be https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkDestroySwapchainKHR.html This leads me to believe that we may use a swapchain while destroying it :thinking:

## Reproduction Steps

1. `cargo run --example pong --features vulkan` where the window opens on a desktop screen and not on my build in laptop screen.

## What You Expected to Happen

A working window no matter where on my screen the window is positioned.

## What Actually Happened

The window is not updated and events are not received until I resize the window. During resize everything works as expected.

## Screenshots and Logs

If applicable, add screenshots to help explain your problem. Any relevant logs would be helpful as well.

## Your Environment

>Operating System
   NAME="Ubuntu"
   VERSION="18.04.2 LTS (Bionic Beaver)"
   ID=ubuntu
   ID_LIKE=debian
   PRETTY_NAME="Ubuntu 18.04.2 LTS"
   VERSION_ID="18.04"
   HOME_URL="https://www.ubuntu.com/"
   SUPPORT_URL="https://help.ubuntu.com/"
   BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
   PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
   VERSION_CODENAME=bionic
   UBUNTU_CODENAME=bionic

Version of Amethyst 0.11.0

Additional Context

gpu:

    description: VGA compatible controller
    product: HD Graphics 620
    vendor: Intel Corporation
    physical id: 2
    bus info: pci@0000:00:02.0
    version: 02
    width: 64 bits
    clock: 33MHz
    capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
    configuration: driver=i915 latency=0
    resources: irq:132 memory:b0000000-b0ffffff memory:a0000000-afffffff ioport:4000(size=64) memory:c0000-dffff

This is the weirdest bug I have ever seen. I might try and fix this myself, as I doubt that it is easily reproducible. Who is the best person to ask if I have any question about amethyst renderer?

[thread_profile.json.txt](https://github.com/amethyst/amethyst/files/3306634/thread_profile.json.txt)

**Comment by jaynus** [comment]
@Frizi  @termhn @omni-viral This sounds like it might be some sort of disparity on when a render graph gets rebuilt vs. what device its actively using?

**Comment by omni-viral** [comment]
Could it be that you have desktop monitor connected to another physical device than built-in display?

**Comment by lcnr** [comment]
@omni-viral I sadly don't fully understand your question. An image of my setup:
![setup](https://user-images.githubusercontent.com/29864074/59830391-d35fbb80-933f-11e9-96d3-6383a5f98d16.png)

**Comment by lcnr** [comment]
The first freeze is during https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/vkAcquireNextImageKHR.html

Callstack:
> futex_reltimed_wait_cancelable (@7ffff5ce7c50..7ffff5ce8233:158)
__pthread_cond_wait_common (@7ffff5ce7c50..7ffff5ce8233:150)
__pthread_cond_timedwait (@7ffff5ce7c50..7ffff5ce8233:111)
___lldb_unnamed_symbol2416$$libvulkan_intel.so (@7ffff2089c00..7ffff2089ff0:108)
___lldb_unnamed_symbol579$$libvulkan_intel.so (@7ffff1f28710..7ffff1f28760:14)
___lldb_unnamed_symbol580$$libvulkan_intel.so (@7ffff1f28760..7ffff1f287f0:25)
___lldb_unnamed_symbol1546$$libVkLayer_unique_objects.so (@7fffdbaa6b40..7fffdbaa6c50:51)
___lldb_unnamed_symbol1789$$libVkLayer_core_validation.so (@7fffdb3cc480..7fffdb3ccc80:223)
___lldb_unnamed_symbol249$$libVkLayer_parameter_validation.so (@7fffdabe4340..7fffdabe46d0:102)
___lldb_unnamed_symbol203$$libVkLayer_threading.so (@7fffda9315d0..7fffda931740:34)
acquire_next_image_khr (/home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.29.0/src/vk.rs:44935)
acquire_next_image (/home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.29.0/src/extensions/khr/swapchain.rs:54)
acquire_image (/home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.2.2/src/window.rs:474)
next_image<gfx_backend_vulkan::Backend> (/home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/rendy-wsi-0.3.0/src/lib.rs:483)
run<gfx_backend_vulkan::Backend,shred::res::Resources> (/home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/rendy-graph-0.3.1/src/node/present.rs:456)
run<gfx_backend_vulkan::Backend,shred::res::Resources> (/home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/rendy-graph-0.3.1/src/graph/mod.rs:180)
run_graph<gfx_backend_vulkan::Backend,sphere::ExampleGraph> (/home/programming/amethyst/amethyst_rendy/src/system.rs:209)
run_now<gfx_backend_vulkan::Backend,sphere::ExampleGraph> (/home/programming/amethyst/amethyst_rendy/src/system.rs:228)
dispatch_thread_local (/home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.7.2/src/dispatch/dispatcher.rs:111)
dispatch (/home/programming/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.7.2/src/dispatch/dispatcher.rs:68)

**Comment by lcnr** [comment]
This can be fixed by setting the PresentNode.present_mode to PresentMode::Immediate...
Will try to find a more indepth reason

**Comment by termhn** [comment]
Seems like this might be a Vulkan driver bug or maybe a bug with your
window manager/DE or something. Changing present mode shouldn’t have that
effect

**Comment by ishitatsuyuki** [comment]
I think we need more info on this, have you tried again with the latest drivers?

**Comment by lcnr** [comment]
> I think we need more info on this, have you tried again with the latest drivers?

yes, tried once more with the same result. afaik I currently still use the same driver.
