### ISSUE TITLE
[BUG] Book "Display the Texture" page uses no longer supported method

### ISSUE THREAD

**Issue by Havvy** [amethyst/amethyst#1740]
## Description

The links for https://book.amethyst.rs/stable/sprites/display_the_texture.html that point to the renderer subcrate 404 because they link to v0.10 types and not v0.11 types.

Relatedly, I'm also not getting an image to show like this when I got it to show using v0.10. I also tried looking for passes that looked for `Handle<Texture>`s, and could't find any. So I'm wondering if this entire chapter is false in v0.11.

**Comment by distransient** [comment]
@termhn on discord:

> Fusha/termhn (she/they) Today at 4:12 AM
> This style of rendering is no longer supported, it was decided that it's not worth the effort to support in the hacked way that it was before
> instead you should just use the SpriteSheet method
> it's a much better way to do things and only has a small upfront effort cost
> in the future improvements to the asset pipeline will make this more convenient

Book page should probably just be removed.

**Comment by jojolepro** [comment]
not stale
