### ISSUE TITLE
[ATELIER-ASSETS] Merge new assets loader as experimental module

### ISSUE THREAD

**Issue by Frizi** [amethyst/amethyst#1741]
Currently developed new assets loader is developed on a fork, which makes cooperative work noticeable harder. It should be merged to current master as an experimental module (under an "experimental" feature flag) so other dependant work can start using that code before we have all parts finished.

Change should remain backward-compatible, old asset system should remain default until the code is ready and tested.

**Comment by jojolepro** [comment]
Do we have an idea of a time frame/estimate for when we can expect this addition?

**Comment by kabergstrom** [comment]
It could probably be merged as an experimental at this point. The main missing feature is Prefabs right now, I believe.
