### ISSUE TITLE
[ATELIER-ASSETS] Implement deserialization support for `Handle<T>` that maps to AssetUUID

### ISSUE THREAD

**Issue by Frizi** [amethyst/amethyst#1743]
Assets loaded as dependencies that are referenced by their UUIDs in meta files have to be transformed (deserialized) into handles in the engine runtime representation.

**Comment by jojolepro** [comment]
Not Stale

**Comment by kabergstrom** [comment]
Should be finished with merging of this PR https://github.com/amethyst/atelier-assets/pull/32

**Comment by distransient** [comment]
PR Merged.
