### ISSUE TITLE
[NEW FEATURE] Add proper support for high precision Transforms

### ISSUE THREAD

**Issue by Frizi** [amethyst/amethyst#1745]
As `Float` gets removed (#1744), we want to get back the features it provided back to the engine. This time in a form of specialized `Transform64` component and a set of systems that update `Transform` (which is used by rendering) using various techniques.

We might implement two systems:
- Part of this ticket: system that simply truncates f64 into f32 and applies to `Transform`
- Idea to explore: system that applies world-origin shift using a resource with `Vector<f64>` as origin point. That origin point can be shifted at any time which would trigger recalculation.

We also have to modify existing builtin systems that use `Transform` directly to accept both `Transform` and `Transform64` types. This might require a generic argument in the implementation, but in that case we should expose two type aliases with specific types filled in.

The most basic form allows us to carry out physics calculations in higher precision, while still allowing rendering to run use lower precision data.

We also have to properly document the fact that while using `Transform64`, the `Transform` component should effectively be treated as read-only, as any updates done on it directly will be discarded. Users should operate on `Transform64` instead.

**Comment by Max-Rensen** [comment]
I might be able to take a stab at this soon, after I look into it some more.

It seems strange to have both a `Transform64` and a `Transform` (when using `Transform64`) for each entity though, but I guess that's necessary for the rendering.

**Comment by Frizi** [comment]
not stale
