### ISSUE TITLE
[FEATURE REGRESSION] Can't (easily?) animate Material anymore

### ISSUE THREAD

**Issue by JadeSnail** [amethyst/amethyst#1755]
It used to be possible to use the AnimationBundle to animate Material, but since Material isn't a Component anymore, it doesn't seem to be possible anymore.

Indeed, the SytemBundle impl of AnimationBundle requires a type parameter T: AnimationSampling + Component, but Material isn't a Component, and Handle<Material> isn't AnimationSampling.

You can't just manually unpack the bundle either, since both the AnimationControlSystem and the SamplerInterpolationSystem also require T: AnimationSampling + Component.

**Comment by Frizi** [comment]
Right. It seems like i've missed refactoring the impls on `impl AnimationSampling for Material` and `impl<'a> ApplyData<'a> for Material`. Both should now be implemented on `Handle<Material>`. With that you won't be able to change individual textures anymore, but swapping out the whole material will still be possible.
