### ISSUE TITLE
[FEATURE MODIFICATION] Allow for custom anchor points

### ISSUE THREAD

**Issue by lcnr** [amethyst/amethyst#1757]
## Feature

2D sprite rendering

## Change

Allow the user to specified a anchor point instead of always having it in the middle of the sprite.
This could be done by adding a field `anchor: Anchor` to SpriteRender.

```rust
pub enum Anchor {
    Center,
    Custom {
       x: f32,
       y: f32
    },
    TopLeft,
    TopMiddle,
    TopRight,
    ...
}
```

## Reason

Currently all sprites are drawn with the transform of the entity in its center.
This can cause things such as collision detection and animations to be less ergonomic, especially when using differently sized sprites.

## Impact

The `Anchor` enum would probably also need to be used during collision detection to effectively lineup colliders with sprites.

## Additional Notes

-

**Comment by Frizi** [comment]
This feature is already supported, although in a different way. You can control that per-sprite, not per-entity. Just use "offsets" field on the `Sprite` definition in your sprite sheet.
