### ISSUE TITLE
Better docs for components supported by render passes

### ISSUE THREAD

**Issue by ohnoimdead** [amethyst/amethyst#1759]
There is currently no documentation for which built-in components are supported by render passes, and how to use them. For example, Tint can be used in 3d passes to tint vertexes, or in 2d passes to multiply a sprite's color by a tint.

@torkleyy suggests adding comments to the specific render pass struct (https://github.com/amethyst/amethyst/pull/1756). I opened a separate ticket since this applies to more than just the Tint component.

**Comment by distransient** [comment]
Not stale.
