### ISSUE TITLE
[BUG] Incorrect PBR Shading

### ISSUE THREAD

**Issue by TimBednarzyk** [amethyst/amethyst#1764]
## Description

When using `amethyst::renderer::pass::DrawPbrDesc`, objects are not lit properly when compared to `amethyst::renderer::pass::DrawShadedDesc`.

## Reproduction Steps / What You Expected to Happen / What Actually Happened

Run [this](https://pastebin.com/N9CkZcPw) code as-is.
There is a rotatable cube and an `amethyst::renderer::light::DirectionalLight` facing [0.0, -1.0, 0.0] so the top of the cube should always be lit regardless of its rotation.

Use WASDRF to move, and TYGHBN to rotate the cube.
You will see that the cube is not lit until you rotate it on the X or Z axes.
This is incorrect as the light source is pointing toward the top of the cube.

Comment out line 279 and uncomment 280 to switch to DrawShadedDesc and run again.
You will see that the top of the cube is always lit regardless of orientation.
This is correct and should be how it works with PBR shading.

## Screenshots and Logs

1. DrawPbrDesc - No rotation
![Pbr No Rotation](https://user-images.githubusercontent.com/8797125/60217605-28696900-983b-11e9-9aeb-a4bf01540a58.png)

2. DrawPbrDesc - Rotated 90° on the X axis
![Pbr Rotated X 90deg](https://user-images.githubusercontent.com/8797125/60217676-4636ce00-983b-11e9-92f5-1c2eae8c5886.png)

3. DrawShadedDesc - No rotation
![Shaded No Rotation](https://user-images.githubusercontent.com/8797125/60217697-4d5ddc00-983b-11e9-8681-df7804708712.png)

4. DrawShadedDesc - Rotated 90° on the X axis
![Shaded Rotated X 90deg](https://user-images.githubusercontent.com/8797125/60217723-5b136180-983b-11e9-8fd9-2b3a5eace68d.png)

## Your Environment

1. Operating System: Arch Linux
2. Operating System Version: 5.1.9-arch1-1-ARCH
3. Version of Amethyst: 0.11.1

**Comment by AndreaCatania** [comment]
I can confirm this bug even on my side.
I've tried with Directional light and Point light and the result are the following respectively:

![Screenshot from 2019-06-27 16-22-29](https://user-images.githubusercontent.com/8342599/60275006-6b8a1180-98f9-11e9-87f6-ac248c2b818d.png)
![Screenshot from 2019-06-27 16-33-35](https://user-images.githubusercontent.com/8342599/60275010-6e850200-98f9-11e9-95e9-933c60569138.png)

On my side rotate it a bit doesn't fix the problem.

**Comment by AndreaCatania** [comment]
Checking other shapes and seems that they works correctly.

![Screenshot from 2019-06-27 16-48-42](https://user-images.githubusercontent.com/8342599/60276198-75ad0f80-98fb-11e9-8067-058e6c3a8be8.png)

I think that the bug is not in the shader, but instead is in the cube generator.
Maybe the tangents are wrongly calculated?

**Comment by TimBednarzyk** [comment]
I don't think it's the cube generator.

In another program, I had hardcoded the position, texture, and normal coordinates and then used an algorithm to generate the tangent coordinates and I saw the same issue.

**Comment by AndreaCatania** [comment]
Oh, so is weird that doesn't happen on the cylinder

**Comment by Frizi** [comment]
might be linked to #1095. We haven't really changed the shader much since then.

**Comment by valkum** [comment]
I cannot reproduce this on Windows 10 1809, AMD R9 390 Driver version 19.6.1, Rust 1.34.1 and Vulkan (SDK 1.1.101.0)

To check whether this is a problem of drivers etc. I changed the example to have fixed positions and rotations to share comparable screenshots. The cubes fixed rotations are the keys 1 to 4. I hope the rotations still are valid for your issue.
The camera can not be moved to avoid a flipped camera (The FlyMovementBundle currently does not prevent this).
Here is my code (cargo builds two bins) https://gist.github.com/valkum/a3972e366ba8ac20f5c00e4ee23e398f

![no_bug_screenshot](https://user-images.githubusercontent.com/169155/60306901-87fe6c00-9942-11e9-8b01-86b90ac9e925.jpg)

**Comment by TimBednarzyk** [comment]
Interesting...
I ran your code and still had the same problem:
![Screenshot 2019-06-27T20:09:47](https://user-images.githubusercontent.com/8797125/60308576-7ce21680-9917-11e9-88f0-5c73c620933a.png)

**Comment by AndreaCatania** [comment]
I've the same problem and my setup is:
Ubuntu 18.04
GeForce GTX 970
Driver Version: 430.26

**Comment by TimBednarzyk** [comment]
To add more information, here's my graphics information:
GPU: AMD Radeon RX Vega 56
Drivers: mesa 19.1.1-1, vulkan-radeon 19.1.1-1

**Comment by jaynus** [comment]
I can confirm this reproduces on both my systems.

Ubuntu 18.04
Desktop: GeForce GTX 980 x 2
Laptop: GeForce GTX 1070 MaxQ
Both drivers: 415.27 (Beta, short lived)
Both Vulkan Layers: LunarG 1.106.1

**Comment by AndreaCatania** [comment]
Any news about this?

**Comment by Frizi** [comment]
It was a generator bug after all. Tangents for XY coplanar surfaces are just totally wrong.
