### ISSUE TITLE
[BUG] SpriteSheetFormat offsets is wrongly documented

### ISSUE THREAD

**Issue by lcnr** [amethyst/amethyst#1768]
## Description

The docs of SpriteSheetFormat describe sprite offsets as
` offsets: (0.0, 0.0), // This is optional and defaults to (0.0, 0.0)`,
while the actually needed format is `offsets: Some((0.0, 0.0))`
## Reproduction Steps

1. look at https://docs-src.amethyst.rs/master/amethyst_rendy/struct.SpriteSheetFormat.html
2. change the example file assets/texture/pong_spritesheet.ron by adding `offsets: (0.0, 0.0),` to line 10.
3. `cargo run --example pong --features vulkan
4. Error while loading the spritesheet

## Your Environment

Version of Amethyst 0.11

## Additional Context

As far I as understand, an offset of `None` is the same as an offset of `(0.0,  0.0)`, so I am in favor of keeping the current documentation and changing the implementation. I would like to implement this if it is desired.

**Comment by torkleyy** [comment]
Ah, I believe the example is simply missing a `#![enable(implicit_some)]`.

**Comment by Friz64** [comment]
This can be closed now.
