### ISSUE TITLE
[BUG] Memory leaks in examples

### ISSUE THREAD

**Issue by nolanderc** [amethyst/amethyst#1777]
## Description

I was following along the Pong tutorial in the book, but after I built the executable I noticed the memory usage steadily increasing by roughly 2MB/s. I tried running some of the examples (`pong`, `materials` and `ui`) in this repository and experienced the same issue.

## Reproduction Steps

1. `git clone https://github.com/amethyst/amethyst.git`
2. `cd amethyst`
3. `cargo run --example pong --features metal`
4. Measure memory usage (eg. using activity monitor)

## What You Expected to Happen

Memory usage to be pretty much constant during runtime.

## What Actually Happened

Memory usage was steadily increasing at a seemingly fixed rate (2-6 MB/s).

## Screenshots and Logs

Output from `amethyst::start_logger`:
```
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.11.1
[INFO][amethyst::app] Platform: x86_64-apple-darwin
[INFO][amethyst::app] Amethyst git commit: 7abfcfc46c73b0fdb6896cc90898aad80292669b
[INFO][amethyst::app] Rustc version: 1.35.0 Stable
[INFO][amethyst::app] Rustc git commit: 3c235d5600393dfe6c36eeed34042efad8d4f26e
[WARN][rendy_factory::factory] Slow safety checks are enabled! Disable them in production by enabling the 'no-slow-safety-checks' feature!
[INFO][rendy_util::wrap] Slow safety checks are enabled! You can disable them in production by enabling the 'no-slow-safety-checks' feature!
[INFO][gfx_backend_metal::device] Entry point EntryPoint { name: "main", execution_model: Vertex, work_group_size: WorkGroupSize { x: 0, y: 0, z: 0 } }
[INFO][gfx_backend_metal::device] Entry point EntryPoint { name: "main", execution_model: Fragment, work_group_size: WorkGroupSize { x: 0, y: 0, z: 0 } }
[INFO][gfx_backend_metal::device] Entry point EntryPoint { name: "main", execution_model: Vertex, work_group_size: WorkGroupSize { x: 0, y: 0, z: 0 } }
[INFO][gfx_backend_metal::device] Entry point EntryPoint { name: "main", execution_model: Fragment, work_group_size: WorkGroupSize { x: 0, y: 0, z: 0 } }
[INFO][gfx_backend_metal::window] build_swapchain SwapchainConfig { present_mode: Fifo, composite_alpha: OPAQUE, format: Bgra8Srgb, extent: Extent2D { width: 1000, height: 1000 }, image_count: 3, image_layers: 1, image_usage: TRANSFER_DST }
Score: |  1  |  0  |
Score: |  1  |  1  |
Score: |  1  |  2  |
...
Score: |  9  | 10  |
Score: | 10  | 10  |
[INFO][amethyst::app] Engine is shutting down
[INFO][gfx_backend_metal::window] dropping Swapchain
[INFO][gfx_backend_metal::window] dropping Frame
[INFO][gfx_backend_metal::window] dropping Frame
[INFO][gfx_backend_metal::window] dropping Frame
```

## Your Environment

1. Operating System: macOS
2. Operating System Version: 10.14.5
3. Version of Amethyst: 0.11.1

## Additional Context

**Comment by torkleyy** [comment]
Thanks for the report!
It seems very strange to me that hello_world has leaks - it doesn’t do anything, really. Not even opens a window.

**Comment by nolanderc** [comment]
Oh sorry, that's an error on my part. I have updated the issue.

I did some more testing, and the issue seems to only affect examples which render something: the example `window` has no memory leak.
