### ISSUE TITLE
[MAINTENANCE] Diagrams and images background within book/documentation

### ISSUE THREAD

**Issue by KSXGitHub** [amethyst/amethyst#1782]
## Description

Diagrams and images within Amethyst book/documentation should have ~black text on~ _white_ background (instead of transparent background).

## Reason

I read Amethyst book in dark theme (Ayu), and then I see a diagram that is almost unreadable due to having black text on transparent background.

![black text on transparent background on dark theme](https://user-images.githubusercontent.com/11488886/60715111-7fabbf80-9f46-11e9-9bc9-51dbe5ae6a24.png)

## Impact

None.

## Steps to reprocedure

1. Go to https://book.amethyst.rs/stable/concepts/entity_and_component.html#storages
2. Switch to dark theme (Ayu).
3. Scroll to the first diagram.

**Comment by jojolepro** [comment]
I'm not sure the text color needs to be changed, but the background should at least be made opaque white.

**Comment by KSXGitHub** [comment]
@jojolepro To clarify, I only said "black text on white background" to imply black text on dark theme being barely readable.

**Comment by jojolepro** [comment]
I had misread what you wrote, I read it as white on black background. My mistake!

**Comment by distransient** [comment]
It's just a PNG that needs a background added to its tiles it seems.

**Comment by OvermindDL1** [comment]
> It's just a PNG that needs a background added to its tiles it seems.

Oh please not a big white box in a dark theme...  ^.^;

What about using an actual table, or SVG that accepts CSS controls?

**Comment by distransient** [comment]
If it works, go for it!

**Comment by zicklag** [comment]
How is this?

![image](https://user-images.githubusercontent.com/25393315/62413814-0fda3480-b5d9-11e9-8eff-7c696e92d797.png)

It uses the Rust theme background color, which I think is the best middleground if you have to pick one.

**Comment by zicklag** [comment]
Here is an inline HTML version. Not sure if that is a detriment to readability of the markdown source, though:

![image](https://user-images.githubusercontent.com/25393315/62414225-cfc98080-b5dd-11e9-9a3a-76801cf53549.png)

![image](https://user-images.githubusercontent.com/25393315/62414230-e7a10480-b5dd-11e9-9562-b5c8f3d98da9.png)
