### ISSUE TITLE
[BUG] Setup in pausable systems

### ISSUE THREAD

**Issue by MegasKomnenos** [amethyst/amethyst#1783]
## Description

System's setup does not fire when the system is pausable.

## Reproduction Steps

1. Go to https://github.com/MegasKomnenos/The-Prince
2. Run and check that println!("Setup has been fired"); in move_camera.rs is not fired.
3. Remove .pausable(GameState::Running) in main.rs
4. Run and check that println!("Setup has been fired"); in move_camera.rs is fired.

## What You Expected to Happen

I expected the system's setup to fire.

## What Actually Happened

It did not fire.

## Screenshots and Logs

If applicable, add screenshots to help explain your problem. Any relevant logs would be helpful as well.

## Your Environment

1. Operating System: Windows 10
2. Operating System Version: 1803
3. Version of Amethyst: 0.11.1

## Additional Context
I think system's setup firing even when the system is pausable and matches the pause condition, or at least firing later when it first gets out of the pause condition is more preferable.

**Comment by jojolepro** [comment]
I'm currently removing all the system setup of the engine, because they are planned for removal in specs. Use a new(&mut world) method to create your system. :)
