### ISSUE TITLE
[MAINTENANCE] Update to winit 0.20.0

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#1786]
## Description

Since `gfx-hal` is updating -- https://github.com/gfx-rs/gfx/issues/2874 -- we should do this as well.

## Reason

Keep up to date with the ecosystem.

**Comment by OvermindDL1** [comment]
Not stale, `gfx` update in https://github.com/gfx-rs/gfx/pull/2888 a few days ago.

**Comment by distransient** [comment]
Will be fixed by #1877

**Comment by vultix** [comment]
@azriel91 @OvermindDL1 What's preventing this from being merged? Please correct me if I'm wrong, but as far as I can tell this is the only thing blocking OpenGL WASM support in #1877

**Comment by distransient** [comment]
Will be fixed sooner in #2040

**Comment by chemicstry** [comment]
Can we close this since it landed into wasm branch?

**Comment by azriel91** [comment]
Normally would keep it open until it lands on `master`, for the small chance another `amethyst` version may be published before the `wasm` one.

**Comment by ezpuzz** [comment]
fixed by #2554
