### ISSUE TITLE
[BUG] Impossible to restart an animation the frame it finish

### ISSUE THREAD

**Issue by Hugal31** [amethyst/amethyst#1789]
# Tasks
- Refactor AnimationControl API to ensure that it is eventually `ControlState::Done`.

## Description

A `AnimationCommand::Start` or `SetInputValue` will not be taken in account on the update cycle on which the animation ends.

## Reproduction Steps

In a system, try to issue a `AnimationCommand` as `Start` or `SetInputValue` when the concerned animation `ControlState` is `Done`.

You can also:
- apply [this patch file](https://github.com/amethyst/amethyst/files/3365792/restart_animation.txt) in the amethyst repo
- run the `animation` example
- press "C" to toggle restart of animation
- press "space" to start the animation

## What You Expected to Happen

The animation to restart when I ask to.

## What Actually Happened

The animation is not restarted at all.

If we look at the code at [this line in the AnimationControlSystem](https://github.com/amethyst/amethyst/blob/b610ebf6ce9e8da88519bb5225d14ed9842cfc16/amethyst_animation/src/systems/control.rs#L322): 
```rust
match (&control.state, &control.command) {
(_, &AnimationCommand::Abort) | (&ControlState::Abort, _) | (&ControlState::Done, _) => // remove the animation
(&ControlState::Requested, &AnimationCommand::Start) => // Start the animation
}
// ...
```

There is no case for `(ControlState::Running, AnimationCommand::Start)`, `(ControlState::Done, AnimationCommand::Start)`
before the `(ControlState::Done, _)`, which explain the bug.

**Comment by azriel91** [comment]
Hm, I *think* this should restart the animation:

```rust
let animation_control_set = get_animation_set(&mut animation_control_sets, entity)
    .expect("Expected animation set to exist.");
let animation_ended = {
    animation_control_set
        .animations
        .iter()
        .find(|&&(ref id, ref _control)| id == animation_id)
        .map_or(true, |(_id, control)| control.state == ControlState::Done)
};

animation_set.abort(animation_id);
animation_set.add_animation(
    animation_id,
    &animation_handle,
    EndControl::Normal,
    1., // Rate
    AnimationCommand::Start,
);
```

However, that doesn't mean we can't do better :slight_smile:.

Shall push that change you mentioned shortly.

**Comment by azriel91** [comment]
Hm, I tried implementing the change in `AnimationControlSystem`, but I can't seem to do it. Already spent a few hours so going to stop.

**Comment by Hugal31** [comment]
If I do this, I manage to use `set_input`. But I need to find if it is a reliable solution:
```diff
diff --git a/amethyst_animation/src/resources.rs b/amethyst_animation/src/resources.rs
index cbc54648..adf09ee6 100644
--- a/amethyst_animation/src/resources.rs
+++ b/amethyst_animation/src/resources.rs
@@ -469,9 +469,13 @@ where
             .iter_mut()
             .filter(|t| t.control_id == control_id)
             .for_each(|sampler| {
-                if let ControlState::Running(_) = sampler.state {
-                    sampler.state = ControlState::Running(dur);
-                }
+                let new_state = match &sampler.state {
+                    ControlState::Done
+                        | ControlState::Running(_) => ControlState::Running(dur),
+                    ControlState::Paused(_) => ControlState::Paused(dur),
+  
             });
     }
               
```

**Comment by Hugal31** [comment]
I think the problem is more complex than that and a fix would require a refactor of the entire `AnimationControl` API. For instance, the `ControlState` in `AnimationControl` is almost never updated, and printing it every frame does :
```
[INFO][animation] Anim state is Requested
[INFO][animation] Anim state is Running(0ns)
[INFO][animation] Anim state is Running(0ns)
[INFO][animation] Anim state is Running(0ns)
...
```
And `AnimationControl.state` is never `ControlState::Done`

Also, `AnimationControl.command` does not change either, and remains `AnimationCommand::Start` during all the animation.
Maybe we could use something like a `EventChannel` for commands.

Meanwhile, I managed to get the result I wanted by manually accessing the `SamplerControl`.

**Comment by JoshLambda** [comment]
I get the same problem when starting/pausing animation A, then starting/pausing animation B, then animation A cannot be started again. (Animations each have a different id in the same control set.)

Aborting/adding works as a workaround, with the difference that it rewinds animation every time. We lose animation position in its timeline, while I assume pausing would preserve it.

IMHO this is an important issue which breaks `start()` in `AnimationControlSet`. And the feature unavailability should probably be noted in the API doc, since it seems complex to solve and it's probably gonna be there for a while.
