### ISSUE TITLE
[BUG] The TransformSystem self modify the transforms

### ISSUE THREAD

**Issue by AndreaCatania** [amethyst/amethyst#1795]
Actually the TransformSystem fetch all the transformations with an event `insert` / `modify`.
And perform the update of the global transform on them.

https://github.com/amethyst/amethyst/blob/master/amethyst_core/src/transform/systems.rs#L76-L88

This operation write an event.
At the bottom of the `run` function this event get cleared only for the TransformSystem reader.

The problem starts when another system keep track of the transform events.

Since the TransformSystem doesn't clear the written events for everyone is tracking it what happens is this:
1. The OtherSystem perform the modification of the transform
2. The TransformSystem see the modification and update the global transform
3. The OtherSystem see the edit (which come wrongly from the TransformSystem) so it perform the edit on it.
4. The TransformSystem see the edit again ...
5. Over and Over again.

To stop this behavior I see two possible solutions.
- Separate the Transform with GlobalTransform.
- Add a method to clear the events to all readers.

**Comment by jojolepro** [comment]
> Separate the Transform with GlobalTransform.
no
> Add a method to clear the events to all readers.
maybe. @torkleyy ?

**Comment by AndreaCatania** [comment]
Thinking about it.
Add a way to disable events writing is much better because clear the events can mean delete useful information for some readers

**Comment by azriel91** [comment]
Not stale -- been worked on in other repositories.
