### ISSUE TITLE
[NEW FEATURE] Testable mock graphics backend

### ISSUE THREAD

**Issue by Frizi** [amethyst/amethyst#1812]
## Description

We need a HAL backend implementation for our test harness.

## What problem does this solve? What need does it fill?
Currently it's impossible to test any graphics-tied code on our CI or even locally in some situations. Current testing code uses real GPU and is limited by whatever your driver/hardware supports. Having a custom mock implementation with possibility to add per-test detailed setup how the emulated hardware capabilities looks like enables us to write tests to cover variety of cases for hardware configuration and driver support.

The biggest downside of that is that it won't help with "image output comparison" kind of tests. It doesn't prevent us from writing those though, we would just have to use real backends there and support that in our automation setup.

## How
There is an effort to make `empty` backend into a mock. It is a separate crate, so could be released more often than a hal itself. Our effort would likely be focused on expanding that in HAL directly (https://github.com/gfx-rs/gfx/pull/2764). We can create additional amethyst-specific wrapper around it for test harness, to make configuration more streamlined.

## Potential problems
Because of how backends are currently supported in rendy (i.e. by direct macros like `is_metal!`), some code paths are simply not possible to test with additional backend. This could be eliminated by feature detection or removal of any special cases on rendy level.

**Comment by azriel91** [comment]
cc: #2245
