### ISSUE TITLE
[NEW FEATURE] Shadow mapping support

### ISSUE THREAD

**Issue by Frizi** [amethyst/amethyst#1814]
## Description

Add a possibility to render shadows of key light in the scene.

## What problem does this solve? What need does it fill?
Amethyst currently lacks any capability of rendering dynamic shadows. This is an important step towards more realistic renders.

## Describe the solution you'd like

Implemenet cascaded shadow maps as a rendering pass and plugin. Take at least one directional light into account, possibly more if turns out to be easy. Render shadow maps in a separate rendering pass, then use it as a texture inside existing 3D render groups. All entities that cast shadows should be marked with `ShadowCaster` component.

The exact choice of shadow mapping technique needs further research. Ideally it would support transparency, but this is optional right now.

## Describe alternatives you've considered
Possible alternatives would be to implement ray-traced shadows, but this approach currently can't be widely supported. We would need a fallback method anyway.

**Comment by distransient** [comment]
Not stale.
