### ISSUE TITLE
[BUG] Current git version won't build

### ISSUE THREAD

**Issue by Type1J** [amethyst/amethyst#1819]
## Description

The current git master version of amethyst won't build due to a problem in the version of Rendy referenced. However, the latest git version of Rendy does seem to resolve some of the issue:
https://github.com/amethyst/rendy/commit/5354c8cdbd4ea435b3fe6b54a844a1a6d0901102#diff-4f06eacfefee15319d3a3e46d8b992efR464

## Reproduction Steps

1. `cargo run --example custom_ui --features "vulkan"`
2. See error

## What You Expected to Happen

Errorless build

## What Actually Happened

```
cargo run --example custom_ui --features "vulkan"
   Compiling amethyst_rendy v0.1.2 (D:\Projects\test-rust\amethyst\amethyst_rendy)
error[E0616]: field `not_found` of struct `rendy_mesh::mesh::Incompatible` is private
   --> amethyst_rendy\src\pass\base_3d.rs:636:37
    |
636 |                                     error.not_found.attributes,
    |                                     ^^^^^^^^^^^^^^^

error[E0616]: field `not_found` of struct `rendy_mesh::mesh::Incompatible` is private
   --> amethyst_rendy\src\pass\base_3d.rs:668:41
    |
668 |                                         error.not_found.attributes,
    |                                         ^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'copied' (see issue #57126)
   --> amethyst_rendy\src\bundle.rs:309:43
    |
309 |         self.target_metadata.get(&target).copied()
    |                                           ^^^^^^
    |
    = help: add #![feature(copied)] to the crate attributes to enable

error: aborting due to 3 previous errors

Some errors occurred: E0616, E0658.
For more information about an error, try `rustc --explain E0616`.
error: Could not compile `amethyst_rendy`.

To learn more, run the command again with --verbose.
```

## Your Environment

1. Operating System: Windows
2. Operating System Version: 10
3. Version of Amethyst: git master (as of 2019-07-24)

**Comment by Friz64** [comment]
The first two error messages appear because of an oversight in the `rendy` crate which still depends on an outdated version of `rendy-mesh` (0.3.0) instead of the correct version (0.3.1).

The third error is because your rust installation is outdated. To update use `rustup update`.

**Comment by omni-viral** [comment]
Simple `cargo update` will fix the first issue

**Comment by Type1J** [comment]
After `rustup update` and `cargo update`, it works. Thanks @Friz64 and @omni-viral !
