### ISSUE TITLE
[BUG] If AnimationBundle is not registered Loader will stuck

### ISSUE THREAD

**Issue by TatriX** [amethyst/amethyst#1827]
## Description

If one tries to load `AnimationSetPrefab` without registering `AnimationBundle` loader will spin forever.

## Reproduction Steps
[Example code](https://github.com/TatriX/bomberman-rs/commit/77688536dba4fe714c66013dca10faa41cfb2ed0)

## What You Expected to Happen

Some kind of error, maybe panic saying that nothing can handle stuff I'm using.

## What Actually Happened

Engines loops forever in loading state.

## Your Environment

1. Linux
2. Arch
3. 0.11

## Additional Context
@Dispersia said:
```
Its one of the problems with being modular
you could write your own loader, how would we know if something were to say it should know how to load the prefab
i agree, it shouldn't spin forever
maybe see if anything is registered before the progress_counter kicks it off to load if any resource is even registered to try and read it? That would probably work
```
Adding
```rust
.with_bundle(AnimationBundle::<AnimationId, SpriteRender>::new("sprite_animation_control", "sprite_animation_sampling"))?
```
solves the problem.

**Comment by azriel91** [comment]
Rudimentary loading taking forever detection:

```rust
use amethyst::core::StopWatch;
pub struct LoadingState { stopwatch: Stopwatch } // new { stopwatch: Stopwatch::new(), }

// omitted random detail
impl State for LoadingState {
    fn update(..) {
        let loaded = unimplemented!();
        if loaded {
            return Trans::Switch(..);
        }

        if let Stopwatch::Started(..) = &self.stopwatch {
            let elapsed = self.stopwatch.elapsed();
            if elapsed > LOADING_TIME_LIMIT {
                self.stopwatch.stop();

                let duration = humantime::Duration::from(elapsed);

                warn!("you didn't register X bundles / systems");
            }
        }

        Trans::None
    }
}
```

**Comment by jojolepro** [comment]
Is this still an issue?

**Comment by azriel91** [comment]
It's an issue when any asset is requested to load, but the `Processor<_>` isn't registered. There's no obvious way to solve this generically. It may be worth waiting for `atelier-assets` to be integrated into amethyst to solve this.

**Comment by versusvoid** [comment]
Can't you make gtlf system depend on animation (or warn at absence) at least for now? I don't event need/care for animations in gltf files I'm trying to load, but if there are any, app just stuck in loading with no indication whatsoever

**Comment by khionu** [comment]
This is probably still relevant.

**Comment by jojolepro** [comment]
A lot of changes happened in the assets crate, so I'm not sure if this is still relevant. Feel free to reopen if you know the set of tasks that we need to take to close this issue.
