### ISSUE TITLE
Tried to fetch a resource of type "Texture" but not exist

### ISSUE THREAD

**Issue by qt911025** [amethyst/amethyst#1835]
## Description

I'm following the pong tutorial to [Section 3](https://book.amethyst.rs/v0.12.0/pong-tutorial/pong-tutorial-03.html). The demo panicked, saying texture resource does not exist.

## Reproduction Steps

1. Fetch [this repo](https://github.com/qt911025/pong)
2. Run `cargo +nightly run --features nightly`

## What You Expected to Happen

No panic shown.

## What Actually Happened

The program panicked with this message:
```
thread 'main' panicked at 'Tried to fetch a resource of type "amethyst_assets::storage::AssetStorage<amethyst_rendy::types::Texture>", but the resource does not exist.
Try adding the resource by inserting it manually or using the `setup` method.', /home/quentine/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.7.2/src/res/mod.rs:186:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

## Your Environment

1. Linux Manjaro
2. Latest
3. 0.12.0

**Comment by ishitatsuyuki** [comment]
You should be using the `RenderingBundle`, which was an addition in `0.12.0`. The examples are updated, but the book seems not.

See this:
https://github.com/amethyst/amethyst/blob/32d13c69d668f072ae4497083c4485cebe8e5a7c/examples/pong_tutorial_03/main.rs#L35-L44

**Comment by qt911025** [comment]
The previous issue is solved, thx.

Now I've finished the whole pong tutorial, however crashing occurred at the last section.
The program crashed with error info:
```
[ERROR][rendy_resource::escape] Terminal must be dropped after all `Escape`s
[ERROR][rendy_resource::escape] Terminal must be dropped after all `Escape`s
[ERROR][rendy_resource::escape] Terminal must be dropped after all `Escape`s
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(2048) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(1048576) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(512) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(4096) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(16384) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(131072) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(256) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(32768) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(262144) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(2097152) is still used
```

...
and multiple
```
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
```

Demo repo is [still the same](https://github.com/qt911025/pong).

**Comment by ishitatsuyuki** [comment]
I think you missed the actual error: the crash handler will not exit the program cleanly thus those error messages, but they have nothing to do with the actual crasher.

Crash are typically panics, run with RUST_BACKTRACE=1 and see if you can get anything more useful.

**Comment by qt911025** [comment]
I ran back trace and found the problem.
I forgot to initialize scoreboard. Careless me...
