### ISSUE TITLE
[MAINTENANCE] Use derive-new, derive_builder and getset macros

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#1838]
## Note

We have a bunch of code that is basically copy pasted, and its a pain to maintain.

First, some facts!
```
grep -r "fn new() " ./  | wc -l
69
grep -r "fn get_" ./  | wc -l
30
grep -r "fn set_" ./  | wc -l
77
egrep -r "fn [a-Z]*\(&self\) ->" ./  | wc -l
134
```

The goal is to get rid of this kind of code
![image](https://user-images.githubusercontent.com/4755185/62293505-c520b700-b436-11e9-98d2-f743bf0f7f90.png)

and this one
![image](https://user-images.githubusercontent.com/4755185/62295171-7b39d000-b43a-11e9-9836-396276d2a969.png)

While I'm already planning on splitting UiTransform in a bunch of components, it would be easier to edit the code if we were using a macro for the new() method, as I would only have to remove the field I'm editing from the struct definition instead of in:

- struct def
- new method signature
- new method body
- accessor ( field_name() method)
- setter ( set_field_name() method)
- sometimes get_mut method

Using both the derive_new macro and the getset macros can help cut down all those methods and instead have

- struct definition
- `#[new(default)] (if needed)`
- `#[get] #[set] #[get_mut]`

So instead of 1+1+1+3+3+(3) = 12 lines per field, in the optimal case we would have 2 lines per field (for public ones).

If we count the mandatory method documentation, we can cut another 3 lines per field and 1 line per struct.

For the derive-builder macro, this is a bit more complex and depends much more on how the struct is defined and used, so it will be looked at on a per-case basis to decide if it is worth replacing a builder by a macro.

## Description

- Add at least the derive-new and getset crates to all amethyst crates
- Make the macros globally accessible in the crates
- Replace ALL `new() -> Self` methods by the `#[derive(new)]` macro
- Use `#[new(default)]` on fields that are currently not in the new() signature but are used by the struct
- Evaluate which Builder structs could be replaced by the derive_builder macro
- Remove ALL get/get_mut/set methods that are not doing anything special and replace them by the corresponding getset macros

## Reason

- Less code, which means faster reviews and easier reading.
- Easier to maintain.
- Lowers modification/editing time significantly.
- Lowers addition time significantly.
- Improves doc consistency (generated docs are always the same for get/get_mut/set methods)

## Impact

If you want to add custom behavior in a setter (which is kind of rare since we try to be as data-oriented as possible), then you'll have to manually write the get/get_mut/set method manually at the same time, because it will not have been written for you ahead of time.

## Additional Information
This isn't planned for any particular release. We'll merge what we can as we go. Normally this shouldn't have any api change, or only minor ones due to naming consistency changes.

Since we want to avoid massive changes, I propose that we split it up as 1 PR / amethyst crate.
This way, multiple people can work at the same time on different parts. Also, this allows to split up the work load in manageable chunks.

Write a comment on this issue or edit this post (if you have the ability) to claim a crate you want to work on. The format is
`- [ ] crate_name (@person_in_change)`

#### Crates

- [ ] amethyst
- [ ] amethyst_animation (@Areredify)
- [ ] amethyst_assets
- [ ] amethyst_audio
- [ ] amethyst_config
- [ ] amethyst_controls (@iamsauravsharma)
- [ ] amethyst_core
- [ ] amethyst_derive
- [ ] amethyst_error
- [ ] amethyst_gltf
- [ ] amethyst_input
- [ ] amethyst_locale
- [ ] amethyst_network
- [ ] amethyst_rendy (@projecteulerrs)
- [ ] amethyst_test
- [ ] amethyst_ui
- [ ] amethyst_utils
- [ ] amethyst_window

**Comment by projecteulerrs** [comment]
i can do amethyst_rendy

**Comment by iamsauravsharma** [comment]
i will do amethyst_controls

**Comment by iamsauravsharma** [comment]
implementing a getset macros will have a API change. Since a getset macros only return reference of a data which will cause breaking change. for example if function initially at first return out a i32 then after a getset it will start to return &i32. So if all crates getset is implemented than their will be lots of API change due to change of return type of lots of getset
For example:-
```
#[macro_use]
extern crate getset;

#[derive(Getters)]
pub struct Sub {
    #[get = "pub"]
    place: i32,
    _location: i32,
}

impl Sub {
    pub fn get_place(&self) -> i32{
        self.place
    }
}

fn main() {
    let a = Sub { 
        place : 10,
        _location : 20,
    };
    let _c = a.place(); // This will return &10
    let _d = a.get_place(); // This will return 10
}
```

**Comment by jojolepro** [comment]
Ah you are right. I'll ask if we can change those to return Copy types directly.

**Comment by jojolepro** [comment]
https://github.com/Hoverbear/getset/pull/19

**Comment by iamsauravsharma** [comment]
I just stumbled upon [property](https://crates.io/crates/property) crate while searching. It's [github](https://github.com/yangby-cryptape/rust-property/) mentioned about a support of a copy type as well as lot's of other support. At first glance it looks more advanced than getset crate. What yours thought about using this crate instead of getset?

**Comment by jojolepro** [comment]
It seems that 
1) The macros are longer
2) The default visibility for getters and setters is pub(crate) instead of using the same visibility as the field's one.

**Comment by Areredify** [comment]
I'll do animation

**Comment by Areredify** [comment]
I'll do utils, ui and window

**Comment by Areredify** [comment]
core::transform has a lot of getters and setters that are marked `#[inline]`, I feel like I shouldn't change them, is that correct?

**Comment by Areredify** [comment]
I guess that's all of them, ironically enough the first example of "bad" code didn't get refactored.

**Comment by kabergstrom** [comment]
While the reduced line count is nice, it seems like this change makes the codebase a bit harder to navigate. Neither RLS nor rust-analyzer can resolve the accessors generated by `getset` right now, and it becomes a bit confusing that `set_*` methods become impossible to search for. I think importantly for a lot of people that use RLS/rust-analyzer, it may become frustrating that "it doesn't work" when navigating the codebase, especially for newer contributors. 

Is there something that can be done to remedy these issues or weigh the pros/cons here?

Also, does `getset` propagate doc comments for fields to the accessor methods?

**Comment by Areredify** [comment]
As for the last question, it does.

**Comment by Frizi** [comment]
@Areredify 
> core::transform has a lot of getters and setters that are marked #[inline], I feel like I shouldn't change them, is that correct?

It seems like generated accessors actually inline things always https://github.com/Hoverbear/getset/blob/master/src/generate.rs#L114

@kabergstrom seems like it does propagate docs


Still, I also feel a bit uneasy about this whole idea. I mean, it's PROBABLY a good thing, but as with most of the good things, you have to be careful to not overdo it. Most of the code analysis tools seems to be confused by this. It might change in the future, but it is frustrating right now.

I myself was really confused when trying to find a `fn global_matrix` in the code. It's really not obvious that a method can really be just a field access if it can't be found by project-wide search. Having things that are impossible to find can feel really bad. This combined with a lot of complex types around components and joins in our codebase adds up quickly to a very hard to read code.

I don't think that optimizing for less lines is a good thing overall. It makes code just more dense in the best case, but usually it also makes it more "magical" without good explanation. I would instead focus on optimizing for less high-level complexity.

**Comment by azriel91** [comment]
I'd like to move this one along, because many wide-ranging PRs in progress means we'd get conflicts (and I have a few planned).

I rely on explicit function declarations / definitions a lot for discovery as well -- without going to docs, it's much faster to find out what can / cannot be done.
In my opinion, the `new` changes are not as disruptive, perhaps we should go with that subset first.

**Comment by jojolepro** [comment]
We can always make a PR to improve the documentation generation of the getset crate. Would you mind explaining how using "jump to function" on a getter improves your productivity vs just jumping to the struct definition?

**Comment by azriel91** [comment]
It maintains flow and keeps me happy.

<details>

<summary>It is very much an emotive reasoning, though a rational reason can be given as well.</summary>

Consider:

```rust
my_iterator
    .map(|data| data.member())
    .for_each(|member| member.do_something());
```

* `member` is a field name from `data`.
* `data` is not necessarily named after its type. `member` may not be either.
* I want to figure out what `do_something()` does.

**Scenario 1: Explicit function definitions**

Assuming I have `data`'s crate in my workspace, I would go:

* What type is `member`?
* Press F12 on `member()`
* I see

    ```rust
    pub fn member(&self) -> GiantKangaroo {
        unimplemented!()
    }
    ```

* Now I know to look in the `giant_kangaroo` crate.

**Scenario 2: macro generated functions**

* What type is `member`?
* Press F12 on `member()`
* Nothing happens. What.
* What type is `data`?
* Trace back to earlier part in the function.
* Figure out it's `KoalaBear`
* Jump to definition for `KoalaBear`.
* Scan struct definition for `member`:

    ```rust
    #[derive(Getters)]
    pub struct KoalaBear {
        #[get]
        member: GiantKangaroo,
    }
    ```

* Now I know to look in the `giant_kangaroo` crate.

</summary>

**Comment by azriel91** [comment]
Ping. Assuming https://github.com/Hoverbear/getset/pull/19 is merged, am okay with using macros to generate the accessor methods (so that `Copy` types are deref'ed), pending majority vote (though I still prefer not to have macro-generated accessors).

By the way, emotive points are valid (s'why I presented it), but they can't always be used to block progress. Would like to progress the many open PRs -- would like to merge the less-debated ones at least, and if we aren't going to merge `getset` yet, we should close them.

**Comment by OvermindDL1** [comment]
@azriel91 I'm quite curious what IDE you use?  I've been using intellij-rust and it's able to not only introspect into macro-by-example's but it shows the types of everything inline and can jump to very specific implementations with ease from my experience thus far (it doesn't use rust-rls as the rls protocol is a bit lacking for strongly typed languages...).

**Comment by azriel91** [comment]
ah I use sublime text 3 with Rust Analyzer; IntelliJ does look very nice (especially showing the types inline), but I have to wait a bit before using it -- can't afford recurring license *just* yet.

**Comment by OvermindDL1** [comment]
> can't afford recurring license just yet.

The rust plugin works fully and completely in the free community edition last I heard, although I do get the ultimate edition through my job, the ultimate edition really only adds features that I've never used, and aren't Rust related at all.

**Comment by jaynus** [comment]
Closing for now after discussions about syntax highlight and docs breaking until future changes
