### ISSUE TITLE
[MAINTENANCE] Replace old authors.md file

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#1844]
## Description

Replace the content of the docs/authors.md file by a link to https://github.com/amethyst/amethyst/graphs/contributors

## Reason

It is heavily outdated and we can't realistically keep track of all contributors.

## Impact

/shrug

**Comment by valkum** [comment]
Sorry for posting on a closed issue but it seems the link only shows a total amount of 100 contributors. Maybe there is a bot that helps keeping the file up 2 date? I found all-contributors/all-contributors-bot but it seems it is a bit too verbose.
Ideally it should create a PR adding a name to the file after a PR got merged with a commit by a new person.
