### ISSUE TITLE
[Bug] Image count not supported with Vulkan backend on Wayland

### ISSUE THREAD

**Issue by wackbyte** [amethyst/amethyst#1846]
# Tasks
- Update amethyst's version of rendy

## Description

I use an Intel Ivybridge Desktop GPU, which has a `minImageCount` of `2` ([see here][gpu-surface]). Ever since updating to 0.12, I've been getting the same error every time I try to run my project.

```text
[WARN][rendy_wsi] Image count not supported. Supported: 4..4294967295, requested: 3
```

Is this why Amethyst warns about Ivybridge Vulkan support?

```text
INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete
```

EDIT: This also doesn't work on `master` and/or with nightly.
EDIT 2: See amethyst/rendy#182

## Reproduction Steps

1. Run the sphere example with Vulkan (the same thing happens)
```sh
cargo run --example sphere --features vulkan
```

## What You Expected to Happen

I expected the example to run and display a sphere.

## What Actually Happened

I got [an error][logs]

## Screenshots and Logs

* [Discord #help conversation][help]
* [Logs][logs]

## Your Environment

1. Operating System: Arch Linux
2. Operating System Version: rolling
3. Version of Amethyst: 0.12

## Additional Context

* GNOME on Wayland
* Mesa 19.1.6
* [GPU & Vulkan info][gpu]

[gpu]: https://vulkan.gpuinfo.org/displayreport.php?id=6579
[gpu-surface]: https://vulkan.gpuinfo.org/displayreport.php?id=6579#surface
[logs]: https://pastebin.com/EpLvybct
[help]: https://imgur.com/a/eggBhQY

**Comment by ishitatsuyuki** [comment]
AFAIK Mesa is known to have a bug where it has a large minImageCount than what is necessary.

**Comment by valkum** [comment]
But I think we checked with the Vulkan Hardware Capability Viewer as well. Why would Mesa return something different to the Capability Viewer than to us?

**Comment by jakbyte** [comment]
Correct me if I'm wrong because I don't really know much about this, but I was thinking that the error was happening because:

* My GPU's `minImageCount` is 2
* Rendy's (specifically `rendy-wsi`'s) minimum is 4
* The supplied image count is 3

So I'm thinking my GPU would accept the image count, but Rendy's minimum causes a panic.

**Comment by valkum** [comment]
Its I think:
- GPU's minImageCount really is 2
- Rendy's (specifically rendy-wsi's) wants to setup a surface with (thus supplied) 3 backing images
- Somehow the GPU or the driver reported to rendy-wsi the minImageCount is 4 thus rendy-wsi returns the error

The question here is: Does Mesa report the wrong image count or is it a problem within rendy-wsi or any dep. For this I asked you (in chat) to run the Vulkan Hardware Capability Viewer to see if the driver really reports the surface capability minImageCount that rendy is getting.

You said yes IIRC. I hope there was no misunderstanding. I meant the value from the program not the value on the website.

Im not sure if the Vulkan Hardware Capability Viewer does something different than rendy-wsi to get the surface capabilities.

**Comment by jakbyte** [comment]
From the Vulkan Hardware Capability Viewer:
![image](https://user-images.githubusercontent.com/29505620/62579671-5e563000-b872-11e9-86ab-296f1ecf0648.png)

**Comment by lykhouzov** [comment]
> From the Vulkan Hardware Capability Viewer:
> ![image](https://user-images.githubusercontent.com/29505620/62579671-5e563000-b872-11e9-86ab-296f1ecf0648.png)

Hi, I have the same issue and the same output of Vulkan Hardware Capability Viewer.
Does some one know how to fix the issue?
PS: in my case the difference of TS is only that i have openSuse. and running an app just after a project was created by `amethysts new project_name`

**Comment by navaati** [comment]
If like me you just wanted to get your feet wet and get a taste of amethyst, you can do that by following the book for version 0.11, which does not have the bug.

Still hope that one gets fixed soon, version 0.12 looks way easier to use !

**Comment by ishitatsuyuki** [comment]
Please change the issue title/description so it reflects that this is a rendy bug with Wayland.

https://github.com/amethyst/rendy/issues/182

**Comment by ishitatsuyuki** [comment]
The upstream issue is resolved. After rendy gets an upgrade, we can close this issue.

**Comment by jakbyte** [comment]
I was able to temp fix this by prefixing the command with `WINIT_UNIX_BACKEND=x11`.

**Comment by ishitatsuyuki** [comment]
rendy is updated, probably can close this.

**Comment by navaati** [comment]
Hi.

Is the relevant version of rendy used in the last stable/recommended version of amethyst ? Because if not the version needs to be bumped in amethyst’s Cargo.toml…

**Comment by ishitatsuyuki** [comment]
It’s in master, might be unreleased but we close issues right after the fix is merged.

**Comment by navaati** [comment]
Ok, I’ll keep an eye on releases then, thank you :)

**Comment by 0x6273** [comment]
It's not in amethyst master, since we still depend on rendy 4.1. [That version still has the image count hard-coded to 3.](https://github.com/amethyst/rendy/blob/74eef19b04164651b17fec9486be37fff5b4df9a/graph/src/node/render/pass.rs#L443)

**Comment by ishitatsuyuki** [comment]
Sorry that's my mistake. Rendy 0.5 port will probably take a while, so a good way might be to backport the imageCount patch to 0.4 branch.

**Comment by Barugon** [comment]
This is blocking me.

**Comment by ishitatsuyuki** [comment]
why? you could trivially workaround by running with X11.

**Comment by AndreasBackx** [comment]
> why? you could trivially workaround by running with X11.

I wouldn't say moving desktop environments is trivial though.

Regardless, for those stuck with this issue, a workaround is to pass `WINIT_UNIX_BACKEND=x11` when starting to force it to use X11 and thus XWayland on Wayland if you have it installed. I didn't see any other backend available on Linux so this seems to be the only real workaround.

Any update on this in the meantime?

**Comment by Barugon** [comment]
> Regardless, for those stuck with this issue, a workaround is to pass `WINIT_UNIX_BACKEND=x11` when starting to force it to use X11 and thus XWayland on Wayland if you have it installed.

Thanks for the tip. It would be nice if it worked on Wayland though.

**Comment by jakbyte** [comment]
Yeah, could we get an update on this? It's been a few months.

**Comment by Barugon** [comment]
Any progress on this? Requiring users to switch to X11 is a show-stopper.

**Comment by chemicstry** [comment]
This should already be fixed on `wasm` branch, but it won't be merged until upstream dependencies release a new version with our changes

**Comment by navaati** [comment]
Hi. Can we remove the stale label ? This is not fixed yet since Amethyst is still based on a Rendy version that has the bug.

**Comment by Barugon** [comment]
https://amethyst.rs/posts/amethyst--starting-fresh
