### ISSUE TITLE
[FEATURE MODIFICATION] Prefer scan codes over virtual key codes whenever possible

### ISSUE THREAD

**Issue by clarfonthey** [amethyst/amethyst#1847]
## Feature

Right now, the pong example and the methods in `amethyst::input` definitely prefer virtual key codes over scan codes, which seriously disadvantages users of non-QWERTY keyboard layouts.

## Change

Right now, scan codes are referenced with a single integer, which makes them hard to use. If I want to control my character using WASD, then it's not immediately obvious which scan codes these represent. I have to first understand how keys are numbered (as the scan code is one-dimensional, not two) and then I have to basically count the keys on my own keyboard in order to determine which is which.

Preferably, there would be a function that converts between virtual key codes and scan codes for a given layout, e.g. QWERTY. Maybe even one to convert a set of bindings to use entirely scan codes instead of key codes so that the codes a developer uses stay the same regardless of what keyboard layout someone uses.

Additionally, there should be standalone methods for `is_scan_code_down` and `is_scan_code_up` like there are for `is_key_up` and `is_key_down`. I would even suggest renaming these to say `virtual_key` instead of `key` to clarify that this doesn't correspond to a physical keyboard.

Maybe, the term "physical key code" instead of "scan code" could be used to help send home the message that this refers to the physical position of the key, in contrast to virtual key codes, which don't.

## Reason

It's extremely common for developers to rely on virtual keyboard codes for controls in games when they really should be using physical scan codes. As a Colemak user, I have to often manually remap my keys every time I play a game because the WASD the developer intended is a WARS for me, and sometimes I even have to switch between QWERTY and my desired layout between gaming and chatting just to get the controls to work.

I feel like Amethyst should be setting the right example by pushing the user to use scan codes instead of virtual codes for most situations. Things like arrow keys and escape should be done with virtual codes, but things like letters depend on keyboard layouts and should not be relied upon if the position is what's important.

## Impact

Honestly, I doubt this would affect much more than the input bundle, in terms of Amethyst itself. Users of the library would have to change how they use their existing bindings in order to use the (preferred) scan codes, although I guess this feature could be done in a way that doesn't affect existing users. 

## Additional Notes

I think I pretty much covered everything.

**Comment by Friz64** [comment]
As a Colemak user myself i couldn't agree more. However a function to convert ScanCode <-> VirtualKeyCode will need to be implemented in winit afaik.

I have found these relevant winit issues: 
- https://github.com/rust-windowing/winit/issues/753
- https://github.com/rust-windowing/winit/issues/732

**Comment by clarfon** [comment]
Perhaps in the meantime there could still be work to at least manually convert between QWERTY and scan codes? Simply having a `qwerty` module with constants for each of the letter keys would still be very helpful.

**Comment by clarfon** [comment]
…oh. I just read those threads and there were comments about how scan codes don't seem to stay consistent across platforms. Welp.

We'll have to wait on them, then.

**Comment by clarfon** [comment]
(comments)

**Comment by jojolepro** [comment]
If the scan codes aren't consistent between platform, do we want to keep this opened?

**Comment by Friz64** [comment]
I think there's no reason for them to not be consistent, winit just hasn't gotten around to doing anything about it afaik

**Comment by Friz64** [comment]
Still relevant i think

**Comment by iwikal** [comment]
In theory they could be different on different platforms, but I think in practice everyone uses the mapping defined by the USB HID standard. Who even has a non-usb keyboard these days? Even laptop keyboards use usb internally, I think.

**Comment by jojolepro** [comment]
The way we do inputs will eventually change, but it is not for right now. For now, please write an RFC under the amethyst/rfcs repository for consideration and further discussions. Thanks!

**Comment by Friz64** [comment]
`winit` has been hard at work on a new keyboard API, which solves this issue. It has already been implemented on Windows: https://github.com/rust-windowing/winit/pull/1788, other platforms following soon.

**Comment by jojolepro** [comment]
perfect! thank you :)

**Comment by clarfonthey** [comment]
I don't really have the time to write up an RFC for this -- it kind of sucks that this issue just gets closed and that's it since it was made before the RFC process existed.

If someone else has the time to put together an RFC for this though, would definitely be willing to help provide extra details as needed.

**Comment by jojolepro** [comment]
I don't mind re-opening it, but I'm trying to have all issues have a set list of tasks to do towards completing the issue (otherwise we have 150+ issues opened for years). This issue seemed to still be in discussion, which is why I'm pointing to the rfc process for further discussions. Does this make sense? :)

**Comment by clarfonthey** [comment]
Oh I completely understand, I mostly just don't want the discussion to get lost completely. I think that with the new winit changes coming everything should be good, though
