### ISSUE TITLE
Expressing my interest to support Amethyst

### ISSUE THREAD

**Issue by Raj2032** [amethyst/amethyst#1852]
I wanted to express my interest to help and support Amethyst.  I have basic/limited experience with Rust and I wanted to build my experience as well as to help with the team. I was wondering if there is an easy issue that I can resolve for amethyst?

**Comment by jojolepro** [comment]
Hello and welcome to the club!

The best place for general discussions or questions is on the forum: https://community.amethyst.rs/
As for easy issues, we have both issues that are specifically meant for new users and others that are less detailed but are also considered easy:
https://github.com/amethyst/amethyst/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
https://github.com/amethyst/amethyst/issues?q=is%3Aissue+is%3Aopen+label%3A%22diff%3A+easy%22

For more direct-style discussions, you can join our discord server https://discord.gg/amethyst .

Happy to have you here!
