### ISSUE TITLE
[BUG] Broken link in animation section of the book

### ISSUE THREAD

**Issue by Areredify** [amethyst/amethyst#1854]
## Description

Broken link to API reference in section 9.4 of the book

## Reproduction Steps

1. Go to 'https://book.amethyst.rs/v0.12.0/animation/definition.html'
2. Click on 'API docs'

## What You Expected to Happen

amethyst_animation docs are shown to me in all their beauty

## What Actually Happened

Docs failed to build :(

## Screenshots and Logs

![зшс](https://user-images.githubusercontent.com/25266609/62460909-f9280f00-b78b-11e9-868e-7ba9a9560f76.png)

**Comment by Yam76** [comment]
Is this as simple as replacing the link in the book with [this?](https://docs.amethyst.rs/stable/amethyst_animation/)

**Comment by Yam76** [comment]
ooh, spooky, there are two links!

[docs.rs](https://docs.rs/amethyst/0.12.0/amethyst/)

[docs.amethyst.rs](https://docs.amethyst.rs/stable/amethyst/)

But if you go to the docs.rs on and click on `amethyst_animation`, you get a [broken link](https://docs.rs/amethyst_animation/0.7.0/amethyst_animation/index.html)

So docs.amethyst.rs is probably the correct one. Clicking on `amethyst_animation` yields a [functional link](https://docs.amethyst.rs/stable/amethyst_animation/)

**Comment by Yam76** [comment]
Sorry for bad PR's, I haven't got a handle on all of Github's features yet.
