### ISSUE TITLE
[MAINTENANCE] Pong tutorial mismatch with amethyst_cli

### ISSUE THREAD

**Issue by SonicZentropy** [amethyst/amethyst#1873]
## Description

The recommended approach inside of the Getting Started section of the book is to use amethyst_cli to create a project skeleton (https://book.amethyst.rs/stable/getting-started.html).  The later tutorials then build on this skeleton.  However, amethyst_cli now places display_config.ron into resources/display_config.ron instead of config/display_config.ron, so the tutorial code doesn't work without amending.

## Reason

It's pretty trivial to notice and correct yourself, but also a simple change would eliminate the need.  I'm happy to PR the changes if someone more experienced can weigh in and tell me exactly which part of this actually needs changing.

## Impact

I don't see why it would, since it's just documentation?

**Comment by jojolepro** [comment]
Fixed by a commit in amethyst/tools
We were missing the 0.12 template.
