### ISSUE TITLE
[BUG] During shutdown, renderer fails to destroy semaphore before destroying device.

### ISSUE THREAD

**Issue by Andrewp2** [amethyst/amethyst#1884]
## Description

Gfx backend vulkan errors happen in the terminal when there should not be any. 

## Reproduction Steps

Run ` cargo run --example pong --features "vulkan"
See error in terminal

## What You Expected to Happen

The example to run with no errors

## What Actually Happened

The example runs fine, but has an error related to [gfx_backend_vulkan]

## Screenshots and Logs

[terminal output](https://gist.github.com/Andrewp2/1e7473b3a7815d38815a13aa2476d37c)

[output from vulkaninfo](https://gist.github.com/Andrewp2/c32fdb5328f3b0d73387f35db10c6476)

## Your Environment

1. Operating System: Ubuntu
2. Operating System Version: 18.04.3 LTS
3. Version of Amethyst: 0.12.0

## Additional Context
I'm brand new to Rust, Amethyst, Vulkan, and contributing to open source, so this is much more likely to be a problem with the way I installed my drivers or something else about my setup. If it isn't that, then it's probably an issue with gfx-hal, and only then amethyst.

**Comment by Dispersia** [comment]
Just to clarify, the 

> [ERROR][gfx_backend_vulkan] 
> VALIDATION [UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout (0)] : Submitted command buffer expects VkImage 0x23[]  (subresource: aspectMask 0x2 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_UNDEFINED.
> object info: (type: COMMAND_BUFFER, hndl: 93934827758224)

happens as soon you start the game, and then 

>  [ERROR][gfx_backend_vulkan] 
> VALIDATION [VUID-vkDestroyDevice-device-00378 (0)] : OBJ ERROR : For VkDevice 0x556ee7b835a0[], VkSemaphore 0x48[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
> object info: (type: SEMAPHORE, hndl: 72)

is what happens when you close the game. I and a few others in the discord can reproduce this now.

**Comment by jmwielandt** [comment]
Hi~

I'm having the same issue following pong tutorial but on w10 pro 1903, build 18362.295.
Vulkan SDK 1.1.114.0.
Rust 1.36 stable
Amethyst 0.12

Vulkaninfo: [vulkaninfo.txt](https://github.com/amethyst/amethyst/files/3526205/vulkaninfo.txt)
```
PS > vulkaninfo.exe > vulkaninfo.txt
c:\vulkansdkbuild\workspace\khronos-tools\repo\vulkaninfo\vulkaninfo.c:6156: failed with VK_ERROR_INITIALIZATION_FAILED
```

Execution log: [log-execution.txt](https://github.com/amethyst/amethyst/files/3526211/log-execution.txt)
```
cargo run --features "vulkan"
```


Source code: [pong.zip](https://github.com/amethyst/amethyst/files/3526216/pong.zip)

What vulkanSDK version should i install? 🤔

Thanks~
I hope this info could help ^^

**Comment by Dummyc0m** [comment]
Very new to amethyst and graphics, and I'm getting the same issue. Is this a problem at all?

**Comment by Zazck** [comment]
[info.txt](https://github.com/amethyst/amethyst/files/4456288/info.txt)
[log.txt](https://github.com/amethyst/amethyst/files/4456289/log.txt)
[main.rs.txt](https://github.com/amethyst/amethyst/files/4456294/main.rs.txt)

Same issue here, log provided.

Windows 10 1909 18363.657

**Comment by CleanCut** [comment]
Reopening.  Stalebot wasn't supposed to actually close issues.

**Comment by Zazck** [comment]
I solved this problem by updating vulkan sdk to latest version. don't know if it's a general solution

**Comment by CleanCut** [comment]
Nice. I'll actually close this, then.  If others still have the problem and updating the vulkan sdk doesn't fix it, feel free to reopen.
