### ISSUE TITLE
[NEW FEATURE] Setting custom logger Formatter

### ISSUE THREAD

**Issue by mvlabat** [amethyst/amethyst#1889]
## Description

I would like to use a custom logger formatter in my project. I have several binaries producing output to the same stdout (a client and a server as a child-process in my case), and I'd like to distinguish their output. Like this, for instance:
> [INFO][SERVER][amethyst::app]

## What problem does this solve? What need does it fill?
The only way I've found to accomplish this is to construct `fern::Dispatch` manually and apply it as a global logger, skipping Amethyst logger. I think it's quite easy to provide an API for passing custom formatter, so users don't have to construct the dispatcher manually.

## Describe the solution you'd like
We could provide an alternative constructor that would allow passing both `LoggerConfig` and a formatter function.

**Comment by nalshihabi** [comment]
Hello, I am new here but I believe I can tackle this feature.

**Comment by mvlabat** [comment]
Works perfectly, thanks @nalshihabi for implementing!
