### ISSUE TITLE
[NEW FEATURE] Getting a port of UdpSocket if passing 0

### ISSUE THREAD

**Issue by mvlabat** [amethyst/amethyst#1890]
## Description

I believe `amethyst_new` should provide a way to get a port assigned to `UdpSocket` by system, if we pass 0 to `NetworkBundle` constructor.

## What problem does this solve? What need does it fill?
In some cases it would be convenient to create `NetworkBundle` with `0` port, but there's no API to get the assigned port by system back.

## Describe the solution you'd like
A `NetworkingSystem` could create a resource, storing the actual port?

**Comment by jstnlef** [comment]
This will be covered by this. https://github.com/amethyst/amethyst/pull/1917. In the new system, you will be expected to bind an appropriate socket and pass it to the associated transport implementation for that socket. `UDP, TCP, Laminar`
