### ISSUE TITLE
[BUG] InvalidImageLayout from validation layer

### ISSUE THREAD

**Issue by ishitatsuyuki** [amethyst/amethyst#1899]
## Description

Validation layer complains with the following error. Also happens with RenderDoc so this is legit.

```
[ERROR][gfx_backend_vulkan] 
VALIDATION [UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout (0)] : Submitted command buffer expects VkImage 0x1b[]  (subresource: aspectMask 0x2 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_UNDEFINED.
object info: (type: COMMAND_BUFFER, hndl: 2221017963664)
```

## Reproduction Steps

I think running any application with `RenderToWindow` and `RenderFlat3D`? TBD.

## Screenshots and Logs

Inspection through RenderDoc shows that this is likely a bad image barrier being issued. The barrier has oldLayout set as `VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL`, while it should have been `VK_IMAGE_LAYOUT_UNDEFINED`.

## Your Environment

Arch Linux (rolling), Amethyst `gac3de03a`

cc @omni-viral

**Comment by ishitatsuyuki** [comment]
So the problem here is that rendy uses implicit layout transitions inside the render pass, but yet it still generates explicit barriers for the image. I think we currently generate barriers for all images that is declared; so maybe we can separate the handling between attachments and other images? Is that correct @omni-viral?

Apart from that rendy [might generate a noop barrier](https://github.com/amethyst/rendy/blob/master/chain/src/sync.rs#L381) that does not transition state at all, but that is not at the heart of this problem: if you run two or more subpass then there will be the same issue.

**Comment by Igosuki** [comment]
I still get this error when trying to run amethyst-starter-2d against master : 
```
VALIDATION [UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout (0)] : Submitted command buffer expects VkImage 0x1b000000001b[] (subresource: aspectMask 0x2 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_UNDEFINED.
object info: (type: COMMAND_BUFFER, hndl: 140710231011496)

[ERROR][amethyst_assets::storage] "renderer::SpriteSheet": Asset "sprites/logo.ron" (handle id: Handle { id: 0 }) could not be loaded: Failed to load asset with name "sprites/logo.ron"
[ERROR][amethyst_assets::progress] Error loading handle 0, renderer::SpriteSheet, with name sprites/logo.ron: Failed to load asset with name "sprites/logo.ron"
caused by: Failed to load asset with name "sprites/logo.ron"
```
