### ISSUE TITLE
[FEATURE MODIFICATION] Premultiplied view*proj matrix

### ISSUE THREAD

**Issue by ishitatsuyuki** [amethyst/amethyst#1902]
## Change

The view and projection matrix should be premultiplied on the CPU. The code responsible for this is inside `EnvironmentSub`.

## Reason

The current implementation do this in vertex shader. The multiplication is performed for each vertex, which is redundant. Changing this may slightly improve performance.

**Comment by ishitatsuyuki** [comment]
Implementor's note: the skybox uses `view_without_translation`, so this change is not a simple find-and-replace.

**Comment by nico-abram** [comment]
Is anyone working on this already? If not, it looks like a simple enough first issue for me to try :P

**Comment by ishitatsuyuki** [comment]
This is probably not very hard, but make sure you check the skybox caveat as I have commented above.

**Comment by nico-abram** [comment]
Thanks for the response, will do, I'm gonna assume no one's working on this aready and give it a shot.

**Comment by nico-abram** [comment]
I think this can be closed now
