### ISSUE TITLE
[NEW FEATURE] GPU instancing

### ISSUE THREAD

**Issue by happydpc** [amethyst/amethyst#1921]
## Description

Unity has a mature GPU instancing switch, and this can ease the objects spawn effectively. I hope Amethyst can also add this feature.

## What problem does this solve? What need does it fill?
Solve the mass entitys problem.

## Describe the solution you'd like
Refer to the bgfx or unity solution to add this feature.

**Comment by ishitatsuyuki** [comment]
We do. Just refer to the same `Material` and `Mesh` and it's automatically batched by the renderer.

**Comment by happydpc** [comment]
Is there any example for this? What I mean is the indirect drawing instance. Thank you.
