### ISSUE TITLE
[BUG] AnimationControlSet is not in sync with SamplerControlSet

### ISSUE THREAD

**Issue by ishitatsuyuki** [amethyst/amethyst#1936]
## Description

Currently `AnimationControlSet` is only used to send commands (in other words, one way binding) to `SamplerControlSet`, and it becomes out of sync once the animation starts. State updates happens in the latter, so things described below requires you to join on the latter to work.

For example, you might want to watch state to remove an Entity when it reaches `ControlState::Done`.

**Comment by ishitatsuyuki** [comment]
not stale

**Comment by ishitatsuyuki** [comment]
not stale

**Comment by jojolepro** [comment]
should get fixed when ControlSet is refactored (tasks are in an older issue already)
