### ISSUE TITLE
[MAINTENANCE] Typo in wiki

### ISSUE THREAD

**Issue by OnkelMarcel** [amethyst/amethyst#1946]
## Description

There is a typo in the "GraphicalBackendError"-section. 
![unknown](https://user-images.githubusercontent.com/27505801/65717021-a50d1d00-e0a0-11e9-99b6-51fb34b7cd4e.png)

## Reason
Typos look bad.

## Impact
It won't have any impact.

**Comment by distransient** [comment]
Fixed
