### ISSUE TITLE
[BUG] Pong_tutorial_01 example in Docs panics

### ISSUE THREAD

**Issue by ZakWebb** [amethyst/amethyst#1951]
## Description

I'm currently reading through the Amethyst book, and working on the pong example.  However, the code as written does not work on my machine.  It compiles, but there is some error in the RenderingBundle code, and I am not familiar enough with Amethyst in order to really determine what the fix is.

Note that I originally ran into this error when following the directions in the amethyst book and writing it myself, but ran into the same error when attempting to run the pong_tutorial_01.

## Reproduction Steps

1. Clone the amethyst repository
2. Run the first pong tutorial example (`cargo run --example pong_tutorial_01 --features "vulkan"`)
3. The code panics

## What You Expected to Happen

I expected a simple monocolor window to pop up that would last until I stop the program.

## What Actually Happened

A window flashes, and the code panics.  In particular, I get 

thread 'main' panicked at 'Unable to load Vulkan entry points: LibraryLoadError("The specified module could not be found. (os error 126)")', src\libcore\result.rs:999:5note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: process didn't exit successfully: `target\debug\pong.exe` (exit code: 101)

## Your Environment

1. Windows 10 Home
2. 1903
3. 0.12 and 0.13 (I have the same error with both)

## Additional Context
A similar error seemed to occur at [issue 1657](https://github.com/amethyst/amethyst/issues/1657).  That error seemed to deal with the documentation being out of sync with the actual version of amethyst, which might be related to this problem, but that bug was closed. 

This error also didn't begin to occur until I included the RenderingBundle portion of the tutorial, and thus I assume that that is where the error arises.

**Comment by mrhatman** [comment]
Does your graphics card support vulkan? Is your driver up to date?

**Comment by distransient** [comment]
@ZakWebb could you download the [Vulkan SDK](https://vulkan.lunarg.com/sdk/home) and then run the `cube.exe` demo in the `Bin` directory of your SDK installation?

**Comment by ZakWebb** [comment]
Yes, this seems to be the issue.  I did not have Vulkan working on my machine.  Once I got it together things seem to work.  Thanks for the help!

**Comment by distransient** [comment]
No problem!
