### ISSUE TITLE
[BUG] Tiles do not appear in Tiles Example on OSX

### ISSUE THREAD

**Issue by nalshihabi** [amethyst/amethyst#1961]
## Description

When running the tiles example in the repository on OSX, I do not see the tiles loaded in the same way as when I would run the example on Windows. The tiles would not actually load at all unless I press a certain key a few times.

## Reproduction Steps

On OSX, run `cargo run --example tiles --features "metal tiles"`

## What You Expected to Happen

The window to load with tiles, like as what appears on Windows when using vulkan.

## What Actually Happened

The window loads, but the tiles do not appear, or you have to press `F` a couple times then the space bar a couple times to reset the window and a line of tiles will appear.

## Screenshots and Logs

Using windows with vulkan
```
cargo run --example tiles --features "vulkan tiles"
```
<img src="https://user-images.githubusercontent.com/8733531/66006152-b2991d00-e47b-11e9-872b-8f4b6b7039ca.png" width="600" />

Using OSX with metal
```
cargo run --example tiles --features "metal tiles"
```
<img src="https://user-images.githubusercontent.com/8733531/66006260-0c014c00-e47c-11e9-895c-b8fb20f01b37.png" width="600" />

I do not see any errors in logs.

## Your Environment

1. Operating System - **OSX**
2. Operating System Version - **10.14.4 Mojave**
3. Version of Amethyst - 0.13.0

**Comment by distransient** [comment]
This should be fixed in #1957 which I'm currently working to release in a patch. Please comment if that did not fix your issue and will re-open.

**Comment by nalshihabi** [comment]
That issue unfortunately does not fix it. It had fixed an issue with the example not being able to be ran on OSX but once I had that issue implemented I found this issue.

**Comment by Ratysz** [comment]
Similar problem also happens on Windows+Vulkan, as of at least 0.13.1; however, panning the view upwards reveals a single row of tiles:

![](https://i.imgur.com/CQLBg4x.png)

0.13.0 produces the expected scene.

**Comment by Ratysz** [comment]
a8962aaea036ae8d6bd29d41aea72ff2e77524bc appears to be the commit that breaks it.

0d8de5adff678d868a5135492f61a6487905f880 (just prior to the above) looks like this:

![](https://i.imgur.com/s5ybR5z.png)

Which is different from 0.13.0 still, but I assume that is the result of https://github.com/amethyst/amethyst/commit/27bff0317535bb7fa606c41a509dd09aea234313#diff-c4297f4f6819b7595828967d27e332afL352:

![](https://i.imgur.com/GkYv32z.png)

**Comment by Ratysz** [comment]
#1968 appears to have fixed this on Windows+Vulkan.

**Comment by distransient** [comment]
@nalshihabi has the latest fix solved this problem for you?

**Comment by jaynus** [comment]
You'll need to cargo update to get the fix

**Comment by nalshihabi** [comment]
The tiles are visible now for me on OSX.
