### ISSUE TITLE
[BUG] Render Sorting fails to sort correctly sometimes

### ISSUE THREAD

**Issue by valkum** [amethyst/amethyst#1963]
## Description

Using the Sponza Sample from https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Sponza the flowers sometimes are rendered before the floor leading to transparency issues.

## Reproduction Steps

1. Load Sponza GLTF with some basic lights.
4. See error (Sometimes)

## What You Expected to Happen

A correct rendered image.

## What Actually Happened

![bug](https://user-images.githubusercontent.com/169155/66088805-d2643a00-e57c-11e9-81c2-091717d06309.jpg)

## Your Environment

1. Win10 (18362)
2. AMD 10.8.2 (R9 390)
3. Git rev: a0f6ee84 (There should be no commits fixing this)

## Additional Context
Renderdoc Capture: https://we.tl/t-jnH594YLjp

**Comment by valkum** [comment]
I digged a little bit into the code. The GLTF file seems to use alphaMode `MASK`for the leaf material.
But our GLTF loader does not add the transparent prefab field to true when the mode is `MASK` See: [amethyst_gtlf::format::material::load_material](https://github.com/amethyst/amethyst/blob/c97faaf50050190eade4efbfae7b7e4dd68f1bce/amethyst_gltf/src/format/material.rs#L103)
As the Prefab loader does not add the `Transparent` component based on the alpha_cutoff I assume the proper fix would be to set the transparent field in the prefab to true in `load_material`

Can someone confirm this analysis? I would open a PR for this then.

**Comment by valkum** [comment]
Reading through the GLTF spec, it seems there should not be the need to sort the meshes when using `MASK`
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#alpha-coverage But that seems weird to me. @Frizi do you have any idea?

**Comment by valkum** [comment]
Might be still relevant

**Comment by jojolepro** [comment]
inactive
