### ISSUE TITLE
[MAINTENANCE] Add a chapter to the book about the networking library

### ISSUE THREAD

**Issue by jstnlef** [amethyst/amethyst#1975]
## Description
We need to add to the amethyst book how to use our new networking library.

**Comment by TimonPost** [comment]
Yea that would be awesome. Let's sum up a couple of important points that we want to cover. If you have anything as well. I like to hear it.

- [ ] Socket Layer
     - Laminar Socket Layer
     - UDP socket layer
     - TCP socket layer 
     - In-memory layer

     For each layer discuss: 
     **What is it**
        - the use-case

     **How to use it** 
      - explenation
      - the exported types
      - example

- [ ] TransportResource
- [ ] NetworkSimulationTime
- [ ] NetworkSimulationEvent

    
 

Examples/Demo's
- [ ] Building and inject your own transport layer
- [ ] Building a basic server/client game
