### ISSUE TITLE
[BUG] Broken showcase game link in the Book's Call for Contribution chapter

### ISSUE THREAD

**Issue by kylejlin** [amethyst/amethyst#1976]
## Description

In the [Call for Contribution chapter](https://book.amethyst.rs/master/pong-tutorial/contribution.html) of the Amethyst Book, "Survivor" is listed as a showcase game. However, the [provided link](https://github.com/jaynus/survival) takes the reader to a 404 page.

**Comment by erlend-sh** [comment]
It’s been republished now, thanks for reporting.
