### ISSUE TITLE
[BUG] Maximising and minimising youtube videos breaks amethyst

### ISSUE THREAD

**Issue by marek2901** [amethyst/amethyst#1993]
## Description

Maximising and minimising youtube videos breaks amethyst

## Reproduction Steps

1. Have amethyst launched
2. Open up chrome and couple different apps (Tall layout seems convenient to display that issue)
3. Go to youtube start watching a movie
4. Make a video fullscreen
5. Minimise video back again

## What You Expected to Happen

Chrome goes back into amethyst controlled mode. I can cycle through the layout back and forth.

## What Actually Happened

Chrome is no longer recognised by amethyst, other windows seems to overlay it. I can't reach that window using cycle layout shortcut.

## Screenshots and Logs

![image](https://user-images.githubusercontent.com/9845288/66875159-9e8e0900-efad-11e9-9f59-c6fca98663c7.png)

There are still 3 opened chrome browser instances in the second screenshot
![image](https://user-images.githubusercontent.com/9845288/66875174-ac438e80-efad-11e9-9870-5175d088829c.png)

## Your Environment

1. Operating System
Mac OS Mojave
2. Operating System Version
10.14.6 (18G103)
3. Version of Amethyst
0.14.2 (76)

**Comment by distransient** [comment]
This is a general issue with maximization in MacOS. Try doing it with a terminal fullscreening for example, and post logs with Vulkan SDK installed for validation layers (they work even if you're using the metal backend afaik)

**Comment by viclim** [comment]
@marek2901 

It seems to me that you're talking about [Amethyst, the tiling window manager for MacOS](https://github.com/ianyh/Amethyst). You might want to reopen this issue over there.

**Comment by distransient** [comment]
😅
