### ISSUE TITLE
[MAINTENANCE] Can't get fetch resource in pong audio section (Update tutorial)

### ISSUE THREAD

**Issue by gaviriacc26** [amethyst/amethyst#1996]
## Description
I recently went through the pong tutorial again and when I tried to add the background music and got 
`thread 'main' panicked at 'Tried to fetch a resource, but the resource does not exist.`

## Screenshots and Solution Found

I searched in the repository files for the tutorial and found that it actually registers the system with 
```
.with_system_desc(
     DjSystemDesc::new(|music: &mut Music| music.music.next()),
    "dj_system",
    &[],
)
```

instead of 

![Screenshot from 2019-10-16 22-14-58](https://user-images.githubusercontent.com/55761757/66975234-7cef5900-f063-11e9-8a38-225edd75f4fd.png)

and it worked right away.

**Comment by mattnenterprise** [comment]
Looks like this has been updated on master https://github.com/amethyst/amethyst/commit/66b69eac382eafe1bcd736387ef59be9f65e4b6f.
