### ISSUE TITLE
[MAINTENANCE] Arch linux dependency installation line

### ISSUE THREAD

**Issue by sahsahae** [amethyst/amethyst#2002]
## Description
This is wrong: https://github.com/amethyst/amethyst#arch-linux

It should be 

```
$ pacman -Syu grep gcc pkgconfig openssl alsa-lib cmake make python3 freetype2 awk libxcb
```

## Reason

https://wiki.archlinux.org/index.php/System_maintenance#Avoid_certain_pacman_commands

Partial upgrades are bad.

## Impact

Arch linux potentially not booting anymore after shutdown, even if technically it's their own fault, that's probably not something that should be given as a thing to copy paste.

**Comment by distransient** [comment]
Could you make a PR for this?
