### ISSUE TITLE
[MAINTENANCE] Suggest that Debian/Ubuntu users install latest CMake version from snap?

### ISSUE THREAD

**Issue by stephengtuggy** [amethyst/amethyst#2009]
## Description

I see that in the Dependencies section of Amethyst's README, it has Debian/Ubuntu users install `cmake` using `apt`. While this works OK, it won't install the latest stable version of CMake. That can be installed using `snap`, i.e.:

```sh
sudo snap install cmake
```

## Reason

**If** this change should be made, it should be made to provide amethyst users with a more recent version of a dependency, namely CMake. Among other things, the snap version of CMake comes with `cmake-gui`, a GUI tool for setting the configuration options for CMake projects.

## Impact

**Disclaimer:** I don't know what negative impacts, if any, this might have on something else. It will have to be tried first.

## Additional Information

I run both Ubuntu 18.04 LTS and Windows 10 on my machine. I have been working on an open-source game, [Vega Strike](https://github.com/vegastrike/Vega-Strike-Engine-Source), attempting to get it to build without source modifications on both operating systems. cmake-gui has been helpful for tuning configuration variables, then testing them out.

**However,** please note that **I haven't yet gotten Vega Strike to build successfully** this way! My struggles are at least partly due to bugs in the CMake files for the VS game itself. But they may also be partly related to bugs in CMake itself that I am not yet aware of. So take this Maintenance Request with a grain of salt. ;-)

## P.S.

Vega Strike is written primarily in C++, and it has some significant issues with memory management. I am very interested in learning and using Rust, and possibly Amethyst, to develop code that doesn't suffer from these problems. I may even suggest these technologies to the VS community for consideration. For now, I'm just dipping my toes in the water.

**Comment by ishitatsuyuki** [comment]
Typically CMake does not have to be the latest since most projects keeps compatibility with LTS versions of build environment.

(Not to mention that some devs or CI environments might be running Ubuntu LTS as well)

**Comment by distransient** [comment]
To my knowledge, it's not currently any Amethyst user's onus to inspect CMake files associated with the engine. CMake is enough of a ~~terror~~ frustration that if I had ever had to use a GUI tool for CMake while working with Amethyst I would instead take up another hobby like weight lifting or painting.

**Comment by stephengtuggy** [comment]
> To my knowledge, it's not currently any Amethyst user's onus to inspect CMake files associated with the engine. CMake is enough of a ~terror~ frustration that if I had ever had to use a GUI tool for CMake while working with Amethyst I would instead take up another hobby like weight lifting or painting.

Fair enough. :-)
