### ISSUE TITLE
[BUG] World::create_entity().with(Component<Storage=DenseVecStorage>) panics "Tried to fetch a resource, but the resource does not exist."

### ISSUE THREAD

**Issue by mankinskin** [amethyst/amethyst#2019]
## Description

Panic when creating an entity with a custom Component to world.

## Reproduction Steps

1. Checkout https://github.com/mankinskin/community at commit de212eaeb8f5fab3e72f59ec5da7a9fdfb9eeca5
2. (see [`fn initialize_rect`](https://github.com/mankinskin/community/blob/de212eaeb8f5fab3e72f59ec5da7a9fdfb9eeca5/src/states/running.rs#L21))
3. `cargo run`

## What You Expected to Happen

I was following [this tutorial](https://book.amethyst.rs/stable/pong-tutorial/pong-tutorial-02.html#our-first-component). I wanted to create an entity to a World object with a basic Component. with `type Storage = DenseVecStorage<Self>;`

## What Actually Happened

This panic occurred:
```
thread 'main' panicked at 'Tried to fetch a resource, but the resource does not exist.
Try adding the resource by inserting it manually or using the `setup` method.
You can get the type name of the missing resource by enabling `shred`'s `nightly` feature', /home/linusb/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.9.3/src/world/mod.rs:471:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
UNASSIGNED-ObjectTracker-ObjectLeak(ERROR / SPEC): msgNum: 0 - OBJ ERROR : VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_EXT object 0x55f03f449b10 has not been destroyed.
    Objects: 1
        [0] 0x55f03f449b10, type: 3, name: NULL

```

## Screenshots and Logs

If applicable, add screenshots to help explain your problem. Any relevant logs would be helpful as well.

## Your Environment

OS: Manjaro Linux 18.1.1 Juhraya
Kernel: x86_64 Linux 4.19.79-1-MANJARO
WM: i3

```
# Cargo.toml
[dependencies.amethyst]
version = "^0.13"
features = ["vulkan"]
```

**Comment by valkum** [comment]
Had a quick look at your code.
You need to register you Component first as you don't have a system that is using it (and thus would register it)

```
world.register::<Rect>();
```

From https://book.amethyst.rs/v0.12.0/pong-tutorial/pong-tutorial-02.html#initialise-some-entities

> This is rather inconvenient — to need to manually register each component before it can be used. There must be a better way. Hint: there is.

>When we add systems to our application, any component that a System uses is automatically registered. However, as we haven't got any Systems, we have to live with registering the Paddle component manually.

**Comment by mankinskin** [comment]
Oh wow... genius.. I should have just kept reading a few lines..
