### ISSUE TITLE
[FEATURE MODIFICATION] amethyst_tiles::Map::to_tile should accept out-of-bounds input.

### ISSUE THREAD

**Issue by ssbr** [amethyst/amethyst#2020]
## Feature

https://docs.amethyst.rs/stable/amethyst_tiles/trait.Map.html#tymethod.to_tile

This returns an `Option<Point3<u32>>`, but does not document when it's `Some(..)` vs `None`. Currently, it's `Some(..)` if the coordinate is within the map or out-of-bounds in a positive direction (on production builds). If it is out of bounds in a positive direction on debug builds, it panics. if it is out of bounds in a negative direction, it returns `None`.

## Change

I think it should return `None` if out of bounds in a positive direction, and the user should choose whether or not to crash.

## Reason

It is difficult to check in advance whether or not the point coordinate is going to be out of bounds -- figuring out where it is on the grid is the purpose of `to_tile` to begin with! So to correctly call this, one must reproduce some of the logic of `to_tile` to do the bounds checks.

## Impact

Improved documentation for to_tile, since it'd be clear and easy to describe when it returns None. Slightly reduced performance on production builds due to the new bounds check.

## Additional Notes

Alternative approaches:

* Always return a `Point3`, but of `i32` and not `u32`, letting the user check the bounds. (Seems more useful in some ways, but inconvenient due to `i32`/`u32` conversions.)
* Remove the debug crash logic so that it never crashes, only returns `None` (out of bounds, negative) or a `Point3<u32>` (that may or may not be out of bounds, positive). (Slightly weird API, but still useful. Same performance as current approach, just removes the debug-only panic logic.)

IMO any of the above would be easier to use and more helpful than the current API.

* Finally, one could embrace crashing: always return a `Point3<u32>`, and panic if out of bounds. (Same performance impact, but seems less useful.)

For now I've solved this by not clicking out-of-bounds in my toy game. ;)  But I'd like a better solution going forward. If you agree with this approach, or one of the alternatives above, feel free to assign this issue to me and I can write the PR.

**Comment by mrhatman** [comment]
I run into this as well, I agree that this should be fixed,  panic should not be being called when in debug mode here as it leads to functionally different code for debug and release.  

My suggestion would be to change it to return result with a new TileOutOfBounds error  that contains the useful information so, if it's out of bounds people can panic or handle it graceful all without losing information.
