### ISSUE TITLE
[BUG] Playing audio causes rendering lags

### ISSUE THREAD

**Issue by pustaczek** [amethyst/amethyst#2030]
## Description

Playing audio with amethyst::audio::output::Output may cause lags ranging from unnoticeable to arbitrarily long, depending on the optimization level and the repeat count. When the sound is about to play, the game hangs and resumes rendering after a very short moment(usually after the sound starts playing, but before it finishes).

The issue is harder to reproduce with lower repeat count and optimization flags, but without --release even using play_once may result in slight pauses on non-gaming hardware.

## Reproduction Steps

1. Open main amethyst repo.
2. Apply the following patch.
3. Run the pong example with `--release --features vulkan,no-slow-safety-checks`.
4. Notice the lag happening every time the ball bounces off a paddle.
5. If the lag is too short, try increasing the number of replays from 30 to e.g. 200, removing the --release flag, or running on weaker hardware.
```diff
diff --git a/examples/pong/audio.rs b/examples/pong/audio.rs
index db209bc0..ee0094b9 100644
--- a/examples/pong/audio.rs
+++ b/examples/pong/audio.rs
@@ -56,7 +56,7 @@ pub fn initialise_audio(world: &mut World) {
 pub fn play_bounce(sounds: &Sounds, storage: &AssetStorage<Source>, output: Option<&Output>) {
     if let Some(ref output) = output.as_ref() {
         if let Some(sound) = storage.get(&sounds.bounce_sfx) {
-            output.play_once(sound, 1.0);
+            output.play_n_times(sound, 1.0, 30);
         }
     }
 }
```

## What You Expected to Happen

Playing sound does not cause rendering lags. Delays caused by loading sound should likely be handled in a different thread or asynchronously, possibly with a way to wait for completion before starting the game.

## What Actually Happened

Noticeable pauses in rendering appear.

## Screenshots and Logs

If the bug turns out hard to reproduce, I could try to prepare a demonstration video but I hope it's reproducible.

## Your Environment

1. Ubuntu
2. 19.10
3. master branch, d2971a21

## Additional Context

The hardware used is a recent laptop without a dedicated graphics card.

**Comment by distransient** [comment]
Running your game without optimizations will always be bad, and copying debuginfo introduces a lot of extra compile time. Try running nalgebra benchmarks with and without --release, and everything in amethyst uses nalgebra. I recommend only using debug builds for gdb/detailed stack traces

**Comment by pustaczek** [comment]
Yes, but this also happens with --release.

**Comment by distransient** [comment]
Ah, I misunderstood. Definitely a performance bug, then.
