### ISSUE TITLE
[NEW FEATURE] Public display of licenses used in Amethyst deps

### ISSUE THREAD

**Issue by Xaeroxe** [amethyst/amethyst#2032]
## Description

Build a publicly accessible webpage that is automatically updated with the output from running `cargo license` on the Amethyst GitHub repo.

## What problem does this solve? What need does it fill?

Improves confidence from users and developers in the Amethyst project by providing a trivial way to audit the licenses in our large dependency list.

## Describe the solution you'd like
Jenkins will, on push to master, run `cargo license` and publish the output to a web page, possibly hosted on GitHub pages. Additionally, enhance CI to search for blacklisted problematic licenses, such as GPL with no alternative license provided.

## Describe alternatives you've considered

We could just require users to run `cargo license` themselves if they're interested in this information. I think this approach, while viable, is inferior because it 

1. Requires the user to know of cargo license
2. Requires the user to install cargo and cargo-license. For non-engineer legal team members this might just not be viable.
3. Could end up taking long enough to audit properly that Amethyst is simply considered "not an option" because a business can't verify legality of usage.

**Comment by valkum** [comment]
And consider a way to add third-party licences. 
Like when you implement an algorithm from a paper and the author of the paper is ok with that, if you add credit notice of some form. e.g. https://github.com/selfshadow/ltc_code/blob/master/LICENSE
