### ISSUE TITLE
[MAINTENANCE] Pong tutorial uses DjSystem when it should use DjSystemDesc

### ISSUE THREAD

**Issue by DarkWugWug** [amethyst/amethyst#2037]
## Note

I am talking about the [Amethyst book section 4.6](https://book.amethyst.rs/stable/pong-tutorial/pong-tutorial-06.html#adding-background-music). The resolution was found in the [example pong code from master](https://github.com/amethyst/amethyst/blob/38f04eb5709f892d9bdaed3a23ea1c5235584663/examples/pong/main.rs#L70).

## Description

The book is out of sync with the master example and doesn't run properly. The book recommends adding the music functionality with this code:
```rust
use amethyst::audio::DjSystem;

let game_data = GameDataBuilder::default()
// --- snip ---
.with(
      DjSystem::new(|music: &mut Music| music.music.next()),
      "dj_system",
      &[],
);
```
The current "solution" and code in master:
```rust
use amethyst::audio::DjSystemDesc;

let game_data = GameDataBuilder::default()
// --- snip ---
.with_system_desc(
      DjSystemDesc::new(|music: &mut Music| music.music.next()),
      "dj_system",
      &[],
)
```

## Reason

So the book's code does compile, but when it gets to making the background music quieter the resource for `AudioSink` cannot be found and causes a runtime panic. [Specifically this line](https://github.com/amethyst/amethyst/blob/38f04eb5709f892d9bdaed3a23ea1c5235584663/examples/pong/audio.rs#L30). When changed to "solution" the code works as expect by playing the background music.

## Impact

Full disclosure I'm just learning Amethyst and ECS so I don't know if there would be negative impacts by this. Just sharing what I know that fixes a problem with the book.

## Additional Information

If you run the current master branch example and replace the code with the book's `DjSystem` registration you will get this error: `error: process didn't exit successfully: 'target\debug\examples\pong.exe' (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
Segmentation fault`. I feel like it's related to issue #2034.

**Comment by distransient** [comment]
This was fixed in #1981/#1999. Thanks for taking the time to post the issue when you found something wrong though! Please post an issue for anything else you notice :)
