### ISSUE TITLE
[BUG] objc 0.2.7 breaks builds

### ISSUE THREAD

**Issue by EthanYidong** [amethyst/amethyst#2046]
## Description

When using `features=["metal"]`, builds fail unless you run `cargo update -p objc --precise 0.2.6` 

## Reproduction Steps

1. amethyst new __
2. Specify metal feature in Cargo.toml
2. cargo run
## What You Expected to Happen

Build should exit successfully

## What Actually Happened

When building the metal crate, an error is thrown. (E0282)

## Screenshots and Logs

<img width="1025" alt="Screen Shot 2019-11-19 at 7 51 59 PM" src="https://user-images.githubusercontent.com/50757300/69207821-2499f400-0b06-11ea-8cb9-1a79bafd7c0c.png">

## Your Environment

1. macOS, although this bug should be platform-independent.
2. 10.14.5
3. 0.13(.2)

**Comment by EthanYidong** [comment]
To be honest, I don't think this is fixable by the amethyst team, but I would suggest adding the workaround in the getting started book.

**Comment by azriel91** [comment]
Breaking change is in `rust-objc`, which was intentional: https://github.com/SSheldon/rust-objc/issues/62. Haven't yet investigated how `amethyst` transitively uses it (or how to update / upgrade).

**Comment by EthanYidong** [comment]
The broken code is in the `metal` crate. The build runs fine without the `metal` features. Builds succeed with `empty`, but I have not tested `vulkan` yet.

**Comment by SSheldon** [comment]
Some previous discussion in #2011.

From my investigation before, it looked like:
> Getting to metal 0.16 or greater will fix the issue, but to do that it looks like you'll need gfx-backend-metal at 0.3 which means rendy at 0.4 in amethyst_rendy.

I believe this is fixed on amethyst master? Since rendy was upgraded to 0.4 in #1908. But that change hasn't yet made it into a published version of amethyst.

**Comment by azriel91** [comment]
Todo:

* [ ] Check if `master` works -- need someone with Mac
* [ ] Publish (what version?)
* [ ] Make sure `amethyst-tools` has a template for that (https://github.com/amethyst/tools/issues/99)

**Comment by HarrisonMc555** [comment]
I also ran into this issue. I just compiled against `master` and it worked.

**Comment by azriel91** [comment]
Thank you!

**Comment by ootoovak** [comment]
Using:

```
[dependencies]
amethyst = { version = "0.13.2", features = ["metal"] }
```

macOS `10.15.2`
xcode-select version `2373`

Using the:
```
cargo update -p objc --precise 0.2.6
```
Command as noted by @EthanYidong before running `cargo run` worked for me to solve the errors I was getting originally.

**Comment by distransient** [comment]
Since this is fixed on master and the appropriate issue is open for the tools repo I'm closing this.
