### ISSUE TITLE
[BUG] PrefabData derive macro bugged

### ISSUE THREAD

**Issue by EthanYidong** [amethyst/amethyst#2049]
## Description

When attempting to derive PrefabData on a Component struct, the build fails.

## Reproduction Steps

<img width="239" alt="Screen Shot 2019-11-22 at 10 46 54 PM" src="https://user-images.githubusercontent.com/50757300/69474791-03413e00-0d7a-11ea-9858-80435b4af400.png">

## What You Expected to Happen

Build should succeed

## What Actually Happened

Build failed with E0308

## Screenshots and Logs

<img width="643" alt="Screen Shot 2019-11-22 at 10 44 39 PM" src="https://user-images.githubusercontent.com/50757300/69474815-3552a000-0d7a-11ea-962c-a20c6b36940f.png">

## Your Environment

1. Operating System: macOS
2. Operating System 10.14.5
3. Version of Amethyst 0.13.2

**Comment by EthanYidong** [comment]
Sorry, I figured out the issue.

**Comment by hubrys** [comment]
In case anyone else finds this issue while trying to get prefabs to work, make sure to add `Clone` to the list of derives, or implement it yourself.
