### ISSUE TITLE
[BUG] AutoFov system and screen_ray don't work together

### ISSUE THREAD

**Issue by aforemny** [amethyst/amethyst#2055]
## Description

When using a perspective camera, the `AutoFov` system and the `screen_ray` function don't work together. After resizing the screen, the `screen_ray` function returns an incorrect ray.

## Cause of the issue

The `screen_ray` function at one points calls `Camera::as_inverse_matrix()`. The `AutoFovSystem` calls `Perspective::set_aspect`. That function updates the `Perspective`'s `matrix` field, but it does not update the `Perspective`'s `inverse_matrix` field, thus the subsequent calls to `Camera::as_inverse_matrix` do not return the correct (updated) matrix.

When changing the source code so that `inverse_matrix` field is recalculated within the `set_aspect` function, the interaction between `AutoFovSystem` and `screen_ray` is as expected.

## Reproduction Steps

Apply the following patch to the mouse_raycast example switching to a perspective camera and the AutoFov system:

```diff
diff --git a/examples/mouse_raycast/main.rs b/examples/mouse_raycast/main.rs
index 7d8374a6..0d11ac0a 100644
--- a/examples/mouse_raycast/main.rs
+++ b/examples/mouse_raycast/main.rs
@@ -25,7 +25,10 @@ use amethyst::{
         ImageFormat, RenderingBundle, Texture,
     },
     ui::{RenderUi, UiBundle, UiCreator, UiFinder, UiText},
-    utils::application_root_dir,
+    utils::{
+        auto_fov::{AutoFov, AutoFovSystem},
+        application_root_dir,
+    },
     window::ScreenDimensions,
     Application, GameData, GameDataBuilder, SimpleState, SimpleTrans, StateData, Trans,
 };
@@ -222,12 +225,13 @@ fn init_camera(world: &mut World) {
     //println!("Init camera with dimensions: {}x{}", width, height);
 
     let mut camera_transform = Transform::default();
-    camera_transform.set_translation_z(1.0);
+    camera_transform.set_translation_z(200.0);
 
     world
         .create_entity()
         .with(camera_transform)
-        .with(Camera::standard_2d(width, height))
+        .with(Camera::standard_3d(width, height))
+        .with(AutoFov::new())
         .build();
 }
 
@@ -275,6 +279,7 @@ fn main() -> amethyst::Result<()> {
                 .with_plugin(RenderUi::default())
                 .with_plugin(RenderFlat2D::default()),
         )?
+        .with(AutoFovSystem::new(), "auto_fov_system", &[])
         .with(MouseRaycastSystem, "MouseRaycastSystem", &["input_system"]);
 
     let mut game = Application::new(assets_dir, Example::default(), game_data)?;
```

Observe that the mouse raycast system still works. Resize the window and observe that the mouse raycast system does not work the same anymore. The mouse position appears to be off slightly (half to full sprite size) in the horizontal direction. The vertical direction seems to be unaffected.

## What You Expected to Happen

Using the AutoFov system, after resizing the screen, the `screen_ray` function returns a correct ray.

## What Actually Happened

Using the AutoFov system, after resizing the screen, the `screen_ray` function returns incorrect coordinates.

## Screenshots and Logs

None provided.

## Your Environment

1. NixOS
2. 19.09.1223.cb2cdab7136 (Loris)
3. 0.13.2

## Additional Context

I can neither confirm nor deny whether this bug is present for non-Perspective cameras. I hope the issue is clear from the description. If you need additional information, such as a test case please let me know and I will try to provide it.

**Comment by ishitatsuyuki** [comment]
It seems #1918 had some oversight on this. @jaynus?

**Comment by jojolepro** [comment]
Status?

**Comment by ishitatsuyuki** [comment]
waiting on @jaynus
