### ISSUE TITLE
[BUG] world_to_screen returns incorrect result

### ISSUE THREAD

**Issue by aforemny** [amethyst/amethyst#2057]
## Description

Hi, I have found that with a perspective camera and a non-trivial transform, the function `world_to_screen` returns an incorrect result.

## Cause of the issue

It seems to me that the following line in `world_to_screen`
```rust
let screen_pos =
    (camera_transform.global_matrix() * self.as_matrix()).transform_point(&world_position);
```

should really say
```rust
let screen_pos =
    (self.as_matrix() * camera_transform.global_matrix().try_inverse().unwrap()).transform_point(&world_position);
```

so that it is the inverse of the matrix `*camera_transform.global_matrix() * self.as_inverse_matrix()` used in `screen_ray`.

## Reproduction Steps

None provided.

## What You Expected to Happen

I expect that `world_to_screen` performs the inverse operation of `screen_ray`.

## What Actually Happened

The function `world_to_screen` does not perform the inverse operation of `screen_ray`.

## Screenshots and Logs

None provided.

## Your Environment

1. NixOS
2. 19.09.1223.cb2cdab7136 (Loris)
3. 0.13.2

## Additional Context
I hope this issue is clear from the described cause of this issue. If you would like me to provide a test case, please let me know!

**Comment by joonazan** [comment]
It doesn't work for me either.

A solution similar to your suggestion fixed it.

**Comment by aforemny** [comment]
The patch in #2087 fixes this issue for me.
