### ISSUE TITLE
[BUG] `amethyst_tiles::MortonEncoder2D` fails to encode/decode correctly for multiple layers.

### ISSUE THREAD

**Issue by jmeggitt** [amethyst/amethyst#2058]
## Description

`MortonEncoder2D` incorrectly encodes/decodes tile positions. This can lead to seemingly random panics when attempting to determine a tile's position on the screen. Revering a valid tile index can return a position on a non-existent layer. This issue also causes multi-layer tile maps to render incorrectly when the length and width are not equal powers of 2. This issue is compounded by the fact that `MortonEncoder2D` is currently the default encoding scheme for `TileMap`.

## Reproduction Steps

This test checks that all tiles are unique and point to the correct positions.
```rust
use amethyst::tiles::{CoordinateEncoder, MortonEncoder2D};

#[test]
pub fn test_morton2d() {
    let encoder = MortonEncoder2D::from_dimensions(50, 50, 3);

    // Test every valid coordinate
    for x in 0..50 {
        for y in 0..50 {
            for z in 0..3 {
                let value = encoder.encode(x, y, z);

                // Every valid coordinate should encode to a unique value
                assert!(value.is_some());

                let (x2, y2, z2) = encoder.decode(value.unwrap()).unwrap();

                // Every valid encoded value should decode to the original position 
                assert_eq!(x, x2);
                assert_eq!(y, y2);
                assert_eq!(z, z2);
            }
        }
    }
}
```

## What You Expected to Happen

Every valid coordinate should encode to a unique value that when decoded will return the original coordinate (The test should run without issues for any positive non-zero width, height, and layer count).

## What Actually Happened

The issue lies in how `MortonEncoder2D` stores the size of each layer. The layer size is determined by multiplication however as stated in the docs, each layer s hould have a size of `x.max(y).next_power_of_two()` squared. The perceived layer size is too low, resulting in valid x/y positions being interpreted as being from different layers.

### Example:
Lets say you have a 3x3 map with a single layer. 
 - Upon initialization, it determines that the layer size is `3 * 3 = 9`.
 - Attempting to encode the valid tile position `(1, 2, 0) -> 9`
 - Later when decoding, `9 -> (0, 0, 1)` because `9 / layer_size = 1`. This position does not exist in the tile map.

**Comment by AlveLarsson** [comment]
Hello, this issue has been marked stale or inactive.
We are currently going to go through major rewrites, please re-evaluate if this issue when 0.16 has been released. Closing this, for now, Thanks for your interest!
