### ISSUE TITLE
[BUG] NetworkBundle cause HUGE CPU usage

### ISSUE THREAD

**Issue by oOBoomberOo** [amethyst/amethyst#2060]
## Description
Whenever I include `NetworkBundle` into the game it will cause significant CPU usage. (Jump from 3% to 40%-60%).
Changing framerate strategy does not fix the issue nor does changing the max framerate to 1.

## Reproduction Steps
1. Setup a basic amethyst project
2. Include `NetworkBundle` to the game
3. Run the game

## Screenshots and Logs
With `NetworkBundle`
![With `NetworkBundle`](https://cdn.discordapp.com/attachments/476032191567233025/652494178705735710/unknown.png)
Without `NetworkBundle`
![Without `NetworkBundle`](https://cdn.discordapp.com/attachments/476032191567233025/652495203479060481/unknown.png)

## Your Environment
Tested OS: Windows 10, Linux.
Rust version: `1.39.0`
Amethyst Version: `0.13.2`

**Comment by jstnlef** [comment]
@oOBoomberOo I'm curious if you are seeing a similar issue on the master branch of amethyst. We have significantly overhauled how the networking library works and will be changing in a near future release. Might be trying out.

**Comment by oOBoomberOo** [comment]
No high CPU usage issue remain on the master branch (Have tried on both TCP and UDP)
