### ISSUE TITLE
[FEATURE MODIFICATION] Input events should be discernable from Ui Events

### ISSUE THREAD

**Issue by mrhatman** [amethyst/amethyst#2065]
# Tasks
- Separate UI events and Input events (user-defined and given by the input handler) from window events (raw keypresses, etc)

## Feature

Ui event and Input events

## Change

Currently when you click on a ui element(like a button) it triggers both a ui_event and an input_event which can be problematic.

You can currently use some workarounds in your code,  like UiTransforms position_inside function,  to help fix this, but it should be an engine feature.
## Reason

To make the common use case that clicking on a button should be discernable from a normal click.

## Impact

Depending on the method used, it could break some existing code. 
## Additional Notes

At least in the short term,  a test function like is_click_a_ui_event(input_event)  should suffice.

**Comment by distransient** [comment]
This seems reasonable to me. Would you like to make a PR for this?

**Comment by mrhatman** [comment]
I can probably write a basic is_click_a_ui_event(input_event) function but anything more is a major system rewrite I believe.

**Comment by jojolepro** [comment]
In most cases, you should be
1) not reading "window clicks" events in a State that is dedicated for ui
2) have a "toggle" (boolean) resource to enable/disable the window click inputs from your gameplay systems (and have the state change this boolean accordingly)

Do you have a use case for which this doesn't work?

**Comment by aforemny** [comment]
Hi @jojolepro, I have come across this issue with a hotbar that I have in a my game. Let's say the player character moves inside the world with left click (world click/ input event), but may select actions on the hotbar with left click as well (ui event). I did not want my character to move towards the hotbar when clicking on it. :disappointed_relieved: 

Is this a use-case that you were asking for, ie. one that cannot be implemented with 1. and 2.?

I ended up implementing a check like @mrhatman suggested and it works well. On the other hand, I was thinking about when the other case would ever be useful: having a world click pass through an input element (that is opaque, interactable, and was clicked). Are there legitimate use cases for that behavior?

**Comment by mrhatman** [comment]
I think a classic example would be a rts/sim game. You need to regularly click on both the screen and buttons and want them discernable. For example building  a unit in an rts, clicking the screen should build a unit,  clicking a button could change what unit you are building,  but when you change unit you don't want to build the old unit. 

In response to the suggestions:
1. This could work if your can separate your ui into a separate state but not all games are formatted to allow for that.  (State specific dispatcher, etc)

2. This is basically what is is PR is asking for excepted I imagined it as a function you could call on each click rather than a system that would constantly be checking.

**Comment by jojolepro** [comment]
@aforemny yes this is a valid use case. We can go forward with this issue and start proposing implementation ideas/solutions.

The use case I was proposing is one where you want to react in some way to all and any clicks, whether or not it was on the ui. For example, playing a sound effect on each click.

**Comment by bonsairobo** [comment]
FWIW, I currently have a system that sets a flag to disable/enable my camera controller on `ClickStart/ClickStop` UI events. It would probably be much simpler if I could distinguish those events in the camera code.

One option for implementing this is to create a new event type like

```
struct UiFilteredInputEvent {
    input: InputEvent,
    ui: Option<UiEvent>,
}
```

which is emitted from the `MouseUiSystem`. Then readers of the `EventChannel<UiFilteredInputEvent>` can ignore the events where `event.ui.is_some()`.

Of course this means that the `MouseUiSystem` would need to generate one of those events for every `InputEvent` that it reads from the channel. It currently doesn't even read input events, it just uses the `InputHandler`.

**Comment by CleanCut** [comment]
Yes, it's still relevant stalebot.  After https://github.com/amethyst/amethyst/pull/2414 gets closed you'll stop threatening to close things and just mark them stale like you're supposed to.

**Comment by jojolepro** [comment]
Maybe we could make it so that if the click event isn't "captured" by the ui, then the input event would be sent.
Inputs would be captured if: the click was on a ui element & at least one ui element at this position was Opaque.
