### ISSUE TITLE
[FEATURE MODIFICATION] Trans::Replace A method of changing the entire game state stack easily

### ISSUE THREAD

**Issue by mrhatman** [amethyst/amethyst#2067]
## Feature

amethyst::Trans

## Change

Add in a Trans::Replace(new_state) which removes each state on the stack ( and calls the on_stop command for each) and replaces in with new_state.

## Reason

To simplify the use case where you want to switch primary states from a pushed state. Example: you want to be able to return to the main game menu from a paused state that is pushed on top of the main game state.

## Impact

Nothing else

**Comment by distransient** [comment]
Would you be willing to write a PR for this?

**Comment by mrhatman** [comment]
The code looks easy enough. I thought of two more types to kinda complete the machine:

- Trans::NewStack(State[]) that replaces the stack with a new stack. 

- Trans::Sequence(Trans[]) the executes a series of transitions

Thoughts of these more radical one?

**Comment by azriel91** [comment]
Re: `Trans::Sequence`, there is this [`SequencerState`](https://github.com/amethyst/amethyst/blob/v0.13.2/amethyst_test/src/state/sequencer_state.rs) which is built like so:

https://github.com/amethyst/amethyst/blob/v0.13.2/amethyst_test/src/amethyst_application.rs#L177-L187

**Comment by azriel91** [comment]
Another relevant discussion is: https://github.com/amethyst/rfcs/pull/9 ([rendered](https://github.com/udoprog/rfcs/blob/state-separation/rfcs/0000-state-separation.md))

**Comment by mrhatman** [comment]
It appears that sequencer states , loads in a sequence of states that are called in order where Trans::sequence calls a sequence of transitions like [pop,pop,push(newstate)] that replaces the state below you with a new state.
