### ISSUE TITLE
[BUG] "No logger detected" when Trace logger stdout is StdoutLog::Off

### ISSUE THREAD

**Issue by mankinskin** [amethyst/amethyst#2068]
When I enable this logger
```
amethyst::start_logger(LoggerConfig {
        level_filter: LogLevelFilter::Trace,
        stdout: StdoutLog::Off,
        log_file: None,
        ..LoggerConfig::default()
    });
```
I get the warning "WARNING: No logger detected, did you forget to call `amethyst::start_logger()`?"

However when setting `stdout: Stdoutlog::Colored`, the warning disappears. This does not happen when setting any other `LogLevelFilter` to `StdoutLog::Off`.

Maybe this has some purpose, but I was certainly wondering why I was getting the warning.

**Comment by distransient** [comment]
This may be a `fern` bug since the logger is just a `fern` instance underneath.

**Comment by AlveLarsson** [comment]
Hello, this issue has been marked stale or inactive.
We are currently going to go through major rewrites, please re-evaluate if this issue when 0.16 has been released. Closing this, for now, Thanks for your interest!
