### ISSUE TITLE
[MAINTENANCE] How do I use info! and error! logging macros with amethys logger?

### ISSUE THREAD

**Issue by mankinskin** [amethyst/amethyst#2069]
# Tasks
- Improve documentation on amethyst logger
- Add section in book about logger

How do I log my own messages through the amethyst logger? The [log crate](https://docs.rs/log/0.4.8/log/index.html#macros) provides macros to log messages, however these don't seem to work with the amethyst loggers started with `amethyst::start_logger()`.
```
    amethyst::start_logger(LoggerConfig {
        level_filter: LogLevelFilter::Info,
        stdout: StdoutLog::Colored,
        log_file: None,
        ..LoggerConfig::default()
    });
    info!("Logger started.");
```
(Does not output anything)

**Comment by pikapak** [comment]
The way I got it to work was by adding the following to my _Cargo.toml_:
```
[dependencies]
#amethyst = "0.13.2"
log = "*"
```
From there, you can use `use log::{debug, error, info, warn};` and call `info!("<your text>");` at will.

**Comment by distransient** [comment]
Hello, Linus! Have you tried either lowering the level filter to Debug or raising the level of your logged message to Warn or Error?

**Comment by jakbyte** [comment]
Have you tried running it with the `RUST_LOG=debug` environment variable?

**Comment by treymo** [comment]
So I ran into this issue as well and setting the RUST_LOG environment did not help. After some research I discovered the [`AMETHYST_LOG_LEVEL_FILTER` environment variable](https://docs.amethyst.rs/stable/amethyst/fn.start_logger.html) and setting this to `debug` had the desired effect.

It's not clear to me if this Amethyst specific variable can control the logging level on a per-module basis or not like [RUST_LOG is able to](https://doc.rust-lang.org/1.0.0/log/#enabling-logging).
