### ISSUE TITLE
[FEATURE MODIFICATION] glTF Camera Import

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [amethyst/amethyst#2072]
## Feature

glTF loader

## Change

Support importing cameras from gltf files.

## Reason

The format supports it, and just like placing lights, placing cameras in the scene can be useful, especially for prototyping.

It seems odd to me that the stuff that the gltf importer matches a lot of the `BasicScenePrefab` functionality, but omits cameras for some reason.

## Impact

I don't think this impacts anything other than the gltf asset loader.

## Additional Notes

Issue #768 mentions that cameras would not be supported, but gives no rationale for the decision. That is the only relevant issue I could find in the repository.

**Comment by ColonelThirtyTwo** [comment]
Humm, now that I look, lights are also not imported, though that appears to be an extension.

My use case is taking scenes from Blender and loading them in Amethyst.

**Comment by jojolepro** [comment]
This would be a nice feature

**Comment by distransient** [comment]
@ColonelThirtyTwo Would you like to make a PR for this?

**Comment by ColonelThirtyTwo** [comment]
@distransient If I work on it, sure. I'm not currently working on it though.

**Comment by distransient** [comment]
Np. Ping here if you do begin working on it!

**Comment by Puciek** [comment]
I believe that this is now resolved?
