### ISSUE TITLE
[MAINTENANCE] amethyst_rendy::camera::Projection::perspective documented to take degrees but takes radians

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [amethyst/amethyst#2073]
## Description

The documentation comment for the `amethyst_rendy::camera::Projection::perspective` function says that the `fov` argument is in degrees, but internally it uses the built-in `f32::tan` function which takes radians. Other functions, like `Camera::standard_3d` and `Projection::perspective`, use the function with radian values too.

## Reason

Because the documentation is incorrect.

## Impact

No impact, just change one word.

## Additional Information

None

**Comment by distransient** [comment]
Would you mind writing a PR for this?
