### ISSUE TITLE
[FEATURE MODIFICATION] Accessible mesh data

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [amethyst/amethyst#2076]
# Tasks
- Keep copy of mesh data into memory (if told to do so)
- Push dirty mesh data automatically or manually to the gpu, depending on configuration.

## Feature

`MeshData` and mesh loading

## Change

Rewrite `MeshData` as a more feature-ful object that allows CPU and client code access to the mesh data.

## Reason

The `ObjLoader` and `GltfSceneFormat` load mesh data as a `MeshData`, a thin wrapper over a rendy `MeshBuilder`. As far as I can tell, there is no way to access the mesh data inside of the `MeshBuilder`\*; the only thing you can do with it is load it into a GPU structure.

Could potentially work around this by writing my own `ObjLoader` and `GltfSceneFormat` that loads into an alternate format, but this means duplicating a lot of code and loading the assets twice.

The biggest use case for accessing the mesh data is for using it as collision meshes.

\* Okay you can serde serialize it and then deserialize it into something else, but that's a dumb inefficient hack. 

## Impact

Would need a new API for `MeshData`, and the loaders that generate it would need to load into a different object. It should not be too hard to add a `to_mesh_builder` method for consumers to use though.

## Additional Notes

I might be able to work on this, but I'd like the community's feedback before I start messing with the API. Or maybe there is a way to access the mesh data that I'm just not seeing.

**Comment by ColonelThirtyTwo** [comment]
Possibly poke the rendy devs and ask if they can add some getters to the `MeshBuilder` struct, I think that would be enough.

**Comment by ColonelThirtyTwo** [comment]
So messing around with this a bit...

I think the best solution would be to add some accessors onto the `MeshBuilder` structure for reading the data it has built. Not only would that not break anything, but `MestBuilder` is very flexible with the underlying mesh representation. The flexibility comes at a cost of making reading the data somewhat complex...

So here is what I am pursuing:

* Add functionality to the `rendy::hal::format::Format` formats to read data from a section of the vertex buffer and return it as a non-raw type (ex. `Rgb32Sfloat` -> `[f32; 3]`). I currently have an extension trait on the concrete format structures in the `format` module that return a fixed type, but I think implementing the extension trait on the resulting type and passing in the format would be more flexible.
* Add an `iter_attribute` function onto `MeshBuilder` that looks up the passed in attribute in each of the bufferfs, and returns an iterator that yields each converted value, handling the buffer stride and offset.

So for getting a collision mesh, the code can use `iter_attribute` on the `"position"` attribute to get the vertex positions (since that's all it cares about). If access to more attributes is needed, the code can zip together a few of these iterators.

**Comment by ColonelThirtyTwo** [comment]
^ My amethyst/rendy#253 PR adds getter functions for the mesh data. Experimenting with it in my project.

With it, I've made a `CollisionMesh` asset that also takes a `MeshData`, so that it can be loaded from things like `ObjLoader`. However it still has to load the file twice, as far as I can tell: one to read the `Mesh` and one to read the `CollisionMesh`, both from the same `MeshData`. And I don't think there's a way to load multiple assets from the same asset data.

So that's another stumbling block. I'm not sure the best solution to that.

**Comment by jojolepro** [comment]
Not sure if this will help you, but I'm currently using a really lazy way to get the mesh data at load time here: https://github.com/amethyst/amethyst/compare/master...jojolepro:hoppinworld

I'm still not sure how to go about a more permanent solution, but I'll be following your progress! :3

**Comment by ColonelThirtyTwo** [comment]
Ended up just having two separate models.

**Comment by thorlucas** [comment]
Anyone figure out how to modify mesh data? Do I really have to delete the mesh and redraw it every frame?

**Comment by jojolepro** [comment]
not stale
