### ISSUE TITLE
[MAINTENANCE] Book - Pong Tutorial - Specs documentation link about DenseVecStorage is broken

### ISSUE THREAD

**Issue by lberrymage** [amethyst/amethyst#2077]
## Description

In the pong tutorial from the book, [pong-tutorial-02.md](https://github.com/amethyst/amethyst/blob/master/book/src/pong-tutorial/pong-tutorial-02.md#our-first-component) contains a dead link at the very end of the "Our first Component" section. The dead link is listed as "[Specs documentation](https://slide-rs.github.io/specs/05_storages.html#densevecstorage)"

## Reason

The link is dead, and thus it is useless to readers.

## Impact

No impact; a fix should be only helpful.

## Additional Information

The updated link to Specs' documentation for DenseVecStorage is [here](https://specs.amethyst.rs/docs/tutorials/05_storages.html#densevecstorage)

**Comment by distransient** [comment]
Thanks!
