### ISSUE TITLE
Add profiling mechanism

### ISSUE THREAD

**Issue by nchashch** [amethyst/amethyst#208]
It would be nice to have a mechanism for measuring performance of various bits of the engine. For example we could measure the average time it takes to run `GfxDevice::render_world`/`State::update`/`Planner::dispatch` methods inside `Application::advance_frame`.

Having this info would allow us to make performance related design decisions based on measurement. Also it would be useful for engine users optimizing their games.

**Comment by torkleyy** [comment]
I'd also like to have such a mechanism, but do you know how we could implement it?

**Comment by kvark** [comment]
Might be worth looking into WR's profiling code, starting with https://github.com/servo/webrender/pull/854

**Comment by nchashch** [comment]
Maybe add something like a `Bench` struct with `Bench::mean_render_world_time`/`Bench::mean_update_time`/`Bench::mean_dispatch_time` methods.

For example if I wanted to measure mean `update` time, I could measure the `update` time every frame (maybe using `timing::Stopwatch`) and add it to `Bench::update_time_sum`. Also I would have to store the number of frames that passed say in `Bench::num_frames`. Then I could get the mean time by computing `bench.update_time_sum/bench.num_frames`.

Also we could compute [average absolute deviation](https://en.wikipedia.org/wiki/Average_absolute_deviation) by adding `(bench.mean_update_time - measured_update_time).abs()` to `bench.update_time_deviation_sum` every frame and then dividing it by `bench.num_frames`. And then print something like `mean update time = 2.3 +- 0.5 ms` to the log.

**Comment by ebkalderon** [comment]
It would be nice to have the profiler take in a target FPS or frame time from the user, compare it to the actual FPS or frame time, and have it display a breakdown of both the target and the actual times spent on each task.
