### ISSUE TITLE
[MAINTENANCE] Bad documentation for ApplicationBuilder::new

### ISSUE THREAD

**Issue by yodaldevoid** [amethyst/amethyst#2088]
## Description

The documentation for the [`ApplicationBuilder::new`](https://docs-src.amethyst.rs/stable/amethyst/struct.ApplicationBuilder.html#method.new) method are out of date and/or incorrect.

## Reason

While it is fairly clear what the method does based on [`CoreApplication::build`](https://docs-src.amethyst.rs/stable/amethyst/struct.CoreApplication.html#method.build) (whose documentation I can only assume is correct), that is no reason to leave the documentation for `ApplicationBuilder::new` in a sorry state.

## Impact

Probably little impact beyond people getting a little confused.

**Comment by distransient** [comment]
Would you mind opening a PR to help improve this API's docs?

**Comment by yodaldevoid** [comment]
I will as soon as I have a moment to do so.
