### ISSUE TITLE
Asset management

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#209]
*This issue was created for discussing different approaches of implementing an asynchronous asset management, as already started in PR #195.*

At the moment, I've implemented an `AssetLoader` which loads assets in threads from a thread pool. After the `AssetData` is loaded, the application will process this data on the main thread (requirement by OpenGL), as long as it does not harm the performance. All this could be done in a separate state, let's call it `Loading` (although it's not limited to that).

The problem I want to discuss is **how the user should get the loaded assets back**.

I came up with the following options:

### Immediately, when submitting name and format of the asset, return a future

In code this would look something like this:

```rust
struct Loading {
    assets_future: Option<AssetFuture>,
}

struct Game; // Also implements `State`

impl State for Loading {
    fn on_start(...) {
        let cube_future = asset_loader.load(&store, "cube", Obj);
        let cone_future = asset_loader.load(&store, "cone", Obj);
        self.assets_future = Some(cube_future.join(cone_future));
        // Submit other assets ....
    }

    fn on_update(...) -> Trans {
        let f = self.assets_future.unwrap();
        match f {
            Ok(Async::Ready(x)) => {
                let basic_assets = BasicAssets { cube: x.0, cone: x.1 };
                world.add_resource(basic_assets);

                // We finished loading the assets, let's start the game
                Trans::Switch(Box::new(Game))
            },
            Ok(Async::NotReady) => Trans::None, // Let's wait until the assets have done loading
            Err(x) => panic!("Asset loading failed: {}", x),
        }
    }
}

// In the game we can now easily read the
// assets we need.
```

I think this approach is quite good and also very flexible. Probably there is a way to make it a bit nicer for the user?

**EDIT:** @vitvakatu suggested to use callbacks in order to improve ergonomics. Seems interesting, but I'm not sure how this will work out.

### Store assets in a hash map owned by `AssetLoader`

I see three problems with this approach:

* Small problem: A bit more overhead because of hashing
* Medium problem: Somehow ugly because you don't really know when they're finished
* BIG problem: Error handling

Well, there are two approaches I experimented with concerning error handling:

#### Store the result

:-1: You had to check every time you want to use the asset if it was successfully loaded.

#### Have error handlers

I'm not sure how nice this would be. Some issues include:

* How many error handlers should we have (1 / multiple)?
* How to handle responsibilities?
* Panics in a thread of the thread pool... probably a bad idea ;)
* No easy state transition depending on the result

---

I hope I could explain the important bits concerning asset management, if not, feel free to ask.
Do you know any alternatives or would you disagree with using the future based solution (the first one)?
Also, if we decide for option 1, is it ergonomic enough or should we provide an optional wrapper to make it easier?

**Comment by vitvakatu** [comment]
I prefer first approach, but with slightly improvement.
For me, ideal API looks like:
```rust
let loader = Loader::new(vec!["cube", "sphere", "cone"]);
loader.on_success(|| { Trans::Switch(Box::new(Game)) });
loader.on_failure(|| { panic!("Error while loading"); });
loader.proceed();
```

**Comment by minecrawler** [comment]
How about returning an Amethyst-managed component which can be added to an entity? Amethyst would then make sure that the asset is sent correctly to the GPU once it is loaded. I do not think that the user has to know when a specific asset is done loading - imho it's a lot more interesting to know when Amethyst is done loading all required assets and can use them. For that purpose, one could use an event, which is called with a Result. You either get an Ok() or an Err() with a description which asset could not be loaded (and why; not found? no permissions? unsupported format? malformatted?)

If that is not viable, I would rather go for Futures. I do not have quite that much knowledge about Rust, but I know that in JS, there is something we call "Callback-Hell", which is solved by cleverly placed Promises, which are similar to Futures.

**Comment by torkleyy** [comment]
@vitvakatu 

> I prefer first approach, but with slightly improvement.
> For me, ideal API looks like:
>
> ```rust
> let loader = Loader::new(vec!["cube", "sphere", "cone"]);
> loader.on_success(|| { Trans::Switch(Box::new(Game)) });
> loader.on_failure(|| { panic!("Error while loading"); });
> loader.proceed();
> ```

Looks nice, but there are many missing points:

* Which type of asset is, for example "sphere"?
* Which format is it? Do you want the format to be dynamically recognized and used?
* Where does `loader` store the assets in the end?
* Can you only react on a loaded asset with a state transition? How would you load assets on the fly then?
* How to handle a case where handling the error does not mean to `panic`?
* What does `loader.proceed()` do?
* How do you want to implement such an API? Where are the callbacks called exactly (which thread)? Where do you call the above methods?

I'd be happy to provide a simple but general purpose API, but I don't want to limit the asset loading because we don't want another rework of the asset management.

---

@minecrawler 

> How about returning an Amethyst-managed component which can be added to an entity? Amethyst would then make sure that the asset is sent correctly to the GPU once it is loaded. I do not think that the user has to know when a specific asset is done loading - imho it's a lot more interesting to know when Amethyst is done loading all required assets and can use them. For that purpose, one could use an event, which is called with a Result. You either get an Ok() or an Err() with a description which asset could not be loaded (and why; not found? no permissions? unsupported format? malformatted?)
>
> If that is not viable, I would rather go for Futures. I do not have quite that much knowledge about Rust, but I know that in JS, there is something we call "Callback-Hell", which is solved by cleverly placed Promises, which are similar to Futures.

If I understood correctly, you are basically suggesting two points here:

**1) Asset manager should return a component when submitting an asset**

I'm sorry but I don't think this is possible, because what would you do if you get to the point where you want to render that asset? Do you want to wait and freeze the game? If the user does not know about asynchronous asset loading, how should he handle things like loading screens or on the fly loading? Additionally, not every asset is a component (AFAIK no asset is a component atm).

**2) Use events to inform user**

I'm not sure if there is a semantic difference between events and callbacks, but you gave me an idea:

Events could be realized by having another method in `State`, which would also allow for good flexibility. Not sure how you would manage it, though. Do you want to have an event triggered as soon as multiple assets were loaded? And how would you go about the types of assets?

**Comment by vitvakatu** [comment]
@torkleyy my example wasn't an example actually :smile: 
I just shown the main feature - using callbacks to define behavior in case of successful loading and in case of failure. Defining `update` method seems redundant for me, because it will  be the same in most situations. 
IMO, user should have an opportunity to load resources in three steps:
1. Specify the resources (filename, path, type, storage, etc)
2. Specify callbacks
3. Start loading of resources (`proceed` method in my code)

**Comment by torkleyy** [comment]
@vitvakatu I'm still very unsure of how to implement it, because, for example, assets do have different types. Do you want to provide a callback for every asset, every type? Or just want to have the callback called if every asset could be loaded successfully? That wouldn't be flexible enough, for example in a multi-player game where you retrieve assets from the server. Additionally, how should the assets be handled by the callback? Just doing a transition isn't really enough or do you want some kind of hash map?

Also, could you please answer the other questions above because I don't know how to solve them.

**Comment by vitvakatu** [comment]
Well, let's start from the beginning.

> Which type of asset is, for example "sphere"?
Which format is it? Do you want the format to be dynamically recognized and used?
Where does loader store the assets in the end?

The same method as in your code. 
```rust
let cube_future = asset_loader.load(&store, "cube", Obj);
```
> Can you only react on a loaded asset with a state transition? How would you load assets on the fly then?
How to handle a case where handling the error does not mean to panic?
How do you want to implement such an API? Where are the callbacks called exactly (which thread)? 

My proposal is to avoid defining `impl State for Loading` manually.
I imagine something like this somewhere in engine internals: 
```rust
impl State for Loading {
...
fn on_update(...) -> Trans {
        let f = self.assets_future.unwrap();
        match f {
            Ok(Async::Ready(x)) => {
                user_callback_success(x);
            },
            Ok(Async::NotReady) => Trans::None, // Let's wait until the assets have done loading
            Err(x) => user_callback_failure(x);
        }
    }
}
```

> Where do you call the above methods?

In any place, for example in `start` method of game State.

Anyway, your initial proposal will be fine too. I just want simplification for user, not rewriting the whole thing. If it's impossible - let it be.

**Comment by torkleyy** [comment]
@vitvakatu 

Okay, so this is essentially a new proposal. If you just want this simplification, that is possible with the future-powered design.

**Comment by torkleyy** [comment]
@vitvakatu
@minecrawler

Thanks for your feedback! I'm waiting for @ebkalderon and other members to add some thoughts and then I'm going to implement the future based solution (if there are no concerns).

**Comment by ebkalderon** [comment]
@torkleyy @vitvakatu Great ideas all round! Overall the futures approach looks very appealing to me.

Is it possible to have a single asset manager future to be stored in-engine and passed in through the `on_start()` method for each state so the user can select which assets they want to be available during its run? Needed assets that have already been loaded will stick around, assets that aren't loaded yet will be loaded and cached, and unnecessary assets will be silently dropped.

**Comment by torkleyy** [comment]
@ebkalderon Thanks for your feedback!

> and unnecessary assets will be silently dropped

I'm not sure if that wouldn't be a performance problem. If I understood correctly, a state change would be pretty expensive then, because if unused assets are just dropped, the next state had to load it again.

Another thing that just came to my mind is to use a `HashMap<(TypeId, String), AssetFuture>`, however there is again the problem that you can never be sure if the asset was already loaded and you had to do this check every time.

I'm not sure how to make it more convenient to use, though.

**Comment by ebkalderon** [comment]
Yes, state switches are very expensive. In contrast, state pushes are cheap since they don't unload the assets of the state immediately below it.

**Comment by ebkalderon** [comment]
I would also like to expand on @vitvakatu's API example. I think it would be nice to have a macro similar to `try!` which immediately returns a `Trans::None` if the assets haven't been loaded yet. That would simplify the example code to this:

```rust
// Macro
impl State for Loading {
    ...
    fn on_update(&mut self, game: &mut Game) -> Trans {
        let assets = try_state!(game.assets.poll())
            .or_else(| e | user_callback_failure(e));
        ...
    }
}

// Macro without `or_else()`
impl State for Loading {
    ...
    fn on_update(&mut self, game: &mut Game) -> Trans {
        let res = try_state!(game.assets.poll());
        let assets = match res {
            Ok(a) => a,
            Err(e) => user_callback_failure(e),
        };
        ...
    }
}

// Fully expanded macro
impl State for Loading {
    ...
    fn on_update(&mut self, game: &mut Game) -> Trans {
        let res = game.assets.poll();
        let assets = match res {
            Ok(Async::Ready(a)) => a,
            Ok(Async::NotReady) => return Trans::None,
            Err(e) => user_callback_failure(e),
        };
        ...
    }
}
```

As a bonus, if rust-lang/rfcs#1859 gets merged, we could replace the macro with this:

```rust
// Macro with `?` syntactic sugar
impl State for Loading {
    ...
    fn on_update(&mut self, game: &mut Game) -> Trans {
        let assets = game.assets.poll()?
            .or_else(| e | user_callback_failure(e));
        ...
    }
}
```

**Comment by torkleyy** [comment]
@ebkalderon I like the idea with the `try_state` macro, but I don't think that coupling the assets with a state is a very good idea, because it wouldn't make it very flexible.

> Assets for the first state are loaded immediately.

> Otherwise, load them up

How would that work out? If these assets weren't loaded yet, the game will freeze.

I think that I can just implement it with futures and `try_state!`, and we can still implement simple situations for the user on top of that after this PR.

I think it is good to have the option to couple some assets with the state, but I don't think it should be a requirement.

**Comment by torkleyy** [comment]
After experimenting with this, I realized

* that there is no nice way to implement it
* it is not really convenient for the user
* it has unnecessary overhead

That's why I came to a different, ergonomics-focused idea:

## Background

We want to load assets, of course. And the idea so far was to load an asset and somewhere in the future, it's finished. Seems very reasonable; however, you can see that very often you don't want just one asset and you are not even interested in a single one having finished. Instead, you want a group of asset to be loaded and you can proceed work or do something with these assets as soon as they were loaded.

## The idea

The set of asset is essentially just a plain struct:

```rust
struct Level1Assets {
    wall: Texture,
    house: Mesh,
    suzanne: Mesh,
}
```

But we need to instruct the `AssetLoader` how to load our assets. Let's define our `AssetSet` trait:

```rust
trait AssetSet {
    fn submit(&self, loader: &mut AssetLoader);
```

This method just registers all the assets which should be loaded.

```rust
    fn next_asset(&self) -> Option<(TypeId, &str)>;
```

Okay, so every time the `AssetLoader` did one cycle of asset loading, we'll check `next_asset`. Next asset will essentially tell us what is required for the set of assets. Then, the asset loader should check if this asset was loaded. If so, we want to

```rust
    fn set(&mut self, id: (TypeId, &str), asset: Box<Any>);
```

the asset. As long as we didn't `set()` the asset, `next_asset` is guaranteed to return the same id. A `None` means all assets were registered in the set and we can happily inform the user. How do we do this? First of all, let's complete our trait:

```rust
    fn name(&self) -> &str;
}
```

To answer this, let's look at the most common use case:

```rust
struct LoadingState;

...
    if all_assets_loaded {
        Trans::Switch(Box::new(Level1::new()))
    }
...

```

So we want to inform the user... but it often involves a state transition. Well, we do already have something like that:

```rust
    /// Executed on every frame before updating, for use in reacting to events.
    fn handle_events(&mut self, events: &[WindowEvent], engine: &mut Engine) -> Trans {
        Trans::None
    }
```

I would really like to have a more generic event system. If you think that's good, let's open a new issue!

If it's implemented with events in `State`, the user can just return a state transition when the right set was loaded and the new state can use the assets (for example by registering them in the `World`).

## This doesn't really look convenient for the user

Yes, you are right. Why should the user implement a trait just for doing some basic asset loading?

Let's let Rust help us!

```rust
asset_sets! {
    set Level1Assets {
        wall: Texture = ("wall", Png),
        house: Mesh = ("house", Obj),
        suzanne: Mesh = ("suzanne", Obj),
    }
}
```

This will create a struct `Level1Assets` and implement `AssetSet`. The struct will also have a construct which takes an `AssetStore`.

## Asset freeing

One thing I'm not too sure about is asset freeing. The most flexible approach is probably something like

```rust
loader.keep_assets(|x| x.0 == "suzanne");
```

together with another method

```rust
loader.keep_sets(&[level1, level2, main_menu]);
```

What do you think about this?

**Comment by minecrawler** [comment]
Sounds like a good idea to me. `build.rs` might be used to build the structs from asset directories (useful for any game big enough to actually profit from the asset-bundling feature) and I would welcome a sample-script to be available for that. It might for instance check if there are `level0`, `level1`, `level2`, etc. directories in the resources folder and generate appropriate structs for them which can be accessed at runtime. Then you could add a getter method to the `AssetSet` , like `pub fn get_asset(&self, name: &str)` or similar. I do not know if we are still capable of doing good error detection that way with the regular rust tools, and I am not a fan of names, since they imply string comparisons or hashmap calculations, but I hope you get the idea!

**Comment by torkleyy** [comment]
@minecrawler 

> build.rs might be used to build the structs from asset directories (useful for any game big enough to actually profit from the asset-bundling feature) and I would welcome a sample-script to be available for that. It might for instance check if there are level0, level1, level2, etc. directories in the resources folder and generate appropriate structs for them which can be accessed at runtime.

Yes, I planned something similar with *scene files*.

> Then you could add a getter method to the AssetSet , like pub fn get_asset(&self, name: &str) or similar. I do not know if we are still capable of doing good error detection that way with the regular rust tools, and I am not a fan of names, since they imply string comparisons or hashmap calculations, but I hope you get the idea!

I'm not really sure how to do that. String comparisons wouldn't really solve many problems (then I wouldn't have to fill in the sets but just access `AssetLoader`s `HashMap`), but on the other side, the way I planned - using trait objects and down-casting - isn't the nicest one.

@ebkalderon @vitvakatu what do you think about the new proposal?

**Comment by vitvakatu** [comment]
*Unfortunately I was busy with work last week, so I'm sorry for late answer.*
IMO, your proposal is fairly good, it combine enough simplicity for user and flexibility (especially that idea with macros)
Talking about informing user... am I right, you're going to force user to define new method just like `handle events`?
It would be great if you give us small, but enough example of this system, just to make sure that I understand you in the right way.

**Comment by torkleyy** [comment]
@vitvakatu Thanks for your comment!

> It would be great if you give us an example of the events handling

How to do this exactly would be an issue I'd open if this proposal is accepted.

Assuming there would be one method for just the assets, it would be something like this:

```rust
fn on_asset_set_finished(engine: Engine, set: Box<AssetSet>) {
    if set.name() == "common" {
        let common = set.downcast::<CommonAssetSet>().unwrap();
        engine.world.add_resource(common);
    }
}
```

**Comment by vitvakatu** [comment]
@torkleyy Well, I see. We need more investigation of this stuff. What if user has a dozens of asset sets? Will user need `if` expression for each one?
Let's ask @ebkalderon about this proposal and yep, we need to think about informing user.
Long story short, I like it. It's better than current asset system anyway.

**Comment by derekdreery** [comment]
My 2 cents

I think using macros is a great idea. We could do something like

```rust
register_asset_locs!(
    ("some/probably/relative/directory" = "prefix")
    ...
);
```
Where `= "prefix"` is optional and allows namespacing of asset directories, preventing naming conflicts.

Then assets could be loaded

```rust
register_asset_set!(
    SetName {
        resource_name: ResourceType = "resource/location"
        ...
    )
);
```

which could probably use custom-derive to be ergonomic.

This would give `SetName` as a struct and maybe a `load` method on it that returns a future, complete when all resources are loaded.

I would push using futures over callbacks because the futures crate is a key dependency of tokio, and this is being worked on by the core rust team, so most/all seasoned rust developers will understand it.

The one limitation of futures is that it doesn't supply any information with `NotReady`. It would be good to parameterize this with some type so progress information could be returned. E.g.

```rust
trait AsyncWithProgress<T, P> {
    Ready<T>
    NotReady<P>
}
```

with some alternative future implementation on top to make use of this.

**Comment by torkleyy** [comment]
@derekekdreery I already described a rough design in a blog post, which you can find on https://torkleyy.github.io

It doesn't match my local work 100%, but it should give you a rough overview.

**Comment by Xaeroxe** [comment]
@torkleyy's asset management was merged so I'm going to go ahead and close this.  If anyone protests please re-open it.

**Comment by minecrawler** [comment]
@Xaeroxe What about #52 ?

**Comment by Xaeroxe** [comment]
@minecrawler That one seems to do with integrating the asset system and the renderer, which hasn't been done yet.
