### ISSUE TITLE
[MAINTENANCE] Update Nalgebra 0.18.1 -> 0.19.0

### ISSUE THREAD

**Issue by jmwielandt** [amethyst/amethyst#2090]
## Description

Now at cargo.toml:
```toml
nalgebra = "0.18.1"
```

Future:

```toml
nalgebra = "0.19.0"
```

## Reason

Integration problems with ncollide2d, that have an updated nalgebra version as dependency.

## Impact

Do you think this change will have a negative impact on anything else? Neither! Updated dependencies will only benefit everyone, for example, reducing compile times avoiding to compile multiple versions of the same library.

**Comment by distransient** [comment]
Already done :) https://github.com/amethyst/amethyst/pull/2025

This will be in the next release which is coming soon.
