### ISSUE TITLE
[MAINTENANCE] Getting started/amethyst new to mention how to setup graphics backedn

### ISSUE THREAD

**Issue by Puciek** [amethyst/amethyst#2092]
## Description

Change getting-started to explain how to setup and decide graphical engine for your newly started project.

Additionally, I think it would also be awesome if `amethyst new` could detect and set it, based on user OS. I am not sure how feasible it is.

## Reason

As it is neither getting-started or `amethyst new` mention about settings the graphics backend, leading to quite a few confusing people arriving on discord, unable to start their very first project.  I think that's a not great welcome experience, and should be improved. In the end, there is only one chance at first impressions ;).

## Impact

I can't see how it will have any but positive impact on new users.

**Comment by 0x6273** [comment]
Maybe an `amethyst run` command that acts like an alias to `cargo run`, but sets the appropriate backend feature?

**Comment by jojolepro** [comment]
it is documented here: https://book.amethyst.rs/book/stable/pong-tutorial/pong-tutorial-01
