### ISSUE TITLE
[NEW FEATURE] Ability to use rendy's ImageView as UiWidget

### ISSUE THREAD

**Issue by mvlabat** [amethyst/amethyst#2093]
# Tasks
- Add ability to have a texture handle in the ui

## What problem does this solve? What need does it fill?
It would be nice to have a way to render an image generated with a shader as a UI element.

## Describe the solution you'd like
I believe we could provide another variant for `UiImageLoadPrefab` or `TexturePrefab` containing a handle of `ImageView`.

**Comment by mrhatman** [comment]
Initial thoughts,  

This could potentially be fairly difficult/require an experienced dev to do as the previous shader that makes the ImageView would need to be a dependency of the ui pass/plugin. 

This probably can't be done completely as a prefab due to that fact. You could create it via prefab but add  in the handle later in code.

Do you have a specific use case that might have an easier solution?

**Comment by mvlabat** [comment]
I initially imagined it the way that a user would implement their own render plugin, creating `ImageView` and drawing into it with a custom shader. And in order to pass `ImageView` to UI entity, a user would save its handle to a resource and then use it in the code where UI entities are created.

The only workaround I imagine is to render such images outside the UI system, but such solution seems to be really ugly and with its own limitations. For instance, it would be a real pain to make it aligned with other UI elements' transforms.

I believe this feature is something worth doing, as it would very much contribute to Amethyst UI being flexible and powerful.

**Comment by mrhatman** [comment]
I agree that this is something worth doing.

I think a system where you have a custom renderer plugin that generates an image of some type and then that image can be passed to future plugins (like ui, and even to use as Sprite/ mesh textures) is something that is needed.

**Comment by imjasonmiller** [comment]
Would this make it possible (or perhaps easier) to use a cropped and blurred part of the rendered elements behind the `UiWidget` as a background? It was something I wanted to look into with Amethyst as a beginner.

**Comment by mvlabat** [comment]
Still needed
