### ISSUE TITLE
[FEATURE MODIFICATION] UI documentation

### ISSUE THREAD

**Issue by bonsairobo** [amethyst/amethyst#2094]
## Feature

amethyst_ui and the Amethyst Book

## Change

Add a chapter in the Amethyst Book about the UI code. Should include things like:

- what are the main components for UI entities?
- how do `UiTransform`s differ from `Transforms`
- how does the `Widgets` resource work?
- when should I use the `UiFinder` instead of `Widgets` and vice versa?
- how do I find my widgets?
- how can I define new `Widget`s?
- how do I create new widgets dynamically (not using a prefab)?
- how is the `Widget` entity hierarchy organized?
- how can I animate UI entities?
- what kind of patterns make UI workflows and management easier?

## Reason

The best way to understand the UI code right now is to read it. It's a lot of code, and it takes significant effort to understand use cases and design decisions. It would be better if users could read a chapter that describes the design of the UI code with annotated examples.

## Impact

Users would be able to understand the UI code much more quickly, and it would probably prevent a lot of questions from making it to the Discord #help channel.

**Comment by mrhatman** [comment]
A ui prefab reference would be great as well.

**Comment by ab0v3g4me** [comment]
This part of the documentation should be very high priority. I don't think we have examples of dynamically created widgets, nor how to find them.

**Comment by CleanCut** [comment]
Stale bot is configured [_not_ to close issues](https://github.com/amethyst/amethyst/blob/master/.github/stale.yml#L13).  I'm trying to figure out why it is closing them anyway.

**Comment by CleanCut** [comment]
Fixed stalebot in #2414 

Does #2311 (and subsequent tweaks) resolve this issue?

**Comment by CleanCut** [comment]
I think this is resolved. Please feel free to reopen if I missed something.
