### ISSUE TITLE
[NEW FEATURE] Add OpenGL backend

### ISSUE THREAD

**Issue by matt2xu** [amethyst/amethyst#2097]
## Description

When trying to build an example, there is no "OpenGL backend" feature. I see that there is a gfx-backend-gl in gfx-rs, so I was expecting that Amethyst and Rendy would support it.

## What problem does this solve? What need does it fill?
Add an OpenGL backend, so people without Vulkan support can still develop with Amethyst (or even ship games using OpenGL as a backend).

## Describe the solution you'd like
I'd like to see an OpenGL backend :)
I'm willing to contribute code for this.

## Describe alternatives you've considered
Keep using Rust + Amethyst and buy another laptop, use OpenGL directly, switch to JavaScript and use WebGL.

**Comment by OvermindDL1** [comment]
Yeah I need an OGL backend to be able to run amethyst programs at all, no vulkan here on an old AMD card (CYPRESS, supports up to OGL 4.3) and it's very annoying to have others test things for me...  ^.^;

**Comment by OvermindDL1** [comment]
It seems gfx-hal already supports OGL fine.  Does rendy support OGL fine?  What's needed to bring it to amethyst?  Where is all the existing work on it already and what's still lacking?  I might be to a point soon that I might be able to poke on it.

**Comment by matt2xu** [comment]
Hmm so there is actually an open PR adding OpenGL/WebGL backend: #1877 
It looks like it depends on #2040 being merged first, maybe it's not too far off!

**Comment by OvermindDL1** [comment]
Ahh, so we are still waiting on the updated rendy, that explains why the logging of rendy in current amethyst is so *so* very noisy.  ^.^;

**Comment by jack-javana** [comment]
I also have a video card without vulkan api
But want to learn Amethyst

**Comment by pheki** [comment]
Actually, this is more like bringing OpenGL back, it used to work and as was stated in the 0.11 changelog:
> -  OpenGL support temporarily dropped, Vulkan and Metal support added.

**Comment by matt2xu** [comment]
It looks like this is being addressed as part of the [WASM project](https://github.com/amethyst/amethyst/projects/20) so I think we can close this particular issue.

**Comment by pheki** [comment]
@matt2xu I don't see any issue there tracking the OpenGL backend, so I personally don't think this should be closed. (but maybe it could be moved to the WASM project?)

**Comment by buxx** [comment]
On my 3 different computer, no one can run amethyst because of no vulkan support :( :+1: for OpenGL support.

**Comment by jojolepro** [comment]
there are plans to allow switching various other renderers, including wgpu. those are longer projects and will be listed under the projects tab when we get there :)

**Comment by 94praneeth** [comment]
I have a issue with amethyst, opening simple window on Ivy Bridge Intel GPU without complete vulkan support. Just wanted to try putting **OpenGL** in _"Cargo.toml"_ and ran hoping to see if it works. And now i'm here. 😂
Guess i'm gonna have to buy new PC or try another game engine.
❤️️ Love to see OpenGL support.

**Comment by maroider** [comment]
Sorry to be the bearer of bad (old-ish) news, but the Amethyst engine isn't actively developed any more.

See <https://amethyst.rs/posts/amethyst--starting-fresh>
