### ISSUE TITLE
Two different DisplayConfig structs

### ISSUE THREAD

**Issue by bjorn3** [amethyst/amethyst#210]
`amethyst::gfx_device::DisplayConfig` is not considered to be equal to `amethyst_config::DisplayConfig`

**Comment by Aceeri** [comment]
`amethyst_config` is being deprecated by https://github.com/amethyst/amethyst/pull/152 so this isn't too much of an issue.

**Comment by ebkalderon** [comment]
@bjorn3 Thank you for bringing this to our attention! But given that `amethyst_config` is going to be replaced and the `gfx_device` module will probably disappear entirely in the near future by #233, I think we can safely close this issue for now.
