### ISSUE TITLE
[MAINTENANCE] Book - Pong Tutorial - Unused world variable in main.rs

### ISSUE THREAD

**Issue by misabiko** [amethyst/amethyst#2100]
## Description

Removing the statement `let mut world = World::new();` from `main.rs` in the Pong tutorial.

## Reason

From [section 4.1](https://book.amethyst.rs/master/pong-tutorial/pong-tutorial-01.html#creating-an-application), the Pong tutorial tells us to create a world in the main function, however it never uses that variable. I later found out the world is already created in `Application::new()`.

## Additional Information

I followed the tutorial with version 0.13.2, and removing the line didn't cause any issue.
I've only started learning Rust and Amethyst yesterday, so I might be missing a reason to explicitly create a separate World in advance and leaving it throughout `main` 's scope.

**Comment by mrhatman** [comment]
This is no longer in the example, so it should be removed
