### ISSUE TITLE
[BUG] Very high CPU usage on AMD Ryzen Threadripper (NUMA-related?)

### ISSUE THREAD

**Issue by dflemstr** [amethyst/amethyst#2102]
## Description

Any amethyst application I have tried uses almost exactly 50% CPU (50% utilization of each 32 cores/64 threads) on my system running an AMD Ryzen Threadripper 3970x CPU.

In this bug report I will use the `tiles` example as an arbitrary nontrivial app, but this happens even with an empty project generated by the quickstart template.

## Reproduction Steps

1. Add this to `Cargo.toml` in the `amethyst` root:
    ```
    [profile.release]
    codegen-units = 1
    debug = true
    lto = true
    ```
2. Run `cargo run --example tiles --release --features tiles,vulkan,no-slow-safety-checks`
3. Observe CPU usage
5. `echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid`
6. `perf record -F 999 -a -g --call-graph=dwarf cargo run --example tiles --release --features tiles,vulkan,no-slow-safety-checks`.
7. Wait for 20 seconds, scroll around a bit in the app in the meantime and observe the CPU usage, then close the app like usual.
5. `perf script | stackcollapse-perf | grep tiles | flamegraph > flamegraph.svg`

## What You Expected to Happen

The application starts quickly and uses very little CPU.

## What Actually Happened

The application takes a few seconds to start, and uses almost exactly 50% of all available CPUs according to tools like `htop` etc. (i.e. 50% of every CPU, not 100% usage on some CPUs and 0% on others or something similar).

## Screenshots and Logs

Unfortunately I can't attach an SVG file, so here is a screenshot of a captured flamegraph, please comment if you want zoomed in/filtered versions:

![flamegraph](https://user-images.githubusercontent.com/56029/72762719-f0fc4880-3be0-11ea-87f0-bd817c5e9680.png)

`amethyst` logs are nothing special:

```
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.13.2
[INFO][amethyst::app] Platform: x86_64-unknown-linux-gnu
[INFO][amethyst::app] Amethyst git commit: 37df46b807699715551f5a20a1c49349a626c4ce
[INFO][amethyst::app] Rustc version: 1.40.0 Stable
[INFO][amethyst::app] Rustc git commit: 73528e339aae0f17a15ffa49a8ac608f50c6cf14
[INFO][winit::platform::platform::x11::window] Guessed window DPI factor: 1
[WARN][gfx_backend_vulkan] Unable to find extension: VK_KHR_wayland_surface
[INFO][amethyst::app] Engine is shutting down
```

## Your Environment

1. Arch Linux running kernel `Linux 5.4.13-arch1-1 #1 SMP PREEMPT Fri, 17 Jan 2020 23:09:54 +0000 x86_64 GNU/Linux`
2. X.Org (as opposed to wayland, which is not yet well supported with nVidia proprietary driver)
3. nVidia driver 440.44 
4. CPU: AMD® Ryzen Threadripper 3970x
5. GPU: GeForce RTX 2080 SUPER/PCIe/SSE2
6. Memory: 64GiB low-latency DDR4
7. Amethyst 37df46b807699715551f5a20a1c49349a626c4ce

**Comment by ishitatsuyuki** [comment]
this is https://github.com/rayon-rs/rayon/issues/394.
