### ISSUE TITLE
[NEW FEATURE] Multi-pass rendering example 

### ISSUE THREAD

**Issue by mrhatman** [amethyst/amethyst#2105]
# Tasks
- Create example with multiple rendering passes

## Description

An example of how to preform a multipass effect like bloom or gaussian blur.

## What problem does this solve? What need does it fill?

We currently have  a robust and complex renderer and a useful plugin system but they are hard to understand for non Trivial cases. 

## Describe the solution you'd like

An example that leverages as much from the plugun system as possible.  For example taking an basic 3d scene that uses RenderFlat3D to draw and then we can create a custom plugin/pass that could take that output and perform an effect (like bloom or blur).

## Describe alternatives you've considered
I have consulted the community via discord for examples and  I have searched online but I have not found much specific to amethyst or rendy that I could understand. 

## Additional context
I realize that how I envision this might not currently be possible (ie with the plugin system) and would be fine with a seperate multipass effect plugin example.

**Comment by CleanCut** [comment]
Stale bot is configured [_not_ to close issues](https://github.com/amethyst/amethyst/blob/master/.github/stale.yml#L13).  I'm trying to figure out why it is closing them anyway.

**Comment by mrhatman** [comment]
Thanks, I am currently working to implement this issue but I am running into issues.

Source:
https://github.com/mrhatman/amethyst/tree/multipass/examples/multipass

Errors:
https://pastebin.com/hjQgAYEy
