### ISSUE TITLE
[NEW FEATURE] Debug grid component

### ISSUE THREAD

**Issue by Puciek** [amethyst/amethyst#2109]
## Description

The idea is relatively simple - to implement a "debug grid" which will be easily added to new and existing amethyst projects and will draw a grid onto the display.

This is barely in its infancy as it is, and I am more than happy to hear any early feedback, feature suggestions etc :).

## What problem does this solve? What need does it fill?

This should help debug all sorts of problems, for example, "Where is my Object? I know it's supposed X/Y/Z, but cannot see it, am I looking at the right place?" would be much simpler to resolve with the grid on as user would know what range of coordinates he is looking at. Similarily that adds a visual component to making sure transformations and all other coordinates-related systems are working correctly.

## Describe the solution you'd like

That's still WIP, as I'm barely starting, but here are some points from discord chat:

* it needs to support different grid scales and axis
* uses "debug grid" component that stores grid unit dimensions (configurable) and choice of 2d or 3d plane via enum
* A debug pass uses the components entity transform (rotation and position) for origin and rotation
* Very easy to configure and use, should just work once installed and attached

For example: in my case, it's just drawing an overlay for anwthyst_tiles, so I'd want to add a component to my TileMap entity configured to match my Sprite dimensions 

(massive thanks to @jaynus for those pointers)

## Describe alternatives you've considered
I've considered writing a simple 2d grid matching my project but doing this right seems like a lot more fun, and I think would be a welcome addition.

**Comment by CleanCut** [comment]
Stale bot is configured [_not_ to close issues](https://github.com/amethyst/amethyst/blob/master/.github/stale.yml#L13).  I'm trying to figure out why it is closing them anyway.

**Comment by jojolepro** [comment]
We now have the DebugLines pass. Feel free to add the features you need :)
