### ISSUE TITLE
[BUG] docs.amethyst.rs is down

### ISSUE THREAD

**Issue by kaoet** [amethyst/amethyst#2116]
Visit https://docs.amethyst.rs/stable/amethyst/. It says `404 page not found`.

**Comment by Kugge** [comment]
You still can found docs for 0.13.0 here :
https://docs.rs/amethyst/0.13.0/amethyst/
And here's the logs about the error : 
https://docs.rs/crate/amethyst/0.14.0/builds/217217

**Comment by azriel91** [comment]
@happenslol has fixed it (thank you :bowing_man:)!
