### ISSUE TITLE
[BUG] BindingTypes not implemented for StringBindings 

### ISSUE THREAD

**Issue by ab0v3g4me** [amethyst/amethyst#2119]
## Description
I'm trying to add this plugin ```RenderImgui::<amethyst::input::StringBindings>::default()``` but i get two errors where one follows the other. The compiler complains that the StringBindings does not implement BindingTypes, and the latter is that the default() doesn't exist for such type (StringBindings). Now this worked for the previous version of amethyst.

Obviously this is implemented ?
https://github.com/amethyst/amethyst/blob/95903958bbf4f48c84d68450288fde015459510f/amethyst_input/src/bindings.rs#L79-L82

Not sure if i had to open this issue on the `amethyst_imgui` repository.

**Comment by saucesaft** [comment]
I have this problem too.

**Comment by ab0v3g4me** [comment]
Seems to be working for me as of 0.6.1.
