### ISSUE TITLE
[MAINTENANCE] Missing implementation of `DataDispose` for `CustomGameData` in the book

### ISSUE THREAD

**Issue by ab0v3g4me** [amethyst/amethyst#2120]
I was just creating a `CustomGameData` for my game according to the book, and it complained that the trait `DataDispose` is not implemented for it. Since i didn't find it there i assume it was not added, or one of the latter versions changed something.

Here's the part of the book with [controlling system execution](https://book.amethyst.rs/stable/controlling_system_execution/custom_game_data.html).

**Comment by azriel91** [comment]
Fixed in #2121.
