### ISSUE TITLE
[FEATURE MODIFICATION] AutoFov is unnecessarily complex

### ISSUE THREAD

**Issue by joonazan** [amethyst/amethyst#2123]
## Feature

AutoFov has `max_fovx`, which is based on the incorrect assumption that Fov would reach over 180 degrees at some point. (see https://github.com/amethyst/amethyst/issues/1193#issuecomment-449657666)

One can think of a game window as a literal window. If the window is made wider, you see more, but you'll only see 180 degrees when the window is infinitely wide.

## Change

AutoFov should have no configuration at all, or a single float to indicate if the system should optimize vertical fov or the horizontal fov. (for example 0.0 for horizontal kept constant and 1.0 for vertical kept constant and 0.5 for a balance)

## Reason

Less code and documentation to maintain, trivial to use, existing implementation behaves surprisingly in some cases.

## Impact

This should be combined with refactoring Projection matrices, as this depends on them and there is an outstanding related bug. #2055

**Comment by minecrawler** [comment]
I would not say that there is no use-case for fov > 180 (thinking back to some space shooters, which were ideally played at 360 degrees), however how common is the actual usage?

Also, with curved monitors, it is physically possible to have a fov of >180, which would be great for immersion into a plane cockpit or similar.

However, should that be in auto_fov? Can auto_fov even determine something like that, and shouldn't tuning it insanely up be a user-setting or implemented by the game devs for their edge-case?

**Comment by joonazan** [comment]
@minecrawler A FOV of more than 180 degrees is not attainable with linear transformations. It requires a fisheye postprocessing step.

I think the purpose of AutoFov is to solve the problem "my view is squished" that most users will have and 99% will want the behaviour I described.

Normal adjustable FOV is compatible with the proposed solution. For 360 FOV you need 6 cameras that render a cube map.

**Comment by minecrawler** [comment]
@joonazan I am not sure if we are talking about the same kind of behavior.

**Comment by joonazan** [comment]
@minecrawler I am not familiar with the space shooters that you are talking about.

If what you mean is what I think it means, it is exceedingly rare. I have never played a game with over 180 degrees FOV and the only games I know that have a nonlinear projection have only slight nonlinearity. Except http://strlen.com/gfxengine/fisheyequake/

**Comment by joonazan** [comment]
Implemented this in #2118

**Comment by chemicstry** [comment]
Fixed in #2118
