### ISSUE TITLE
[MAINTENANCE] Jenkins fails to fetch repo

### ISSUE THREAD

**Issue by joonazan** [amethyst/amethyst#2124]
Jenkins randomly fails to fetch the repo, which causes incorrect CI failures.
See https://github.com/amethyst/amethyst/pull/2118#issuecomment-582078442

**Comment by azriel91** [comment]
@distransient and @fhaynes are working on another CI system (Bamboo?) that hopefully is more stable.

**Comment by CleanCut** [comment]
Update: @fhaynes and I are trying out GitLab as a CI in https://github.com/amethyst/amethyst/pull/2364
