### ISSUE TITLE
[BUG] Documentation links on website are broken

### ISSUE THREAD

**Issue by milesrout** [amethyst/amethyst#2131]
## Description

The documentation links on the website (specifically the ones to 'API documentation') are broken. I get a 404 on https://docs.amethyst.rs/stable/amethyst/.

## Reproduction Steps

1. Go to https://amethyst.rs/doc
2. Click on Browse the API Reference

## What You Expected to Happen

I expected to see API documentation.

## What Actually Happened

I got a 404.

**Comment by Voodlaz** [comment]
please fix that bug because i can't work on amethyst game engine without documentation.

**Comment by milesrout** [comment]
As a workaround you can do `cargo doc --open` in your project root @Voodlaz to generate the documentation yourself locally.

**Comment by Voodlaz** [comment]
> As a workaround you can do `cargo doc --open` in your project root @Voodlaz to generate the documentation yourself locally.

thanks!

**Comment by Voodlaz** [comment]
@milesrout thanks!

**Comment by snordgren** [comment]
Here's a working link https://docs.rs/amethyst/0.13.0/amethyst/

**Comment by milesrout** [comment]
What about 0.14? How hard can it be to release new docs when you release a new build?

**Comment by snordgren** [comment]
I don't know, I'm not part of this project. But yes, you'd expect working documentation from a project of this size.

**Comment by ab0v3g4me** [comment]
This was fixed few days ago.
