### ISSUE TITLE
[BUG] `.hide()` does not hide UiButton text

### ISSUE THREAD

**Issue by DavidDupre** [amethyst/amethyst#2139]
# Tasks
- Look at the UiWidget::Button transformation code to see if we are skipping the hide field

## Description

Using a `UiWidget::Button` with `UiTransformData::hide` does not hide the button text.

## Reproduction Steps

1. Replace the `to_native_widget` function in `examples/custom_ui` with this:

    ```rust
    fn to_native_widget(self, _: ()) -> (UiWidget<CustomUi>, Self::PrefabData) {
        let widget = UiWidget::Button {
            transform: UiTransformData::default()
                .with_position(60.0, -25.0, 1.0)
                .with_size(200.0, 50.0)
                .hide(),
            button: UiButtonData {
                id: None,
                text: "Hide me please".to_string(),
                font_size: 25.0,
                font: None,
                normal_text_color: [1.0, 1.0, 1.0, 1.0],
                normal_image: None,
                hover_image: None,
                hover_text_color: None,
                press_image: None,
                press_text_color: None,
                hover_sound: None,
                press_sound: None,
                release_sound: None,
            },
        };
        (widget, ())
    }
    ```

2. Add the `HideHierarchySystem` to `examples/custom_ui`

    ```rust
    .with_system_desc(HideHierarchySystemDesc::default(), "HideHierarchySystem", &["ui_transform"])
    ```

3. `cargo run --example custom_ui --features vulkan`
4. See the button text

## What You Expected to Happen

The button should not be visible.

## What Actually Happened

The button text is visible.

## Your Environment

OS: Windows 10 1809
Amethyst Version: 0.14.0 (also on master at ref 45536af87974)

## Additional Context

I also tried setting `hidden: true` on buttons in `examples/assets/ui/example.ron` and this works as expected. I'm only working with hidden because I've been struggling with creating buttons dynamically. Looking forward to progress on #2094.

**Comment by ChosunOne** [comment]
Also seeing this on Ubuntu 20.04.

**Comment by ChosunOne** [comment]
Looks like a workaround is to include the [HideHierarchySystem](https://docs.amethyst.rs/stable/amethyst_core/struct.HideHierarchySystem.html)
