### ISSUE TITLE
[BUG] Cursor position doesn't get updated

### ISSUE THREAD

**Issue by mvlabat** [amethyst/amethyst#2146]
## Description

Cursor position doesn't get updated until text content of any field gets changed (it's not necessarily the focused one).

## Reproduction Steps

1. Comment out `random_text` UI element out of `example.ron` (otherwise text updates will be retriggered every frame)
2. Run `ui` example
3. Focus the editable field, try to move the cursor with mouse clicks or Left/Right buttons on the keyboard

## What You Expected to Happen

I would expect the cursor to move.

## What Actually Happened

The cursor stays on the same position, until you type something.

## Your Environment

1. Windows 10 Pro
2. 1909
3. The latest master version (d647450)

**Comment by azriel91** [comment]
Looks like https://github.com/amethyst/amethyst/pull/2143 fixes this as well -- I just tried it out.

**Comment by mvlabat** [comment]
@azriel91 it doesn't fix it for me on clicks either.. The bug I've described isn't related to text spaces: the cursor position doesn't get updated at all, not only when it reaches whitespace.

If you're testing it on the `ui` example, are you sure that you've commented out `random_text` UI element? Otherwise you won't catch this particular bug

**Comment by azriel91** [comment]
Heya, could you try #2146 (ideally #2146 rebased over #2143). I've commented out `random_text`, and it kinda works (there's a small lag, but the cursor does update its position).

**Comment by mvlabat** [comment]
@azriel91 #2149 works perfectly now, thanks!
Btw, while a bit unrelated to this issue, could it be possible to put the caret right under the cursor, when we click on a field for the first time? Right now it always appears at the beginning of the field and moves under the cursor only on the second hit (after the field gets focus). If it's not a minor fix that could be implemented as a part of that PR, I can create a separate issue for that

**Comment by azriel91** [comment]
Heya, ya, noticed that one too. Shall look into it in a separate PR soon (today).
