### ISSUE TITLE
UIImage::Sprite items no longer display after fix to close #2018

### ISSUE THREAD

**Issue by trsoluti** [amethyst/amethyst#2157]
## Description

UI Sprite icons no longer display after the fix for "Draggable UI elements are broken when using ScaleMode::Percent" was implemented.

## Reproduction Steps

1. Download www.github.com/trsoluti/space_shooter
2. Run space shooter. 3 life icons show at the upper-left-hand corner of the screen
3. Modify Cargo.toml, change:
  amethyst = { git = "https://github.com/amethyst/amethyst", rev = "37df46b807699715551f5a20a1c49349a626c4ce"}
to
  amethyst = { git = "https://github.com/amethyst/amethyst", rev = "1ef6b1a673db8b7c3dd5142905b2f8dff7cf4f0c"}
4. Run space shooter again.

## What You Expected to Happen

3 life icons should appear at the upper-left-hand-corner of the screen

## What Actually Happened

No icons visible. This remains true in the 0.14.0 release of Amethyst.

## Screenshots and Logs

If applicable, add screenshots to help explain your problem. Any relevant logs would be helpful as well.

## Your Environment

1. OS: macOS Catalina
2. OS Version: 10.15.3
3. Amethyst: https://github.com/amethyst/amethyst/commit/1ef6b1a673db8b7c3dd5142905b2f8dff7cf4f0c

## Additional Context
Code to display UI Image is in entities/lives.rs.

**Comment by azriel91** [comment]
@bonsairobo my mind's not working tonight, maybe yours is? Handy links:

* [UI coordinates](https://github.com/trsoluti/space_shooter/blob/d12206330d9a2702e05ab2be41b598972a8b95db/src/entities/lives.rs#L44-L45)
* https://github.com/amethyst/amethyst/pull/2111/files

**Comment by bonsairobo** [comment]
@azriel91 Taking a look.

**Comment by bonsairobo** [comment]
Strangely enough, after resizing the window, I am able to see the "lives."

I'm can't compile the "before" revision because of this "__rt" issue.

**Comment by bonsairobo** [comment]
Seems to suggest the `ui::ResizeSystem` is at play in this.

Anyway, here are the UiTransforms of the lives in the "after" revision:

```
FIRST FRAME

entity = Entity(1, Generation(1)) tfm = UiTransform { id: "life0", anchor: TopLeft, pivot: Middle, stretch: NoStretch, local_x: 0.0, local_y: -26.0, local_z: 0.0, width: 32.0, height: 26.0, pixel_x: 0.0, pixel_y: -26.0, global_z: 0.0, pixel_width: 32.0, pixel_height: 26.0, scale_mode: Pixel, opaque: true, transparent_target: false, pd: PhantomData }
entity = Entity(2, Generation(1)) tfm = UiTransform { id: "life1", anchor: TopLeft, pivot: Middle, stretch: NoStretch, local_x: 32.0, local_y: -26.0, local_z: 0.0, width: 32.0, height: 26.0, pixel_x: 32.0, pixel_y: -26.0, global_z: 0.0, pixel_width: 32.0, pixel_height: 26.0, scale_mode: Pixel, opaque: true, transparent_target: false, pd: PhantomData }
entity = Entity(3, Generation(1)) tfm = UiTransform { id: "life2", anchor: TopLeft, pivot: Middle, stretch: NoStretch, local_x: 64.0, local_y: -26.0, local_z: 0.0, width: 32.0, height: 26.0, pixel_x: 64.0, pixel_y: -26.0, global_z: 0.0, pixel_width: 32.0, pixel_height: 26.0, scale_mode: Pixel, opaque: true, transparent_target: false, pd: PhantomData }

SECOND FRAME

entity = Entity(1, Generation(1)) tfm = UiTransform { id: "life0", anchor: TopLeft, pivot: Middle, stretch: NoStretch, local_x: 0.0, local_y: -26.0, local_z: 0.0, width: 32.0, height: 26.0, pixel_x: 0.0, pixel_y: 974.0, global_z: 0.0, pixel_width: 32.0, pixel_height: 26.0, scale_mode: Pixel, opaque: true, transparent_target: false, pd: PhantomData }
entity = Entity(2, Generation(1)) tfm = UiTransform { id: "life1", anchor: TopLeft, pivot: Middle, stretch: NoStretch, local_x: 32.0, local_y: -26.0, local_z: 0.0, width: 32.0, height: 26.0, pixel_x: 32.0, pixel_y: 974.0, global_z: 0.0, pixel_width: 32.0, pixel_height: 26.0, scale_mode: Pixel, opaque: true, transparent_target: false, pd: PhantomData }
entity = Entity(3, Generation(1)) tfm = UiTransform { id: "life2", anchor: TopLeft, pivot: Middle, stretch: NoStretch, local_x: 64.0, local_y: -26.0, local_z: 0.0, width: 32.0, height: 26.0, pixel_x: 64.0, pixel_y: 974.0, global_z: 0.0, pixel_width: 32.0, pixel_height: 26.0, scale_mode: Pixel, opaque: true, transparent_target: false, pd: PhantomData }

FRAME AFTER RESIZE

entity = Entity(1, Generation(1)) tfm = UiTransform { id: "life0", anchor: TopLeft, pivot: Middle, stretch: NoStretch, local_x: 0.0, local_y: -26.0, local_z: 0.0, width: 32.0, height: 26.0, pixel_x: 0.0, pixel_y: 996.0, global_z: 0.0, pixel_width: 32.0, pixel_height: 26.0, scale_mode: Pixel, opaque: true, transparent_target: false, pd: PhantomData }
entity = Entity(2, Generation(1)) tfm = UiTransform { id: "life1", anchor: TopLeft, pivot: Middle, stretch: NoStretch, local_x: 32.0, local_y: -26.0, local_z: 0.0, width: 32.0, height: 26.0, pixel_x: 32.0, pixel_y: 996.0, global_z: 0.0, pixel_width: 32.0, pixel_height: 26.0, scale_mode: Pixel, opaque: true, transparent_target: false, pd: PhantomData }
entity = Entity(3, Generation(1)) tfm = UiTransform { id: "life2", anchor: TopLeft, pivot: Middle, stretch: NoStretch, local_x: 64.0, local_y: -26.0, local_z: 0.0, width: 32.0, height: 26.0, pixel_x: 64.0, pixel_y: 996.0, global_z: 0.0, pixel_width: 32.0, pixel_height: 26.0, scale_mode: Pixel, opaque: true, transparent_target: false, pd: PhantomData }
```

**Comment by bonsairobo** [comment]
Seems like the `pixel_y` values are changing. Not sure what's causing that (other than a aspect ratio change).

**Comment by bonsairobo** [comment]
The issue persists event without the `DragWidgetSystem` running.

**Comment by bonsairobo** [comment]
Issue persists even without the `ui::ResizeSystem` running.

**Comment by bonsairobo** [comment]
Ah. I had a misunderstanding of what `ui::ResizeSystem` does. It seems that it's actually the `UiTransformSystem` that handles moving the transforms on window resize.

**Comment by bonsairobo** [comment]
OK the changes to `pixel_y` are definitely caused by the `UiTransformSystem` and *both* changes result from changes to `ScreenDimensions`.

The first change happens on the first dispatch of `UiTransformSystem`, because it starts with a `size` of `(0.0, 0.0)`, and this does not match `ScreenDimensions`.

The 2nd change happens via the same code patch during an "actual" window resize.

**Comment by bonsairobo** [comment]
Starting to wonder if the pixel_y thing is a red herring. Both (0, 974) and (0, 996) should be visible given the window size is (1000, 1000).

@trsoluti mentioned #2018 in the title, but then references 1ef6b1a673db8b7c3dd5142905b2f8dff7cf4f0c as the bad revision, which is related to #2111, not #2018.

**Comment by azriel91** [comment]
Thanks for doing so much investigation :bowing_man:.

> Strangely enough, after resizing the window, I am able to see the "lives."

Given it's visible after resizing, then this part makes sense:

> Both (0, 974) and (0, 996) should be visible given the window size is (1000, 1000). 

But for the first frame when `pixel_y` is `-26.0`, that's going to be below the window (since y: 0 is the bottom of the window), so perhaps it's actually the initial coordinate that's incorrect?
Hopefully that logic is correct.

**Comment by azriel91** [comment]
I tried both revision 37df46b807699715551f5a20a1c49349a626c4ce and 1ef6b1a673db8b7c3dd5142905b2f8dff7cf4f0c, but the `UiImage::Sprite` does not show up on either until the window is resized. The breakage must have happened earlier.

**Comment by azriel91** [comment]
I was initially going to solve this before doing an amethyst release, but since I don't have the means to (the `UiImage::Sprite` never shows up until window is resized, on old + new versions of amethyst), I have to skip this.
