### ISSUE TITLE
Mobile devices support

### ISSUE THREAD

**Issue by nameofuser1** [amethyst/amethyst#2159]
Hello!

I have seen in the roadmap that support for mobile devices should be already implemented. However I can not see any docs or news on the matter. So what is the current state of mobile compatibility?

Thank you!

**Comment by atonamy** [comment]
Yes I also very wondering to try out mobile support iOS and Android.

**Comment by AlveLarsson** [comment]
Thanks for the interest, just made #2317 to track what is going on

**Comment by ProgrammingLife** [comment]
@AlveLarsson What about iOS?

**Comment by atonamy** [comment]
@ProgrammingLife mobile means support at least both platforms so if it will be supported it will be supported for iOS and Android

**Comment by AlveLarsson** [comment]
Yeah sorry have to make the issue more clear, IOS will come it's just currently mutch more easy to test and Dev on Android devices, we want to share as much code as possible between the platforms. 

Also I currently don't have access to the Apple dev ecosystem and devices, but we warmly welcome anyone who has to help add IOS support.
