### ISSUE TITLE
Enforce updating the changelog

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#216]
According to [Keep a Changelog](http://keepachangelog.com/en/0.3.0/), the format this repository is using, it is recommended to have an `## [Unreleased]` section at the top which keeps track of the latest changes. Probably we should add this hint to `CONTRIBUTING.md` and ask for adding the changes to `CHANGELOG.md` when reviewing a PR.

**Comment by ebkalderon** [comment]
@torkleyy Good point! We already have the `## [Unreleased]` section, but we never added the hint to the `CONTRIBUTING.md` guide.

**Comment by Xaeroxe** [comment]
This has been done, so I'm closing this issue.
