### ISSUE TITLE
[BUG] Amethyst network using Laminar drops connection 

### ISSUE THREAD

**Issue by Machine-Hum** [amethyst/amethyst#2168]
## Description
Using the laminar implementation of amethyst network when there is one server and one client, everything works perf. When you add another client in, the server will fire the Disconnect after a while.
If you check out what's going on with wireshark, you can see the heartbeat packets sending fine, so there's no reason for a disconnect

https://imgur.com/a/WBVYrvf

Packet 2727 is when the server sends to all the other clients the one client has disconnected, however you can see heartbeats from that client ms before.

## Reproduction Steps
Create a server and connect more than one client

## What You Expected to Happen
When both client send their heartbeat there shouldn't be a disconnection event

## What Actually Happened
There is a disconnection event

## Your Environment

1. Operating System
Debian

2. Operating System Version
Stretch

3. Version of Amethyst
master

**Comment by TimonPost** [comment]
This should probably be moved to laminar issues. It is a known bigbug in laminar

**Comment by Centronias** [comment]
@TimonPost , is there any information about what exactly is known about this bug? I'm curious to know if there's any possibility to fixing it, as it's holding me up from my quarantine distraction project.

**Comment by onbjerg** [comment]
@TimonPost Does that mean Laminar is not really usable for games with multiple clients at the moment?
