### ISSUE TITLE
Get WASM application initialization to work (Linux)

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#2176]
[`pong_wasm`](https://github.com/amethyst/pong_wasm)'s [`#[wasm_bindgen(start)]` function](https://github.com/amethyst/pong_wasm/blob/178f88993ddab34971f72daac739c0558e5557d2/src/main.rs#L165-L169) begins with a log statement, but it does not show up in the browser console:

```rust
#[wasm_bindgen(start)]
pub fn run() {
    wasm_logger::init(wasm_logger::Config::default());

    log::debug!("run()");

    let _ = super::main();
}
```

```bash
wasm-pack build -- --features "wasm gl"
(cd www && npm install && npm run start)
```

Make sure the WASM application is actually initialized, and make sure WASM Pong's logging works.

See [www/index.js](https://github.com/amethyst/pong_wasm/blob/master/www/index.js).

**Update:** This works on Windows/Firefox, Windows/Chrome, but not on Ubuntu/Firefox or Ubuntu/Chrome.

**Comment by chemicstry** [comment]
I was able to compile everything as described in wasm contribution guide, except for a few minor problems:
* Native compiler error as described https://github.com/amethyst/amethyst/pull/2178
* Fixed import in index.js `"./node_modules/pong/pong"` -> `"../pkg/pong_wasm"`. Or should I have used npm link? But the module name is incorrect anyway.
* Replaced `#[wasm_bindgen(start)]` in main.rs with `#[wasm_bindgen]`. Previous one causes function to be executed automatically during import, but since `pong.run()` is called in `index.js` it causes it to be executed 2 times.

Apart from that, I am able to see log output in console `DEBUG src/main.rs:167 run()`. Is this issue already resolved or this could be a platform specific bug? I'm compiling on Windows.

**Comment by azriel91** [comment]
ah, thanks for #2178.

Wondering if `npm` behaves differently on Windows, I think this part in `package.json` should put it under `node_modules/pong` when running `npm install`:

```json
  "dependencies": {
    "pong": "file:../pkg"
  },
```

I haven't really used node before this; perhaps it is different on different OSes.

> * Replaced `#[wasm_bindgen(start)]` in main.rs with `#[wasm_bindgen]`. Previous one causes function to be executed automatically during import, but since `pong.run()` is called in `index.js` it causes it to be executed 2 times.
>
> Apart from that, I am able to see log output in console `DEBUG src/main.rs:167 run()`. Is this issue already resolved or this could be a platform specific bug? I'm compiling on Windows.

ah, I'm on Pop OS (effectively Ubuntu) on Firefox, and can't see anything. Shall try on chrome / my windows box soon.

**Comment by chemicstry** [comment]
> Wondering if `npm` behaves differently on Windows, I think this part in `package.json` should put it under `node_modules/pong` when running `npm install`:
> 
> ```json
>   "dependencies": {
>     "pong": "file:../pkg"
>   },
> ```
> 
> I haven't really used node before this; perhaps it is different on different OSes.

Oh, I haven't looked into `package.json` but in this case the `import * as pong from "pong"` works (without node_modules path).

**Comment by azriel91** [comment]
Heya, just checked. The `run()` log works on Windows/Firefox, but doesn't work on PopOS/Firefox and PopOS/Chrome. Might have to find another Linux box to see if it's just my computer, or across other Linuxes / Ubuntus.

> `import * as pong from "pong"` should work on all platforms (without node_modules path)

Yeap this works :v:, shall commit that soon (with the other changes you mentioned above).

**Comment by azriel91** [comment]
ah, it does work on linux after changing it to reference the "pong" module by name instead of by path -- been trying heaps of changes but forgot to check that one after switching computers `._.`. 

I've pushed the changes to the `pong_wasm` repository.
