### ISSUE TITLE
Get `web_worker` `ThreadPool` integrated

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#2177]
[`web_worker`](https://github.com/jojolepro/web_worker) uses a JS `WorkerPool` to service tasks, so tasks can be run in parallel.

Integrate this into `amethyst` and create a small WASM application to demonstrate `ThreadPool` usage.

**Comment by azriel91** [comment]
Note, assets still cannot be loaded simply by getting `rayon` to use a `WorkerPool` -- `amethyst_assets` still loads from the file system, and we have to get it to load from perhaps a `HttpSource`.

**Comment by chemicstry** [comment]
While working on #2180 I experimented with `web_worker` and couldn't get it to work on stable rust, but got it working with nightly as per https://github.com/rustwasm/wasm-bindgen/blob/master/examples/raytrace-parallel/build.sh instructions. Strangely I didn't get any compile errors, but browser refused to load workers with `Failed to execute 'postMessage' on 'Worker': #<Memory> could not be cloned.`. I guess the required rust features are still experimental? If that's the case, then the build instructions will have to be updated.

**Comment by chemicstry** [comment]
Partially solved in #2189. Narrowed down to #2191
