### ISSUE TITLE
WASM: Solve timing problems

### ISSUE THREAD

**Issue by chemicstry** [amethyst/amethyst#2183]
Currently `std::time::Instant` is not implemented for wasm. An easy solution that seamlessly integrates is [insant](https://github.com/sebcrozet/instant) library. Do we care about dependency bloat and want to reimplement simpler version ourselves?

**Comment by chemicstry** [comment]
Created a PR #2184

**Comment by khionu** [comment]
So, this can be closed now?

**Comment by chemicstry** [comment]
Yep
