### ISSUE TITLE
Release 0.15.0

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#2187]
[Instructions](https://github.com/amethyst/amethyst/blob/master/docs/PUBLISHING.md)

Progress tracking:

* [x] Update versions in `Cargo.toml` for sub crates, including inter-crate dependency versions.
* [x] Update `CHANGELOG.md`.
* [x] Publish crates.

    - :label: tag: https://github.com/amethyst/amethyst/tree/0.15.0
    - :card_file_box: GH releases: https://github.com/amethyst/amethyst/releases/tag/0.15.0
    - :package: crates.io: https://crates.io/crates/amethyst/0.15.0

* [x] PR (sanity check) -- https://github.com/amethyst/amethyst/pull/2188.
* [x] Tag and publish a github release.
* [x] Amethyst tools -- https://github.com/amethyst/tools/pull/108.
* [x] Blog post -- https://amethyst.rs/posts/release-0-15-0.
* [x] Announce on [Discord], [r/rust_gamdev], [URLO], [Twitter] -- ask Erlend (as [`@AmethystEngine`])

    - https://www.reddit.com/r/rust_gamedev/comments/fodn13/announcing_amethyst_0150/
    - https://twitter.com/AmethystEngine/status/1242561365325361162

[Discord]: https://discordapp.com/channels/425678876929163284/482547634641436673
[r/rust_gamdev]: https://www.reddit.com/r/rust_gamedev/
[URLO]: https://users.rust-lang.org/
[Twitter]: https://twitter.com/home
[`@AmethystEngine`]: https://twitter.com/AmethystEngine

**Comment by khionu** [comment]
@AlveLarsson can also do the post
