### ISSUE TITLE
[BUG] Removing audio feature does not remove audio from dependencies

### ISSUE THREAD

**Issue by ytaras** [amethyst/amethyst#2193]
## Description

Adding `amethyst` dependency to project brings `amethyst_audio` regardless of the audio feature being disabled or enabled. 

## Reproduction Steps

1. Add following dependency to your Cargo.toml:
```
    [dependencies.amethyst]
    version = "0.15.0"
    default-features = false
    features = ["empty"]
```
2. Compile a project

## What You Expected to Happen

`amethyst_audio` not being added to a project dependencies

## What Actually Happened

`amethyst_audio` was added as a dependency of `amethyst_ui`, which has it as a unconditional dependency

## Screenshots and Logs

skip

## Your Environment

1. Operating System - Any
2. Operating System Version - Any
3. Version of Amethyst - 0.15.0

## Additional Context

skip

**Comment by CleanCut** [comment]
Closing in favor of #2490, which has some useful discussion.
