### ISSUE TITLE
WASM: audio

### ISSUE THREAD

**Issue by chemicstry** [amethyst/amethyst#2195]
Current `cpal` only supports `emscripten`, but not `wasm-bindgen`. We probably don't want any external javascript dependencies.

Blocked on:
https://github.com/RustAudio/cpal/issues/212 / https://github.com/RustAudio/cpal/pull/372
https://github.com/RustAudio/rodio/pull/247

**Comment by azriel91** [comment]
Tried using the above branches, and updated amethyst. Chrome has this error:

```js
Unable to write sample data into the audio context buffer: JsValue(TypeError: Failed to execute 'copyToChannel' on 'AudioBuffer': The provided ArrayBufferView value must not be shared.
// ..
at real (http://localhost:8000/pkg/pong_wasm.js:200:20))', /home/azriel/.cargo/git/checkouts/cpal-df9dae205d491af1/61d1a25/src/host/webaudio/mod.rs:273:25
```

The [web audio API spec](https://webaudio.github.io/web-audio-api/#dom-audiobuffer-copytochannel) also says this:

> Note: This means that `copyToChannel()` cannot be used to change the content of an `AudioBuffer` currently in use by an `AudioNode` that has acquired the content of an `AudioBuffer` since the `AudioNode` will continue to use the data previously acquired.

Perhaps this means we cannot use the same `OutputStreamHandle` to play multiple audio files, and should instead create a new output stream each time.

**Comment by azriel91** [comment]
In [`cpal/src/host/webaudio/mod.rs:273`](https://github.com/amethyst/cpal/blob/ca3db4f/src/host/webaudio/mod.rs#L273-L275) this call happens:

```rust
// panic is from this copy_to_channel / expect
ctx_buffer
    .copy_to_channel(&mut temporary_channel_buffer, channel as i32)
    .expect("Unable to write sample data into the audio context buffer");
```

In the error message `The provided ArrayBufferView value must not be shared`, the `ArrayBufferView` likely refers to the `temporary_channel_buffer`, rather than the `ctx_buffer`. Nevertheless, I have tried cloning both `ctx_buffer` and `temporary_channel_buffer` before that method call, and the same error is hit.

I'm not sure what to do next, save for looking into the generated JS bindings / chromium source code. I have asked for help in:

* Rust community discord
* https://github.com/RustAudio/cpal/issues/212#issuecomment-610144281

Perhaps waiting will give us an answer.

**Comment by azriel91** [comment]
We cannot manipulate the `AudioBuffer`'s data via [`AudioBuffer::get_channel_data`](https://docs.rs/web-sys/0.3.37/web_sys/struct.AudioBuffer.html#method.get_channel_data) because shared references can't currently be returned from imported JS functions (https://github.com/rustwasm/wasm-bindgen/issues/1335#issuecomment-471683469).

**Comment by azriel91** [comment]
Theory (thanks `@chemicstry`!), `temporary_channel_buffer` is created in a web worker, and so is on a `SharedArrayBuffer` automatically, so passing a reference to it in `copy_to_channel` would always result in an `ArrayBufferView`. Tried using an external JS function to create a non-view:

```js
// Creates a a standalone `Float32Array` from the given `src`.
//
// This is necessary when the source values are in shared memory -- the `AudioBuffer` cannot
// reference memory that is shared, and so if `src` backs onto `SharedArrayBuffer` (as is the case
// when using web workers), calling this on `src` will return a standalone copy.
function make_standalone(src) {
    // var standalone = Float32Array.from(src);
    // var standalone = new Float32Array(src);
    // var standalone = src.slice();
    // var standalone = ArrayBuffer.transfer(src);
    console.error("src: " + src);
    var standalone = [...src];
    console.error("standalone: " + standalone);
    // console.error("is view: " + ArrayBuffer.isView(standalone));
    return standalone;
}

if (typeof exports === 'object' && typeof module === 'object')
    module.exports = make_standalone;
else if (typeof define === 'function' && define['amd'])
    define([], function() { return make_standalone; });
else if (typeof exports === 'object')
    exports["make_standalone"] = make_standalone;
```

The `[...src]` method finally gave us `is view: false`. However, the same error appears:

```
Failed to execute 'copyToChannel' on 'AudioBuffer': The provided ArrayBufferView value must not be shared.
```

Am guessing this means simply by passing `&mut some_data` into `copy_to_channel`, it automatically gets turned into an `ArrayBufferView` whenever it's on a web worker thread. Maybe this will work if the audio system is on the main thread?

**Comment by azriel91** [comment]
Yay, the error goes away when using JS to invoke the `AudioBuffer.copyToChannel` call, on an owned `ArrayBuffer`:

```rust
// cpal
#[wasm_bindgen]
extern "C" {
    fn copy_audio_buffer(dest: &AudioBuffer, src: &[f32], channel: i32);
}

copy_audio_buffer(&ctx_buffer, &temporary_channel_buffer, channel as i32);
```

JS:

```js
function copy_audio_buffer(dest, src, channel) {
    // Turn the array view into owned memory.
    var standalone = [...src];
    // Make it a Float32Array.
    var buffer = new Float32Array(standalone);

    // Copy the data.
    dest.copyToChannel(buffer, channel);
}

if (typeof exports === 'object' && typeof module === 'object')
    module.exports = copy_audio_buffer;
else if (typeof define === 'function' && define['amd'])
    define([], function() { return copy_audio_buffer; });
else if (typeof exports === 'object')
    exports["copy_audio_buffer"] = copy_audio_buffer;
```

Audio doesn't play yet though -- needs a user interaction. There's also another error which I don't yet understand:

```js
Uncaught Error: closure invoked recursively or destroyed already
// ..
at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h8782643c7ede96f8 (:8000/wasm-function[6507]:0x361b3a)
// ..
```

**Comment by azriel91** [comment]
The following line looks similar to https://github.com/rustwasm/wasm-bindgen/issues/782:

```
at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h8782643c7ede96f8 (wasm-function[6507]:0x361b3a)
```

Not sure what `FnMut(..)` that refers to, still searching code :confused:.

**Comment by azriel91** [comment]
Hacked a `sed` fix in https://github.com/amethyst/pong_wasm/pull/3, but at least that's gotten it to work.

**Comment by azriel91** [comment]
Split the clean up to #2222.
