### ISSUE TITLE
[MAINTENANCE] Remove ron files from examples

### ISSUE THREAD

**Issue by ab0v3g4me** [amethyst/amethyst#2197]
This should be marked for the next release. It is very tedious to sift through examples because of this. There should be only one example for demonstrating loading of `.ron` files and creating entities from their data, everything else should programmatically be created. 

**Why ?**

As i've said on one hand it is **hard** for users to maneuver  through the example tree and when they look at the source directory they will find a `main.rs` in which they can't really see anything but they will see that it loads some file that isn't even in the parent directory but in the examples directory which makes no sense. And when you take a look at the example not all the code that needs to be there is there.

Another thing is that the examples themselves should contain their own screenshots and not the example folder!! It's easier on loading the page and it doesn't stretch into infinity. 

**What am i trying to say?**
Well if you're still not getting it, the main point of this is that when a user wants to look at a specific example he will click the link to `custom_ui` example and it would lead him to that folder in which all the files are located with or without extra inconvenient `.ron` files. It shouldn't make the user go back and search for the files that the example is trying to load.

**Comment by Puciek** [comment]
I think that's an excellent idea which will make the examples a lot more entry-level friendly!

**Comment by CleanCut** [comment]
Can I get some feedback on this draft PR? Am I going in the right direction?  I thought I might help this issue along by just relocating all assets into their respective example projects. So far, I've just done `sprite_camera_follow` through `window`.  If this seems like the right direction, I'll go through the rest of the list.  Even if we don't end up removing ron files, I think the examples are much more understandable with their assets close by (especially the one that had unused assets inside the example project named the same as assets actually being used over in `examples/assets` 😆 😭 ).

/cc @ab0v3g4me @Puciek

**Comment by CleanCut** [comment]
Regarding only colocating assets (including ronfiles) with their examples: https://github.com/amethyst/amethyst/pull/2289 got merged after I had done examples `renderable_custom` through `window`.  I opened https://github.com/amethyst/amethyst/pull/2305 and am working on `animation` through `renderable`.  I welcome participation from anyone who is interested.

**Comment by ab0v3g4me** [comment]
The PR for this issue was merged, hence I'm closing the issue.

**Comment by CleanCut** [comment]
@ab0v3g4me If you are referring to my work in https://github.com/amethyst/amethyst/pull/2289 and https://github.com/amethyst/amethyst/pull/2305 -- I did colocate all the example assets, including ron files. I didn't directly address your initial request at all, though:

> There should be only one example for demonstrating loading of `.ron` files and creating entities from their data, everything else should programmatically be created.

If that is still important to you or others, perhaps we should leave this issue open.  I don't have a strong opinion about that.

**Comment by ab0v3g4me** [comment]
You're probably right, let it hang a bit more!

**Comment by AlveLarsson** [comment]
Can we also ensure all examples work on all platforms while this maintenance is going on? (I've had some issues on Linux ubuntu)
I think we should make this into 0.15.1

**Comment by CleanCut** [comment]
VMWare hasn't produced Vulkan drivers yet, so my Windows and Linux VM's can't run amethyst on my Mac. Otherwise I'd be happy to check them.  😞

**Comment by ezpuzz** [comment]
I'm considering moving UI examples inside the amethyst_ui crate, tiles examples inside tiles crate, etc.
This is not required for an 0.16 release though so removing milestone.

Also I agree we only need a few prefab examples, having so many prefabs has made testing/running the examples difficult during the legion transition.  I have already converted the spheres example to not use prefabs I believe.

**Comment by CleanCut** [comment]
Putting examples demonstrating usage of Amethyst inside of subcrates would be odd, unless the intent of the example is to show how to use only the subcrate without the rest of Amethyst.

**Comment by ezpuzz** [comment]
> Putting examples demonstrating usage of Amethyst inside of subcrates would be odd, unless the intent of the example is to show how to use only the subcrate without the rest of Amethyst.

Ah yeah that makes sense to reserve it for using the crate without anything else.  Specifying features for examples in cargo.tonl makes enough sense for now.  The examples do need some better naming and some need prefabs made in to code instead.

**Comment by ezpuzz** [comment]
Considering that relevant assets are now located with their examples in 0.16, and constructing entities in code instead of from prefabs is a different issue I am going to close this issue.
