### ISSUE TITLE
[BUG] Rendy example fails at loading prefab from ron file

### ISSUE THREAD

**Issue by ykafia** [amethyst/amethyst#2199]
## Description

The rendy example fails while apparently loading resources from a ron file.

## Reproduction Steps

1. Clone amethyst repository
2. Run command : 
```powershell
cargo run --release  --features="vulkan animation gltf" --example rendy
```

## What You Expected to Happen

The example running without failure

## What Actually Happened

While loading resources the example failed and the application crashed.

## Screenshots and Logs

```powershell
Create spheres
Create lights
Error: [AssetErrorMeta { error: Error { inner: Inner { source: Some(Error { inner: Inner { source: None, backtrace: None, error: StringError("Failed loading sub asset") } }), backtrace: None, error: Asset("prefab\\rendy_example_scene.ron") } }, handle_id: 0, asset_type_name: 
"PREFAB", asset_name: "prefab\\rendy_example_scene.ron" }]
```

## Your Environment

1. Windows 10
2. Latest ( Git )

**Comment by sinkuu** [comment]
You need to install Git LFS (and run `git lfs pull`) before running examples. https://github.com/amethyst/amethyst#before-you-begin

**Comment by ykafia** [comment]
I'm sorry, I should read the documentation more.
