### ISSUE TITLE
Config files

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#220]
I think the config files are somehow broken, because they contain "fixed" stuff like window title, but also options the player would like to change (like resolution, full screen).

Maybe split it into `config.yml` and an `options.yml` (which isn't in the `resources` folder)?

**Comment by Emilgardis** [comment]
I think the reason for this is because of full screen games and providing a default configuration for windowed

**Comment by torkleyy** [comment]
But still, how would you have such an options file in a nice way? The window is built from the `config.yml`.

**Comment by torkleyy** [comment]
It's not that config files should be different, I misunderstood what exactly they are for.
