### ISSUE TITLE
[BUG] RLS in VSCode -> could not compile `rendy-util`

### ISSUE THREAD

**Issue by JamesPatrickGill** [amethyst/amethyst#2200]
## Description

When completing the pong tutorial, rls for VS-Code is unable to compile 'rendy-util', meaning many rls features do not work - `cargo run` works correctly

## Reproduction Steps

1. Setup project following the guide in the tutorial using vscode with rls extension installed
2. Look in the problems tab of the toolbar to see the "could not compile `rendy-util`" message as shown below.

## What You Expected to Happen

Amethyst would be able to be compiled as normal for rls - vscode

## What Actually Happened

A error message appeared meaning the compilation didnt happen.

## Screenshots and Logs

Error + Cargo.toml
![image](https://user-images.githubusercontent.com/44863195/77824670-49c5f100-70fc-11ea-8ed1-d30786fbc3c1.png)

## Your Environment

1. MacOS
2. 0.15.0

**Comment by ab0v3g4me** [comment]
Perhaps this is a metal issue ? Have you tried going vulkan if possible ?

**Comment by JamesPatrickGill** [comment]
Hi thanks for your help, I have tried vulkan aswell with same problem, 

To clarify i want to say that this happens during the rls background build of the dependencies i.e. when this icon can be seen at the bottom: 
![image](https://user-images.githubusercontent.com/44863195/77832660-8c54f100-712f-11ea-8b35-34af84f687c6.png)
In this screenshot it is building rodio in the background for example.

The RLS does however output this error about vulkan backend (this is with both vulkan and metal) 
![image](https://user-images.githubusercontent.com/44863195/77832698-dc33b800-712f-11ea-9a2f-77555db189e0.png)

All help is appreciated, thank you

**Comment by JamesPatrickGill** [comment]
Hi I have just solved my issue, I believe RLS is looking at all the features in my toml and compiling the dependencies for all of them, this for some reason is causing issues on my macOS machine, 

I have not tried it but think i need to just install the vulkan sdk on my machine.

However, i also needed to remove the `empty = ["amethyst/empty"]` feature also as this was causing a failed compile on amethyst-asset, once i removed that the rls fully compiled and could do its intellisense/error line stuff. 

P.S. my working toml,

`[package]
name = "the-outdoors"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = "0.15.0"

[features]
default = ["metal"]
metal = ["amethyst/metal"]
`
