### ISSUE TITLE
[FEATURE REQUEST] Support multiple windows

### ISSUE THREAD

**Issue by ckaran** [amethyst/amethyst#2203]
## Note

I can't decide if this is a feature request or a maintenance request...

I'm developing a simulator where it would be extremely useful to have multiple windows open and attached to the same ECS at the same time.  Based on my quick reading of the latest code, it appears that Amethyst assumes that there will always be exactly one window per application; this makes handling my use case much more difficult.  Would it be possible to turn the Window type into a component throughout?

## Description

I want to be able to treat windows as components, and specify entities for them.  This way I can create systems that display different information depending on the particular window entity that they are outputting to, rather than having to cram all information into a single window.

The problem with this is that much of Amethyst seems to assume that there is exactly one window in a game.  I don't know if this is true, it's just based on what I could tell from quickly reading through the code.  

## Reason

There are many applications where it would be useful to have multiple windows open at once, with all of the windows tied to the same ECS.  For example, in a flight simulator it would be nice to be able to have multiple monitors, and to have each monitor displaying different information.  The ECS would be the central repository of all truth in the system, and the windows on each monitor would display different instruments that show different parts of that truth.

Since it is possible that there are other 'assumed singletons' in Amethyst, the only way that I can be sure of making such a system work right now is to fork off one child process per monitor/window, and set up some kind of IPC between the parent and the children to make sure that they remain in sync.  However, that is really not the way things should be in a good game engine.

## Impact

Do you think this change will have a negative impact on anything else?

Not that I can think of.   Games that only require a single window at a time would just have a single window entity, so unless the ECS crate is really, really slow, it shouldn't have an impact on performance.

## Additional Information

Amethyst is shaping up to be a pretty good engine; wish it existed when I started my PhD!

**Comment by khionu** [comment]
While I love the idea (many games could benefit from this), it's likely going to be a very low priority.

### Issues that would need to be addressed:
- [ ] All windows as components or have a concept of a "primary" window?
- [ ] Review affected modules and determine if anything blocks.

**Comment by ckaran** [comment]
It would be better to *not* have a primary window as the temptation is to direct all user input to the primary window.  There are use cases where this would be annoying (e.g., old school console games where each player sees their own window, and expects that their window is primary relative to themselves).
