### ISSUE TITLE
Attempt to migrate Resources into Components.

### ISSUE THREAD

**Issue by ckaran** [amethyst/amethyst#2204]
## Note

See #2203 for an example of what I'm talking about

## Description

What do you see that needs to be updated? Include a link to the code if possible.

I know that Amethyst assumes that there is exactly one window in a game (see #2203), but I don't know if there are other types that are also assumed to be singletons within Amethyst.  This issue report is to alert the Amethyst team to look for such assumptions and to create issues to change those assumptions where it makes sense to do so.  

So, what is the problem exactly? When a type is assumed to be a singleton, it instantly limits what the end user can do with Amethyst.  With #2203, this assumption means that it is difficult to write a game that has multiple windows open at the same time, all tied to the same ECS.  While it may be possible to work around this issue, because the assumption pervades how Amethyst's code was written, there may be unintended side-effects of creating multiple windows, or multiple game loops, etc.

Instead of assuming that **any** object is a singleton, amethyst should default to assuming that there can be multiple objects of the same type alive at the same time.  The default builders can then do the common thing of creating and storing a single instance in the ECS.  If the game developer needs to make changes, they can create multiple entities for the given component type.

## Reason

Why should this change be made?

Two reasons.  First, it expands what it is possible to do with Amethyst.  #2203 is one example; here are some more:

- Multiple controllers of the same type (for aircraft, this might be the pilot & copilot seats).
- Old school multiplayer, but with multiple monitors.   There is one computer, but two controllers and two separate monitors, or really old school with one monitor and two windows.
- Testing & debugging in real-time.  An end user can be set up at a station with one monitor, while the developer is observing debugging output on a second monitor (e.g., the FPS counter, any info about network lag and how it's affecting the user, etc.).  
- X-ray glasses - Thanks to [Window::inner_position()](https://docs.rs/winit/0.22.0/winit/window/struct.Window.html#method.inner_position) and [Window::inner_size()](https://docs.rs/winit/0.22.0/winit/window/struct.Window.html#method.inner_size), it's possible to know the positions of two windows relative to one another.  With that, you can display information in the X-ray window that is positioned relative to the other window.  For example, in the first window you see a picture of a patient (or car, or whatever).  As you drag the X-ray window over the first window, you see an X-ray of the patient, correctly positioned over the patient so it appears that you're wearing X-ray glasses.  You could have numerous windows, each with different filter effects letting you see different information at the same time.

Second, it makes for cleaner, clearer code.  By making every single type a component, they can all be handled in exactly the same way.  This makes it easier for developers as the muscle memory will become `for (foo, bar, baz) in (&foos, &bars, &bazs).join() {...}` for every single system that they write. 

## Impact

Do you think this change will have a negative impact on anything else?

I think it will have a very *positive* impact on everything else.  Since some operating systems require certain calls to only be made on certain threads (e.g., iOS requires drawing code to be called from the main thread), it will become a part of the ECS's job to decide which threads different systems can run on.  This will reduce headaches and increase the chance for parallelism as the ECS figures out how to load balance between the threads automatically, instead of making the developer do it.

**Comment by khionu** [comment]
I would concede that singletons should not be the default, but they certainly have their place. If you know there will only be one of a specific item, then it's a faster look-up and gives to more intuitive code.

> Instead of assuming that any object is a singleton
This is a sweeping generalization that is simply not true. If a Resource becomes a problem in it being a singleton, it can be considered for moving into a Component. There will need to be a cost-benefit analysis.

Re #2203, it's not an unreasonable assumption for a budding engine that there will only be one window. While there are plenty of cases for multiple windows, it's still rather niche.

Putting things as Resources isn't going to be something that goes away, but we will welcome any critical review on a per-case basis.

**Comment by ckaran** [comment]
I agree that some items are best treated as singletons, but in the case that an item is going to be a singleton it should be *clearly* marked as such (maybe a marker trait?), and the reasons why it was chosen to be a singleton should be documented.  The feeling I get is that the decision regarding the number of windows in a game was an accident, not intentional.  This issue is about making clear decisions, and requiring that all types be multiples unless there is a good reason to make a given type a singleton.

**Comment by ckaran** [comment]
@khionu Is there a different place where this is being discussed than GitHub?  If so, I'd like to jump in on that discussion.

Also, should I start doing my own triage?  I can create a list under this issue, or I can create separate issues for each item, depending on what is best for the project.

**Comment by khionu** [comment]
I would start a discussion on the Forums. Mind you, I did not mean to say that we would accept any changes. The relevant team(s) would need to agree with your arguments.

**Comment by ckaran** [comment]
> I would start a discussion on the Forums. 

OK, will do, and thank you!

> Mind you, I did not mean to say that we would accept any changes. The relevant team(s) would need to agree with your arguments.

Of course! I would actually be more concerned with the direction of the project if ideas and PRs were blindly accepted!
