### ISSUE TITLE
WASM: Solve WebGl2RenderingContext uniform block index invalid

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#2205]
When running `pong_wasm` in chrome, the rendering panics on the following line ([`device`](https://github.com/amethyst/gfx/blob/wasm/src/backend/gl/src/device.rs#L823)):

```rust
panicked at 'called `Option::unwrap()` on a `None` value', /mnt/data/work/github/gfx-rs/gfx/src/backend/gl/src/device.rs:823:41
```

This happens when [`WebGl2RenderingContext::get_uniform_block_index`](https://docs.rs/web-sys/0.3.37/web_sys/struct.WebGl2RenderingContext.html#method.get_uniform_block_index) returns [`INVALID_INDEX`](https://github.com/grovesNL/glow/blob/0d6409eafe2cf3e764b95dbb61fa70c81d201e2b/src/lib.rs#L1852).

Figure out why.

```bash
git clone git@github.com:amethyst/pong_wasm.git
./build.sh
# serve, e.g. simple_web_server
# start chrome and open developer tools, then
# open http://localhost:8000
```

**Comment by azriel91** [comment]
Adding `log::warn!("INVALID_INDEX: {}", name);` to [glow::web_sys`](https://github.com/grovesNL/glow/blob/f497fb198ce9db9d09cdbe0ca7447b3dc55e3195/src/web_sys.rs#L2793) gives:

```rust
WARN /mnt/data/work/github/grovesNL/glow/src/web_sys.rs:2793 INVALID_INDEX: _53_55
```

`_53_55` is the name of the `uniform` from the compiled shader (line 5 of the following snippet):

```glsl
// SPIRV-Cross generated shader:
#version 300 es
const vec2 _19[4] = vec2[](vec2(0.5, -0.5), vec2(-0.5), vec2(0.5), vec2(-0.5, 0.5));

layout(std140) uniform _53_55
{
    vec2 _m0;
} _55;

out vec2 _32;
layout(location = 2) in vec4 _35;
out vec4 _43;
layout(location = 3) in vec4 _44;
out vec4 _46;
layout(location = 4) in vec4 _47;
layout(location = 0) in vec2 _51;
layout(location = 1) in vec2 _70;

void main()
{
    _32 = mix(_35.xy, _35.zw, _19[gl_VertexID] + vec2(0.5));
    _43 = _44;
    _46 = _47;
    vec2 _60 = _51 * _55._m0;
    vec2 _94 = _60;
    _94.y = 1.0 - _60.y;
    gl_Position = vec4(((_94 + ((_70 * _55._m0) * _19[gl_VertexID])) * 2.0) - vec2(1.0), 0.0, 1.0);
    gl_Position.y = -gl_Position.y;
}
```

This corresponds to [`ui.vert`](https://github.com/amethyst/amethyst/blob/wasm/amethyst_ui/shaders/ui.vert) -- shader source has same layout / types.

**Comment by azriel91** [comment]
Recompiling the shader using:

```bash
glslc -c -fauto-bind-uniforms -fauto-map-locations -o amethyst_ui/compiled/ui.vert.spv amethyst_ui/shaders/ui.vert
```

Gives us the same error, but with the shader name:

```
WARN /mnt/data/work/github/grovesNL/glow/src/web_sys.rs:2793 INVALID_INDEX: UiViewArgs
```

```glsl
// SPIRV-Cross generated shader:
#version 300 es
const vec2 _19[4] = vec2[](vec2(0.5, -0.5), vec2(-0.5), vec2(0.5), vec2(-0.5, 0.5));

layout(std140) uniform UiViewArgs {
    vec2 inverse_window_size;
} _55;

out vec2 out_tex_coords;
layout(location = 2) in vec4 tex_coord_bounds;
out vec4 out_color;
layout(location = 3) in vec4 color;
out vec4 out_color_bias;
layout(location = 4) in vec4 color_bias;
layout(location = 0) in vec2 coords;
layout(location = 1) in vec2 dimensions;

void main() {
    vec2 pos = _19[gl_VertexID];
    vec2 coords_base = pos + vec2(0.5);
    out_tex_coords = mix(tex_coord_bounds.xy, tex_coord_bounds.zw, coords_base);
    out_color = color;
    out_color_bias = color_bias;
    vec2 center = coords * _55.inverse_window_size;
    center.y = 1.0 - center.y;
    vec2 final_pos = ((center + ((dimensions * _55.inverse_window_size) * pos)) * 2.0) - vec2(1.0);
    gl_Position = vec4(final_pos, 0.0, 1.0);
    gl_Position.y = -gl_Position.y;
}
```

**Comment by azriel91** [comment]
Quite sure the crash is it's relevant, based on these lines in the `useProgram` stack trace:

```rust
// ..
gfx_hal::device::Device::create_graphics_pipelines::hcfc28eef27d84819   @   06e44cc6-18399:119
amethyst_rendy::pipeline::PipelinesBuilder<B>::build::hff695b9caaf339f1 @   06e44cc6-1556:105
amethyst_ui::pass::build_ui_pipeline::h54126ef4d0170670 @   06e44cc6-776:837
// ..
```

In `glow`, that call likely corresponds to [`web_sys.rs#L682`](https://github.com/grovesNL/glow/blob/f497fb198ce9db9d09cdbe0ca7447b3dc55e3195/src/web_sys.rs#L682). The `WebGl2RenderingContext` implementation delegates to [`web_sys::use_program`](https://docs.rs/web-sys/0.3.37/web_sys/struct.WebGl2RenderingContext.html#method.use_program)

**Comment by jaynus** [comment]
Does `DebugLines` pass work? 

I suspect this may be due to having a single value uniform, and the gl backend conversion is failing.

**Comment by azriel91** [comment]
Yeap the `DebugLines` pass works. This one's difficult.

**Comment by azriel91** [comment]
Yeap the `DebugLines` pass works. This one's difficult.

**edit:** Got more useful logging:

```
WARN /mnt/data/work/github/gfx-rs/gfx/src/backend/gl/src/device.rs:818
Log: Varyings with the same name but different type, or statically used varyings in fragment shader are not declared in vertex shader: _24
```

**Comment by azriel91** [comment]
Turns out that last log line really means what it says -- the `out` variable names (and types) from a preceeding shader must match the variable names for the subsequent shader.

#2207 updates the shaders in `amethyst_ui` to do so.

Pong WASM in chrome:

![pong_wasm](https://user-images.githubusercontent.com/2993230/78204501-2c2aca00-74f6-11ea-8608-3cc1b02d36da.png)
