### ISSUE TITLE
[BUG] Only the last TileMap created is visible

### ISSUE THREAD

**Issue by GGalizzi** [amethyst/amethyst#2210]
## Description

If you create more than one `TileMap` Entity, only the last one is visible, while any other created previously to that one are not visible.

## Reproduction Steps

1. Create two TileMap entities
2. Place one at some coordinate, the other at a different coordinate.
3. You'll only see one, the one that was created last.

You can easily do this with the current `tiles` example, duplicating the map being rendered, but changing its transform.

## What You Expected to Happen

Both `TileMap`s visible at their corresponding positions.

## What Actually Happened

Only one `TileMap` is visible.

## Your Environment

1. Operating System: Windows 10
2. Version of Amethyst: Master

## Additional Context

I'm trying to figure out `pass.rs` for tiles, but I have no experience with rendy and negligible experience in graphics programming, having said that, it looks to me that there is only one `TileMapArgs`, containing the dimensions and transform of the map to be rendered, so its values are from the last iteration of the `join` loop,  and so both TileMaps are rendered at the same spot with same sizes. But I have no idea where to go from here.

https://github.com/amethyst/amethyst/blob/6453a83c4dc5b6152d35004d64931f5e09f98e65/amethyst_tiles/src/pass.rs#L214

**Comment by plorefice** [comment]
Can confirm, I'm experiencing this issue right now.

In my case, I have two `TileMap` entities, and only the `Transform` component of the second one is taken into account during rendering, which results in the maps overlapping (both maps have the same dimensions in my case).
