### ISSUE TITLE
WASM: Split audio from `BounceSystem`

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#2215]
While audio hasn't been implemented (https://github.com/amethyst/amethyst/issues/2195), it should still be possible to get the rest of pong to work.

[`BounceSystem`](https://github.com/amethyst/pong_wasm/blob/5929d4f/src/systems/bounce.rs) currently uses 3 audio related resources:

```
Read<'s, AssetStorage<Source>>,
ReadExpect<'s, Sounds>,
Option<Read<'s, Output>>,
```

These can be split to a separate system, which plays the sound when a `BounceEvent` happens.

**Comment by AlisCode** [comment]
PR at https://github.com/amethyst/pong_wasm/pull/2

**Comment by chemicstry** [comment]
Merged https://github.com/amethyst/pong_wasm/pull/2
