### ISSUE TITLE
WASM: Split audio from `WinnerSystem`

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#2216]
While audio hasn't been implemented (https://github.com/amethyst/amethyst/issues/2195), it should still be possible to get the rest of pong to work.

[`WinnerSystem`](https://github.com/amethyst/pong_wasm/blob/5929d4f/src/systems/winner.rs) currently uses 3 audio related resources:

```
Read<'s, AssetStorage<Source>>,
ReadExpect<'s, Sounds>,
Option<Read<'s, Output>>,
```

These can be split to a separate system, which plays the sound when a `ScoreEvent` happens.

This is similar to https://github.com/amethyst/amethyst/issues/2215, so perhaps use the same system, and the event may be an enum:

```rust
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum PongEvent {
    Bounce,
    Score,
}
```

**Comment by AlisCode** [comment]
PR at https://github.com/amethyst/pong_wasm/pull/2

**Comment by chemicstry** [comment]
Merged https://github.com/amethyst/pong_wasm/pull/2
