### ISSUE TITLE
Texture Samplers

### ISSUE THREAD

**Issue by msiglreith** [amethyst/amethyst#222]
The renderer passes create samplers themself with fixed settings (e.g `WrapMode::Clamp`). This causes wrong results for some scenes, which require different samplers.

**Comment by msiglreith** [comment]
Would be also preferable to set the filtering method manuelly, which is currently set to `Scale` (nearest-neighboring sampling). 😄

**Comment by Xaeroxe** [comment]
@ebkalderon Is this addressed by #233 ?

**Comment by Aceeri** [comment]
I think this was fixed, we have a builder method `with_sampler` now so? If it wasn't just re-open.
