### ISSUE TITLE
[BUG] Sprites don't update for 1 frame

### ISSUE THREAD

**Issue by arlyon** [amethyst/amethyst#2224]
## Description

I am creating a procedural world. A world gen system maintains a list of entities with a `Terrain` component and a `Position` component (that abstracts the world coordinates from the screen space). Terrain has a `Variant` which is a simple enum for a few different terrain types.

The render system iterates through the Terrain components, converts the `Position` to a `Transform`, and updates the entities index into the sprite map according to the `Terrain`'s variant. It seems, however that the transform is updated a frame before the sprite (or rather the sprite a frame after the transform), despite them being mutated at the same time.

https://gfycat.com/belovedgloriousalaskajingle

Notice the flickering as the transforms are updated, while the sprites lag behind a frame. Relevant code, where sprite is a `SpriteRender`.

```rust
for (terrain, pos, trans, sprite) in
    (&terrain, &positions, &mut transforms, &mut sprites).join()
{
    let mut t = cam_trans + (pos.trans - cam_pos.trans) * TILE_SIZE;
    t.z = 0.0;
    log::debug!("{} {} {}", t.x, t.y, t.z);
    trans.set_translation(t);
    sprite.sprite_number = match terrain.variant {
        TerrainVariant::Air => 5,
        TerrainVariant::Grass => 0,
        TerrainVariant::Dirt => 3,
        TerrainVariant::Water => 4,
    };
}
```

This is a dealbreaker for me; alternatives such as firing off events to update the transforms the frame after are an ugly workaround.

## Reproduction Steps

Repo here: https://github.com/arlyon/rustown
Reproduced on macOS and Windows.

Simply cargo run, then press G to generate. This sends an event to the generation system and the render system to update. The render system depends on the generation system so despite receiving the event on the same frame, the render system runs after.

## What You Expected to Happen

I expect sprites to update the frame that they are changed, not the frame after. 

## What Actually Happened

Sprites update a frame after their index into the sprite sheet is changed.

## Screenshots and Logs

Video above.

## Your Environment

1. Operating System: macOS + Windows
2. Operating System Version: Catalina + 10
3. Version of Amethyst: 0.15.0

**Comment by mrhatman** [comment]
I don't see why this is happening but a few suggestions to improve things:

- Move to a state specific dispatcher for most of your systems . This might fix the issue ( there is a chapter is the book about this topic)
- The engine has a tile system already implemented, it is fairly well implemented.
