### ISSUE TITLE
[BUG] GLTF loader cannot load assets with armatures exported from Blender 2.82

### ISSUE THREAD

**Issue by moses-palmer** [amethyst/amethyst#2225]
## Description

When loading GLTF assets exported from _Blender 2.82_ using armatures for animation, the meshes are distorted and unusable.

## Reproduction Steps

1. Open [this file](http://newrainsoftware.com/gltf/model.blend) in _Blender 2.82_.
2. Export it to _GLTF_ (like [this](http://newrainsoftware.com/gltf/model.glb)). Make sure to enable _Geometry / Modifiers_ and _Animation / Skinning_.
3. Load it as a GLTF asset.

## What You Expected to Happen

I expect the model to be rendered like when uploading it to [here](https://gltf-viewer.donmccurdy.com/).

## What Actually Happened

I cannot see the mesh. If I perform a new export using a [file with no armatures used](http://newrainsoftware.com/gltf/model-no-armature.blend) I can see it.

## Your Environment

1. Operating System - Linux
2. Operating System Version - Ubuntu 19.10
3. Version of Amethyst - 0.15.0

**Comment by azriel91** [comment]
heya, no you've already provided good information :bowing_man:.

There hasn't been work on the `amethyst_gltf` crate for a while, and I'm not sure if anyone who is still around has the knowledge, so in honesty the best step for this to progress is to try and investigate / solve it yourself. If you manage to, we would be happy to take the fix

(sorry it's not the answer you may be looking for)

**Comment by moses-palmer** [comment]
Sorry for the late response---I never got a notification from github.

If that is the case, what do people use for storing model assets? I assumed that would be GLTF.
