### ISSUE TITLE
WASM: Document How To Build an Amethyst Project With WASM Support

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#2227]
As per title. The best place to start is to look at the [`pong_wasm`](https://github.com/amethyst/pong_wasm) repository.

Perhaps add this to the book.

**Comment by azriel91** [comment]
This has been added in #2257, and is online at <https://book.amethyst.rs/wasm/wasm_support.html>.

**Comment by cmizzi** [comment]
Maybe this documentation/project must be updated ? #2516
