### ISSUE TITLE
Flipped png images

### ISSUE THREAD

**Issue by msiglreith** [amethyst/amethyst#223]
Images loaded with the default image loader of the assets manager are vertically flipped.

**Comment by Aceeri** [comment]
Wasn't there some old issue/PR about this?

**Comment by torkleyy** [comment]
@Aceeri https://github.com/amethyst/amethyst/pull/141 is about it being the other way around IIRC

**Comment by Xaeroxe** [comment]
This is no longer a problem on the current master, closing this issue.

**Comment by Xaeroxe** [comment]
My bad.  Issue was reported again by @jojolepro.

**Comment by Xaeroxe** [comment]
The issue reported by @jojolepro seems to actually be about horizontal flipping rather than vertical flipping, so I'll close this again.
