### ISSUE TITLE
[MAINTENANCE] SunLight Example Request

### ISSUE THREAD

**Issue by whizsid** [amethyst/amethyst#2234]
## Note

I have googled a lot about amethyst sunlight rendering. But I couldn't find a useful resource. Can you implement an example to show the sunlight rendering? 

## Description

My object is at `(0.0,0.0,0.0)` position. My sun object is at `(0.0,1000.0,0.0)` with intensity of `1000.0` and` std :: f32 :: consts :: PI` angle. But my object is still in black. Then I replaced 'Sunlight' for 'Pointlight' and it showed as expected.

Can you provide any working example for sunlight?

**Comment by Neo-Zhixing** [comment]
I can't see it mentioned anywhere in the docs. Had to dig into the source code. Based on [PBR Fragment Shader](https://github.com/amethyst/amethyst/blob/master/amethyst_rendy/shaders/fragment/pbr.frag) I'm only seeing shading implementation for `SpotLight`, `DirectionalLight` and `PointLight`. I'm guessing that sun light wasn't implemented?

For 3DShadedRenderer, I'm only seeing `PointLight` and `DirectionalLight` implemented in the [shader](https://github.com/amethyst/amethyst/blob/master/amethyst_rendy/shaders/fragment/shaded.frag)

**Comment by whizsid** [comment]
@Neo-Zhixing Sunlight is in the [docs](https://docs.rs/amethyst_renderer/0.10.4/amethyst_renderer/struct.SunLight.html) . I have asked about this issue in their discord chat. They informed me to use a big `SpotLight` as an alternative.  `SunLight`was not implemented yet and not a prioritized task.
