### ISSUE TITLE
[BUG] Custom Game Data example broken

### ISSUE THREAD

**Issue by sc312** [amethyst/amethyst#2235]
## Description

When trying to run the custom game data example code it fails with the error 'No such system registered ("input_system")'.

## Reproduction Steps

1. Clone amethyst repo
2. Run 'cargo run --example custom_game_data --features vulkan'
3. Wait for it to compile

## What You Expected to Happen

The example would work and I could learn how to use custom game data.

## What Actually Happened

It didn't work.

## Screenshots and Logs

![image](https://user-images.githubusercontent.com/37505939/79150076-0f2cab80-7dc0-11ea-88db-4993da05d06a.png)

## Your Environment

1. Operating System - Windows 10 Pro
2. Operating System Version - 1909
3. Version of Amethyst - 0.15.0

**Comment by sc312** [comment]
I have modified my working Pong code (which I only slightly changed from the walkthrough in the book) and the same error occurs.
![image](https://user-images.githubusercontent.com/37505939/79152186-a810f600-7dc3-11ea-831b-86e99c22e2f9.png)
There's the code to build the game data. As you can see I have added the input bundle and I also have the Paddle System which requires the input_system and that worked fine before making this change.

**Comment by SimonCadge** [comment]
I've figured out why the example code didn't work. Since the UiBundle relies upon the InputBundle but the UiBundle is defined first the UiBundle would throw an error. I don't know why this is a problem with custom game data but not when we use standard game data, but I've fixed it and I'm making a pull request to make the change.
The input bundle is defined before the ui bundle in my own code which means that my problem must be something different, but hopefully I can fix it myself.

**Comment by SimonCadge** [comment]
https://github.com/amethyst/amethyst/pull/2239

**Comment by thorlucas** [comment]
I actually ran into this issue as well — it is what @SimonCadge said. You must include the InputBundle before the UiBundle. I have no idea why this is the case (they should check for dependencies after everything has been registered, surely?)

**Comment by Okarin99** [comment]
I also run in this Problem. It isn't explained in the book https://book.amethyst.rs/stable/pong-tutorial/pong-tutorial-05.html. It just says that the UIBundle relies on the InputBundle, but not that you have to create the InputBundle first.

**Comment by lberrymage** [comment]
Right beneath [here](https://book.amethyst.rs/stable/pong-tutorial/pong-tutorial-05.html#adding-a-scoreboard) in the book it says

"Finally, add the `UiBundle` after the `InputBundle`"

and [the docs for UiBundle](https://docs.amethyst.rs/stable/amethyst_ui/struct.UiBundle.html) say

"Will fail with error 'No resource with the given id' if the InputBundle is not added."

I'd like to know whether this is considered sufficient or if we can make this situation better. This problem (if we can call it that) is documented after all, and the error message given isn't ambiguous to someone who knows what a bundle is at its core. However, I wonder if we can have some sort of compile-time check for this. I think that might be a conversation for a whole other GitHub issue though; the original one here seems to be solved.

**Comment by Bastczuak** [comment]
@SimonCadge I am stuck at the same problem now. Your merge request is already in the master right? But this runtime error still shows up when running `custom_game_data` example by adding `input_system` as a dependency to `ExampleSystem`.
