### ISSUE TITLE
Moving another window in front of the window on macOS / metal causes the program to become unresponsive

### ISSUE THREAD

**Issue by thorlucas** [amethyst/amethyst#2236]
## Description

If you are on macOS, if you lose sight of the screen (i.e. you move another window in front of it, or tab to a different desktop), you cannot return. There will be no input, no nothing. The console spams "[WARN][gfx_backend_metal::window] No frame is available." The only way to get it back is to quit and rerun the application.

This may be a duplicate of #1927, but they seem to imply that the bug only occurs with fullscreen windows. This bug is more general — it occurs any time the amethyst window is covered up.

## Reproduction Steps

1. Make a program on macOS.

2. Drag another screen on top of the app

3. Try to return

## Screenshots and Logs

https://i.imgur.com/OSeIrxI.mp4

```
[WARN][gfx_backend_metal::window] No frame is available
```

## Your Environment

macOS Catalina 10.15.14

Amethyst 0.15.0

**Comment by Neo-Zhixing** [comment]
Did a bit of debugging today
The problem traces down to this:

In `rendy-wsi` it calls gfx_hal::Swapchain::acquire_image:

```rust
    pub unsafe fn next_image(
        &mut self,
        signal: &B::Semaphore,
    ) -> Result<NextImages<'_, B>, gfx_hal::AcquireError> {
        let index = gfx_hal::Swapchain::acquire_image(
            // Missing swapchain is equivalent to OutOfDate, as it has to be recreated anyway.
            self.swapchain
                .as_mut()
                .ok_or(gfx_hal::AcquireError::OutOfDate)?,
            !0,
            Some(signal),
            None,
        )?
        .0;

        Ok(NextImages {
            targets: std::iter::once((&*self, index)).collect(),
        })
    }
```

When the backend is `gfx_backend_metal`, in `window.rs`:

```rust
            AcquireMode::Oldest => {
                let frame = match self.frames.get(oldest_index) {
                    Some(frame) => frame.inner.lock(),
                    None => {
                        warn!("No frame is available");
                        return Err(hal::AcquireError::OutOfDate);
                    }
                };

```

**Comment by Neo-Zhixing** [comment]
Potentially related: https://github.com/gfx-rs/gfx/issues/3195

**Comment by tsal** [comment]
may also be the same issue as #1927

**Comment by chemicstry** [comment]
It seems that this would be resolved by moving rendy to the new gfx-hal swapchain model. This is also relevant for wasm branch (gl window resizing). @bobtwinkles was considering working on this, but I don't know if that went anywhere?

**Comment by bobtwinkles** [comment]
I started looking in to it, but pretty quickly ran into some deep weirdness in Rendy. I can write up my findings later today if there's interest, but tl;dr we need to rework how Rendy handles out of date swapchains. Right now Rendy just explodes when the swapchain is out of date, which is unacceptable because the window surface could change size in the time between the last resize event and the image acquire.

**Comment by tsal** [comment]
https://github.com/gfx-rs/gfx/issues/3195 - for reference on the above

**Comment by inosms** [comment]
I am experiencing the same issue with Catalina 10.15.1 (Intel Iris 1536 MB on a MacBook 2013). 
Switching windows (or sometimes states) causes this. Resizing the window 'revives' it.
I guess this is because the swapchain gets dropped and rebuilt then.

Excerpt from the log:
```
[INFO][gfx_backend_metal::window] dropping Swapchain
[INFO][gfx_backend_metal::window] dropping Frame
[INFO][gfx_backend_metal::window] dropping Frame
[INFO][gfx_backend_metal::window] dropping Frame
[INFO][gfx_backend_metal::window] build_swapchain SwapchainConfig { present_mode: Fifo, composite_alpha: OPAQUE, format: Bgra8Srgb, extent: Extent2D { width: 2560, height: 1510 }, image_count: 3, image_layers: 1, image_usage: COLOR_ATTACHMENT }
```

Is there any progress with this? If not, can I have some pointers as to where I can help in fixing this? How involved is the upgrade to the new gfx-hal swapchain model?

**Comment by ishche** [comment]
https://github.com/gfx-rs/gfx/issues/3195#issuecomment-606154055
Does it mean a deadlock for this issue?

**Comment by TransmissionsDev** [comment]
Still having issues with this, are there any solutions?

**Comment by ezpuzz** [comment]
Everyone in this thread please try the examples on master to see if they resolve your issue.  Rendy has been updated with newer gfx and winit.

**Comment by adammitchelldev** [comment]
I'm encountering this issue on master as of today.

**Comment by ezpuzz** [comment]
thanks for the report @adammitchelldev this is likely due to rendy's gfx dependency being out of date.  It's a kind of tough fix because the shader pipeline API was moved around a lot between rendy's version and the stable gfx release.
