### ISSUE TITLE
Wrong multisampling for rendering pipelines

### ISSUE THREAD

**Issue by msiglreith** [amethyst/amethyst#224]
Renderpasses don't have access to the sampling settings of the config. Therefore the multisampling is disabled for all created PSOs. The information should be passed on pass creation and corresponding sampling fields filled in for the rasterizer state.

**Comment by Xaeroxe** [comment]
cc @ebkalderon @omni-viral 
Is this still a problem?

**Comment by ebkalderon** [comment]
@Xaeroxe Yes, this is still the case.
