### ISSUE TITLE
[BUG] ECS and other types are hidden from documentation

### ISSUE THREAD

**Issue by alercah** [amethyst/amethyst#2242]
In the [generated API docs](https://docs.amethyst.rs/stable/amethyst/), the modules `crate::core::{ecs,shred,shrev}` are re-exported, but they are not themselves public. As a result, types such as the critical `System` and `Entity` types are missing from the API reference, as can be seen on [this function](https://docs.amethyst.rs/stable/amethyst/prelude/trait.Builder.html#tymethod.build): the `Entity` type is not hyperlinked because it isn't exported on its true path.

This can likely be fixed by using the [`#[doc(inline)]` attribute](https://doc.rust-lang.org/rustdoc/the-doc-attribute.html#docno_inlinedocinline).

**Comment by azriel91** [comment]
Heya, we're in the process of fixing the automatic docs publishing, but in the meantime the documentation for all dependencies are now published. For example `specs`' documentation is here: <https://docs.amethyst.rs/stable/specs/>
