### ISSUE TITLE
Input manager

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#225]
I just reviewed the input manager and I think there are some problems:

- [ ] Don't store a `HashMap` of pressed keys, but of keys mapping to their state

[Link](https://github.com/amethyst/amethyst/blob/develop/src/ecs/resources/input.rs#L32)

I think this will increase performance because we don't add/remove them all the time.

- [ ] Rename `key_down` to `key_pressed`

because `key_down` is widely used for "the key was pressed this frame".

---

It's the same for #181, so I'll fix it after it's merged.

**Comment by Emilgardis** [comment]
I've tried addressing your first point. What you will find is that what needs to happen is that `VirtualKeyCode` gets an `#[repr(u8)]`

https://github.com/tomaka/winit/issues/87
some discussion here: https://github.com/amethyst/amethyst/pull/114

**Comment by derekdreery** [comment]
I can add the `key_down -> key_pressed` change in #181 if you like?

**Comment by Emilgardis** [comment]
It should be added (by rebasing) when that pr is merged

**Comment by Xaeroxe** [comment]
@torkleyy I think we determined in https://github.com/amethyst/amethyst/pull/247 that we weren't going to store the key state in the way described here due to it requiring a larger copy every frame.  I also addressed your second point in that PR.  How do you feel about closing this issue?
