### ISSUE TITLE
WASM: Publish book and API docs

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#2260]
Currently the `wasm` branch's book and API documentation is not published, making it hard to use.

Publish these so that users may access the docs online.

**Comment by azriel91** [comment]
Book is published at https://book.amethyst.rs/wasm/.

Docs can be built (#2261), but are not yet published (needs work on `.gitlab-ci.yml`).

**Comment by dcormier** [comment]
Is anyone aware that trying to view the wasm book results in a `500` error?

**Comment by Blisto91** [comment]
@dcormier the wasm book was either never hooked up to the book publishing CI or was pulled out a while back.
Don't know the specifics
