### ISSUE TITLE
[FEATURE MODIFICATION] Simplier image rendering (without spritesheet)

### ISSUE THREAD

**Issue by SET001** [amethyst/amethyst#2269]
## Feature

texture rendering

## Change

add ability to render texture without spritesheet

## Reason

Currenlty, I'm having tens of textures, all in its own file. To use it I need tens of `ron` files with image sizes and creating tens of spritesheets which is useless in case where I need to use whole image, not a pat of it.

## Impact
not sure

## Additional Notes

I see relevant issue here https://github.com/amethyst/amethyst/issues/1086 but I'm not sure where it is all ended and how to use it. None of discussed there `DrawSprite` and `DrawTexture` can be found in docs. Following commit in that issue I found `DrawFlat2D` but have no glue how to use it.

**Comment by viridia** [comment]
I need this too. I have a large background image, there's no benefit to be gained by spriting this. This is also useful when doing repeating/tileable textures.

**Comment by edgarssilva** [comment]
Yes, you would think just rendering a simple Texture would be easier but guess not been looking around for hours and I'm starting to think there is no way.

**Comment by Nuclearfarts** [comment]
There any progress on this?

**Comment by jojolepro** [comment]
Feel free to open a pull request with the changes you need :+1:
