### ISSUE TITLE
[NEW FEATURE] Expose keyup and keydown data in InputHandler

### ISSUE THREAD

**Issue by szunami** [amethyst/amethyst#2274]
## Description

For many use cases, you care not just which keys are down in this frame, but which keys are *newly* down or *newly up*. 

## What problem does this solve? What need does it fill?
For many use cases, you care not just which keys are down in this frame, but which keys are *newly* down or *newly up*. For example, you may want to release a charging shot when a player releases the shoot button, like in Megaman / Metroid.

## Describe the solution you'd like
The InputHandler exposes method `keys_that_became_down` and `keys_that_became_up`, which return `Iterators` over `VirtualKeyCode`.

## Describe alternatives you've considered
This could likely be solved by consuming `ButtonPressed` and `ButtonReleased` events.

## Additional context
This should probably be mirrored for `MouseButtons` and `ControllerButtons`; unclear what this looks like for `ControllerAxes`.

This is my first FR on this repo, and I'd be happy to contribute this functionality.

**Comment by ab0v3g4me** [comment]
Well you can get the last key by using:
```rust
input.keys_that_are_down().last();
```
I don' think it would make much sense for this ? You can implement it in your own system of course.

**Comment by szunami** [comment]
The goal isn't to get the `last` key, but rather to identify keys that are down / up as of this frame that weren't in that state last frame. But sure, understand if there isn't desire for this now.
