### ISSUE TITLE
Find a way to provide render graph data without unsafe code

### ISSUE THREAD

**Issue by chemicstry** [amethyst/amethyst#2275]
Rendy graph has a user definable generic type (auxiliary data) which was used to pass `World` into render passes. In legion resources are separate from the world and now we need to pass `World` and `Resources`. This is impossible because you can't use composite types with lifetime (references) as auxiliary data.

Simplified issue: https://github.com/rust-lang/rust/issues/51567

This is temporarily resolved by unsafely making lifetime static. It is safe as long as references to world or resources are not saved in render passes. https://github.com/amethyst/amethyst/blob/legion_v2/amethyst_rendy/src/system.rs#L35

Figure out how to make it safely.

**Comment by ezpuzz** [comment]
As long as we document this and our own render plugins don't violate the safety I think this is not required for 0.16 release.

**Comment by willolisp** [comment]
Hi there! I'd love to help you guys with this one, but, quick disclaimer, I'm new to both Rust and Amethyst, so I'd probably have to ask a lot of dumb questions before getting by feet wet (like why exactly doesn't rendy accept lifetimed composite types as aux data... by taking a quick look at rendy, all i noticed was the ' ?Sized' bound for the generic type).
If you feel this is a good task for a rust noob, and if you think you've got the time for a lot of silly questions, let me know and I'll do my best to help :).

**Comment by willolisp** [comment]
So, I played a bit with this issue in the last couple of days, but didn't make much progress. I guess I still don't understand the reason why it's impossible to use lifetimed structs as auxiliary data.

When analysing the[ provided simplified issue](rust-lang/rust#51567), it makes sense to me not to want a lifetimed `Logger`, as the `Record`'s lifetime is only relevant when running `Writer.write` and `Writer` and `Logger` don't keep any references to `Record`. That said, I don't think it'd be impossible to use lifetimed `Records` (or any other lifetimed `T`) with `Logger` or `Writer`.

When considering the issue at hand, it seems to me the auxiliary data type `T` is passed all the way from `Graph` to `DynNode`, to be used on `DynNode.run` and `DynNode.dispose`, but I don't see what on `DynNode` prevents us from using `InternalGraphAuxData<'a>` as auxiliary data type.

Well, I guess all that's to say I still don't get why we can't have lifetimed auxiliary data types :joy: . Any help would be greatly appreciated.

Cheers :).

**Comment by willolisp** [comment]
Hmmm is it because [`RenderState` must also implement `Resource`](https://github.com/amethyst/amethyst/blob/main/amethyst_rendy/src/bundle.rs#L95) , which is `'static` ?
