### ISSUE TITLE
Legion: port amethyst_utils

### ISSUE THREAD

**Issue by chemicstry** [amethyst/amethyst#2279]
Probably would use a refactor on the way: https://github.com/amethyst/amethyst/issues/2277

**Comment by jojolepro** [comment]
taking ownership

**Comment by jojolepro** [comment]
@ab0v3g4me taking ownership of this issue

**Comment by ab0v3g4me** [comment]
#2350

**Comment by chemicstry** [comment]
Fixed by #2350
