### ISSUE TITLE
[BUG] Cannot import DefaultBackend on `empty` feature

### ISSUE THREAD

**Issue by Puciek** [amethyst/amethyst#2284]
## Description

I am trying to make my app support both graphical and non-graphical modes, and so far so good, the code works well and was very easy to split off based of features used with help of `#[cfg(feature = "empty")]` and then building proper game data, and picking the right state accordingly. Problem is that when I try to run the code that works with `vulkan` with `empty` that causes a crash, as apparently `use amethyst::renderer::types::DefaultBackend;` macro doesn't work on `empty`. 

I think that's a bug as imports in rust are not easily made conditional (if I could just gate that use behind #[cfg], I would, but that refuses to work), so having this import fail with one backend, but not the other doesn't seem right. I don't expect it to be able to render anything, quite the opposite - trying to use `DefaultBackend` for `empty` should cause an error, but merely importing it should not.

## Reproduction Steps

1. Put `use amethyst::renderer::types::DefaultBackend;` into your code, do not actually use it anywhere.
2. Try `cargo run --features empty`
3. Observe

## What You Expected to Happen

I expect the project to run just fine.

## What Actually Happened

An error:

```
error[E0432]: unresolved import `amethyst::renderer::types::DefaultBackend`
  --> src\main.rs:85:13
   |
85 |         use amethyst::renderer::types::DefaultBackend;
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `DefaultBackend` in `renderer::types`

error: aborting due to previous error
```

## Possible workaround

Switching back to `cargo run --features vulkan` makes the application work as expected, but goes against the idea of having an application support both `empty` and `vulkan/metal`.

## Your Environment

1. Operating System
Windows
2. Operating System Version
10
3. Version of Amethyst
Master branch (0.15)

**Comment by SarthakSingh31** [comment]
Can you add your Cargo.toml?
If you have a default feature to enable vulkan you might be enabling vulkan and empty at the same time.

**Comment by SarthakSingh31** [comment]
I believe that DefaultBackend being not defined is intentional when more than one backend is enabled. 
https://github.com/amethyst/amethyst/blob/602c818e9e79ffbed588c76fcb9ad9a9a93891d1/amethyst_rendy/src/types.rs#L93-L110
Amethyst can't make a choice as to which backend is default when both vulkan and empty are enabled at the same time.

**Comment by Puciek** [comment]
@SarthakSingh31 I think you misunderstood the issue, I am not trying to build with both vulkan and empty at the same time, those are separate runs - one with vulkan, the other with empty, they are never enabled at the same time.

**Comment by SarthakSingh31** [comment]
@Puciek can you add your Cargo.toml?

**Comment by Puciek** [comment]
@SarthakSingh31 sure, you can have the whole project as a test bed: https://github.com/Puciek/upfire-rust

**Comment by SarthakSingh31** [comment]
https://github.com/Puciek/upfire-rust/blob/1191af7c67b145725086ad78fff5bac9b021452f/Cargo.toml#L22-L27

you have vulkan set as the default feature, so when you do
`cargo run --features empty`
both vulkan and empty are activated at the same time.

**Comment by Puciek** [comment]
@SarthakSingh31 

```
C:/Users/pucie/.cargo/bin/cargo.exe run --color=always
   Compiling upfire v0.1.0 (F:\work\RustProjects\upfire)
error[E0412]: cannot find type `DefaultBackend` in this scope
  --> src\main.rs:94:35
   |
94 |                 RenderingBundle::<DefaultBackend>::new()
   |                                   ^^^^^^^^^^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0412`.
error: could not compile `upfire`.

To learn more, run the command again with --verbose.

Process finished with exit code 101
```

All I did is undo the last comment which commented out vulkan stuff, so the entire listing of main.rs and cargo toml (you have command used in log): https://gist.github.com/cdd31f647dfddf5dfcd84a0ee23ff017

**Comment by SarthakSingh31** [comment]
you haven't imported amethyst::renderer::types::DefaultBackend

**Comment by Puciek** [comment]
@SarthakSingh31 you are right, i must have been somehow tangling them between all the tests, mean coulpa and thanks a million!
