### ISSUE TITLE
anyone use amethyst in WSL?

### ISSUE THREAD

**Issue by nterheoid** [amethyst/amethyst#2286]
the problem is WSL doesn’t support graphics very well currently. 
you need to like remotely map your linux display to windows 10 through tools which implemented X11 protocol.
i tried some tools alreday like xming,vcxsrv,x410, but all them are failed:

```
    Finished dev [unoptimized + debuginfo] target(s) in 7.13s
     Running `target/debug/AAAA`
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.15.0
[INFO][amethyst::app] Platform: x86_64-unknown-linux-gnu
[INFO][amethyst::app] Amethyst git commit: UNKNOWN
[INFO][amethyst::app] Rustc version: 1.41.0 Stable
[INFO][amethyst::app] Rustc git commit: 5e1a799842ba6ed4a57e91f7ab9435947482f7d8
**[INFO][winit::platform::platform::x11::window] Guessed window DPI factor: 1
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unsupported', src/libcore/result.rs:1188:5**
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

i just wonder is anyone there got some successful experience,
or just be told it is impossible.

**Comment by mvlabat** [comment]
I guess WSL experience with graphics applications will become much better when this lands: https://devblogs.microsoft.com/directx/directx-heart-linux/

When I last tried to run my game in WSL I didn't proceed much further myself (that was maybe a year ago).

**Comment by CleanCut** [comment]
I'm going to close this because I don't think there's anything more to be said for now. Please feel to reopen this or open a new issue when the WSL graphics acceleration hits!
