### ISSUE TITLE
[FEATURE MODIFICATION] Handle input key according to physical location of the key

### ISSUE THREAD

**Issue by mashedcode** [amethyst/amethyst#2287]
## Feature

Input Key Mapping

## Change

Handle input key mapping according to their physical location independent of the current keyboard layout.

## Reason

Input keys are usually chosen for their physical location.
But depending on the keyboard layout this yields unexpected behavior for example on a dvorak keyboard layout the keys **,aoe** are in the place of **wasd**.

Therefore if the programmer decides to map `w` the same action should be triggered by `,` in case the user uses dvorak.

One may argue that the user of such a keyboard should remap the keys himself. But even if software key remapping is supported that still means a lot of trouble for the user which essentially is terrible user experience.

Note on software key remapping:

In case the software supports key remapping (a user can remap keys in settings) a user with a custom layout should ideally see `,` mapped to the action that corresponds to `w` even though `w` is the key which is hardcoded. When choosing a new key internally the physical location should be recorded and the correct one according to the layout of the user should be displayed to the user.

## Impact

The a qwerty user would not be impacted by this change at all.
For a user of a custom layout this would be a big plus in terms of user experience as he can use the same keyboard layout for ingame chat as he's using for playing the game without having to remap all keys in the game.

## Additional Notes

Most engines get this wrong but this is actually possible and some games do get this right!

**Comment by Friz64** [comment]
Similar issue: https://github.com/amethyst/amethyst/issues/1847

**Comment by mashedcode** [comment]
Closing in favor of #1847
