### ISSUE TITLE
[FEATURE MODIFICATION] Vsync display option

### ISSUE THREAD

**Issue by RedlineTriad** [amethyst/amethyst#2290]
## Feature

Display options

## Change

Re-add vsync option.

## Reason

The vsync option seems to have been removed at some point but many examples still seem to use it.

## Impact

This should allow for the engine to run at higher refresh rates than the connected monitor.

## Additional Notes

An example of the option being used: [examples/config.ron](https://github.com/amethyst/amethyst/blob/e18c7c8b954424f4c91267e70434a93f4b89f5c5/amethyst_config/examples/config.ron)
The `DisplayConfig` struct (missing vsync option): [src/config.rs](https://github.com/amethyst/amethyst/blob/ea083c38e9247e1e605dd68a69de4533ae9e9e3b/amethyst_window/src/config.rs)

**Comment by AlveLarsson** [comment]
Looks good to me, I can't say if there is any specific reason why it was removed
