### ISSUE TITLE
[NEW FEATURE] Custom shader example

### ISSUE THREAD

**Issue by viridia** [amethyst/amethyst#2291]
## Description

I've gone through the basic tutorials and built the pong game, but now I am at a loss for what to do next. I would like to port one of my old Java games from libgdx to Rust/Amethyst, but the first thing I'll need is to support custom GLS shaders. I use custom shaders for virtually every object, particularly transient effects (shatter, explosion, glow, laser shots, missiles) and particle systems (clouds, debris, fire, water, etc.). (I definitely don't want to make every particle an entity, that would be *way* too much overhead - the shader should be doing all the heavy lifting).

Some guidance on where to start in terms of writing a custom rendering pass (assuming that is the right thing to do) woud be great.

## What problem does this solve? What need does it fill?

Anyone who is interested in making a commercial grade game (something I've been doing since 1983 - retired now) is going to want to use custom shaders for rendering, but looking at the code and examples for Amethyst it's really hard to figure out.

## Describe the solution you'd like

A basic tutorial page that implements a basic custom shader.

If it also incorporated dynamic mesh generation (which is needed for particles) that would be a bonus.

## Describe alternatives you've considered

Abandoning my Rust-based project and switching to Godot :)

**Comment by viridia** [comment]
OK so this blog post is a good start - it explains how to compile the shaders: https://falseidolfactory.com/2018/06/23/compiling-glsl-to-spirv-at-build-time.html

**Comment by ab0v3g4me** [comment]
Take a look at the custom_render_pass example, pretty much the only way you can utilize shaders in amethyst.

**Comment by viridia** [comment]
I am not able to follow that code, sorry. There are a bunch of words that I don't know the definitions for (assemble, plan, layout) in that context.

In any case, I have kind of given up on this project - my goal was to try and port one of my old parallax scrolling games to Rust as a way of learning Rust. But it took me over a week to figure out just how to display a single sprite using an orthographic camera (hint: using the default transform won't work), and even then I can't figure out how to get it to scale the way I want. This is way too much work to be fun. I'm no stranger to vertex buffers and GLSL, but I can't figure this stuff out.
