### ISSUE TITLE
Need a way to reference asset manager from a system

### ISSUE THREAD

**Issue by agmcleod** [amethyst/amethyst#230]
Working on a simple arena fighter game to try out features of amethyst, I started by adding a system that works as an enemy spawner. It uses the delta time to keep count, and spawn an enemy every couple seconds. I've defined assets in the State, but have no way to reference these,   as  the System#run() does not provide any objects that contain that information.

One solution might be to add the asset_manager to the world itself, much like you would any other object. Though this means it would be writable, which I'm not sure makes sense.

**Comment by torkleyy** [comment]
For other users experiencing this, the answer on Gitter was that each type of asset currently is a component.

@agmcleod Did this solve your case?

**Comment by agmcleod** [comment]
@torkleyy The only thing is i'm not sure how to reference that Renderable since it wouldn't be tied to an entity yet :)

**Comment by Xaeroxe** [comment]
Asset Manager structure is going away and being replaced by allowing game devs to initialize structures in `amethyst_assets` instead.  Since this allows you to access assets from systems I'm closing this issue.
