### ISSUE TITLE
[BUG] Download link for square.ttf is not working in pong tutorial

### ISSUE THREAD

**Issue by Forbaya** [amethyst/amethyst#2306]
## Description

The download link for square.ttf gives 404.

## Reproduction Steps

1. Go to https://book.amethyst.rs/stable/pong-tutorial/pong-tutorial-05.html#adding-a-scoreboard
2. Scroll down to "Inside initialise_scoreboard, we're first going to load up a font which we've saved to assets/font/square.ttf (download)."
3. Click on (download)

4. See error 404 on URL https://github.com/amethyst/amethyst/raw/master/examples/assets/font/square.ttf.

## What You Expected to Happen

I expected to be able to download square.ttf font.

## What Actually Happened

Got a 404.

**Comment by ab0v3g4me** [comment]
We are currently in movement of reorganizing the `examples` directory, primarily the `assets` one. 

Here's the path to the font now: https://github.com/amethyst/amethyst/blob/master/examples/pong_tutorial_06/assets/font/square.ttf

Soon each example will have it's own asset directory.
