### ISSUE TITLE
Mouse position and DPI

### ISSUE THREAD

**Issue by yancouto** [amethyst/amethyst#2307]
Hello!

I think I've been hitting exactly this same issue as #1241. When using my large monitor, I see this in the logs:
```
Guessed window DPI factor: 1.25
```

And then the mouse position gets "out of sync" with the actual position on the screen by exactly this factor.

So I have a question: is the DPI scaling supposed to be transparent to us users when accessing mouse positions?
- If so, then this is probably a bug that needs fixing.
- If not, then how do I track the current DPI? (In order to take that into account.) I see `WindowEvent::HiDpiFactorChanged` when reading [this](https://docs.amethyst.rs/stable/amethyst_rendy/rendy/wsi/winit/dpi/index.html), and tried handling that event in my game state, but it does not show up. What is the correct way of tracking DPI?

_Originally posted by @yancouto in https://github.com/amethyst/amethyst/issues/1241#issuecomment-643674858_

(Re-opened as a new issue for more visibility, also I can't reopen the old issue.)

Repro: I can repro this consistently on [my game](https://github.com/yancouto/psycho_rust), doesn't seem to be related to the game. I can build a small project with a minimum repro if necessary.

**Comment by Blisto91** [comment]
Hi there! Sorry for the wait.

I would like to try and look into this when i've got the time.
I'll keep you updated if i figure something out.
