### ISSUE TITLE
Initial Android support

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#231]
As mobile/tablet games become pretty popular (40% of the games market in 2016), it's important for Amethyst to support the Android platform.

This issue tries to focus on getting initial support, the overall process could be tracked as a project (probably as cross platform support in general?).

These are the first steps towards Android support:

- [ ] Support context creation on most Android devices (https://github.com/tomaka/glutin/issues/861)
- [ ] Provide touch-friendly input mechanisms
- [ ] Abstract away savestates and other files which will be modified
- [x] Merge the future asset system which provides a default cross-platform storage

**Comment by derekdreery** [comment]
`glutin::WindowEvent` has a `Touch` variant.

**Comment by torkleyy** [comment]
Constant buffers are not supported by OpenGL ES, we need a workaround there. 
The old renderer creates constant buffers [here](https://github.com/gfx-rs/gfx/blob/8f9b09c45/src/render/src/factory.rs#L149), not sure about the new renderer.

Thanks to @ozkriff for the research on this!

**Comment by ebkalderon** [comment]
@torkleyy This definitely does need to be refactored. I'm looking into possible alternatives.

**Comment by torkleyy** [comment]
@ebkalderon Great, thanks!

**Comment by ebkalderon** [comment]
One possible solution to the constant buffers problem is to have the `EffectBuilder` determine whether we are using OpenGL ES, and if so, to silently split the constant buffer's fields into individual uniforms somehow, probably through some `#[cfg]` trickery. This leaves the GLSL out of date, though, and I'm not too keen on performing regex on the GLSL. Thoughts?

**Comment by kvark** [comment]
Why not provide the same data in both constant buffers and uniforms on the Rust side, similarly to how some of the gfx-rs examples do it?

**Comment by torkleyy** [comment]
Sounds difficult but does anybody have an idea how to handle input cross-platform? Considering that Android controls work very different from desktop, I'm not sure how one would go about that.

cc @Xaeroxe

**Comment by Xaeroxe** [comment]
Android controls are so different from desktop controls I'm not sure if it's useful to abstract over them like that.  Some mobile games use emulated buttons and joysticks but in my opinion that's far from an ideal solution.  If at some point we feel it would help we can add support for that kind of emulation, but I would consider abstraction over input in this way to be a low priority.

**Comment by torkleyy** [comment]
I think it would already be helpful to have something like dragging on the touch screen setting some axis value. I mean that's what all the input abstraction is about, right?

**Comment by Xaeroxe** [comment]
I actually disagree mostly because devices can support multiple touch points so it'd probably be easier to report each touch point as a set of coordinates, and possibly report the "motion" of each touch point.

**Comment by torkleyy** [comment]
I probably should have expanded my comment a bit. What I'm asking for is that the user should be able to place something like a draggable D-Pad which is able to write axis values. The main reason is that it should be rather easy to run the game on any platform. One problem I see with this is that we don't really know if there has been a movement of the D-Pad or a movement somewhere else when we receive such a motion event. Which somehow reminds me of "consuming" input events. So I'm really not sure whether or not our current solution works out that well.

**Comment by Xaeroxe** [comment]
I think it'd probably be easier to address that idea as soon as we have our UI framework in place as I'd like the D-Pad to be drawn by the UI framework and then have a "virtual D-Pad" object interact with axes in the InputHandler.  Perhaps in order to accommodate this I should introduce "unbound" axes whose values can be modified programmatically (either by the engine or the game author).

Another thought that just occurred to me is it would be nice to have a way to abstract over touching something on a phone and clicking on it on the desktop.  That would be helpful for point and click games that get mobile ports, or even just menus for other games.

**Comment by fhaynes** [comment]
Captured the User Story [here](https://openproject.amethyst-engine.org/projects/8/work_packages/61/activity).

**Comment by fhaynes** [comment]
Closing this due to age and lack of progress. This will be properly scoped and planned and put on the roadmap, as there is demand for it.
