### ISSUE TITLE
Rendy Overhaul

### ISSUE THREAD

**Issue by AlveLarsson** [amethyst/amethyst#2322]
This issue is meant to track fixes and upgrades to Rendy.  Rendy currently needs many improvements. Let's add to this list:

- [ ] Custom shaders need 400+ lines of code. [Forum discussion](https://community.amethyst.rs/t/rendering-runtime-api-types-rethink/298/25)
- [ ] Program unresponsive when window is not visible #1927 #2236 
- [ ] Ability to add uniforms to shaders without rewriting the pipeline

**Comment by bonsairobo** [comment]
Just want to say that I would love the ability to add uniforms to my shaders without rewriting the pipeline! I know that there are probably a lot of other considerations involved in this issue, but if you could prioritize the ability to customize the set of uniforms, that would be greatly appreciated :)

Specifically, I wrote a render plugin for triplanar texturing that just implements the `RenderBase3D` trait, but I want the ability to scale my textures on a per-instance (or per-mesh) basis. Right now the scale factor is hard coded in the shader.

**Comment by CleanCut** [comment]
> I would also be willing to contribute a PR specifically for my use case if that seems OK with the team.

With the caveat that rendering is not my area of expertise, I think your contribution is a good idea!  As a volunteer organization, we are always on the lookout for people willing to help.  Please go ahead and let's see what it looks like.  If you have details that you want to discuss with folks before diving into the code, then I suggest opening a new issue as a place for that discussion.

If things go well, perhaps you would like to join the effort to help maintain the current state of `rendy`/`amethyst_renderer` in general?  We don't have any active maintainers for the current code that I'm aware of (apologies if there are any efforts going on that I'm unaware of!), and maintaining our current code is vital in the meantime even if an overhaul or rewrite is done later.

/cc @Frizi @zakarumych @termhn -- some folks with relevant experience

**Comment by bonsairobo** [comment]
@CleanCut No promises yet, but I'll definitely do some hacking around in the renderer and see what it will take. I probably can't be on the hook for maintenance, but I'm happy to make contributions when I need new functionality.

**Comment by chemicstry** [comment]
I'll chime in my opinion here too.

From what I gathered in old forum posts and from my personal experience with renderer I can say that biggest friction is amethyst_rendy not the rendy itself (although I don't know much about it). The general idea was to move to data driven renderer and drop all hardcoded desricptors such as `Material`. The ideal case would be shader generation as other fancier engines have, but until then an intermediate step with shader reflection (partly implemented in rendy) would be a nice feature. I imagined it as defining all required data in the shader (naming convention?) and renderer should plug all the data from the world automatically, with only additional code being a mapping function for non-pod types.

**Comment by CleanCut** [comment]
> ...then I suggest opening a new issue as a place for that discussion.

I should have also mentioned the [Amethyst Discord server](https://discord.gg/amethyst)!  I think it is an even more active place for discussion than GitHub.  Though I rather like that GitHub issues don't scroll away and get lost. 😄

**Comment by khionu** [comment]
We try to encourage design discussions to happen on the forums, for the sake of async communication across timezones

**Comment by bonsairobo** [comment]
I started this topic where I propose (and solicit advice on) some incremental changes to amethyst_rendy:

https://community.amethyst.rs/t/moving-the-needle-on-user-defined-rendering-a-render-plugin-for-my-voxels/1580

**Comment by CleanCut** [comment]
@AlveLarsson I updated your original comment and started to list Rendy things that I know about.
