### ISSUE TITLE
Cursor grabbing is not yet possible on Wayland.

### ISSUE THREAD

**Issue by antonromanov1** [amethyst/amethyst#2327]
## Description

I tried to run a standard example and got an error from cargo

## Reproduction Steps

1. Run cargo run --example fly_camera --features vulkan
2. See error
[ERROR][amethyst_controls::systems] Unable to release the cursor. Error: "Cursor grabbing is not yet possible on Wayland."

## What You Expected to Happen

Watching some graphics

## Your Environment

1. GNU/Linux
2. Fedora 31
3. Version of Amethyst 0.15.1

**Comment by CastilloDel** [comment]
The same happens to me in Debian bullseye/sid. But I think the crash didn't happen because of that error but rather because of this warning:
`[WARN][rendy_wsi] Image count not supported. Supported: 4..=4294967295, requested: 3`
The panic message is:
```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorMessage { msg: "Image count not supported." }', path-to-amethyst/amethyst/amethyst_rendy/src/system.rs:115:13```

**Comment by Blisto91** [comment]
@antonromanov1 i think this issue might have been fixed in [winit 0.20](https://github.com/rust-windowing/winit/blob/master/CHANGELOG.md#0200-alpha-4-2019-10-18).
```On Wayland, add support for set_cursor_visible and set_cursor_grab.```

Unfortunately amethyst uses 0.19 and a upgrade probably have to wait until after the legion port.
Hopefully it can get some priority

**Comment by CleanCut** [comment]
@azriel91 tried to upgrade to `winit 0.22.2` and hit a blocker in https://github.com/amethyst/amethyst/issues/2285 -- it might be good if someone could take a look at picking that effort back up.
