### ISSUE TITLE
Framebuffers (and anything else based on screen resolution) must be recreated on resize.

### ISSUE THREAD

**Issue by derekdreery** [amethyst/amethyst#234]
Currently, when an amethyst window is resized, the rendering context stays the same size. This can be seen in the pong example. To fix this, all buffers dependent on screen dimensions must be recreated on a resize event.

## Extra info

The following is from the gfx_app library, a helper library for building applications with gfx that is not used in amethyst. When a resize event comes in, we need to check if the dimensions are really different, and if they are, regenerate views for our window using `gfx_window_glutin::new_views`. After the call these new views must be used as the target.

It will also be necessary to resize any other buffers if there are any (I'm a little confused by the code). Currently, the aspect ratio is not changed in response to resizes and I think it should stay the same - it is the author's job to decide on the behaviour of the MVP matrices.

```rust
loop {
        for event in window.poll_events() {
            match event {
                winit::Event::Closed => return,
                winit::Event::KeyboardInput(winit::ElementState::Pressed, _, key) if key == A::get_exit_key() => return,
                winit::Event::Resized(width, height) => if width != cur_width || height != cur_height {
                    cur_width = width;
                    cur_height = height;
                    let (new_color, new_depth) = gfx_window_glutin::new_views(&window);
                    app.on_resize(&mut factory, WindowTargets {
                        color: new_color,
                        depth: new_depth,
                        aspect_ratio: width as f32 / height as f32,
                    });
                },
                _ => app.on(event),
            }
        }
        // draw a frame
        app.render(&mut device);
        window.swap_buffers().unwrap();
        device.cleanup();
        harness.bump();
    }
```

I would write a PR but as the renderer is undergoing a rewrite I think this would lead to redundent work.

**Comment by msiglreith** [comment]
Good point!
We should only recreate the swapchain on every resize event.
Something more fancy would be to allow textures/images to have a backbuffer dependent size (1x, 2x, 0.5x dim) but I'm unsure if that's a good idea :grinning: or let the users just take care of it themself (more flexible but also error-prone).

**Comment by Xaeroxe** [comment]
It's been 4 months and there's been lots of development work so I just wanted to clarify: This is still a problem.

**Comment by derekdreery** [comment]
I'll test this.

**Comment by jojolepro** [comment]
I'll take a look too

**Comment by derekdreery** [comment]
Ok cool :)

**Comment by jojolepro** [comment]
I have got the RenderSystem to realize that the window has been resized, and it can update the size inside the Target. The problem is that I didn't realized I had to make a new builder, so figuring out how to create a new Target from within the RenderSystem (gfx_window_glutin::new_views) is the next step.

**Comment by jojolepro** [comment]
Ya sure :) Give me like 10 minutes to figure out how ^^

**Comment by jojolepro** [comment]
https://github.com/jojolepro/amethyst/commit/39e83e54ea7476d67711918374873f494acc50bc

**Comment by jojolepro** [comment]
Its still not working. It detects resizes, and updates the renderer.main_target accordingly. I now have to update the pipeline.targets somehow.

**Comment by derekdreery** [comment]
Awesome, I think it will help me to understand how to catch all the different targets. I'll message you if I have any ideas, I'll let you do the actual changes if that's ok with you? :)

**Comment by jojolepro** [comment]
Yes, just poke me on the gitter or here. (btw I have pretty much no idea of what I'm doing :D )

**Comment by derekdreery** [comment]
Same :)

**Comment by Xaeroxe** [comment]
Fixed!

**Comment by jojolepro** [comment]
:tada:
