### ISSUE TITLE
Link to website from repo

### ISSUE THREAD

**Issue by roosmaa** [amethyst/amethyst#235]
It would be awesome if the amethyst/amethyst repo had a link to https://www.amethyst.rs/

**Comment by vitvakatu** [comment]
Hello, @roosmaa. I can see about 5 links to the site in the README.md. There're not obvious, but the first one leads directly to the main page (see "This Week in Amethyst" in the beginning).
Actually, site isn't good now, we need to improve it, I'm not sure links are necessary for now.

**Comment by roosmaa** [comment]
I kind of meant this field for the Github project:

<img width="1009" alt="screenshot 2017-05-15 20 13 37" src="https://cloud.githubusercontent.com/assets/65596/26072188/ff68d2ca-39aa-11e7-8a1d-ecb1ecdde8d1.png">

Even though it might not be good, it does have the links to the book and docs. So instead of trying the different links in README.md, it's much easier just to open the project page - at least that's my opinion.

**Comment by vitvakatu** [comment]
Oh, I see. It seems reasonable. Let's wait for one of the team members :)

**Comment by Aceeri** [comment]
@ebkalderon probably has to do this, I don't think non-owners have the permissions for changing repository details?

**Comment by kvark** [comment]
@Aceeri yep, I don't see this option.

**Comment by ebkalderon** [comment]
Done! Thank you for the suggestion, @roosmaa!
