### ISSUE TITLE
[BUG] The API Docs are Broken in docs.rs

### ISSUE THREAD

**Issue by pop** [amethyst/amethyst#2363]
## Description

The docs are failing to build on `docs.rs` and seem to be stale on the Amethyst website.

## Reproduction Steps

1. Go to https://docs.rs/crate/amethyst/0.15.0
2. Click on [builds](https://docs.rs/crate/amethyst/0.15.0/builds)
3. Scroll down to [the rust nightly build](https://docs.rs/crate/amethyst/0.15.0/builds/232766)
4. See the errors for the `xcb v0.8.2` package.

## What You Expected to Happen

I expected docs.rs and the Amethyst Stable docs to be up to date.

## What Actually Happened

The API docs are ~2 versions behind stable.

## Screenshots and Logs

As was brought up in [this thread from the forum](https://community.amethyst.rs/t/how-to-ues-world-create-iter/1541) the Amethyst Stable API docs for `World::create_iter()` shouldn't be present in the latest docs because the latest stable version of Amethyst doesn't include this method.

## Your Environment

Not relevant. Infrastructure issue.

## Additional Context

The issue is with the `xcb` package. Amethyst depends on this via this lineage:

```
amethyst_ui 0.10.1
└── clipboard 0.5 (using 0.5.0, latest 0.5.0)
    └── x11-clipboard ^0.3 (using 0.3.3, latest 0.5.1)
        └── xcb ^0.8 (using 0.8.2, latest 0.9)
```

**Comment by CleanCut** [comment]
Since the discussion we had, I learned that we're publishing our official docs to https://amethyst.rs/doc -- I think we should fix the docs.rs version as well since lots of people go straight there -- so let's leave this issue open for that purpose.

**Comment by Blisto91** [comment]
I have not noticed this issue before now.

I've made a [tracking issue](https://github.com/amethyst/amethyst/issues/2438) of known things to be fixed.
Fixing the xcb dependency might have to wait until the legion changes have been merged.

**Comment by CleanCut** [comment]
👍 Closing in favor of #2438
