### ISSUE TITLE
Fix the Book

### ISSUE THREAD

**Issue by CleanCut** [amethyst/amethyst#2365]
We need to fix the book.

As a result of at least #2311 (and maybe other PRs - it is hard to tell since building the book exits at the first error), the book will not compile due to incomplete examples.  Below is a list of what needs to be fixed. @ab0v3g4me -- since you added the breaking content, would you be willing to do the remainder of the fix?  I put in 2 hours or so last night and fixed the first two, but I'd love it if you would finish it up.  (Sidenote: I accidentally pushed the fixes directly to master, so I got @fhaynes to go add a branch protection rule for `master` so that can't happen again. 😊)

- [x] `book/src/ui/introduction.md` - done in 8a5dac53f8e1ffb8bfb920cd423477f69aa8140e
- [x] `book/src/ui/simple_button.md` - done in 335b7def48ac073ea0bb0fff781935d668faa737
- [x] `book/src/ui/state_interaction.md` - https://github.com/amethyst/amethyst/pull/2368
- [x] `book/src/ui/interacting.md` - unknown -- this file is not referenced in `SUMMARY.md`, so I don't even know if it's going to attempt to build it.

As @azriel91 [pointed out](https://github.com/amethyst/amethyst/pull/2353#issuecomment-656988006) The Amethyst Book needs to compile correctly, including examples.  I'll repeat the workflow advice from that comment (I tweaked the advice slightly):

```bash
# First, clean up amethyst artifacts, and rebuild to ensure there is only one copy of the artifacts
# in the amethyst repo. (otherwise mdbook complains). You only need to do this once, unless
# you change code in the actual amethyst library.
rm -rf ./target/debug/deps/libamethyst*
cargo test --workspace --features=empty --no-run

# Then, test the book.  You can edit, run this command, and then repeat until you get everything passing.
# This is what the book tests do, so the snippets in the book must pass before you can push.
mdbook test -L ./target/debug/deps book
```

I believe the requirement for book examples to compile correctly is implicit by being in CI for Jenkins for those with write access. Let's make it explicit by documenting it.

- [x] Document requirement for documentation examples (including in the book) to compile before merging #2371 

# 🚨 Workaround

Until we've got CI fixed, we need to manually check that the book can still be compiled before merging PRs that touch it. I assembled an all-in-one command for convenient copy-and-pasting by reviewers.  /cc @AlveLarsson since you're often [helping get these PRs merged](https://github.com/amethyst/amethyst/pull/2311#event-3512058736)

```
rm -rf ./target/debug/deps/libamethyst* && cargo test --workspace --features=empty --no-run && mdbook test -L ./target/debug/deps book
```

This situation is possible since [Jenkins fails to fetch the repository for PRs originating from forks](https://github.com/amethyst/amethyst/issues/2124), which means we _have_ to ignore CI to get outside contributions merged. @fhaynes and I are trying to resolve the situation by migrating off of Jenkins.  At the moment, we are testing GitLab CI in https://github.com/amethyst/amethyst/pull/2364, but we don't yet know if that will be the final solution.

/cc @amethyst/documentation

**Comment by ab0v3g4me** [comment]
Okay, i'll fix this as soon as i can. The file `book/src/ui/interacting.md` should be referenced, but i accidentally referenced another file.

**Comment by CleanCut** [comment]
I added a checklist item to update our contributing docs to explicitly say we require examples to be able to compile.  I plan to make the update myself later today, unless someone beats me to it.

**Comment by ab0v3g4me** [comment]
#2373

**Comment by CleanCut** [comment]
@ab0v3g4me Thanks, I merged #2373.  We could use some extra hands finishing up `state_interaction.md` that is partially completed in #2368 if you're willing.

**Comment by ab0v3g4me** [comment]
I'm not sure i have the git skills for that. The only way would be to create my own PR from scratch.

**Comment by CleanCut** [comment]
@ab0v3g4me No worries, @MrTanoshii is on it.

**Comment by CleanCut** [comment]
Done!
