### ISSUE TITLE
[BUG] UI hot reload not working

### ISSUE THREAD

**Issue by PvdBerg1998** [amethyst/amethyst#2369]
## Description

The `HotReloadSystem` works for other assets, but does not reload a UI defined using `ron` files.

## Reproduction Steps

1. Add the `HotReloadBundle` and `UiBundle`
2. Load a UI using `data.world.exec(|mut creator: UiCreator<'_>| creator.create("ui/test.ron", ()))`
3. Edit the `ron` file

## What You Expected to Happen

The `UILoader` uses `PrefabLoaderSystem`, which reads the hot reload strategy and passes it to the asset manager: https://github.com/amethyst/amethyst/blob/v0.15.0/amethyst_assets/src/prefab/system.rs#L84. This should allow it to hot reload the assets.

## What Actually Happened

It's not updating.

## Your Environment

1. Windows 10
3. Amethyst 0.15

**Comment by valkum** [comment]
Discussion about this: https://discord.com/channels/425678876929163284/495950539864014877/732275664480108585
