### ISSUE TITLE
[BUG] Window gets bigger in high-dpi screens

### ISSUE THREAD

**Issue by pferreir** [amethyst/amethyst#2372]
## Description

If I run the same app on the same machine using different screens with different DPI, the UI elements show up twice as small on the high DPI screen (expected) but the window size seems to stay the same (larger in px).

## Reproduction Steps

1. Create an amethyst project which uses `UIText` and `UIImage`
2. Set a fixed resolution using `display.ron`
3. Run the project on a low DPI screen
4. Run it on a second screen with higher DPI (e.g. retina MacBook) and things will be much smaller

## What You Expected to Happen

I understand that higher DPI means things will be smaller, but I would expect that in my example the actual game window shows up proportionally smaller too.

## What Actually Happened

What happens is that Amethyst seems to create a window which is twice as big.

## Screenshots and Logs

Low DPI:
![unknown.png](https://user-images.githubusercontent.com/2699/87449473-8ced9680-c5fd-11ea-84dd-86e02882f029.png)

High DPI:
![unknown-1.png](https://user-images.githubusercontent.com/2699/87449516-9545d180-c5fd-11ea-8f09-b4d3469dc24f.png)

## Your Environment

1. MacOS Catalina
2. Amethyst 0.15.1

## Additional Context

BTW, as you can see, the imgui plugin seems to be smart enough to keep things to proportion, which seems even stranger to me.

**Comment by Blisto91** [comment]
Sorry for wait!

I don't have direct access to a high-dpi monitor, but i will try to dig into this a bit when i have time.

**Comment by pferreir** [comment]
@Blisto91 feel free to ping me if you need it to be tested!
