### ISSUE TITLE
Few questions regarding amethyst

### ISSUE THREAD

**Issue by Joe23232** [amethyst/amethyst#2374]
I have a few questions regarding the amethyst project:

* Why does amethyst decide to use `legion` over `shipyard` when `shipyard` has the potential for higher performance?
* Am I able to code my game using Rust using this game engine?
* Is there an alpha/beta version of the GUI game editor available?

**Comment by CleanCut** [comment]
> * Why does amethyst decide to use `legion` over `shipyard` when `shipyard` has the potential for higher performance?

The reason for using legion is here: https://github.com/amethyst/rfcs/issues/22

> * Am I able to code my game using Rust using this game engine?

Yes! You will be using Rust for all of your game engine code with Amethyst.  Documentation is here: https://amethyst.rs/doc

> * Is there an alpha/beta version of the GUI game editor available?

I would call it pre-alpha.  The editor is being worked on here: https://github.com/amethyst/editor

**Comment by Joe23232** [comment]
> The reason for using legion is here: amethyst/rfcs#22

In the link that you have provided, it doesn't mention about `shipyard` though. It talks about `specs` instead. I just wanted to know why pick `legion` over `shipyard`?

> Yes! You will be using Rust for all of your game engine code with Amethyst. Documentation is here: https://amethyst.rs/doc

Thanks.

> I would call it pre-alpha. The editor is being worked on here: https://github.com/amethyst/editor

The link that you have provided is dead. Has it been moved somewhere or something?

**Comment by CleanCut** [comment]
> > * Why does amethyst decide to use `legion` over `shipyard` when `shipyard` has the potential for higher performance?

> In the link that you have provided, it doesn't mention about `shipyard` though. It talks about `specs` instead. I just wanted to know why pick `legion` over `shipyard`?

I would guess that shipyard wasn't considered because it wasn't very usable at the time. I am intrigued that you assert "`shipyard` has the potential for higher performance."  I've never heard anyone claim that before. Can you provide any evidence to back that up?  If there has been some research done, I'd like to read up on it.  The [specs and legion](https://csherratt.github.io/blog/posts/specs-and-legion/) research was fascinating.

> The link that you have provided is dead. Has it been moved somewhere or something?

Ah, my apologies.  It is not yet public. I know that we've done a bit of experimenting with different ideas, and I speculate that we haven't yet committed to the path we want to take.  Currently there is no publicly-available editor that I am aware of. /cc @AlveLarsson in case you have more information you would like to share.

**Comment by Joe23232** [comment]
> I would guess that shipyard wasn't considered because it wasn't very usable at the time. I am intrigued that you assert "shipyard has the potential for higher performance." I've never heard anyone claim that before. Can you provide any evidence to back that up? If there has been some research done, I'd like to read up on it. The specs and legion research was fascinating.

I had a developer who told me the criticisims of Amyethist, as to why he didn't want to work on it and he wanted to make something else. One of them being that he claims that `shipyard` is more lower level and gives more control over `legion`, though it is a bit harder to use.

> Ah, my apologies. It is not yet public. I know that we've done a bit of experimenting with different ideas, and I speculate that we haven't yet committed to the path we want to take. Currently there is no publicly-available editor that I am aware of. /cc @AlveLarsson in case you have more information you would like to share.

All good mate, thanks for letting me know :)

**Comment by AlveLarsson** [comment]
I think you asked the very same question on discord about shipyard, if not there is some ppl who did ask, use the discord search function and see all the hits on shipyard maybe that can help

**Comment by Joe23232** [comment]
It didn't quite appear that people were so sure so I wanted a different opinion.

**Comment by AlveLarsson** [comment]
Ah maybe @jojolepro can respond?

**Comment by jojolepro** [comment]
its all tradeoffs and opinions. personally I prefer specs because of the simplicity, which I value more than performance. others prefer legion because of performance and ffi compatibility. and that's all valid opinions, at this point its just about who takes the decisions and what they like most.

**Comment by chemicstry** [comment]
There were many, many discussions about archetypal vs sparse set ECS architectures and there is no clear winner. It is all tradeoffs between usability, speed and specific use cases as @jojolepro mentioned.

If you want a lengthy read: https://community.amethyst.rs/t/archetypal-vs-grouped-ecs-architectures-my-take/1344

**Comment by khionu** [comment]
Another thing to note is that all of the cases I've been aware of where Legion has lacked in performance? They're easy to mitigate. Ie component insertion, if you're going to be doing it with any regularity, you can just use an Option.
