### ISSUE TITLE
[BUG] Pong Example Sprite Assets Fail to Load on Ubuntu 20.04

### ISSUE THREAD

**Issue by 0ur0bor0s** [amethyst/amethyst#2386]
## Description

Running pong code on new amethyst project causes sprites to fail to render followed by error messages.  pong_tutorial_02 in amethyst example directory builds correctly.

## Reproduction Steps

1. Install Amethyst tools with `cargo install amethyst_tools`
2. Create new project with `amethyst new pong`
3. To save time, copy source, asset, and config files from pong_tutorial_02 in amethyst example folder
4. `cargo run`

## What You Expected to Happen

Pong assets are rendered on screen.

## What Actually Happened

Assets are not loaded, followed by error messages

## Screenshots and Logs

Console Output:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/pong`
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.15.0
[INFO][amethyst::app] Platform: x86_64-unknown-linux-gnu
[INFO][amethyst::app] Amethyst git commit: UNKNOWN
[INFO][amethyst::app] Rustc version: 1.45.0 Stable
[INFO][amethyst::app] Rustc git commit: 5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2
[INFO][winit::platform::platform::x11::window] Guessed window DPI factor: 1
[WARN][rendy_factory::factory] Slow safety checks are enabled! Disable them in production by enabling the 'no-slow-safety-checks' feature!
[INFO][rendy_util::wrap] Slow safety checks are enabled! You can disable them in production by enabling the 'no-slow-safety-checks' feature!
[ERROR][amethyst_assets::storage] "renderer::SpriteSheet": Asset "texture/pong_spritesheet.ron" (handle id: Handle { id: 0 }) could not be loaded: Failed to load asset with name "texture/pong_spritesheet.ron"
[ERROR][amethyst_assets::progress] Error loading handle 0, renderer::SpriteSheet, with name texture/pong_spritesheet.ron: Failed to load asset with name "texture/pong_spritesheet.ron"
caused by: Failed to load asset with name "texture/pong_spritesheet.ron"
Error { inner: Inner { source: Some(Error { inner: Inner { source: Some(Error { inner: Inner { source: None, backtrace: None, error: LoadSpritesheetError(Parser(ExpectedIdentifier, Position { col: 1, line: 1 })) } }), backtrace: None, error: Format("SPRITE_SHEET") } }), backtrace: None, error: Asset("texture/pong_spritesheet.ron") } }
caused by: Format "SPRITE_SHEET" could not load asset
Error { inner: Inner { source: Some(Error { inner: Inner { source: None, backtrace: None, error: LoadSpritesheetError(Parser(ExpectedIdentifier, Position { col: 1, line: 1 })) } }), backtrace: None, error: Format("SPRITE_SHEET") } }
caused by: Failed to parse SpriteSheet
Error { inner: Inner { source: None, backtrace: None, error: LoadSpritesheetError(Parser(ExpectedIdentifier, Position { col: 1, line: 1 })) } }
[ERROR][amethyst_assets::progress] Note: to handle the error, use a `Progress` other than `()`
[WARN][amethyst_assets::storage] Loading unnecessary asset. Handle 6 is unique 
[ERROR][amethyst_assets::progress] Error loading handle 6, Mesh, with name texture/pong_spritesheet.png: Asset was loaded but no handle to it was saved.
caused by: Asset was loaded but no handle to it was saved.
Error { inner: Inner { source: None, backtrace: None, error: UnusedHandle } }
[ERROR][amethyst_assets::progress] Note: to handle the error, use a `Progress` other than `()`
```

## Your Environment

1. Operating System: Ubuntu
2. Operating System Version: 20.04 LTS
3. Version of Amethyst: 0.15.0
4. Version of Amethyst CLI: 0.10.0

## Additional Content

Attempted to follow these related issues to no avail:
https://github.com/amethyst/amethyst/issues/2034
https://community.amethyst.rs/t/sprite-doesnt-render-in-pong-tutorial/1217

**Comment by CastilloDel** [comment]
After following your reproduction steps and changing the paths in main.rs to be the correct ones I had no problems. I'm in Debian Bullseye/sid and also using the 0.15.0 version of amethyst.

**Comment by 0ur0bor0s** [comment]
Sorry forgot to include changing the path in the reproduction steps.  Hmmm very weird.  Perhaps it is only a bug in ubuntu 20.04.

**Comment by CleanCut** [comment]
Is there anyone else who has Ubuntu 20.04 that can verify this?  @0ur0bor0s, if we can't find anyone to independently verify this, maybe it would be worthwhile for you to run through the steps again yourself with the current master branch and see if you still hit the problem?

**Comment by Blisto91** [comment]
I will try to see if i can reproduce this within a couple of days.

**Comment by Blisto91** [comment]
@0ur0bor0s Okay i'm back!
Can you type ```file [filename]``` with the path to your ```pong_spritesheet.ron``` and post the output here.

**Comment by 0ur0bor0s** [comment]
Hey guys! Sorry got busy with work and school! @Blisto91 tonight I can retry and post my output if it still doesn't work!

**Comment by Blisto91** [comment]
School and work have priority ofc! 
But then again i have been staying up way too late lately investigating issues here. Also checking in at work :grin:

**Comment by 0ur0bor0s** [comment]
Ooh you rebel @Blisto91 :wink: Okay just made sure dependencies were updated and seem to be receiving the same asset loading error :(. Here is my file command output as requested:
```
$ file assets/texture/pong_spritesheet.ron
assets/texture/pong_spritesheet.ron: ASCII text
```
Just to confirm I wasn't doing anything incorrectly, I ran the same project on my Manjaro Linux environment and it ran with no errors.

**Comment by Blisto91** [comment]
Strange.
Do you think you can tar up the file in question on your Ubuntu and share it here?

Can you also type ``locale`` in a prompt and share the output?

**Comment by Blisto91** [comment]
@0ur0bor0s  Can you try pointing to [this branch](https://github.com/amethyst/amethyst/tree/allow-encoding-variants) and see if it fixes it?

**Comment by Crash0** [comment]
Hi, I also had problem with this, w10, amethyst 0.15.2.
It did not work when i typed the file myself, or copied the text from browser.
What did fix it, was downloading the raw file. So maybe a line ending issue?

EDIT: A quick diff tells me that the file i created (that did not work) had encoding UTF-8 BOM CRLF, and the file that worked had UTF-8 LF, the text content was unchanged.
