### ISSUE TITLE
Auto-generated example fails to build

### ISSUE THREAD

**Issue by aschuhardt** [amethyst/amethyst#239]
Below is the output I'm receiving when trying to generate and build the default example application.  I am on Windows 10 64-bit, running `nightly-x86_64-pc-windows-msvc` and `rustc 1.19.0-nightly (d47cf08d5 2017-05-28)`

`PS C:\Users\aschuhardt\Desktop> amethyst new hello_world
PS C:\Users\aschuhardt\Desktop> cd .\hello_world\
PS C:\Users\aschuhardt\Desktop\hello_world> amethyst build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling threadpool v1.3.2
   Compiling bitflags v0.7.0
   Compiling wavefront_obj v5.0.0
   Compiling atom v0.3.4
   Compiling xml-rs v0.3.6
   Compiling gdi32-sys v0.1.1
   Compiling khronos_api v1.0.1
   Compiling num-traits v0.1.37
   Compiling mopa v0.2.2
   Compiling yaml-rust v0.3.5
   Compiling gcc v0.3.49
   Compiling winapi-build v0.1.1
   Compiling d3dcompiler-sys v0.2.0
   Compiling dwmapi-sys v0.1.0
   Compiling rustc-serialize v0.3.24
   Compiling log v0.3.8
   Compiling gl_generator v0.5.3
   Compiling amethyst_config v0.2.2
   Compiling kernel32-sys v0.2.2
   Compiling shell32-sys v0.1.1
   Compiling fnv v1.0.5
   Compiling d3d11-sys v0.2.0
   Compiling tuple_utils v0.2.0
   Compiling gfx_gl v0.3.1
   Compiling bitflags v0.6.0
   Compiling draw_state v0.6.0
   Compiling dds-rs v0.4.0
   Compiling glutin v0.7.4
   Compiling winapi v0.2.8
   Compiling gfx_core v0.6.1
   Compiling user32-sys v0.1.2
   Compiling libc v0.2.23
   Compiling rand v0.3.15
   Compiling num_cpus v1.5.0
   Compiling approx v0.1.1
   Compiling cgmath v0.14.1
   Compiling cgmath v0.12.0
   Compiling genmesh v0.4.3
   Compiling miniz-sys v0.1.9
   Compiling flate2 v0.2.19
   Compiling imagefmt v4.0.0
   Compiling gfx_core v0.5.1
   Compiling lazy_static v0.2.8
   Compiling shared_library v0.1.5
   Compiling gfx_device_gl v0.13.1
   Compiling gfx v0.14.1
   Compiling dxguid-sys v0.2.0
   Compiling time v0.1.37
   Compiling winit v0.5.11
   Compiling pulse v0.5.3
   Compiling specs v0.7.1
   Compiling gfx_window_glutin v0.14.0
   Compiling amethyst_renderer v0.4.2
   Compiling gfx_device_dx11 v0.4.0
   Compiling gfx_window_dxgi v0.5.0
   Compiling amethyst v0.4.2
   Compiling hello_world v0.1.0 (file:///C:/Users/aschuhardt/Desktop/hello_world)
error[E0432]: unresolved import `amethyst::engine::Application`
 --> src\main.rs:3:24
  |
3 | use amethyst::engine::{Application, Duration, State, Trans};
  |                        ^^^^^^^^^^^ no `Application` in `engine`

error[E0432]: unresolved import `amethyst::engine::Duration`
 --> src\main.rs:3:37
  |
3 | use amethyst::engine::{Application, Duration, State, Trans};
  |                                     ^^^^^^^^ no `Duration` in `engine`

error[E0432]: unresolved import `amethyst::engine::State`
 --> src\main.rs:3:47
  |
3 | use amethyst::engine::{Application, Duration, State, Trans};
  |                                               ^^^^^ no `State` in `engine`. Did you mean to use `state`?

error[E0432]: unresolved import `amethyst::engine::Trans`
 --> src\main.rs:3:54
  |
3 | use amethyst::engine::{Application, Duration, State, Trans};
  |                                                      ^^^^^ no `Trans` in `engine`

error: module `engine` is private
 --> src\main.rs:3:24
  |
3 | use amethyst::engine::{Application, Duration, State, Trans};
  |                        ^^^^^^^^^^^

error: module `engine` is private
 --> src\main.rs:3:37
  |
3 | use amethyst::engine::{Application, Duration, State, Trans};
  |                                     ^^^^^^^^

error: module `engine` is private
 --> src\main.rs:3:47
  |
3 | use amethyst::engine::{Application, Duration, State, Trans};
  |                                               ^^^^^

error: module `engine` is private
 --> src\main.rs:3:54
  |
3 | use amethyst::engine::{Application, Duration, State, Trans};
  |                                                      ^^^^^

error: cannot continue compilation due to previous error

error: Could not compile `hello_world`.

To learn more, run the command again with --verbose.
Error: Cargo task failed!`

**Comment by aschuhardt** [comment]
After submitting this I did some more searching and learned that this issue is a duplicate of the one outlined [here](https://github.com/amethyst/tools/issues/37).  It appears the solution is to _not_ use Amethyst Tools.

**Comment by aschuhardt** [comment]
Can we please make this more apparent on the front page for this repo?

**Comment by minecrawler** [comment]
The problem is, that not only the tools, but also the book and docs and examples are all lacking and outdated. I think, that should be a topic for the v1.0 release. You can use the tools to create a project, but you will have to [pull the latest template from git](https://github.com/amethyst/project_template) yourself. For now, I think that basic features and API consolidation should be the priority. What good does it do, if the devs always have to change many places for every small change, which happens during pre-release development?

**Comment by Aceeri** [comment]
I'll just add a bolded message to the top of the amethyst README for now. Since we have been getting a lot of these kinds of issues.

**Comment by aschuhardt** [comment]
Thanks!
