### ISSUE TITLE
[BUG] Font download link in Pong tutorial is broken

### ISSUE THREAD

**Issue by brundonsmith** [amethyst/amethyst#2392]
In this page: https://book.amethyst.rs/stable/pong-tutorial/pong-tutorial-05.html

Ctrl+F for "we're first going to load up a font" and you'll see a "download" link, which is broken:
https://github.com/amethyst/amethyst/raw/master/examples/assets/font/square.ttf

I believe it should be:
https://github.com/amethyst/amethyst/raw/master/examples/pong_tutorial_05/assets/font/square.ttf

**Comment by CleanCut** [comment]
This was fixed in https://github.com/amethyst/amethyst/pull/2313 -- the change will be reflected on the website when we update the books during the 0.15.1 release.
