### ISSUE TITLE
Scripting Language

### ISSUE THREAD

**Issue by Hamed2012-dr** [amethyst/amethyst#2394]
Hi developers. Im a JavaScript developer about 2 years experience and i was looking for a game engine that have JavaScript scripting language. I found **Amethyst** and start coding in it about 2 weeks. It's **SUPER AMAZING**. Most JavaScript developers interested in **Rust** programming language, because of evolution of **Deno**. So i think the **JavaScript**-like scripting language would be a very amazing thing for **Amethyst**. Anyway thanks for making this **SUPER AMAZING** game engine and im sure about **Amethyst** future, that is very bright.

**Comment by khionu** [comment]
We have futures plans to support an extensible scripting API with support for plugging in various languages/runtimes. See our RFC: https://github.com/amethyst/rfcs/blob/master/0001-scripting.md

**Comment by Hamed2012-dr** [comment]
> We have futures plans to support an extensible scripting API with support for plugging in various languages/runtimes. See our RFC: https://github.com/amethyst/rfcs/blob/master/0001-scripting.md

Cool. Thanks
