### ISSUE TITLE
Release 0.4.3

### ISSUE THREAD

**Issue by nchashch** [amethyst/amethyst#240]
Some valuable non-breaking changes have accumulated on `develop`, so it's time for another PATCH version bump. I think this should be done before merging any of the major breaking changes.

I have merged or closed all PRs, except for major breaking ones. So I think we can release current develop branch as 0.4.3 (AFAIK only CHANGELOG.md would have to be updated).

**Comment by ebkalderon** [comment]
Sounds good to me. I'm on it! :+1:

**Comment by ebkalderon** [comment]
Done!
