### ISSUE TITLE
[BUG] FlyControlBundles not working as expected when loaded inside State::on_start

### ISSUE THREAD

**Issue by jruiss** [amethyst/amethyst#2402]
## Description

FreeRotationSystem requires CursorHideSystem.hide = true to work, which it becomes when MouseFocusUpdateSystem sets is_focused = true. This requires a WindowEvent which doesn't happen when the state is loaded after the initial window creation.

## Reproduction Steps

1. Initiate FlyControlBundle in State::on_start
2. Nothing happens
3. Move focus from window and return
4. HideCursorSystem and FreeRotationSystem activates

## What You Expected to Happen

FlyControlBundles FreeRotationSystem and HideCursorSystem to activate on State::on_start

## What Actually Happened

Cursor don't hide and no rotation on mouse movement

## Additional Context

See https://github.com/amethyst/amethyst/blob/10517e0b5c26e80c5e594785a520132726bd5e7c/amethyst_controls/src/systems.rs#L171

**Temporary solution**

Set window focus in State::on_start
```rust
let mut window_focus: Write<WindowFocus> = data.world.system_data();
window_focus.is_focused = true;
```

**Comment by Blisto91** [comment]
Sorry for the wait!

When I have the time next I'll try to look into this a bit.
