### ISSUE TITLE
Prefab system in legion

### ISSUE THREAD

**Issue by chemicstry** [amethyst/amethyst#2404]
We have successfully ported `amethyst_assets` to legion except for the prefabs. Porting prefabs is a difficult task because they are based on specs `SystemData` tuples to access component storages. This would require a complete rewrite for legion.

Instead of wasting resources rewriting old systems, there is an option to switch to https://github.com/amethyst/atelier-assets, the long awaited asset system.

**Comment by kabergstrom** [comment]
To elaborate a bit on the atelier-assets part: atelier-assets does not contain a prefab system. The prefab system Acylsma and I designed and implemented to demonstrate the concepts lives here: https://github.com/kabergstrom/prefab/
and you probably want to read the relevant forum thread: https://community.amethyst.rs/t/atelier-legion-integration-demo/1352?u=kabergstrom

**Comment by chemicstry** [comment]
Cross linking: https://community.amethyst.rs/t/adopting-atelier-as-the-new-asset-crate-for-legion-port/1621

**Comment by jlowry** [comment]
I'll update a previous integration of atelier-assets by @kabergstrom and add the prefab system designed by @kabergstrom and @aclysma. If you are okay with that you can assign this to me.

**Comment by jlowry** [comment]
The commit history of wip branch is divergent resulting in a massive amount of old commits (the commits I branched off came out differently in the true legion_v2 branch), so I'm going to tidy that up and then link a draft pull request against this issue.

**Comment by jlowry** [comment]
My draft pull request is #2520 but I do not have permission to link it against this issue.

**Comment by jlowry** [comment]
At the moment to see it running do:
```
cd examples/asset_loading
cargo run --features "metal" --example asset_loading
```
Then change some values in `assets/mesh/cuboid.custom`

**Comment by jlowry** [comment]
I'm working on fixing an example that uses complex prefabs so I have a harness I can try things against. I expect to have a complex prefab working by the end of the week.
