### ISSUE TITLE
[MAINTENANCE] Possible readme error?

### ISSUE THREAD

**Issue by anchpop** [amethyst/amethyst#2409]
## Description

The readme contains this line:

> Amethyst is based over a very powerful parallel ECS called Specs. This allows games built with Amethyst to maximize the available processing power to run as smoothly and as quickly as possible, without the headaches of multi-threaded programming.

## Reason

I believe Amethyst uses Legion now, not specs. If that is not the case, ignore this issue!

## Impact

Basically none

**Comment by CleanCut** [comment]
@anchpop The legion integration is still being actively worked on in the [legion_v2](https://github.com/amethyst/amethyst/tree/legion_v2) branch. Hopefully that will land Soon™ 😉

**Comment by CleanCut** [comment]
Also, if you'd like to help out, we're tracking the project on [this board](https://github.com/amethyst/amethyst/projects/21)
