### ISSUE TITLE
[MAINTENANCE] [DOC] Book `System` example has an extra `mut`

### ISSUE THREAD

**Issue by luckystreak63** [amethyst/amethyst#2416]
## Description

An extra `mut` snuck its way into the docs at the following section: https://book.amethyst.rs/stable/concepts/system.html#getting-all-entities-with-specific-components

```
for (mut transform, _) in (&mut transforms, &falling).join() {...}
      ^----- variable does not need to be mutable
```

## Reason

When trying to compile code with the extra `mut`, the compiler complains that it's not necessary, which can be confusing for people new to Amethyst.

**Comment by Jaden-Giordano** [comment]
@AlveLarsson @CleanCut @khionu  This can be closed as it was resolved in #2430
