### ISSUE TITLE
[MAINTENANCE] Amethyst banner in Book covers search interface

### ISSUE THREAD

**Issue by fosskers** [amethyst/amethyst#2418]
## Description

The published `stable` version of the book is fine, but the one on `master` has a very nice banner that unfortunately covers the entire search UI:

![2020-08-11-160501_1916x1041_scrot](https://user-images.githubusercontent.com/229679/89957523-7c284480-dbec-11ea-9d33-85ceb54f3bf8.png)

You can still press `s` and do a search as with all `mdbook`s, but the banner covers the results too.

**Comment by AlveLarsson** [comment]
Oh wops, my fault I forgot about the search page, will get that fixed in an hour or 2

**Comment by fosskers** [comment]
Confirmed, works like a charm!
