### ISSUE TITLE
Integration in QtVulkanWindow

### ISSUE THREAD

**Issue by lehmanju** [amethyst/amethyst#2425]
Hey, I was wondering whether it is possible to not use SDL and Winit but instead integrate a game in an external framework. I would like to have some normal Qt widgets and a vulkan widget that displays my Amethyst game. Consequently, input events would be coming from Qt as well as some other custom events.

**Comment by khionu** [comment]
The complexity of having an Amethyst Game be rendered in a window spawned outside of Winit is large. It would require patches to multiple crates before Amethyst could even consider supporting it. I would look into whether you can get Qt to run WASM through their browser widget, that would be your best bet.

**Comment by lehmanju** [comment]
Hmm, it doesn't look like that is supported or considered stable at the moment. However, there may be some other solution. Actually, I need a way to get digital pen input and some buttons to change settings. If that is possible in Amethyst without Qt and preferably by reusing existing widgets, that would also work.

**Comment by lehmanju** [comment]
Is using druid or iced an option here? They also use winit and wgpu from what I understand.

**Comment by Blisto91** [comment]
druid is using their own windowing code currently.
I think winit doesn't support all the things they wanted, like smooth resize.

**Comment by khionu** [comment]
Supporting other input devices would be a different issue, but something we can do with our own usage of Winit.

**Comment by lehmanju** [comment]
I am already implementing wayland tablet api in smithay/winit, so that should be available soon.

**Comment by lehmanju** [comment]
Closing this as I am taking a different approach now.
