### ISSUE TITLE
[BUG] Stable Book Page: tiles/create_a_tile_map is empty

### ISSUE THREAD

**Issue by dekuraan** [amethyst/amethyst#2441]
## Description
The page tiles/create_a_tile_map is has an empty body on the book for the stable branch, however it is fine on the book for master.

## Reproduction Steps

1. Go to https://book.amethyst.rs/stable/.tiles/create_a_tile_map.html
2. Go to https://book.amethyst.rs/master/tiles/create_a_tile_map.html (Url for master is different for some reason)

## What You Expected to Happen

Full

## What Actually Happened

Empty

## Your Environment

Firefox & Chrome tested

**Comment by CleanCut** [comment]
Fixed in #2445 

Stable now correctly links to https://book.amethyst.rs/stable/tiles/create_a_tile_map.html in the navigation links.
