### ISSUE TITLE
[BUG] amethyst_rendy bundle test doesn't compile

### ISSUE THREAD

**Issue by bonsairobo** [amethyst/amethyst#2446]
## Description

The test amethyst_rendy test `main_pass_surface_plan` doesn't compile. I think because it has the `#[ignore]` attribute, it doesn't run in CI, and it's been broken for a while.

## Reproduction Steps

```
cd amethyst_rendy
cargo test --features="vulkan"
```

## What You Expected to Happen

Tests build and pass.

## What Actually Happened

Compile error:

```
error[E0599]: no method named `create_surface` found for struct `rendy_factory::factory::Factory<gfx_backend_vulkan::Backend>` in the current scope
   --> amethyst_rendy\src\bundle.rs:912:32
    |
912 |         let surface1 = factory.create_surface(&window);
    |                                ^^^^^^^^^^^^^^ method not found in `rendy_factory::factory::Factory<gfx_backend_vulkan::Backend>`
```

## Your Environment

Amethyst version 0.15.1

**Comment by Blisto91** [comment]
Sadness.

Will try to look into it later today if no one else does it.
