### ISSUE TITLE
Nitro vs Amethyst comparison

### ISSUE THREAD

**Issue by Xaeroxe** [amethyst/amethyst#245]
Intro: I was previously the main developer for the Nitro game engine project, I've decided to work on Amethyst instead though.  My first goal is to get Amethyst up to speed with features I had in Nitro that aren't in Amethyst currently.  I created a comparison between the two engines which I'm recording here so I can refer back to it.

Features only Nitro has:
- 2D sprite rendering in an orthographic camera
- ~~SFX/Music playback with music playlists that can shuffle and loop~~ Done!
- nphysics powered physics simulation
- ~~Input axes, rebinding inputs, and saving and loading bindings from files~~ Done!

Features only Amethyst has:
- 3D rendering and a 3D world.
- Vastly improved concurrency support. Nitro is single threaded only.
- Much more efficient component and entity storage. (Nitro made liberal usage of Box and HashMap, this and a lack of concurrency support made the engine drop to about 12FPS when I added 10,000 GameObjects for stress testing)
- Display configuration files. Nitro had very limited display configuration, even from a programmatic standpoint.
- Push down automaton structures
- An AssetManager. Nitro's asset management was scattered throughout the source.

The biggest way in which Nitro and Amethyst differed in my opinion was the API usage. I went into Nitro trying to mimic what I liked in Unity3D, so I made components programmable as opposed to adding Systems. This had a few major problems:
- Concurrency was nearly impossible with this API scheme, any attempts to change that made for very unpredictable and complicated code.
- Requiring a vtable lookup for every component, every frame, on every GameObject was murderous to performance.
- Execution ordering of components and making sure that it was easy to define the execution ordering, but not cumbersome, turned out to be a bit complicated and very expensive for the hardware.

So going forward the first areas I personally want to tackle for Amethyst are filling in the gaps, adding audio, adding key rebinding, 2D sprite rendering, and some day getting a nice physics engine in. Then I'd like to start working on some of the goals I had for Nitro that I didn't get to, things like layer masking support, easier UI design, and enhancements to make setting up multiplayer easier.

**Comment by Xaeroxe** [comment]
[Input rebinding PR](https://github.com/amethyst/amethyst/pull/247) (WIP as of 2017-06-17)

**Comment by Xaeroxe** [comment]
Phase 1 of input rebinding is complete.  At some point I'm going to do a phase 2, here's my current wishlist for that phase

- Introduce default binding config files as an asset and allow the InputHandler to load and save these.  If the binding config file is an asset it should be treated as read-only, if it was loaded from somewhere else in the filesystem then it can be written to.
- return impl Iterator instead of our own Iterator structures (This language feature isn't stable yet, I'm hoping it will be by the time I start this.)
- Add functions such as `released_keys` and `down_keys` and analogues for mouse buttons and generic buttons.  This lets the user generically query for any input in those states, whereas currently they can only generically query for inputs in the pressed state.

**Comment by Xaeroxe** [comment]
Rodio PR: https://github.com/tomaka/rodio/pull/125 this should help with getting sound working in Amethyst.

**Comment by Xaeroxe** [comment]
Input rebinding phase 2: https://github.com/amethyst/amethyst/pull/261
Phase 3 will integrate this with the asset system once [Ron](https://github.com/kvark/ron) is ready.

**Comment by Xaeroxe** [comment]
https://github.com/amethyst/amethyst/pull/265 Audio PR

**Comment by Xaeroxe** [comment]
Input rebinding phase 3: https://github.com/amethyst/amethyst/pull/274

Once this is merged amethyst will have complete coverage of nitro's old input system capabilities.

**Comment by erlend-sh** [comment]
> Features only Nitro has:
> (...)
>  - nphysics powered physics simulation

Will this have any effect on RFC #205?

Also, @mechaxl already had a go at nphysics integration in #144 but ultimately opted to drop it.

**Comment by Xaeroxe** [comment]
@erlend-sh I'm not particularly insistent that we use nphysics specifically for this, as I'm realizing in its current state it may not be the best choice for a physics processor.  However I would like to direct your attention to this issue: https://github.com/sebcrozet/nphysics/issues/71 which indicates the author of nphysics is at least considering making the library more ECS friendly.  In the event that this doesn't get moving fast enough I'll probably end up making my own ECS friendly physics engine.  That bullet point is more intended specifically for "get any kind of physics working in Amethyst at all."

**Comment by sebcrozet** [comment]
> [...] the author of nphysics is at least considering making the library more ECS friendly.

Right now I am working on a prototype using `specs`. Basically I want to have one component for rigid bodies and one system for the physics engine itself. So far I've rewritten a couple of things on `ncollide` that relied on `Rc<RefCell>`, and am in the process of modifying the solver of nphysics so that it works with indices instead of pointers to rigid body.

> In the event that this doesn't get moving fast enough I'll probably end up making my own ECS friendly physics engine.

I think I'll have a working prototype with demos in one or two months. It it ends up working well (and without drop of performances), I'll concider re-adding the other features that already exist on the current implementation (sensors and joints). Hopefully most of it will be done and documented for the end of this year.

**Comment by Xaeroxe** [comment]
@sebcrozet Feel free to poke us if you come up with anything we can do to help!

**Comment by Xaeroxe** [comment]
It's not really necessary for this to be left open anymore as these two remaining tasks are pretty well mutually understood by all involved on the project.  So I'm going to close this.
