### ISSUE TITLE
[BUG] Issue with the tutorial Pong code just giving me an error

### ISSUE THREAD

**Issue by 13ros27** [amethyst/amethyst#2457]
## Description

If I do `cargo run`on the code from [Pong Tutorial 01](https://book.amethyst.rs/stable/pong-tutorial/pong-tutorial-01.html) I get this error: `Error: Error { inner: Inner { source: None, backtrace: None, error: Parser(Parser(ExpectedStruct, Position { col: 1, line: 1 })) } }` and if I do `cargo build` and then run `target\debug\amethyst-test` I get this error: `Error: Error { inner: Inner { source: None, backtrace: None, error: File(Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }) } }`

## Your Environment

My operating system is Windows 10 and I am using the latest crates.io version of amethyst (0.15.*) with vulkan

## Code

The exact code that I am using is:
```
use amethyst::{
    prelude::*,
    renderer::{
        plugins::{RenderFlat2D, RenderToWindow},
        types::DefaultBackend,
        RenderingBundle,
    },
    utils::application_root_dir,
};

pub struct Pong;

impl SimpleState for Pong {}

fn main() -> amethyst::Result<()> {
    amethyst::start_logger(Default::default());
    let app_root = application_root_dir()?;
    let display_config_path = app_root.join("config").join("display.ron");
    let game_data = GameDataBuilder::default().with_bundle(
        RenderingBundle::<DefaultBackend>::new()
            .with_plugin(
                RenderToWindow::from_config_path(display_config_path)?
                    .with_clear([0.0, 0.0, 0.0, 1.0]),
            )
            .with_plugin(RenderFlat2D::default()),
    )?;
    let assets_dir = app_root.join("assets");
    let mut game = Application::new(assets_dir, Pong, game_data)?;
    game.run();
    Ok(())
}
```

**Comment by Blisto91** [comment]
Hi there!

The second error is because it can't find the config/display.ron in target/debug/
If you copy this folder into there then it should show the first error again.

Can you show the content of your display.ron?

**Comment by 13ros27** [comment]
@Blisto91 Thanks for explaining the second one, my config/display.ron file is:
```
{
	title: "Pong!",
	dimensions: Some((500, 500)),
}
```

**Comment by Blisto91** [comment]
Try changing the beginning and end braces to parentheses.
```
(
	title: "Pong!",
	dimensions: Some((500, 500)),
) 
```

In the ron format parentheses are used for [structs among other Thing's](https://github.com/ron-rs/ron#same-example-in-ron).

The error message could probably be more clear since it doesn't mention which file is the problem.

**Comment by 13ros27** [comment]
Thanks that works now, I misread as I was going through the tutorial because I was thinking it was more similar to json so just assumed they were curly
