### ISSUE TITLE
[BUG] Tint component, Transparent component and Premultiplied Alpha

### ISSUE THREAD

**Issue by dejaime** [amethyst/amethyst#2458]
This is my first issue, so please let me know if I missed something or if anything needs to be changed

## Description

Tint component, Transparent component and Premultiplied Alpha in Amethyst are confusing.
I am not sure if this is a necessarily a bug in rendering transparency or maybe I didn't correctly understand the documentation on how to use Palettes, Alpha wrappers, Srgba, Tint and Transparent.

To the point, changing the alpha value of the Tint component (on an entity that also has a Transparent component) changes their transparency just slightly until very close to alpha = 0.0, when it instantly jumps from almost opaque to invisible.

## Reproduction Steps
See example at https://github.com/dejaime/amethyst-alpha-test (hard fork of amethyst 2d template)
Video of project running: https://streamable.com/2wr6ua
Relevant code is at
- `state.rs`, `init_sprites` function at line 138, especially the line that creates the Tint components and the alpha value passed: `Tint(Srgba::new(1.0, 1.0, 1.0, 0.001)` 

- `transparency_system.rs`

1. Add `Transparent` component and `Tint` component to an entity with a Sprite
2. See it is fully opaque and visible
3. Change the Tint's alpha overtime (between 0.0 and 1.0), see just a very small change in transparency, almost fully opaque still

Note: if you change alpha to `0` from a small value (e.g. `0.0001`) it jumps from slightly transparent to completely invisible

4. Add another entity, now with `Transparent` component and `Tint` and set Tint's alpha to something close to zero (e.g. 0.01)
5. See it is fully opaque and visible
6. Leave Tint's alpha with the low value, but change RGB overtime (between 0.0 and 1.0 ["premultiply"]), and see it going from opaque to transparent as expected

## What You Expected to Happen

I expected the transparency to scale linearly with the Alpha value of the tint component, for whatever RGB values on the Tint component.
Did not expect sprite to jump from almost opaque to invisible when reaching zero alpha.
I expected the middle case (alpha and RGB with values in sync) to gradually fade in alpha as well as in color, instead of fading to black and then blinking.

## What Actually Happened
Alpha has little to no effect if we don't premultiply the alpha in the colors. Still, assigning 0.0 alpha to the Tint makes sprites jump to invisible despite RGB being all 1.0, what I believe is inconsistent with premultiplied alpha.

## Screenshots and Logs
https://streamable.com/2wr6ua

## Your Environment
I tested this in Arch Linux ([this one](https://haste.rys.pw/yekiduniyi.coffeescript)) and on Windows 10.
Tested Amethyst versions 15.0, 15.1 and 15.3

## Additional Context
Very helpful discussion on Discord
https://discord.com/channels/425678876929163284/476032191567233025/747331673364103168
Big thank you to everybody who helped me over at reddit and discord!

**Comment by Blisto91** [comment]
I never got to run your code, but I'll toy around with this when I have Time.
