### ISSUE TITLE
[BUG] Keyboard shortcuts for text editing (copy/cut/paste/select all) are inserting additional character on Mac OS

### ISSUE THREAD

**Issue by jhinch** [amethyst/amethyst#2459]
## Description

Copy, cut, paste and select all appear to not be working correctly for the `TextEditing` component in `amethyst_ui` on Mac OS. The character for the shortcut (c/x/v/a) is inserted in addition to the shortcut action being performed.

## Reproduction Steps

1. Run `cargo run --example ui --features metal`
2. Click on the editable text box at the bottom of the screen
3. Attempt to use copy (cmd+c), cut (cmd+x), paste (cmd+v) or (cmd+a)

## What You Expected to Happen

The behaviour you would get in a native text editor i.e.

* Copy - The selected text is copied to the clipboard and no characters are inserted
* Cut - The selected text is copied to the clipboard and the selected characters are removed
* Paste - The contents of the clipboard is copied into the textbox at the cursor, any selected text is removed
* Select all - The contents of the text box is selected

## What Actually Happened

The shortcut character is inserted into the textbox at the cursor after the shortcut action is performed. This causes:

* Copy - the `c` character is inserted at the cursor
* Cut - the selected text is replaced with an `x` character
* Paste - The contents of the clipboard is pasted, followed by the `v` character
* Select all - The contents of the text box is replaced with the `a` character

This appears to be due to the `WindowEvent::KeyboardInput` event being followed a `WindowEvent::ReceivedCharacter` event. `winit` (the source of the events), does not document what the intended events are to be sent for keyboard events. The closest I could find was this comment https://github.com/rust-windowing/winit/issues/268#issuecomment-325712407 which seems to indicate that receiving both events is expected. I was not able to reproduce the issue on Windows so I assume it is Mac OS specific.

## Screenshots and Logs

N/A

## Your Environment

1. Operating System - Mac OS
2. Operating System Version - Catalina 10.15.6
3. Version of Amethyst - master (Tested at 2bffce61)

**Comment by Blisto91** [comment]
@CleanCut is this something you can confirm?

**Comment by CleanCut** [comment]
@Blisto91 Confirmed.

I _think_ the fix will have to be done in `amethyst_ui/src/text_editing.rs`, as from what I read from the linked issues above it sounds like this behavior is for reasons that will not go away.
