### ISSUE TITLE
[BUG] Parser Error with pong_tutorial_01

### ISSUE THREAD

**Issue by RobertBonagura** [amethyst/amethyst#2460]
## Description
Error: Parser Error expecting Map Colon after adding Rendering Bundle

## Reproduction Steps

1. Go to https://github.com/amethyst/amethyst/tree/master/examples/pong_tutorial_01
2. copy code from https://book.amethyst.rs/stable/pong-tutorial/pong-tutorial-01.html
3. Build code

## What You Expected to Happen

The result of tutorial part 1

## What Actually Happened
After calling cargo build

```
   Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/pong`
Error: Error { inner: Inner { source: None, backtrace: None, error: Parser(Parser(ExpectedMapColon, Position { col: 13, line: 3 })) } }
```

## Your Environment

1. Ubuntu 16
3. Amethyst 0.15

**Comment by Grzybojad** [comment]
I had the same issue. The problem was caused by an UTF-8-BOM encoding on my `display.ron` file. Changing the encoding to ANSI or UTF-8 fixes the issue.

**Comment by Blisto91** [comment]
If the encoding is fine could you show the content of your display.ron

**Comment by RobertBonagura** [comment]
I still have to look into what it means to encode my display.ron, but here is what it looks like

```
(
  title: "Pong!",
  dimensions" Some((500,500)),
)
```

**Comment by Blisto91** [comment]
You have a " instead of a : after dimensions 👍

**Comment by RobertBonagura** [comment]
Now my error makes perfect sense!

```
   Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/pong`
Error: Error { inner: Inner { source: None, backtrace: None, error: Parser(Parser(ExpectedMapColon, Position { col: 13, line: 3 })) } }
```

How should I have interpreted my error to know it was referencing my config/display.ron file and not my main.rs?

**Comment by Blisto91** [comment]
To be fair the error messages aren't very obvious when they don't mention the offending file.

**Comment by RobertBonagura** [comment]
Now I have this
```
robert@bright-augura:~/Programming/pong$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/pong`
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.15.3
[INFO][amethyst::app] Platform: x86_64-unknown-linux-gnu
[INFO][amethyst::app] Amethyst git commit: UNKNOWN
[INFO][amethyst::app] Rustc version: 1.45.2 Stable
[INFO][amethyst::app] Rustc git commit: d3fb005a39e62501b8b0b356166e515ae24e2e54
[INFO][winit::platform::platform::x11::window] Guessed window DPI factor: 1
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unsupported', /home/bright-augura/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.3.3/src/lib.rs:326:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by RobertBonagura** [comment]
It compiles fine, but after running main 'panics' at Result::unwrap() ?

**Comment by RobertBonagura** [comment]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unsupported', /home/bright-augura/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.3.3/src/lib.rs:326:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1272
  14: core::result::Result<T,E>::unwrap
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libcore/result.rs:1005
  15: gfx_backend_vulkan::Instance::create
             at /home/bright-augura/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.3.3/src/lib.rs:326
  16: rendy_factory::factory::init
             at /home/bright-augura/.cargo/registry/src/github.com-1ecc6299db9ec823/rendy-factory-0.4.1/src/factory.rs:1032
  17: <amethyst_rendy::system::RenderingSystem<B,G> as shred::system::RunNow>::setup
             at /home/bright-augura/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_rendy-0.15.3/src/system.rs:148
  18: shred::dispatch::dispatcher::Dispatcher::setup
             at /home/bright-augura/.cargo/registry/src/github.com-1ecc6299db9ec823/shred-0.10.2/src/dispatch/dispatcher.rs:28
  19: amethyst::game_data::GameDataBuilder::build_dispatcher
             at /home/bright-augura/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.3/src/game_data.rs:481
  20: <amethyst::game_data::GameDataBuilder as amethyst::game_data::DataInit<amethyst::game_data::GameData>>::build
             at /home/bright-augura/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.3/src/game_data.rs:489
  21: amethyst::app::ApplicationBuilder<S,T,E,X>::build
             at /home/bright-augura/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.3/src/app.rs:895
  22: amethyst::app::CoreApplication<T,E,R>::new
             at /home/bright-augura/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.15.3/src/app.rs:202
  23: pong::main
             at src/main.rs:35
  24: std::rt::lang_start::{{closure}}
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/rt.rs:67
  25: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  26: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  27: std::panicking::try
             at src/libstd/panicking.rs:274
  28: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  29: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  30: std::rt::lang_start
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/rt.rs:67
  31: main
  32: __libc_start_main
  33: _start
```

**Comment by RobertBonagura** [comment]
I was getting this same error prior to running this pong directory when I ran the https://github.com/amethyst/amethyst-starter-2d repo.

For what it's worth, I just downloaded rust and cargo earlier today. Perhaps I did not complete installation correctly.

**Comment by RobertBonagura** [comment]
My Cargo.toml:
```
[package]
name = "pong"
version = "0.1.0"
authors = ["Robert <robert.bonagura@gmail.com>"]
edition = "2018"

[dependencies.amethyst]
version = "0.15"
features = ["vulkan"]
```

**Comment by Blisto91** [comment]
What's your graphics card?

**Comment by RobertBonagura** [comment]
`
08:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X] (rev e7)
`

**Comment by Blisto91** [comment]
Can you type this in the prompt and post the output
```glxinfo | grep 'renderer string'```

**Comment by RobertBonagura** [comment]
`OpenGL renderer string: Radeon RX 580 Series (POLARIS10, DRM 3.35.0, 5.4.0-42-generic, LLVM 9.0.0)`

**Comment by Blisto91** [comment]
It's weird because it looks like it's complaining about a Vulkan extension or similar being unsupported. But i don't think that should be the case.
Gonna try to do some digging.

**Comment by Blisto91** [comment]
Can you type this in the prompt and show the output
```sudo lshw -c video```

**Comment by RobertBonagura** [comment]
```
  *-display                 
       description: VGA compatible controller
       product: Ellesmere [Radeon RX 470/480/570/570X/580/580X]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:08:00.0
       version: e7
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
       resources: irq:81 memory:e0000000-efffffff memory:f0000000-f01fffff ioport:e000(size=256) memory:fcf00000-fcf3ffff memory:c0000-dffff
```

**Comment by Blisto91** [comment]
Thank you for sticking with me for so long!
Hope it's not too tiring

Could you try installing the latest amdgpu driver and see if that fixes the issue? ---> [Link](https://www.amd.com/en/support/graphics/radeon-500-series/radeon-rx-500-series/radeon-rx-580)

**Comment by RobertBonagura** [comment]
Just did but still no change to the error :/

**Comment by Blisto91** [comment]
Arg annoying.
What's your linux distro?

**Comment by RobertBonagura** [comment]
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by Blisto91** [comment]
Can you ```apt install vulkan-utils``` and then run ```vulkaninfo``` in the prompt and share the whole output through pastebin or something similar.
I'm gonna try to scan through it tomorrow when i have time.

It's about bedtime for me so sorry for leaving you hanging so far!

**Comment by RobertBonagura** [comment]
Surely, thanks for your help thus far. Perhaps this is a reason for the error
```
===========
VULKAN INFO
===========

Vulkan Instance Version: 1.1.70

Cannot create Vulkan instance.
/build/vulkan-UL09PJ/vulkan-1.1.70+dfsg1/demos/vulkaninfo.c:768: failed with VK_ERROR_INCOMPATIBLE_DRIVER
```

**Comment by Blisto91** [comment]
Oh no. You make me want to stay up and look more into it.

It seems to be a driver problem which makes sense since your card should support vulkan properly.
```apt install libvulkan1 mesa-vulkan-drivers``` what happens after you try this?

**Comment by RobertBonagura** [comment]
Fixed :)

**Comment by RobertBonagura** [comment]
Or so I think. vulkaninfo returns alot of data and now pong is running

**Comment by RobertBonagura** [comment]
Any resources for what exactly happened? I understand close to nothing about graphics cards/drivers/vulkan. Is it possible I never installed drivers for my graphics card? My computer is fairly new and I dont game on it

**Comment by Blisto91** [comment]
Wooot. I didn't think that would actually work because i assumed those were already included atleast with the amdgpu driver.

I haven't actually messed with vulkan on linux (or in general) because my previous laptop didn't support it.
mesa-vulkan-drivers is an open source implementation of the vulkan drivers and are usually used together with amd GPU's on linux.
libvulkan1 handles some of the layers between the driver and the hardware. I think atleast? dunno the details.

I didn't think to suggest the ```libvulkan1 mesa-vulkan-drivers``` thing earlier, even tho i knew about it, because i assumed them to already be included with your system.
So i learned something too! :)

**Comment by Blisto91** [comment]
On windows the vulkan drivers are included together with the amd driver installation

**Comment by RobertBonagura** [comment]
Though its probably worth mentioning I am getting the following errors:
```
[WARN][gfx_backend_vulkan] Unable to find layer: VK_LAYER_LUNARG_standard_validation
[WARN][rendy_factory::factory] Slow safety checks are enabled! Disable them in production by enabling the 'no-slow-safety-checks' feature!
```

**Comment by Blisto91** [comment]
Don't worry, that warning shouldn't affect anything.

**Comment by CleanCut** [comment]
Nice investigation!  Is this issue resolved, then?

**Comment by Blisto91** [comment]
Should be :) 

@RobertBonagura if you encounter any more problems then feel to open a new issue. Hopefully we can get you running with less effort than this time.
You are also welcome to ask over on our community forums or pop by the discord channel.

**Comment by QuentinJanuel** [comment]
Hi, I have the very same problem but on Windows, following the Pong! tutorial
How can I fix it?
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unsupported', C:\Users\QuentinJanuel\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-vulkan-0.3.3\src\lib.rs:326:41
```

**Comment by CleanCut** [comment]
@QuentinJanuel Is your combination of Windows version, CPU, and GPU compatible with Vulkan? (Are you running on an old system?)

**Comment by QuentinJanuel** [comment]
@CleanCut I'm on windows10 so it's not that old I suppose. Though I don't know what Vulkan is, I just wanted to learn amethyst. How can I know if my CPU and GPU are compatible, and if they are not, is there any work around?

**Comment by CleanCut** [comment]
@QuentinJanuel Windows 10 certainly can support it. Your best bet is to search for whether your specific CPU and specific graphics card support Vulkan. If they do, then you may just need to install the latest drivers from your graphics card vendor.  If they don't, you're out of luck until you upgrade/replace your hardware.
