### ISSUE TITLE
[BUG] Crash with display.ron UTF-8-BOM encoding

### ISSUE THREAD

**Issue by Grzybojad** [amethyst/amethyst#2463]
## Description

A runtime crash when using a `display.ron` file encoded using UTF-8-BOM or other BOM encodings.
Changing the encoding on this file to ANSI or UTF-8 fixes the issue.

## Reproduction Steps

This issue was discovered while following the "Setting up the project" part of the official [Pong tutorial](https://book.amethyst.rs/stable/pong-tutorial/pong-tutorial-01.html) but it should be reproducible for any project utilizing a `display.ron` file.

1. Set up an Amethyst project that utilizes a display config file
2. Create the config file and set its encoding to UTF-8-BOM (using Notepad++ for example)
3. Build the project using `cargo build`
4. Run the project using `cargo run`

## What You Expected to Happen

Expected the program to run or display a clear error suggesting to change the character encoding.

## What Actually Happened

Upon running the build, this error popped up and stopped the program
```
Error: Error { inner: Inner { source: None, backtrace: None, error: Parser(Parser(ExpectedStruct, Position { col: 1, line: 1 })) } }
error: process didn't exit successfully: `target\debug\pong.exe` (exit code: 1)
```

## Screenshots and Logs

![image](https://user-images.githubusercontent.com/18161644/91224373-4de55180-e722-11ea-9792-4aca160199c9.png)

## Your Environment

1. OS: Windows 10 Home
2. Amethyst: 0.15

**Comment by CleanCut** [comment]
For the benefit of folks without access to Windows, would you mind attaching an example file?

**Comment by Grzybojad** [comment]
Here's a UTF-8-BOM encoded display.ron file.
I changed the extension to .txt, because GitHub wouldn't accept a .ron file.

[display.txt](https://github.com/amethyst/amethyst/files/5130480/display.txt)

**Comment by Blisto91** [comment]
So I'm thinking out loud here without really having looked into it.
It should be possible to recode the stream as utf-8 (or whatever is preferred) before the parser tries to make sense of it.
Or even better would be if it didn't care much and were able to interpret all the common file encodings.

**Comment by Blisto91** [comment]
@Grzybojad Can you try pointing to [this branch](https://github.com/amethyst/amethyst/tree/allow-encoding-variants) and see if it fixes it?

**Comment by Grzybojad** [comment]
@Blisto91 using that branch fixed the problem. Both UTF-8-BOM and other BOM encodings I tried (UCS-2-BE BOM and UCS-2-LE BOM) worked fine.

**Comment by Blisto91** [comment]
Awesome. 
The encoding_rs_io crate will transcode the opened file into regular utf-8. It's tries to detect the encoding by sniffing for BOM's and picking the appropriate encoding to decode from, if supported. If a BOM isn't found, like in the case of UTF-8 without BOM, and it can't detect the encoding it will send the raw bytes through.

I'm still looking into detecting unsupported encodings or detecting invalid unicode characters so proper errors can showed. But haven't found a satisfactory solution yet.
