### ISSUE TITLE
[FEATURE MODIFICATION] Improve book styling

### ISSUE THREAD

**Issue by itsfarseen** [amethyst/amethyst#2466]
The heavy box shadow of sidebar and menu bar of the book make it look cluttered.
Especially on low resolution screens.
I am attaching screenshots with and without the shadows.
I understand this may be a subjective thing. So no hard feelings if the community doesn't agree with my views :) 

With shadows:

![2020-08-28-193534_1366x768_scrot](https://user-images.githubusercontent.com/40014472/91577532-75c4f700-e966-11ea-991e-276b895d8a5d.png)

Without shadows:

![2020-08-28-193501_1366x768_scrot](https://user-images.githubusercontent.com/40014472/91577541-78bfe780-e966-11ea-8189-1abb1ae17657.png)

**Comment by Blisto91** [comment]
Also adding some feedback here to keep it in one place.

When types or concepts are marked it isn't possible to see what's a link and what isn't.
<details>
<summary>Image</summary>

![links](https://user-images.githubusercontent.com/47954800/91605140-4915dd00-e970-11ea-99f5-1aa02c8d925c.PNG)
</details>

When lines are a certain length they stretch depending on the panel and window size.
<details>
<summary>Images</summary>

![words](https://user-images.githubusercontent.com/47954800/91605342-95f9b380-e970-11ea-9042-ef5fa8eeb5b8.PNG)
![words2](https://user-images.githubusercontent.com/47954800/91605346-98f4a400-e970-11ea-99aa-b9c1eb7193a3.PNG)
</details>
