### ISSUE TITLE
[ui integration] ui beautiful

### ISSUE THREAD

**Issue by josuesantos1** [amethyst/amethyst#2484]
## Description

could have a UI integration.  glade, qml or cef

## What problem does this solve? What need does it fill?
Amethyst not have ui beautiful And simple

**Comment by MrTanoshii** [comment]
There is amethyst_ui and also alternatives that are supported
https://github.com/amethyst/amethyst-imgui
https://github.com/amethyst/amethyst_iced

I hope this helps
