### ISSUE TITLE
[MAINTENANCE] Add bitrot lint checks to CI

### ISSUE THREAD

**Issue by str4d** [amethyst/amethyst#2500]
The current Actions CI job runs the test suite against Linux, macOS, and Windows, and additionally runs several lint checks (`rustfmt` and `clippy`). This exercises most of the main code and its corresponding tests (the `tiles` feature is enabled in addition to the default features `animation`, `audio`, `locale`, `network`, and `renderer`).

However, the example code is not checked by CI to ensure it still builds. In particular, the `rendy` example was broken four months ago when #2118 was merged (specifically by cfb68f6c3b697851e2e4bc0ea5f929aa01481328, which removed some APIs used by the example).

It would be useful to run `cargo check --examples` somewhere within CI, as an additional lint, to defend against this. This only needs to run on `ubuntu-latest`, as there is no target-specific code in the examples themselves. It might be useful to combine this with the `rustfmt` and `clippy` checks in a new `Lint` job, which can run in parallel with the main tests (but I'm not familiar with exactly how your CI is set up, so IDK if there's a requirement to run all necessary tests within a single job).

**Comment by CleanCut** [comment]
I love the idea! I added it as a tracked item in #2407 

Feel free to make a PR trying it out, if you like. I'd be happy to review.

**Comment by ezpuzz** [comment]
Fixed on legion_v2.  Thanks!
