### ISSUE TITLE
[BUG] locked FPS (FrameRateLimiter and VSync are ignored)

### ISSUE THREAD

**Issue by LU15W1R7H** [amethyst/amethyst#2503]
## Description

Currently every amethyst application runs at 30 FPS. There's currently no working (!) way of changing this.
Setting the `FrameRateLimitStrategy` to `Unlimited` doesn't change the max FPS.
On the amethyst discord Goat#7658 told me that VSync is responsible for this restriction.
There is a setting in the `DisplayConfig` where you should be able to disable VSync but it isn't respected.

## Reproduction Steps

Run an amethsy application and disable `vsync` in the `DisplayConfig` and set the `FrameLimitStrategy` on the application to `Unlimited`.
Observe that the application runs at 30 FPS.

## What You Expected to Happen

Amethyst respects the `vsync` setting and the `FrameRateLimitStrategy`.

## What Actually Happened

Amethyst ignores the options and still runs at 30 FPS

## Screenshots and Logs

Not applicable

## Your Environment

1. Arch Linux and Windows 10
3. Amethyst 0.15.3

## Additional Context
I need this feature for doing genetic evolutions of intelligent agents (neuroevolution). The learning process is currently limited by the FPS count.

**Comment by chemicstry** [comment]
Vsync is currently hardcoded in rendy https://github.com/amethyst/rendy/blob/5d4f91f6b05b8ffaddae6d9a519d1568eee9e48d/init/src/windowed.rs#L288

**Comment by LU15W1R7H** [comment]
@chemicstry is there a reason for this? Or could this be changed right now?

**Comment by chemicstry** [comment]
I don't know the history of this. Probably nobody bothered to implement it

**Comment by LU15W1R7H** [comment]
Okay, then I might take a look at implementing this, if I'm able to do it...
