### ISSUE TITLE
[MAINTENANCE] Documentation unclear for InputHandler::action_is_down

### ISSUE THREAD

**Issue by mfdorst** [amethyst/amethyst#2514]
## Description

[The documentation for `InputHandler::action_is_down`](https://github.com/amethyst/amethyst/blob/master/amethyst_input/src/input_handler.rs#L597) says:
```rust
    /// Returns true if any of the actions bindings is down.
    ///
    /// If a binding represents a combination of buttons, all of them need to be down.
    pub fn action_is_down<A>(&self, action: &A) -> Option<bool>
```
It does say what happens if none of the actions bindings are down. Does it return `Some(false)` or `None`?
Presumably it returns `Some(false)` under some circumstances and `None` under others. If that is the case, it should be documented. If not, then I think it should return `bool` instead of `Option<bool>`, right?

**Comment by OscarTHZhang** [comment]
This one can be closed

**Comment by grzi** [comment]
Thank you !
