### ISSUE TITLE
[BUG] Unable to build `pong_wasm` project

### ISSUE THREAD

**Issue by cmizzi** [amethyst/amethyst#2516]
I'm currently trying to build the [pong_wasm](https://github.com/amethyst/pong_wasm) project. However, I'm facing several problems. The first one is when I try to build the project using the `./build.sh` file, an error occurs:

```rust
> RUSTFLAGS="-C target-feature=+atomics,+bulk-memory" cargo build -v --target wasm32-unknown-unknown -Z build-std=std,panic_abort --features "wasm,gl"

error[E0425]: cannot find function `atomic_notify` in module `core::arch::wasm32`
  --> /home/p1ngouin/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-futures-0.4.12/src/task/multithread.rs:39:33
   |
39 |             core::arch::wasm32::atomic_notify(
   |                                 ^^^^^^^^^^^^^ not found in `core::arch::wasm32`
````

I have another error when trying the following command : 

```rust
> cargo build --features "wasm,gl"

error[E0432]: unresolved import `amethyst_window::winit::platform::web`
  --> /home/p1ngouin/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/0d2c008/amethyst_rendy/src/bundle.rs:82:47
   |
82 |         use amethyst_window::winit::platform::web::WindowBuilderExtWebSys;
   |                                               ^^^ could not find `web` in `platform`

error[E0412]: cannot find type `HtmlCanvasElement` in this scope
  --> /home/p1ngouin/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/0d2c008/amethyst_rendy/src/bundle.rs:79:24
   |
53 | impl<B: Backend> RenderingBundle<B> {
   |                - help: you might be missing a type parameter: `, HtmlCanvasElement`
...
79 |         canvas: Option<HtmlCanvasElement>,
   |                        ^^^^^^^^^^^^^^^^^ not found in this scope

   Compiling amethyst_audio v0.10.0 (https://github.com/amethyst/amethyst.git?branch=improvement/2228/chip-away-at-crashes#0d2c0083)
error[E0599]: no method named `with_canvas` found for struct `WindowBuilder` in the current scope
  --> /home/p1ngouin/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/0d2c008/amethyst_rendy/src/bundle.rs:86:67
   |
86 |         let window_builder = display_config.into_window_builder().with_canvas(canvas);
   |                                                                   ^^^^^^^^^^^ method not found in `WindowBuilder`

error: aborting due to 3 previous errors
```

I tested the builder from a sample project, but the same second error still occurs. What I'm doing wrong ?

**Comment by azriel91** [comment]
Hm, maybe they renamed `atomic_notify` -- there's a [`core::arch::wasm32::memory_atomic_notify.`](https://doc.rust-lang.org/core/arch/wasm32/fn.memory_atomic_notify.html) on the std docs. `pong_wasm` was created quite a while ago.

That said, on `master`, running `cargo update`, then `./build_release.sh` worked:

```
    Finished release [optimized] target(s) in 1m 47s
+ wasm-bindgen target/wasm32-unknown-unknown/release/pong_wasm.wasm --out-dir pkg --target no-modules
+ audio_context_workaround=const lAudioContext = (typeof AudioContext !== 'undefined' ? AudioContext : typeof webkitAudioContext !== 'undefined' ? webkitAudioContext : null)
+ sed -i s/const lAudioContext.\+$/const lAudioContext = (typeof AudioContext !== 'undefined' ? AudioContext : typeof webkitAudioContext !== 'undefined' ? webkitAudioContext : null)/ pkg/pong_wasm.js
```

Note that that means using `wasm-bindgen 0.2.68` as well (`cargo install wasm-bindgen-cli`). However, it doesn't run on chrome for me now, when it used to.

**Comment by cmizzi** [comment]
Thanks! The code compiles fine, but it's very slow on my computer (no error) but I cannot move any paddle and see the ball go away every few seconds. I also hear differents audio, but no visual update (maybe really slow FPS?). I created a simple basic template (just `clear_color` the canvas), but my CPU usage is very high just.

**Comment by azriel91** [comment]
ah! If you compile in `--release` mode (I think that's the only difference between `build.sh` and `build_release.sh`), the performance difference should be noticeable.

Re:moving paddles, you need to click on the canvas after clicking the button to get the events to go through. One could workaround the second click by making the canvas the thing to click to get pong to load (I've applied this workaround in my game a while back).

Re:no visual update, that's a flakey issue somewhere between the browser, the gfx library, and wasm bindgen instability. I tend refresh the page (when demoing).

Re:sound being slow, that's also a browser / cpal / wasm-bindgen issue, and right now it's a very patchy hack (push bytes to JS, and ask it to play), so it tends to be out of sync with the game anyway. I *think* miniquad/macroquad managed to get relatively responsive audio going.

**Comment by cmizzi** [comment]
I don't really understand all the underlying stack used but if you have some resources to share, I'll be happy to help improve the project!
