### ISSUE TITLE
Legion: amethyst_gltf

### ISSUE THREAD

**Issue by valkum** [amethyst/amethyst#2518]
I want to discuss how we progress with amethyst_gtlf as part of #2517.
GLTFs are kind of an asset and atelier-assets now is useable to load gltfs:

> here's a GLTF Importer for atelier-assets in another project: https://github.com/aclysma/renderer_prototype/blob/render-graph/demo/src/assets/gltf/importer.rs - _[Discord Link](https://discord.com/channels/425678876929163284/488363247284518922/773898186128752642)_

Therefore I would propose to add the integration of atelier to the next release as well. Bear in mind that @jlowry has an integration of atelier-assets in a fork, but it needs more testing ([Discord Link](https://discord.com/channels/425678876929163284/488363247284518922/777635849776398338))
So this might be a good kickstarter.

Other options are: dropping the gltf subcrate (or make it a stub for better migrating to atelier loading GLTFs later) or invest the time now but accept that this investment can become void.

**Comment by jlowry** [comment]
I am working towards the integration of atelier because of [this comment](https://github.com/amethyst/amethyst/issues/2404#issue-672888398) by @chemicstry:

> Porting prefabs is a difficult task because they are based on specs SystemData tuples to access component storages. This would require a complete rewrite for legion.
>
>Instead of wasting resources rewriting old systems, there is an option to switch to https://github.com/amethyst/atelier-assets, the long awaited asset system.

**Comment by ezpuzz** [comment]
Atelier is going to be used for new assets pipeline and we will integrate this importer

**Comment by grzi** [comment]
This is now in MR ready for a review.
