### ISSUE TITLE
[BUG] PhysicsBundle doesn't implement SystemBundle on 0.15.3

### ISSUE THREAD

**Issue by kmdreko** [amethyst/amethyst#2530]
Amethyst version `0.15.3` has introduced an issue causing `PhysicsBundle` to not implement `SystemBundle` as expected. This code:

```
use amethyst::GameDataBuilder;
use amethyst_nphysics::NPhysicsBackend;
use amethyst_physics::PhysicsBundle;

fn main() -> amethyst::Result<()> {
    amethyst::start_logger(Default::default());

    let game_data = GameDataBuilder::default()
        .with_bundle(PhysicsBundle::<f32, NPhysicsBackend>::new());

    Ok(())
}
```

with these dependencies:

```
amethyst = { version  = "0.15.3", features = ["empty"]  } 
amethyst_nphysics = "0.2.0" 
amethyst_physics = "0.2.0"
```

yields an error:

```
error[E0277]: the trait bound `PhysicsBundle<'_, '_, f32, NPhysicsBackend>: SystemBundle<'_, '_>` is not satisfied
   --> src\main.rs:270:48
    |
270 |         GameDataBuilder::default().with_bundle(PhysicsBundle::<f32, NPhysicsBackend>::new());
    |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `SystemBundle<'_, '_>` is not implemented for `PhysicsBundle<'_, '_, f32, NPhysicsBackend>`
```

Setting the `amethyst` version to `>=0.15.0, <0.15.3` (which Cargo.lock shows uses `0.15.1`) compiles successfully.

```
amethyst = { version  = ">=0.15.0, <0.15.3", features = ["empty"]  } 
amethyst_nphysics = "0.2.0" 
amethyst_physics = "0.2.0"
```

*Edit:*

It appears that `amethyst_physics` uses `amethyst_core` version 0.10.1 while `amethyst` itself uses `amethyst_core` 0.15.3 causing the core issue. It appears multiple sub-crates should be updated.

**Comment by Voodlaz** [comment]
https://github.com/AndreaCatania/amethyst_physics/pull/15

**Comment by grzi** [comment]
Was not directly linked to Amethyst but to an external project. Solved in https://github.com/AndreaCatania/amethyst_physics/pull/15
