### ISSUE TITLE
[MAINTENANCE] dirs is unmaintained; switch to dirs-next

### ISSUE THREAD

**Issue by brightly-salty** [amethyst/amethyst#2545]
## Description

The dirs crate (used as a build dependency for amethyst) is unmaintained as documented in RUSTSEC-2020-0053 (see the link below). The dirs-next crate is recommended as a replacement by the RustSec team.

## Reason

Future updates will not be reliably made to unmaintained crates. It is better to switch to maintained crates to receive future security updates or bug fixes.

## Impact

This change should not have any negative impacts; the dirs-next is a drop-in replacement for dirs at the moment.

## Additional Information

https://rustsec.org/advisories/RUSTSEC-2020-0053

I would be willing to implement this and submit a PR if it would be accepted.

**Comment by ezpuzz** [comment]
this is fixed
