### ISSUE TITLE
Add counters for total frames, elapsed time, FPS

### ISSUE THREAD

**Issue by ebkalderon** [amethyst/amethyst#257]
Besides tracking delta time and `fixed_update()` tick rate internally, we are missing quite a few timekeeping features that people might find useful, namely:

- [ ] Total number of frames
  * Should we provide separate counters for `fixed_update()` and `update()` ticks?
- [ ] Time elapsed since game start
- [ ] Average FPS measurement
  * Should we expose it as an integer? Floating point number?
  * What might be a good default sample rate? Should we measure samples per frame or per second/millisecond?

Users should be able to access these counters easily from within systems or game states (#233 introduces a shared `Engine` context that can be passed into `State` methods).

**Comment by torkleyy** [comment]
Should definitely be resources. But IIRC correctly we won't have `update` anymore (but just let systems do the job).

**Comment by ebkalderon** [comment]
What do you mean by that? I was unaware we had planned to remove `State::update()`.

**Comment by Aceeri** [comment]
Heres something I wrote a week or two ago for a snake game: https://github.com/SDRust/July-2017-challenge/blob/master/src/tick.rs#L12

**Comment by minecrawler** [comment]
Imho, it would be useful to have

- FPS
- average seconds per frame since x
- fastest frame since x
- slowest frame since x

The "since x"  part should be seen as a way to define a time-frame.

Here a little code snippet I am using for the mentioned stats, so you know what I am talking about. It uses one second as time frame, over which it observes and finally displays stats.

```rust
fn update(&mut self, world: &mut World, _: &mut AssetManager, _: &mut Pipeline) -> Trans {
    use amethyst::ecs::resources::Time;

    let time = world.read_resource::<Time>().pass();
    let delta_time = time.delta_time.subsec_nanos() as f32 / 1.0e6;

    if self.frame_stats.sum >= 1.0e3 {
        println!("INFO: FPS={}\tslowest={:.5}ms\tfastest={:.5}ms\terror={:.5}ms\tATPF={:.5}ms",
                 self.frame_stats.count as u32,
                 self.frame_stats.slowest,
                 self.frame_stats.fastest,
                 self.frame_stats.sum - 1.0e3,
                 self.frame_stats.sum / self.frame_stats.count,
        );

        self.frame_stats.sum = 0.0;
        self.frame_stats.count = 0.0;
        self.frame_stats.fastest = 0.0;
        self.frame_stats.slowest = 0.0;
    }
    else {
        self.frame_stats.sum += delta_time;
        self.frame_stats.count += 1.0;

        if delta_time < self.frame_stats.fastest || self.frame_stats.fastest == 0.0 {
            self.frame_stats.fastest = delta_time;
        }
        else if delta_time > self.frame_stats.slowest {
            self.frame_stats.slowest = delta_time;
        }
    }

    Trans::None
}    
```

**Comment by ebkalderon** [comment]
@Aceeri This might be a good start for FPS calculation at least. I like that it samples over a range of frames at a user-set regular interval to smooth the result out.
@minecrawler The fastest and slowest frame statistic looks very useful. However, I have a few reservations:

1. Is there a specific reason `State` stores time values in `f32` instead of the more accurate and precise `std::time::Duration`?
2. On a similar note, why is `count` an `f32` instead of a `u64` that gets typecast when needed?
3. Could it use `fixed_update()` instead of `update()` to make the calculation of `sum` more regular?

**Comment by minecrawler** [comment]
Well, that piece of code is just something I quickly put together some time ago and copy/pasted it here for illustration

1. There is no specific reason (other than performance, which I didn't benchmark yet)
2. it's f32 for fast f32-on-f32 calculations (or at least that was what I thought when I set it up, though now I think it doesn't matter, as I convert it on of two times anyway)
3. I feel like it should be a tool of measurement, which gets updated as fast as possible to produce accurate results. I think, `fixed_update()` might have a bad rhythm, hence lead to a greater deviation from the accurate time span, depending on the setup

**Comment by ebkalderon** [comment]
No worries! It's very helpful to have it here regardless; thank you for doing that.

My two big worries of using `f32` to store time durations is precision and the possibility for overflow on larger numbers.

I can understand your reasoning on comment number 3, though I would like to point out that the `Application` is always doing its own internal timekeeping for `fixed_update()` to ensure it's accurate to an acceptably high degree, plus it's stored in a more precise format (`Duration`). So why track the same delta times twice?

**Comment by Xaeroxe** [comment]
I don't really have much that's terribly useful to add here but one thing I've done in the past in order to get the instantaneous framerate is to just do `1 / delta_time_in_seconds.

**Comment by ebkalderon** [comment]
@Xaeroxe I was considering doing the same approach, but instantaneous framerate isn't all that useful in most cases, especially for profiling. But even if you're just displaying the current FPS as part of a debug overlay, it's still downright problematic.

You will get drastically inaccurate results (impossibly high or low) if the game loop gets paused (e.g. when stopped by a breakpoint in a debugger) or if the previous frame ran abnormally slowly. By changing your equation to something similar to what's shown below, we can smooth out any outliers and output a much more accurate measurement.

```rust
let total: Duration = past_few_deltas.iter().sum();
let avg_delta: f32 = duration_to_f32(total) / past_few_deltas.len();
let fps: f32 = 1.0 / avg_delta;
```

**Comment by OvermindDL1** [comment]
An optional more detailed FPS overlay of a Histogram would be very nice as well, and let you see when spikes happen and when so you can correlate it to actions.  At the very least the code to handle a Histogram with the user rendering it themselves would work, though an all-in-one would be very useful.

**Comment by Xaeroxe** [comment]
@OvermindDL1 That'd probably be easier to do once we get a UI framework in place.

(I find myself saying this a lot.  Perhaps that indicates we ought to prioritize getting that UI framework down.)

**Comment by nchashch** [comment]
> What do you mean by that? I was unaware we had planned to remove State::update().

I belive @torkleyy referred to [this](https://github.com/amethyst/amethyst/issues/238#issuecomment-315515234) comment.

**Comment by jojolepro** [comment]
From my scala game engine.
On Update:
stableDeltaAccum = BufferHelper.addToCircularBuffer(1)(stableDeltaAccum,deltaTime)
BufferHelper:
`type CircularBuffer[A] = Vector[A]
def emptyCircularBuffer[A]:CircularBuffer[A] = Vector.empty[A]
def addToCircularBuffer[A](maxSize:Int)(buffer:CircularBuffer[A],element:A)=buffer.drop(buffer.size - maxSize + 1) :+ element`

Basically a simple circularbuffer implemented with a vector can do the job of smoothing the fps values, with minimal effort.

**Comment by torkleyy** [comment]
I think it would be best to have this kind of functionality in an `amethyst_util` (or sth like that) crate, which provides nice systems / resources for all kinds of debugging and profiling.

**Comment by jojolepro** [comment]
I already started working on it a bit. I'm making the fps counter for my game, then I'll port it into some external crate.

**Comment by jojolepro** [comment]
```
Cur FPS: 2606.1145, Sampled: 2567.036
Cur FPS: 2517.3572, Sampled: 2562.5002
Cur FPS: 2500.425, Sampled: 2556.852
Cur FPS: 2562.4338, Sampled: 2555.094
Cur FPS: 2575.1294, Sampled: 2550.873
Cur FPS: 2626.685, Sampled: 2559.065
Cur FPS: 2563.419, Sampled: 2552.1375
Cur FPS: 2604.6687, Sampled: 2550.2002
Cur FPS: 2568.7527, Sampled: 2547.5942
```
Do we want the user to manually add the system + resource, or do we want the fps counter to be enabled by default in Application?

**Comment by Aceeri** [comment]
Probably manually add the system, adding it by default makes it more annoying to replace. Plus we'd need to add an option to remove it if we do it that way.

**Comment by jojolepro** [comment]
Allright, so I'll just add a amethyst_util crate, and dump all the function "helpers" + systems in it.

**Comment by Aceeri** [comment]
I don't think we need a new crate for that, I think the `amethyst` crate itself should just contain any "util", and engine specific stuff.

**Comment by Aceeri** [comment]
I believe this was solved by the FPSCounter resource?
