### ISSUE TITLE
[BUG] Dependency issues with legion-prefab

### ISSUE THREAD

**Issue by slondr** [amethyst/amethyst#2570]
## Description

When I try to install amethyst from git, `cargo build` reports the following error:
```
error: no matching package named `legion-prefab` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `amethyst_assets v0.15.3 (https://github.com/amethyst/amethyst?rev=f0dd344953a8748daee02ea6ca8b568056edc997#f0dd3449)`

```
legion-prefab is listed under the [patch] section of amethyst's Cargo.toml so I'm not immediately sure of why I'm seeing this error

(edit: looks like amethyst_assets doesn't have a patch section: see https://github.com/amethyst/amethyst/blob/f0dd344953a8748daee02ea6ca8b568056edc997/amethyst_assets/Cargo.toml#L56)

## Reproduction Steps

1. Add amethyst as a dependency of a project in cargo.toml, using the git master branch
2. run `cargo build`

## Your Environment

1. Operating System: Arch Linux
3. Version of Amethyst: git master (or the `debug-lines` branch)

## Additional Context

I also get this warning earlier in the cargo build ouput, which doesn't seem related but maybe it is:

```
warning: invalid character `/` in feature `atelier_importer/serde_importers` in package atelier-daemon v0.1.0 (https://github.com/radium-io/atelier-assets.git?rev=de0e3ab231cabd95c355ebd7da57be8a6405562a#de0e3ab2), characters must be Unicode XID characters, `+`, or `.` (numbers, `+`, `-`, `_`, `.`, or most letters)
This was previously accepted but is being phased out; it will become a hard error in a future release.
For more information, see issue #8813 <https://github.com/rust-lang/cargo/issues/8813>, and please
leave a comment if this will be a problem for your project.
```

**Comment by ezpuzz** [comment]
Thanks for the report, will patch this immediately.

**Comment by slondr** [comment]
Okay, I'm not sure why, but this didn't fix the issue.

For a minimum reproducible repo see: https://git.sr.ht/~slondr/ametest2/tree

**Comment by slondr** [comment]
![image](https://user-images.githubusercontent.com/13040688/103572093-0920b280-4e9a-11eb-9284-446223e69099.png)

**Comment by ezpuzz** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/13040688/103572093-0920b280-4e9a-11eb-9284-446223e69099.png)

for now copy the patch.crates-io section from the amethyst cargo.toml

I will try to find proper solution

**Comment by ezpuzz** [comment]
@slondr can you try #2575

**Comment by slondr** [comment]
@ezpuzz Yep, looks like that fixed the issue. Thank you so much!
