### ISSUE TITLE
[MAINTENANCE/DISCUSSION] Split out the small examples into an amethyst-examples repo

### ISSUE THREAD

**Issue by valkum** [amethyst/amethyst#2583]
With the recent landed #2579 the examples are now more easy to copy for newcomers. This is a big plus.
This comes with a drawback though. You now need to call the examples by using `cargo run -p $example` instead of `cargo run --example $example`.
As a frequent rust user I expect files/dirs (or to be more precise examples) in the example directory to be callable by using `cargo run --example $example`.

Furthermore I am not a fan of commenting out examples in master while merging huge changes.

A solution would be to split out the fine detailed examples (probably picked up in the book) into its own git repository.
These examples could follow releases/pre-releases of the main amethyst repo and we keep 2-3 more complex examples in the main repo to be able to test all facets of changes to the underlying codebase.
Furthermore, it would lower the traffic generated for larger LFS stored assets in the main repo.

A drawback would be that the release process needs to take care of enforcing that a second repository needs to be up2date, which currently could be error prone to human errors.

**Comment by ezpuzz** [comment]
> Furthermore I am not a fan of commenting out examples in master while merging huge changes.

This was the only way to get CI to be meaningful for the amethyst branch, otherwise I'd have to block them in the CI script and that seems less maintainable.  Now with #2579 there is a single list in Cargo.toml of the remaining broken examples in an easily readable format.  My thoughts were that the sooner we could release green `amethyst_*` crates the sooner users could utilize the code and give feedback.  I'm actively fixing the broken examples on master and we have other pledged contributors on discord.

> A drawback would be that the release process needs to take care of enforcing that a second repository needs to be up2date, which currently could be error prone to human errors.

We already have https://github.com/amethyst/amethyst-starter-2d which is not kept up to date with master and we have extremely limited human resources.  I barely knew this starter repo existed 😆 I would be open to an RFC about how to break up examples and keep them up to date.

> A solution would be to split out the fine detailed examples (probably picked up in the book) into its own git repository.
> These examples could follow releases/pre-releases of the main amethyst repo and we keep 2-3 more complex examples in the main repo to be able to test all facets of changes to the underlying codebase.

I think a primary factor in how long the Legion work has taken is that it is nearly impossible to test independent crates using the old examples because they are too complex (for example utilizing prefabs when they don't have to).  I think if a similar large-scale change (to a different renderer for example) were to take place in the future we could try to focus on maintaining full compatibility but changing the underlying ECS was too major a change to approach it this way.



>  This comes with a drawback though. You now need to call the examples by using `cargo run -p $example` instead of `cargo run --example $example`.
> As a frequent rust user I expect files/dirs (or to be more precise examples) in the example directory to be callable by using `cargo run --example $example`.

I know I mentioned on Discord but for anyone else reading this issue, many crates already do this.  Here is a rough search of them: https://github.com/search?l=&p=2&q=members+%3D+%5B%22examples+language%3ATOML&ref=advsearch&type=Code

Also similar game related crates do this such as https://github.com/EmbarkStudios/rust-gpu/tree/aed5204f4ac93578e3e9888256ee96c57deeb315/examples/runners/cpu

**Comment by valkum** [comment]
> 
> 
> > Furthermore I am not a fan of commenting out examples in master while merging huge changes.
> 
> This was the only way to get CI to be meaningful for the amethyst branch, otherwise I'd have to block them in the CI script and that seems less maintainable. Now with #2579 there is a single list in Cargo.toml of the remaining broken examples in an easily readable format. My thoughts were that the sooner we could release green `amethyst_*` crates the sooner users could utilize the code and give feedback. I'm actively fixing the broken examples on master and we have other pledged contributors on discord.
> 
> > A drawback would be that the release process needs to take care of enforcing that a second repository needs to be up2date, which currently could be error prone to human errors.
> 
> We already have https://github.com/amethyst/amethyst-starter-2d which is not kept up to date with master and we have extremely limited human resources. I barely knew this starter repo existed 😆 I would be open to an RFC about how to break up examples and keep them up to date.
> 
> > A solution would be to split out the fine detailed examples (probably picked up in the book) into its own git repository.
> > These examples could follow releases/pre-releases of the main amethyst repo and we keep 2-3 more complex examples in the main repo to be able to test all facets of changes to the underlying codebase.
> 
> I think a primary factor in how long the Legion work has taken is that it is nearly impossible to test independent crates using the old examples because they are too complex (for example utilizing prefabs when they don't have to). I think if a similar large-scale change (to a different renderer for example) were to take place in the future we could try to focus on maintaining full compatibility but changing the underlying ECS was too major a change to approach it this way.

Yeah I understand this. We should reconsider the release rules to include the starter templates need to be up2date. 

> > This comes with a drawback though. You now need to call the examples by using `cargo run -p $example` instead of `cargo run --example $example`.
> > As a frequent rust user I expect files/dirs (or to be more precise examples) in the example directory to be callable by using `cargo run --example $example`.
> 
> I know I mentioned on Discord but for anyone else reading this issue, many crates already do this. Here is a rough search of them: https://github.com/search?l=&p=2&q=members+%3D+%5B%22examples+language%3ATOML&ref=advsearch&type=Code
> 
> Also similar game related crates do this such as https://github.com/EmbarkStudios/rust-gpu/tree/aed5204f4ac93578e3e9888256ee96c57deeb315/examples/runners/cpu

The difference is, that rust-gpu and the ones I looked at from the search query is that they do not have a crate at repository root level. Their repos are simply workspaces. This way cargo run --example would give a more sane error msg than in our case.

**Comment by Benlitz** [comment]
>
> As a frequent rust user I expect files/dirs (or to be more precise examples) in the example directory to be callable by using `cargo run --example $example`.

I wouldn't call myself a frequent rust user or an expert in rust ecosystem but I had kind of the same feeling after this change, and I thought maybe it would be good enough to simply rename the `examples` folder to `samples` which is basically the same thing but could remove the confusion with whether to run that as `cargo --example` or simply as independent packages.

**Comment by grzi** [comment]
I'm actually a bit divided on this subject. On the first hand, I agree with the fact that It's a better practice to be able to run examples from the ```run --example``` command. 
As far as I'm concerned, the more standard we stay, the easier it is to read the repository for newcomers and new contributors. 
Now, it's a bit more complicated to work on these examples projects from my IDE as each project is now independent.
 
On the other hand, be able to just fork the project we need to start from scratch is a real plus. It's like having a lot of starters ready. 

I'm pretty sure that if we split the examples to another repository, we will struggle with the maintenance of this repository. They are useful to validate things, not only when a module is compiling, but also when it is used. 

I think we could re-think the hierarchy. I'm pretty sure we could clean up a bit and have significant show off examples. As said previously, there are some cross dependencies between a feature 'A' example and some features 'B' and 'C' that could be avoided.
I guess there should be one show off example for each crate, and all the other examples should be samples, like Benlitz said.

**Comment by ezpuzz** [comment]
>  Now, it's a bit more complicated to work on these examples projects from my IDE as each project is now independent.

I'm curious which IDE and what issues you are speaking of?

In vscode with rust-analyzer I am having great luck with the following settings at the root of the repo,  I can edit examples or library code and it is checked and analyzed:

```json
{
    "rust-analyzer.checkOnSave.overrideCommand": [
        "cargo",
        "+nightly",
        "clippy",
        "-Z",
        "unstable-options",
        "--message-format=json",
        "--workspace",
        "--all-features",
        "--all-targets"
    ],
    "rust-analyzer.assist.importPrefix": "by_crate",
    "rust-analyzer.hoverActions.debug": false,
    "rust-analyzer.hoverActions.run": false,
    "rust-analyzer.hoverActions.implementations": false,
    "rust-analyzer.inlayHints.enable": false,
    "rust-analyzer.updates.channel": "nightly",
    "rust-analyzer.updates.askBeforeDownload": false,
    "rust-analyzer.lens.enable": false,
    "rust-analyzer.rustfmt.extraArgs": [
        "+nightly"
    ],
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true,
    "rust-analyzer.cargo.allFeatures": true,
}
```

**Comment by grzi** [comment]
@ezpuzz I'm using IntelliJ && Visual studio Code. On VsCode it works great with your config though. I guess I need to find how to configure properly all the subprojects on IntelliJ.
