### ISSUE TITLE
Culling tilemaps for better rendering performances

### ISSUE THREAD

**Issue by Benlitz** [amethyst/amethyst#2592]
## Feature

Tilemap rendering

## Change

Cull the tilemaps at rendering according to the active camera, using a specific `DrawTiles2DBounds` implementation, so that the render pass does not iterate over all tiles of the map.

## Reason

Tilemaps are currently not culled when being rendered, making them very slow for large maps (say, 1000x1000 tiles). Culling allows to mitigate the problem.

## Additional Notes

I already have an implementation of this [in this branch](https://github.com/amethyst/amethyst/compare/master...Benlitz:tilemap-camera-culling). I can clean it up and open a PR if this idea is generally approved in this ticket (the meaningful part is just the large chunk of code in `pass.rs` if anyone wants to pre-review). There are a few caveats/things to know:
- this implementation is general, casting 4 rays at the four corners of the camera to find which tiles are going to be rendered there, and uses these tiles to build a bounding `Region`. It works for all cameras (ortho/persp) with all transforms (at least I think so :) I tested quite intensively). More efficient culling can be achieved with more constraints on the camera itself, but this approach already drastically improves performances
- it requires an `ActiveCamera` to be set. From what I've seen, this is not automatically set when the first camera is created and requires to do something like `world.fetch_mut::<ActiveCamera>().entity = Some(camera);` in the user code. Because of this, this `DrawTiles2DBounds` isn't the default one. Automatically assigning the active camera on the engine side could be considered.
- if there is no default `ActiveCamera`, the returned region is empty. This makes it easier to track a "missing active camera" problem, rather to falling back to the default method of rendering everything which would hide the problem but still have the same poor performances on large map. Other options would be panicking or at least outputing log, but I think disabling the active camera on purpose is something normal one user might want to do.
- the culling itself isn't ideal because the render pass is using `Region` which are axis-aligned (in tile space) rectangles (for example in case of a 45° rotated square tilemap, 2x more tiles than needed will be still rendered). Something to keep in mind for future improvement maybe, but this implem is still "good enough" I believe.
- there's still an issue with the fact that tiles are arranged using the Morton encoder (by default), while they are iterated linearly in the render pass (because iterating a region [is linear](https://github.com/amethyst/amethyst/blob/6d8d4c495fbb78bd3ec4b132dd38d899f19d3d3c/amethyst_tiles/src/iters.rs#L181-L203)), which defeat the purpose of using something like morton for tiles - I actually have better performances using a linear encoder instead, although I didn't precisely measure that. Initializing and filling the storage with morton is particularly slow to my observation. This last point is slightly off-topic but it might be worth re-evaluating the value of the morton encoder in a different ticket maybe.

**Comment by ezpuzz** [comment]
Considering this results in a drastic performance improvement with little to no effort from the user and if there are bugs they can still use the old version please make a PR!  I'd love to give this a try with a large map on my sanity project.

Thanks!

**Comment by ezpuzz** [comment]
@Benlitz created the PR for you, if you can get it up to date I will test and merge.

**Comment by Benlitz** [comment]
> 
> 
> @Benlitz created the PR for you, if you can get it up to date I will test and merge.

Hey, thanks!

Actually my bad, I didn't pay attention to the fact that legion was already merged into master... I was hoping to be able to open the PR immediately, but first I need to learn legion a bit and adapt the code. It shouldn't take too long tho!

**Comment by Benlitz** [comment]
It's ready now! But I can't update the PR description myself
