### ISSUE TITLE
un-recoverable freeze

### ISSUE THREAD

**Issue by AlveLarsson** [amethyst/amethyst#2613]
## Description
Freezes the entire engine and window when right-clicking on an element in the UI.
This is either a winit bug, or our UI event system

## Reproduction Steps
1 Enter the ui_from_code example
2 Right-click several times on any interactive UI element and poof. 

## Your Environment
Operating System: Windows 10
Version of Amethyst: Main branch

**Comment by AlveLarsson** [comment]
Further notes.
It seems to be only happening when holding down the left mouse button and a right-click at the same time causes the freeze

**Comment by AlveLarsson** [comment]
This is not UI specific, this happens on all the examples including the most simple window example

**Comment by ezpuzz** [comment]
> 
> 
> This is not UI specific, this happens on all the examples including the most simple window example

probably winit then, likely to do with mouse capture / hiding.
