### ISSUE TITLE
No example target name '...'

### ISSUE THREAD

**Issue by johanlindfors** [amethyst/amethyst#2628]
## Description
I just cloned the amethyst repository on my MacBook M1 and also on a Windows 10 device. Both devices have updated the toolchains (rustc 1.49.0) and both demonstrates the same error when trying to build any example.

What am I doing wrong? I can successfully run other crates examples with similar structure.

## Reproduction Steps

1. I run the following command in the root of the amethyst repository:

cargo run --example hello_world

## What You Expected to Happen
Expect the example to run...

## What Actually Happened
Output message:

error: no example target named 'hello_world'

## Your Environment

Operating System: Windows 10
Operating System Version: 19042.746
Version of Amethyst: latest from GitHub

Operating System: MacOS Big Sur
Operating System Version: 11.1
Version of Amethyst: latest from GitHub

**Comment by johanlindfors** [comment]
Aha, so the examples should be run with -p not --example...

My bad...

**Comment by jzyzxx** [comment]
I met the problem also,but how could i run the example well
