### ISSUE TITLE
What dependencies  shoud i install?

### ISSUE THREAD

**Issue by jzyzxx** [amethyst/amethyst#2630]
The readme file did not tellabout the dependencies list of windows10,could you tell me what shoud i do?I am confused.

**Comment by MrTanoshii** [comment]
What do you mean by dependencies?

**Comment by jzyzxx** [comment]
> What do you mean by dependencies?

Yes,dependencies

**Comment by jzyzxx** [comment]
> What do you mean by dependencies?

Such as mingW,visual studiocode......

**Comment by AlveLarsson** [comment]
@jzyzxx

On windows it is strongly recommended to use Visual Studio's Microsoft C++ compiler (toolchain), this should be already set up when you installed rust.

MinGW, mysys, etc is the Linux way of setup on windows using GCC and G++, this can be very tricky to set up, I recommend you being a Linux wizard for that one :P

So in general, you may want to check that you have good graphics drivers or hardware that supports Vulkan 
(this has been a recurring pitfall for newer devs)

if you get any errors then post them here 👍
