### ISSUE TITLE
Amethyst book unreachable: DNS issue

### ISSUE THREAD

**Issue by joristork** [amethyst/amethyst#2634]
## Description

It is not possible for me to reach the Amethyst book site at https://book.amethyst.rs/stable/ . This seems to be a DNS issue.

## Reproduction Steps

1. Open browser
2. Navigate to https://book.amethyst.rs/stable/

## What You Expected to Happen

To view the Amethyst site.

## What Actually Happened

On Firefox, I get the following error:
> Hmm. We’re having trouble finding that site.
> We can’t connect to the server at book.amethyst.rs.

## Screenshots and Logs

![Screenshot from 2021-02-17 12-00-30](https://user-images.githubusercontent.com/504681/108188387-32c72d80-7118-11eb-88d1-fa18f63dbc86.png)

## Your Environment

Operating System: Debian Linux
Operating System Version: sid
Version of Amethyst: n/a

## Additional Context

Our networks engineer suspects some DNS related misconfiguration for the Amethyst book site. The C-name resolves, but the cloudfront doesn't.
`book.amethyst.rs.       300     IN      CNAME   d1gjl9nafw3yuo.cloudfront.net.`

**Comment by sak96** [comment]
In my case i am not able to open [resource page](https://book.amethyst.rs/stable/concepts/resource.html) and later pages.
But the earlier page do load properly.

**Comment by AlveLarsson** [comment]
Thanks for the report, our AWS server went down, I'm moving us over to Netlify as we already have 80% of our stuff there

we now have configs the configs on a repo (WIP)
https://github.com/amethyst/amethyst-doc-deploy

**Comment by grzi** [comment]
his is now resolved. Thank you for the report ! <3
