### ISSUE TITLE
Flexible localization

### ISSUE THREAD

**Issue by Klaider** [amethyst/amethyst#2635]
## Feature

The `locale` module (crafted from [Fluent](https://crates.io/crates/fluent)) seems to lack flexibility when it comes to resource loading.  I've just published [recoyx_localization](https://crates.io/crates/recoyx_localization), which compared to Fluent instead accepts simple JSONs, but in the other hand is straighter to use.

`recoyx_localization` pros:

- Manages resources, dinamically loads and optionally cleans previous unused locale resources.
- When switching to a new locale on a `LocaleMap`, it aborts once a resource fails to load, keeping every previously loaded resource as is.

`recoyx_localization` cons:

- No plural formatting, but it supports specifying single quantity (applied to message identifier).
- No currency formatting.
- No date formatting.
- No collation formatting.

Note it can reflect the current `Locale` of a `LocaleMap` with `locale_map.current_locale()` and use `locale.standard_tag().to_string()`.

## Change

Add a feature to replace `amethyst::locale` to use `recoyx_localization`.

## Reason

Localization implementation can be difficult to change as Amethyst grows, thus I'm suggesting support for my localization crate.

**Comment by MrTanoshii** [comment]
Are there any plans to work on those cons?

I feel like currency and date formats, especially, are important for games

**Comment by Klaider** [comment]
@MrTanoshii I'm wanting to support these. [Chrono](https://crates.io/crates/chrono) is like ECMAScript Temporal if I'm understanding correctly. It supports localized formatting with a locale code as parameter (`locale.standard_tag().to_string()`), however it also requires the format (which varies for `Locale`). Currency needs to be able to fetch the current unit values.
