### ISSUE TITLE
What does e7602a22dba669ac0264298474e76ad03b084d65 wrok for?

### ISSUE THREAD

**Issue by NichtsHsu** [amethyst/amethyst#2668]
## Description

I feel weird about this commit "replace Read with read_resource" e7602a22dba669ac0264298474e76ad03b084d65 . For an example, we will get following code at [`book/src/concept/event-channel.md`](https://github.com/amethyst/amethyst/blob/main/book/src/concepts/event-channel.md) after this commit:

```rust
# struct MySystem;
# 
# impl System for MySystem {
    type SystemData = .read_resource::<EventChannel<MyEvent>>();
#   fn build(mut self) -> Box<dyn ParallelRunnable> {}
# }
```

But hey, what meas `.read_resource::<EventChannel<MyEvent>>()`? How can we assign `.read_resource::<EventChannel<MyEvent>>()` to `SystemData`? In fact, I can't compile it anyway.

**Comment by rdelfin** [comment]
Looks like it was a blind search and replace, I'm guessing as part of the refactor to Legion and thus is still WIP (master seems to be getting used for dev work). @ezpuzz might be able to clarify better though

**Comment by ezpuzz** [comment]
probably something I didn't finish in my docs updates.  sorry haven't been around much.  if I find sometime will revisit.  Had a way I was testing the docs that would've caught that.
