### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by uzytkownik** [amethyst/amethyst#2679]
## Description

Documentation links seems to be broken:

- docs.rs currently failed to build 0.15.x amethyst
- Most links on webpage (both for master and 0.15) go to 'API Index' page
- Documentation from index page is only for main package without dependencies which means it only lists submodules but does not include documentation of structs etc.
- There is https://docs-src.amethyst.rs/stable/amethyst/ which do include them however
- However 'master' documentation does not cover 0.16 changes
- I could not find 0.16 book link

**Comment by AlveLarsson** [comment]
Thanks for the report, yes all this will be fixed soon, we are moving the entire documentation into the new main site
so there will be a 0.15x section and the master branch API and Book

**Comment by muttering-oldman** [comment]
Is there any progress on this issue?

**Comment by korczis** [comment]
Any news?
