### ISSUE TITLE
Integrate Bors

### ISSUE THREAD

**Issue by Xaeroxe** [amethyst/amethyst#268]
Do we want to use bors with this repository in order to keep the build badge "evergreen"?

**Comment by Xaeroxe** [comment]
(I'd be happy to set it up if answer is yes.)

**Comment by torkleyy** [comment]
Only org owner can do that, so that would be @ebkalderon

**Comment by ebkalderon** [comment]
Good idea! I'm on it.

**Comment by Xaeroxe** [comment]
@ebkalderon This looks to me to be the easiest way to accomplish it https://bors.tech/

**Comment by torkleyy** [comment]
Increasing priority to "important" since merging different commits into `release-0.5` and others in `develop` can easily result in a broken build, which is exactly what bors prevents (it merges the commit into branch and tests it then).
