### ISSUE TITLE
Panics when hiding Ui

### ISSUE THREAD

**Issue by CassiopeiaStar** [amethyst/amethyst#2685]
(This is my first github issue so please be nice)
## Description
Panic when hiding Ui renderables.

I'm not sure, but it looks like in amethyst_ui/src/pass.rs, it appears entities with Hidden and HiddenPropagate are filtered out of the query on line 337, then the entity is still expected in the query on line 349. 

## Reproduction Steps
1. Create an aplication with the RenderingBundle, UiBundle, and HideHierarchySystem  
2.  Create an entity with Hidden or HiddenPropagate, UiTransform, and UiImage (or another Ui renderable) 

## What You Expected to Happen
The entity would be created hidden without panicking.

## What Actually Happened
Panics and exits the application.

## Screenshots and Logs
[INFO][distill_daemon::asset_hub_service] tokio::net::TcpListener accepted
thread 'main' panicked at 'Unreachable: Entity is guaranteed to be present based on earlier actions: AccessDenied', C:\Users\Cassandra\.cargo\git\checkouts\amethyst-fedb0a1032a075ce\c132d1a\amethyst_ui\src\pass.rs:349:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

## Your Environment
Operating System:  Windows 10 home
Operating System Version:  20H2
Version of Amethyst:  Amethyst git commit: c132d1a498350f6bd040d30dc0a061fc77b61f31

**Comment by jlowry** [comment]
Thankyou for posting this.

It would be super helpful if you could link to a minimal project on Github we could use to reproduce the issue.

**Comment by CassiopeiaStar** [comment]
I've created a project linked below. This has a different error message than the one I was receiving on my other project. I'm not sure what is causing the differences.

https://github.com/CassiopeiaStar/amethyst-hidden-ui-bug
