### ISSUE TITLE
Migrating to a GitHub organization

### ISSUE THREAD

**Issue by ebkalderon** [amethyst/amethyst#27]
This is a big step, but I think I'm ready to migrate the Amethyst repositories away from my personal account to [a GitHub organization](https://github.com/amethyst). Before I do this, I need to confirm the following matters:

1. What are the potential consequences? I know that the Git repos and their associated metadata will be automatically redirected. But what about:
   * The Amethyst book and docs on GitHub Pages
   * The links on *TWIA*, Twitter, Reddit, etc.
   * The Gitter chat ([some people have had issues when transferring ownership](https://github.com/gitterHQ/gitter/issues/616))
2. Is everyone okay with the name? I picked "amethyst" since that was what was available. Would you prefer "amethyst.rs" or something completely different?
3. We need to decide on a concrete branching model that complements our [Semantic Versioning](https://github.com/ebkalderon/amethyst/wiki/Releases) strategy. @LucioFranco suggested [Git Flow](http://nvie.com/posts/a-successful-git-branching-model/) on the Gitter chat. It might be overkill now, but if we continue growing it could become necessary.
4. I have registered the "amethyst.rs" domain through ISTanCo! How would you like the website to be organized? Here are my thoughts:
   * **amethyst.rs:** The main website
     * **amethyst.rs/book:** The online Amethyst book
     * **amethyst.rs/doc:** Rust API documentation
   * **blog.amethyst.rs:** Redirects to *This Week in Amethyst* on Wordpress (unless we successfully migrate it to gh-pages, see #26)
5. The Gitter chat is starting to get really busy. I'm considering splitting it into multiple rooms. See this [GitterHQ post about Community Pages](http://blog.gitter.im/2015/08/11/introducing-community-pages/) to see how it could look. Is this a good idea? If so, how should the rooms be organized?

## Current Status

Here's the current status of these questions, as gathered from our collective discussion both on this issue and on Gitter:

- [x] Eliminating possibly broken links
   - [x] **Book and documentation**: I will make a pull request against `master` on this repo to "future-proof" these links before taking down https://ebkalderon.github.io/amethyst.
   - [x] **Links on _TWIA_, Twitter, Reddit, etc**: For the wiki pages, I can fix broken image/file links by moving images over to the organization website repository. The WordPress blog can remain open for a little while longer to preserve old links, and I can make a post asking followers to migrate to the new site and feed.
   - [x] **Gitter**: I guess we can't prevent link breakage, so I will keep the old chat open for continuity. However, everyone is urged to move to the new chat once it's deemed ready.
- [x] Organization name choice
   * No complaints on the name yet, so I am assuming the silence == agreement. :smile: 
- [x] Branching strategy
   * We will follow the Git Flow branching strategy, which is essentially equivalent to what GFX does.
- [x] Website organization
   * Again, no complaints from anyone, so I guess we're good on this one!
- [x] Splitting up the Gitter chat into different rooms
   * General consensus is a `general` channel + 1 channel for each repository. I personally want documentation to be a separate room since it crosses repository boundaries. How does this room layout look to you guys?
      * **documentation**: Discussions about the book and API documentation
      * **engine**: Development discussion about the engine
      * **general**: Team-wide announcements and answering general questions
      * **random**: Off-topic discussion and other tomfoolery
      * **tools**: Development discussion about the toolchain around the engine
      * **website**: Contributing to the website and the TWIA newsletter

**Comment by LucioFranco** [comment]
For `#3` I think we should go with something similar to what [gfx/gf-rs](https://github.com/gfx/gfx-rs) does and have a `stable` or `master` branch, it contains the current code that has been tested. We can then have branches for every `0.X` release and for every `0.X.Y` release we can just put those commits on top of the `0.X` branch. Everything else seems good!

**Comment by ebkalderon** [comment]
@LucioFranco I would personally prefer having a single `release` branch with each release version being tagged, similar to Git Flow's approach, mostly because I can see the sheer number of branches becoming overwhelming a few major versions down the line. What do you think about this?

**Comment by White-Oak** [comment]
@ebkalderon I'm up for this. But if, in the future, someone will request a bugfix for an older version (say, 1.5, when current is 1.7) it makes sense to branch out from tagged release and submit a bugfix.

**Comment by ebkalderon** [comment]
@White-Oak That is absolutely correct, yes.

**Comment by LucioFranco** [comment]
@ebkalderon Sorry for the delayed response was on vacation. I agree with your point. One thing that I want to bring up is the future support of 0.X or when time comes A.X releases.  One issue with theses is that they are more likely to need long-term support. It may be nice to only create branches for very major releases. This will allow for a cleaner way of managing old releases and to easily submit bugfixes. I find that git tag is very complicated to hotfix code without added branches. So it may be worthwhile having a few branches for major releases. We can always delete old branches. Besides that, I think everything looks good!

**Comment by White-Oak** [comment]
@LucioFranco you can always branch out from every commit, so I don't see, why keep branches, instead of creating them when they are needed.

**Comment by LucioFranco** [comment]
@White-Oak will that not add a bunch of hotfix branches that need to be added to the repo? You need to create a new branch to hotfix no matter what unless you wanna do git magic. So to me, it makes more sense to have a major branch and just add the hotfix commits on top of that. But what I am also saying is that we do not keep smaller versions for branches. If someone has an issue with 1.5 we just tell them to upgrade to the latest because it has no breaking changes instead of hotfixing 1.5. But if there is an issue with 1.3 and we are on 2.1 there would be a release-v1 branch that we can then easily hotfix. We can still use git tags for every version to keep track but going into detached head mode with git tags is not an easy thing to deal with.

**Comment by White-Oak** [comment]
@LucioFranco compatibility between minor versions is a myth

**Comment by LucioFranco** [comment]
@White-Oak so what you suggest then is to just keep everything tagged with git tag and then when a hotfix is needed create a branch for it?

**Comment by White-Oak** [comment]
@LucioFranco yes, why not? If a version is compatible with current one, then a separate branch is not needed, but sometimes there'll be a need.

**Comment by LucioFranco** [comment]
@White-Oak That makes sense. That means we only need extra branches for that one off occasions where someone needs an old hotfix.

**Comment by ebkalderon** [comment]
Here's the current status of these questions, as gathered from our collective discussion both on this issue and on Gitter:

1. Eliminating possibly broken links
   - [ ] **Book and documentation**: I believe the book's Markdown source should remain here on this repository since it counts as engine documentation and should be locally accessible to users along with the Rustdoc pages. I'm willing to make a pull request against `master` on this repo to "future-proof" these links before taking down https://ebkalderon.github.io/amethyst. Are you all okay with this?
   - [ ] **Links on _TWIA_, Twitter, Reddit, etc**: Undiscussed. For the wiki pages, I can fix broken image/file links by moving images over to the organization website repository. What about the existing WordPress blog? What about the existing followers and RSS feeds? Does Cobalt.rs support email notifications and RSS feeds, perhaps like *This Week in Rust*?
   - [ ] **Gitter**: Undiscussed. Not sure how to preserve hyperlinks to old posts once we move.
2. Organization name choice
   - [x] No complaints on the name yet, so I am assuming the silence == agreement. :smile: 
3. Branching strategy
   - [x] We will follow the Git Flow branching strategy, which is essentially equivalent to what GFX does.
4. Website organization
   - [x] Again, no complaints from anyone, so I guess we're good on this one!
5. Splitting up the Gitter chat into different rooms
   - [ ] Undiscussed. How does this room layout look to you guys?
      - **development**: Discussions about the internals of the engine and toolchain
      - **documentation**: Discussions about the book and API documentation
      - **general**: Team-wide announcements and answering general questions
      - **random**: Off-topic discussion and other tomfoolery
      - **webdev**: Contributing to the website and the TWIA newsletter

**Comment by LucioFranco** [comment]
@ebkalderon 
For the rest of the items. I think we should just split our Gitter chat into:

**general**
**engine**
**documentation**
**render** *possibly*

And I don't think there is a way of preserving the hyperlinks and I think it is better that we move soon rather than later to run into less of these types of issues.

**Comment by White-Oak** [comment]
@LucioFranco there should be a room for **website**

**Comment by LucioFranco** [comment]
@White-Oak I was thinking of combing **website** into **documentation**. There could probably be a better name

**Comment by Aceeri** [comment]
@LucioFranco Maybe information?

**Comment by White-Oak** [comment]
@LucioFranco I do not really think website should be merged with documentation.

**Comment by LucioFranco** [comment]
@White-Oak why is that? I think that there is not going to be much website so there should just be one chat for all things related to stuff on the website.

**Comment by ebkalderon** [comment]
@LucioFranco Personally, I prefer to keep webdev and documentation separate since I consider them separate things. For example, our conversations about CloudFlare, domain names, and DNS records are completely separate from, for example, adding book chapters or improving misleading docs.

While the book and API docs happen to be hosted on `amethyst.rs`, they are stored in the `amethyst`  repository for a reason. They are meant to be accessible locally, not just online, and should be treated separately from the website.

Does this make sense?

**Comment by LucioFranco** [comment]
@ebkalderon that makes sense! I think we should go ahead with what you suggest!

**Comment by White-Oak** [comment]
@ebkalderon sounds reasonable.

**Comment by ebkalderon** [comment]
Okay. I've updated the top post with the candidate Gitter chat layout. Looks good?

**Comment by ebkalderon** [comment]
I think we have reached a consensus on all of the proposed issues! We are ready for the transition.

**Comment by ebkalderon** [comment]
We are almost done! This is all that is left:

- [ ] Codify the branching model in either `CONTRIBUTING.md` or on the wiki.
- [ ] Wait for [Gitter issue 1185](https://github.com/gitterHQ/gitter/issues/1185) about improving our chat rooms to be resolved

**Comment by ebkalderon** [comment]
With the tasks above complete, this issue is now considered resolved.
