### ISSUE TITLE
RenderToWindow::from_config_path - Parse Errors include filename that couldn't be parsed

### ISSUE THREAD

**Issue by TimVanDyke** [amethyst/amethyst#2703]
## Feature
from_config_path

## Change
I would like to see the file path or file name printed to the console in parsing errors.

Ex: 
Current: 
`Error: Error { inner: Inner { source: None, backtrace: None, error: Parser(Parser(ExpectedMapColon, Position { col: 13, line: 3 })) } }`

Preferred: 
`Error: Error { inner: Inner { source: None, backtrace: None, error: Parser(Parser(*FILE_PATH:* ExpectedMapColon, Position { col: 13, line: 3 })) } }`

## Reason
I'm a Rust and Amethyst noob and seeing more detailed errors will help me better find my errors. I am also not the only one who has had issues with not knowing where my error is. 
 - https://github.com/amethyst/amethyst/issues/2460

**Comment by kirusfg** [comment]
This would require refactoring `amethyst_error` crate's `ConfigError` and everything that uses it. Not a difficult, but rather tedious task. I would label it as a good first issue, @AlveLarsson.
