### ISSUE TITLE
Examples fail to run second time with error: failed to load manifest for workspace member .assets_db

### ISSUE THREAD

**Issue by eqkessel** [amethyst/amethyst#2723]
## Description
Attempting to run an example fails with error `failed to load manifest for workspace member`.

## Reproduction Steps

1. Clone repository into local folder with `git clone https://github.com/amethyst/amethyst.git`.
2. Run an example using `cargo run -p  hello_world` as per the examples folder [README](https://github.com/amethyst/amethyst/blob/main/examples/README.md). I tried examples `hello_world`, `window`, and `sphere`. This successfully compiles and runs.
3. Attempt to run an example again using `cargo run -p window`. I tried examples `hello_world`, `window`, `sphere`, and `pong_tutorial_01`.

## What You Expected to Happen
The example compiles and runs.

## What Actually Happened
Cargo fails to compile or run the example.

## Screenshots and Logs
Upon running `cargo run -p window` (or any other example) in PowerShell:
```
error: failed to load manifest for workspace member `C:\Users\redne\Documents\Git\Amethyst\amethyst\examples\.assets_db`

Caused by:
  failed to read `C:\Users\redne\Documents\Git\Amethyst\amethyst\examples\.assets_db\Cargo.toml`

Caused by:
  The system cannot find the file specified. (os error 2)
```
`.assets_db` contains the following:
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        10/16/2021     18:16                cache
-a----        10/16/2021     18:16          45056 data.mdb
-a----        10/16/2021     18:16           8128 lock.mdb
```
`Cargo.toml` is indeed missing. Deleting the `.assets_db` folder after each example run allows the example to run again.

## Your Environment

Operating System:  Windows 10
Operating System Version: 20H2, build 19042.1237
Version of Amethyst: Compiler listed `amethyst_core v0.16.0` when building right after cloning.

## Additional Context

I am just starting out in Rust and hoping to learn the language by practical example. While I am a noob at this language, I haven't done anything except clone this repo and run an example, so I doubt I have caused this issue.

I have run `rustup update` before all of this.

**Comment by dellwatson** [comment]
Do u clone it into submodule? your path is confused

```rust
Caused by:
  The system cannot find the file specified. (os error 2)
```
usually that above caused by path corruption, and it is shown from yours `examples\.assets_db\Cargo.toml` and there's no .assets_db

can you try cargo new hello_cargo into examples and try to run it? I think it won't be working in ur case. if yes then try to clone new and cargo build from root folder
