### ISSUE TITLE
the focus screen functionality does not work at all

### ISSUE THREAD

**Issue by ninjarogue** [amethyst/amethyst#2726]
## Description

when I hit the shortcut key to focus screen 1, 2, or 3 etc, nothing happens

## Reproduction Steps

1. set hotkey for focus screen 1, 2 and 3
2. restart amethyst
3. use hotkeys to switch screens (1, 2, or 3)

## What You Expected to Happen

I expected the screens to switch

## What Actually Happened

nothing happened.

## Your Environment

Operating System: macOS Monterey
Operating System Version: 12.0.1
Version of Amethyst: 0.15.0

## Additional Context

I'm on a mac mini m1

**Comment by Epacnoss** [comment]
What focus screen are you talking about? Is this a MacOS thing?

**Comment by ninjarogue** [comment]
I'm not sure if it's a macOS thing, but for example 'Focus screen one' doesn't work

**Comment by BurntNail** [comment]
What is a focus screen?!

**Comment by ninjarogue** [comment]
It’s a command

**Comment by BurntNail** [comment]
Can you give any more detail? I've never heard of a focus screen, nor do I have any clue what it is.
Is this a Mac command, or are you getting mixed up with an Amethyst scene?

**Comment by ninjarogue** [comment]
If you go to preferences > shortcuts, and scroll down you should see "focus screen 1", "focus screen 2", etc. When I record a shortcut and try to use it, nothing happens. The command to "focus screen 1" doesn't work as expected.

**Comment by ninjarogue** [comment]
Sorry, I made a mistake. This isn't the same amethyst app I thought it was.

**Comment by BurntNail** [comment]
Phew - this is amethyst.rs - the Rust game framework, that work was recently stopped on.

**Comment by ninjarogue** [comment]
Sorry for the confusion!
