### ISSUE TITLE
Amethyst rendy is broken, the build is broken and has been broken for more than a year

### ISSUE THREAD

**Issue by CCCCC7** [amethyst/amethyst#2729]
## Description
Amethyst Rendy has been broken for more than over a year...
https://travis-ci.org/github/amethyst/rendy

## Reproduction Steps

1. Begin compilation
2. Get cucked because of bad maintainers

## What You Expected to Happen

Someone to maintain, something that is advertised as apparently the `holy grail` of game engines in rust.
Extremely, extremely disappointed.

## What Actually Happened

I ran build on every single backend possible, all failed.

## Screenshots and Logs

https://imgur.com/LyaRDpL

## Your Environment

Operating System: Windows 11
Operating System Version: Latest beta
Version of Amethyst: Latest

## Additional Context

Other than being disappointed in the community? No, that's about it.

**Comment by Epacnoss** [comment]
What version of rust are you running?

**Comment by CCCCC7** [comment]
> What version of rust are you running?

I am on the stable version of rust, its not even nightly. For like days, I have been in its windows or its rust or its amethyst, and finally. I think its all of the above.

**Comment by Epacnoss** [comment]
This was going to be fixed in 0.16, but that never got released (see [here](https://amethyst.rs/posts/amethyst--starting-fresh)). Assuming you're currently in 0.15.3, you'll need to change your rust version to 1.47.
`rustup override set 1.47` - type that into a shell whilst in your project.

**Comment by CCCCC7** [comment]
Thank you but I will not be using something that is not maintained. I wish this information was like way easier to get to, or in my face but I digress, thank you sensei.
