### ISSUE TITLE
Relicense under dual-license Apache2 and MIT

### ISSUE THREAD

**Issue by thiolliere** [amethyst/amethyst#28]
as you may know rust libraries are mostly dual-licensed in apache-MIT

The Apache license has protections from patent trolls and an explicit contribution licensing clause.
And the MIT is for GPLv2 compatibility (because Apache is not compatible with GPLv2)

[here](https://github.com/l1048576/fbx_direct/issues/1) a message from a crate.io bot for explanation of how to set dual-license in your project.

feel free to close it if your intension is to keep MIT alone.

Anyway great project, keep going :-)

**Comment by ebkalderon** [comment]
@thiolliere Thanks for pointing this out! I didn't really think about patent trolls and explicit contribution licensing when I first started the project, since I wasn't really sure if people were interested in helping or not. This seems like a good idea to me. Hopefully everyone else agrees.

# Contributor checkoff

To agree to relicensing, comment with :

```
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.
```

Or, if you're a contributor (looks like GitHub only shows contributors to `master`), you can check the box in this repo next to your name.

- [ ] @cooperra 
- [x] @ebkalderon
- [ ] @Oflor

**Comment by ebkalderon** [comment]
The source code is changing at quite a rate, and we need everyone on this list to chime in whether you support this transition. This has been sitting here for far too long now, we should arrive at a consensus ASAP.

**Comment by Aceeri** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by nchashch** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by csherratt** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by cooperra** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ebkalderon** [comment]
@Emilgardis @lschmierer @Oflor @palodequeso @White-Oak Please respond to this thread whether you support the licensing change or not. As contributors to this repository, your input is very valuable, and this thread cannot be closed until you chime in. Thanks!

**Comment by White-Oak** [comment]
My contribution to amethyst was pretty minor and I hope i can contribute more :), but, nevertheless, I checked myself in in that list.

**Comment by lschmierer** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Emilgardis** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by palodequeso** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by LucioFranco** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by serprex** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ebkalderon** [comment]
@msiglreith @Oflor Please chime in on whether you agree or disagree with this relicensing initiative! Thank you.

**Comment by msiglreith** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option

**Comment by Emilgardis** [comment]
It seems like @Oflor hasn't been active in a long time.

**Comment by Emilgardis** [comment]
Anyone doing work for the relicense? Seems like everyone is onboard. master on amethyst/website also needs to be changed to state that we are dual-licensed

**Comment by Aceeri** [comment]
I can do this later if no one else wants to.
