### ISSUE TITLE
Remove all `expect` and `unwrap` from source (where reasonable)

### ISSUE THREAD

**Issue by Binero** [amethyst/amethyst#301]
Right now when the engine isn't used exactly the way it's supposed to, it will often just leave the user with something along the lines of `thread 'main' panicked at 'called 'Option::unwrap()' on a 'None' value'`. Often enough, this happens in a thread other than main, so the end user cannot even use the back trace to figure out what he did that went wrong. 

It makes more sense to return a `Result` at all places, only using `except` where it is believed an error should be impossible. 

To make this easier, we can move to the [error-chain](https://github.com/rust-lang-nursery/error-chain) crate, to reduce the amount of boilerplate such a comprehensive result system would require.

**Comment by derekdreery** [comment]
I'm gonna have a look at this, since I'm an error-chain evangelist :P

**Comment by derekdreery** [comment]
I've implemented error handling using error-chain in #332 , just for the renderer so far.

**Comment by torkleyy** [comment]
@Binero I'm improving errors currently, and I remember you had such an issue while refactoring your code to use the latest version of Amethyst. Can you remember at which line the engine panicked?

**Comment by Binero** [comment]
@torkleyy IIRC the renderer expected a `Camera`when there wasn't any. It might also be worth logging to the console when a `Camera` doesn't have a `Transform`.

**Comment by Xaeroxe** [comment]
I feel the main thrust of this issue has been accomplished pretty satisfactorily.  So I'm going to close this.  Let me know if you disagree with my decision.
