### ISSUE TITLE
Decouple assets from renderer

### ISSUE THREAD

**Issue by Binero** [amethyst/amethyst#303]
Right now the asset loader and the renderer are pretty tightly coupled. For instance, to generate a mesh at runtime, one must hack their way through the loader. This is the result of the fact that `MeshComponent` is tightly coupled to `AssetPtr`. 

As such I propose the following:

1. When you load a `T` from the `Loader`, it gives you an `AssetFuture<T>` which implements `Component` whenever `T` does.
2. This `AssetFuture<T>` can be attached to an entity. 
3. There is an `AssetSystem` which tracks whenever these futures have been completed, and replaces the `AssetFuture<T>` components on these entities with `T`. 

As an added bonus, this system could leave behind a `LoadedAsset<T>` component, as to keep track of which entities use which assets. A `HotReloadAssets` system could then be added to iterate over these `LoadedAsset<T>`s, and replace them with new `AssetFuture`s when reloading is needed.

This approach has the advantage that when the asset system is not required, as it isn't for instance when you are generating meshes, it doesn't get in the way as it does now, preventing you from implementing your features. 

For instance, creating an entity with a mesh could look like this:
```rust
let assets = engine.world.read_resource::<Loader>();
engine.world.create_entity().with(assets.load("cube", ObjFormat)).build();
```

The code would add an `AssetFuture<Mesh>` to the entity. Once the asset has been loaded, the `AssetSystem` will replace the future with the loaded `Mesh`. If the user does not want to use the asset loader, or cannot use it because they are generating the meshes at runtime, they could simply add the `Mesh` directly, without going through `AssetFuture<Mesh>`.

**Comment by torkleyy** [comment]
This is very similar to my original implementation, as I already wrote yesterday. The problem here is that one has to be explicit about the hot reloading, since there is no information about where the asset came from, thus you would have to manage `LoadedAsset` yourself. How do you expect the user to do that?

**Comment by Binero** [comment]
There is several approaches the user could take here. Either they just add `LoadedAsset<T>` instead of all their assets, and then force the hot reloader to 'update' all the assets, essentially using it for initialisation as well. 

A second approach would simply be to store an identifier of the asset being loaded in `AssetFuture<T>`. We could even go as far as to provide a wrapper structure around `AssetFuture<T>`:

```rust
struct LoadingAssetComponent<T> {
    future: AssetFuture<T>,
    identifier: AssetSpec,
    enable_hot_reloading: bool
}
```

The second approach would be the most flexible approach.

**Comment by Binero** [comment]
@omni-viral proposed in gitter to have assets use streams as opposed to futures. That might fit in even better with the aforementioned second approach:

```rust
struct AssetLoaderComponent<T> {
    source: Stream<T>,
    identifier: AssetSpec,
}
```

The user could then specify for every asset whether it should be hot-reloaded or not. If it should be, it returns a `Stream` which will keep providing updates. If not, it returns a `Stream` which immediately exist. If the `Stream` closes, the `AssetSystem` would simply remove the component from the entity. The benefits:

 - The same system can manage hot reloading and loading, while in my previous proposal the hot reloading system would simply invoke the loading system on updates.
 - Hot reloading can be enabled on a per-asset basis.
 
I am not sure about how complex such a solution would be, however. @omni-viral might have more details on how to implement such a system.

**Comment by omni-viral** [comment]
@Binero If we will use `Stream` we will put it into `World` as `Component`.
`MergeStream` (or another name of our choice) will take it from `World` and remember what `Entity`s id was. Same as in [my PR](https://github.com/slide-rs/specs/pull/243).
The hard thing to do is quit `poll`in everything every frame.

**Comment by ebkalderon** [comment]
I really like the idea of using streams to unify the normal loading and hot-reloading behaviors into one system. It seems elegant to me, especially if we were to add in support for things like chunked assets that are continuously being streamed from disk, e.g. large outdoor maps.

@omni-viral Care to elaborate on the feasibility of adopting streams in the Specs `Merge` system?

**Comment by Xaeroxe** [comment]
I believe this was closed by https://github.com/amethyst/amethyst/pull/341 .  Please reopen if I'm mistaken.

**Comment by omni-viral** [comment]
@Xaeroxe this issue is also about breaking `MeshComponent` into pair. `MeshComponent` which is `Mesh` and nothing else. And additional component for hot reloading.
Same for `TextureComponent` etc

**Comment by OvermindDL1** [comment]
As an example, in my C++ ECS game engine I handle resources by loading a resource component of a given type, say a `AssetMeshComponent`, it has a string 'path' field on it that is the path to the mesh data in URI format.  If it is `file:///blah` then it would grab `/blah` from the virtual filesystem (which could be physical or zip files or so), it could even be `data://BASE64;`encoded as well (few supported formats) for the simple inlined stuff (generally only used for things like a cube mesh or a single pixel image).

A system would watch for these asset components based on the type of the asset component, so AssetMeshComponent had an AssetMeshSystem that listened for when these were added/removed.  It then used the URI in it to look up in its cache if it had already been loaded, if not then it loads it and stores it in the cache and then (or if it already was in the cache) takes it from the cache, put it on a transient component of type MeshComponent (transient's were never stored, never transmitted over a network, never serialzied, etc... etc...) that other systems, like the MeshRenderingSystem would then use to add it to the internal octree for rendering.

Things like the AssetMeshSystem would put on a placeholder MeshComponent (also able to be overridden by the component, but was a transparent purple cube for me by default until I overrode it) until the asset was fully loaded, at which point all wanting to use that mesh would be swapped with the real mesh.

Things like sound could preload multiple sounds at once keyed by one of my Atom64's, the AssetSoundComponent took a hashmap of Atom64's->URI's, then other systems could play sounds based on a keyed name that would be precached on the SoundComponent.  I only did this for sounds that should be always loaded in memory (at least while these entities are active) and music and so forth I still loaded via URI as-needed.

**Comment by Xaeroxe** [comment]
@OvermindDL1 You'll be happy to know we already have all of those features.  We use asynchronous loading for multiple assets, we have systems that can merge the assets in once they're ready to use, and we permit sharing of internal asset memory.

@omni-viral Since not all aspects of the issue are resolved I'll re-open it.

**Comment by OvermindDL1** [comment]
Woot!  What about loading assets via other locations, like via inline data or via http network call (which is very useful for grabbing, say, a contributor decoration or so).

**Comment by Xaeroxe** [comment]
@OvermindDL1 We mostly support that, this issue is concerned with making sure we have complete support for that.

**Comment by Xaeroxe** [comment]
I believe this issue has been resolved by our recent round of merging, please re-open if you feel I'm incorrect.
