### ISSUE TITLE
Builders

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#304]
Builders are often convenient for creating e.g. the `Application`, but as soon as you cannot add something in one step, need a loop, etc. it gets ugly and you end up with something like

```rust
builder = builder.with_something();
```

Would it make sense to have `with_` methods consume the builder and `add_` methods borrow them mutably? This would also resolve consistency issues in naming (current builder methods have `add_` and `with_` mixed).

**Comment by omni-viral** [comment]
And there is `register` without `prefix

**Comment by Xaeroxe** [comment]
I'm not sure I understand why consuming the builder should ever be necessary.  A lot of the places where both amethyst and specs do that seem to be unnecessary.  Can we not just use

```Rust
pub fn with_x(&mut self, x: X) -> &mut Self
```

**Comment by torkleyy** [comment]
No, I don't think so. We need to consume the fields of the builder at the end. We could in theory work around that, but I never saw anyone doing it:

```rust
let mut builder = Builder::new();

builder
    .add_x(x)
    .add_y(y)
    .add_z(z);

let built = builder.build();
```

**Comment by Xaeroxe** [comment]
Oh ok that makes sense actually.  Thanks!

**Comment by Xaeroxe** [comment]
I agree with the suggestion to standardize naming conventions then.

**Comment by ebkalderon** [comment]
I've found an interesting conclusion on https://github.com/colin-kiegel/rust-derive-builder/issues/2. It appears that non-consuming builders actually aren't that bad with all the cloning at the build stage, since the `clone()` invocations are actually optimized away at compile time!

**Comment by torkleyy** [comment]
Thing is that e.g. `World` cannot be cloned.

**Comment by ebkalderon** [comment]
@torkleyy Didn't think of that. Would storing the `World` in an `Option` help? The builder can replace the built `Some(World)` with a `None` at build time.

**Comment by torkleyy** [comment]
Theoretically we could.. But a builder which does not consume indicates that it can be used multiple times, which is not the case. Unwrapping the fields everywhere doesn't seem to be nice.

If you don't like the idea of having both, maybe we could consider the workaround above?

**Comment by torkleyy** [comment]
This has been partially fixed by #353. Now we only need to implement `add_` methods.

**Comment by gaudecker** [comment]
How should methods without prefix such as `TextureBuilder::dynamic` be named? Or the `register` method in `ApplicationBuilder` as @omni-viral pointed out?

**Comment by Rhuagh** [comment]
`register` is kind of special as it doesn't add any data to the world. My personal opinion is to keep it as `register`.

`TextureBuilder::dynamic` is a difficult one, since it changes the semantics of the data, not the actual data itself. I would probably name it `as_dynamic` to make it obvious it differs.

**Comment by torkleyy** [comment]
I agree with @Rhuagh. The `register` function really is special, you wouldn't use it in a loop or a conditional and registering is really just making sure it's there, since registering twice is a no-op. If we wanted to have the same distinction, we would have to rename it to e.g. `with_comp`.

**Comment by jojolepro** [comment]
Do we still have methods using add_xxx?

**Comment by jojolepro** [comment]
I think this was resolved. If I'm wrong please reopen.
