### ISSUE TITLE
Automatically create formatting PR

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#329]

**Comment by Binero** [comment]
Can't this be closed now?

**Comment by Xaeroxe** [comment]
Nope, because we still don't enforce formatting via CI.  I tried a few times but nothing got merged because I was indecisive.

**Comment by torkleyy** [comment]
My idea would still be to have a bot which just creates a PR every three days in case the codebase is not fully formatted. We could even auto-merge it in case bors doesn't have concerns.

**Comment by zoonage** [comment]
Maybe it's also worth having travis check that running `cargo fmt` doesn't result in any changes?

**Comment by Rhuagh** [comment]
It's harder than it sounds, we've tried a few times to do this.

**Comment by zoonage** [comment]
What about something like `cargo fmt -- --write-mode diff` inside an include-only matrix for rust stable and then checking the return code?

**Comment by torkleyy** [comment]
The problem with checking formatting on CI is that it makes contributions
harder and makes our builds break (and feature PRs incredibly large due to
formatting changes).
I prefer pure formatting PRs because of that.

**Comment by jojolepro** [comment]
Then we don't want to enforce formatting and we can close this?

**Comment by zoonage** [comment]
I think I agree with @torkleyy with the periodic formatting PRs, should we re-name the ticket to implement this? As @jojolepro said the ticket title is wrong

**Comment by jojolepro** [comment]
From @torkleyy 
>My idea would still be to have a bot which just creates a PR every three days in case the codebase is not fully formatted. We could even auto-merge it in case bors doesn't have concerns.

**Comment by torkleyy** [comment]
Thanks to @magnonellie's work on CI and efforts to stabilize rustfmt, this can be closed now.
