### ISSUE TITLE
Panic on DisplayConfig::load()

### ISSUE THREAD

**Issue by minecrawler** [amethyst/amethyst#331]
I am on the develop branch and using the following code always results in an panic for me:

```rust
let display_config_path = "resources/config.ron";
let display_config = DisplayConfig::load(display_config_path);
```

```ron
(
    display: (
        title: "",
        brightness: 1,
        fullscreen: false,
        dimensions: (1280, 800),
        min_dimensions: None,
        max_dimensions: None,
        vsync: false,
        multisampling: 16,
        visibility: true,
    ),
    logging: (
        file_path: "resha.log",
        output_level: "warn",
        logging_level: "debug",
    ),
)
```

```
thread 'main' panicked at 'Give me some!', C:\Users\marco_000\.cargo\registry\src\github.com-1ecc6299db9ec823\ron-0.1.1\src\de\mod.rs:88:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: process didn't exit successfully: `target\debug\re_sha.exe` (exit code: 101)
```

Any idea on how to fix that?

**Comment by torkleyy** [comment]
Something is calling `deserialize_any` which is currently unimplemented.

**Comment by minecrawler** [comment]
What puzzles me is that the examples work (they do not seem to call `deserialize_any`). Hence I think that it has to be something on my side. Something I am forgetting or overlooking.

**Comment by Xaeroxe** [comment]
@torkleyy "Give me some!" Is a funny error message but perhaps we could make it more helpful?

**Comment by Rhuagh** [comment]
Hmm, I'm fairly certain this means it couldn't find the file. I recognize the error.

**Comment by Xaeroxe** [comment]
@minecrawler If this is still an issue for you can you provide
- Output of the program when environment variable RUST_BACKTRACE is set to 1
- A zip file of your project so we can potentially identify any file path problems

**Comment by Xaeroxe** [comment]
Oh wait a minute, I see the problem.  `DisplayConfig` only has the fields for your `display` section.  That code is expecting a file that looks like this:

```
(
    title: "",
    brightness: 1,
    fullscreen: false,
    dimensions: (1280, 800),
    min_dimensions: None,
    max_dimensions: None,
    vsync: false,
    multisampling: 16,
    visibility: true,
)
```

**Comment by minecrawler** [comment]
Tried to change the file, however still the same panic

**Comment by Xaeroxe** [comment]
@minecrawler Can you provide us a zip of your project?  It's difficult for me to troubleshoot at this point.  If you're unable to provide these exact files can you send us a zip with a basic project structure that can reproduce this?

**Comment by minecrawler** [comment]
![Screenshot of Error](https://i.imgur.com/6eBnsNn.png)

[Repository](https://github.com/minecrawler/ron-debug). Please don't forget to copy the resource folder to the target directory.

**Comment by torkleyy** [comment]
This is the line: https://github.com/ron-rs/ron/blob/master/src/de/mod.rs#L88

`Deserializer::deserialize_any` has no implementation. Serde states that not all formats have to implement it.

**Comment by torkleyy** [comment]
> Please don't forget to copy the resource folder to the target directory.

Why would you need to copy the folder? Just use `cargo run`.

**Comment by torkleyy** [comment]
Figured it out: The key `brightness` does not have a respective field in the `Config` struct. Thus, Serde reads the key, notices it cannot use it, and because of that, calls `deserialize_ignored_any`, which is forwarded to `deserialize_any` [right here](https://github.com/ron-rs/ron/blob/master/src/de/mod.rs#L382).

**Comment by torkleyy** [comment]
Increasing priority, this is a confusing error message. I suspect that RON has to implement `deserialize_ignored_any`.

**Comment by Xaeroxe** [comment]
This is being fixed in Ron, so I'm closing this issue.
