### ISSUE TITLE
Amethyst on OpenCollective?

### ISSUE THREAD

**Issue by erlend-sh** [amethyst/amethyst#333]
@ebkalderon & co, any chance we'll be seeing Amethyst on [OpenCollective](https://opencollective.com/)? Mixing open source and money isn't without its pitfalls, but OpenCollective is designed to make that easier, and there's no shortage of [opportunities for spending](https://medium.com/open-collective/has-your-open-source-community-raised-money-heres-how-to-spend-it-3e9dd957dad). Strategic spending is a major part of [my job at Discourse](https://blog.discourse.org/2017/02/the-discourse-encouragement-fund/), so I'd be happy to offer advice.

In my experience, one great use of funds in a project such as this is art assets. Good looking demos will do wonders for your pitch. Ideally, you'd even manage to source original assets that could be CC-licensed and shared freely, which is a great PR opportunity.

I can commit to $20/month to kick things off.

**Comment by Xaeroxe** [comment]
I'd prefer to do this once the project is more commercially viable.  We still have several major vacancies that make Amethyst difficult to recommend for a game development project.  At minimum I'd like to get the following done before we consider doing this:

- [ ] Animation system, both 2D and 3D
- [ ] Physics system
- [ ] 2D sprite rendering
- [ ] UI framework

Right now funding poses a real risk to the quality of the project in my opinion, as it permits people who are neither commercial users or contributors to have significant sway in the project.

**Comment by Xaeroxe** [comment]
Alternatively: We could start this early, but I would prefer an absolute policy in "standing our ground".  We will not make decisions regarding the direction of the project in order to meet the whims of a financial contributor.  "I'll pull my funding if you don't do it my way" should always be met with stoic resolve to not compromise the quality of the project in the name of appeasing financial contributors.  We've made it this far on $0/month and we shouldn't risk our long term goals to meet short term needs.

**Comment by Xaeroxe** [comment]
@amethyst/engine-devs I think we're presented with 3 options here:

- Defer until the checklist is complete
- Start now, with no expectations for large amounts of funding at this point in time.
- Don't do this at all.

I think I prefer to start now.  Ultimately this decision really rests with @ebkalderon.

**Comment by ebkalderon** [comment]
I don't mind doing this at all, I welcome it! However, I agree that it might be too early to start with this now. My personal list of required features is, at minimum:

- [ ] Rudimentary UI support
- [ ] Text rendering
- [ ] Better tooling

Other features like physics and intuitive animation are both a huge deal, but ultimately not deal-breakers to all games. See simple games like pong, snake, breakout, etc. But being unable to render a simple menu screen or high score table, or lacking any form of artist or gamedev tools support is definitely a showstopper.

**Comment by erlend-sh** [comment]
Sounds good! I'll revisit this in a few months or so. Also..

> Other features like physics and intuitive animation are both a huge deal, but ultimately not deal-breakers to all games. See simple games like pong, snake, breakout, etc. But being unable to render a simple menu screen or high score table, or lacking any form of artist or gamedev tools support is definitely a showstopper.

💯 👏

**Comment by erlend-sh** [comment]
I'd like to revisit this. Other Rust gamedev projects are already having good results on Patreon:

- https://www.patreon.com/sebcrozet/overview
- https://www.patreon.com/tomaka/overview
- https://www.patreon.com/citybound/overview

...and judging by Amethyst's steady influx of GitHub stars and inquiries on Gitter, lots of people continue to be excited about the great work you all are doing.

> Right now funding poses a real risk to the quality of the project in my opinion, as it permits people who are neither commercial users or code contributors to have significant sway in the project.

This is a legit concern but bear in mind it's entirely up to you to decide *when* you start spending any money and on what. I think a great use of the funds would be Ludum Dare-esque contests for small game demos and assets.

It is exactly because Amethyst is still intensely focused on code development that I'm unable to contribute with my own skillsets, such as community building and marketing. In the meantime I'd love to have a way to show my continued support for Amethyst. It's not about buying any kind of deciding power, and you can make that abundantly clear in your copy.

I still recommend OpenCollective over Patreon though, since it's built specifically for open source teams and they are themselves an open source project.

**Comment by torkleyy** [comment]
> I think a great use of the funds would be Ludum Dare-esque contests for small game demos and assets.

That's actually I good idea. I'm strictly against paying people for contributions to this project, I think that simply doesn't work well for community projects, but a game jam could be a nice way to get nice example games and attention.

**Comment by jojolepro** [comment]
We could accept donations, and use that to put bounties on the hardest features that nobody wants to work on. As said previously, game jams could be nice. If you can do them remotely though (like ludum dare), the cost would actually be minimal (if any?). I personally think amethyst is coming to a point where it is near ready for 2d games. The most important features that we are missing is simply "good graphics". Particle systems, effects, trails, etc...

**Comment by jojolepro** [comment]
Getting free assets for prototyping is as easy as getting paid ones though.

**Comment by erlend-sh** [comment]
Since it's looking very likely that Amethyst will soon have a Discourse forum, this seems timely:

https://blog.patreon.com/patreon-discourse-integration-mcrider

**Comment by erlend-sh** [comment]
Done.

https://www.amethyst.rs/blog/non-profit-announce/
https://opencollective.com/amethyst
