### ISSUE TITLE
Update the Transform System

### ISSUE THREAD

**Issue by Aceeri** [amethyst/amethyst#336]
I wrote the transform system when specs was still a relatively newer ecs and ended up taking a lot of ideas from that and implementing most of them into specs in a more performant/space efficient way. Now that those components are in specs, it would be better to rewrite the transform system in that style.

- [ ] Replace boolean flags with `FlaggedStorage`
- [ ] Use bitset joining instead of an `Init` component.
- [ ] Rename `Child` back to `Parent`? (I was indifferent when I wrote it, but I feel that `Parent` is a better identifier since the entity is contains is the "parent" entity)

There are probably going to be some annoying collisions with how the old transform system worked when trying to port it over, so this might take longer than expected.

**Comment by torkleyy** [comment]
As a remainder, it would be great if we could add the transform stuff as an example to Specs once we implemented it.

**Comment by Xaeroxe** [comment]
Hey while we're at it can we also address https://github.com/amethyst/amethyst/issues/236 ?

**Comment by Aceeri** [comment]
@Xaeroxe Wheres the issue with it right now? I'm pretty sure I only used primitive types for the `Transform` and such?

**Comment by Xaeroxe** [comment]
@Aceeri It's just some nice wrapping so it's easier to talk between different math libraries and crates.  It also provides labels for things like x and y, which we don't have currently with [f32; 3] types.

**Comment by Xaeroxe** [comment]
mint is supposed to be a very neutral and un-opinionated crate, which is what we need right now.
