### ISSUE TITLE
Review / Merge flow

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#350]
Even though I won't be the most active user for the next weeks, I'd like to introduce a more quality-oriented merging policy.

We are through a phase of very heavy development in all modules of the engine. These months were full of weeks with no PR merged and others with many PRs at once. Also, the size of the Pull Requests was very big, which made thorough reviews almost impossible. Now that all those rewrites have been merged, I'd like to concentrate more on the quality of the PRs than just getting things merged.

Here would be my proposal for "the common case":

* Pull Requests shall not be merged before at least 24 hours have passed.
* Pull Requests shall be approved by at least two members (two approvals from contributors can count as one member approval.)
* Merging a PR shall be done with `bors r+`
* If a member self-requested a review, the PR shall not be merged until they reviewed the PR (exception: the member becomes inactive)

Note: The author of a PR cannot approve their own PR.

### Urgent fixes

* If something went wrong (like a broken version has been released, the website doesn't work at all, ..) no approval is required for merging
* Merging can be performed instant (but still with bors)

### Grammar fixes, style improvements, ..

* Same here, no approval is required for merging
* There is no reason to wait 24 hours here

### Documentation, tests, benchmarks

* Unless it's a major rewrite in our testing / benchmarking architecture, one review is sufficient.
* Please still wait one day before merging the PR

### Experimental branches

* If there are very experimental branches, there's no need to use bors; in fact, CI may even fail if that makes working on it easier.
* A review would be good prior to merging, but rules don't need to be strict here

### Architecture changes, API which influences the workflow / general design of the engine

* Should be labeled with `type: RFC`
* Needs at least three approvals by members only
* Should be left open for reviews for a couple of days

**UPDATE:** Add last section, clarification.
**UPDATE:** Add point about self-requests.
**UPDATE** Change regular contributors to two contributors

**Comment by torkleyy** [comment]
Btw, here's one example of why bors makes sense: https://github.com/slide-rs/specs/pull/262#issuecomment-329195908

**Comment by Xaeroxe** [comment]
Quick clarification: if the author of the PR is also a member do they then need 2 **other** members to approve the PR, or can they count as one of the 2?

**Comment by torkleyy** [comment]
Yes, they do need, since you cannot approve your own PR.

**Comment by Xaeroxe** [comment]
Now that I'm not so sure about.  Activity levels in our organization vary but we usually have at least two members active, 3 could cause significant delays in merging.

**Comment by torkleyy** [comment]
This 1) assumes that only members are PR authors and 2) reducing the number would not change the status quo, since PRs are already approved by one member and merged afterwards.

**Comment by torkleyy** [comment]
I mean it also says that we should at least wait a day, which I honestly don't think is a problem. We have been merging PRs very fast in the last weeks. I think we should be a little more conservative in the future.

**Comment by Xaeroxe** [comment]
https://github.com/amethyst/amethyst/graphs/contributors?from=2017-06-06&to=2017-09-13&type=c

In the past 3 months the overwhelming majority of contributions to the engine have been made by 3 users all of which are members.  We're effectively requiring all active org members to sign off on a PR prior to merging if the PR was authored by an org member.  Not to mention a lot of these PRs could be to systems and portions of the software a particular org member might not have a strong opinion on.  I'd strongly advocate for reducing the amount of required reviews if the PR was submitted by an org member.

**Comment by torkleyy** [comment]
I think @Aceeri asked for more time to review PRs lately; if we wait longer, there sure are people to review the PR, like @Aceeri, like @ebkalderon, like me.

**Comment by torkleyy** [comment]
@Xaeroxe But the current merging happens to fast. If we reduce the number of required approvals, there's no need to agree on such a number.

**Comment by Xaeroxe** [comment]
I'm content with the 24 hour delay in merging, I just don't want it to get to the point of waiting a week or so for some org member to provide feedback.

**Comment by torkleyy** [comment]
Btw, the last three months are not representative for the next three month; we have been working on very big changes and mostly told contributors to wait for some rewrite. Now in the past weeks we got @omni-viral, @Rhuagh, @derekdreery (back), @jojolepro and possibly others. Not to mention @ebkalderon and @LucioFranco are back.

**Comment by Xaeroxe** [comment]
This is true.  So I suppose if we can maintain those numbers this is fine, however I'd like us to keep an open mind to reducing it if we end up with excessive delays in merging.

**Comment by torkleyy** [comment]
There'll always be two members to review; maybe I won't be able to do it one the same day the PR has been created, but I'm very sure I can do it on the next day. And then there's @Aceeri and you and @omni-viral (very active). Also don't forget those new contributors can easily become members in the future.

**Comment by torkleyy** [comment]
Sure. We could just check how well this works in let's say two weeks and revert this if it doesn't work out.

**Comment by derekdreery** [comment]
I never mind if a PR takes a while to merge. I'd rather it's been checked :)

**Comment by jojolepro** [comment]
I'm for that change too. If not enough reviewers are available to review a pr from a member, we could use 2 contributor approval to count as one review?

**Comment by Xaeroxe** [comment]
Review is good, but progress is essential, especially because our engine isn't even commercially viable yet.  I'm of the opinion that an implementation with a few problems is better than no implementation at all.  I might be slightly more opinionated on this than usual because I just spent 6 months getting a 4 line function into the standard library only to have it reverted because it broke downstream code.  That was infuriating and I actually decided I'm not going to be doing anymore contributions to rust-lang/rust because of that.  Rapid iteration is preferable to getting bogged down.  I'm not opposed to my code being reviewed, but it is very important it does not impede us getting the job done.

**Comment by Xaeroxe** [comment]
@jojolepro I believe a regular contributor's review is considered equivalent to a member's review under this proposal right @torkleyy?

**Comment by Xaeroxe** [comment]
If we're going to the effort of codifying this it'd also be nice to define "regular"

**Comment by derekdreery** [comment]
"regular" can be a list made by the members.

**Comment by derekdreery** [comment]
ie. you want a small group of people who decide this, rather than use some sort of protocol. It's ok to be a bit of a dictatorship, because you're not stopping anyone from forking the code.

**Comment by torkleyy** [comment]
> we could use 2 contributor approval to count as one review?

Seconded. Now going from that we could just drop the "regular contributor" addition (and add a few more members in the near future).

**Comment by Xaeroxe** [comment]
:+1:

**Comment by jojolepro** [comment]
:+1:

**Comment by Xaeroxe** [comment]
I'd like to start moving this towards official policy so here's a @amethyst/engine-devs checkoff list for approving this.  Check the box next to your name if you approve.
In alphabetical order:
- [ ] @kvark 
- [ ] @ebkalderon 
- [ ] @nchashch 
- [ ] @omni-viral 
- [ ] @Aceeri 
- [ ] @LucioFranco 
- [x] @Xaeroxe
- [x] @torkleyy 

If we can get 6/8 members to approve this (with @ebkalderon being given veto power of course) then we should move forward with it.

**Comment by Aceeri** [comment]
> In the past 3 months the overwhelming majority of contributions to the engine have been made by 3 users all of which are members.

Most of my work in the past few months has been on other repos than /amethyst/amethyst, so I'm not sure that is very accurate.

**Comment by Xaeroxe** [comment]
@Aceeri I apologize, I didn't mean to diminish the value of work done outside the main repository.

**Comment by Aceeri** [comment]
@Xaeroxe Just saying that there are likely going to be enough people to review PRs.

**Comment by Xaeroxe** [comment]
@LucioFranco @nchashch @ebkalderon Mind hitting your checkbox up there or voicing your objections if you have any?

**Comment by Xaeroxe** [comment]
6/8 have approved, so let's move this to official policy.  Next step is to update CONTRIBUTING.md
