### ISSUE TITLE
Renderer components should share underlying asset data

### ISSUE THREAD

**Issue by Xaeroxe** [amethyst/amethyst#351]
Currently if you clone a `MaterialComponent`, `MeshComponent`, or `TextureComponent` it will clone the underlying asset data too.  This should be avoided, as sharing that asset data gives us a lot of potential for saving memory.  The easiest way to do this would be to make these Component types use an `Arc` internally instead of the underlying amethyst_renderer type.

cc @ebkalderon @torkleyy @omni-viral @jojolepro

**Comment by omni-viral** [comment]
`Asset` trait is designed to share internaly if sharing is viable.
`Mesh` and `Texture` already share real data with clones.

**Comment by Xaeroxe** [comment]
Oh they do?  Excellent my bad.  What about Material?

**Comment by omni-viral** [comment]
@Xaeroxe material is just a few textures. Clone it is like cloning few pointers.

**Comment by jojolepro** [comment]
Thanks for the precision! :)
