### ISSUE TITLE
Keeping change log up to date

### ISSUE THREAD

**Issue by ebkalderon** [amethyst/amethyst#36]
I believe that in [CONTRIBUTING.md](https://github.com/amethyst/amethyst/blob/master/CONTRIBUTING.md), we should add under **Pull Requests** some conditions that make sure people's pull requests also update [CHANGELOG.md](https://github.com/amethyst/amethyst/blob/master/CHANGELOG.md) to some degree so it doesn't have to be done manually.

What those conditions should be is up for discussion. Personally, I believe that we should look towards Semantic Versioning for ideas: if you fix a known bug, introduce new functionality, overhaul an existing feature, or produce a breaking change, you should document it appropriately in the change log.

See issue #17 from a while back for more information about the CHANGELOG.md format we use.

**Comment by White-Oak** [comment]
Just an oppinion, but I believe this should be done by a mantainer, not by pull requesters. Interesting to see, what others think.

**Comment by ebkalderon** [comment]
@White-Oak I can see what you mean, just wanted to share an idea I've had floating around. I am curious, is there any kind of standard as to how maintainers should handle change log updates? Is it updated ad-hoc or done all at once?

**Comment by White-Oak** [comment]
@ebkalderon I know rustc team puts a tag like 'changelog-notes' and uses that for a next release.

**Comment by ebkalderon** [comment]
I think this should remain the responsibility of the maintainer, since a stable change log should be part of a stable release schedule. We need to codify this on the wiki or in the CONTRIBUTING.md file, along with the branching model detailed in #27. Closing for now.
