### ISSUE TITLE
The amethyst CLI tool seems to be out of date with the libraries.

### ISSUE THREAD

**Issue by golddranks** [amethyst/amethyst#362]
I tried to create a new project using the command line tool, but the created project wouldn't build.

Here's a gist of the log: https://gist.github.com/golddranks/46cd34b3717fbff57007e8cf13ad9a0d

**Comment by jojolepro** [comment]
The amethyst command line tool is currently broken. I suggest you create a normal bin project using cargo, and add amethyst as a dependency.

**Comment by torkleyy** [comment]
This should be fixed soon. I'll assign myself and do it for the 0.6 release.

**Comment by Xaeroxe** [comment]
Fixed with latest release of the cli.
