### ISSUE TITLE
Improve mesh asset loading.

### ISSUE THREAD

**Issue by omni-viral** [amethyst/amethyst#363]
Right now meshes can have different vertex formats. But only mesh with `PosNormTex` vertices can be loaded as asset. One time user may want to ignore normal vectors even they are specified in file. Another time user wants tangent vectors to use physically based materials. Tangent vector may be read from file or calculated.

**Comment by Xaeroxe** [comment]
I doubled up project labels on this as I imagine we'd want this issue to show up in both search for assets and rendering.

**Comment by omni-viral** [comment]
This is mostly about assets. Currently render can use anything that is `Component + AsRef<Mesh>` for meshes, `Component + AsRef<Material>` for materials and so forth.

**Comment by omni-viral** [comment]
We need to decide if we want to support multiple vertex formats in one game or not.

**Comment by Xaeroxe** [comment]
I think the answer is probably yes.  Companies have outsourced art studios all the time that might submit assets with a different vertex format than the rest of their art team, so being able to mix is good.

**Comment by omni-viral** [comment]
Then the question is how we gonna do this. Either user puts mesh drawing pass for each vertex format he want to use. Or we make drawing pass working with multiple formats. But complexity for passes will increase drastically

**Comment by torkleyy** [comment]
Sorry if this comment is missing something obvious, but why not just make the `Data` of mesh assets an enum or some other more flexible type?

**Comment by omni-viral** [comment]
@torkleyy thatbwas what I thinking except sometimes you may want to convert `PosNormTex` into `PosNormTangTex`

**Comment by torkleyy** [comment]
Yep, then let's just add a method to the enum ;)

**Comment by omni-viral** [comment]
When you load `Mesh` you don't work with vertex sequence. It is passed from `Format` to `Context` directly

**Comment by torkleyy** [comment]
I'm not sure I can follow. If the `Mesh` (which, already, is a limited type) needs tangents, they should be calculated. If not, they should not.

**Comment by omni-viral** [comment]
`Mesh` doesn't care.
`Pass` do

**Comment by torkleyy** [comment]
@omni-viral If we could ask for these capabilities, where'd that be?

**Comment by omni-viral** [comment]
It has to be additional parameter for `Loader::load` method which will be propagated to the `Context::create_asset`.

**Comment by Rhuagh** [comment]
Or type parameter on the Format or some other construct?

**Comment by torkleyy** [comment]
So we do now have

* `Format::Data` to pass additional requests to the format
* We do support different attribute combinations and #417 even improves that further

So I'd consider this issue fixed.

**Comment by Rhuagh** [comment]
Yes, by using options we can control what attributes are loaded, we just need to add the support to our formats I guess

**Comment by Rhuagh** [comment]
This is fixed for the most part, we could discuss if we want to add options to the wavefront loader.
