### ISSUE TITLE
Stabilize rustfmt version

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/amethyst#367]
For the readability of our codebase, I suggest we stabilize onto one version of rustfmt. Also possibly look into either enforcing that PR's are rustfmt or have travis rustfmt our code for us.

**Comment by Xaeroxe** [comment]
One possible approach: Code a bot to run on a Google Apps micro instance for free that executes once every other day, the bot clones the codebase, runs rustfmt on it, and if it finds any changes opens up a PR with those changes.

**Comment by Xaeroxe** [comment]
This way we get a formatted code base without harassing contributors about formatting.

**Comment by torkleyy** [comment]
It would be great if bors could do formatting on merge, eventually.

**Comment by torkleyy** [comment]
As for formatting standards, we could easily ensure that by adding the current defaults to our `rustfmt.toml`, so if they're changed in a newer version of rustfmt, we still have the same formatting result but everyone can use the version they like.

**Comment by Xaeroxe** [comment]
rustfmt is going to be shipped in rustup with the next rustc release, so this is going to be a significantly simpler problem in the future.  There may be occasional minor formatting differences between users of the nightly compiler vs users of the stable compiler, but I don't see this as such an urgent imperative once rustc 1.24 hits stable.

So I'm planning on closing this issue once 1.24 hits stable.  Let me know if you disagree with this decision.
