### ISSUE TITLE
Audio playback delayed and slowed

### ISSUE THREAD

**Issue by Xaeroxe** [amethyst/amethyst#376]
Multiple users have reported that audio playback is either delayed, slowed, or even both.  The only cause I can think of for this is that the Decoder isn't operating fast enough, so in order to make it operate faster I'd like to move decoding into a dedicated thread so that way we can execute `Decoder::next` more frequently than the rate at which samples are requested by the audio backend.  I have higher priorities at the moment so I'm writing this issue to make sure I come back and do this at some point.

**Comment by omni-viral** [comment]
I'd recommend to utilize rayon for this purpose. And possibly `futures::Stream`

**Comment by Xaeroxe** [comment]
Rodio is already doing this internally.  I'm not really sure what to do because I can't improve the situation over what rodio already does.  So I guess I'll close this.

If you're experiencing audio distortion you might be just experiencing it as a symptom of significantly degraded system performance.  If the computer can't decode fast enough the audio will start to distort.

**Comment by omni-viral** [comment]
I guess modern laptop should have
> significantly degraded system performance

in pong example

**Comment by jojolepro** [comment]
I run at 1400 fps, which causes thread starvation on the audio thread. I'm using a laptop. I'm not sure what you mean here @omni-viral

**Comment by omni-viral** [comment]
I mean that if you run at 1400fps you can expect that audio won't lag

**Comment by Xaeroxe** [comment]
Audio decoding happens completely independently of amethyst. We have an audio engine that we get from an upstream crate that we just send commands to. So if our systems consume all of the processing power there isn't any processing power left for the upstream audio engine.  I have absolutely no idea what any of you expect me to do about this.

rodio doesn't expose the information on how much audio is decoded because it takes the responsibility for decoding itself.  I build a `rodio::Decoder` and pass it to rodio, which then consumes it and I never see it again.  Honestly at this point I think we're just inventing problems with it, we've already determined this only occurs when the system is at 100% CPU usage and I've literally never seen a game function properly on a computer with 100% CPU usage.  If someone wants to make a PR to decode whenever or however you feel like that's fine just keep in mind rodio already does buffered decoding at its own pace automatically for you.  It's not coupled to the frame rate, but it's there and it works.  If someone can find a problem with that architecture I'll consider fixing it, but executing slowly on a system with 100% CPU usage is not a problem with the audio setup.

**Comment by anderejd** [comment]
Hi All! I'm usually just lurking here and have not contributed anything important, but I plan to! Later ;)

I do have two ideas about this: 

1. Make sure at least one hardware thread is dedicated to sound (and that the rest of the engine does not use more than the number of HW threads - 1)
2.  Play around with thread priority and see if it makes a difference

I hope to allocate some time to dive in and contribute, but this is not the time. :)

**Comment by Xaeroxe** [comment]
We already have a dedicated thread for audio output and a dedicated thread for audio decoding as part of rodio itself.  We've discussed the thread priority idea and have turned it down because priorities can cause starvation on a majority of systems.

See: https://blog.codinghorror.com/thread-priorities-are-evil/

http://vanillajava.blogspot.se/2011/09/why-thread-priority-rarely-matters.html?m=1

**Comment by torkleyy** [comment]
Hi @anderejd!

> Make sure at least one hardware thread is dedicated to sound (and that the rest of the engine does not use more than the number of HW threads - 1)

We don't have much control about how audio thread is executed, but it's already done in another thread.

Just seeing @Xaeroxe was faster..

I added a comment on #384, maybe that could solve the problem.

**Comment by anderejd** [comment]
@Xaeroxe @torkleyy Sounds good, how about limiting the number of threads used by the rest of the engine? Even if using frame rate limiting some systems with a heavy enough game will be using all available threads all the time and perhaps starving the sound system again, right?

**Comment by torkleyy** [comment]
@anderejd The plan is that while the main thread is sleeping (at which point, no system is executing), the audio system can do all the work it couldn't do while systems were running. The problem right now is not that systems are too heavy, but they're executed just too often.

**Comment by anderejd** [comment]
> The problem right now is not that systems are too heavy, but they're executed just too often.
@torkleyy Solving the problem at hand sounds like a good idea 👍

**Comment by Xaeroxe** [comment]
Because I'm not interested in having an open close battle on this issue @omni-viral can you please close this if you have nothing further to say?

**Comment by Xaeroxe** [comment]
@jojolepro

> Well, it ended up I was mostly wrong. The only way to degrade sound performance after using the fps cap was to literally bring the game down to one fps using 8 Systems with for loops of 1 billion doing nothing, and it still ended up with an ok quality, because the dispatchers can't fit everything perfectly, and the audio eats the free space that's left (that's my guess at least).

So I'm closing this.

**Comment by omni-viral** [comment]
@Xaeroxe you could at least wait for me after asking to close it 😸 
Since yielding in #384 should fix it I have no objections to close this issue.
