### ISSUE TITLE
Amethyst executing at 1400 FPS and eating all the CPU

### ISSUE THREAD

**Issue by Xaeroxe** [amethyst/amethyst#383]
@jojolepro 's profiler indicated the pong example was running at 1400 FPS causing amethyst to consume all of the CPU resources.  We should provide some kind of FPS cap.

**Comment by jojolepro** [comment]
I already knew that, I can use the steam fps counter, or the fps counter I added to amethyst.
To cap the fps, a while(true) checking the time in a single thread environment (outside of the dispatcher) could do the job easily.

**Comment by Rhuagh** [comment]
Don't do while(true), that will use up one thread all the time. Use yield or something like it instead.

**Comment by jojolepro** [comment]
I read somewhere a while ago that using any kind of pause will result in imprecision, because the os will lower the thread priority while its in pause, and will check less often if it should unpause it.

**Comment by Rhuagh** [comment]
For processes yes, this is for threads. Yield will "give the cpu" to other threads in the same process.

**Comment by Rhuagh** [comment]
Yield is basically a way to say "someone else can go now, but if noone else with the same or higher priority wanna go I'll keep going".

**Comment by omni-viral** [comment]
Usually you wait in few steps steps. First you yield to another thread then you yield to another process. If you need to wait for too long - sleep
