### ISSUE TITLE
Pong example losing keyboard events at low fps.

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#408]
Title. There's a lot of PR going around, so I'll wait until those I merge before implementing the input-event system in the pong example.
To reproduce, change the maximum fps to 5 in the frame-limit branch (as of writing this issue)

**Comment by jojolepro** [comment]
Not useful for a simple use case like pong, so closing. If it was a shooter where you absolutely don't want to miss a user input, then that would be useful to implement.

**Comment by torkleyy** [comment]
The question is still why this happens, isn't it?

**Comment by Xaeroxe** [comment]
As the frame occurs events collect from the window, these events will be processed and sent into a shrev::EventChannel at the beginning of every frame.  This EventChannel has a maximum size of 200 events, so if you leave it to collect events for too long it will eventually overflow.  That's what's happening here.
