### ISSUE TITLE
Google Summer of Code?

### ISSUE THREAD

**Issue by termhn** [amethyst/amethyst#412]
Hello all,
So... I'm sure most of you have heard of/know what the GSoC is, but if not: https://developers.google.com/open-source/gsoc/

Has anyone thought at all about applying Amethyst for a mentorship/organization position? I'm thinking about applying as a student and working on something for Amethyst would be an awesome position, plus I think this is just a really cool project and could be cool to have for GSoC if anyone is feeling up to mentor someone.

Applications aren't until January for orgs and March for students, but thought I'd put this here to see if anyone is even interested.

**Comment by Xaeroxe** [comment]
Our ability to do this depends on

- Having adequate projects for students to take on
- Having sufficient volunteers for mentors.

GSoC advises that most projects will have under 3 students in their first year, and they also advise to have 2 mentors available per student.  So at minimum we'll need 2 mentor volunteers, preferably 4.  I offer myself as the first mentor volunteer.

Google offers the following advice on good project ideas:


>There are many ways to define a good GSoC project–probably as many ways as there are student-mentor pairings. Here are just a few:

>Low-hanging fruit: These projects require minimal familiarity with the codebase and basic technical knowledge. They are relatively short, with clear goals.

> Risky/Exploratory: These projects push the scope boundaries of your development effort. They might require expertise in an area not covered by your current development team. They might take advantage of a new technology. There is a reasonable chance that the project might be less successful, but the potential rewards make it worth the attempt.

>Fun/Peripheral: These projects might not be related to the current core development focus, but create new innovations and new perspective for your project.

>Core development: These projects derive from the ongoing work from the core of your development team. The list of features and bugs is never-ending, and help is always welcome.

>Infrastructure/Automation: These projects are the code that your organization uses to get its development work done; for example, projects that improve the automation of releases, regression tests and automated builds. This is a category in which a GSoC student can be really helpful, doing work that the development team has been putting off while they focus on core development.

>The project you propose will define the tone and scope of your organization’s participation in GSoC. It is a key part of your organization’s application. Further, it may be the first impression made on a potential student applicant.

>Pro Tip: Maintain an “ideas page” with a running list of entry projects year-round. This can benefit your development effort throughout the year. It can also make your organization’s GSoC application easier to put together the following summer.

>Don’t Be That Guy: Don’t propose projects that neither you nor anyone else wants to mentor.


Some project ideas for Amethyst:
- Scripting API: https://github.com/amethyst/amethyst/issues/271 This one fits into "Risky/Exploratory"
- Create a bot/travis setup that can automatically generate documentation for new pull requests and post links to the generated documentation
- More complex examples: Our examples do a pretty good job of showing off Amethyst's features but we could have much better looking examples.  Something demonstrating a first person or third person scene would be great.  (Note: A third person example may be dependent on completing the animation system prior to January)

**Comment by Aceeri** [comment]
I think the clearest project might be better examples or just usage of the engine. If we do go through with this then I'm definitely willing volunteer as a mentor.

**Comment by termhn** [comment]
I definitely think better/more complete examples that really show off what it can do would be great to have--just being able to have some cool screenshots to show off would be cool and then allow people to dig into how that's done if they're interested. I think this is an area that many open source projects, especially graphics-related ones, miss the mark on personally.

**Comment by Xaeroxe** [comment]
So while we can technically do this with two volunteers I'd prefer to hold out for 4 as I'm guessing we'll likely have at least two student applicants.

**Comment by torkleyy** [comment]
So are there any special requirements other than to have mentors available?

**Comment by Xaeroxe** [comment]
I mean we have to get through an application process ourselves, but my
impression is they're not really picky.

**Comment by Luke-Nukem** [comment]
I recently completed [2017 GSoC for Gnome GJS[(https://luke-nukem.gitlab.io/gsoc-2017.html). It's looking like next year I'll be taking a few more papers, and thus will still be a student.

I would *love* to work on amethyst if you get in.

**Comment by zacnomore** [comment]
This would need to get moving pretty immediately if it's going to happen. The deadline is [January 23, 2018 at 12:00 (EST)](https://summerofcode.withgoogle.com/get-started/) so just about 2 weeks from now.

**Comment by termhn** [comment]
I’d still be very down/excited to do this as a student. 😊

**Comment by Xaeroxe** [comment]
Unfortunately developer resources are already pretty thin and we're scant for volunteer mentors, so I don't believe we'll be able to participate in the GsoC.  My apologies go out to those excited to work with amethyst.

Even if we get more mentors it seems too late to put together projects and an application, so I'm going to close this.

**Comment by termhn** [comment]
Darn! Disappointing but understandable. Maybe next year!

**Comment by torkleyy** [comment]
Hopefully, yes! I'm pretty sure I'll have more time next year and I intend to prepare some tasks and material then.

**Comment by Rhuagh** [comment]
Feel free to contribute anyway ;)

**Comment by termhn** [comment]
That I certainly will do.. when I find the time ;p
