### ISSUE TITLE
Rendering optimization notes

### ISSUE THREAD

**Issue by omni-viral** [amethyst/amethyst#428]
Here we may put our notes and ideas about rendering optimizations.
I'll start with a few.

- [ ] Cache constant buffers. Don't update if not modified.
  With help of slide-rs/specs#291.
- [ ] Use indexed meshes to reuse vertices.
- [ ] Move to `gfx_hal`
- [ ] Mark static geometry.
  - [ ] Batch it. Reuse secondary command buffers. Optimize static lighting.
- [ ] Discard meshes that falls out of cameras frustum. Mesh is required to have known AABB.
  - [ ] `collision-rs` can help to optimize it further.

**Comment by Rhuagh** [comment]
I would do frustum culling in user space, and make it possible to use a marker component for visibility

**Comment by Rhuagh** [comment]
```
pub struct Visible;

impl Component for Visible {
    type Storage = NullStorage<Visible>;
}
```

and use that in the join in the passes.

**Comment by Rhuagh** [comment]
Or maybe the opposite would be better, NotVisible and !NotVisible in Join, that way those that don't care about frustum culling don't need to do anything.

**Comment by omni-viral** [comment]
@Rhuagh Isn't it would be nicer to do visibility query in renderer? Consider multicamera setup

**Comment by Rhuagh** [comment]
It's a fairly expensive procedure, and something that I consider optional.

**Comment by Rhuagh** [comment]
If you have 8 meshes in total, you're gonna lose performance by doing it.

**Comment by omni-viral** [comment]
I agree on that should be optional.
But I'm not agree about using marker components for this purpose.
It's better to query visible meshes from `Camera + Transform + SpecialSortedStructure`. Probably with some caching.

**Comment by Rhuagh** [comment]
I don't agree. 

With user space culling we allow the user to come up with their own culling techniques without having to duplicate our pass code. Some users may need occlusion culling, z-culling, frustum culling, distance culling. I don't think we should add all of those culling techniques to the renderer crate, but provide systems that can do these things externally.

**Comment by Rhuagh** [comment]
And by putting it in user space, we also enable the user to use the visibility data for their own systems.

**Comment by omni-viral** [comment]
Good point. But still those culling methods results are local to camera.

**Comment by Rhuagh** [comment]
Some are yes, some aren't. Distance culling for instance can be done without the full camera matrix, you only need the position of the camera (or the controller entity, which might be a different entity).

**Comment by omni-viral** [comment]
I mean that for another camera you have another results

**Comment by Rhuagh** [comment]
Sure.

**Comment by omni-viral** [comment]
Maybe we can have `Culled` attached to `Camera`. And in this component will be bitset with bits set to meshes culled by any technique.

**Comment by omni-viral** [comment]
If nobody fills `Culled` for specific `Camera` then renderer will render all meshes

**Comment by Rhuagh** [comment]
Possibly, I'm not sure what the performance/usability difference would be.

**Comment by Rhuagh** [comment]
But it's not a bad idea.

**Comment by omni-viral** [comment]
Difference with what approach?

**Comment by Rhuagh** [comment]
Using components.

**Comment by Rhuagh** [comment]
That's a good point.

**Comment by Rhuagh** [comment]
I reordered the comment above btw, to reflect what I think is a good order to do the improvements in :)

**Comment by omni-viral** [comment]
I agree with this order. I was writing them in the same order they came in my mind 😄

**Comment by omni-viral** [comment]
@Rhuagh I'll put skinning support in another issue. This one is about optimization.

**Comment by torkleyy** [comment]
Caching should be easy soon:

https://github.com/slide-rs/specs/pull/291

Look at the `tracked` example.

**Comment by fhaynes** [comment]
@omni-viral is any of this still relevant?

**Comment by omni-viral** [comment]
I think that this is out of date
