### ISSUE TITLE
Passes have too much boilerplate

### ISSUE THREAD

**Issue by omni-viral** [amethyst/amethyst#429]
Right now `Pass` implementation defines shaders and serve as simple pipe `World` -> `Encoder`.
The second part (pipe) requires enormous amount of boilerplate to write. Different passes share most of the code. If we add some more sophisticated features like caching buffers problem will grow.
Boilerplate should be reduced to minimum.
I think passes should be written in more declarative manner.

**Comment by Rhuagh** [comment]
Can we look at how gfx-hal handles passes?

**Comment by omni-viral** [comment]
@Rhuagh It's not really related. Our problem in `fn apply` implementation. `Effect` talks with `gfx` to configure pipeline.

**Comment by Rhuagh** [comment]
Ok, I have no idea, just brainstorming :) I like to idea of writing passes declarative.

**Comment by fhaynes** [comment]
Closing this as it hasn't had an update in over a year. Tracking it on the roadmap at https://openproject.amethyst-engine.org/projects/render/work_packages/67/activity
