### ISSUE TITLE
Constrained non-physics based transformation

### ISSUE THREAD

**Issue by Rhuagh** [amethyst/amethyst#434]
I've been thinking over what @minecrawler have been doing with the API to update transformations, and have come to the conclusion that I'd like an abstraction on top of `LocalTransform`, where you can add constraints. I think the `LocalTransform` as it is after @Aceeri's PR is merged is good, it makes it easy to do unconstrained transformation, which is what it should be on that level of abstraction imho.

The basic idea with constraints is that you use them to remove degrees of freedom. So by supplying a new `ConstrainedTransform` (name copyright pending), we can (hopefully) fulfill everyones hopes and dreams of a nice API for doing constrained transformation. This would be the place to put the API for doing movement along 2 axis, and "ignore" one axis, i.e you want to constrain movement to those 2 axes.

This would also mean that for those using a real physics engine, they can work with only `LocalTransform` and `Transform`, and don't have to muck around with constraints in multiple places.

I don't have any concrete code examples at this point, just thought I'd get feedback on the idea.

**Comment by minecrawler** [comment]
What kind of constraints do you want? You mentioned reducing the number of axis (which can be useful in many situations), but what about the degree of transformation? For example limiting a local system to rotate no more than plus-minus 90 degree (maybe for CCTV camera in a game)? What about speed (clip vector length of movement of a single frame to a certain value)? Can that system be extended to doing transitions? For example you have a constrained transformation which only lets you advance .03 units per frame, but a user wants to advance 30 units (with ease-in-out effect)?

As for code, wouldn't a `ConstrainedTransform` just be a wrapper over `LocalTransform` with checks if a passed value is within the given limits?

```rust
impl ConstrainedTransform {
    // taken from my code and modified
    pub fn move_local_constrained(&mut self, axis: Vector3<f32>, amount: f32) -> &mut Self {
        let a = if amount > self.constrained_move_amount {
            self.constrained_move_amount
        } else { amount };
        self.move_local(axis, a)
    }

    // ...
}
```

**Comment by Rhuagh** [comment]
That's the basic idea, yeah. You should be able to constrain both orientation change and position change. Transitions I haven't really though about yet.

**Comment by Rhuagh** [comment]
Transitions are more of an animation thing I think.

**Comment by minecrawler** [comment]
> Transitions are more of an animation thing I think.

true. Let's leave it out of this discussion.

**Comment by Xaeroxe** [comment]
If the constraint doesn't exist in the physics system how would such a constraint be enforced?  Does the physics system not need to take such constraints into account?

**Comment by minecrawler** [comment]
Can't we correct the physics system in that case?

**Comment by Rhuagh** [comment]
If you have a physics engine most of these constraints will be handled there.

**Comment by Rhuagh** [comment]
With physics you'll use forces to request transformation changes, and the physics system will do the actual movement. The constraints here are needed when you're not following physical rules.

**Comment by Xaeroxe** [comment]
So in the absence of the physics system, how would the constraint be enforced?  Would we just reset the values any time they were out of bounds?  If the engine user has full control over the transform why couldn't they just write code that doesn't move it out of bounds in the first place?

**Comment by Rhuagh** [comment]
This is just a new abstraction you can use of you want constrained transformation, i.e. "rotate max 45 degrees up", " when moving, only move in the xz plane ", the output of this will be LocalTransform with the constraints applied to any change in transformation

**Comment by Rhuagh** [comment]
And for future reference, doing constraints on quaternions is almost impossible, so you'd want a different representation for rotation, or convert it to a different representation for constraining and then convert back to quaternion afterwards

**Comment by bakamomi** [comment]
I wanted to constrain my top-down camera to certain angles and that issue brought me here. So, if you don't mind, I'll chime in.

The idea of implementing additional methods that would check if some new transform is within restrictions doesn't sound so good to me. You either lose some methods that unconstrained transform supports, or would need to implement a lot of duplicates (move_forward/back/etc, pitch/yaw/roll). And if you accidentally use an unconstrained method, your constraints won't apply. So I thought of some other strategies:
But first, here is a couple of caveats that might be introduces by constraints:
- if transform fields are public, somebody might change them bypassing constraints
- if many rotational transforms are applied sequentially, they might flip the entity before constraints are processed in case their procession isn't immediate upon change
1. Add a constraint field to the Transform struct and process them in TransformSystem.
    Pros: caveat 1 doesn't apply
    Cons: constraints won't be applied until the transform system runs (caveat 2), all methods that return non-self, e.g. transform.matrix(), which returns a matrix, must account for constraints manually
2. Add a field and process it in every method that manipulates Transform.
    Pros: caveat 2 doesn't apply
3. Implement a new component and a system (ConstrainedTransformSystem). Fix transformations in the new system.
    Pros: caveat 1 doesn't apply
    Cons: the constraints won't be applied on Transform's fields until the new system runs; this method requires lots of changes everywhere to account for the new system; finally, I'm not sure which system should depend on which:
    Transform->ConstrainedTransform or ConstrainedTransform->Transform?
4. Create a new Transform trait that requires methods like move_global, move_local, rotate_global, rotate_local, and provides methods like  move_forward, yaw_local, roll_global, etc. FreeTransform and ConstrainedTransform would then implement this trait. If an entity has both components, only ConstrainedTransform would be used by TransformSystem.
    Cons: both components would need separate implementations of other traits like CgTransform, which would probably be very similar

I think the second option is the best.
1. We just change Transform to this:
```rust
pub struct Transform {
    rotation: Quaternion<f32>,
    scale: Vector3<f32>,
    translation: Vector3<f32>,
    pub constraints: Option<NewStructForConstraints>,
}
```

2. Add "constraints: None" to default()

3. Add these methods:
```rust
fn rotation(&self) -> &Quaterion<f32> { &self.rotation };
fn scale(&self) -> &Vector3<f32> { &self.scale };
fn translation(&self) -> &Vector3<f32> { &self.translation };
fn with_constraints(&self, constrains) -> self {...};
```

4. Adjust methods that directly change Transform fields, e.g.:
```rust
pub fn move_global(&mut self, translation: Vector3<f32>) -> &mut Self {
    if let Some(constraints) = self.constraints {
        // apply translation with constraints
    } else {
        self.translation += translation;
    }
    self
}
```

Everything else would remain as it is now, aside from those users who address Transform fields directly.

I can implement this if it's acceptable.

**Comment by termhn** [comment]
I think it might be better to make a new component called, say, `ConstrainedTransform`, which would require (build on top of) a regular `Transform` and modify it. You'd basically implement it as just 

`
pub struct ConstrainedTransform {
    pub constraints: Option<NewStructForConstraints>,
}
`

and it would guarantee transforms are constrained as long as you only interact with it and not the underlying `Transform` itself. You'd just reimplement the transform methods as above (maybe refactor those common methods out into a trait, though probably not necessary). This way we don't need to have conditionals in all the methods and only people who want to use it will.

**Comment by Rhuagh** [comment]
I don't think you need to complicate this so much, my idea was to constrain based only on the local transform. Other constraints really don't make much sense, since it will be incredibly hard, not to mention inperformant to rollback transformations going back up a potentially deep hierarchy if a constraint is violated.

**Comment by fhaynes** [comment]
Closing this due to age and lack of progress. If there is demand, we'll add it to the roadmap.
