### ISSUE TITLE
Consider removing `Engine` struct

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#449]
So basically both the delta time and the thread pool can be retrieved from the `World`, so I wonder if we could remove that struct and just pass `World` to the state machine.

**Comment by Xaeroxe** [comment]
Yeah the distinction is becoming pretty meaningless, since in order for our APIs to be useful they have to be accessible from the `World` anyways so you can access them in both Systems and States.

I'm for this proposal.

**Comment by Rhuagh** [comment]
:+1:
