### ISSUE TITLE
Structure to allow usage as a server as well as a client

### ISSUE THREAD

**Issue by moonheart08** [amethyst/amethyst#458]
What it says on the tin. 
Being able to act as a server is very important, and being good at hauling data (which Amethyst seems to be designed for) is a VERY important part of server software.

**Comment by Rhuagh** [comment]
This is planned yes. It will require some thought so we haven't gotten around to it yet. The main solution will probably be to have separate states for server/client. This will require us to be able to create separate system trees per state, which currently is a work in progress.

**Comment by erlend-sh** [comment]
@moonheart08 do you have any good examples of game engines that already do this?

**Comment by minecrawler** [comment]
@erlend-sh with my limited experience I guess that the UE4 also has that kind of structure.

**Comment by moonheart08** [comment]
Well, for one, every MUD in existence, but that's cheating.

1. Isogenic Engine
2. BYOND (But don't use it as an example for how to do it!)
3. DimensioneX Multiplayer Engine

**Comment by Rhuagh** [comment]
Mud is only the server side though

**Comment by LucioFranco** [comment]
Yeah, I believe figuring out a way to run server only code etc is on the roadmap. But I have been quite busy with school and work so I have not had much time to think about it.

**Comment by Xaeroxe** [comment]
I believe our hello world example demonstrates you can run Amethyst without a rendering stack.  I think that's sufficient for "allowing use as a server".  Does anyone else feel there's more that should be done?

**Comment by torkleyy** [comment]
Yep:

* implement networking
* example server
* docs

**Comment by jojolepro** [comment]
Just use different systems,states and resources. See the #532 PR net_client and net_server for example. You can add the rendering and input systems to the client without needing them on the server.

**Comment by jojolepro** [comment]
As this is addressed by the data-oriented nature of the ecs, and is supported by the current implementation of the network PR, I'm closing this issue. Follow the progress in the issue dedicated to networking. #335
