### ISSUE TITLE
Improve errors and error handling

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#460]
So we need

* more error types
* include more information
* allow better handling of them (e.g. improve `amethyst_assets::Progress` stuff)

There are many locations where such improvements can be made, so I'm gonna set this to `easy` and ask for help here. Small PRs are preferred here.

**Comment by torkleyy** [comment]
If there are any questions, I'll gladly assist you!

**Comment by minecrawler** [comment]
What about logging?

**Comment by torkleyy** [comment]
We also need logging, should be a separate issue though.

**Comment by torkleyy** [comment]
I'd suggest to use `error_chain` for this.

**Comment by Rhuagh** [comment]
YES!

**Comment by torkleyy** [comment]
So I'm working on better error handling in the assets crate now.

**Comment by torkleyy** [comment]
I did the hard part in #464 which introduces much better errors for asset handling. What is left are much easier jobs for the other crates:

* `amethyst_gltf`
* `amethyst_renderer`
* `amethyst`

All this crates would benefit from using `error_chain!`.

**Comment by Binero** [comment]
This issue is strongly tied to https://github.com/amethyst/amethyst/issues/301.

**Comment by Aceeri** [comment]
Thoughts on using [`failure`](https://github.com/withoutboats/failure) for this?

**Comment by Binero** [comment]
What are the advantages of said crate? It says it tries to solve a lot of problems `quick-error` and `error-chain` have, but doesn't go into more detail.

**Comment by Hittherhod** [comment]
From listening to a talk about `failure` it seems like `error-chain` encourages things like a single unified error type for a library as well as having a steep learning curve for newcomers (macros given pretty bad error messages if you mess them up).

**Comment by omni-viral** [comment]
@hittherhod. From my experience you easily can define multiple `error_chain`s in crate and establish links between them to use `?`. Or use `chain_err` function to stack up errors for better context of what went bad where you handle errors.

**Comment by Rhuagh** [comment]
I'm in favor of moving to `failure` myself.

**Comment by Binero** [comment]
One major setback in using the failure crate is that it's very hard to maintain type information about the errors you're returning, when there is a series of possible errors. This is especially painful when some error variants are from external libraries, as as far as I know there is no way to implement foreign errors like in error-chain.

Furthermore, much like in error chain, I don't think there is an easy way to chain errors without losing type information.

**Comment by jojolepro** [comment]
for reference https://github.com/rust-lang-nursery/failure

Where do we go from here? failure vs error_chain vs ??

**Comment by OvermindDL1** [comment]
For note:
https://github.com/rust-lang-nursery/failure/issues/181

**Comment by anderejd** [comment]
> Where do we go from here? failure vs error_chain vs ??

It doesn't need to be a library, we can use the standard built-in error handling in rust, using `.map_err` and `From` impls. This is my preference.

**Comment by OvermindDL1** [comment]
Even if Failure is used it is still recommended to make your own error enum and don't use the generic Error as that one is designed only for generic setup and testing, not for actual publication.  The rest of the stuff in Failure is still very useful.

**Comment by distransient** [comment]
Actually, it appears that we should probably wait for the work and effects of RFC 2504 (https://github.com/rust-lang/rust/issues/53487) to settle, since it'll likely effect the api of `Failure` and best path forward generally. Although it's regardless `error-chain` will be deprecated, it'd still make our lives easier to wait just a little longer on changing our Error strategy 😛

**Comment by torkleyy** [comment]
This issue is no longer of value. We have an error strategy by now.
