### ISSUE TITLE
[book] "system requirements" -> "HDD: 17 MiB free disk space" -> MiB ?

### ISSUE THREAD

**Issue by vi** [amethyst/amethyst#467]
https://www.amethyst.rs/book/master/html/getting_started.html

Maybe meant "17 GiB free disk space"? Typical `build` directory of a Rust project is measured in hundreds of megabytes.

**Comment by Xaeroxe** [comment]
That's kind of a silly requirement to list anyways, so we're probably going to remove it.  It's worth noting, Amethyst isn't even close to 17GB.

**Comment by Rhuagh** [comment]
More like 900MiB for a debug build :)

**Comment by vi** [comment]
So it should probably be `1.7 GiB` or `1700 MiB`.

**Comment by vi** [comment]
Is ["Writing a Simple Application"](https://www.amethyst.rs/book/master/html/simple_application.html) section not implemented yet or I miss some link to click?

If the former, it should be mentioned in the text.

**Comment by Xaeroxe** [comment]
@vi Our book is horribly outdated at the moment and quite useless. I'm really sorry about this, you might try looking at our example projects in the repository.  We'll be rewriting the book either shortly before or shortly after our 0.6 release.

**Comment by Rhuagh** [comment]
Sphere -> Renderable -> Pong is the order I would recommend.

**Comment by vi** [comment]
Then put some banner at the top of the book warning users that the book is outsated and rework in progress.

**Comment by Rhuagh** [comment]
You mean like the one on https://www.amethyst.rs/book/master/html/index.html ?

**Comment by vi** [comment]
Yes. The banner is visible only on the index page, but the incompleteness fully kicks in on the "Writing a Simple Application" page. The banner may mention the examples above.

Currently the big "[Learn]" button on https://www.amethyst.rs/ lead to the the book, so complete or incomplete, it is the face of Amethyst for newly arriving users.

**Comment by Rhuagh** [comment]
I didn't say it was a good banner, and I totally agree we should have a better introductory experience. Like we said, unfortunately the book has been neglected for some time simply due to the fact we all do this in our spare time, and sometimes other shiny things catch our attention when we really should be fixing this.

It is in our roadmap to fix this around release time, which shouldn't be far off now.

**Comment by vi** [comment]
The homepage looks as if Amethyst is already "Launched", but in reality it is more like "In construction"?..

Maybe it may be more benefitial to have a toned down homepage until Amethyst is ready for influx of users.

**Comment by vi** [comment]
The warning at [crates.io](https://crates.io/crates/amethyst) looks more appropriate and may be duplicated both to the book (all pages) and to the homepage.

**Comment by distransient** [comment]
This issue is solved with https://github.com/amethyst/amethyst/commit/f952ce7c4a764bd0b20b23972a954905e85ec1a7#diff-998a7340c3c0a62eb8a2221b5a17ca11

**Comment by Xaeroxe** [comment]
That's true, so I'll close this.  Thanks!
