### ISSUE TITLE
RFC: Language Loading API

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#469]
I'm making a language API based on iso 639-2 code definition. Make your suggestion/criticisms here about the features + architecture. Here's my current "plan".

Goal: Load and structure a bunch of strings under a language->language packs structure to make it easy to get a string in a language, and to make it compatible with modding (#470). This will allow things like language-pack mods, which add translations to a game that is missing them.

> Lang API
> 
> if debug, log when not found and default to specified default language.
> if not found in default language, write "MISSING TEXT"
> 
> if release, same as debug but don't log
> 
> struct StringPack{
>     priority: i32,
>     strings: HashMap<String,String>,
> }
> 
> struct Language{
>     display_name:String,
>     string_packs: HashMap<String,StringPack>,
> }
> 
> struct LanguageAPI{
>     fallback:Language,
>     langs:HashMap<String,Language>,
> }
> 
> get_langs()
> get_lang("mis").get_string_packs()
> get_lang("eng").get_string_pack("interface").get_string("main_menu_description") -> &String
> get_lang("fra").get_string("main_menu_description") -> &String //lookup in all string_packs. gets the first one found
> get_lang(user_pref.lang).get_string_pack("interface") -> &Dictionary

**Comment by Xaeroxe** [comment]
So Language confused me because of the connotation with Programming Language, so maybe let's call this a localization API?  Looks pretty good to me otherwise though!

We can't be the only ones with this need, are there any already existing crates for this stuff?

**Comment by jojolepro** [comment]
Localization also refers to things like date and money formats. I did find this crate: https://crates.io/crates/fluent (and a couple others too), but I'm not sure if they really solve my use case. The goal of this is to be compatible with #470 , which is to basically make modding possible and easy by loading everything from raw data. If we are going to use a crate, we will still need a way to push the strings into the crate, so formatting happens.

From fluent examples:
```
let ctx = MessageContext::new(&["en-US"]);
ctx.add_messages("hello-world = Hello, world!");

let value = ctx.get_message("hello-world")
               .and_then(|message| ctx.format(message, None));

```

**Comment by OvermindDL1** [comment]
I'd probably just call it GetText and then follow the standard gettext format since it has tons of tools for all this and all already (I use the gettext format excessively in other projects, it is pretty easy to define the files and interface for it).

**Comment by jojolepro** [comment]
@OvermindDL1 the only difference I see between gnu's gettext and this is the name of the functions. I'll rename them as it does make sense to follow the standard. ;)
What's your opinion about the language packs (split a language file into multiple smaller files)?
base/lang/eng/errors.ron
base/lang/eng/ui.ron
base/lang/fra/ui.ron
mod/overrides/lang/eng/errors.ron

**Comment by OvermindDL1** [comment]
Not just the naming, also talking about the asset files to load for the languages.  The format has been very well battle-hardened.  :-)

I absolutely would *\*not\*ever\** try to come up with your own asset format for them.  I've seen those fail in so very many language corner cases over the years and everyone ends up going to the gettext format anyway.

**Comment by Rhuagh** [comment]
I agree with @OvermindDL1, let's just use gettext.

**Comment by OvermindDL1** [comment]
Unsure how complete it is since it is only 0.2.0, but:  https://crates.io/crates/gettext

**Comment by jojolepro** [comment]
@OvermindDL1 I never used gettext, but I'm looking at it right now. What's the benefit of having that file format https://www.gnu.org/software/gettext/manual/html_node/MO-Files.html when we can have a simple HashMap directly in a ron file which gets deserialised in a single line with serde?

**Comment by OvermindDL1** [comment]
> @OvermindDL1 I never used gettext, but I'm looking at it right now. What's the benefit of having that file format gnu.org/software/gettext/manual/html_node/MO-Files.html when we can have a simple HashMap directly in a ron file which gets deserialised in a single line with serde?

It's format handles not only simple mappings like a hashmap would, but it also handles pluralizations, numbering formats, even has support of languages that have many different representations of plurality and not just the normal 2/3 that most languages have, and far *far* more.

Let me put it this way, anyone who assumes that a simple hashmap is sufficient for internationalization of even just simple 'text' has never internationalized something.  ^.^

**Comment by OvermindDL1** [comment]
Also, you should not use `mo` files straight like that, the usual files people use are `po` files (which you can kind of 'compile' into an `mo` file for faster loading, but always start with `po` files).

**Comment by jojolepro** [comment]
In my head, this was originally only to get a string in a language according to a key. I wasn't really thinking about money symbols, date formats, right to left text, and complex stuff like those. I admit it would be nice to integrate those, though. I'll check them out and see how much work they require to integrate.

**Comment by OvermindDL1** [comment]
> In my head, this was originally only to get a string in a language according to a key. I wasn't really thinking about money symbols, date formats, right to left text, and complex stuff like those. I admit it would be nice to integrate those, though. I'll check them out and see how much work they require to integrate.

I'd say just use an existing gettext library, it looks like there is a few for Rust.

**Comment by jojolepro** [comment]
As @OvermindDL1 said, we should use a library to do localization for us. Thus making this RFC useless. Feel free to open a PR if you want to integrate localization and translations support.
