### ISSUE TITLE
RFC: Asset Loading API

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#470]
Goal: Fully automate asset loading using a optional and customisable template describing the structure and distribution of the assets, while allowing modding of assets.

Make your suggestions/criticisms here.

Description:

> Asset Loading API
> 
> In this document, mentally replace all references (&something) by a UUID/GUID/UID  (unique identifier).
> 
> Features:
> -autoload using configured folder structure
> -load from network (post release, after network is working)
> -modding/override support (via next point)
> -asset referencing using UUID
> 
> 
> Folder Structure Example (configurable, of course):
> Meshes -> Mesh1.obj
> Textures -> tex1.png,tex2.jpg
> Entities -> Entity1(&Mesh1,&tex1), Entity2(&Mesh1,&tex2)
> Configurations -> display_conf.ron, user_prefs.ron
> Languages->eng->language_pack1.ron
> Scripts->script1.??
> 
> Networked Structure Example (flat structure, segmented by network packets):
> (Mesh1,Mesh2,Texture1,Texture2,Entity1(&Mesh1,&Texture2),display_config.ron)
> 
> 
> To keep track of which files are which type, a config structure will map folderpaths/networkoffset to a asset type. (Can be a downloadable template!)
> Example:
> ./meshes/{mesh} -> Mesh
> ./languages/{lang}/{language_pack} -> Lang
> 
> 
> Modding/Override Example
> ./base/meshes/mesh1.obj
> ./base/entities/Entity1(&mesh1)
> ./mod1/overrides/meshes/&mesh1.obj

Side note: By implementing modding at the engine level, it will reduce the work load of people making games with it. It will also make a standard modding structure which will allow modders to make mods that *could* be compatible with multiple games!

Following the lack of details, here's how it should work internally:
This will rely on lazy loading.
When you enable this opt-in feature, you will need to specify how your data is layed out (being in files, over the network, or anywhere else).
Then this will create and resolve references between the raw asset data. The actual `Asset` won't be loaded until you explicitly use it, or if you explicitly tell the asset to get loaded (like in a loading screen).

**Comment by Rhuagh** [comment]
Please don't force a folder structure on the engine user.

**Comment by Xaeroxe** [comment]
So a couple things:

I'm not completely certain we want to automate loading of assets for every project, as assets can take a while to load and sometimes it's critical that we don't start particular operations until the asset is loaded.  Giving the developer tight control over asset loading is likely to be very important especially for commercial games.

This RFC also forces the asset system to be abstract over the source of the asset, which for many games that don't care about asset substitution, is unnecessary overhead.  It'd be a lot easier to critique around this point with some code examples though.

**Comment by Rhuagh** [comment]
I don't even understand what this PR is about, I'd need a lot more information before I can make an opinion

**Comment by jojolepro** [comment]
@Rhuagh Its a opt-in functionality where you specify how your data is layed out, and the asset system takes care of the loading.
For example
{working_dir}/meshes contains multiple Mesh assets, serialized as ron.

@Xaeroxe Opt-in, and configurable. If you want to use it, you use it, if not you don't.
As for load times, the principle behind this is to rely heavily on lazy loading. You load all references to the raw data on boot, but only convert the raw data to asset when you either
1) Use it
2) Request the loading

I'll update the RFC description accordingly with more precision.

**Comment by Rhuagh** [comment]
This sounds like the stuff @torkleyy is working on.

**Comment by Xaeroxe** [comment]
> It will also make a standard modding structure which will allow modders to make mods that could be compatible with multiple games!

I'd rather not entertain this possibility as there is absolutely no way that'd work in practice.  I guarantee it.

**Comment by jojolepro** [comment]
It does sound a lot like hot reloading, but with more automation. (I'm lazy)

**Comment by jojolepro** [comment]
@Xaeroxe I said its a possibility. Obviously the difference between how games will actually differ in content makes it really impractical.

**Comment by torkleyy** [comment]
@jojolepro Did you read my plans regarding "asset libraries"?

**Comment by torkleyy** [comment]
Once they're merged, this issue is very, very easy to solve. It won't be 100% automatically, you will have to write something like this

```rust
loader.load_library(FullAssetLibrary::new(..), "./", (), storages);
```

but I think that's acceptable.

**Comment by Xaeroxe** [comment]
It was determined on gitter this is redundant, so I'm closing this.

**Comment by jojolepro** [comment]
That got closed, but where's torkleyy RFC for that feature?

**Comment by Rhuagh** [comment]
He's had a busy week, it'll be in eventually.
