### ISSUE TITLE
Long boot time on macOS

### ISSUE THREAD

**Issue by Kerollmops** [amethyst/amethyst#472]
When you launch any amethyst driven program on any macOS system, the boot time (with the white screen) is very long compared to other OS, it's displayed more than 5 seconds.

**Comment by Rhuagh** [comment]
Only happens for some examples, I have examples where it's instant. That being said this occurs deep inside the renderer during pipeline build.

**Comment by Xaeroxe** [comment]
@Rhuagh indicated this only happens when using DrawPbm or DrawShaded.  DrawFlat loads very quickly.

**Comment by Rhuagh** [comment]
`let pso = fac.create_pipeline_state(&prog, self.prim, self.rast, self.init.clone())?;`

this line takes 5s on OSX with DrawShaded/DrawPbm

**Comment by Rhuagh** [comment]
Got it.
