### ISSUE TITLE
Targets without depth test display nothing on Mac

### ISSUE THREAD

**Issue by Xaeroxe** [amethyst/amethyst#473]
Targets without a depth test don't work on Mac, this makes the UI pass useless on OSX.  We should fix this before we release.

**Comment by omni-viral** [comment]
Haven't you tested it with depth target?

**Comment by Xaeroxe** [comment]
@omni-viral As in while using a blend target with a depth buffer?  Yes I have, why?

**Comment by omni-viral** [comment]
It works fine if you specify some depth testing in `with_blend_target`.

**Comment by Xaeroxe** [comment]
Right, I remember now.  So it only fails when you have no depth test on a blend target.

**Comment by Xaeroxe** [comment]
@Rhuagh helped narrow down the problem, so I've updated the issue title and comment.
