### ISSUE TITLE
Texture animation

### ISSUE THREAD

**Issue by Xaeroxe** [amethyst/amethyst#478]
My next project is going to be animating textures, both in the 3D world and for the UI.  This will also be a big step towards 2D sprite objects.  I'm opening this issue to collect feature requests for this.  Some things might include:

- Any file formats you want our 2D animation to support?
- Do you want animations to progress over time, or over frames?  Maybe let the user pick?  Currently I don't think anyone needs over frames, but tell me if I'm wrong!

Things that are out of scope:

- Animating movement.  This project is geared specifically towards changing textures.

**Comment by jojolepro** [comment]
> Do you want animations to progress over time, or over frames? Maybe let the user pick? Currently I don't think anyone needs over frames, but tell me if I'm wrong!

Both

**Comment by Rhuagh** [comment]
Wrong button...

**Comment by Rhuagh** [comment]
Can you give a use case of animating over frames?

**Comment by Xaeroxe** [comment]
@jojolepro Can you give me some examples of when you'd want to animate per frame instead of per time span?

**Comment by Rhuagh** [comment]
For movement animation of normal entities with a `LocalTransform`, the existing animation system works well.

**Comment by omni-viral** [comment]
Animating the texture must be available in several forms.
* Picking a portion of texture.
* Pick texture from array.
* Switching from one texture to another.

**Comment by OvermindDL1** [comment]
There are also Shader-animated textures (which I tend to do for fire and water and such), which can be as simple as just animating the coordinates of the texture applied so it moves in a direction, to changing scale, to just flat-out generating it in full in the shader and anything in-between.  As well as the picking a portion of a texture or picking from an array can be done in shader as well (though the switching cannot be unless you bind them all all the time, though binding two at a time and blending between them, perhaps based on another texture doing the morph mapping, is useful too).

**Comment by Xaeroxe** [comment]
Feature is in the engine so I'm closing this.
