### ISSUE TITLE
The Amethyst book is missing content

### ISSUE THREAD

**Issue by binary132** [amethyst/amethyst#50]
I'd love to explore the Pong guide, but the chapter appears to be missing.  :smile:

https://www.amethyst.rs/book/simple_application.html

**Comment by LucioFranco** [comment]
There has been a lot of work on the renderer and ecs so I think it will start to be filled up soon! 😄

**Comment by binary132** [comment]
It looks really cool, I can't wait.

**Comment by binary132** [comment]
Still interested.  Still keeping an eye on the project.  If someone wants to point me in the right direction to contribute this I'd be happy to help.

**Comment by Emilgardis** [comment]
An pong example is available, no guide has been written though, see example 04 :)

**Comment by derekdreery** [comment]
I'm currently learning the engine by writing a guide to the pong example. I'll post it once I've finished in case it's useful/good enough to include.

**Comment by Rafagd** [comment]
As someone who is just looking at this project from outside, I can say that a full description of the options that are available on the config.ron file would be very much welcome.

**Comment by Xaeroxe** [comment]
This issue is somewhat outdated and we have other issues tracking progress on the book, so I'm going to close this.
