### ISSUE TITLE
Add thread profiler to all subcrates

### ISSUE THREAD

**Issue by Aceeri** [amethyst/amethyst#503]
Profiling was broken when we moved the code into subcrates, so we need to add the subcrate features to the top level Cargo.toml

**Comment by Hittherhod** [comment]
Which subcrates use it? The latest develop branch doesn't seem to have any subcrates referencing the thread_profiler.

**Comment by zoonage** [comment]
Looks like this was done in commit 07cf8b45f2551eee7beb5f645fbd16b5acac4380, should this be closed?

**Comment by torkleyy** [comment]
I think this issue is about two things:

* enable the `profiler` feature for the subcrates if the `profiler` feature of the main crate is enabled
* add profiling code to the subcrates

Both are not fixed as far as I can see.

**Comment by Rhuagh** [comment]
That sounds about right to me yeah. All systems should have profiling atleast. For the asset crate I'd guess all format calls should be profiled.

**Comment by zoonage** [comment]
@Rhuagh could you clarify what you mean by 'all format calls should be profiled'?

Going from the examples it looks like it would be up to the program using the library to implement the profiling for the functions in the `Format` trait.

**Comment by Rhuagh** [comment]
https://github.com/amethyst/amethyst/blob/a78139f8612ffe1aea7e0eb53f4389b43d7b62e9/amethyst_assets/src/loader.rs#L142

The import here should be profiled, so we can tell how fast/slow individual formats are.

**Comment by zoonage** [comment]
@Rhuagh I've added this into the PR.

On a generic note should we standardise the names of each profile? Currently they seem to be named sensibly, but arbitrarily. Maybe we could use a naming scheme like `<crate_name>::<path>::<to>::<function>::<comment>` i.e. `amethyst_assets::source::dir::Directory::load::load_asset`, this would make debugging a lot easier as it would tell you where to look, however these are quite lengthy.

**Comment by jojolepro** [comment]
Looks like a good idea, but if we change the directory of a file we'll forget to change the profile name.
What about amethyst_assets:load_asset

**Comment by zoonage** [comment]
I've logged an issue against thread_profiler to get some comments https://github.com/glennw/thread_profiler/issues/12

**Comment by zoonage** [comment]
I've put in a PR to fix glennw/thread_profiler#12 after that this issue is just adding the profiling code to our sub-crates

**Comment by Rhuagh** [comment]
Because you don't want profiling in a live game, because it consumes cpu cycles.

**Comment by zoonage** [comment]
The thread_profiler won't do anything if the feature isn't enabled on their crate (we are duplicating feature gates), in glennw/thread_profiler#9 we were looking at removing it, so I wanted to know if there was another reason for us having it

**Comment by torkleyy** [comment]
I'm not sure whether we should wrap the macro ourselves or use the current mechanism. I tend to the latter.

**Comment by zoonage** [comment]
@torkleyy Only the assets crate is profiled at the moment, There is remaining work to profile the remaining crates. However I'm not sure what needs to be profiled in those as I'm not familiar with the other crates and their bottlenecks.

the stuff being discussed (and therefore the naming of the profiles bein taken in the sub-crates) in glennw/thread_profiler#9 should be done in a separate issue as it will be a different release of that particular crate

**Comment by torkleyy** [comment]
Not only the assets loop is profiled, but also the game loop and (I think) rendering. I think this issue was mainly about setting the project layout up, that's done. Before we don't know what exactly we want to profile, we should just leave it like this.

**Comment by torkleyy** [comment]
I'm closing this now, otherwise it'll confuse new contributors. When there are specific sections we want to profile, new issues shall be opened.
