### ISSUE TITLE
Pong example: generate_rectangle_vertices has wrong values for tex_coord

### ISSUE THREAD

**Issue by trsoluti** [amethyst/amethyst#509]
This doesn't matter to the Pong game, but the moment you try to use a png file as your texture instead of a single colour, you get strange results.

The tex_coord values should be 0.0 for every left, 1.0 for every right, 0.0 for every bottom and 1.0 for every top.

This will help people who want to start making 2D games for Amethyst.

**Comment by torkleyy** [comment]
I believe we already changed the coordinates before..

**Comment by trsoluti** [comment]
In the repository, amethyst/examples/pong/pong.rs and amethyst/examples/pong_tutorial_02/pong.rs have the wrong values.

**Comment by Hittherhod** [comment]
I don't see these issues in the repository. From the git history, there were changes in on October 10 (at least in the dev branch)

**Comment by jojolepro** [comment]
is this fixed yet?

**Comment by Xaeroxe** [comment]
No, no action has been taken as we're not quite sure what's correct here.

**Comment by trsoluti** [comment]
I've checked the repository. They've been wrong since the beginning. Here are the proposed changes:
```
*** pong.rs_CURRENT	Mon Feb 19 10:57:42 2018
--- pong.rs_PROPOSED	Mon Feb 19 18:02:30 2018
***************
*** 262,264 ****
              position: [left, top, 0.0],
!             tex_coord: [1.0, 1.0],
          },
--- 262,264 ----
              position: [left, top, 0.0],
!             tex_coord: [0.0, 1.0],
          },
***************
*** 274,276 ****
              position: [right, bottom, 0.0],
!             tex_coord: [0.0, 0.0],
          },
--- 274,276 ----
              position: [right, bottom, 0.0],
!             tex_coord: [1.0, 0.0],
          },
```

**Comment by jojolepro** [comment]
Now managed by sprites and spritesheets. Closing this.
