### ISSUE TITLE
Nightly regression (receiving SIGSEV)

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#512]
I'm sure it happens somewhere between `Application::build` and `State::on_start`. Probably in the renderer initialization :(

---

```
Version: v0.5.1-394-gaf76188
Platform: x86_64-unknown-linux-gnu
Amethyst git commit: af76188a7628c87f306e380df1dc80ec5cfadcbb
Rustc version: 1.24.0-nightly Nightly
Rustc git commit: 7eb64b86ce44cc1828dd176a8b981e37ea08fc38
```

**Comment by Rhuagh** [comment]
What graphics driver ?

**Comment by torkleyy** [comment]
`Mesa 17.0.7` which is well-known for its bugs. However, it doesn't happen on stable, so I'm pretty sure it's `rustc`'s fault.

**Comment by torkleyy** [comment]
As noted by @Rhuagh the line in question is https://github.com/amethyst/amethyst/blob/af76188a7628c87f306e380df1dc80ec5cfadcbb/amethyst_renderer/src/renderer.rs#L284

I noticed that turning vsync off "solves" the problem.

**Comment by torkleyy** [comment]
Okay, the problem is `SwapIntervalEXT`. While it is reported to be loaded, it causes a `SIGSEV` on mesa. `SwapIntervalSGI` works.

**Comment by Rhuagh** [comment]
Report to glutin?

**Comment by torkleyy** [comment]
I would prefer to deliver a fix, but yeah you're right.

**Comment by torkleyy** [comment]
I created a PR to glutin which fixed this issue. Once we're using the latest glutin version, vsync should work on mesa.

**Comment by torkleyy** [comment]
Fixed in the latest version which will be used in the next gfx version.
