### ISSUE TITLE
Document ScreenDimensions better

### ISSUE THREAD

**Issue by Xaeroxe** [amethyst/amethyst#522]
This resource is confusing people, so I'm creating this issue as a reminder

**Comment by OvermindDL1** [comment]
Especially document what happens if it is not an integral number stored in it, like say `984.286` or something.  Though in my opinion a type should *only* represent valid values, and if something like the prior is an invalid value then the type should be corrected to prevent that.

**Comment by Xaeroxe** [comment]
The interface to `ScreenDimensions` prevents invalid values being stored, it specifically requests integers.  However it does also return floats because most of the time when these are needed they're going to be converted to float values anyways.
