### ISSUE TITLE
Cannot compile using Metal backend

### ISSUE THREAD

**Issue by Hittherhod** [amethyst/amethyst#523]
I'm trying to see how things would work with a Metal backend instead of OpenGL, but I'm getting loads of compiler errors about Self being unsized. It might be that there is an old version of cocoa-rs lying around, as I'm seeing 0.5.2 being pulled in when I think it is up to 0.13 at this point.

# Meta
`stable-x86_64-apple-darwin unchanged - rustc 1.22.1 (05e2e1c41 2017-11-22)`
`MacBook Pro (15-inch, 2017) `
`OSX 10.12.6 Sierra`

# Compiler errors
`   Compiling cocoa v0.5.2`
` error[E0277]: the trait bound 'Self: bitflags::<unnamed>::marker::Sized' is not satisfied`
`   --> /Users/rhodysn1/.cargo/registry/src/github.com-1ecc6299db9ec823/cocoa-0.5.2/src/appkit.rs:300:45`
`    |`
`300 |     unsafe fn sharedApplication(_: Self) -> id {`
 `   |                                             ^^ 'Self' does not have a constant size known at compile-time`
`    |`
`    = help: the trait 'bitflags::<unnamed>::marker::Sized' is not implemented for 'Self'`
`    = help: consider adding a 'where Self: bitflags::<unnamed>::marker::Sized' bound`

...
`   Compiling winit v0.7.6`
`error: aborting due to 56 previous errors`

`error: Could not compile 'cocoa'.`

The 56 errors are all about the Sized trait not being implemented. It might be a problem with older dependencies but still, I would think it would still compile.

winit did make a note about changing cocoa APIs, but I don't know if that was related to the subcrate or the direct Apple APIs.

**Comment by Rhuagh** [comment]
Even though it might look like we have metal support, we don't really have metal support. We currently only support OpenGL in the develop branch. This will change when gfx-hal has been released and we can merge our new renderer (#463).

**Comment by Hittherhod** [comment]
Okay. Should I close this issue once the HAL branch is merged or is now okay?

**Comment by Xaeroxe** [comment]
Now is fine, since this technically isn't really a supported feature right now.  Sorry for causing you a hassle!
