### ISSUE TITLE
[RFC] amethyst_deps

### ISSUE THREAD

**Issue by Xaeroxe** [amethyst/amethyst#528]
We currently have 11 crates in the repository, several of which share many dependencies.

It would be foolhardy to move all of these shared dependencies into core because then they'd become part of our exposed interface and updating our dependencies might become a breaking change when it doesn't have to be.

So I propose adding a new crate called `amethyst_deps`.  The only purpose of this crate is to expose common dependencies between our 11 crates.  If any two crates have the same dependency, then that dependency would be an eligible candidate to move into `amethyst_deps`.

Unlike our other crates `amethyst_deps` would not be re-exported through the `amethyst` crate, instead our 11 crates will just depend on it separately.  This allows us to release new breaking versions of `amethyst_deps` to our heart's desire, and depend on these new versions in non-breaking releases.

**Comment by omni-viral** [comment]
So when you increase version of dependency `A`, you'll have to increase version of `amethyst_deps` and so all crates. Instead of just two crates that actually depend on `A`?

**Comment by Xaeroxe** [comment]
Right, that is a problem.  The only ways around this I can think of would involve breaking semver for amethyst_deps.  I don't think that's a good idea.

**Comment by Xaeroxe** [comment]
I'll leave this open for a day in case anyone comes up with an alternative, but with the point you've mentioned I'm no longer confident this is a good idea.

**Comment by torkleyy** [comment]
There's actually another problem: you'll have to download and compile dependencies that you don't even need.

**Comment by omni-viral** [comment]
@torkleyy in case you use only some of amethyst crates? Yes. It's even bigger problem.

**Comment by jojolepro** [comment]
Looks like more management work for very little reward :/
