### ISSUE TITLE
[RFC] Crate files organisation

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#535]
Proposal: Organize files following a more strict hierarchy as follow:
{crate_name}/src/bundles/
{crate_name}/src/components/
{crate_name}/src/resources/
{crate_name}/src/model/ (enums+traits+structs that are not component or resources, like Error for example)
{crate_name}/src/systems/
{crate_name}/src/utils/
{crate_name}/src/prelude.rs
{crate_name}/src/lib.rs
{crate_name}/cargo.json

[+]
-Possible automatic mod.rs files creation.
-Easier to import what you need (no need to read the doc or source code). Compensate for the lack of proper IDE auto-import support.
-Easy to manage prelude using scripts.
-Easy to locate the prelude in each crates, which is good for quick iterations and testing/learning code.
-Reduced workload due to higher level of automation.
[-]
-Boring to implement at first
-Somewhat higher quantity of code to write (you have to duplicate imports when un-merging structs from files)

With this, there would be the need for automation scripts that could generate mod.rs and prelude.rs files.
A simple recursive directory crawler that generates code could do that pretty easily.

**Comment by Rhuagh** [comment]
I think we've decided to not do preludes, only export everything at the root of the library
