### ISSUE TITLE
UI Example Failures to Run on Mac OS X

### ISSUE THREAD

**Issue by Hittherhod** [amethyst/amethyst#536]
## Metadata
Initializing Amethyst...
Version: v0.5.1-421-ge8829ba
Platform: x86_64-apple-darwin
Amethyst git commit: e8829ba76fd29eb804faeaaa44dbe3c341bc2c39
Rustc version: 1.24.0-nightly Nightly
Rustc git commit: 687d3d15ba726dbb1ac6b85223ebe0e98c6820cc

## Additional Information
Dimensions 0 0
I added a print in the `initialise_camera()` function to print out the height and width, and it is returning 0. I see in the `amethyst_renderer/src/bundle.rs` file that the ScreenDimensions are initially set to 0. The pong example shows the same behavior (ScreenDimensions are 0), but it doesn't use the ScreenDimensions are the input to the camera so it's not a big deal.

I see that `amethyst_renderer/src/systems.rs` updates the screen dimensions, but it doesn't look like it has been called by the time we initialize the camera.

**Comment by Xaeroxe** [comment]
Thanks for filing an issue!  I've known about this I just hadn't made an issue for it yet.  Now I have something to put in a PR that fixes this!

Our fix to this is likely going to involve restructuring the Amethyst initialization process, as it has a difficult time communicating with the Specs world during initialization.  That causes compromises such as this.
