### ISSUE TITLE
The future of the `Bundle` API

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#541]
I think the main problem of the current API is that it is ugly to access the world while building the `Application`. Also, we should be able to add `RunNow` stuff to `DispatcherBuilder`.

cc @Xaeroxe @Rhuagh

**Comment by Xaeroxe** [comment]
I'm going to call this resolved.  @torkleyy re-open if you disagree with me.

**Comment by torkleyy** [comment]
I think we reached like the near time goal, so yeah closing is okay. In the future we might need more flexibility e.g. allow to add resources but not systems.

**Comment by Rhuagh** [comment]
I have ideas, we can discuss at some point.
