### ISSUE TITLE
Pong Example Player 1 (Left Hand) ScoreText Does Not Appear

### ISSUE THREAD

**Issue by Hittherhod** [amethyst/amethyst#544]
I'm using the Pong Example to learn some of the components of amethyst, but I'm confused as to why the left-side player (player 1)'s score isn't showing up. It has something to do with the coordinate system, which has me confused. The arena is configured to be 100 x 100, which is why I assume the constant "100" appears in pong.rs in the translation closures. However, the first closure evaluates to a negative number (because the ScreenDimensions are 0 at the time the `initialise_paddles()` is called #536). 

I've played around with the numbers, and it seems like the camera projects such that the visible x-coordinate values are 0-1000. I'm not super sure of the math behind it though, so I can't figure out a equation that uses knowledge of arena properly.

**Comment by Xaeroxe** [comment]
So the UI pieces don't rely on camera properties whatsoever.

Also, I've seen this work on current develop.  Can you give us some data about your system?

**Comment by Xaeroxe** [comment]
Just compiled and ran this on Windows 10 and it's working for me.  I'm able to see both scores.

**Comment by Hittherhod** [comment]
I'm running on a Mac OS X running 10.12.

Version: v0.5.1-434-g6eb490d
Platform: x86_64-apple-darwin
Amethyst git commit: 6eb490d6e21f62b82cf4ff2ecec41a9971c729e8
Rustc version: 1.25.0-nightly Nightly
Rustc git commit: 3f92e8d89861f0f5408ad9381a7467ec6e7d76bc

This is from my pull of the current develop.
<img width="503" alt="only_second_score" src="https://user-images.githubusercontent.com/1400222/35017465-f4d9a6b6-faea-11e7-8378-18a8c19e3f9d.png">

**Comment by Xaeroxe** [comment]
Excellent thank you!  I'll make sure to test this on OSX.

**Comment by Xaeroxe** [comment]
@Hittherhod Out of curiosity, does the problem go away if you resize the window a tad?

**Comment by Hittherhod** [comment]
The example hides the cursor, so I'm not sure how to resize it. Is there a keymap for that?

**Comment by Xaeroxe** [comment]
Oh does it even hide the cursor if you move the cursor outside the window?  I know it hides if the cursor is in the window but it shouldn't hide if the cursor is outside the window.

**Comment by Hittherhod** [comment]
At least on my machine it does. It hides it if the application is the main window. If it isn't then I can see the cursor. I was able to resize using that and I get some vicious screen tearing.
<img width="680" alt="screen shot 2018-01-16 at 18 42 36" src="https://user-images.githubusercontent.com/1400222/35017907-1255c38a-faed-11e7-8bf8-a300392130b7.png">

**Comment by Xaeroxe** [comment]
☹️ Drat.  Ok I'll make sure to start adding more OSX testing to my QA checks before doing a release.  Thanks for filing an issue!

**Comment by Hittherhod** [comment]
I'm willing to help out with that if you need it. I have a couple OSX computers that I can test things out on. One is pretty much frozen on 10.12, but the others have newer versions of OSX.

**Comment by Xaeroxe** [comment]
That might actually be helpful.  It's a little perturbing that the OSX resizing doesn't work at all.  Since I wrote the resize handling code I'll need to figure out why that isn't working.

**Comment by Hittherhod** [comment]
Using the latest from the `develop` branch, which includes basic logging with `fern`, I get the following output:

[amethyst::app][INFO] Initializing Amethyst...
[amethyst::app][INFO] Version: v0.5.1-438-gd3b7d51
[amethyst::app][INFO] Platform: x86_64-apple-darwin
[amethyst::app][INFO] Amethyst git commit: d3b7d51f41e3eff2faea08acd14a4f04550d9364
[amethyst::app][INFO] Rustc version: 1.25.0-nightly Nightly
[amethyst::app][INFO] Rustc git commit: da569fa9ddf8369a9809184d43c600dc06bd4b4d
[gfx_device_gl::info][INFO] parsing version '4.1 ATI-1.60.24'
[gfx_device_gl::info][INFO] parsing version '4.10'
[gfx_device_gl][INFO] Info { platform_name: PlatformName { vendor: "ATI Technologies Inc.", renderer: "AMD Radeon R9 M395 OpenGL Engine" }, version: 4.1, ATI-1.60.24, shading_language: 4.10, extensions: {"GL_ARB_vertex_attrib_64bit", "GL_EXT_texture_filter_anisotropic", "GL_ARB_transform_feedback2", "GL_ARB_texture_storage", "GL_ARB_instanced_arrays", "GL_EXT_depth_bounds_test", "GL_EXT_texture_sRGB_decode", "GL_ARB_tessellation_shader", "GL_ARB_viewport_array", "GL_APPLE_object_purgeable", "GL_APPLE_rgb_422", "GL_EXT_debug_marker", "GL_ARB_sample_shading", "GL_EXT_debug_label", "GL_APPLE_flush_render", "GL_ARB_texture_rgb10_a2ui", "GL_ARB_gpu_shader_fp64", "GL_ARB_occlusion_query2", "GL_EXT_texture_mirror_clamp", "GL_ATI_texture_mirror_once", "GL_ARB_transform_feedback3", "GL_ARB_gpu_shader5", "GL_ARB_texture_cube_map_array", "GL_ARB_draw_indirect", "GL_APPLE_row_bytes", "GL_ARB_texture_buffer_object_rgb32", "GL_ARB_texture_gather", "GL_ARB_texture_query_lod", "GL_ARB_timer_query", "GL_ARB_vertex_type_2_10_10_10_rev", "GL_ARB_texture_swizzle", "GL_ARB_shader_bit_encoding", "GL_ARB_separate_shader_objects", "GL_ARB_draw_buffers_blend", "GL_ARB_shader_subroutine", "GL_ARB_ES2_compatibility", "GL_ARB_explicit_attrib_location", "GL_ARB_sampler_objects", "GL_APPLE_client_storage", "GL_APPLE_texture_range", "GL_ARB_shading_language_include", "GL_NV_texture_barrier", "GL_ARB_internalformat_query", "GL_EXT_texture_compression_s3tc", "GL_ARB_blend_func_extended", "GL_APPLE_container_object_shareable"} }
[gfx_device_gl][INFO] Capabilities { max_vertex_count: 1048575, max_index_count: 150000, max_texture_size: 16384, max_patch_size: 32, instance_base_supported: false, instance_call_supported: true, instance_rate_supported: true, vertex_base_supported: true, srgb_color_supported: true, constant_buffer_supported: true, unordered_access_view_supported: true, separate_blending_slots_supported: true, copy_buffer_supported: true }
[gfx_device_gl][INFO] PrivateCaps { array_buffer_supported: true, frame_buffer_supported: true, immutable_storage_supported: true, sampler_objects_supported: true, program_interface_supported: false, buffer_storage_supported: false, clear_buffer_supported: true, frag_data_location_supported: true, sampler_lod_bias_supported: true, texture_border_clamp_supported: true }
[gfx_device_gl::factory][INFO] 	Created frame buffer 1
[gfx_device_gl::shade][INFO] 	Compiled shader 1
[gfx_device_gl::shade][INFO] 	Compiled shader 2
[gfx_device_gl::shade][INFO] 	Linked program 3
[gfx_device_gl::shade][WARN] 	Log: WARNING: Could not find fragment shader output 'Target2' to match FragDataBinding request.
WARNING: Could not find fragment shader output 'Target3' to match FragDataBinding request.
WARNING: Could not find fragment shader output 'Target1' to match FragDataBinding request.
WARNING: Could not find fragment shader output 'Target0' to match FragDataBinding request.

[gfx_device_gl::shade][INFO] 		Sampler[0] = 'albedo'	F32	D2(NoArray, NoMultiSample)
[gfx_device_gl::shade][INFO] 		Attrib[0] = "normal"	F32	Vector(3)
[gfx_device_gl::shade][INFO] 		Attrib[1] = "tangent"	F32	Vector(3)
[gfx_device_gl::shade][INFO] 		Attrib[2] = "tex_coord"	F32	Vector(2)
[gfx_device_gl::shade][INFO] 		Attrib[3] = "position"	F32	Vector(3)
[gfx_device_gl::shade][INFO] 		Block[0] = 'VertexArgs' of size 192
[gfx_device_gl::shade][INFO] 			Element at 0	= 'proj'	F32	Matrix(ColumnMajor, 4, 4)
[gfx_device_gl::shade][INFO] 			Element at 64	= 'view'	F32	Matrix(ColumnMajor, 4, 4)
[gfx_device_gl::shade][INFO] 			Element at 128	= 'model'	F32	Matrix(ColumnMajor, 4, 4)
[gfx_device_gl::factory][INFO] 	Created buffer 1
[gfx_device_gl::shade][INFO] 	Compiled shader 4
[gfx_device_gl::shade][INFO] 	Compiled shader 5
[gfx_device_gl::shade][INFO] 	Linked program 6
[gfx_device_gl::shade][WARN] 	Log: WARNING: Could not find fragment shader output 'Target2' to match FragDataBinding request.
WARNING: Could not find fragment shader output 'Target3' to match FragDataBinding request.
WARNING: Could not find fragment shader output 'Target1' to match FragDataBinding request.
WARNING: Could not find fragment shader output 'Target0' to match FragDataBinding request.

[gfx_device_gl::shade][INFO] 		Sampler[0] = 'albedo'	F32	D2(NoArray, NoMultiSample)
[gfx_device_gl::shade][INFO] 		Attrib[0] = "tex_coord"	F32	Vector(2)
[gfx_device_gl::shade][INFO] 		Attrib[1] = "position"	F32	Vector(3)
[gfx_device_gl::shade][INFO] 		Block[0] = 'VertexArgs' of size 32
[gfx_device_gl::shade][INFO] 			Element at 0	= 'proj_vec'	F32	Vector(4)
[gfx_device_gl::shade][INFO] 			Element at 16	= 'coord'	F32	Vector(2)
[gfx_device_gl::shade][INFO] 			Element at 24	= 'dimension'	F32	Vector(2)
[gfx_device_gl::factory][INFO] 	Created buffer 2
[gfx_device_gl::factory][INFO] 	Created buffer 3
[gfx_device_gl::factory][INFO] 	Created buffer 4
[gfx_device_gl::factory][INFO] 	Created buffer 5
[gfx_device_gl::factory][INFO] 	Created buffer 6
[gfx_device_gl::shade][INFO] 	Compiled shader 7
[gfx_device_gl::shade][INFO] 	Compiled shader 8
[gfx_device_gl::shade][INFO] 	Linked program 9
[gfx_device_gl::shade][WARN] 	Log: WARNING: Could not find fragment shader output 'Target2' to match FragDataBinding request.
WARNING: Could not find fragment shader output 'Target3' to match FragDataBinding request.
WARNING: Could not find fragment shader output 'Target1' to match FragDataBinding request.

[gfx_device_gl::shade][INFO] 		Uniform[0] = 'transform'	F32	Matrix(ColumnMajor, 4, 4)
[gfx_device_gl::shade][INFO] 		Sampler[0] = 'font_tex'	F32	D2(NoArray, NoMultiSample)
[gfx_device_gl::shade][INFO] 		Attrib[0] = "color"	F32	Vector(4)
[gfx_device_gl::shade][INFO] 		Attrib[1] = "tex_pos"	F32	Vector(2)
[gfx_device_gl::shade][INFO] 		Attrib[2] = "pos"	F32	Vector(3)
[gfx_device_gl::factory][INFO] 	Created buffer 7
[gfx_device_gl::factory][INFO] 	Created buffer 6
[gfx_device_gl::factory][INFO] 	Created buffer 8
[gfx_device_gl::factory][INFO] 	Created buffer 6
[gfx_device_gl::factory][INFO] 	Created buffer 7
[gfx_device_gl::factory][INFO] 	Created buffer 6
The factory just keeps creating buffers 6, 7, and 8 in the order above until I press escape.

**Comment by Rhuagh** [comment]
FYI, I can't see the score for the left player either, and the right player score is on the left side of the screen. I'm also on Mac.

**Comment by Hittherhod** [comment]
For the screen tearing, the tearing only happens on the right and bottom of the screen. Resizing to be more vertical adds garbage to the bottom, while resizing horizontally adds garbage to the right side (even if I resize the window to pull it to the left).

**Comment by Hittherhod** [comment]
@Xaeroxe @Rhuagh More weirdness. Resizing causes those tears, but it actually fixes the placement of the ScoreText in some cases (mostly if I stretch the window horizontally enough).

<img width="737" alt="screen shot 2018-01-22 at 8 19 52 pm" src="https://user-images.githubusercontent.com/1400222/35253091-a049d1e0-ffb1-11e7-890c-e28f4e0b74b0.png">

I added a print of the UI Transforms in amethyst_ui/src/pass.rs on line 190 and got this output:
Pre-resize:
```
UI Transform: Some(UiTransform { id: "P1", x: 72.5, y: 0.0, z: 1.0, width: 55.0, height: 50.0, tab_order: 0, pd: PhantomData })
UI Transform: Some(UiTransform { id: "P1", x: -127.5, y: 0.0, z: 1.0, width: 55.0, height: 50.0, tab_order: 0, pd: PhantomData })
```
Post-resize: 
```
UI Transform: Some(UiTransform { id: "P1", x: 806.5, y: 0.0, z: 1.0, width: 55.0, height: 50.0, tab_order: 0, pd: PhantomData })
UI Transform: Some(UiTransform { id: "P1", x: 606.5, y: 0.0, z: 1.0, width: 55.0, height: 50.0, tab_order: 0, pd: PhantomData })
```

**Comment by Xaeroxe** [comment]
Some of that is expected.  The reason I asked you to trigger a resize before is that doing a resize should re-trigger the placement functions for the UI pieces, which are dependent on screen size.  Since screen size is initially 0,0 they get placed with that as the screen size, which is of course incorrect.

Sorry I haven't gotten around to finishing my PR to fix this, life has been slightly hectic as of late.

**Comment by Hittherhod** [comment]
@Xaeroxe I'm still seeing a related issue with this. Before a resize event, both ScoreTexts are off to the left side.
<img width="499" alt="screen shot 2018-02-01 at 07 57 19" src="https://user-images.githubusercontent.com/1400222/35679759-353fd92c-0726-11e8-8655-126593a4f8de.png">

After a resize, I see this:
<img width="519" alt="screen shot 2018-02-01 at 07 57 36" src="https://user-images.githubusercontent.com/1400222/35679772-3d8a1c50-0726-11e8-8810-58575afcae3a.png">

**Comment by Xaeroxe** [comment]
Related to https://github.com/tomaka/winit/issues/399
