### ISSUE TITLE
Resizing to expand window causes garbage to appear on Mac OS X

### ISSUE THREAD

**Issue by Hittherhod** [amethyst/amethyst#547]
Discovered this while troubleshooting #544. If you expand the screen, it adds garbage to the windows. This happens on all window examples, not just with the UI, so I believe it is a separate issue. 

## Metadata
```
[amethyst::app][INFO] Version: v0.5.1-438-gd3b7d51
[amethyst::app][INFO] Platform: x86_64-apple-darwin
[amethyst::app][INFO] Amethyst git commit: d3b7d51f41e3eff2faea08acd14a4f04550d9364
[amethyst::app][INFO] Rustc version: 1.25.0-nightly Nightly
[amethyst::app][INFO] Rustc git commit: ae920dcc98c9b18b38aac03367f7f1cd6dce7d2d
```

## Screenshots
<img width="1125" alt="screen shot 2018-01-23 at 16 30 37" src="https://user-images.githubusercontent.com/1400222/35301902-d8d42908-005a-11e8-8511-110c0fbc00c1.png">

**Comment by Hittherhod** [comment]
These seems related to https://github.com/tomaka/winit/issues/399

**Comment by Rhuagh** [comment]
Looks very likely to be the issue yes. Retina displays usually don't have logical == physical pixels.
