### ISSUE TITLE
OpenVR Support?

### ISSUE THREAD

**Issue by palodequeso** [amethyst/amethyst#55]
Now that I own an HTC Vive, I've been looking for a suitable open source engine to hack some demos in. I explored Rust quite a bit a year ago, and then fell off. Now that I see everything really maturing more, I'd like to dive back in. I saw this project and love the inspiration. I was hacking my own engine, but would perhaps like to start contributing to this instead. Know all of this, I know it is still very early to start thinking about such a feature, but it would be great to add in support for OpenVR.

I'd be willing to hack on that when the time is right, if that's even in the scope of this engine.
Thoughts?

**Comment by palodequeso** [comment]
Note, it seems I can't assign labels, but I would say this is probably fairly easy, and low priority.

**Comment by csherratt** [comment]
There is https://github.com/rust-openvr/rust-openvr. It would be neat to support.

**Comment by palodequeso** [comment]
> There is https://github.com/rust-openvr/rust-openvr. It would be neat to support.

That seems like a great place to start, but is there a camera system, or basic renderer yet for this engine? I suspect there's a lot to be done before it realistically makes sense to dive into the OpenVR wrapper.

**Comment by kvark** [comment]
@palodequeso the engine has rendering (thanks to @csherratt) and it's hooked up with our ECS (`specs`), but no standard systems in place to actually do stuff for you, they are the first on our TODO list.

**Comment by palodequeso** [comment]
@kvark, got it. I suppose I'll dig through the code for a bit and make a few examples, and then dive into the "standard systems".

**Comment by palodequeso** [comment]
PS: Is there a slack or IRC channel where people discuss general ideas for this project?

**Comment by kvark** [comment]
@palodequeso You'd need to use the `develop` branch to explore these new things.
As for the chat, you are welcome to join https://gitter.im/amethyst/engine and https://gitter.im/amethyst/general

**Comment by benrob0329** [comment]
What about http://www.osvr.org/ ?

**Comment by diegor8** [comment]
https://www.khronos.org/vr
All pc hmd manufacturers are part of this initiative , which means that open vr will become obsolete once this is released , so we should keep an eye on this instead .

**Comment by assumptionsoup** [comment]
It looks like https://github.com/MortimerGoro/rust-webvr is would cover both open vr and oculus until khronos gets something out.

**Comment by Xaeroxe** [comment]
This issue is pretty old and a lot of the info in here isn't quite relevant anymore, so I'm going to go ahead and close this.

**Comment by johannesvollmer** [comment]
Khronos' OpenXR has been released last year, and a Rust binding already exists. Is someone interested in amethyst and VR?

**Comment by johannesvollmer** [comment]
Ah, I see there was another Issue in 2018, but no one cared enough, so nothing happened. Then just ignore these two comments haha
