### ISSUE TITLE
Arbitrary mesh flickers while playing

### ISSUE THREAD

**Issue by Xaeroxe** [amethyst/amethyst#557]
For reasons I have yet to determine sometimes when playing Pong the right paddle will flicker.  It's not consistent or constant throughout play, but can still be reliably re-produced.

Meta:

```
[amethyst::app][INFO] Initializing Amethyst...
[amethyst::app][INFO] Version:
[amethyst::app][INFO] Platform: x86_64-pc-windows-msvc
[amethyst::app][INFO] Amethyst git commit: ac7cab3484e520edc65a067b11d0bcf5c3c1ca0d
[amethyst::app][INFO] Rustc version: 1.23.0 Stable
[amethyst::app][INFO] Rustc git commit: 766bd11c8a3c019ca53febdcd77b2215379dd67d
```

**Comment by Xaeroxe** [comment]
Can't reproduce on my personal laptop.  I can reproduce on one of my two desktops.  I'll check the other tonight.

**Comment by Aceeri** [comment]
@Xaeroxe Look at the window resizing code, it might not be getting updated. (That was the issue I had where the meshes flickered black)

**Comment by Xaeroxe** [comment]
Very likely to be a graphics driver failure on the integrated intel graphics of the machine I saw this on.  I can't reproduce this elsewhere, so I'm closing this.
