### ISSUE TITLE
[Renderer] Add implicit layers/target

### ISSUE THREAD

**Issue by ghost** [amethyst/amethyst#57]
This is a pretty important but complicated feature. We need a way for some `Pass` to build list of new targets that are needed. The use-case that comes to mind is support for shadow passes. This involves looking at the list of lights, checking which ones request a shadow buffer be generated and which ones are visible. The `Renderer` should then create shadow buffer targets for each light that passed this test and render the scene as required into them before the `Pass` is run.

This is a pretty complex feature and I doubt we are ready to tackle it yet with the current `Renderer` it's far to simple. But understanding how to build this solution should highlight all the missing blocks and driver the `Renderer` in the correct direction.

**Comment by kvark** [comment]
We can split the problem into a number of sub-problems:
  1. How do we create new resources in the passes? We could have a method like `Pass::prepare` that would accept `&mut self` and `&mut Factory`, by default doing nothing. For the shadow pass, it would create all the needed targets for the scene.
  2. How do we store the resources? They are accessible from multiple semi-independent passes (like, one pass fills in shadows, another one reads it when evaluating the light).
    - one way is to have some sort of an `AnyMap`, either globally (so it can be indexed by light ID), or per-light. Obviously, this is not elegant.
    - another way is ECS, strangely. Basically, a shadow can be just a component of the entities that are light sources. Obviously, this ruins the abstraction between the renderer and ECS.

There is more to it. One could state that a different layer/target should use it's own command buffer for rendering. So basically, a pass (or something else) needs to be able to spawn temporary layers, and re-use the associated resources (targets, buffers) between frames somehow. This intersects with how our parallel rendering is going to work, so it's blocked by #19.

**Comment by OvermindDL1** [comment]
Honestly, no point separating the ECS and rendering, should be an ECS engine as that would be a far better pattern to follow in the development.

**Comment by Xaeroxe** [comment]
This issue is super out-dated and I believe fixed in the current version so I'm closing it.
