### ISSUE TITLE
[RFC] Alternate root GameData structure

### ISSUE THREAD

**Issue by huhlig** [amethyst/amethyst#576]
Per request from @Xaeroxe this RFC was inspired by recent discussions on Gitter.

As more use cases for Amethyst begin to explore the virtues and limitations of
the current data architecture some hurdles are beginning to present themselves for
both optimization and flexibility. The current ECS design forces a specific way of
thinking that works for a lot of designs but requires use of anti-pattern solutions
in others. When examining how one would implement a dense voxel map idiomatically in
Amethyst general consensus is that each voxel should be an entity within
the system. While very simple this is not an optimal structure for chunked densely 
packed Voxel data accessed by range query. Thus Voxel information would be 
relegated to an outside resource with array data and a second ecs world containing
Voxel definitions. The access pattern of this second ecs is random and differs 
greatly from the sequential access pattern of the primary ecs iterator.

This proposal suggests removing the global specs World structure and replacing it
with a structure containing just the resource portion of the specs world structure.
Each state would be handed this new resource structure instead of the global ecs
and when building system pipelines a Vector of ResourceID(TypeID, GUID) would be
provided. This would still match the current behavior of providing a "global" ecs
to each system but would also allow supplemental resources to be provided to a 
system while allowing background threads to dynamically load and save new resources
or build new pipelines.

For System specialization this allows for specialized or multiple data structures
to be provided to a system in an idiomatic way. An example of this is using 2 
separate ECS structures for entity data, a chunked voxel structure and ecs, 
or eschew the ecs entirely in favor of an alternate system.

**Comment by Xaeroxe** [comment]
So one alternate way of viewing your RFC @huhlig would be to mostly maintain the existing `World` structure but have dedicated component storages for each `SubWorld`
For the most part what's suggested is having multiple instances of component storages
Systems would also have an assigned `SubWorld` for which they fetch component storages, but otherwise function the same

**Comment by jojolepro** [comment]
Nothing here is trivial to implement < 3

**Comment by huhlig** [comment]
So just for some additional context around this and my thinking. The _GameData_ structure is master container which gets passed around to all _Game States_. It needs to include all data (or the ability to lazily load it) for any given state the game can be in and any data which needs to be transferred from state to state. The _Active State_ is also responsible for dictating what data gets processed by which code at what time. This may include entity components being processed by a system, optimized rendering passes on a dense 3d voxel structure, or starting network synchronization. However this can also include background tasks **unrelated** to the currently active entities. An example of this would be preloading the next level in a side scroller asynchronously; a second example would be running a less precise secondary simulation thread semi synchronously updating once per frame for inactive maps (for living worlds). 

The following would effectively mimic current behavior by including a single default global ecs. 
```
use amethyst::ecs::shred::Resources;
use amethyst::ecs::World;

pub struct GameData {
    resources: Resources,
}

impl Default for GameData {
    pub fn default() -> Self {
        let gamedata = GameData {
            resources: Resources::new(),
        };
        let pecs = World::new();
        gamedata.resources.add_with_id(pecs, 0);
        return gamedata;
    }
}
```

One piece that isn't exposed in this is how to dispatch resource(s) to be processed. I assume this is currently part of the fixed_update call, however it might be worth while to make system_dispatch for a given ecs an explicit call.

With the following altered State trait, an api endpoint is provided that would allow ecs dispatching, background task execution via threadpool, or other baked in features.
```
pub trait State {
    fn on_start(&mut self, _api: &EngineAPI, _data: &mut Gamedata) {}
    fn on_stop(&mut self, _api: &EngineAPI, _data: &mut Gamedata) {}
    fn on_pause(&mut self, _api: &EngineAPI, _data: &mut Gamedata) {}
    fn on_resume(&mut self, _api: &EngineAPI, _data: &mut Gamedata) {}
    fn handle_event(&mut self, _api: &EngineAPI, _data: &mut Gamedata, _event: Event) -> Trans { Trans::None }
    fn fixed_update(&mut self, _api: &EngineAPI, _data: &mut Gamedata) -> Trans { Trans::None }
    fn update(&mut self, _api: &EngineAPI, _data: &mut Gamedata) -> Trans { Trans::None }
}

pub trait EngineAPI {
   /// Dispatch an ecs container to a specified system
   fn dispatch(_ecs: &mut World, system: &System);
   /// Perform background task
   fn submit_task<V>(_task: Fn()-> V) -> Future<V>;
}
```

I understand this is not where Amethyst is today however let me know if my logic is faulty, shortsighted, or misguided in this architecture.

**Comment by jojolepro** [comment]
> It needs to include all data (or the ability to lazily load it) for any given state the game can be in
Network runtime asset loading is included in lazy load? Or is it only to register components? :thinking: 

The logic seems to hold, and I see how it could be used.
General questions opened to everyone:
-Need: How much is this a desirable feature.
-Feasibility: Is it possible to code this without stopping progress on other essential features for months.
-Performance: Will this negatively affect performance, or will it improve it? Memory? Parallel execution % ?
-Priority: If this RFC is accepted, should we do it asap, or focus on the features that we are currently missing in the engine? (network, complete ui system, physic integration, examples, doc).

Since everyone seems to agree that its a going to be a giant amount of work, I think it would be important to be sure we want to do it, and how we want to do it.

ps: Nice rfc, well written (:

**Comment by huhlig** [comment]
For Networking this is honestly where an architecture like this is best suited imho. You handle events from the runtime, then call dispatch on the active ecs with the network sync system. All dirty inputs are sent to the server/peers and all authoritative state is downloaded and populates the proper components. Then when the next fixed_update is called the new state data is processed and the simulation ticks forward.

**Comment by jojolepro** [comment]
Quote from @torkleyy on gitter
>I don't think all worlds should share a dispatcher
We discussed before and came to the conclusion that it should be possible to have multiple dispatchers for a single world.

**Comment by torkleyy** [comment]
## Disadvantages of having multiple worlds

* Two `Entity`s can be equal, but belong to different `World`s. That is confusing.
* Fetching `SystemData` seems to be either impossible or has to be done manually; if done manually we still have to provide our reads and writes. However, a `ResourceId` does not contain information which `World` the resource is coming from, thus there is no way to do parallelization :(

**Comment by torkleyy** [comment]
Also, I don't think you want to share all resources between all the worlds. Imagine two worlds in a split-screen game, each is for one screen. You'll want two `UiFocused` resources, but just one `AssetStorage<FontAsset>`.

**Comment by huhlig** [comment]
When would one entity coexist in two separate worlds simultaneously. At least in my mind a world is a discrete separate context of execution. An entity my transfer between Worlds but I don't see any reason why it would exist in two simultaneously. Also systems would be discrete to the world, each world would have it's own set. This would allow a pre-primed world to be brought into active use with an atomic swap rather than a save, clear, load cycle. Think of it like a backbuffer in 3d graphics. You prepare one, while blitting the other. Same can be said for worlds. They are discrete collections of related data. The key point there is *discrete*.

**Comment by jojolepro** [comment]
Imagine the player looking at a terminal/monitor showing the player moving through a different level. Both entities are the same, except for the transform. Also, one of the 2 is not controllable.

**Comment by huhlig** [comment]
That's not discrete. Nor even a single render. Most games that use "portal windows" use secondary rendering and a completely separate second camera. Basically you would dispatch a rendersystem call n the second world from the second camera entity. The result you map into your primary geometry. Basically the terminal camera is a completely separate entity existing in that other world. This is one reason secondary dispatch can be even more useful. That secondary world can be dispatched in parrallel as the two structures are unrelated.

**Comment by jojolepro** [comment]
What I wrote was a potential use case, and also an example that could be made in the future. I'm sure having 2 worlds can make this easy. How would you fetch the camera of the second world on put it on the texture in the first world? That's can't be multithreaded, obviously, as you need the second world to fully render before you can fetch the texture and then render the first world.

**Comment by huhlig** [comment]
Why can't it be multi threaded? Building Vulkan pipelines at least is naturally multi-threaded. In fact you would kick off the render to image on the first thread and as part of your pipeline the result would be included on a surface in your primary render thread.

**Comment by jojolepro** [comment]
I'm wondering how that would be integrated in the engine. System in world 1 accessing components in world 2.

**Comment by huhlig** [comment]
Why would system 1 be accessing components owned by system 2? World 2 has it's own copy of systems.

**Comment by jojolepro** [comment]
World 1
texture(component) of world2::camera
World 2
camera (component)

You update the texture in world 1 using a System or using some kind of reference to the component in world 2?

**Comment by huhlig** [comment]
You got me there. I would say if you're in that situation either it's one level with multi level geometries OR your texture component contains a dynamic texture handle from the graphics driver. So
World 1 
DynamicTextureComponent(ImageHandle of World2 Pipeline) 
World 2
Camera(Component), RenderTypeComponent(ImageHandle)

In this specific instance the levels are inexorably linked due to cross pollination, they are no longer discrete and require special setup. Decomposing this down, if Both worlds are considered active I would likely iterate over all camera's in world 2 that are "exported" as image buffers and insert them into world one as handles as part of state setup. Alternatively I would use a shared (and locking) resource used by both worlds to communicate the small amount of cross pollinating data. As a side note, if you are using networking, you are already dealing with a lot of similar synchronization rules between parallel worlds. Having two discrete worlds that need to stay completely or partially in sync will need to be a solved problem anyway.

**Comment by torkleyy** [comment]
The following is possible today:

```rust
impl<'a> System<'a> for MySys {
    type SystemData = (Fetch<'a, TileWorld>, Fetch<'a, TileMap>);

    fn run(&mut self, (world, map): Self::SystemData) {
        let e = map.tile(1, 5).entity;
        let world = &world.world;
        if let Some(material) = world.read::<Material>().get(e) {
            println!("Tile at (1, 5): {:?}", material);
        }
    }
}
```

**Comment by Rhuagh** [comment]
I think a better solution is to make the game data pluggable, and we supply a default variant that looks similar to what we have today.

**Comment by huhlig** [comment]
That was kind of my intent by putting the resource manager as top level, then you could setup any combination of gamedata as the authority. Be is ECS, or something different.

**Comment by Rhuagh** [comment]
And I don't like a default variant where we only have shred::Resources, that removes a serious amount of specs features with little gain.

**Comment by huhlig** [comment]
Alright then simply define GameData as extending Any + Send + Sync. It would also logically mean that states are then responsible for starting ecs dispatch but I don't think that's necessarily a bad thing.

**Comment by Rhuagh** [comment]
That's the basic idea yeah

**Comment by huhlig** [comment]
I'm all for it then! I love ECS but it's ill suited to certain problems.

**Comment by Rhuagh** [comment]
I can take a stab at this soon. Or I might improve the bundle system first, we'll see.

**Comment by torkleyy** [comment]
> general consensus is that each voxel should be an entity within the system

Is it? I'm not sure that's such a good idea. If you don't need the ECS mostly, you can mostly just use resources or make `GameData` a resource. Rendering will have to be more flexible, but that would be a good thing anyways.

**Comment by OvermindDL1** [comment]
The way I did voxels in my ECS was to have chunks of data, each of which held 32x32x32 blocks, the chunk itself was an entity, each block pointed to a 'type' entity (an entity shared among types) except for the occasional one that needs to hold location-specific state, in which case it would 'point' to the base entity type but have an additional storage for a world entity (which was just a BlockPos that used a 4-integer coordinate to state what block it was on).  I could 'access' any block as an entity, like it was a world entity, but it didn't actually save as a new unique entity unless some location specific component got stored on it (and consequently it vanished if all location-specific components were removed).
