### ISSUE TITLE
Question: Data oriented | Functional programming

### ISSUE THREAD

**Issue by ShalokShalom** [amethyst/amethyst#581]
Hi there :)

Especially with DDD combined does it occur to me that the modularity and the conceptional context of OO becomes in functional programming united with the parallelism friendliness and conciseness of data oriented design?

Is the performance gap seriously such huge between data oriented imperative code and declarative functional one?

How much functional code is there in Amethyst?

**Comment by omni-viral** [comment]
@ShalokShalom Not much functional code in `amethyst`. `amethyst` is based on `specs`. And specs is stateful.

**Comment by ShalokShalom** [comment]
I see. Is this simply for performance reasons and/or since specs is so suitable for your project?

**Comment by torkleyy** [comment]
I think there have been experimentations with functional ECS in Rust, but the performance wasn't very good.

**Comment by ShalokShalom** [comment]
I see. Thanks a lot
