### ISSUE TITLE
Using transparencies requires the user to link in other crates

### ISSUE THREAD

**Issue by trsoluti** [amethyst/amethyst#583]
The with_transparency() method on passes takes three arguments:

```
        mask: ColorMask,
        blend: Blend,
        depth: Option<DepthMode>
```
The types and possible values for these are private within Amethyst, meaning the user has to link in gfx and gfx_core just to get a program using with_transparency() to compile.

I recommend the following:

1) re-export the appropriate types and constants from gfx and gfx_core (`ColorMask`, `Blend`, `DepthMode`, and `gfx::preset::blend::*`).
2) add another method `with_standard_transparency` which takes no arguments and calls `with_transparencies(ColorMask::all(), ALPHA, None)` (these are the arguments the UI pass uses).

This should provide flexibility and also ease of use.

Another option is to make transparencies the default, and to add another method `without_transparency` for people who want a faster pass.

**Comment by Rhuagh** [comment]
I'd like to avoid the last part, simply because the vast majority of meshes will be opaque. The rest sound good to me.
