### ISSUE TITLE
Commit efa39a7 breaks example 'renderable'

### ISSUE THREAD

**Issue by Candunc** [amethyst/amethyst#585]
This is built on Windows 10 x64 using 'rustc 1.24.0 (4d90ac38c 2018-02-12)', and gives the following error:

> thread '\<unnamed\>' panicked at 'No resource with the given id', src\libcore\option.rs:891:5

I have attached the stdout with RUST_BACKTRACE="full": [renderablepanic.txt](https://github.com/amethyst/amethyst/files/1760631/renderablepanic.txt)

Given that [the change was very minor](https://github.com/amethyst/amethyst/commit/efa39a7acc7d2228347ae6c458c3956f732dee67#diff-cf946f1970d88f384e748923503ad7f5), could this be a bug with the newest amethyst_ui?

**Comment by jojolepro** [comment]
Caused by missing InputHandler<A,B>

**Comment by jojolepro** [comment]
I'll be fixing it within the next 1-2 hours.

**Comment by jojolepro** [comment]
Fix out. #586
