### ISSUE TITLE
[Noob] v0.6.1 of amethyst_renderer/bundle.rs is different between cloned Amethyst repository and Amethyst dependency in my project

### ISSUE THREAD

**Issue by Borginator** [amethyst/amethyst#587]
Hi,
This is odd. I'm probably just being stupid but any help would be greatly appreciated.
My own project has the amethyst 0.6.0 dependency
I have also cloned this repository in to a separate project.

The version of amethyst_renderer is 0.6.1 in both my library dependency in my project, and in my cloned version of this project.

But bundle.rs is different between the two. Specifically the constructor for RenderBundle is different (among other things, but this is what I noticed when trying to get the window example to run in my project) I assume this isn't normal?

`` 
pub fn new(pipe: B, config: Option<DisplayConfig>) -> Self {
        RenderBundle {
            pipe,
            config,
            transparent_sorting: None,
        }
    }
``
vs 
``
    pub fn new() -> Self {
        Default::default()
    }
``

**Comment by jojolepro** [comment]
cc @omni-viral

**Comment by Xaeroxe** [comment]
Sometimes version numbers in the repo don't get updated until we do the release itself.  I'm sorry if this is confusing.

As a rule of thumb, if the crate has changed in the repo but the version number hasn't then what you're looking at is actually going to be the next breaking version.  So amethyst_renderer in the repo would be 0.7.0

**Comment by Rhuagh** [comment]
It's kind of a rust convention to only update the version numbers just prior to release.

**Comment by Candunc** [comment]
If you want to use the latest amethyst build, rather than the previous release, you might want to use this in your Cargo.toml.

amethyst = { git = "https://github.com/amethyst/amethyst.git", branch = "develop" }

**Comment by jojolepro** [comment]
Personally I'd prefer if we were to update the version numbers every time there's a PR on a crate.

**Comment by Xaeroxe** [comment]
Most of the time we don't know how many changes we're going to get in before our next release.  The next version might be semver compatible with the last one, but it also might not be.  Updating version numbers prior to the release means we have to make this judgement more than once, overall incurring more review work.

I'm not really opposed to updating version numbers sooner rather than later but I also don't have any interest in enforcing this myself.

**Comment by jojolepro** [comment]
That's totally fine. I think this question as been answered properly. The version hasn't been updated because there wasn't a release. Also, he might have cloned the develop branch instead of 0.6, which might have led to this confusion.

**Comment by Xaeroxe** [comment]
@Borginator If you feel the question posed has been satisfactorily answered would you please close this issue?

To future readers: If this thread has been dead for a month go ahead and close this.

**Comment by Borginator** [comment]
@jojolepro You nailed it, I did check out the develop branch and hadn't noticed. I expected that when I hit the https://github.com/amethyst/amethyst page It would be on the latest release, it didn't even occur to me that this might have been the dev branch, I suppose that's probably because it's not 1.X.X yet.

@Rhuagh I was unaware of this convention in Rust-land. I usually use X.X.X-SNAPSHOT for things that have changed but not released yet.

Thank you everyone for taking the time to respond. I really appreciate it.

**Comment by jojolepro** [comment]
To avoid future confusion, I suggest we add a "The amethyst github is by default using the develop branch" inside the readme file, where it is really obvious and visible.
@Borginator have fun using amethyst :) :100:
