### ISSUE TITLE
[amethyst-controls] Add arc-ball camera

### ISSUE THREAD

**Issue by Candunc** [amethyst/amethyst#593]
The currently implemented fly camera is good for 'birds eye view' movement around the scene, however I was wondering if a sort of third person 'arc-ball camera' could be added to amethyst. The [kiss3d crate](https://github.com/sebcrozet/kiss3d/) has a good description of how it operates: 

> An arc-ball camera is a camera rotating around a fixed point (the focus point) and always looking at it.

@jojolepro, I understand you implemented the fly camera two weeks ago with your amethyst_controls crate, would it be possible to add this sort of camera as well?

**Comment by jojolepro** [comment]
Its definitely something that I would like.
Would you like to do the implementation/PR?
If you don't I can do it eventually.

**Comment by Candunc** [comment]
I could look into it, however until I get started other people are free to do the implementation.

**Comment by jojolepro** [comment]
If someone takes this over, please write a comment here to prevent duplicate work. Thanks!

**Comment by jojolepro** [comment]
Here is an example of a first person camera, for reference: https://github.com/amethyst/amethyst/blob/develop/amethyst_controls/src/systems.rs#L103

**Comment by mnivoliez** [comment]
Hello, I will *try* to answer this issue.
From a mathematical point of view, a just do rotation in the target referencial (the thing we look at). Therefore, the arc ball component should have a "target" property indicating what the camera is looking for. It seems to me that the calcul is essentially the same as @jojolepro reference some minutes ago https://github.com/amethyst/amethyst/blob/develop/amethyst_controls/src/systems.rs#L103.

**Comment by jojolepro** [comment]
Thanks a lot @mnivoliez
