### ISSUE TITLE
UiText alignment

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#594]
Feature request

Align left default----
--align center--
----align right

Also, if the text doesn't fit into the mesh holding it, it might be a good idea to have an "overflow" option.
if we reverse the problem, changing the text size so it fits onto the mesh could be another option.

Also top,center and bottom vertical alignements.
When I use my layouting PR to set the text to be fill a rectangle, having the text centered in the middle would be nice ;)
Less testing required to align stuff this way.

Since this requires modifying the pass, I'd consider this average difficulty.

**Comment by Rhuagh** [comment]
I think overflow already exists?

**Comment by Xaeroxe** [comment]
Fair warning: This might be a bit more difficult than you're thinking.  You'll probably need a custom implementer of this trait: https://docs.rs/gfx_glyph/0.9.0/gfx_glyph/trait.GlyphPositioner.html

**Comment by jojolepro** [comment]
@Rhuagh 
text.text = "55555555555555555555555555555555555555555555";
on a UiText with space for around 10 numbers makes it invisible.

**Comment by Xaeroxe** [comment]
I've started working on fixing this/providing this enchantment

**Comment by jojolepro** [comment]
Hello. Was there any progress on this since last time? Thanks!

**Comment by Xaeroxe** [comment]
No, several branches were made and then discarded I kept getting distracted so no I don't have any progress on this sadly.

**Comment by jojolepro** [comment]
Okay, thanks for the quick reply.

**Comment by jojolepro** [comment]
issue reserved
