### ISSUE TITLE
Default Amethyst Processors and Components for ECS

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/amethyst#60]
This issue is to keep track of all the systems that will need to be implemented for amethyst engine.
### Systems
- [x] Transform | Issue: (https://github.com/amethyst/amethyst/issues/53), PR: (https://github.com/amethyst/amethyst/pull/113)
- [x] Rendering | PR: (https://github.com/amethyst/amethyst/pull/85)
- [ ] Scripting
- [x] Audio
### Components
- [x] Transform
- [ ] Velocity?
- [x] Renderable

Feel free to leave a comment and/or create a PR. Let us know if you are working on one by leaving a comment.

**Comment by JDoneth** [comment]
Should networking be a target? 

For example: Some sort of automatic serialization and transmission of structs over the std library networking functions.

**Comment by ebkalderon** [comment]
@JDoneth That is correct, but off-topic. Networking is an engine-level feature and not an ECS (entity-component-system) feature. This issue deals with implementing [systems in the ECS sense](https://www.amethyst.rs/book/glossary.html#Entity-component-system%20%28ECS%29%20model). Personally, I prefer the term "processors" to eliminate confusion.

**Comment by JDoneth** [comment]
Ah sorry, my bad, I saw systems and thought engine layers.

**Comment by ahmedaliadeel** [comment]
Position and velocity shouldnt be separate components. If u use 3rd party physics like nphysics or bullet bindings u get rigidbody access. We need to provide a rigidbody component.

**Comment by Emilgardis** [comment]
I think that they should be separated, I don't see any reason why they shouldn't. Having them together means more work for the engine, i.e computing if a object is static (not moving) or dynamic (moving).

**Comment by ahmedaliadeel** [comment]
I haven't explorered the nphysics yet but based on my experience on unity 3d i was suggesting this idea. 
Look, its not just velocity or angular velocity there is much more about a physical body. Like i want to know velocity at certain point? 
Let me explain in detail for a different perspective. I think we should have separate components and respective subsytem for both 2d and 3d. 
Talking about the granulity of components incase of 3d physics we should provide components the way most physics engine api is natural to map. Physix, bullet both have to concept of rigidbodies, colliders etc 
For kinemetic physics we can just add a property to rigidbody component that this object is not dynamic. (As of know nphysics doest support kinemetic bodies) or if its an unmovable static body etc.
Now that i have discovered this project i will also try to implement a reference set of components and subsystem.
Thanks for consideration.

**Comment by kvark** [comment]
@ahmedaliadeel yes, while rendering 2D/3D is mostly uniform, physics gets definitely much more complicated, so it kinda makes sense to separate 2D and 3D components for it. Looking forward to see what you'll come up with!

**Comment by Aceeri** [comment]
I think a networking system might definitely be a goal for this. For instance, automatic sync between a server (or maybe P2P?) for specified components.

**Comment by Aceeri** [comment]
Outdated, kind of handled in separate issues like `scripting` and `physics`.
