### ISSUE TITLE
[Bug] Entity recreation causes Parenting systems to fail.

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#600]
How to replicate:
Create an entity.
Delete the entity a few frames later.
Re-create the same entity at the same index.

Known affected Systems:
-UiParentSystem #591 [Fixed]
-TransformSystem [Pending #601]

Impact:
As those systems think that it is the same entity, when it is not, they do not execute changes that should be applied to those newly created entities.

If you know of a System using a Bitset to track entities by their index, it is most likely affected by this too.

**Comment by torkleyy** [comment]
We need the Tracked stuff..

**Comment by Rhuagh** [comment]
Yep

**Comment by jojolepro** [comment]
I need to change something, or you are talking about a future specs feature?

**Comment by torkleyy** [comment]
the latter :)

**Comment by jojolepro** [comment]
Fixed by recent updates, right? @Rhuagh

**Comment by Rhuagh** [comment]
Should be

**Comment by jojolepro** [comment]
Reopen if you notice something similar ;)
