### ISSUE TITLE
Supporting more keys

### ISSUE THREAD

**Issue by antoyo** [amethyst/amethyst#602]
Hi.
It would be nice to support more keycode because keyboard in other languages than english has characters like `é`.
Thanks.

**Comment by torkleyy** [comment]
This should probably be moved to winit I think.

**Comment by Xaeroxe** [comment]
@antoyo I think there's been a bit of a misunderstanding.  Keycodes, despite appearances, aren't actually concerned with representing characters.  Character input is handled by a completely different set of OS events.  Keycodes are concerned with symbols on the actual key pressed, not how that press could be interpreted.  For example, there is no é key on any keyboard, but the correct sequence of key presses can produce that character.

**Comment by JadeSnail** [comment]
@Xaeroxe Some keyboards layout have accentuated characters such as é on a single key. That is, you only need a single key press to get é. Afaik there is no way to register such a key press in amethyst.

**Comment by Xaeroxe** [comment]
Can you send me a picture of such a keyboard?  I'm having a hard time finding a layout that does this

**Comment by JadeSnail** [comment]
For example, the french standard layout has a ù to the right of the keyboard, see https://fr.wikipedia.org/wiki/AZERTY#/media/File:KB_France.svg

I'm also aware of the french bépo layout, which has éèçêà

**Comment by Xaeroxe** [comment]
Ok, thank you!  As @torkleyy mentioned first this has to happen in winit, then it can propagate to Amethyst.  This function in winit is responsible for doing the keycode transalation on Windows: https://github.com/tomaka/winit/blob/master/src/platform/windows/event.rs#L32

If we can update this (and the other platforms) to use whatever we're expecting then we should be in good shape.

**Comment by francesca64** [comment]
Looks like this issue never made its way over to winit.

I should note that `VirtualKeyCode` is on the list of "things with unresolved API questions that I can't think about right now", so while I'll merge any PR that comes in for adding more variants, it would be a *huge* help if someone wants to put more thought into this aspect of keyboard handling. tomaka/winit#59 tomaka/winit#71

**Comment by torkleyy** [comment]
If there is a need for more keys, please make a PR against winit or contribute to the discussion as linked by @francesca64. I'm closing this since there's nothing we can do in this repo to fix this.
