### ISSUE TITLE
UI Feature List

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#607]
I kinda duplicates some issues, but at least now its all going to be in the same place.

* [x] Components builders. Example: UiButton::new(x,y,name,Option<parent>).build() -> (image: Entity, text: Entity)
* [x] UiButton
* [ ] UiCheckbox
* [ ] UiDropdown (list)
* [ ] UiTable?
* [ ] UiSlider
* [x] UiTextArea (text + text editing)
* [ ] UiNumberArea (text + number text editing)
* [ ] UiPagedArea (can be shown or not)
* [ ] UiScrollArea (UiSlider + UiOverflowModes)

## Bug fixes

* [ ] Text shows on top of everything
* [x] Z ordering breaks caching (gfx_glyph bug)
* [x] Alignment is broken on mac.

## Features

* [ ] UiOverflowModes (if something goes outside of his parent's box, hide or show? Partially show or remove completely?)
* [x] Scale with % of screen/parent size
* [x] Text alignement (top,middle,bottom. left,middle,right, reuse Anchor enum for this)
* [x] Ui elements animations

## Extra
* [ ] Macro for easy layout prototyping.
Example:
```
!buildui{
	Button("btn1",0,0).with_anchor(TopLeft),
	DropDownList([elements],20,20).stretched(Stretch::X)
}
```

**Comment by memoryruins** [comment]
You may be aware of better UI algorithms/solutions, but if it helps, lately I've used [tui](https://docs.rs/tui/) for a few projects, and recently, looked into one of its few crate dependencies [cassowary](https://docs.rs/cassowary), which implements the Cassowary constraint solving algorithm ([Badros et. al 2001](https://constraints.cs.washington.edu/solvers/cassowary-tochi.pdf) | [Wikipedia](https://en.wikipedia.org/wiki/Cassowary_(software))). It aims to be performant and make no assumption of UI in general, and makes setting an overflow element easily (even in a tui, with ease I had one view for normal terminal size and an additional sidebar for larger windows).

**Comment by torkleyy** [comment]
@memoryruins I think @Aceeri experimented with the Cassowary algorithm. I think it's even in [citrine](https://github.com/amethyst/citrine). Maybe they can contribute something to this discussion.

**Comment by torkleyy** [comment]
It looks quite interesting to me! Let's see what @Xaeroxe and @jojolepro think about it :)

**Comment by Xaeroxe** [comment]
tui looks like what we're going for in general, however I'd prefer a more flexible UI.  Game-dev frequently calls for high-res animated UI images, which it seems tui isn't capable of.  However. I'd definitely be open to examining and lifting some of their code.

**Comment by jojolepro** [comment]
I have already answered a similar question. Basically my point that such a layouting system (Cassowary in particular) would slow down prototyping and would become cumbersome to maintain over time. The constraint + stretch method I went for is maybe less accurate, but is definitely more intuitive, in my opinion.

**Comment by memoryruins** [comment]
Oh, I mentioned the tui crate because it was how I discovered the cassowary crate, and since cassowary makes minimal assumptions on its use case, it should work at any resolution. It's the same algorithm Apple currently uses in the layout engine for Mac OS and iOS.

**Comment by memoryruins** [comment]
I was unaware how much progress had been made on the above UI elements, so if you have something that already works, fantastic! Shared in the case it would save time, but it's great to hear you already experimented with it :)

**Comment by jojolepro** [comment]
Thanks for sharing :)
The big turn off for me with cassowary is this sentence: "It's the same algorithm Apple currently uses in the layout engine for Mac OS and iOS". Since last week I spent 5+ hours making a button list (ios), I don't feel like its a good layouting system for anything not "standard".

**Comment by torkleyy** [comment]
@jojolepro I think we do want some kind of a layouting system. Allowing fast prototyping is important and also needs to be resolved, but I think for more complex UIs we need a full layouting system.

**Comment by jojolepro** [comment]
Just as a precision. I'm not against using a more complex layouting system, but I currently don't see the need to. If we have a dead end or some problem that cannot be solved easily with the current system, I don't mind switching.

**Comment by jojolepro** [comment]
Keeping this here as a note ;)

I'm already working on a thing that automatically updates ui texts based on the id. Both the UiText and the UiTextUpdated will be on the same component, so I will just have a join over both of those. In this specific case the current api design will look like this:

Components
* UiText
* AutoFpsText(component): UiAutoText(trait)

* AutoFpsSystem (FPSCounter resource -> updates AutoFpsText
* AutoTextSystem<T: UiAutoText> (UiAutoText -> updated UiText)

AutoFpsSystem would always run before AutoTextSystem<AutoFpsText>
and both would be in the fps counter bundle.

**Comment by Rhuagh** [comment]
Is this ticket still relevant, or should we ditch it for the work being done under the RFC?

**Comment by jojolepro** [comment]
I guess we don't need it since we have favro tracking the features that need work.

But I think there is things listed here that I forgot to add in favro.

**Comment by Rhuagh** [comment]
Ok, could you create tickets there then, and then remove this?

**Comment by fhaynes** [comment]
Closing this, will remake them with proper priority and such
