### ISSUE TITLE
amethyst_assets hl example does not run as expected

### ISSUE THREAD

**Issue by zoonage** [amethyst/amethyst#609]
# Problem

I cannot run the example in amethyst_assets/examples/hl.rs using the standard `cargo run --example hl` method. If there is an extra bit to this command to get it to run then it is not documented in an obvious location.

# Expected

for the hl example to work like the ll example 
```
aaron@neptune:~/Programming/amethyst/amethyst_assets$ cargo run --example ll --features profile
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `/home/aaron/Programming/amethyst/target/debug/examples/ll`
dummy: Some(DummyAsset(">> Hello World!!\n"))
aaron@neptune:~/Programming/amethyst/amethyst_assets$ 
```

# Example

```aaron@neptune:~/Programming/amethyst/amethyst_assets$ cargo run --example hl
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `/home/aaron/Programming/amethyst/target/debug/examples/hl`
thread '<unnamed>' panicked at 'No resource with the given id', libcore/option.rs:917:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
aaron@neptune:~/Programming/amethyst/amethyst_assets$
 ```

## Edits
Fixed some text inside the first in-line code block

**Comment by torkleyy** [comment]
Thanks for filing the issue!

The error message you're getting means that a system tried to access a resource that doesn't exist in the `World`. [A PR](https://github.com/slide-rs/shred/pull/77) was merged a few hours ago that improves the error message and tries to avoid situations where the error can occur in the first place.

Fixing this issue is pretty straightforward, as far as I can see it's just the `Time` resource missing.

**Comment by jojolepro** [comment]
Bug replicated on my side. I would recommend moving those examples into the main amethyst directory so that travis can check if the examples are compiling.

**Comment by torkleyy** [comment]
They do get checked by this line: https://github.com/amethyst/amethyst/blob/develop/.travis.yml#L49

**Comment by Rhuagh** [comment]
Examples are only compiled, not run, so Travis wouldn't have detected this anyway.

**Comment by zoonage** [comment]
@Rhuagh  was correct,  `world.add_resource(Time::default());` just needed to be added for it to run, however running it doesn't actually do anything, my command prompt just hangs on the 'Running' statement.

What is the expected output from the hl.rs example?

**Comment by zoonage** [comment]
This example has to be run from the root of the amethyst_assets crate as it has to load assets from `examples/assets/`.

```
aaron@neptune:~/Programming/amethyst/amethyst_assets$ cargo run --example hl
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `/home/aaron/Programming/amethyst/target/debug/examples/hl`
Mesh is loaded and the game can begin!
Game ending, sorry
aaron@neptune:~/Programming/amethyst/amethyst_assets$ 
```

Which is the expected outcome

**Comment by zoonage** [comment]
A bit more digging and it turns out that amethyst_assets::Loader will get stuck in an endless loop if it cannot find the asset. Is this an expected / wanted behaviour?

The `State::update` function gets stuck with being in a constant state of `State::Loading`. Something is not handling an error that initially starts at `Source::modified` well enough.

**Comment by torkleyy** [comment]
> Is this an expected / wanted behaviour?

Definitely not.

**Comment by torkleyy** [comment]
But what endless loop are you talking about? I don't see what you mean.

**Comment by Rhuagh** [comment]
If you run the example from the root directory (not the amethyst_assets directory), it fails to load the asset and enters an infinite loop if I understand correctly.

**Comment by zoonage** [comment]
@torkleyy You can see the loop by doing the following; In the hl.rs example insert a print in the function `State::update`
```
            State::Loading(progress) => if progress.is_complete() {
                Some(State::SomethingElse)
            } else {
                // Insert println!
                println!("I'm stuck here");
                Some(State::Loading(progress))
            },
```
