### ISSUE TITLE
Wrong assets get freed

### ISSUE THREAD

**Issue by thepowersgang** [amethyst/amethyst#618]
Ref https://github.com/thepowersgang/fury3clone/blob/master/src/main.rs#L687-L704

When adding multiple entities that use the same model (and material), both `DrawShadedSeparate` and `DrawFlatSeparate` panic with a None unwrap. However, when the original handles to the models and materials are forgotten (using mem::forget of the containing Vec in the above code), the render acts as expect (drawing all models in the world).

**Comment by thepowersgang** [comment]
Reproduction in https://gist.github.com/thepowersgang/6dc88337fc1061650018dcbbf936e785 - Comment out line 111 and the blue triangle doesn't appear.

**Comment by torkleyy** [comment]
Which version of Amethyst are you using? I think I fixed a bug before, could you try using `develop`? Just trying to reproduce this.

**Comment by torkleyy** [comment]
I don't get anything rendered FYI

**Comment by thepowersgang** [comment]
Gist updated to develop (dc9aa963f7d9b362ef711aa3b13eb7c3da55b485), same behavior.

**Comment by torkleyy** [comment]
Thanks, I'll take a look.

**Comment by torkleyy** [comment]
I don't get anything rendered when uncommenting the code. But it doesn't panic either. Does it still panic for you?

**Comment by torkleyy** [comment]
Little update, the asset system is deleting texture handles, that's why it doesn't render. I'll do some more investigation later.

**Comment by torkleyy** [comment]
The bug is somewhere in the garbage collection of the `AssetStorage`. The uniqueness of the handles is

```
[false, false, false, false, false, false, false, false, true, true, true]
```

but 4 elements got freed in that pass.

**Comment by torkleyy** [comment]
I think I just fixed a lot of strange bugs we were getting in the past, please check if it works for you now.
