### ISSUE TITLE
Warn about unnecessary asset loading

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#628]
We could just entirely skip loading an asset when nobody is holding a handle to it.

# Known drawbacks

* when benchmarking asset loading you need to hold the handle, otherwise it doesn't load anything

# Unresolved questions

* should we log this?
* is there anything wrong with just calling `Tracker::success` in such a case?

# Alternatives

* only log a warning, keep loading the asset as usual

**Comment by Xaeroxe** [comment]
I actually think this particular optimization doesn't help a ton.  It complicates the system rules, which makes performance less intuitive, and it only helps in scenarios where users are loading things that they shouldn't be, which shouldn't be a common scenario.  If the user doesn't want that particular asset to load then they simply shouldn't load it.

**Comment by torkleyy** [comment]
I think I have an alternative here. How about we just `warn!` in such a case and continue as usual? Would that be a better solution in your eyes?

**Comment by zoonage** [comment]
Looking into this

**Comment by jojolepro** [comment]
Off topic, but can we actually unload assets?

**Comment by jojolepro** [comment]
Found my answer while reading through my notifications :)

**Comment by zoonage** [comment]
@torkleyy could you clarify what the issue is if the handle is unique?Even if only one existed then it is still a valid handle to an asset, so why would we not want to load it?

I made some changes based off of the the task, however I think I have the wrong end of the stick with this `Handle` thing https://github.com/zoonage/amethyst/commit/b083eded0f2ce1519b2a4b7a3af991b2d310bbf1.

**Comment by zoonage** [comment]
I've put in PR #642 for this (and some profling code that got left out of my last issue) however I've got absolutely no idea how to actually test this change

**Comment by zoonage** [comment]
Are there any docs on how asset loading works? My current understanding is something like

* `World` adds a `Asset` source via the `Loader`
* The `Loader` queries the `AssetStorage`
* The `Loader` runs a task in the `threadpool` to read the requested `Asset` from disk
* The `Loader` returns a `Handle` that corresponds to the asset
* When the `Asset` is queried for there is no guarantee that it has been read yet, but this is visible by some sort of `tracker` that is associated with the `Handle`
* `process_custom_drop` runs in a background thread to update the status of the loading of assets and trigger hot reloads of assets and update the details of the tracker

From this I'm guessing that `process_custom_drop` is the place where we want this check?

**Comment by zoonage** [comment]
For future reference @torkleyy  replied in Gitter

```


    Are there any docs on how asset loading works? My current understanding is something like

        World adds a source via the Loader
        The Loader queries the AssetStorage
        The Loader runs a task in the threadpool to read the requested asset from disk
        The Loader returns a Handle that corresponds to the asset
        When the asset is queried for there is no guarantee that it has been read yet, but this is visible by some sort of tracker that is associated with the Handle
        process_custom_drop runs in a background thread to update the status of the loading of assets and trigger hot reloads of assets and update the details of the tracker

    yes
    the Loader asks the AssetStorage to allocate handles and pushes these handles together with asset data to a processing queue
    exactly, and then it pushes to the queue
    yep, it just clones the one it allocated
    if you call AssetStorage::get it may not exist yet, correct. The Tracker allows to specifially wait for multiple assets before you switch to a new State
    no, it gets called from systems (like AudioSystem, RenderSystem, or generically Processor<Asset>) because assets can require complex initialization with a context (e.g. for meshes you need to have the gfx factory, so the RenderSystem does that)
```

**Comment by zoonage** [comment]
This can be closed now @torkleyy
