### ISSUE TITLE
All examples show a turquoise window

### ISSUE THREAD

**Issue by MrMinimal** [amethyst/amethyst#632]
**Amethyst version:**
0.6.0

**OS/device including version:**
Windows 10
AMD Vega 64 Radeon Software Version 18.3.4

**Issue description:**
Compiling and running the examples with `cargo run` shows the same window as in the attached screenshot.

**Logs:**
```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target\debug\test_game.exe`
Initializing Amethyst...
Version:
Platform: x86_64-pc-windows-msvc
Amethyst git commit:
Rustc version: 1.25.0 Stable
Rustc git commit: 84203cac67e65ca8640b8392348411098c856985
```

![image](https://user-images.githubusercontent.com/8739690/38552962-0fcbbb84-3cbe-11e8-8993-3b0a4d646cfe.png)

**Comment by torkleyy** [comment]
Which version of Amethyst did you clone exactly? Please make sure you're using latest `develop`.

**Comment by MrMinimal** [comment]
With the version from `develop` I get the following. Yet no window is created:

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target\debug\game.exe`
[amethyst::app][INFO] Initializing Amethyst...
[amethyst::app][INFO] Version: v0.5.1-591-gc4a1937
[amethyst::app][INFO] Platform: x86_64-pc-windows-msvc
[amethyst::app][INFO] Amethyst git commit: c4a19375463932652fcabd182c936b721b351c84
[amethyst::app][INFO] Rustc version: 1.25.0 Stable
[amethyst::app][INFO] Rustc git commit: 84203cac67e65ca8640b8392348411098c856985
Begin!
Hello from Amethyst!
End!
[amethyst::app][INFO] Engine is shutting down

```

**Comment by torkleyy** [comment]
Turns out it was some issue with the wrong working directory.

**Comment by MrMinimal** [comment]
Latest version from the `develop` branch works fine. All the examples can be compiled with my setup using `cargo run --example name_of_demo`.

Issue can be closed.
