### ISSUE TITLE
Fly Camera centering mouse without window focus

### ISSUE THREAD

**Issue by Lukazoid** [amethyst/amethyst#635]
This is occurring on Windows 10, I am not sure about other operating systems.

It seems that the `MouseCenterLockSystem` keeps centering the mouse in the window even if the window no longer has focus.

This can be reproduced with the fly_camera example and moving focus away from the window (e.g. with alt-tab).

**Comment by zoonage** [comment]
Verified this on Fedora 26 as well

**Comment by jojolepro** [comment]
The fix is trivial to implement, you only need to read from the event channel of window events and look for this one: https://docs.rs/winit/0.12.0/winit/enum.WindowEvent.html#variant.Focused

**Comment by MrMinimal** [comment]
Almost done with this one, will create PR soon. Only fix that the camera jumps around when the window regains focus.

**Comment by jojolepro** [comment]
On window focus, set mouse position to center immediate.

**Comment by MrMinimal** [comment]
Fixed in #694
