### ISSUE TITLE
[Docs] Animation Tutorial

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#637]
Issue #629 / PR #631 adds documentation to the animation crate and explains the concept. This issue builds on top of that to write a proper tutorial in the book to build up an animation.

The [line in the book](https://github.com/amethyst/amethyst/pull/631/files/3a437ca007c332c12fa7ff7e1f3209197d0f671c#diff-9c47d9908ff5b287d687b6f42cf784b5R5) currently reads:

> Right now we do not have a tutorial for defining an animation from scratch ...

**Comment by highway900** [comment]
Some of the challenges I had using the animation system for sprite animation that would be great to be covered in tutorial/documentation are...

- Initialisation of animations
     * How and why this has probably already been thought about
     * There is probably a few places this could be done. It might help to point this out.
- How should I start my animation?
- How do I transition between 2 animations? 2D+3D
- Current examples as references
     * Most examples key presses are driven from the example state event handler. Though this isn't invalid, it might be a good idea to drive future tutorials with ecs always involved (there might be reasonable counter arguments to this but is something that confused me) only partially related to animation
     * Sprites example which includes animated sprites also has some behaviors that are never used. It seems like it was potentially meant to allow the user to switch between different types of sprite rendering. This is something that would be good to cover.

**Comment by fhaynes** [comment]
Closing this due to age and lack of progress. We'll have to revisit when we rework the tutorials and book.
