### ISSUE TITLE
Will amethyst support scripting languages? (c#)

### ISSUE THREAD

**Issue by srxqds** [amethyst/amethyst#647]
hi, Do it may host c# or other script language?
If we support c# (hosting .net coreclr) or other script language, it can make developing more efficient because the c# has more simple syntax and more useful sugar and can built fast!

**Comment by torkleyy** [comment]
I don't like C# but I do think that we can make it work rather easily. But
beyond that, I don't think we should support it as a first-class language,
or at least I won't.

**Comment by Xaeroxe** [comment]
I actually disagree with my peers a bit and I think C# should be one of our priorities to get working with the engine as there is a rather large knowledge base for it.  The similarities it has to Java also make it pretty easy for Java devs to pick up, which is another huge block of coders.

Now that being said, scripting support is a bit of a ways off.  It's definitely on the roadmap though.

**Comment by jojolepro** [comment]
We'd need to support .net core clr and that would allow us to support vb c# f# all at once.

**Comment by OvermindDL1** [comment]
The issue with .NET core is the license, mono is better, though I'm not a fan of GC'd anything being in a game engine, even as a scripting language, luajit was even a pain with that at times and it's memory is very segmented (I.E. fast to collect, unlike mono/.NET)...

**Comment by srxqds** [comment]
If amethyst support c# ( strong type language) ,it can make inspect object easy like unity editor.

**Comment by srxqds** [comment]
And amethyst has plan of WYSWYG editor like unity support?

**Comment by jojolepro** [comment]
Yes

**Comment by JohnDoneth** [comment]
I think [rhai](https://github.com/jonathandturner/rhai) or [rlua](https://github.com/chucklefish/rlua) would be easier to integrate than C#. 

I am biased towards rhai as it's a all in one rusty package although not yet proven.

**Comment by RUSshy** [comment]
lua is shit and slow, consider D/Kotlin Native/C#

**Comment by jojolepro** [comment]
We plan on having a compatibility layer that allows supporting most if not all scripting languages. It is called "vnodes", if you are interested.

**Comment by Xaeroxe** [comment]
@RUSshy I'm deleting your comment because out there in the world is someone who feels the same way about another scripting language.  Opinions don't further the discussion.  Please provide more substantial reasoning if you'd like us to consider dropping Lua.

**Comment by torkleyy** [comment]
To expand on @Xaeroxe's comment, we respect your opinion on Lua, but we're asking you to tell it without offending anybody else next time.

Side note: @Moxinilian @jojolepro you might want to make our code of conduct official by uploading a such a document (probably just copy it from Rust).

**Comment by hydroper** [comment]
C# has recently added  `ref` params and locals and null things just like Swift. It's ofc a great language. The only bad part is reflection and `dynamic` property lookup, but anyway any Java-like language has it, so do whats...?

**Comment by erlend-sh** [comment]
Discussion for scripting support is continued here: 
https://github.com/amethyst/rfcs/pull/1
