### ISSUE TITLE
Foliage Support

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#654]
Depends on BillBoard #651 

Features:
- [ ] "Grass" like batched objects
- [ ] Instanced objects
- [ ] Billboard & 3D world & 2D world Modes
- [ ] Wind effects + wind zones
- [ ] LOD Support

**Comment by fhaynes** [comment]
Tracking this is an epic here: https://openproject.amethyst-engine.org/projects/engine/work_packages/77/activity

**Comment by fhaynes** [comment]
Closing this due to age and lack of interest. These can go on the roadmap if there is demand for them later.
