### ISSUE TITLE
Shared System Components

### ISSUE THREAD

**Issue by huhlig** [amethyst/amethyst#668]
Per a discussion on amethyst/general on Gitter. I am opening this RFC in regards to shared system components at the application level. Right now there is one thread safe system component for handling assets. I purpose abstracting this concept for arbitrary system components and adding several default implementations for common needs. Some of the basic shared thread safe system components include: 
* AssetManager (a port of the existing code into the new api) 
* NetworkManager (Owner of the actual TCP Handle, packager of messages, and channel publisher)
* RenderManager (responsible for managing root rendering context, I.E. Making opengl calls single threaded, owning a vulkan instance, creating ECS System Render Pipelines, etc) 
* StorageManager (Owner of things like a SQLite database handle, responsible for providing uncontested file handles to systems)

These systems would provide thread safe APIs accessable both by the State and ECS Systems. 

This is part of a larger suggestion to allow dynamic swapping of game logic, systems, render logic, and ecs/resource data based on state or arbitrarily within a state. This flexibility can be exceptionally useful when building games with a sandwich architecture where scripts external to the core rust code can mutate how a game operates. I.E. a script can tell the engine to swap states to a minigame with a different rendering pipeline.

**Comment by jojolepro** [comment]
>StorageManager (Owner of things like a SQLite database handle, responsible for providing uncontested file handles to systems)

This is not something that is planned to be part of the engine. (Though I understand its just an example.


You can already have `State` specific `System`, as well as `State` specific `Resource`s.
https://github.com/jojolepro/world-digger/blob/master/src/main.rs#L255 and https://github.com/jojolepro/world-digger/blob/master/src/main.rs#L435

**Comment by Rhuagh** [comment]
We discussed this some more and most of this looks like resources to me, probably used as the authoritative source of context /configuration type data by some system that drives that part of the engine.

That way both state and systems can interact with them with minimal overhead. 

We do have a lot of things that will improve this planned, but no eta (spare time eh).

**Comment by jojolepro** [comment]
I don't think we have a roadmap at all. Linux philosophy eh?

**Comment by Rhuagh** [comment]
We all have our individual roadmaps I sure, don't think we an updated feature list though.

**Comment by OvermindDL1** [comment]
The Projects tab in github here is specifically for roadmaps (and linking issues and PR's to them).

**Comment by jojolepro** [comment]
We now support state specific systems and worlds through the usage of GameData (and just adding a dispatcher into the state's field. 

For this reason, I'm closing this issue.
