### ISSUE TITLE
Audio does not take the time multiplier into account.

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#669]
The audio system should change the audio playing speed of rodio depending on the time scale in the Time resource.
It should be configurable (disable/enable time scaling on a per sink basis)

**Comment by Xaeroxe** [comment]
This feature would likely result in hilarious "chipmunk" sfx.

So of course I'm all for it :P

**Comment by jojolepro** [comment]
You could create a pink unicorn sound and make the pitch awfully low when they attack you :P

**Comment by Rhuagh** [comment]
Time scale != pitch, but would be hilarious anyways :P

**Comment by jojolepro** [comment]
Actually yes because you are effectively changing the frequency of the sound by accelerating it.

**Comment by Xaeroxe** [comment]
@Rhuagh Time scale can be adjusted independent of pitch, but it requires a more advanced analysis of the sound samples to preserve the wavelengths produced.  You can't just haphazardly omit samples every X samples, you have to actually analyze the waves produced.

**Comment by OvermindDL1** [comment]
Technically the pitch should be adjusted with the time, that is how it works in the real world after all.  ^.^

**Comment by magnonellie** [comment]
So I was thinking of taking this one but I noticed that `Output` doesn't actually have access to the time scale. Should the different functions take a `time_scale: Option<f32>` parameter or something like that?

**Comment by jojolepro** [comment]
https://github.com/amethyst/amethyst/blob/develop/amethyst_audio/src/systems/audio.rs. you can add time to this system and then do the things you need to do so that the audio frames are played faster or slower. Either make it actually play faster, or compress the frames.

**Comment by Xaeroxe** [comment]
This is actually a rather complex issue involving multi-threaded communication channels so I'm removing the good first issue recommendation.

**Comment by fhaynes** [comment]
Closing this due to age and lack of progress. If there is interest, we'll put it on the roadmap.
