### ISSUE TITLE
CI builds on nightly keep failing

### ISSUE THREAD

**Issue by frazar** [amethyst/amethyst#678]
The CI builds for the last PRs have been failing consistently in nightly, both on [Travis](https://travis-ci.org/amethyst/amethyst/builds/372372920?utm_source=github_status&utm_medium=notification) and [AppVeyor](https://ci.appveyor.com/project/amethyst/amethyst/build/1.0.1923).

The reason is that the following command fails on nightly
```
$ cargo test --all --features profiler -v 
error: cannot specify features for more than one package
```

I think this is due to a recent change ([here](internals.rust-lang.org) you can see the internals.rust-lang.org announcement) in how the `--features` flag works.
In particular, from [this](https://internals.rust-lang.org/t/help-us-test-the-breaking-bug-fix-to-cargo-features/7317/11?u=frazar) comment it appears that using `--features` and `--all` together is not allowed anymore.

The simplest solution I can think of is chaning the build scripts to compile each of the `amethyst-*` crates with separate commands, specifying the `--features` flag. However, it's not very elegant.

Any suggestion on how to fix this in a better way?

**Comment by derekdreery** [comment]
I've submitted #682 as an example of one way to fix this.

**Comment by frazar** [comment]
The change in how nightly handles the `--features` flag has been [reverted](https://github.com/rust-lang/cargo/pull/5430).

**Comment by torkleyy** [comment]
I deleted the cache for `develop`, it should work now.

**Comment by frazar** [comment]
Yes, the latest CI builds on nightly are running fine (e.g. [this one](https://travis-ci.org/amethyst/amethyst/jobs/375056056)). Closing the issue.
