### ISSUE TITLE
amethyst_animation::util::get_animation_set panics if Entity is dead.

### ISSUE THREAD

**Issue by Xaeroxe** [amethyst/amethyst#686]
See this: https://github.com/amethyst/amethyst/pull/684/files/8696588889e44cc42f8b5e0e851d3ce9f8557df3#r185024799

for more detail.

**Comment by torkleyy** [comment]
I'm adding this issue for first-time contributors. Here's a more detailed description of the issue:

The following function is using an `unwrap` on the `Result` of `entry`. In case the Entity is dead, the result is an error and the unwrap will make the function panic.

https://github.com/amethyst/amethyst/blob/6484af2a97e7700d6c86f097bf8d5a7caa8414eb/amethyst_animation/src/util.rs#L15-L27

Your task is to evaluate whether the function should return an `Option` or a `Result` and replace the unwrap accordingly. If you're interested in fixing this issue or you need help with something, please comment here.

There's a rough overview of the animation crate available [in our book](https://www.amethyst.rs/book/develop/book/index.html).

**Comment by hashedone** [comment]
I don't think, that returning `Result` makes sense here, as long, as only information available in `Err` is `actual_gen`. Am I right?

**Comment by Xaeroxe** [comment]
It's the only information we have and I don't see much harm in returning a Result

**Comment by hashedone** [comment]
I made a correction and submitted pull request for this.
