### ISSUE TITLE
Crash on example startup with X11

### ISSUE THREAD

**Issue by MrMinimal** [amethyst/amethyst#707]
## Kind of bug

* [x] Crash
* [ ] Nothing happens
* [ ] Instability
* [ ] Wrong behavior (please specify the expected behavior)
* [ ] Other (describe below)

## Error message with stack trace (if relevant)

<details><summary>Click to expand</summary>
<pre><code>
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fba5033f801 in __GI_abort () at abort.c:79
#2  0x00007fba5032f39a in __assert_fail_base (fmt=0x7fba504b67d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7fba4d776660 "!xcb_xlib_threads_sequence_lost", 
    file=file@entry=0x7fba4d7764cb "../../src/xcb_io.c", line=line@entry=259, function=function@entry=0x7fba4d776908 "poll_for_event") at assert.c:92
#3  0x00007fba5032f412 in __GI___assert_fail (assertion=0x7fba4d776660 "!xcb_xlib_threads_sequence_lost", file=0x7fba4d7764cb "../../src/xcb_io.c", line=259, 
    function=0x7fba4d776908 "poll_for_event") at assert.c:101
#4  0x00007fba4d7041da in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x00007fba4d70428b in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#6  0x00007fba4d70457d in _XEventsQueued () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007fba4d7073c5 in _XGetRequest () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007fba4d7074df in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#9  0x00007fba4d706ca3 in _XError () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#10 0x00007fba4b970482 in ?? () from /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#11 0x00007fba4b96c694 in ?? () from /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#12 0x00007fba4b99e078 in ?? () from /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0
#13 0x00005622f3973ce9 in glutin::api::glx::ffi::glx_extra::Glx::CreateContextAttribsARB (self=0x7ffd9407f398, dpy=0x7fba4f4f0000, config=0x7fba4f561120, share_context=0x0, direct=1, 
    attrib_list=0x7fba4f554a70) at /home/tom/Dev/Rust/amethystMrMinimal/target/debug/build/glutin-9c0363fde75d28a7/out/glx_extra_bindings.rs:528
#14 0x00005622f3967d5c in glutin::api::glx::create_context (glx=0x7ffd94085d68, extra_functions=0x7ffd9407f398, extensions=..., xlib=0x7fba4f515010, version=..., profile=..., debug=true, 
    robustness=glutin::Robustness::NotRobust, share=0x0, display=0x7fba4f4f0000, fb_config=0x7fba4f561120, visual_infos=0x7ffd94086010)
    at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.15.0/src/api/glx/mod.rs:375
#15 0x00005622f3966c4c in glutin::api::glx::ContextPrototype::finish (self=..., window=39845893)
    at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.15.0/src/api/glx/mod.rs:210
#16 0x00005622f39705ac in glutin::platform::platform::x11::Context::new (window_builder=..., events_loop=0x7ffd94096db8, pf_reqs=0x7ffd940891c0, gl_attr=0x7ffd94088cd0)
    at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.15.0/src/platform/linux/x11.rs:215
#17 0x00005622f3959918 in glutin::platform::platform::Context::new (window_builder=..., events_loop=0x7ffd94096db8, pf_reqs=0x7ffd940891c0, gl_attr=0x7ffd940891f8)
    at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.15.0/src/platform/linux/mod.rs:58
#18 0x00005622f3964404 in glutin::GlWindow::new (window_builder=..., context_builder=..., events_loop=0x7ffd94096db8)
    at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.15.0/src/lib.rs:313
#19 0x00005622f391f8e4 in gfx_window_glutin::init_raw (window=..., context=..., events_loop=0x7ffd94096db8, color_format=..., ds_format=...)
    at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_window_glutin-0.23.0/src/lib.rs:144
#20 0x00005622f38985cb in gfx_window_glutin::init (window=..., context=..., events_loop=0x7ffd94096db8)
    at /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_window_glutin-0.23.0/src/lib.rs:67
#21 0x00005622f38494e5 in amethyst_renderer::renderer::init_backend (wb=..., el=0x7ffd94096db8, config=0x7ffd94096d70) at amethyst_renderer/src/renderer.rs:286
#22 0x00005622f3848b92 in amethyst_renderer::renderer::RendererBuilder::build (self=...) at amethyst_renderer/src/renderer.rs:200
#23 0x00005622f33ffe6b in <amethyst_renderer::system::RenderSystem<P>>::build (pipe=..., config=...) at /home/tom/Dev/Rust/amethystMrMinimal/amethyst_renderer/src/system.rs:53
#24 0x00005622f348cc8c in <amethyst_renderer::bundle::RenderBundle<'c, B, P> as amethyst_core::bundle::SystemBundle<'a, 'b>>::build (self=..., builder=0x7ffd940a5100)
    at /home/tom/Dev/Rust/amethystMrMinimal/amethyst_renderer/src/bundle.rs:62
#25 0x00005622f34abac8 in <amethyst::app::ApplicationBuilder<'a, 'b, T>>::with_bundle (self=..., bundle=...) at /home/tom/Dev/Rust/amethystMrMinimal/src/app.rs:669
#26 0x00005622f33b6dd8 in gltf::run () at examples/gltf/main.rs:159
#27 0x00005622f33b8564 in gltf::main () at examples/gltf/main.rs:185

</code></pre>
</details>

## Logging output including initialization output

<details><summary>Click to see platform and versions</summary>
<pre><code>

    Finished dev [unoptimized + debuginfo] target(s) in 0.23s
     Running `target/debug/examples/fly_camera`
[amethyst::app][INFO] Initializing Amethyst...
[amethyst::app][INFO] Version: v0.5.1-723-g3c9e8e7
[amethyst::app][INFO] Platform: x86_64-unknown-linux-gnu
[amethyst::app][INFO] Amethyst git commit: 3c9e8e779830cdf95f47dd2224eb861a6654f5e6
[amethyst::app][INFO] Rustc version: 1.27.0-nightly Nightly
[amethyst::app][INFO] Rustc git commit: 428ea5f6b9e7c6e5ee3294fe9f105e77e89ab407
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
fly_camera: ../../src/xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)

</code></pre>
</details>

<details><summary>Click to see logging output</summary>
<pre><code>

    Finished dev [unoptimized + debuginfo] target(s) in 0.23s
     Running `target/debug/examples/fly_camera`
[amethyst::app][INFO] Initializing Amethyst...
[amethyst::app][INFO] Version: v0.5.1-723-g3c9e8e7
[amethyst::app][INFO] Platform: x86_64-unknown-linux-gnu
[amethyst::app][INFO] Amethyst git commit: 3c9e8e779830cdf95f47dd2224eb861a6654f5e6
[amethyst::app][INFO] Rustc version: 1.27.0-nightly Nightly
[amethyst::app][INFO] Rustc git commit: 428ea5f6b9e7c6e5ee3294fe9f105e77e89ab407
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
fly_camera: ../../src/xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)

</code></pre>
</details>

## Reproduction

* [x] I have used the following example from this repository: gltf, fly_camera, sphere, window
* [ ] You can find my code here:
* [ ] I'm currently creating a minimal example for reproduction
* [ ] A reproduction is not necessary because I know the source of the bug

### Reproduction steps

1. Launch the project with `cargo run --example gltf` multiple times
2. might get this error on startup

## Source of the bug

* [ ] The bug is triggered by the following line (please use a permalink):
* [x] I suspect the bug is located in the following crate: amethyst_renderer

**Comment by jojolepro** [comment]
Can you try to run the window and sphere examples please?

**Comment by MrMinimal** [comment]
@jojolepro I ran both, same result. Sometimes they work, sometimes they crash on startup.

**Comment by Rhuagh** [comment]
Sounds like a race condition in mesa initialisation.

**Comment by Rhuagh** [comment]
Well this is failing on an assertion far down in Mesa during initialisation of the gl context. Without more information this will be quite difficult to find :/ I suspect the glutin or winit crates are likely culprits here.

**Comment by azriel91** [comment]
I think this is the same issue as https://github.com/tomaka/winit/issues/458

**Comment by torkleyy** [comment]
This seems to be fixed now, so we just need to use that patch now.

**Comment by Rhuagh** [comment]
It's released as 0.15.1, so I believe we would be already with a cargo update?

**Comment by torkleyy** [comment]
Correct.
