### ISSUE TITLE
Improve CI setup

### ISSUE THREAD

**Issue by Rhuagh** [amethyst/amethyst#708]
It feels very unnecessary that we build and run the project multiple times when all that was updated was the book, or other .md files, or such. If we could find a way to avoid that, that would save us some considerable amount of CI time, and since we can only run one job at a time, this should also alleviate the pressure somewhat.

**Comment by torkleyy** [comment]
In general it would be good if Travis caches actually worked.

**Comment by Rhuagh** [comment]
We should move over to travis-ci.com, and we should start using the Travis CI Github Apps integration.

More information can be found here:

* https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
* https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

**Comment by torkleyy** [comment]
I can do this.

**Comment by torkleyy** [comment]
They're still in the process of shifting projects; existing projects will migrate to .com later.

**Comment by Rhuagh** [comment]
We can start using the google apps integration directly though I think?

**Comment by torkleyy** [comment]
google apps?

**Comment by torkleyy** [comment]
Closing since CI has been reworked in #1047
