### ISSUE TITLE
The book should use the inclusion syntax for its examples

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#714]
We can use

```text
{{#include file.rs:2:10}}
```

to include the code from our examples in the book, so we don't need to duplicate everything.

**Comment by torkleyy** [comment]
http://rust-lang-nursery.github.io/mdBook/format/mdbook.html#including-files

**Comment by Rhuagh** [comment]
Ah, cool. Sounds excellent, then we get testing on it aswell.

**Comment by Xaeroxe** [comment]
I'm not sure including arbitrary line numbers is a good idea.  It's really easy to have these offset by simple PR changes such as formatting or otherwise.  It could become so difficult to maintain correctly that duplication might be preferable.

**Comment by torkleyy** [comment]
@Xaeroxe Yeah, I realized that, too.

**Comment by Xaeroxe** [comment]
So, after having realized that do you still feel this is a good solution?

**Comment by torkleyy** [comment]
At least for the complete examples where we don't need lines, this does makes sense.

**Comment by torkleyy** [comment]
Like I think every pong chapter has them at the end, so we can do it for those.

**Comment by Moxinilian** [comment]
I'm not sure this is a good idea either. The representation in the repo always contains additional details to make it work in the context of the repo, most notably the assets path.

**Comment by jojolepro** [comment]
So @Moxinilian ended up making the examples compile in the book. The code is still a duplicate, but it is more versatile like this.
