### ISSUE TITLE
Material example is simply black with some setups

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#734]
## Kind of bug

* Nothing happens (/ nothing gets rendered)

## Logging output including initialization output

<details><summary>Click to see platform and versions</summary>
<pre><code>

[Paste your initialization output here]

</code></pre>
</details>

<details><summary>Click to see logging output</summary>
<pre><code>

[Paste important sections of your logging output]

</code></pre>
</details>

## Reproduction

* I have used the following example from this repository: `material`

### Reproduction steps

1. Launch the example with `cargo run --example material`
2. The screen doesn't show any spheres

### Screenshot (expected behavior)

![screenshot from 2018-05-19 06-13-28](https://user-images.githubusercontent.com/23152057/40264912-1eafe11e-5b2e-11e8-803d-0b3ffb96b1c5.png)

## Source of the bug

* I suspect the bug is located in the following Amethyst module: `amethyst_renderer`

---

I left out some sections because I could not reproduce the issue.

cc @karroffel

**Comment by torkleyy** [comment]
Could not reproduce on my Linux machine:

```
[amethyst::app][INFO] Initializing Amethyst...
[amethyst::app][INFO] Version: v0.5.1-791-g78b83a8
[amethyst::app][INFO] Platform: x86_64-unknown-linux-gnu
[amethyst::app][INFO] Amethyst git commit: 78b83a860505349402a2c9dc4f4c5b6896a11cf7
[amethyst::app][INFO] Rustc version: 1.27.0-nightly Nightly
[amethyst::app][INFO] Rustc git commit: 2f2a11dfc436fc0f401b595f22ed043c46dbebe7
```

* Graphics: Intel® HD Graphics 620 (Kaby Lake GT2)
* Driver: Mesa 17.2.8

(we should include those things in the log, too)

**Comment by karroffel** [comment]
I am away for the weekend but maybe I can test this on my laptop. I'll definitely post more information at a later point

**Comment by karroffel** [comment]
I can't reproduce the issue anymore, it works fine now. :+1:
