### ISSUE TITLE
ui example did not compile

### ISSUE THREAD

**Issue by adals** [amethyst/amethyst#735]
Win8:amethyst $ cargo run --example ui
   Compiling coreaudio-sys v0.2.0
   Compiling gfx_core v0.8.2
   Compiling amethyst_config v0.6.0 (file:///Users/Codes/Rust/amethyst/amethyst_config)
   Compiling gltf-json v0.9.3
   Compiling amethyst_core v0.2.0 (file:///Users/Codes/Rust/amethyst/amethyst_core)
error: failed to run custom build command for `coreaudio-sys v0.2.0`
process didn't exit successfully: `/Users/Codes/Rust/amethyst/target/debug/build/coreaudio-sys-9464e1141b65e0d9/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=framework=AudioUnit
cargo:rustc-link-lib=framework=CoreAudio

--- stderr
error: header '/System/Library/Frameworks/CoreAudio.framework/Headers/CoreAudio.h' does not exist.
thread 'main' panicked at 'unable to generate bindings: ()', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Rhuagh** [comment]
Known issue, there's a workaround described in the Readme.

**Comment by torkleyy** [comment]
Hello @adals!

Sorry for the inconvenience, we currently need to use a workaround because the maintainer of `coreaudio-sys` did not release a new version yet and the old one is broken.

Please paste this into your `Cargo.toml`:

```
[patch.crates-io]
coreaudio-sys = { git = "https://github.com/RustAudio/coreaudio-sys.git", rev = "cf3a8321f461655a304ee8aa3139d5c5c88fd379" }
```

**Comment by torkleyy** [comment]
@Rhuagh I think the README should clarify that this is not only needed on OS X. For some reason it works fine for me though.

**Comment by Rhuagh** [comment]
It should only be needed when target os is macos or ios.

https://github.com/tomaka/cpal/blob/20fffb26fb9150ed8e1a19d3eafbf608dffa3480/Cargo.toml#L24

**Comment by adals** [comment]
thank you all it works right now
