### ISSUE TITLE
Add motivation for using Amethyst over "gluing the building blocks"

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#737]
Request by @boscop 

> It would be nice to have an overview in the introduction for when to use Amethyst instead of just combining crates for physics, networking, rendering etc. (when one doesn't need a ECS).

**Comment by erlend-sh** [comment]
Some relevant discussion points here:

https://users.rust-lang.org/t/ecs-with-specs-for-turn-based-game/17483?u=erlend_sh
