### ISSUE TITLE
InputBundle loading does not allow for checking for success

### ISSUE THREAD

**Issue by Alex-Addy** [amethyst/amethyst#742]
With `InputBundle::<String, String>::new().with_bindings_from_file(&binding_path)` there is no way to check if the load succeeded or not. This ends up meaning that my program will go on without any key bindings with no indicators besides a single line in the logs.

This made for an unpleasant experience while following the tutorial as I had mistyped `Up` as `up` in my `.ron` file and couldn't didn't see the log message.

It would be great if `with_bindings_from_file` returned a result and let the program handle it instead of using the default empty bindings.

For a more reliable startup I ended up going with:
```rust
let bindings = Bindings::load_no_fallback::<&str>(binding_path)
        .map_err(|e| amethyst::Error::Config(e))?;
let input_bundle = InputBundle::<String, String>::new().with_bindings(bindings);
```

On another note it might be nice if `amethyst::Error` implemented `From<ConfigError>`, should I make an issue for that?

**Comment by torkleyy** [comment]
> On another note it might be nice if amethyst::Error implemented From<ConfigError>, should I make an issue for that?

or a PR, yes :)

**Comment by torkleyy** [comment]
Yes, the `with_bindings` function should simply return an error so you can decide yourself what to do with it.

@Xaeroxe This requires a bit more than changing the return type, we need to change `amethyst_config` for this.

**Comment by Xaeroxe** [comment]
Stalled on merging of https://github.com/amethyst/amethyst/pull/690

**Comment by Alex-Addy** [comment]
Why would that stall this? Is there more to this than just propagating the `ConfigError` from `load_no_fallback` through `with_bindings_from_file`?

**Comment by Rhuagh** [comment]
We're completely changing the Error structure, so this will be affected.

**Comment by mnivoliez** [comment]
I'll take this one ^^

**Comment by mnivoliez** [comment]
Sadly, I have tried to manage that issue, but time is becoming a rare currency for me. If I found time, I'll get back to it, but I can't assure it will be anytime soon. Sorry for having this long before saying it.
