### ISSUE TITLE
Alpha cutoff in the PBR shader

### ISSUE THREAD

**Issue by Rhuagh** [amethyst/amethyst#747]
GLTF specifies that you need to support 3 blend modes:

* Opaque - fully opaque (we support this already)
* Blend - Normal blend operation (we support this already)
* Mask - based on alpha cutoff a pixel is either completely opaque or transparent.

To support the last case we need to add a cutoff parameter to the PBR shader, which is checked against the alpha of the albedo, and rejects the pixel if the alpha is below the cutoff. We can default this cutoff to 0, which should make it work for all situations.

For a use case, this is commonly used for things like wire fences and tree leaves.

**Comment by Xaeroxe** [comment]
A cutoff of `0.01` sounds preferable to me actually, that way we don't have to deal with float equality non-sense.  1% visible is basically invisible anyways.

**Comment by mnivoliez** [comment]
As previously asked on the gitter,I take this issue, unless someone disprove.

**Comment by Rhuagh** [comment]
Ok, so this is actually more complicated than what I thought based on a first runthrough of the gltf spec.

pseudo code for what we want:
```
let alpha = if alpha < cutoff {
    0.0 
} else {
    1.0
}
```

**Comment by mnivoliez** [comment]
should it not be more like
```
let alpha = if alpha < cutoff {
    0.0 
} else {
    alpha
}
```

**Comment by Rhuagh** [comment]
No, for `Mask` its either full on or off, but we can control that by not setting `Transparent` on the `Entity`, and using cutoff for complete discard.

**Comment by Rhuagh** [comment]
This has been fixed.

**Comment by torkleyy** [comment]
Hah, I just wanted to address this :sweat_smile:
