### ISSUE TITLE
Multi stage prefab loading and progress

### ISSUE THREAD

**Issue by Rhuagh** [amethyst/amethyst#750]
After having experimented a bit with my new prefab loading system, I've noticed a side effect that I'll have to deal with somehow. 

If you look at the Gltf example in the PR, it will load the scene definition from a Ron file, which contains a link to a Gltf file to load. This is what I'd call sub asset load. The basic issue with this is that the scene prefab will load first, create some entities (like the lights etc), then the gltf load will kick off, which takes a few frames to complete, and then that prefab load will create some more entities, and eventually the meshes and textures will load somewhere at the end and it will turn up on screen.

The core issue with this is that you might have systems processing entities before they're actually visible to the player, which is unacceptable. To remove this issue I will need to introduce a prepass on prefab loading that spawns the sub loads for things that need to be created before the entities are created (like meshes, textures etc). 

For this to work I need to add a way for the asset loading processor systems to tell the asset system that an asset is in a waiting state, and needs to be reprocessed next frame (and next, and next, until the subloads have completed). 

To do this, I need to change the signature of the `process` function on `AssetStorage`. My question to you all is, how should I change it? My current option is `FnMut(A::Data) -> Result<Option<A>>`. A second option would be to create our own enum that have something like `Loading`, `Done(value)`. What do you think?

**Comment by Rhuagh** [comment]
@Xaeroxe @torkleyy @jojolepro

**Comment by Xaeroxe** [comment]
I like the first option personally

**Comment by Rhuagh** [comment]
Hrmpf, can't use the first option because of move semantics, need to return the data from the process function for "not fully loaded yet".

**Comment by omni-viral** [comment]
> systems processing entities before they're actually visible to the player, which is unacceptable.

But sometimes desirable

**Comment by jojolepro** [comment]
Okay, so what is actually possible to do with the current implementation is to have a second dispatcher containing the systems that need to operate on the loaded entities. You have a ProgressCounter, and you only update that dispatched once the prefab is done loading.

The other way of doing it is to add a "Loading" tag component over the entities being loaded by the prefab system, and to remove it at the end.

**Comment by OvermindDL1** [comment]
> The other way of doing it is to add a "Loading" tag component over the entities being loaded by the prefab system, and to remove it at the end.

What I always did with my assets, whether a texture or a model or so is that the entity would have something like a `Textures` component with a list of texture ID's it needs (atom64's on my engine but strings work fine if you don't mind heap allocation, I tried to eradicate heap allocation so I could just memcpy my component tables for storage), then the AssetLoader systems (various template CRTP's for things like Textures and other things) would work through those to load assets, on first access it added the handle component to the resources on the entity if needed (usually not, the renderer handled that) with a default value initially (a purple/white checkberbox texture, a cube mesh, etc... though another component could define a different 'loading' asset if it was already loaded else ignored) that was then updated to the actual value later.  The rendering systems wouldn't care about things like Textures components, just things like AssetTextures and so forth.  Streaming loading was conveniently easy though.

**Comment by torkleyy** [comment]
Seems to be fixed by #716, as noted by @Rhuagh on Discord.

**Comment by jojolepro** [comment]
There is still system dependencies to add in the examples from what I understood.

**Comment by Rhuagh** [comment]
System dependencies are correct in both examples and docs. This issue is completed.
