### ISSUE TITLE
Error because of missing default font used by UiButtonBuilder::new()

### ISSUE THREAD

**Issue by bakamomi** [amethyst/amethyst#761]
This is a minor issue, but UiButtonBuilder::new() is using DEFAULT_FONT_NAME: &'static str = "font/square.ttf" if it doesn't exist, you get an error in stdin. But it doesn't matter because you can set a new font later .with_font. So, there should be some way to suppress the error in stdin or set the font before Builder tries to use DEFAULT_FONT_NAME.

**Comment by Rhuagh** [comment]
I will probably refactor the button builder majorly in a few days. I want all the loading to be done in a single call, not spread into two separate locations.

**Comment by minecrawler** [comment]
Just an idea and a thing I have been missing, but: Would it be a good idea to use a default system font if no font is specified, throwing a warning in the process? That might be good for quick prototyping, though it would require a cross-platform way to access system fonts and some good defaults might have to be specified (like Arial, Helvetica, Segoe UI, Roboto, etc.).

It might be added in a new crate, which might base its code on [this](https://github.com/foliojs/font-manager/tree/master/src) C++ code.

**Comment by Moxinilian** [comment]
@Rhuagh Did your refactor happen? If so, did it fix this?

**Comment by Moxinilian** [comment]
Comic Sans as a default font would be ideal
