### ISSUE TITLE
Wrong? ChannelType of Color attribute of vertices

### ISSUE THREAD

**Issue by bakamomi** [amethyst/amethyst#763]
https://github.com/amethyst/amethyst/blob/d54806bf4f6c0b85a55436c0d006add120b68953/amethyst_renderer/src/vertex.rs#L45
All other attributes use ChannelType::Float, only this uses Unorm and it doesn't work in fragment shader if you set gl_Color = color_attribute.
Changing to ChannelType::Float fixed the issue with my fragment shader, but I'm not sure whether I'm just doing something wrong in the fragment shader or it's "Unorm" that is wrong.

**Comment by msiglreith** [comment]
Most probably Float is correct. It seems very unlikely to me that the color attributes are encoded as unorms

**Comment by Xaeroxe** [comment]
It's kind of amazing we got by with such a significant error for so long.  I'm opening a PR to correct this now.
