### ISSUE TITLE
UI example doesn't render images

### ISSUE THREAD

**Issue by lukebitts** [amethyst/amethyst#765]
I ran the UI example on my machine and this is what I got:

![ui_example_error](https://user-images.githubusercontent.com/606788/40897898-4126fc9c-6794-11e8-92d1-1d319e363e5a.png)

I'm not sure what info is relevant for debugging this, but let me know and I will provide.

**Comment by Xaeroxe** [comment]
Reproduced, investigating now.

**Comment by Xaeroxe** [comment]
amethyst_ui 0.2.1 fixes this, please run `cargo update` if you're still experiencing this issue.

**Comment by lukebitts** [comment]
Confirming it fixed my issue, thanks!
