### ISSUE TITLE
Single frame animation breaks animation state

### ISSUE THREAD

**Issue by Rhuagh** [amethyst/amethyst#781]
Something breaks on starting single frame animations. Not sure what, but the state after ending the animation is broken somehow, probably due to an incorrect `RestState` being created somewhere.

**Comment by marciusvinicius** [comment]
Hey @Rhuagh can you share an example of your implementation?

**Comment by marciusvinicius** [comment]
Thanks, @Rhuagh, I'm looking on the issue #938 now, As soon as I finish that I can try to get this one in case of no one get.

**Comment by mh84** [comment]
I will have a look into this one.

**Comment by marciusvinicius** [comment]
Thanks @mh84  I didn't do much on this, I will take a look on your code to learn something :D
