### ISSUE TITLE
Need a simple 3d rendering example

### ISSUE THREAD

**Issue by ahmedaliadeel** [amethyst/amethyst#79]
Need a simple 3d rendering example, like a cube or sphere, nothing fancy.  Deferred or Forward defined in yaml file.

**Comment by Emilgardis** [comment]
There already is one. On the develop branch: https://github.com/amethyst/amethyst/blob/develop/src/renderer/examples/main.rs

**Comment by ahmedaliadeel** [comment]
Got that working but was wondering how to fit in the main window example with ecs. Anyway thanks I will see into this tonight.

![untitled](https://cloud.githubusercontent.com/assets/6824526/17083057/a7ff9318-519b-11e6-85fb-044f3bb16404.png)

**Comment by ahmedaliadeel** [comment]
I mean i need an example without directly using glutin or gfx through amethyst interface! is something is WIP?

**Comment by nchashch** [comment]
There is no example with rendering yet, but you might want to take a look at #80.

**Comment by nchashch** [comment]
see `examples/sphere.rs` in #80.

**Comment by ebkalderon** [comment]
Given that we have a working rendering example, I think we can mark this issue resolved
