### ISSUE TITLE
Allow placing text in the 3D world

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#792]
We have text rendering for UI, but text is also useful inside the 3D world to label arrows, entities, etc.

**Comment by Xaeroxe** [comment]
Do we want something like this: 
![image](https://user-images.githubusercontent.com/6182002/41419749-07596fbc-6fb0-11e8-9b6e-1fb6aac8c23a.png)

Or do we just want simple labels for things far off in the distance that follow those things?

**Comment by omni-viral** [comment]
Your example is too 3d I think.
I think we should support UI rendered on any surface.

**Comment by minecrawler** [comment]
Render to texture for UI? Then it should also be possible to do that for anything...

![render to tex example](https://i.redd.it/rm69e6yv9tg01.jpg)

**Comment by Xaeroxe** [comment]
It'd probably be less rendering overhead to transform the UI rendering into the intended place in the 3D world.  There isn't really anything stopping us from doing that.

**Comment by Rhuagh** [comment]
I think we should have both. We should have 3d text rendering, and we should be able to render some UI entities to texture, while rendering other UI entities to the "real UI".

**Comment by jojolepro** [comment]
2 Types:
-Billboard text
-3D static rotation text

**Comment by fhaynes** [comment]
Closing this due to age and lack of progress. If there is interest, we'll put it on the roadmap.
