### ISSUE TITLE
UiText scaling to screen dimensions

### ISSUE THREAD

**Issue by illis** [amethyst/amethyst#799]
Had an issue where if I shrunk the window I was playing in - the UiText wouldn't scale down to fit the screen. Its more of an issue, if I load up onto another machine with a smaller screen.

Created a basic system to scale the fonts depending on screen size:
https://github.com/amethyst/amethyst/compare/develop...illis:feature/fontscaler

It works by including a UiTextScaler component along with the UiText
```
            world
            .create_entity()
            .with(UiTransform::new(
                    "score".to_string(),
                    Anchor::TopRight,
                    0.,
                    25.,
                    0.,
                    200.,
                    50.,
                    1,
                    ))
            .with(UiText::new(
                    font.clone(),
                    "000".to_string(),
                    SCOREBOARD_COLOR_SCORE,
                    50.,
                    ))
            .with(UiTextScaler {
                base_width: 1920.,
                base_height: 1200.,
                base_size: 25., })
            .build();
```

Scaling code is a bit janky at the moment - didn't want to spend too much time on it, if no-one else was interested in including something like this. If people are interested, I can tweak it up, and create a PR.

**Comment by Xaeroxe** [comment]
I love the base idea here, however I'm wondering if inside the `UiTextScaler` component we can instead use a more flexible unit than the pixel.  Percent scaling for example is probably the way to go here.

**Comment by Xaeroxe** [comment]
I'm wondering if we ought to use `UiTransform.scale_mode` to determine if the text size is interpreted as a percent or pixels.

**Comment by jojolepro** [comment]
I think we should be using scale mode for this.

**Comment by illis** [comment]
Changed the code a bit more to make use of ScaleMode:
https://github.com/amethyst/amethyst/compare/develop...illis:feature/fontscaler

Just not sure how the ScaleMode::Pixel part of it would work.

**Comment by azriel91** [comment]
> Could potentially dump the UiTextScaler component, and work directly with the UiTransform scale_mode & height -> but that would mean this would affect every instance of UiText & UiTransform.

Would that be a bad thing? Other way round, I would think that would be a sensible default / what people would expect when resizing the screen, and if they actually intend for the text to stay at a certain size, *then* they would specify something.

<sub>(disclaimer: rookie at game engines)</sub>

**Comment by jojolepro** [comment]
scale_mode is exactly what this should be for, but it is (was?) unimplemented if I remember correctly.

**Comment by illis** [comment]
Ok, thanks guys. I'll have some free time tomorrow, so I'll go ahead with dumping the UiTextScaler component and work directly with the UiTransform scale_mode & height.

**Comment by fhaynes** [comment]
Closing due to age and lack of activity.
