### ISSUE TITLE
Codename for 1.0 release

### ISSUE THREAD

**Issue by ebkalderon** [amethyst/amethyst#8]
Once the engine stabilizes, a new code name will be needed for the 1.0 release. The format is as follows:
1. Random adjective
2. Random noun

Some examples:
- Drafty Glockenspiel
- Wicked Cucumber
- Rowdy Radiator
- Kinky Touchdown
- Spent Weasel

Currently, the 0.1.x series is "Uncanny Snow" and 0.2.x is "Explosive Cleric". All development versions before 1.0 will henceforth remain under the code name "Explosive Cleric" to better adhere to the semantic versioning standard (see the [Releases](https://github.com/ebkalderon/amethyst/wiki/Roadmap) page). Each major release will be assigned a code name which will persist until the next breaking API change.

This code name must be determined before the 1.0 release. Suggestions can be posted in the comments below. Get cracking!

**Comment by TheNeikos** [comment]
Spinning Armadillo

**Comment by ebkalderon** [comment]
Update: The official protocol for codename contests is now [codified on the wiki](https://github.com/ebkalderon/amethyst/wiki/Codenames).

**Comment by vemilyus** [comment]
Serene Badger

**Comment by tsujin** [comment]
Lazy Wombat

**Comment by vemilyus** [comment]
Rebarbative Compulsion

**Comment by Oflor** [comment]
Shiny Boulder

**Comment by paezao** [comment]
Unknown Wizard

**Comment by kvark** [comment]
Not a big fan of release names, they are too much noise to me. I'd rather just see the version.

**Comment by ebkalderon** [comment]
@kvark I agree that users should only see and refer to the software by its version, since codenames are intended for internal use. This is meant to be a little game for our own enjoyment. :smile:

**Comment by White-Oak** [comment]
I agree with @kvark

**Comment by Aceeri** [comment]
Closing this for now since a 1.0 release is probably pretty far away still. By the time we get there we can decide if this is still something we want.
