### ISSUE TITLE
Button on top of an editable Text can't be clicked

### ISSUE THREAD

**Issue by lukebitts** [amethyst/amethyst#826]
I had a scene where a Button and an editable Text were overlapping. The button was visually on top but would not receive any events. I ~fixed by separating them but it doesn't seem like intended behaviour. I can provide a .ron file and some code if necessary.

**Comment by jojolepro** [comment]
A small code showcasing the issue would help fix the code faster. We'll be looking into it soon ;)

**Comment by lukebitts** [comment]
I got the latest code in the develop branch and it seems like the issue is fixed

**Comment by jojolepro** [comment]
Perfect! Tell us if you get the issue again and we will re-open this issue. Have a good day.
