### ISSUE TITLE
Remove all env!("CARGO_MANIFEST_DIR")

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#831]
env!("CARGO_MANIFEST_DIR")
doesn't work when you actually make a release product as it insteads target the environment where it was compiled.

In my game dash-raid, I am using the following piece of code to determine the game's directory at runtime:
```
let bin_path = env::args().next().expect("Failed to get binary executable path");
    let last_slash_index = bin_path.rfind("/").expect("Failed to get last slash in binary path.");
    let mut base_path = bin_path[..last_slash_index].to_string();
    
    if base_path.contains("target/"){
        base_path = String::from(".");
}
```

It is not really safe, and was tested only on linux. Also, I didn't check if that works when using middleman callers (example: nohup, steam, nautilus, etc...).

TODO:
1) Come up with a clean solution for that.
2) Make all instances of CARGO_MANIFEST_DIR use the resource folder instead (the one we declare when creating Application)
3) Update examples and docs
4) profit :ok_hand: 

Priority of important because it prevents releasing games if you use the profiler or prefabs.

**Comment by omni-viral** [comment]
> `let last_slash_index = bin_path.rfind("/")`

You really shouldn't reimplement `std::path::Path::parent`

**Comment by jojolepro** [comment]
Oh, I didn't know that was a thing. Thanks!

**Comment by onbjerg** [comment]
What about [`std::env::current_exe`](https://doc.rust-lang.org/std/env/fn.current_exe.html)? Looks to fit, can pop off the top portion of the [`PathBuf`](https://doc.rust-lang.org/std/path/struct.PathBuf.html).

**Comment by jojolepro** [comment]
If we do make a check for symlinks yes

**Comment by onbjerg** [comment]
@omni-viral Except if I open up the game using an absolute path in another directory then `std::env::current_dir()` will not reflect the directory we are actually looking for (the directory with the data files).

**Comment by omni-viral** [comment]
Then [std::env::current_exe](https://doc.rust-lang.org/std/env/fn.current_exe.html) is what you need.

**Comment by Rhuagh** [comment]
That won't work when running from cargo, because the executable files are created in temporary directories under `build/`, and you have no way to guarantee its location as compared to the asset files.

**Comment by Rhuagh** [comment]
This is the reason why we use the cargo manifest directory as the root location in the examples. This strategy should not be used in actual full games, for those you need to separate the logic for each platform. It is for this reason we created the `platform` crate.

**Comment by jojolepro** [comment]
I use this and it works. This issue is just about integrating this code in the engine, cleaning it up a bit, and ensuring that its used everywhere.
https://github.com/jojolepro/amethyst-extra/blob/77acd8920f7b68494bddd538ac9946cb0e584d78/src/lib.rs#L526

**Comment by jojolepro** [comment]
Note: The linked implementation ^  doesn't work on osx. On osx, if you click on an executable using finder, the workdir will be set to the home directory instead of the current directory, causing "." to fail. To fix this, you need to change the path variable of the current directory during the initialization. Code for this is available in amethyst/ludumdare42

**Comment by jojolepro** [comment]
```
jojolepro@JojoleproServer-1:~/prog-remote/amethystvanilla$ grep -r "env!(\"CARGO_MANIFEST_DIR\")" ./
./amethyst_assets/src/source/dir.rs:        let test_assets_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/assets");
./amethyst_assets/src/source/dir.rs:        let test_assets_dir = Path::new(env!("CARGO_MANIFEST_DIR"))
./amethyst_assets/examples/hl.rs:    let assets_dir = format!("{}/examples/assets/", env!("CARGO_MANIFEST_DIR"));
./amethyst_assets/examples/ll.rs:    let path = format!("{}/examples/assets", env!("CARGO_MANIFEST_DIR"));
./src/app.rs:        let path = format!("{}/thread_profile.json", env!("CARGO_MANIFEST_DIR"));
./examples/material/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/material/main.rs:    let resources = format!("{}/examples/assets/", env!("CARGO_MANIFEST_DIR"));
./examples/custom_game_data/main.rs:    let resources_directory = format!("{}/examples/assets", env!("CARGO_MANIFEST_DIR"));
./examples/custom_game_data/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/pong_tutorial_02/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/pong_tutorial_02/main.rs:    let assets_dir = format!("{}/examples/assets/", env!("CARGO_MANIFEST_DIR"));
./examples/ui/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/ui/main.rs:    let resources = format!("{}/examples/assets", env!("CARGO_MANIFEST_DIR"));
./examples/animation/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/animation/main.rs:    let resources = format!("{}/examples/assets/", env!("CARGO_MANIFEST_DIR"));
./examples/pong_tutorial_01/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/pong_tutorial_01/main.rs:    let assets_dir = format!("{}/examples/assets/", env!("CARGO_MANIFEST_DIR"));
./examples/pong/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/pong/main.rs:                env!("CARGO_MANIFEST_DIR")
./examples/pong/main.rs:                env!("CARGO_MANIFEST_DIR")
./examples/pong/main.rs:    let assets_dir = format!("{}/examples/assets/", env!("CARGO_MANIFEST_DIR"));
./examples/appendix_a/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/appendix_a/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/appendix_a/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/appendix_a/main.rs:    let assets_dir = format!("{}/examples/assets/", env!("CARGO_MANIFEST_DIR"));
./examples/locale/main.rs:    let resources_directory = format!("{}/examples/assets", env!("CARGO_MANIFEST_DIR"));
./examples/fly_camera/main.rs:    let resources_directory = format!("{}/examples/assets", env!("CARGO_MANIFEST_DIR"));
./examples/fly_camera/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/fly_camera/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/window/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/sphere_multisample/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/sphere_multisample/main.rs:    let resources = format!("{}/examples/assets/", env!("CARGO_MANIFEST_DIR"));
./examples/gltf/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/gltf/main.rs:    let resources_directory = format!("{}/examples/assets/", env!("CARGO_MANIFEST_DIR"));
./examples/arc_ball_camera/main.rs:    let resources_directory = format!("{}/examples/assets", env!("CARGO_MANIFEST_DIR"));
./examples/arc_ball_camera/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/arc_ball_camera/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/asset_loading/main.rs:    let resources_directory = format!("{}/examples/assets", env!("CARGO_MANIFEST_DIR"));
./examples/asset_loading/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/renderable/main.rs:    let resources_directory = format!("{}/examples/assets/", env!("CARGO_MANIFEST_DIR"));
./examples/renderable/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/prefab/main.rs:    let resources_directory = format!("{}/examples/assets", env!("CARGO_MANIFEST_DIR"));
./examples/prefab/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/sprites/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/sprites/main.rs:    let assets_directory = format!("{}/examples/assets/", env!("CARGO_MANIFEST_DIR"));
./examples/separate_sphere/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/separate_sphere/main.rs:    let resources = format!("{}/examples/assets/", env!("CARGO_MANIFEST_DIR"));
./examples/pong_tutorial_03/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/pong_tutorial_03/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/pong_tutorial_03/main.rs:    let assets_dir = format!("{}/examples/assets/", env!("CARGO_MANIFEST_DIR"));
./examples/sphere/main.rs:        env!("CARGO_MANIFEST_DIR")
./examples/sphere/main.rs:    let resources = format!("{}/examples/assets/", env!("CARGO_MANIFEST_DIR"));
./book/src/pong-tutorial.md:    env!("CARGO_MANIFEST_DIR"));
./book/src/pong-tutorial/pong-tutorial-03.md:    env!("CARGO_MANIFEST_DIR")
./amethyst_config/examples/main.rs:    let path = format!("{}/examples/display_config.ron", env!("CARGO_MANIFEST_DIR"));
```

**Comment by jojolepro** [comment]
Probably in the utils crate. standard_working_directory() or something

**Comment by scorbeil** [comment]
How do you feel about that?  I will fully admit that I'm out of practice at Rust.  That's actually why I dropped by to look at the issue tracker: to get some practice :)

It builds, all tests run, etc.  I will say that I have no idea how to write a reproducible test for a function that depends on PROFILE ("release" or "debug") and the presence or absence of a symlink.

**Comment by scorbeil** [comment]
#911 fixes this except for some of the examples/tests in sub-crates, as discussed on the PR.  @jojolepro seemed fine with leaving those few alone.

**Comment by Moxinilian** [comment]
Thank you!

**Comment by linonetwo** [comment]
Seems `application_root_dir` is not pub from utils?

I try to use it likes what in the example, but it don't exist.

I'm in
```
amethyst = "0.8.0"
```
project is created by amethyst_tools.

**Comment by magnonellie** [comment]
We haven't yet released a new version to crates.io that includes this change so you either have to depend on the git repository or wait until 0.9 to use this :wink:
