### ISSUE TITLE
Better example for Component in the book

### ISSUE THREAD

**Issue by rivertam** [amethyst/amethyst#845]
I'm a bit confused about `Component`s. Namely, do they describe all properties of an `Entity` or does each one correspond to one property?

In [the book](https://www.amethyst.rs/book/master/concepts/component.html), the example given is just

```rust
pub struct MyComponent {
    some_property: String,
}
```

At the risk of sounding unfairly harsh, I consider this an unacceptable example as it explains nothing about what a `Component` is to me.

A good example, I think, given the previous descriptor, would be one of the following:

```rust
enum Shape {
    Sphere { radius: f32 },
    RectangularPrism { height: f32, width: f32, depth: f32 },
}
pub struct Shape {
    shape: Shape,
}

pub struct Material {
    material_name: String,
}
```

or 

```rust
enum Shape {
    Sphere { radius: f32 },
    RectangularPrism { height: f32, width: f32, depth: f32 },
}

pub struct BottleComponent {
    shape: Shape,
    material_name: String,
}
```

**Comment by jojolepro** [comment]
Makes a lot of sense!
To answer your question, the right answer is the first of the two examples you wrote.
You usually want to have a single property (or property set) per component.

**Comment by rivertam** [comment]
@jojolepro Great! Thanks! Will update the book. Working on a couple PRs with general changes.

**Comment by Temeez** [comment]
I too am confused about components and I want to confirm something. For a in-game item component I would do something like this:
```rust
pub struct Name {
    name: String
}

pub struct Description {
    description: String
}

pub struct Value {
    value: i32
}

pub struct Quantity {
    quantity: i32
}
```

instead of this:
```rust
pub struct Item {
    name: String,
    description: String,
    value: i32,
    quantity: i32,
}
```
?

If the answer is "yes" then why? Is it more memory efficient or something along those lines?

**Comment by jojolepro** [comment]
No you should be using the second piece of code.

**Comment by magnonellie** [comment]
@Temeez In your case, I would probably say that you should go for the combined struct. The reason why someone might want to go with your first approach is that it's more modular. You can mix and match between having and not having different attributes. Something maybe doesn't have a name and something might not have a value just as simple examples.

**Comment by rivertam** [comment]
Well now I'm confused. I thought each `Component` represented one trait an object might have?

I could see how `Item` might represent some generic "pile". Like in RuneScape there are "piles" of things that would have those attributes (though maybe not `value`, I forget). But barring the "this is a very generic bundle of one resource", why would you want to combine all of those?

**Comment by OvermindDL1** [comment]
I think of ECS very different than from these descriptions...

I think of Component types as tables in a database (SQL or whatever), an entity as just a unique ID, and an instance of a component on an entity as a row in the component table of a given type with the primary key of that entity id.

**Comment by magnonellie** [comment]
@rivertam It's a very fine (and subjective) balance between being too verbose and too limiting. Performance plays a little into this but not quite as much. If you have all of those different components, you need to be very verbose when using them in systems and they may also slow down your program simply because of the quantity of components you end up with. If you combine attributes too much, you end up fetching the same component over and over accessing different values from it which breaks specs parallel fetching strategy but at the same time it's easier to use. My suggestion would be to just try to make something with ECS and then everything falls into place sooner or later. That's what I did anyway. :smile:

**Comment by LucioFranco** [comment]
@rivertam @Temeez So generally you want each component to represent some piece that can be attached to an entity. It can mean it having a few items in the component or just one. For the example of an item, an all those attributes can be in one `ItemComponent` but the benefit of an ECS system is that down the line say only some items have a `value` and some don't. You can then have one component that is `ItemComponent` and another with `ItemValuedComponent` that allows you to attach the `ItemValuedComponent` to only certain entities. I actually found that the [specs book](https://slide-rs.github.io/specs/#whats-an-ecs) has some really good explanations about how you should think about different components.

**Comment by Temeez** [comment]
I see now, very informative. You're all awesome, thank you. :smile:

**Comment by Moxinilian** [comment]
Besides, if you are not going to perform computation on one value on its own without all the others, there us no reason to separate them in the first place. You most likely will never take all the descriptions alone of all items to do something with them.

**Comment by jojolepro** [comment]
The new example for components has been merged into the develop branch. I am closing this issue. Feel free to reopen if your question wasn't fully answered.
