### ISSUE TITLE
Lighting/Pass compatibility

### ISSUE THREAD

**Issue by ghost** [amethyst/amethyst#855]
# Tasks
- Add missing lights to renderer

I've noticed some holes in the supported [lights](https://docs.rs/amethyst_renderer/0.8.0/amethyst_renderer/enum.Light.html) with different rendering passes. I'll catalog them here, so that maybe I or somebody can work on fixing them eventually. I'll post my test program when I get a chance.

Pass|Area|Directional|Point|Spot|Sun
-|-|-|-|-|-
`DrawShaded<PosNormTex>`||Lit|Lit||**Dark**
`DrawShadedSeparate<PosNormTex>`
`DrawPbm<PosNormTangTex>`||**Dark**|Lit||**Dark**
`DrawPbmSeparate<PosNormTangTex>`|||Bugged||**Dark**
`DrawFlat<PosTex>`|*n/a*|*n/a*|*n/a*|*n/a*|*n/a*
`DrawFlatSeparate<PosTex>`|*n/a*|*n/a*|*n/a*|*n/a*|*n/a*

Pinging @omni-viral per @jojolepro for guidance.

**Comment by omni-viral** [comment]
In `Pbm` shaders passes `Directional` light wasn't implemented. Should be.
What's `Sun` light type? How it is different from `Directional`

**Comment by minecrawler** [comment]
As per the comment above the struct:

> /// A realistic disk-shaped sun light source.

So I guess that a directional light has parallel light rays, but a sun's rays are spreading, which creates a different effect...

What would be interesting is knowing what technique is used to calculate the lights and shadows and if it provides modern effects, like light bleeding, ambient occlusion, multi-reflection and scattering (getting rid of ambient illumination), hard->soft shadows, etc.

Imho, especially the PBS shaders should be able to handle such realistic features. There should also be algorithms for weaker machines!

**Comment by Aceeri** [comment]
https://seblagarde.files.wordpress.com/2015/07/course_notes_moving_frostbite_to_pbr_v32.pdf#page=24&zoom=auto,-122,784
Good diagram of punctual vs area and such.

**Comment by omni-viral** [comment]
With deferred shading it would be easier to add new lightsource types to lighting pass.

**Comment by magnonellie** [comment]
We would still need to support forward rendering for stuff like VR that pretty much require MSAA.

**Comment by termhn** [comment]
Clustered forward: some of the benefits of deferred and most of the benefits of forward http://www.cse.chalmers.se/~uffe/clustered_shading_preprint.pdf
also used in doom http://www.adriancourreges.com/blog/2016/09/09/doom-2016-graphics-study/

**Comment by torkleyy** [comment]
The task here is to extend support for lighting as far as possible and making sure support is documented accordingly.

**Comment by karroffel** [comment]
In #1081 and #1074 I added support for `DirectionalLight`s and `SpotLight`s to the PBM pass.

`SpotLight`s have not been implemented anywhere in Amethyst before, so please test for any weird behaviours.

I only touched the PBM pass, so the shaded pass will not handle SpotLights yet, but this should be a good start
