### ISSUE TITLE
amethyst.rs book: link to API reference broken

### ISSUE THREAD

**Issue by sinesc** [amethyst/amethyst#86]
/book/intro.html on amethyst.rs links to /doc/amethyst/ (404) when it should probably link to /doc/master/amethyst/ in this sentence:

Read the crate-level **API documentation** for more details.

**Comment by ebkalderon** [comment]
@sinesc Uh oh, good catch! This is definitely an issue, but thankfully it should be a simple fix.

**Comment by ebkalderon** [comment]
@amethyst/engine-devs @amethyst/tools-devs Looks like we might be able to revise the **develop** version of the book, but the website's [generate.sh](https://github.com/amethyst/website/blob/master/generate.sh) script pulls from the **master** version of the book, which is static for the moment. Shall we change the script to pull from **develop** instead?

**Comment by LucioFranco** [comment]
@ebkalderon I think we should keep it on master. The api url did change and we should fix the book to point to master.

**Comment by ebkalderon** [comment]
I think this issue has been fixed now. Thanks for reporting, @sinesc! :smile:
