### ISSUE TITLE
Request: Support for custom default `Source` types in `Loader`

### ISSUE THREAD

**Issue by mtak-** [amethyst/amethyst#862]
I'm a bit of an amethyst newb, but I've been testing out a hacked version of amethyst on iOS and android, and have a little feedback on some annoyances.

`Loader`'s default source is a `Directory`. On android for example, this is borderline useless as reading from the APK has to go through `AAssetManager`. On iOS, asset catalogs would likely be the default source type - which again, is not a `Directory`.

I can understand why `Loader` is not generic over the default source type. Maybe a `default_source: Arc<dyn Source>` would work?

Additionally, the `Prefab` system (possibly other systems) currently only supports loading files from the default `Source`. Making `Prefab`'s less usable in situations where you might wanna load certain `Ui`'s downloaded from the network - writable paths are in a different location than the actual app on both iOS and android.

**Comment by Rhuagh** [comment]
We should fix so the default can be a different `Source`, yeah. 

I believe that you're referring to sub loads not working from non-default sources right ?

**Comment by mtak-** [comment]
Thanks for the response and all the work on amethyst.

For the prefab system, you are correct I am referring to sub loads not working with non-default sources.

FWIW, these were all minor thingies, and amethyst mostly "just worked" on iOS/android with only slight modifications to it's dependencies :clap:. gfx/gfx-glyph, and possibly others. Mostly it was changing shaders to `#version 300 es` (requires GLES 3), and bumping `winit` dependencies to the latest. `TouchEvent`s also needed to be routed through the input system. The audio dependencies didn't build for me on iOS, and `clipboard` doesn't support iOS either.

**Comment by Rhuagh** [comment]
This has been fixed, closing.
