### ISSUE TITLE
Pong tutorial 3 not clear enough

### ISSUE THREAD

**Issue by Telzhaak** [amethyst/amethyst#863]
After creating the "mod.rs" that specifies the "mod paddles;" it is stated to implement the actual PaddleSystem. 

For rust-beginners it would be helpful to state, that the implementation does not happen in "mod.rs" but inside a new file calles "paddles.rs" (which you actually refer to later, but never said to create)

It's a minor thing and can be figured out easily by reading the compile-error, but for the sake of completeness I think it should be included.

**Comment by LucioFranco** [comment]
@Telzhaak I agree! I just opened a PR for this, thanks for reporting it.

**Comment by LucioFranco** [comment]
Since the PR got merged this morning, I am going to close this issue. If you have anymore questions or if it is not clear enough please feel free to reopen!
