### ISSUE TITLE
Travis fails to build.

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#865]
Travis always fails to build. It appears to be related to sdl_controller.
Is it still even compiling? Are we missing a dependency?

**Comment by jojolepro** [comment]
I can manually compile with the sdl_controller features on my side. I'll investigate next time a build fails.

**Comment by jojolepro** [comment]
Bors fails because travis gets a permission denied on the trying(probably stating too) branch

**Comment by LucioFranco** [comment]
@jojolepro seems that Travis has passed, https://travis-ci.org/amethyst/amethyst/builds/416468070?utm_source=github_status&utm_medium=notification

so can we close this issue?

**Comment by jojolepro** [comment]
I want to see if its gonna timeout again next pr

**Comment by LucioFranco** [comment]
@jojolepro it seemed travis completed but appveyor didn't, and it looked like it was just a long queue time for appveyor https://ci.appveyor.com/project/amethyst/amethyst/build/1.0.2670

**Comment by jojolepro** [comment]
travis build but appveyor is slow.
closing this as we have a tracking issue about appveyor
