### ISSUE TITLE
Change State::handle_event to handle other types of events.

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#866]
We need to expand State::handle_event to react to arbitrary events, and not just the ones from winit.

Proposed solution:

pub enum StateEvent {
    Window(winit::Event),
    Ui(uievent),
    .....
}

This way, handling ui events will be much easier, and creating transitions between different menu will be much easier to create.

**Comment by jojolepro** [comment]
taking issue

**Comment by Telzhaak** [comment]
Wouldn't that lead to a `match` inside a `match` inside a `match`?

Seperate event channels might be better and easier to understand for the developer

**Comment by jojolepro** [comment]
No because you have to register multiple ReaderId in each state.
That makes simple things like states that are simply menu to become really tedious to make.
But yes that does lead to a match inside a match.

The easy way to do it is like this:
```rs
if let StateEvent::Ui(UiEvent::Click(target_entity)) = &event {}
```
and for multiple event types:
```rs
match event {
    StateEvent::Ui(UiEvent::Click(target_entity)) => info!("Clicked {:?}",target_entity),
    StateEvent::Ui(UiEvent::HoverStart(target_entity)) => info!("HoverStarted {:?}",target_entity),
    _ => {},
}
```
