### ISSUE TITLE
Pong tutorial code out of date.

### ISSUE THREAD

**Issue by Aaronepower** [amethyst/amethyst#872]
A lot of the code in the pong example is out of date with the current amethyst version. Specifically these two examples I ran into while trying to get through it.

```rust
let pipe = Pipeline::build().with_stage(
    Stage::with_backbuffer()
        .clear_target([0.0, 0.0, 0.0, 1.0], 1.0)
        // No such thing a PosTex, it's now PosNormTex
        .with_pass(DrawFlat::<PosTex>::new()),
);
```

```rust
let mut game = Application::build("./", Pong)?
     // no method named `with_bundle` found for type `amethyst::ApplicationBuilder<pong::Pong>` in the current scope
    .with_bundle(TransformBundle::new())? // Add this bundle
    .with_bundle(RenderBundle::new(pipe, Some(config)))?
    .build()?;
```

**Comment by Moxinilian** [comment]
The first one is correct. You probably missed an import.
The second one is known, and will be updated as soon as somebody is available.

**Comment by Aaronepower** [comment]
@Moxinilian It isn't correct as `amethyst new` generates the following code. I didn't import anything.
```rust
let pipe = Pipeline::build().with_stage(
    Stage::with_backbuffer()
        .clear_target([0.0, 0.0, 0.0, 1.0], 1.0)
        .with_pass(DrawFlat::<PosNormTex>::new()),
);
```

**Comment by jojolepro** [comment]
You are supposed to import PosTex
use amethyst::renderer::PosTex

and change PosNormTex to PosTex

**Comment by Aaronepower** [comment]
@jojolepro If you're supposed to do that then why isn't that in the book? https://www.amethyst.rs/book/master/pong-tutorial/pong-tutorial-01.html

**Comment by Moxinilian** [comment]
![image](https://preview.ibb.co/h9C8o9/image.png)

Please read my previous comment carefully.

**Comment by jojolepro** [comment]
![image](https://user-images.githubusercontent.com/4755185/44045450-8d2922fc-9ef6-11e8-9cef-7b894da33824.png)

**Comment by Aaronepower** [comment]
Thank you both for addressing this issue through passive aggressive screenshots.

**Comment by jojolepro** [comment]
I am sorry if we offended you.
That wasn't the goal.

I will close this issue as it has been addressed. Have a good day!

**Comment by Aaronepower** [comment]
@jojolepro Offending me would imply that's my fault for you not handling feedback well.

**Comment by jojolepro** [comment]
I would prefer to not let this matter escalate, as it is against our rule of conduct.

Have a good day!
