### ISSUE TITLE
Tutorial code does not compile

### ISSUE THREAD

**Issue by jackmott** [amethyst/amethyst#874]
The last code section on this page:
https://www.amethyst.rs/book/master/pong-tutorial/pong-tutorial-02.html

Does not compile, using amethyst 0.8.0

**Comment by jojolepro** [comment]
Yes, thanks for reporting. It will be fixed shortly.

**Comment by Moxinilian** [comment]
@jojolepro are you working on that or do you want me to do it? we would have to merge it into master then which might be a bit delicate for me

**Comment by jojolepro** [comment]
*issue reserved*
