### ISSUE TITLE
[RFC] Groups (Eliminate Parent Component)

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#876]
# Group RFC

Instead of having a recursive tree-based structure for entities (via parent), I propose a structure based on grouping.

### First, the issues with parenting:
* Accessing the childs or all childs recursively of a specific entity is tedious.
* Applying some operation to a subset of childs of a specific entity requires making a node entity holding that subset. If you need two subsets that overlap, this becomes impossible.
* Algorithms like ui layouting and GlobalTransform calculations become quickly complex, and require heavy cache use at the System level to prevent killing the cpu.

### What's good about them:
* Naturally represent tree-like structures: Ui and Animations
* Easy to represent in pure data

### Goal

The goal of groups is to encourage a structure that is flat instead of recursive.

Recursion is used when transforming the data, instead of when consuming it, which simplifies both the user's code and the engine's code.

### Concept

Groups will basically be the same as the classic "TagComponent" + Join approach.

** A group contains a list of entities. **

Data transformations applied to a group are applied to each member entity of said group.

### How does it look like?

Here is a simple example:

Entities:
* Arena
* Player1
* Player2
* WeaponPlayer1
* WeaponPlayer2

Groups:
* All (Arena, Players)
* Players (Player1Group, Player2Group)
* Player1Group (Player1, WeaponPlayer1)
* Player2Group (Player2, WeaponPlayer2)
* PlayersOnly (Player1, Player2)

__Please note that this is not how the code will look like in reality__

__Also note that groups are recursive, but in the end, from the usage perspective you will get a list of unique entities, or a single group interface directly modifying all entities under it.__

Now, let's say we want to move player 1.
```rs
Group::Player1Group::AllComponents<TransformDelta>().translate(1,1,0);
```

What about moving all players, but not the arena?
```rs
Group::Players::AllComponents<TranformDelta>().translate(0,100,0);
```

And to remove only the players, but not the weapons, so the weapons drop on the ground?
```rs
Group::PlayersOnly::Delete();
```

### Spicing things up

Now, let's get messy with a hard one: Ui layouts

Entities:
* Button1Text
* Button1Image
* Button2Text
* Button2Image

Groups:
* Button1Group (Button1Text, Button1Image)
* Button2Group (Button2Text, Button2Image)
* UiList (Button1Group, Button2Group)

```rs
UiList::ApplyLayout(params);
// Moves Button1Group and Button2Group on the screen so that they respect the layouting constraint of UiList for the specified parameters.
```

```rs
Button1Group::ApplyLayout(params);
// Applies the layouting constraint of a button group: Center the text in the middle of the button's position.
```

In this case, both UiList and Button1Group could implement a `UiLayout` trait providing the method to layout the entities according to the specificities of that group.

Also, note that calling UiList::ApplyLayout should NOT call Button1Group::ApplyLayout, except if the dimensions of the Button1Group needs to be changed.

__Ui layouting is a big -hard to work with- concept. If you have a better idea for a ui data representation and transformation, I'm all for it!__

### This looks like the current implementation, what's the point?

From the user perspective, it is not the same at all.

If we take the ui example again, instead of this structure:

UiList
- UiImage (btn1)
-- UiText
- UiImage (btn2)
-- UiText

Here's what it will end with:
- UiImage (btn1)
- UiText (btn1)
- UiImage (btn2)
- UiText (btn2)

Currently, to change the text of a button (or change the child of any entity) you have to:
* Find the parent entity.
* Search through all entities to find the ones that have the parent in their `Parent` component. (and if you need to get them all recursively, good luck)
* Modify those child entity.

Currently, there is a quicker way of doing it for the ui because UiTransform has an "id" field, which is a string.
For other things though, like animations, player controllers, etc... You need to create what is called a "Tag Component", which sole purpose is to identify a particular entity.

With groups, now all you need to do is to get the entities in your group:
```rs
for (entity) in Group::Button1::entities() {
    ui_text_storage.get(entity).map(|text| text.text = "desired new value");
}
```

### Convenience

Now, the last piece of code shown looks annoying to use, right?
What about having pre-defined groups that are used to massively apply transformations for you?

```rs
Group::Button1::set_text("desired new value", &mut ui_text_storage);
```

We can add various utility functions to groups.
General:
* Getting all components of a type for a group (shorthand for join)
* Deleting all components of a type for a group
Specific:
* Changing a UiButton's text
* Animating a bone of a 3d entity

### Bye bye, GlobalTransform

Since we don't have a recursive entity structure anymore, but still the same functionnality, we can get rid of some syncronisation systems and components that were annoying to deal with.

Here's a quick list:
* Prefabs
* Gltf
* GlobalTransform (becomes a cached matrix directly into Transform instead)
* UiTransform (+layouting becomes a group property. It can still be modelled as a tree in files, and then mapped to groups
* Probably a lot more...

If accepted, this rfc implementation will need to be made both inside amethyst and inside specs. This is a breaking change, obviously.

**Comment by Moxinilian** [comment]
Shut up and take my money.

**Comment by Xaeroxe** [comment]
I think you could implement this without modifying `specs`, and something like this is going to be helpful.  I'm imagining one could implement this as simply `Vec<Entity>`.  

Also a lot of your cons of the current system could be resolved by simply reversing the data flow.  Perhaps we could use `Children(Vec<Entity>)` instead of or in addition to `Parent(Entity)`

**Comment by Moxinilian** [comment]
I remember having more problems working with children-based components than parents. But I don't remember where the issues were unfortunately.

**Comment by jojolepro** [comment]
Children(Vec<Entity>) will not solve much, as you will still need to access the entities recursively to build the whole list of childs for a specific entity. It also doesn't allow removing the recursive algorithms like GlobalTransform + TransformSystem

**Comment by Xaeroxe** [comment]
> Players (Player1Group, Player2Group)

Isn't the same true under this proposal?

Also recursive access could be simplified into a function.  `all_children(parent: Entity, storage: ReadStorage<Children>) -> impl Iterator<Item=Entity>`

**Comment by Xaeroxe** [comment]
Helper functions like that could go really well in the `specs-hierarchy` crate.

**Comment by Moxinilian** [comment]
But this does not solve the issue of having an entity in multiple groups.

By the way, to apply something to all entities of a group without the tedious syntax, just do:
```rust
Groups::write_on<T: Component>(storage: WriteStorage<T>, f: FnOnce(&mut T))
```

**Comment by jojolepro** [comment]
Oh yeah this is nice.

The only thing I'm unsure of is how groups will actually be stored.
Groups are only Vec<Entity>, but they need to be stored and access somewhere if we want to be able to add and remove entities to them.

**Comment by Moxinilian** [comment]
Just make them resources.

**Comment by Xaeroxe** [comment]
There's two paradigms, which is hardly cognitive overload imo, but this is just my two cents.

Hierarchies are a strong and battle tested way of making games.  I'd be hesitant to try and infringe on that.  However there are plenty of valid criticisms here of the current hierarchy system we have.  So let's fix the hierarchy system by adding helper functions and bi-directional flow.

However the Group proposal also has merit as just a convenient way to clump `Entities` together.  Maybe we should implement `Join` for `Vec<Entity>` and call it a day?

**Comment by jojolepro** [comment]
If you just want to clump entities together, you can make a simple tag component + join() and call it a day.

**Comment by Xaeroxe** [comment]
That too :)

**Comment by Xaeroxe** [comment]
Allow me to be a bit more specific


> Accessing the childs or all childs recursively of a specific entity is tedious.

Helper function can alleviate this pain

> Applying some operation to a subset of childs of a specific entity requires making a node entity holding that subset. If you need two subsets that overlap, this becomes impossible.

Architect this as either tag components or `Vec<Entity>` instead.
    
> Algorithms like ui layouting and GlobalTransform calculations become quickly complex, and require heavy cache use at the System level to prevent killing the cpu.

Can you point me to some specific lines in the systems you feel are unwarranted?  I'm not 100% sure I understand this.

**Comment by Rhuagh** [comment]
I'm with @Xaeroxe, scene (di)graphs are basically required for some features to work correctly, so I'm not gonna endorse any removal of that. Grouping have benefits sure, so we can always add that. When it comes to looking up all children in a sub hierarchy that's actually trivial to add an iterator for.

**Comment by Rhuagh** [comment]
As an example, skeletal animation requires a digraph, unless your skeleton have a single node (not common).

**Comment by Rhuagh** [comment]
The `TransformSystem` and the `UiLayoutSystem` are only complex because we want to avoid doing calculations for things that haven't updated, not because of any inherent complexity in the hierarchy itself.

**Comment by Xaeroxe** [comment]
I'm also not super sure we need bi-directional flow now that I think about it because `specs-hierarchy` already solves the "find my immediate children" issue pretty well.

**Comment by Rhuagh** [comment]
Bidirectional how? You can already get the parent entity for a given entity directly from `Hierarchy`?

**Comment by Xaeroxe** [comment]
Sorry, earllier I had proposed a `Children(Vec<Entity>)` component.  I'm now saying I don't think we'll need that.

**Comment by Rhuagh** [comment]
Ah, yeah, there's already a function for that on `Hierarchy`

**Comment by jojolepro** [comment]
# Complexities

So I tried to calculate the inherent complexities related to both ideas and ended up with this:
## hierarchy:
* entity create O(1)
* find entities O(n^m) (possibly n or less because of specs-hierarchy cache)
* remove entities O(m)

## Groups:
* entity create O(m)
* find entities O(1)
* remove entity O(m)

# Example of how a tree-based data can be converted into groups.

This example is based on bone animations.

## Hierarchy
Player:
-Transform
-Arm:
--Transform
--Mesh
-Torso:
--Transform
--Mesh
--Head:
---Transform
---Mesh

Move all player -> player's transform.translate(1,2,3)
Bow forward -> torso.rotate(quaternion)

## Groups

Arm:
-Transform
-Mesh
Torso:
-Transform
-Mesh
Head:
-Transform
-Mesh

PlayerGroup: (Arm, Torso, Head)
TorsoGroup: (Torso, Head)

Move all player -> PlayerGroup::translate_global(1,2,3);
Bow forward -> TorsoGroup::rotate_with_origin(torso, quaternion);

## Issues with this method

I realized with moxi that, while this method is more performant in most cases, if you move multiple times per frame you lose performance. Also, managing the ordering of operations can become tedious I think.
