### ISSUE TITLE
Remove usage of String in the asset manager

### ISSUE THREAD

**Issue by bjadamson** [amethyst/amethyst#88]
Looking up resources by a string is convenient but slow thanks to dynamic allocation. I believe this is why OpenGL uses integer handles, even if it they are less convenient to work with.

These string should be replaced with type-safe integer wrappers, or some other design to improve the performance of the asset manager.
https://github.com/amethyst/amethyst/blob/develop/src/context/src/asset_manager.rs#L41-L42

Consideration must be given to the current convenience though, especially if it is removed.

Maybe offering both versions make sense? What does everyone think?

**Comment by OvermindDL1** [comment]
Shouldn't most asset strings have the 'key' only allocated once per app?  If not then a flyweight string container could do that.  That way you get a unique id comparison via taking the pointer of the string or the appropriate method in rust.

**Comment by bjadamson** [comment]
> Shouldn't most asset strings have the 'key' only allocated once per app?

Perhaps, but it's forcing the user to use a string when they otherwise would not. That's really what I'm trying to point out.

**Comment by bjadamson** [comment]
#90

**Comment by Geemili** [comment]
Could we make it a generic so that the user can decide?

Another thought I had is making a build script that takes a resource file and bakes the strings into integers, similar to how android does it. The build script could generate a bunch of environment variables like `AMETHYST_RESOURCE_ID_sphere_mesh=123`. After the environment is generated, the user can just include using:

```
let sphere_resource = env!("AMETHYST_RESOURCE_ID_sphere_mesh");
```

Or even a custom macro so we can omit the prefix:

```
let sphere_resource = resource!("sphere_mesh");
```

Anyway, those are my thoughts. Don't know if we want to mess with build scripts.

**Comment by bjadamson** [comment]
I like this, I think I can put a builder in front of this and make it general.

**Comment by Geemili** [comment]
Another thought: If we're going to deal with build scripts, we could just generate a "resources.rs" that contains all the resource constants. It would mean that all the `env!()` macros wouldn't need a `u32::from_str().unwrap()` surrounding them.

**Comment by Emilgardis** [comment]
One way to have both i64's and String is to with #90 have each function take id: T where T: Into<*Id>
The one problem I can see are collisions. One way to fix this is to feature-flag i64 to only have one enabled, but I'm playing around trying to find the best solution.

**Comment by bjadamson** [comment]
Another thought, maybe it makes sense to always support static str& as a key too.

**Comment by ebkalderon** [comment]
The asset manager has changed significantly since the creation of this issue and uses `&str` as opposed to fat strings. I think I'll close this issue as it is no longer relevant.
