### ISSUE TITLE
Docs have invalid links and missing fields

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#880]
https://www.amethyst.rs/doc/master/doc/amethyst_renderer/enum.Event.html?search=event
Second entry "amethyst_renderer::Event::Event::event" leads to a 404

https://www.amethyst.rs/doc/master/doc/amethyst_renderer/enum.Event.html#variant.DeviceEvent
this is missing a link to the DeviceEvent doc

**Comment by Telzhaak** [comment]
Server 404: https://www.amethyst.rs/doc/master/doc/amethyst/ecs/struct.World.html

**Comment by TimonPost** [comment]
Note that this issue can be closed! see pull request [914](https://github.com/amethyst/amethyst/pull/914)

**Comment by jojolepro** [comment]
Will be closed automatically once the pr is merged.
