### ISSUE TITLE
pong_tutorial_02, clarification

### ISSUE THREAD

**Issue by Telzhaak** [amethyst/amethyst#882]
#### [A Quick Refactor](https://www.amethyst.rs/book/master/pong-tutorial/pong-tutorial-02.html#a-quick-refactor) says:

> And in the run() function add: `use pong::Pong;`

In the actual code of **examples/pong_tutorial_02** it looks like this:
```
fn main() -> amethyst::Result<()> {  
   amethyst::start_logger(Default::default());
   use pong::Pong;
   /*snip*/

   game.run();

   Ok(())
}
```

That's a tad misleading as it could result in:
```
game.run(use pong::Pong);
```

Since it makes no difference where we add the line, this could be better:
> And in **main.rs** add `use pong::Pong;` before `fn main()`

**Comment by jojolepro** [comment]
fixed by #881
