### ISSUE TITLE
Split out backend code into separate modules

### ISSUE THREAD

**Issue by bjadamson** [amethyst/amethyst#89]
Implementing a function for different back-ends all inline within the function body becomes unmaintainable over time.

Example:
https://github.com/amethyst/amethyst/blob/develop/src/context/src/asset_manager.rs#L118-L139

The different backend implementations should be moved to their own separate module.

**Comment by bjadamson** [comment]
I'm working on this at the moment.

**Comment by bjadamson** [comment]
#98 I just sent a pull request moving all of this code entirely, and instead depend on Gfx to handle the backend code.

**Comment by bjadamson** [comment]
idea for using traits for better separation:

https://www.youtube.com/watch?v=erJdCIti_O8

**Comment by Xaeroxe** [comment]
Complete, closing.
