### ISSUE TITLE
Transparent image parts ignore the window background

### ISSUE THREAD

**Issue by ab0v3g4me** [amethyst/amethyst#890]
Here's the code used for drawing my `.png` file. I'm using Wayland as my display server.
```rust
pub fn initialise_player(world: &mut World, spritesheet: TextureHandle) {
    /* . . . . .  */
    let mut transform = Transform::default();
    transform.translation = Vector3::new(200.0,200.0,0.5);
    world.create_entity()
        .with_sprite(&sprite, spritesheet.clone(), (32.0,32.0))
        .expect("Failed to add sprite render on player")
        .with(Player::new())
        .with(GlobalTransform::default())
        .with(transform)
        .build();
}
```

```rust 
    fn on_start(&mut self, data: StateData<GameData>) {
        let world = data.world;
        let spritesheet = {
            let loader = world.read_resource::<Loader>();
            let texture_storage = world.read_resource::<AssetStorage<Texture>>();
            loader.load(
                "player.png",
                PngFormat,
                Default::default(),
                (),
                &texture_storage,
            )
        };
        player::initialise_player(world, spritesheet);
    }
```

```rust
    let pipe = Pipeline::build().with_stage(
        Stage::with_backbuffer()
        .clear_target([0.0, 0.0, 0.0, 1.0], 1.0)
        .with_pass(DrawFlat::<PosTex>::new()),
    );
```
Here's an image on how it looks like. 

![image](https://user-images.githubusercontent.com/19503519/44313219-76843380-a404-11e8-919c-f28768591326.png)

**Comment by Telzhaak** [comment]
@Moxinilian 
Transparency wasn't fixed with using a different png encoding, it just so happened to fill the alpha with the same colour as the background (black):
![unbenannt2](https://user-images.githubusercontent.com/29286474/44574012-77142580-a788-11e8-987e-f4bc4b147437.png)

For other .png encodings (do not know which this is):
![heart](https://user-images.githubusercontent.com/29286474/44574164-e8ec6f00-a788-11e8-8144-e1f5407837ad.png)
gets displayed as:
![unbenannt](https://user-images.githubusercontent.com/29286474/44574145-e12cca80-a788-11e8-85bf-09fcb07f28cd.PNG)

**Comment by minecrawler** [comment]
untested, but I think transparency is missing completely from the [flat shader](https://github.com/amethyst/amethyst/blob/develop/amethyst_renderer/src/pass/shaders/fragment/flat.glsl). It might be done with the following main function (just replace it and test again):

```glsl
void main() {
    vec2 coords = tex_coords(vertex.tex_coord, albedo_offset.u_offset, albedo_offset.v_offset);

    if(texture2D(albedo, coords).a != 1.0f)
    {
        discard;
    }

    color = texture(albedo, coords);
}
```

as the first thing in the main function. That would at least discard all pixels which have transparency. Blending is a bit more complicated, though, and I have no experience with it using gfx-rs.

**Comment by Rhuagh** [comment]
`DrawFlat` have support for alpha blending, that's not the issue here. The issue here is that he can see through the window to the workspace outside our process.

**Comment by Moxinilian** [comment]
The bug is probably upstream and should be forwarded where it belongs. gfx-rs maybe?

**Comment by Rhuagh** [comment]
Doubtful, looks like winit or lower to me.

**Comment by ab0v3g4me** [comment]
Please note that when i run `WINIT_UNIX_BACKEND=x11 cargo run` i can't see through the window anymore.

**Comment by Rhuagh** [comment]
Definitely winit or lower then.

**Comment by jojolepro** [comment]
So the issue should be opened in the winit repo (if it doesn't exist already)

**Comment by torkleyy** [comment]
I think this is resolved now, or at least we provided a workaround.

**Comment by jojolepro** [comment]
Reopen if it is not resolved. Thanks!
