### ISSUE TITLE
Custom GameData issue/book page need fixing (and remove the Arc type from ThreadPool)

### ISSUE THREAD

**Issue by Temeez** [amethyst/amethyst#893]
https://www.amethyst.rs/book/develop/game-data.html 3rd code block from the top will lead to bad time for those that try to use the code with https://www.amethyst.rs/doc/develop/doc/amethyst_core/type.ThreadPool.html

With that the https://github.com/amethyst/amethyst/blob/develop/examples/custom_game_data/game_data.rs example needs to be fixed too and the external crate removed since it's not really needed.

**Comment by virome** [comment]
I'd like to work on this one.

**Comment by LucioFranco** [comment]
#921 is now merged so this can be closed, thanks for the PR @virome !
