### ISSUE TITLE
Implement sprite batching for DrawSprite

### ISSUE THREAD

**Issue by Moxinilian** [amethyst/amethyst#894]
Now that the special sprite pass is merged, to be able to use it in realistic project, sprite batching must be implemented. Indeed, currently a small tilemap of 256 sprites eats 25% of a GTX 1070, which is ridiculous.
This also applies to traditional 3D meshes, even though sprites might be easier to implement first.

This should be relatively easy to implement as the sprite pass iterates over all sprite, so instead of drawing them directly it only needs to build a batch. Eventually, to get even better performances, we could consider caching the batch itself, but naive batching would already be a huge improvement.

**Comment by Moxinilian** [comment]
@azriel91 If you've got some time I would really love if you could give that a look.
@termhn implemented it for ggez (but is unfortunately unable to do it for Amethyst), here is the relevant code in ggez:
https://github.com/ggez/ggez/blob/master/src/graphics/spritebatch.rs

**Comment by azriel91** [comment]
This is on my radar as well, but not for at least the next two weeks -- got a lot of tasks that have to be done before that. I'll see if I can slot it in after that.

**Comment by Moxinilian** [comment]
Fixed by #902 and #923.
Closing, thank you all!
