### ISSUE TITLE
Pong Tutorial - Moving The Paddles may not build as described

### ISSUE THREAD

**Issue by jackmott** [amethyst/amethyst#898]
It is possible I have missed something, but I have double checked.

Following along with the tutorial here:
https://www.amethyst.rs/book/master/pong-tutorial/pong-tutorial-03.html

As described , the code in paddle.rs cannot find `Paddle` and `Side'.  The documentation mentions that Paddle and Side need to be made public, and I have done that.   The fix here may be simple but I'm still new to the Rust module system.

**Comment by magnonellie** [comment]
I think you're missing this line: https://github.com/amethyst/amethyst/blob/develop/examples/pong_tutorial_03/systems/paddle.rs#L4 :wink: 

May I suggest you join our Discord where we have a help channel you can use if you need further assistance? https://discord.gg/E2Dd244

**Comment by jackmott** [comment]
You are correct, that will do it. However that is completely missing from the tutorial, so we should get that added.  I'll see if I can do it.

What branch/repo do I fork to update the docs properly?

**Comment by Moxinilian** [comment]
On another note, do we want to mention every single import? That's just a ton of not very useful code.
I guess we could just tell the user to assume them, but I'm not sure.

**Comment by magnonellie** [comment]
I was thinking about that and I think for the sake of being as inclusive as possible, we should probably do it, yeah. If nothing else, people may read the book right after or before finishing TRPL, so being explicit is probably not a bad thing.

**Comment by jackmott** [comment]
closed with merge #899
