### ISSUE TITLE
The from_data method of JpgFormat should have &[u8] or &mut [u8] instead of Vec<u8> as an argument.

### ISSUE THREAD

**Issue by Debily** [amethyst/amethyst#900]
[Here](https://docs.rs/amethyst_renderer/0.8.0/amethyst_renderer/struct.JpgFormat.html#method.from_data) is the documentation for the function.

Some graphics are stored in static memory so it might be better to use &[u8] or &mut [u8]. Another idea is implementing a new function for &[u8] types.

**Comment by Debily** [comment]
This of course applies to other fileformats too

**Comment by Moxinilian** [comment]
Thank you for your PR!
