### ISSUE TITLE
Remove unwraps

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#908]
Either remove all unwraps from the engine and replace them with proper error handling, or add a comment explaining how an unwrap will never panic.

**Comment by usbalbin** [comment]
Hi!

Amethyst looks like a very exciting project. I would like to give this issue a try, if that is ok.

I am fairly new to rust. Been playing around with some smaller toy projects. However, I have pretty much zero experience with contributing to open source projects.

Is there anything in particular to think about regarding this issue except follow you contribution guidelines?

/Albin

**Comment by Moxinilian** [comment]
Welcome!
Error handling in the Rust ecosystem is a little bit tricky because the features of the standard library regarding it are a bit limited. This is why it is rated medium.
Have you ever dealt with advanced error handling in Rust?

**Comment by anderejd** [comment]
I would like to point you in the direction of this <https://doc.rust-lang.org/std/result/enum.Result.html> to begin with. One of the most important pieces of error handling with Result is the `map_err` method, which is surprisingly not mentioned once in the error handling chapter of the Rust book. Custom error enums in combination with ´Result::map_err´ and the question mark operator will provide the tools you need to do error propagation in most cases. Hope that helps to get you started 🙂

**Comment by jojolepro** [comment]
Welcome!

**Comment by usbalbin** [comment]
Thank you for your answers! No I have not dealt with any sort of non-trivial error handling before. Might not be the best issue for me to start with?

So for something like StateMachine::start

```rust
pub fn start(&mut self, data: StateData<T>) {
    if !self.running {
        let state = self.state_stack.last_mut().unwrap();
        state.on_start(data);
        self.running = true;
    }
}
```
would turn in to something like this
```rust
enum StateError { NoStatesPresent }

pub fn start(&mut self, data: StateData<T>) -> Result<(), StateError> {
    if !self.running {
        let state = self
            .state_stack
            .last_mut()
            .ok_or(StateError::NoStatesPresent)?;
        state.on_start(data);
        self.running = true;
    }
    Ok(())
}
```
? Or am I supposed to use amethyst::Result? Sorry if this is obvious.

Am I on the right path or should I should I start with something easier?
Please be honest :)

**Comment by Moxinilian** [comment]
If you've got specific questions on the internals of the engine, feel free to contact us on the #development channel on the Discord server.

**Comment by usbalbin** [comment]
Hi again!

I feel like I'm in over my head quite a bit. There is just too many places where I don't know whether arguments to functions etc can be expected to play nice with each other and where errors should be caught and handled. Thus I think I will take a step back on this one and maybe try something easier and gain some experience, getting a better feel for how everything works together. 

Should I make a PR for the few things that I have changed so far(might be completely unusable :P)?

**Comment by Moxinilian** [comment]
Thank you for your work!This is a pretty broad issue, we would not expect you to remove all panics at once. This is something that should be done by multiple people. Please do PR your changes, the more we PR now the less will be left to do.

**Comment by torkleyy** [comment]
## Task

The task here is to search for unwraps in the engine source and documentation. When you found one, look at

* what input is possible and
* if there's input that can possibly trigger it

If the answer is no, then the `unwrap` should be replaced with an `expect` explaining the bug. If the answer is yes:

* look at how this API is used and check
* if it makes sense to return `Option` / `Result` and using `None` / `Err` in the error case

Unless the API overhead would be unreasonably big, change the return type. If it is, the allowed input needs to be clearly documented. Make sure there's a `## Panics` section in the docs and propagate this to other functions calling the one you just documented.

This issue is not meant to be addressed all at once, small PRs with just a few improvements are very much appreciated!

**Comment by barskern** [comment]
I would like to contribute regarding this issue. Starting to work on it now :smile:

**Comment by barskern** [comment]
Crates where unwraps have been removed:

- [ ] amethyst_animation
- [ ] amethyst_assets
- [ ] amethyst_audio
- [ ] amethyst_config
- [ ] amethyst_controls
- [X] amethyst_core
- [ ] amethyst_derive
- [ ] amethyst_gltf
- [ ] amethyst_input
- [ ] amethyst_locale
- [ ] amethyst_network
- [ ] amethyst_renderer
- [ ] amethyst_ui
- [ ] amethyst_utils
