### ISSUE TITLE
Transform.scale does not handle negative values in DrawSprite

### ISSUE THREAD

**Issue by megapctr** [amethyst/amethyst#909]
If I take an entity with a `Transform` component and set `transform.scale.x` to a negative value, the sprite should be flipped vertically. Instead, the sprite disappears.

![gif](https://user-images.githubusercontent.com/4096683/44591062-9f197e00-a7b4-11e8-9696-0ada7f006a7e.gif)

**Comment by jojolepro** [comment]
Isn't that flipping the normal (aka facing direction).
Normally I think we have culling enabled by defaults, which removes inverted normals.

**Comment by Moxinilian** [comment]
Well the issue is that behavior is inconsistent. Setting a camera's scale to a negative value flips, whereas on a sprite it makes it disappear. I think the expected default is to flip.

**Comment by megapctr** [comment]
One workaround would be to set `flip_horizontal = true` in the `SpriteRender` component

**Comment by Rhuagh** [comment]
Doubtful, this looks like winit or lower tbh.

**Comment by Moxinilian** [comment]
As soon as #925 is merged, could you please try again to see if your issue is fixed?

**Comment by Rhuagh** [comment]
Merged now.

**Comment by megapctr** [comment]
It's fixed, thanks!
