### ISSUE TITLE
Debug lines

### ISSUE THREAD

**Issue by Aceeri** [amethyst/amethyst#917]
Just would be nice to have a quick system for adding debugging lines in 2d/3d.

**Comment by Moxinilian** [comment]
I extremely support this one.
It would be extremely good to be able to draw a unit grid for the isometric transforms to help with setting things up.

**Comment by khskarl** [comment]
I will be taking this issue.

The plan is to feed positions and other properties into a geometry shader to efficiently generate multiple smooth lines, all of this in a final pass considering the depth buffer for proper occlusion.

**Comment by khskarl** [comment]
I guess this can be closed as #957 has been merged.

**Comment by jojolepro** [comment]
yes thanks!
