### ISSUE TITLE
Docs: Example in the book invalid in most cases

### ISSUE THREAD

**Issue by Telzhaak** [amethyst/amethyst#918]
The example regarding ActiveCamera is out of date:
https://www.amethyst.rs/book/develop/concepts/system.html#getting-a-component-of-a-specific-entity

It can panic, because no ActiveCamera Resource is found,

**Comment by Moxinilian** [comment]
While the example is correct, ActiveCamera is most of the time not populated so its use should be discouraged.
This example should be replaced by something else. Please note that it should not be changed to a join over the camera component and transforms, as at that point in the tutorial the join method has not been introduced yet.
