### ISSUE TITLE
Follow Camera using Parent -> PlayerEntity can lead to difficult to track error

### ISSUE THREAD

**Issue by Telzhaak** [amethyst/amethyst#919]
Scenario:
- Renderer pipeline with SpritePass
- Camera with Player as Parent, so that it should follow the parent's transform

Result:
-Panic at runtime on https://github.com/amethyst/amethyst/blob/690acabf6c578896280673e6273472cd6117d94c/amethyst_renderer/src/pass/util.rs#L252 according to @Moxinilian 

Reason: 
- Player Z gets copied, too, therefore Camera is on the same Plane as the PlayerSprite/Sprites,  
leading to the View matrix of the Global Transform becoming singular/non-invertable

Amethyst 0.8.0 + SpriteRender:
```
[dependencies]
shred = { version = "0.7.0", features =["nightly"]}
amethyst = { git = "https://github.com/amethyst/amethyst", rev = "44c87a512cacbbfd774433bd6f6d935ed97b6c0d", features = ["nightly"]}
```

Example:
```rust
let pipe = Pipeline::build()
        .with_stage(
            Stage::with_backbuffer()
                .clear_target([0.0, 0.0, 0.2, 1.0], 1.0)
                .with_pass(DrawSprite::new()),
        );

let game_data = GameDataBuilder::default()
        .with_bundle(InputBundle::<String, String>::new()
            .with_bindings_from_file(
                &keybindings_path
            )?,
        )?
        .with_bundle(
            TransformBundle::new()
                .with_dep(&["position_mapping_system"])
        )?
        .with_bundle(
            RenderBundle::new(
                pipe, 
                Some(config)
            )
            .with_sprite_sheet_processor()
        )?;
```

```rust
let player_entity = world
            .create_entity()
                .with(
                    sprite_render
                )
                .with(
                    GlobalTransform::default()
                )
                .with(
                    Transform::default()
                )
            .build());

 world
        .create_entity()
            .with(
                Camera::from(
                    Projection::orthographic(
                        0.0,
                        100,
                        100,
                        0.0,
                    )
                )
            )
            .with(
                GlobalTransform(
                    Matrix4::from_translation(
                        Vector3::new(
                            0.0, 0.0, 1.0
                        )
                    ).into()
                )
            )
            .with(
                Parent{
                    entity: player_entity,
                }
            )
            .with(
                Transform::default()
            )
        .build(); 
```

**Comment by Rhuagh** [comment]
The actual panic is here: https://github.com/amethyst/amethyst/blob/690acabf6c578896280673e6273472cd6117d94c/amethyst_renderer/src/pass/util.rs#L248

**Comment by jojolepro** [comment]
Sorry I skipped that issue. Try changing the Transform on the camera entity to have z=10. This way it will always be offset from the player depth

**Comment by jojolepro** [comment]
Did you try? (Changing Transform on the camera entity, not GlobalTransform)

**Comment by Telzhaak** [comment]
I am not using the parent-think anymore, and just a fixed offset by 10 (incidentally).
Instead i wrote a system that just copies the x and y translation of the player each frame, works good enough for me

**Comment by jojolepro** [comment]
We'll keep this issue around to remember to make an example using a follow camera using the way I suggested, to help new developers figure out how it should be done to avoid such panic.

**Comment by jojolepro** [comment]
Task: Create an example showing that to have the camera follow a 2d entity, the camera must have the Parent component pointing to the followed entity. The camera must have a Transform with a non-zero z offset value.

**Comment by torkleyy** [comment]
The engine should not panic in the first place.

**Comment by halfbro** [comment]
I can work on an example for this, I might check out the panic as well.

**Comment by andrewhalle** [comment]
I believe this issue can be closed.

**Comment by Moxinilian** [comment]
It can indeed!
Thanks everyone!
