### ISSUE TITLE
Hello World sample doesnt work

### ISSUE THREAD

**Issue by jcbritobr** [amethyst/amethyst#922]
Hello,
Im trying some sample code, and notice that hello world example don't compile.
The root cause is that the EmptyState and EmptyTrans traits doesn't existis in last amethyst framework.

```
extern crate amethyst;

use amethyst::prelude::*;

struct Example;

impl EmptyState for Example {
    fn on_start(&mut self, _: StateData<()>) {
        println!("Begin");
    }

    fn on_stop(&mut self, _:StateData<()>) {
        println!("End");
    }

    fn update(&mut self, _:StateData<()>) -> EmptyTrans {
        println!("Hello from Amethyst!");
        Trans::Quit
    }
}

fn main() {
    amethyst::start_logger(Default::default());
    let mut game = Application::new("./", Example, ()).expect("Fatal error");
    game.run();
}

```
error[E0405]: cannot find trait `EmptyState` in this scope
 --> src/main.rs:8:6
  |
8 | impl EmptyState for Example {
  |      ^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `EmptyTrans` in this scope
  --> src/main.rs:17:46
   |
17 |     fn update(&mut self, _:StateData<()>) -> EmptyTrans {
   |                                              ^^^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `EmptyState` in this scope
 --> src/main.rs:8:6
  |
8 | impl EmptyState for Example {
  |      ^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `EmptyTrans` in this scope
  --> src/main.rs:17:46
   |
17 |     fn update(&mut self, _:StateData<()>) -> EmptyTrans {
   |                                              ^^^^^^^^^^ not found in this scope

error: aborting due to 2 previous errors

Some errors occurred: E0405, E0412.
For more information about an error, try `rustc --explain E0405`.
error: aborting due to 2 previous errors

Some errors occurred: E0405, E0412.
For more information about an error, try `rustc --explain E0405`.
error: Could not compile `amethyst_test`.
warning: build failed, waiting for other jobs to finish...
error: Could not compile `amethyst_test`.

**Comment by Moxinilian** [comment]
You're looking at the develop branch here, which corresponds to the next unreleased version of the engine.
Try switching GitHub to the master branch to see examples for the latest version.

**Comment by jcbritobr** [comment]
You're right. What we can do now? Make this issue opened, and setup the default branch to master, or close it?

**Comment by Moxinilian** [comment]
Having develop be the default branch avoids contributors from trying to PR into master.
The best way to access examples is from the website. There's not much else we can do unfortunately.
I'm closing the issue.

**Comment by OvermindDL1** [comment]
Isn't master supposed to be the 'master' development branch, and either side-branches or tags named with the version supposed to corresponding to specific released versions?

**Comment by LucioFranco** [comment]
@OvermindDL1 probably should be like that, but originally we had a lot of churn, so master was to resemble *stable* code and develop was to represent unstable code. I am all for changing how we do that now though since we have a lot more stable code and it is more friendly.

cc @jojolepro @Moxinilian @Xaeroxe

**Comment by jojolepro** [comment]
Master: latest release + some doc fixes
Develop: where we develop stuff
v0.8: 0.8 release
v0.7 ......
trying & staging: reserved for bors bot

**Comment by OvermindDL1** [comment]
> but originally we had a lot of churn, so master was to resemble stable code and develop was to represent unstable code.

Lol, I've never seen that style...  This is what I've always seen and done myself as well:

master:  Currently 'tested' code, who knows if it's stable but generally assumed to mostly work
vx.y.z:  Specifically released version branched from master at the time of release (optionally a tag could be used for this, but branches allow for post-release updates more easily)
<any-other-branch-name>: A Development branch for a specific feature before it gets merged into master upon completion of the feature.

Having master as the latest release is really *really* weird, never seen that before and it's highly confusing for anyone coming here.  Having 'develop' act as master is also very odd as it's a highly non-standard name.  Generally unversioned branches are feature(-or-bugfix)-development branches, thus a branch named 'develop' would be expected to be some feature development branch for some feature named 'develop'.  So it is definitely non-standard git usage by far and is confusing for people coming here as they'd by default be PR'ing to master as almost every-single-git tool defaults to that (not like many people PR through the web interface so whatever it defaults to is not that useful).
