### ISSUE TITLE
Move back to only master branch

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/amethyst#924]
Originally we had decided to use a develop branch and a master branch due to high code churn. Now that the engine is more stable I suggest we move back to a master only situation, where `staging` and `trying` are reserved for @bors[bot]. This would mean stable and released code would be found under  the release tag in github releases which will correspond with crates.io releases.

Things that need to change to support this:
- [x] Merge develop into master, remove develop and set master as the main branch for the repo.
  - [x] Verify that travis config works without a develop branch
  - [x] Verify that appveyor config works without develop branch (even though we don't use it at the moment we still want to keep the config consistent)
  - [x] Verify bors works without a develop branch
  - [x] Make sure all new PR's are open vs master and all previous PR's get merged into develop before it gets deleted.
- [x] Remove references to the `develop` branch in the main repo
  - [x] Book
  - [x] Readme
  - [x] Contributing guideline
- [x] Remove referenes on the amethyst/website repo
  - [x] Change the docs page

## Questions

~Should we remove `release-x.x` branches and just leave releases to git tags?~

cc @amethyst/engine-devs

**Comment by Xaeroxe** [comment]
> Should we remove release-x.x branches and just leave releases to git tags?

No, because these are very important for patch releases.  Maintaining the ability to diverge code for old releases is very important.

**Comment by LucioFranco** [comment]
@Xaeroxe great point, I like the ability to apply *hotfixes* in a sense. 👍

**Comment by OvermindDL1** [comment]
> No, because these are very important for patch releases. Maintaining the ability to diverge code for old releases is essential for fixing high priority bugs in older versions.

I entirely agree here.  Although some projects use just tags to mark releases, that means applying patches to them is more difficult, where always generating a release (and tagging it too) allows for future patches far more easily and consistently so I always vote for release branches.

**Comment by Rhuagh** [comment]
@Xaeroxe I would suggest only creating those branches on need, i.e. when a patch release needs to be done. Branching from a tag isn't that hard.

**Comment by LucioFranco** [comment]
@Rhuagh right, but then we have branches that exist just for minor fixes instead of branches that exist for that release and any minor changes that need to come after its release?

**Comment by Xaeroxe** [comment]
@Rhuagh Yeah that's a good point.  I suppose thanks to the power of git thinking ahead that much isn't necessary and might just be creating extra work for us.

Most releases historically haven't needed patch releases, so perhaps it's better to start with the assumption they won't be necessary.

**Comment by OvermindDL1** [comment]
That's why releases should be branched on `x.y` releases but tags exist for `x.y.z` releases.  Say something can track the branch on the `x.y` version then they get all updates for all `x.y.z` automatically without needing to change tags, and thus that is why branches should always exist.

**Comment by Xaeroxe** [comment]
our code is usually distributed downstream via cargo rather than git, so it'd more or less only be useful to those of us directly in the Amethyst organization and collaborators.  I could see it being helpful, but is it more helpful than it is a pain to maintain?

As the person who's coordinated most of the recent releases for this project I'm going to go ahead and say I'd rather skip the branch creation and instead do it if and when we do our first patch release.

**Comment by LucioFranco** [comment]
@Xaeroxe I agree, I don't think especially at this stage of pre 1.0 that we will hotfix things but instead tell users to generally move to the new versions.

So the new branching and release scheme will be to *ONLY* tag the commit for that release and release it via cargo. No new branches etc.

**Comment by jojolepro** [comment]
I'd keep the release branches personally. Otherwise :+1:

**Comment by OvermindDL1** [comment]
Don't forget that that includes PR's to it.  You can't PR an emergency bugfix to a tag, but you can to a branch.

**Comment by LucioFranco** [comment]
@jojolepro @OvermindDL1 Well I do agree with you guys, I don't think its needed right now. We are still pre 1.0, the likely hood of needing to emergency bugfix is extremely low. So the benefit vs the cost to me at least doesn't make much sense.

**Comment by OvermindDL1** [comment]
Cannot overstate how useful it is to get in to the habit 'now' though.  ;-)

**Comment by jojolepro** [comment]
What cost? The release branches are just sitting there doing nothing, and making one actually takes 1 full minute.

**Comment by Rhuagh** [comment]
The cost would be that anyone that does pull or fetch on the main fork will always get those branches, while tags are only fetched if you supply --tags.

**Comment by OvermindDL1** [comment]
> The cost would be that anyone that does pull or fetch on the main fork will always get those branches, while tags are only fetched if you supply --tags.

No they won't?  You only get the branches that are requested, which by default is just `master`?  o.O?

**Comment by jojolepro** [comment]
No when you `git fetch`. It pulls the git history of all branches I think. Not that the git metadata is that heavy

**Comment by OvermindDL1** [comment]
> No when you `git fetch`. It pulls the git history of all branches I think. Not that the git metadata is that heavy

That's `git-fetch` though, it is designed to grab *everything*, most people will just clone though.

**Comment by kvark** [comment]
I've been using the minor release branches on multiple projects for quite a while. My conclusion (and recommendation) is: if you already agree to tag releases, then only create branches temporarily (from the tags or master). No reason for them to hang out.

**Comment by Rhuagh** [comment]
@OvermindDL1 yes, but if you're a contributor you will need to fetch atleast one for every PR you perform, so you can rebase it onto the latest development branch. git pull will also pull all the metadata for all branches, it just won't tell you it's doing it. You can see this by pulling in a branch, then swapping to a different branch, at which point it will tell you that you're "3 commits behind", hence it's got metadata about that branch from origin.

**Comment by Rhuagh** [comment]
And it's not about it being "heavy" for the amount of data, it's about cognitive load and clutter.

**Comment by OvermindDL1** [comment]
> at which point it will tell you that you're "3 commits behind"

Huh?  I've never seen that message in `git`?

> it's about cognitive load and clutter.

Can you elaborate on this?  I'm not sure I've experienced it (and I've worked on *much* larger projects).

**Comment by jojolepro** [comment]
@LucioFranco we already did for the documentation on the master branch. If we move develop to master, and master to dedicated release branches, we'll still be able to do those doc updates. We wouldn't have nearly as many people in the discord if we weren't fixing things so fast the first week after the 0.8 release.

**Comment by jojolepro** [comment]
When we move the master branch we should do a 0.8.1 branch to keep the doc changes somewhere for that old version.

**Comment by Moxinilian** [comment]
Didn't you update release-0.8 for the doc changes?

**Comment by jojolepro** [comment]
no, only master :joy:

**Comment by LucioFranco** [comment]
@jojolepro right but that was a patch to the current release, not a previous release. So still doesn't make sense to add a bunch of release branches that we will never update. I really doubt we will need to add doc fixes to 0.7 or 0.6 etc

**Comment by Moxinilian** [comment]
We should not make it look like we support older Amethyst versions. It's important that people stay up to date as much as possible.

**Comment by LucioFranco** [comment]
@Moxinilian agreed. I think for major versions its fine but that won't happen for a while aka hitting 2.0.

So as of right now, that strategy will be like this. Releases will create a tag off of a commit that exists on master. No release branch.

**Comment by kvark** [comment]
I'm afraid this is also unrealistic. You can't release 1.0 until you know for sure that the right API is provided, and the only way to get there is to have lots and lots of external use of the engine. Having people using different pre-1.0 breaking versions is inevitable in this situation. And I wouldn't even talk about 1.0 until there is a handful of happy clients.

**Comment by randomPoison** [comment]
I'm in favor of not keeping release branch around (and use tags instead) primarily because it causes a lot of clutter when using a git GUI. Most GUIs I've used list all the branches by default. The branches list for Amethyst is already cluttered and will only get more so as more releases are added.

![amethyst-branches](https://user-images.githubusercontent.com/1900829/44871987-feb2d600-ac59-11e8-9c5e-d7ee353c0d69.PNG)

Keeping the list of branches short makes it a bit more friendly for new contributors to work with the repo.

**Comment by Rhuagh** [comment]
So you've never seen this?:

```
opardum:rhusics simon$ git status
On branch feature/gravity-and-damping
Your branch is up to date with 'origin/feature/gravity-and-damping'.
opardum:rhusics simon$ git pull
gitremote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From https://github.com/rustgd/rhusics
   2620364..07ad358  master     -> origin/master
   2620364..07ad358  staging    -> origin/staging
Your configuration specifies to merge with the ref 'refs/heads/feature/gravity-and-damping'
from the remote, but no such ref was fetched.
opardum:rhusics simon$ git checkout master
Switched to branch 'master'
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
opardum:rhusics simon$
```

**Comment by LucioFranco** [comment]
Gonna give this a few more days till we make a final decision so if anyone has other concerns please voice them now. Thanks.

**Comment by LucioFranco** [comment]
Since, no one has voiced anymore concerns I am going to move forward with the proposed solution.

@Moxinilian would you be able to take charge on fixing the website and I can do the rest on the main repo?

If anyone else would like to help out please let me know, could def use some help on this 😄 .

**Comment by jojolepro** [comment]
I'd try to get the current pr merged first before that to limit how much breaks

**Comment by torkleyy** [comment]
If the released version has a bug and you want to fix it, how are you going to do that with only a master branch? You can't ask people to e.g. adopt the new renderer and depend on develop to have their bug fixed.

**Comment by kvark** [comment]
@torkleyy you take the tag of the version to patch, you branch off the tag, make a PR, merge it, make a new tag and publish. No need to force people on the newest version.

**Comment by LucioFranco** [comment]
All tasks have been done, and `master` is now the default branch. This can be closed.
