### ISSUE TITLE
Keyboard input causes application to freeze

### ISSUE THREAD

**Issue by michaelmelanson** [amethyst/amethyst#931]
I ran into an issue in my game where keyboard input causes the app to freeze and beachball. I have created a reduction of the issue in a fresh project. 

[amethyst-freeze.zip](https://github.com/amethyst/amethyst/files/2346007/amethyst-freeze.zip)

To reproduce the issue:

1. `cargo +nightly run`
2. Press any keys for a few seconds.

You should see the app window freeze after ~5 seconds. I have only tried to reproduce the issue on OS X.

By stopping the app in `lldb` it seems that the event loop gets stuck handling the keyboard events. I see that the list of `pending_events` has several (~8) keyboard events. I originally thought it may be a deadlock in `winit', since stopping it while it's frozen usually catches it while it's locking a mutex. But that doesn't seem to be the case: stepping forward from there shows it continuing to process events seemingly-okay...

Mouse input, or other kinds of window events, seem to not trigger the freeze.

The reduction is a simple skeleton Amethyst project -- about the simplest there is -- so I assume that I'm doing something wrong, but it's really unclear what that could be. 🤷‍♂️

Thanks for the help.

**Comment by omni-viral** [comment]
How exactly can I see if it freeze when there is nothing happens at all?

**Comment by michaelmelanson** [comment]
On OS X you should see the mouse cursor change to a beach ball / pinwheel. It should also stop responding to the Escape key to close the window.

**Comment by omni-viral** [comment]
Can't reproduce 🤷‍♂️

**Comment by michaelmelanson** [comment]
Okay I have more information: it only reproduces for me on Rust nightly. On Rust stable, it doesn't freeze.

Can you try to reproduce with `cargo +nightly run` instead?

**Comment by michaelmelanson** [comment]
It's definitely a Rust issue, and moreover it's been fixed (I was using an outdated nightly):

1. `cargo +nightly-2018-08-19 run` ❌ freezes
2. `cargo +nightly-2018-08-24 run` ✅ works fine

I'll resolve the issue.
