### ISSUE TITLE
Application inspired by examples can't access some private mods

### ISSUE THREAD

**Issue by fabiao** [amethyst/amethyst#936]
I'm trying to compile an application based on sprites example and some mod are private so I can't access directly some functionality. I forked project and I prepared a PR if this can help to extend sprite engines.
My fork/branch URL: https://github.com/fabiao/amethyst/tree/fix_sprites_example

**Comment by jojolepro** [comment]
Which types were you trying to access and couldn't?

**Comment by fabiao** [comment]
amethyst::renderer::SpriteRender
amethyst_animation::SpriteRenderChannel
amethyst_animation::SpriteRenderPrimitive
amethyst::renderer::SpriteSheetSet
amethyst::renderer::TextureCoordinates
amethyst::renderer::DrawSprite
amethyst::state::SimpleState

**Comment by jojolepro** [comment]
amethyst::SimpleState
DrawSprite reexported here from pass https://github.com/amethyst/amethyst/blob/develop/amethyst_renderer/src/lib.rs
amethyst::renderer::DrawSprite from external crates, amethyst_renderer::DrawSprite for internal amethyst crates and examples. Are you using master 0.8 or develop

**Comment by fabiao** [comment]
I was on master 0.8, just tried to update dependency with develop and all works fine. You could close issue, perhaps updating docs here: https://www.amethyst.rs/book/master/getting-started.html
specifing to add dependencies on develop branch

**Comment by kevlarr** [comment]
Just ran into this myself, basing off of the tutorial.. Why the difference between master 0.8 and develop?
