### ISSUE TITLE
Unsupported png format

### ISSUE THREAD

**Issue by jojolepro** [amethyst/amethyst#938]
The png images found here https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Cube/glTF cannot be loaded by the engine currently.

Stacktrace here https://gist.github.com/jojolepro/7444496769d19b752fb9333e29cc2eaf

**Comment by Valinora** [comment]
I'd like to take a look at this

**Comment by jojolepro** [comment]
https://github.com/jojolepro/hoppinworldv2

**Comment by jojolepro** [comment]
There is a lot of unrelated things in there. I suggest modifying the gltf example of amethyst.

**Comment by marciusvinicius** [comment]
@Valinora Are you current look this?

**Comment by Valinora** [comment]
@marciusvinicius I've been too busy, sorry

**Comment by marciusvinicius** [comment]
@Valinora I will try take a look, I'm a newbie here and I want something simple to start. thanks

**Comment by LucioFranco** [comment]
@marciusvinicius great, feel free to pop on discord if you need some help.

**Comment by jojolepro** [comment]
So an easy way to start would be to
* Clone amethyst
* Replace add this file in examples/assets/forgotthename
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Cube/glTF 
* Change the gltf example to point to that file.
* Change the gltf example to not use joints (main function->renderbundle->remove with_joint if its there)

**Comment by marciusvinicius** [comment]
Thanks @jojolepro I'm starting this today. hope I can fix it :D thanks for all supported

**Comment by jojolepro** [comment]
![image](https://user-images.githubusercontent.com/4755185/46376186-68603e80-c663-11e8-822c-bc30f152f8b1.png)

**Comment by jojolepro** [comment]
Not sure why, but the issue fixed itself. Thanks for checking it out :)

**Comment by marciusvinicius** [comment]
@jojolepro nice, Was nice, look the code, I'm understand better the amethyst now.

**Comment by Rhuagh** [comment]
My guess is that those pngs are progressive, which we didnt support before, but someone made a PR not that long ago for that.
