### ISSUE TITLE
Mapping MouseWheel to an Axis

### ISSUE THREAD

**Issue by yeliknewo** [amethyst/amethyst#939]
I am making a strategy game. I need to be able to zoom in and out with the mouse wheel. The current input system doesn't directly handle MouseWheel. My work around is to handle_event the MouseWheel and store the movement in a Resource.

**Comment by jojolepro** [comment]
this https://docs.rs/winit/0.17.2/winit/enum.MouseScrollDelta.html
needs to be added here https://github.com/amethyst/amethyst/blob/develop/amethyst_input/src/button.rs#L8
as well as the handling

**Comment by yeliknewo** [comment]
How hard would this be for me to implement?

**Comment by jojolepro** [comment]
Pretty easy. You add a variant in the second link of my comment for the event found in the first link, then you add a handling in amethyst_renderer/src/system (or renderer?)
that's all of it

**Comment by OvermindDL1** [comment]
Isn't a mousewheel effectively just more buttons in the OS?  I'm unsure how well that would map, especially as it 'clicks', like does it reset back to 0 when read once or...?

**Comment by magnonellie** [comment]
When using touchpads and similar the scroll is analog which I think most input systems have adapted at this point even for regular scroll wheels.

**Comment by OvermindDL1** [comment]
Internally the touchpads don't send an analog signal, since the OS doesn't work that way, rather it just translates it in to `keydown`/`keyup` messages, you can even listen for those and see.

**Comment by magnonellie** [comment]
Wayland would like to have a word with you: https://wayland.freedesktop.org/libinput/doc/latest/api/group__event__pointer.html#ga81ad7d8a95c456731a874e584c4c8dda 😝

**Comment by OvermindDL1** [comment]
Oooo wayland changed that?  I'm liking that.  Yep then I'm +1 on relative (not absolute) axis then.  :-)

**Comment by Xaeroxe** [comment]
Fixed in #991
