### ISSUE TITLE
HiDPI factor from winit update missed scaling UI

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#943]
When Winit was updated to `0.17`, the hidpi factor wasn't taken into account to scale UI components.

Symptoms:

* UI button in the middle of the screen is rendered further up and left, but clickable area is still in the middle.

This issue tracks the fix.

**Comment by jojolepro** [comment]
That was fix by @Xaeroxe fix right?

**Comment by jojolepro** [comment]
wrong button sorry azriel

**Comment by Xaeroxe** [comment]
Yes it was
