### ISSUE TITLE
pong example compile failed 

### ISSUE THREAD

**Issue by cloudfreexiao** [amethyst/amethyst#947]
I compile the pong example on Ubuntu failed On Win10 is ok 

error: failed to run custom build command for `alsa-sys v0.1.2`
process didn't exit successfully: `/home/cloudfreexiao/WorkSpace/RustWorkSpace/amethyst/target/debug/build/alsa-sys-f93a641c4082f0ed/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"alsa\"`: No such file or directory (os error 2)"', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by jojolepro** [comment]
From the readme:
Dependencies
If you are compiling on Linux make sure to install the following dependencies:
Ubuntu
$ sudo apt install libasound2-dev libx11-xcb-dev libssl-dev

If it still doesn't work after, let us know and we will reopen the issue.

**Comment by cloudfreexiao** [comment]
I have install the dependencies  the Ubuntu is virtual machine 
Is that the reason compile failed?

**Comment by jojolepro** [comment]
The error seems to be because you don't have alsa installed, but even if you would be able to compile the current renderer doesn't support virtual machines because it requires a physical gpu (or integrated gpu) to work properly. If you get it to compile it will complain about no virtual pixel format.
