### ISSUE TITLE
[v0.8.0] Pong tutorial issue with DrawSprite

### ISSUE THREAD

**Issue by botagar** [amethyst/amethyst#959]
Hello world!
I'm trying to follow the [pong tutorial](https://www.amethyst.rs/book/master/pong-tutorial/pong-tutorial-01.html) but I find myself stuck before even being able to pass the first page in said tutorial.

I use the amethyst tool to create a new project, replace the main.rs file contents with 
```
extern crate amethyst;

use amethyst::input::{is_close_requested, is_key_down};
use amethyst::prelude::*;
use amethyst::renderer::{DisplayConfig, DrawSprite, Event, Pipeline,
                         RenderBundle, Stage, VirtualKeyCode};
```
and I then cannot progress due to:
```
unresolved import `amethyst::renderer::DrawSprite`
no `DrawSprite` in `renderer`
```

I also tried jumping ahead a tiny bit and found that `SimpleState` is also missing
```
cannot find trait `SimpleState` in this scope
not found in this scope
```

Is something missing from the instructions or have i overlooked something? Any help would be appreciated!

System Info:
```
Operating System: Windows 8.1 64-bit
Language: English (Regional Setting: English)
Processor: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 CPUs), ~4.0GHz
Memory: 16384MB RAM
```

**Comment by vektah** [comment]
Those are the docs for `master`, try https://www.amethyst.rs/book/latest/pong-tutorial/pong-tutorial-01.html

**Comment by botagar** [comment]
Thanks. Does that mean the package published to cargo is not master?

**Comment by vektah** [comment]
I think there are some recent changes:

see #954 #924

**Comment by botagar** [comment]
I'm still rather confused. By those tickets, master should be pretty much be the latest and the docs linked to by the amethyst main site are master, but latest (which isnt a branch from what I can tell) is the version actually published? I can progress with the tutorial now so :smile: but the docs linked by the site point to something old.

Cheers~!

**Comment by Telzhaak** [comment]
`Latest` refers to the latest stable release on crates.io, currently version "0.8.0".
`Master` is the in-development version with major changes to sprite rendering and other stuff. It will basically end up as release "0.9.0" when the [milestone](https://github.com/amethyst/amethyst/milestone/5) is reached and everything works properly.

**Comment by botagar** [comment]
Thanks for clearing that up.
If you go to https://www.amethyst.rs/get-started/ and click on the examples link, you go to examples in the master branch which differs in functionality from what someone might get when adding amethyst="0.8.0" as a dependency and trying to follow along with the master branch examples (which is where i ran into trouble).

**Comment by Moxinilian** [comment]
amethyst/website#105 makes it clearer, and fixes the links on the Get Started page.
Thank you for your feedback!
