### ISSUE TITLE
[RFC] Officially deprecrate the Gitter chat

### ISSUE THREAD

**Issue by magnonellie** [amethyst/amethyst#961]
We currently link to both Gitter and Discord on various places as means of chatting, but the fact of the matter is that a most people within the Amethyst community simply don't use Gitter at all. We're usually encouraging people to move over to the Discord as that's where you can get the most help. Having the Gitter still open means that new people are gonna get a bad impression when they see the Gitter isn't all that active and they can't get answers to their help requests. I therefore think it would be a good decision to deprecate the Gitter and not link to it at all. Here's a rundown of the upsides and the downside I can think of:

Upsides:
- Less confused people
- Project won't be perceived as inactive
- Less fragmentation within the community
- Discord is a more common chat platform overall

Downside:
- Stupid companies are stupid and some block Discord without taking into account that it might actually be work related

**Comment by Moxinilian** [comment]
While I agree with the idea, I want to had another downside that some people (for some reason) prefer Gitter over Discord.
I really hate the fact that Discord is blocked by some however.

**Comment by jojolepro** [comment]
> While I agree with the idea, I want to had another downside that some people (for some reason) prefer Gitter over Discord.

@omni-viral

**Comment by Moxinilian** [comment]
"I want to had"
Jesus Christ

**Comment by erlend-sh** [comment]
As someone who makes a living consulting on community strategy I strongly support this.

The good thing is that you don’t need to irreversibly nuke Gitter right away. All of the goals of this RFC would be reasonably well achieved by:

- De-emphasizing any callouts to Gitter
- put up a banner/sticky (I assume they have something like this) on Gitter explaining that it’s in maintenance mode.

**Comment by omni-viral** [comment]
@jojolepro I don't prefer gitter, I'm just used to it. If everyone agree on dropping gitter channel in favor of discord, ok, no problem.

**Comment by LucioFranco** [comment]
I am all for this, *most because gitter doesn't have iPhone X support* 😠 . I agree with @erlend-sh's approach to this, we should give Gitter a period to depricate, this can be done by updating the description of all the channels. Another idea, is to delete all the channels but the main amethyst/general channel. This will force the use of one channel that we can then communicate accross to say that we are depricating gitter to move to discord. We could give gitter a few months before we offically delete the last channel, this way we can ensure everyone is using discord over gitter.

**Comment by torkleyy** [comment]
People seem to be in favour of this, I'm proposing to accept this RFC and to implement it by clearly stating, on all Gitter channels, that our official communication platform is Discord and not Gitter anymore. I don't think any further steps are necessary.

Please tick the box in front of your name to approve, comment to disapprove.

* [ ] @jojolepro 
* [ ] @Aceeri 
* [ ] @LucioFranco 
* [ ] @Xaeroxe 
* [ ] @Moxinilian 
* [ ] @omni-viral 
* [ ] @Rhuagh 
* [x] @torkleyy

**Comment by torkleyy** [comment]
:tada: This PR has been accepted :tada:

**Comment by torkleyy** [comment]
Implemented.
