### ISSUE TITLE
Support 3D mesh instancing

### ISSUE THREAD

**Issue by Moxinilian** [amethyst/amethyst#967]
Instancing of 3D meshes allows the drawing of multiple instances of the same mesh with one draw call. This is a necessary feature for 3D performance. Sprite batching has already been implemented for the 2D `DrawSprite` pass, so in the continuity of it, 3D passes should receive instancing.

Note: This should not be added to the current renderer, as its replacement is coming soon for 0.10. Instead, this will be part of the new renderer coming in 1.0. If you want to tackle this issue, please visit the Discord server where you will get all the information about contributing to the upcoming renderer.

**Comment by magnonellie** [comment]
The intention was to implement it for the current renderer, but then we kinda realized the new renderer isn't too far off, so I think everyone is putting their effort there :wink:

**Comment by Moxinilian** [comment]
3D instancing will definitely be in the new renderer, alongside a lot of other improvements to the 3D technology.

**Comment by Moxinilian** [comment]
@khskarl If you want to contribute to the new renderer, feel free to ping us on the Discord server!

**Comment by fhaynes** [comment]
Closing this. We'll put it on the roadmap if and when the new renderer is integrated.
