### ISSUE TITLE
Subscribing to component modifications (`FlaggedStorage` API)

### ISSUE THREAD

**Issue by torkleyy** [amethyst/amethyst#978]
_This issue discusses an overhaul of the current `FlaggedStorage` API that allows to get information about which components have been added, modified or removed. The current interface comes with several problems which are described in the following. Please note that while this is mostly about [Specs](https://github.com/slide-rs/specs), I've opened an issue here to get more attention and since this affects both internals and users of Amethyst quite a lot._

## The current API & how it works

From https://github.com/slide-rs/specs/blob/0ab563e86aff3968a23c0927cce9e2685fa88dac/examples/track.rs#L7-L37

```rust
struct TrackedComponent(u64);
impl Component for TrackedComponent {
    type Storage = FlaggedStorage<Self>;
}


struct SysA {
    modified_id: ReaderId<ModifiedFlag>,
    modified: BitSet,
}


impl SysA {
    fn new(world: &mut World) -> Self {
        let mut components = world.write_storage::<TrackedComponent>();
        let readerid = components.track_modified();
        SysA {
            modified_id: readerid,
            modified: BitSet::new(),
        }
    }
}


impl<'a> System<'a> for SysA {
    type SystemData = (Entities<'a>, ReadStorage<'a, TrackedComponent>);
    fn run(&mut self, (entities, tracked): Self::SystemData) {
        self.modified.clear();
        tracked.populate_modified(&mut self.modified_id, &mut self.modified);


        for (entity, _tracked, _) in (&entities, &tracked, &self.modified).join() {
            println!("modified: {:?}", entity);
        }
    }
}
```

So what you do is simply define the component with `type Storage `FlaggedStorage<Self>`;`, that allows subscribing to the events. Then, you create a reader id (which is now often done in `setup`) and store it in your system. In each `run`, you read out the events and you can e.g. store all modified entities in a bitset to iterate it at a later point.

Events are recorded in three different [`EventChannel`](https://docs.rs/shrev/1.0.1/shrev/struct.EventChannel.html)s:

From https://github.com/slide-rs/specs/blob/0ab563e86aff3968a23c0927cce9e2685fa88dac/src/storage/track.rs#L19-L34

```rust
/// All three types of tracked modifications to components.
pub struct TrackChannels {
    /// Modifications event channel.
    ///
    /// Note: This does not include insertions, only when a component is changed
    /// after it has been added to an entity.
    pub modify: EventChannel<ModifiedFlag>,
    /// Insertions event channel.
    ///
    /// Note: Insertion events only occur when something inserts a component without
    /// there being a pre-existing component. If there is a pre-existing component
    /// for an entity then it will fire a modification event.
    pub insert: EventChannel<InsertedFlag>,
    /// Removed event channel.
    pub remove: EventChannel<RemovedFlag>,
}
```

And populating them to the bitset is as simple as (from https://github.com/slide-rs/specs/blob/master/src/storage/track.rs#L79-L85):

```rust
    /// Reads events from the modified `EventChannel` and populates a structure using the events.
    pub fn populate_modified<E>(&self, reader_id: &mut ReaderId<ModifiedFlag>, value: &mut E)
    where
        E: Extend<Index>,
    {
        value.extend(self.modified().read(reader_id).map(|flag| *flag.as_ref()));
    }
```

where the bitset gets fed in as `value` and thus extended by all the ids read from the modification events.

Now this generally works great and was chosen because

* by using this event system, nobody misses an event, which would be the case with a simple `BitSet` (see Appendix A)
* you can only read the events you care about (either modification, insertion or removals), thus you get good access patterns

## Problems of the interface

A very common use-case is that you need to synchronize the components with another data structure. Let's say you wanted to keep track of how many components there are in the storage:

```rust
struct Sys {
    inserted: ReaderId,
    removed: ReaderId,
    cache0: BitSet,
    cache1: BitSet,
    count: usize,
}

impl<'a> System<'a> for Sys {
    type SystemData = ..;

    fn run(&mut self, ..) {
        self.cache0.clear();
        flagged_storage.populate_inserted(&mut self.inserted, &mut self.cache0);

        self.cache1.clear();
        flagged_Storage.populate_removed(&mut self.removed, &mut self.cache1);

        let new_count = (&self.cache0 & !&self.cache1).iter().count();
        println!("old: {}, new: {}", self.count, new_count);
        self.count = new_count;
    }
}
```

At a first glance, the above code might look fine (not optimal, but fine), but actually this has a major bug which can be triggered as follows:

* create entity A with our component
* run systems
* remove component from entity A
* re-add component to entity A
* run systems

This will generate one `Inserted` event and one `Removed` event. That means that even though there is a component again, the count will decrease because the bit becomes `0` after combining the two bit sets.

---

Now, we could try to take another approach:

Don't clear the bitset, but instead only keep one bit set and update it each frame:

> Note: obviously this example is stupid because we could just iterate the components and count them, but I think you get the point.

```rust
struct Sys {
    inserted: ReaderId,
    removed: ReaderId,
    components: BitSet,
    count: usize,
}

impl<'a> System<'a> for Sys {
    type SystemData = ..;

    fn run(&mut self, ..) {
        for RemovedFlag(index) in flagged_storage.removed().read(&mut self.removed) {
            self.components.remove(index);
        }

        flagged_storage.populate_inserted(&mut self.inserted, &mut self.components);

        let new_count = self.components.iter().count();
        println!("old: {}, new: {}", self.count, new_count);
        self.count = new_count;
    }
}
```

Besides requiring an extra for-loop from the user (that one could be fixed quite easily), this still has a bug; it's the exact reverse bug. We now add a bit if a component got first inserted and then removed, so the count will increase even though we removed the component again. That's because the remove gets processed before the insertions. We could switch both, but that would make our old bug appear again. The only way to fix this is the following:

```rust
struct Sys {
    inserted: ReaderId,
    removed: ReaderId,
    components: BitSet,
    count: usize,
}

impl<'a> System<'a> for Sys {
    type SystemData = ..;

    fn run(&mut self, ..) {
        for RemovedFlag(index) in flagged_storage.removed().read(&mut self.removed) {
            self.components.remove(index);
        }

        for InsertedFlag(index) in flagged_storage.inserted().read(&mut self.inserted) {
            if flagged_storage.mask().contains(index) {
                self.components.add(index);
            }
        }

        let new_count = self.components.iter().count();
        println!("old: {}, new: {}", self.count, new_count);
        self.count = new_count;
    }
}
```

> Note: Alternatively we could record the insertions into a `BitSet` and join it with the component storage, that would have the same effect but be more expensive.

Now, both cases should work just fine:

A) Insert -> Remove

The removals will run first, removing the (non-existent) bit from the set. Then, the insertion loop will run, but won't add the component because the storage's mask (bitset) doesn't contain the component anymore. :heavy_check_mark: 

B) Remove -> Insert

Again, removals will run first and will remove the bit for the component. Afterwards, the bit will be reinserted by the insertions loop because the mask will contain the bit for the component. :heavy_check_mark: 

So that's how it would be done correctly with the current API. It theoretically works, but is hard to understand and easy to get wrong.

## Problems of the implementation

Besides the API problems just listed, two other issues exist, although they're not that bad. I'm only going to list them here, an explanation is probably not necessary.

* the modification events can occur even though the component wasn't changed; this happens because every component that was retrieved mutably gets flagged as modified
* because every access of a component is recorded in the event channel, **parallel modification of the storage is not possible (`ParJoin`)**; this could be solved though by a workaround that flags them all at once, before they're joined over

### Solution A: Create a wrapping API that uses the current code to provide a convenient interface

Basically just implement the final solution presented in "Problems of the API" in a generic way, plus some other convenience methods. Suggestions how that API could be designed exactly are welcome.

Advantages:

* not too hard to implement
* we're still able to read the individual channels only

Disadvantages:

* unclear how such a higher-level API could cover all use-cases
* might be even more confusing in case we'd need to expose both low-level and high-level API
* additional wrapper APIs generally make the implementation less readable and harder to maintain

### Solution B: Merge all three channels so we know the order of the events

Instead of three `EventChannel`s for insertions, modifications and removals we'd have just one channel that receives an enum value:

```rust
pub enum ComponentEvent {
     Inserted(Index),
     Modified(Index),
     Removed(Index),
}
```

Advantages:

* easy to implement
* easy to understand and use

Disadvantages:

* worse access patterns if only insertions or only removals are relevant
* there still might be confusion that you need to check removals and insertions when you care about modifications (because insert -> remove should be handled as one)

---

More suggestions highly welcome! Please make sure to alphabetise them so we can refer to them more easily.

### A: Why a `BitSet` does not work

In short, there's some point at which you clear the `BitSet` and some point where the information needs to be read. As soon as between READ and CLEAR or between CLEAR and READ a WRITE happens, your reader will miss an event.

#### Example 1

* system A generates events
* system B reads the events
* system C generates events
* events get cleared

Problem: system B won't get to read the events C generated

#### Example 2

Easy enough, we can just clear them as soon as we read them!

* system A generates events
* system B reads the events
* events get cleared
* system C generates events

Problem: None :)

#### Example 3

The problem comes again when there are multiple readers:

* system A generates events
* system B reads the events
* events get cleared
* system C generates events
* system D reads events

Problem: system D will never get to read the events system A generated

---

This was the reason we decided a `BitSet` isn't enough. Even though there might situations where you can properly sync it by cleverly arranging systems or maybe maintaining two bitsets, that's too confusing and can lead to bugs that are hard to fix.

## References

* [PR that shows that the order of insertion and deletion cannot be trivially determined](https://github.com/slide-rs/specs/pull/463/files)
* [Users of Specs experiencing the issue and discussing possible solutions](https://github.com/slide-rs/specs/issues/361#issuecomment-388207131)
* [Usage of `FlaggedStorage` in `specs-hierarchy`](https://github.com/rustgd/specs-hierarchy/blob/master/src/lib.rs#L210-L400) (warning, very complex case)
* [`TransformSystem` using events](https://github.com/amethyst/amethyst/blob/master/amethyst_core/src/transform/systems.rs#L59-L127)

**Comment by Rhuagh** [comment]
Small side note, can we also change the events to carry the Entity, not just Index? That would help A LOT!

**Comment by WaDelma** [comment]
I would also be inclined to do option B as it seems cleaner.

When you would need to listen just one/some of the event types?

**Comment by torkleyy** [comment]
@WaDelma We have (/had?) one case where you placed a GLTF asset on an entity and a system would listen for those, delete the component and spawn all the required entities and components as children of that entity.

**Comment by Moxinilian** [comment]
I'd also like to note that the current API leaves a lot of burden on the user. Is there nothing we can do to make it simpler to use?

**Comment by torkleyy** [comment]
@Moxinilian I know, that's what I'd like to gather here.

We might be able to implement simple functions like `iter_modified`. Please post requests for methods here so I know what to implement.

**Comment by torkleyy** [comment]
@Rhuagh Actually, we cannot unfortunately. At least we cannot store entities, since `UnprotectedStorage`s only deal with `Index` and not `Entity`.

**Comment by Rhuagh** [comment]
@torkleyy i suspected as much :/

**Comment by jojolepro** [comment]
Voting for :b:

**Comment by azriel91** [comment]
`specs` was upgraded in #1122.
