### ISSUE TITLE
XR Support

### ISSUE THREAD

**Issue by dotellie** [amethyst/amethyst#990]
I realized we don't have a proper tracking issue for this so here it is.

We should have easy VR, AR and MR support in the engine. All of those have in common that they can have trackers of different kinds and that they track in real space although they do differ in a few areas. Initially, these will be implemented using vendor specific APIs, but the goal is to eventually move to a completely OpenXR based implementation.

## VR
VR requires the frame to be rendered at least twice. Preferably, you would also want a monitor output too which can either be done by rendering a third time or cheating by reusing the headsets view somehow. It should also be noted that VR can actually use more than two viewports for things such as wide FOV or a CAVE projection.

## AR
Admittedly, I'm not super familiar in this area, but from my very rudimentary understanding of it, what basically needs to happen is that you need to render your scene on top of a camera view with "true to life" lighting. Again, I haven't taken a deep look into this, so I may be missing something here. This is probably not gonna be implemented in the initial implementation.

## MR
This is basically the same as AR combined with the multiple viewports from VR but you don't render the camera. Instead you have a transparent background that you can see the real world through. This is definitely not gonna be implemented for a while since I don't have any MR capable devices and I suspect most other contributors here don't either.

**Comment by fhaynes** [comment]
Closing due to age and lack of activity and complexity. This is going to need to be decomposed and pieces put on the roadmap. Please open a thread on the forums for continued discussion.

**Comment by jojolepro** [comment]
A pull request exists here for those interested: https://github.com/amethyst/amethyst/pull/1413
